### ISSUE TITLE
Nintendont freezes screen when exiting a game

### ISSUE THREAD

**Issue by ronnieyip** [FIX94/Nintendont#1002]
When I exit a GameCube game by pressing the home button on the wiimote, the screen freezes and the wiimote shuts off. The Wiimote cannot be turned back on. To reset, I must hold down the system power button.

This behaviour only occurs if I launch Nintendont through USB loader GX. When I load a game using Nintendont through the homebrew channel, pressing the home button on the wiimote will exit the game back to the homebrew channel. This is my desired method of exiting a game when using USB loader GX. 

Is this a problem with Nintendont, USB loader GX, or HBC? Or is there a simple setting I'm missing?

Thank you!

**Comment by carnage702** [comment]
im guessing you start usbloader gx through a channel on the wii menu right?

Nintendont can only exit back to channels with full stubs so you would need a usbloader gx channel with a  full stub and now a fowarder.

**Comment by ronnieyip** [comment]
No, I load usbloader gx from hbc. It just seems weird as running Nintendont directly works fine.

**Comment by carnage702** [comment]
> No, I load usbloader gx from hbc. It just seems weird as running Nintendont directly works fine.

then its your usbloadergx version that is causing the issue, try to find another version or something.

**Comment by ronnieyip** [comment]
Thanks. I’ll follow up if I find a solution.

**Comment by ronnieyip** [comment]
As you suggested, I downgraded USB loader GX from v3.0 r1272 to r1271.

Now when I press the home button on the wiimote to exit out of Nintendont, the system does a reset to the warning/health and safety screen. This is obviously way better than having the system locking up. 

Thanks!
