### ISSUE TITLE
Pokemon Box Ruby & Sapphire adventure mode not working.

### ISSUE THREAD

**Issue by Shinigati** [FIX94/Nintendont#1005]
So all link cable functions work fine except for when you try to launch adventure mode all you get is the white splash screen, can deposit and withdraw pokemon just fine however.

**Comment by carnage702** [comment]
this is a know bug and there is already an issue open for this no need of a duplicate one.

**Comment by GB-CG** [comment]
@Shinigati See https://github.com/FIX94/Nintendont/issues/224
