### ISSUE TITLE
Pokemon Box black screen freeze

### ISSUE THREAD

**Issue by DBGreece** [FIX94/Nintendont#1006]
I am having a problem when I attempt to run the Pokemon Box Ruby & Sapphire (USA) game with Nintendont.
When I start the game it first shows me the Nintendo logo and trademark information, but instead of going to the title screen it ends up staying in a black screen and then playing an ear splitting noise.
I had an older version of Nintendont before and when I updated to 6.498 I got the game working past this once. Now however it is back to doing the same thing despite having worked within the last hour.
While this issue appears similar to "Pokémon Box: Freeze Glitch #221" in that the black screen and sound are the same, it is not happening on a specific function and is instead happening during the booting of the game.
I have all settings set to off or auto as they come normally except for native control set to on so that my GBA link cable will work.
I get the same result from both Wiiflow and from Nintendont directly.
I am just using a standard nkit.iso and when I checked the settings for the game it did say that it was not able to be MD5 verified due to not being a 1:1 dump of the game. Don't know if any of that information helps or not but trying to give all the info I can.

**Comment by carnage702** [comment]
use a 1:1 iso matching redump ... nkit is not officially supported at all
