### ISSUE TITLE
Help needed in Mario kart Double Dash!

### ISSUE THREAD

**Issue by Marioiscool312** [FIX94/Nintendont#1009]
I am playing with the Wii mote but I don't know which button drifts!?

**Comment by carnage702** [comment]
this is for issues not to ask for buttons...

wiimote + nunchuck wasnt made by the official nintendont devs it was added by a pull request, so i never tryed or know how it works i know there are alot of button combos to  use.

this is by far the worst control scheme you should invest in a classic controller or even better a gc controller, and if your wii or wiiu doesnt have gc ports you can use a switch/wiiu gc adapter even on the wii plus a gc controller.

to know more about wiimote+nunchuck stuff that was added to nintendont by pull request check this thread and ask questions there instead.

https://gbatemp.net/threads/nintendont-wiimote-nunchuck-support-discussions.371356/
