### ISSUE TITLE
Can't Create Memory Card File (Wii U VC Injector)

### ISSUE THREAD

**Issue by abcdeffghhi** [FIX94/Nintendont#1010]
Hello, when i try to use a game i injected with the Wii U VC Injector, it says it can't create a memory card file. I tried doing this on an SD card with more storage, but it came up with the same problem

**Comment by carnage702** [comment]
where does it says cant create memory card? 

Is your sd card unlocked?
do you have memory card emulation set to on in the settings?

**Comment by abcdeffghhi** [comment]
It say i cant load the card when i boot up the software

**Comment by carnage702** [comment]
take a picture of the message and post it here.
