### ISSUE TITLE
Support Multi Disc Game Filenames like Swiss

### ISSUE THREAD

**Issue by shefben** [FIX94/Nintendont#1011]
I tend to work on both wii and gamecube consoles alot for friends and stuff.
I have a central drive with all my backups for gamecube on it,

The issue is that swiss does not care what you name disc 1 or disc 2
but nintendont requires me to put both discs into a single folder and rename them game.iso and disc2.iso.

That means I cannot just copy/paste the backups, I need to manually dissect each folder for swiss if im working with gamecube

this naming convention sucks because having multiple folders on swiss show up on the list before the rest of the games is just plain ugly.

**Comment by carnage702** [comment]
nintendont is open source, you are free to change the code to whatever you want that doesn't look ugly to you.
