### ISSUE TITLE
(R + Z + B + D-Pad Down) combination not working for 8bitDo SN30Pro+ or other 8bitDo controllers

### ISSUE THREAD

**Issue by atmavan** [FIX94/Nintendont#1016]
(R + Z + B + D-Pad Down) combination not working for 8bitDo SN30Pro+ or other 8bitDo controllers

I can trigger reset only but I cannot shutdown emulator to exit to menu in order to run other games, I have to fully shut down Wii itself. For now any controllers config files found on Internet did not help.

Thank for advise.

**Comment by carnage702** [comment]
that is the exit for gc controller because they lack an home button,i dont own an 8bitdo controller but from what i see online the controller has 2 main button on the front one with three --- and one with two squares so one should be exit and the other start no?
