### ISSUE TITLE
Hyperkin procube

### ISSUE THREAD

**Issue by johnnywiiu** [FIX94/Nintendont#1017]
Sorry as this is almost certainly non associated with Nintendont but my Wii u won't accept the hyperkin procube and I've searched everywhere, the controller lights up and doesn't connect, I'm talking on the dashboard not in Nintendont

**Comment by spudpiggy** [comment]
The Wii U delivers less power than usual out of its USB ports - I think this is to save power but it's so terrible. USB hard drives need a y cable because of this.
Sounds like your controller needs more power than the Wii U supplies it.
