### ISSUE TITLE
Magic NS 2 Controller inputs not registering.

### ISSUE THREAD

**Issue by Unreal52** [FIX94/Nintendont#1018]
I have the Magic NS 2 adapter put in Dinput mode on the Wii U. I created a ini for the the controller with https://gbatemp.net/threads/mayflash-magic-ns-2-on-nintendont.615112/
and
https://github.com/FIX94/Nintendont/pull/851
I put the ini in the sd card, when in game certain inputs are not registering like Start and Y, I created the ini correctly but it still doesn't work. I'm on the latest version of nintendont. I tested the same game on Dolphin and it worked.

**Comment by Unreal52** [comment]
I changed the start button in the ini to a different button and it didn't work still.

**Comment by javisarms** [comment]
> I have the Magic NS 2 adapter put in Dinput mode on the Wii U. I created a ini for the the controller with https://gbatemp.net/threads/mayflash-magic-ns-2-on-nintendont.615112/
> and
> #851
> I put the ini in the sd card, when in game certain inputs are not registering like Start and Y, I created the ini correctly but it still doesn't work. I'm on the latest version of nintendont. I tested the same game on Dolphin and it worked.

Interesting. I don't have any problems on Dinput mode. If it's any help, I'm using a regular Wii.
