### ISSUE TITLE
(NTSC-U) Wrestlemania X8 chugs heavily during intro FMV

### ISSUE THREAD

**Issue by liftedterps** [FIX94/Nintendont#1022]
Game runs perfectly on disc through Wii System menu but chugs heavily during the intro FMV when running the game through Nintendont on multiple storage devices.
Tested on an SD card, HDD, and an SSD (all storage devices are FAT32 with 32KB clusters) for precautionary measures. 

Backup plays perfectly fine on Dolphin as well so it wasn't a bad dump.

**Comment by carnage702** [comment]
take a picture of your nintendont settings.

**Comment by liftedterps** [comment]
![20220820_142056](https://user-images.githubusercontent.com/111559023/185766399-b4700c65-354a-4684-9f5b-96d2ae007834.jpg)

those are my nintendont settings, my Wii is on IOS58 v24.32

**Comment by carnage702** [comment]
> ![20220820_142056](https://user-images.githubusercontent.com/111559023/185766399-b4700c65-354a-4684-9f5b-96d2ae007834.jpg)
> 
> those are my nintendont settings, my Wii is on IOS58 v24.32

try turning force progressive to off and video to auto.

if it still shuggs try unlocking read speed to yes.

**Comment by liftedterps** [comment]
Tried booting it up but Nintendont isn't working for me now at all for some reason, with no game at all. Just says
 "CheckForMultiGameAndRegion () failed: 1
  Unable to open the disc image file."

Tried from both my SD card and my HDD. My HDD is partitioned into two FAT32 drives though and the second partition is the one with the GameCube games so that could be one of the issues but they won't even boot from an SD card now.. Is it possible my Nintendont somehow got messed up?

**Comment by carnage702** [comment]
> Tried booting it up but Nintendont isn't working for me now at all for some reason, with no game at all. Just says "CheckForMultiGameAndRegion () failed: 1 Unable to open the disc image file."
> 
> Tried from both my SD card and my HDD. My HDD is partitioned into two FAT32 drives though and the second partition is the one with the GameCube games so that could be one of the issues but they won't even boot from an SD card now.. Is it possible my Nintendont somehow got messed up?

maybe your files got corrupted? try deleting your ninconfig.bin and any controller.ini on the root of usb/hdd and if it still doesnt solve anything maybe your iso went bad somehow.

**Comment by liftedterps** [comment]
I think some files might have indeed been corrupted, when I plugged it into my PC right now it said something about my drive needing to be scanned for errors. Replaced the corrupted ISO with a backup that works on dolphin and it now works again but it still chugs with the settings you recommended. 

Though what I just realized while playing both intro videos at the same time on dolphin and nintendont is that the video itself plays perfectly fine and in sync, it's basically just the audio streaming part that sounds like it's dying

**Comment by liftedterps** [comment]
Also just found out Nintendont apparently isn't able to read my FAT32 partition that I made for GameCube games. It will only read one FAT32 partion on an HDD not two of them. 
I messed up by making both of my partitions FAT32 and placing my GameCube games on the second partition instead of the first one.

**Comment by liftedterps** [comment]
So I will try my HDD once the transfer is over to see if it makes a difference on there

**Comment by liftedterps** [comment]
ok just got to trying it with both settings you recommended on an HDD and the audio still struggles pretty bad. pretty sure this can't be fixed either, since its just the sound

**Comment by carnage702** [comment]
> ok just got to trying it with both settings you recommended on an HDD and the audio still struggles pretty bad. pretty sure this can't be fixed either, since its just the sound

i just tried this and the audio doesnt struggle, struggle means the audio was unable to perform correctly do to cpu/gpu power  not being enough, this is an entirely different issue, the audio has some sort of static which probably means the game uses a very weird bit-rate/audio file structure and it does static, but not because its struggling , this isnt a speed issue, just a weird ass audio file/bit-rate crap not sure if it will ever be fixed since fix94 coded the audio streaming and he left long ago, not like it affects much of the game either since the game runs fine by itself.

**Comment by carnage702** [comment]
just tested the pal version and the sound works great there so there is that no idea why.

You can force pal version to videomode ntsc and forced progressive so you get the ntsc version basically with good  intro audio lol.

**Comment by liftedterps** [comment]
> > ok just got to trying it with both settings you recommended on an HDD and the audio still struggles pretty bad. pretty sure this can't be fixed either, since its just the sound
> 
> i just tried this and the audio doesnt struggle, struggle means the audio was unable to perform correctly do to cpu/gpu power not being enough, this is an entirely different issue, the audio has some sort of static which probably means the game uses a very weird bit-rate/audio file structure and it does static, but not because its struggling , this isnt a speed issue, just a weird ass audio file/bit-rate crap not sure if it will ever be fixed since fix94 coded the audio streaming and he left long ago, not like it affects much of the game either since the game runs fine by itself.

ahhh that makes a lot more sense. it did seem super odd that the video and the game itself ran flawlessly but the audio sounded possessed
