### ISSUE TITLE
Eternal Darkness [GEDP01] Freezes on Chapter 3

### ISSUE THREAD

**Issue by EchoSevenHotel** [FIX94/Nintendont#1025]
Once you collect the Tome of Eternal Darkness, and you pause the game, you go through the Magick tutorial.  Once you hit 'B' on Quick Spell, the game freezes.

I've tried 1:1 and Shrunk.

**Comment by carnage702** [comment]
take a picture of your nintendont settings.

**Comment by EchoSevenHotel** [comment]
Where would those be located?

**Comment by EchoSevenHotel** [comment]
> take a picture of your nintendont settings.

Where would those be located?

**Comment by carnage702** [comment]
> 

you got cheats on, are you using cheats? maybe turn that off also your not using memory card emulation? you are using a real memory card?also maybe turn off drive acess led too.

**Comment by EchoSevenHotel** [comment]
> > 
> 
> you got cheats on, are you using cheats? maybe turn that off also your not using memory card emulation? you are using a real memory card?also maybe turn off drive acess led too.

I tried all, except for the memory card, as I have a physical memory card, not sure how that would affect the freeze issue.  I'll work on converting the physical save to a virtual one, and see if that fixes it while enabling the Virtual Memory Card option.  Funny part is that I used Dolphin, and it gave me an error at that point, which I was able to bypass and move on.

**Comment by carnage702** [comment]
> > > 
> > 
> > 
> > you got cheats on, are you using cheats? maybe turn that off also your not using memory card emulation? you are using a real memory card?also maybe turn off drive acess led too.
> 
> I tried all, except for the memory card, as I have a physical memory card, not sure how that would affect the freeze issue. I'll work on converting the physical save to a virtual one, and see if that fixes it while enabling the Virtual Memory Card option. Funny part is that I used Dolphin, and it gave me an error at that point, which I was able to bypass and move on.

it could actually be a normal game bug or something, games did crash too even on original hardware, if you can then upload your save file and detailed instructions on how to trigger it so i can try it too, i never played the game so the instructions need to be step by step.

**Comment by EchoSevenHotel** [comment]
> > 
> 
> you got cheats on, are you using cheats? maybe turn that off also your not using memory card emulation? you are using a real memory card?also maybe turn off drive acess led too.

I'm thinking the gamesave may be corrupted.  I'll start fresh and see if that will work.  I'll keep you posted.

**Comment by EchoSevenHotel** [comment]
> > > 
> > 
> > 
> > you got cheats on, are you using cheats? maybe turn that off also your not using memory card emulation? you are using a real memory card?also maybe turn off drive acess led too.
> 
> I'm thinking the gamesave may be corrupted. I'll start fresh and see if that will work. I'll keep you posted.

I figured it out; the save was corrupted.  I deleted it, started a new one, and the issue no longer arises.  Thanks for bringing up the memory card.
