### ISSUE TITLE
Request NAS support

### ISSUE THREAD

**Issue by Coaleb2** [FIX94/Nintendont#1026]
I was thinking how nice it would be to implement some sort of nas support to use with the project https://github.com/danmons/retronas. Idk how difficult that would be to implement though. Just an idea I had that I thought might be a great addition to this already great project

**Comment by carnage702** [comment]
not gonna happen, the wii is already slow as is, let alone uploading save files to random servers,

**Comment by MisterSheeple** [comment]
I think it's worth noting that Swiss has support for the FSP protocol, which allows it to run games off of a server, such as a RetroNAS instance. If the GameCube can do this, then I don't see why the Wii can't; that is, unless additional memory limitations that come as a result of running a compatibility layer at the same time come into play somehow.

**Comment by drinksomewhiskey** [comment]
> not gonna happen, the wii is already slow as is, let alone uploading save files to random servers,

Is there any way to look into this? As mentioned in the prior comment, GC can support it and it would
Be great to have a similar ability on the Wii given how much more affordable it is.
