### ISSUE TITLE
Nintendont wont recongize my games

### ISSUE THREAD

**Issue by Eattherich3** [FIX94/Nintendont#1030]
I followed everything, it looks right, nintendont just only recognizes super Mario sunshine. They all have game.iso inside them. I'm using an original wii with GameCube support
![Screenshot 2022-09-18 132717](https://user-images.githubusercontent.com/77688028/190926977-4d60b01f-c72d-412d-9763-d5d3acf4f595.png)
![Screenshot 2022-09-18 132410](https://user-images.githubusercontent.com/77688028/190926886-8f3bd11f-2429-4734-81e3-5957e6c09977.png)
![Screenshot 2022-09-18 132328](https://user-images.githubusercontent.com/77688028/190926887-e2da7189-5b23-4595-92d1-db0e1efadd55.png)
![Screenshot 2022-09-18 132311](https://user-images.githubusercontent.com/77688028/190926888-88c78c9b-6815-4df1-9324-8f1bfa27be0c.png)

**Comment by carnage702** [comment]
are you sure you didnt acidentally named them game.iso.iso? if your pc is hidding extensions and you added.iso then its now iso.iso

**Comment by Eattherich3** [comment]
> are you sure you didnt acidentally named them game.iso.iso? if your pc is hidding extensions and you added.iso then its now iso.iso

I checked and extensions arent hidden

**Comment by carnage702** [comment]
> > are you sure you didnt acidentally named them game.iso.iso? if your pc is hidding extensions and you added.iso then its now iso.iso
> 
> I checked and extensions arent hidden

if the games arent showing up in the game list they they are hidden try to delete the .iso and leave the name of the file to only be "game"

**Comment by Eattherich3** [comment]
> > > are you sure you didnt acidentally named them game.iso.iso? if your pc is hidding extensions and you added.iso then its now iso.iso
> > 
> > 
> > I checked and extensions arent hidden
> 
> if the games arent showing up in the game list they they are hidden try to delete the .iso and leave the name of the file to only be "game"

I articulated that wrong. What I was trying to say is they are named correctly. I have 2 pictures attached, one with extensions turned on, and one with them turned off.
![Screenshot 2022-09-18 182517](https://user-images.githubusercontent.com/77688028/190937038-d0cbea2e-f32f-4989-96c3-ae96f052f893.png)
![Screenshot 2022-09-18 182353](https://user-images.githubusercontent.com/77688028/190937041-c6e3427e-65e1-4e0d-9631-a5a70e6f921a.png)

**Comment by Eattherich3** [comment]
Nvm. I downloaded some crappy roms that nintendont wont recognize.
