### ISSUE TITLE
Nintendont crashes after checking storage presents this message

### ISSUE THREAD

**Issue by Sunnyknightt** [FIX94/Nintendont#1032]
![20221018_054759](https://user-images.githubusercontent.com/76987129/196694120-6eaee10b-d9f5-42a0-8988-9cdd1c953b65.jpg)

Whenever I go to open Nintendont, it shows goes through the normal boot up sequence, and then aftereards gives this message and reboots back to the homebrew menu.

**Comment by carnage702** [comment]
never saw that message on my entire life, what nintendont version are you suing? it should say on the top corner of the menu(or you cant even reach the menu?)
