### ISSUE TITLE
Donkey Konga Native Controller - Turn off Wiimote to save battery?

### ISSUE THREAD

**Issue by coolspot18** [FIX94/Nintendont#1034]
Hi all,

Nintendont is loading and playing Donkey Kong fine with the Bongos, but is there a way to turn off the Wiimote to save battery? 

When using native controls for the Bongos, the remote remains on for the duration of the game, it doesn't enter sleep mode?

All 4 LEDs are lit up.

Thanks.

**Comment by carnage702** [comment]
if your wiimote has a nunchuck or classic controller it will stay on because its recognized as a valid controller, if you disconnect any extensions it should power off, if it doesnt you can always just take a battery out ...
