### ISSUE TITLE
Disney Sports - Skateboarding (NTSC-U) is crashing on stage selection screen

### ISSUE THREAD

**Issue by Maschell** [FIX94/Nintendont#1038]
The game crashes when you move the cursor to "Objectives" on the stage selection screen with latest nintendont version.

Got broken somewhere between 667b9cff2916b1632b90a782142ed855ae405819 and 142b6d3deed222e899f8a220d4c4768655af1559

**Comment by carnage702** [comment]
take a picture of your nintendont settings, and is your iso md5 checked?

**Comment by FlotterCodername** [comment]
Affects the redump ISO. It was discovered during a Twitch stream.

**Comment by Maschell** [comment]
I tested serveral nintendont version I could track it down to one commit.
The game works in 667b9cff2916b1632b90a782142ed855ae405819 (3.320) but in broken in 142b6d3deed222e899f8a220d4c4768655af1559 (3.321)

**Comment by carnage702** [comment]
fixed in nintendont 499 a timer patch was being applied where it shoudlnt be because by miracle everything matched.
