### ISSUE TITLE
Gamecube disc not loading

### ISSUE THREAD

**Issue by rodsthepeople** [FIX94/Nintendont#1044]
Hi!

When I try to run a Gamecube retail disc through Nintendon't it gets stucked on 'Loading, please wait...'. 
Also tried through USB loader GX and it got stucked on a black screen.

My Wii is compatible with Gamecube, and the game is working fine on Gamecube mode but I would like to play it using my Wii Classic Controller and without the need of a memory card. 
Game is 'Pokémon Colosseum', just in case.

Could anybody help me? :( 
Thanks in advance!

**Comment by carnage702** [comment]
take a picture of your nintendont settings.

**Comment by rodsthepeople** [comment]
> take a picture of your nintendont settings.

![CA095F75-EFDE-4B0A-AC00-9E4686C852FE](https://user-images.githubusercontent.com/117839115/200904516-245c2b29-f91d-4dff-a668-19abe7a3680b.jpeg)

**Comment by rodsthepeople** [comment]
> take a picture of your nintendont settings.

Adding some extra pictures to help you understand the issue:

![5825A92F-C4B9-4900-B789-5735385EBF3B](https://user-images.githubusercontent.com/117839115/200908114-541e7fce-d9fb-45a0-ac65-482785ac26f4.jpeg)
![F8487A87-2709-43CC-913A-6F2EC7D3C165](https://user-images.githubusercontent.com/117839115/200908195-f1f4bfc3-9619-4172-bed1-9ad56c968582.jpeg)

- Images showing that the disc is working normally on Gamecube mode

**Comment by rodsthepeople** [comment]
> take a picture of your nintendont settings.

![5811C5AC-3604-4216-B497-574AAE71B43C](https://user-images.githubusercontent.com/117839115/200908847-ed12f0d6-9f1b-4c38-b82a-59bf21765a1a.jpeg)

- Super Mario Sunshine iso is working normally too on Nintendon’t

![57F4987D-1D7D-44C1-8BD9-57C2CC290EFE](https://user-images.githubusercontent.com/117839115/200908943-3ddf1172-b74a-4c07-8a66-00fd1c318730.jpeg)

- That’s what happens when I try to boot the GC disk: it gets stuck on this screen forever.

**Comment by carnage702** [comment]
just wondering is nintendont on the sd card or usb? the app itself?

**Comment by rodsthepeople** [comment]
> just wondering is nintendont on the sd card or usb? the app itself?
> Did you ever hacked the gc mode? like dios mios or the likes?

- Nintendon’t is in the sd card
- Now that you said it, I’m not sure. I know I can boot GC isos, but it’s the first time that I tried to use Nintendon’t to play a GC retail disk. Could you please help me with this?

**Comment by carnage702** [comment]
> > just wondering is nintendont on the sd card or usb? the app itself?
> > Did you ever hacked the gc mode? like dios mios or the likes?
> 
>     * Nintendon’t is in the sd card
> 
>     * Now that you said it, I’m not sure. I know I can boot GC isos, but it’s the first time that I tried to use Nintendon’t to play a GC retail disk. Could you please help me with this?

im gonna try my wii first to make sure it works for me i got pokemon collosseum disk too  but pal version, just making sure your wii is stock wii right? you didnt use a wode to play backups or stuff like that and swapped out the disc drive?

**Comment by carnage702** [comment]
> > 
> 
> My wii is already hacked but I don’t remember if I hacked the GC mode. I’m not sure what a “wode” is, but the only thing I did on it was playing Wii games (either by original disks or isos) and Gamecube games (original disks or ISOs). The problem I’m facing is because I wanna play this game without the need of using the GC controller and memory cards and it gets stuck on that screen.

so i tried it nintendont on sd card and colosseum pal disc on my wii and everything worked fine you can see the video here
https://www.youtube.com/watch?v=DqJJdqX_QLE

So i got a couple of questions for you
1-when you click on boot disc  do you hear the wii disc drive making noises to read the disc?
2- if it makes noises does it stop making noises eventually?

A wode is hardware, basically opening the wii swapping the disc drive with a drive that reads everything  from burned to original discs and so on. if you only hacked the wii with only  some files on sd card and didnt chipped it or installed different physical components then you didnt use a wode, if you injected some custom mios(gc mode firmware) we might have to put the original mios back in place.

**Comment by rodsthepeople** [comment]
> > My wii is already hacked but I don’t remember if I hacked the GC mode. I’m not sure what a “wode” is, but the only thing I did on it was playing Wii games (either by original disks or isos) and Gamecube games (original disks or ISOs). The problem I’m facing is because I wanna play this game without the need of using the GC controller and memory cards and it gets stuck on that screen.
> 
> so i tried it nintendont on sd card and colosseum pal disc on my wii and everything worked fine you can see the video here https://www.youtube.com/watch?v=DqJJdqX_QLE
> 
> So i got a couple of questions for you 1-when you click on boot disc do you hear the wii disc drive making noises to read the disc? 2- if it makes noises does it stop making noises eventually?
> 
> A wode is hardware, basically opening the wii swapping the disc drive with a drive that reads everything from burned to original discs and so on. if you only hacked the wii with only some files on sd card and didnt chipped it or installed different physical components then you didnt use a wode, if you injected some custom mios(gc mode firmware) we might have to put the original mios back in place.

- Oh, got it now. I bought this Wii from another person and I believe the previous user did this “wode” thing since she said the console can read burned discs. If that’s the case, I will not be able to play the GC disk through Nintendon’t?

**Comment by carnage702** [comment]
> > > My wii is already hacked but I don’t remember if I hacked the GC mode. I’m not sure what a “wode” is, but the only thing I did on it was playing Wii games (either by original disks or isos) and Gamecube games (original disks or ISOs). The problem I’m facing is because I wanna play this game without the need of using the GC controller and memory cards and it gets stuck on that screen.
> > 
> > 
> > so i tried it nintendont on sd card and colosseum pal disc on my wii and everything worked fine you can see the video here https://www.youtube.com/watch?v=DqJJdqX_QLE
> > So i got a couple of questions for you 1-when you click on boot disc do you hear the wii disc drive making noises to read the disc? 2- if it makes noises does it stop making noises eventually?
> > A wode is hardware, basically opening the wii swapping the disc drive with a drive that reads everything from burned to original discs and so on. if you only hacked the wii with only some files on sd card and didnt chipped it or installed different physical components then you didnt use a wode, if you injected some custom mios(gc mode firmware) we might have to put the original mios back in place.
> 
>     * Oh, got it now. I bought this Wii from another person and I believe the previous user did this “wode” thing since she said the console can read burned discs. If that’s the case, I will not be able to play the GC disk through Nintendon’t?

if he did the wode then nope, nintendont cant access the wode, since its a different hardware and nintendont just isnt coded for that, what i recommend you if you still want to use emulated memory cards and controllers is get a colosseum  iso put it on the sd card and play it from sd card, nothing is lost.

**Comment by rodsthepeople** [comment]
> > > > My wii is already hacked but I don’t remember if I hacked the GC mode. I’m not sure what a “wode” is, but the only thing I did on it was playing Wii games (either by original disks or isos) and Gamecube games (original disks or ISOs). The problem I’m facing is because I wanna play this game without the need of using the GC controller and memory cards and it gets stuck on that screen.
> > > 
> > > 
> > > so i tried it nintendont on sd card and colosseum pal disc on my wii and everything worked fine you can see the video here https://www.youtube.com/watch?v=DqJJdqX_QLE
> > > So i got a couple of questions for you 1-when you click on boot disc do you hear the wii disc drive making noises to read the disc? 2- if it makes noises does it stop making noises eventually?
> > > A wode is hardware, basically opening the wii swapping the disc drive with a drive that reads everything from burned to original discs and so on. if you only hacked the wii with only some files on sd card and didnt chipped it or installed different physical components then you didnt use a wode, if you injected some custom mios(gc mode firmware) we might have to put the original mios back in place.
> > 
> > 
> > ```
> > * Oh, got it now. I bought this Wii from another person and I believe the previous user did this “wode” thing since she said the console can read burned discs. If that’s the case, I will not be able to play the GC disk through Nintendon’t?
> > ```
> 
> if he did the wode then nope, nintendont cant access the wode, since its a different hardware and nintendont just isnt coded for that, what i recommend you if you still want to use emulated memory cards and controllers is get a colosseum iso put it on the sd card and play it from sd card, nothing is lost.

Understood. Thank you for helping me out!
