### ISSUE TITLE
Force 240p [Feature request]

### ISSUE THREAD

**Issue by MisterFungii** [FIX94/Nintendont#1046]
I used to use Swiss, and I've always preferred the look of 240p on Gamecube games with my CRT TV. I use my Wii and Nintendont now, and I really miss the nice sharp, clean look of 240p Gamecube games. I was wondering how difficult it would be to add such a feature?

**Comment by carnage702** [comment]
this will never be added by nintendont team, nintendont already forces 480p which is superior,forcing 240p will be pretty  pointless for most people, nintendont is an open source project so you can code it yourself or find someone to code it for you and then do a pull request here.

**Comment by GB-CG** [comment]
Also duplicate of https://github.com/FIX94/Nintendont/issues/162

**Comment by smdstudios** [comment]
> already forces 480p which is superior
Not for games made for 240p like Resident Evil 2

**Comment by wolfmanvid01** [comment]
We need 240p. Not all CRTs we wanna use support 480p even if its the superior alternative!

**Comment by ismailbaisa** [comment]
+1 on 240p, really want to play on 240p especially for pixel art games and GBA if can.

**Comment by wolfmanvid01** [comment]
> this will never be added by nintendont team, nintendont already forces 480p which is superior,forcing 240p will be pretty pointless for most people, nintendont is an open source project so you can code it yourself or find someone to code it for you and then do a pull request here.

U dont know that CRTs are the retro bomb now??? 240p look beautiful on em, and lots of em dont support 480p or even component cables but they allow 240p thru composite
