### ISSUE TITLE
CC control not working correctly on GC games

### ISSUE THREAD

**Issue by neithan09** [FIX94/Nintendont#1048]
My clasic controller isnt working correctly on gamdcube games. Trying it on smash bros melee, all the menus work correctly but when starting a match the character just keeps using shield, so its pressing the l or r buttons and I cant find a way to stop it. This only happens in nintendont, doesnt happen anywhere else and I dont know why, Edit: also it seems like the r and l buttons do work when using the camera mode, its not like they are being pressed all the time its just always doing the shield when i try to play

**Comment by carnage702** [comment]
Is your controller official? If it's a fake/3rd party one then it's most likely the issue, nintendont is not garanteed to work with those at all.
