### ISSUE TITLE
Zelda Collectors Edition: Majora's Mask Save File Glitch

### ISSUE THREAD

**Issue by Foxero18** [FIX94/Nintendont#1050]
For some odd reason, after I beat the Ikana Temple (the 4th temple in the game), when I save and restart my console, the save file is back to a previous save file where I didn't even start the temple.
Is this a glitch?

**Comment by carnage702** [comment]
Did this happened multiple times or just one time? Are you sure you saved? What did you use to hold saves? Real memory card? SD? USB?

**Comment by Foxero18** [comment]
My game crashed and I saved before I went into the temple.
I did some research on the game itself.
I used the quick save in the game, and then played again, but apparently, doing that will erase the quick save.
So I will check tomorrow if it was "my fault" that the save file did this.
Really dumb how this game does the quick save method.
