### ISSUE TITLE
Plugging in Gamecube Controller Adapter disables Wii U Gamepad

### ISSUE THREAD

**Issue by NuclearMuffin** [FIX94/Nintendont#1051]
So I recently updated my version of Nintendon't on my Wii U... I've been using GCN injects on my Wii U through the Teconmoon VC Injector and everything used to work perfectly.  I could keep my GCN Controller Adapter plugged in and both the GCN controllers and Wii U Gamepad worked just fine when used at the same time.

Now however? Plugging in the GCN Controller Adapter completely disables all of the buttons on the Wii U Gamepad except for the Home button; even if I choose to use the Wii U Gamepad from the Wii U Menu.  This essentially makes the Wii U Gamepad completely useless; as I keep Wavebird receivers plugged into the GCN Controller Adapter at all times, and now the only way to restore the Wii U Gamepad's button/stick inputs is to remove the GCN Adapter from the USB port of the Wii U.  It seems that somewhere along the way, some sort of change has been made to how Nintendon't prioritises controller inputs? Surely the Wii U Gamepad should be considered the highest priority over GCN controllers? Can anything be done to make both the Wii U Gamepad and the GCN Controller Adapter usable at the same time again?

**Comment by carnage702** [comment]
this is no bug... wiiu gamepad is being pushed to player 2...


 before nintendont priority on controllers were

wiiugamepad<usb controllers<bt controllers

now is   usb controllers<wiiugamepad<bt controllers

wiiu gamepad has its own setting on nintendont menu called wiiu gamepad slot if you want the wiiu gamepad slot to be first just put 1 on that setting, and you can  keep your wiiu gc adapter plugged and keep the gc controller on slot 2 so slot 1 is free for wiiu gamepad.

**Comment by NuclearMuffin** [comment]
Thank you for the explanation.
