### ISSUE TITLE
Control de GameCube USB Generico  no esta mapeada el boton Z (wii)

### ISSUE THREAD

**Issue by SiclinCopito** [FIX94/Nintendont#1052]
Estoy jugando The Legend of Zelda Wind Waker con mi control de GC USB generico y no funciona el boton Z en la (WII).
¿Que puedo hacer para arreglarlo?
PD: el boton si funciona lo probe en Dolphin y si funciona solo que en Nintendont No
AYUDA URGENTEE!!!!!!!!

**Comment by carnage702** [comment]
If its a usb hid controller you must find a way to make and make your own controller.ini the button isnt mapped because your using an ini that was made for another controller that for luck is working with yours, so make your own controller.ini using hid test.

**Comment by SiclinCopito** [comment]
Como lo hago???

**Comment by carnage702** [comment]
> ¿Como lo hago??? ¿Es una app de pc o es una app de wii?

app de wii if you dont know how to do it then google it.

**Comment by SiclinCopito** [comment]
Hola chicos, ya arregle mi problema con la app de HIDTEST para wii identifique primero que valor de los botones eran.
Después, modifique el archivo controller.ini 
el botón predeterminado era así
Z= 6, 08
y yo lo cambie a este
Z= 6, 04
al principio no entendí que estaba pasando porque en el HIDTEST me decía que la Z era así 7 en vez del 6
pero lo arregle 
MUCHAS GRACIAS!!
