### ISSUE TITLE
Possible C0 Codetype Codehandler or Register Issue in Nintendont

### ISSUE THREAD

**Issue by ReclaimerShawn** [FIX94/Nintendont#1053]
So, I made a C0 Code for Pokemon Colosseum and attempted to load it via Nintendont (Nov 1, 2022 build, the latest build). The code works on Swiss without any problems, but immediately freezes the game on Nintendont. I haven't tried this code on any other builds of Nintendont.

I'm writing to two static addresses using a C0 Codetype, as I needed to do a few conditional checks and some operations I couldn't do with Gecko Codetypes alone. I've confirmed that the addresses I'm looking for are static and are the same both on Nintendont and on a real Gamecube (Swiss). The address are the X and Y coordinates of the player, and with those, I wanted to make a walk through walls code by adding 0x01000000 to a float address. It won't give exact float values, but it's enough for me to break through a wall. I use registers r9-r12 in my C0 Code, as those are generally safe registers for the C0 Codetype.

My guess is there's either something wrong with the codehandler in Nintendont concerning C0 Codetypes (as previously mentioned here: https://github.com/FIX94/Nintendont/issues/261#issuecomment-226688593) or registers r9-r12 are somehow being handled improperly in Nintendont. I've made another C0 Codetype for Pokemon XD and have used it on Nintendont with no problems, which makes me think the C0 Codetype isn't entirely bugged. Then again, that code only uses the r12 and r11 registers and not r9 or r10, which points me in the direction that the bug is related to how Nintendont handles registers. 

The code activates by going to the edges of the map and then clicking the directional pad in the direction of a wall to bust through it. This is the code I used for Pokemon Colosseum (NSTC-U, GC6E01) that freezes the game:

Walk Through Walls (Hold DPAD in a Direction)
C0000000 0000000F
3D808040 A18C1C28
3D60809E 3D40809E
3D200100 2C0C0008
41820020 2C0C0004
41820028 2C0C0002
41820030 2C0C0001
41820038 4E800020
814A52C4 7D495050
914B52C4 4E800020
814A52C4 7D4A4A14
914B52C4 4E800020
814A52BC 7D4A4A14
914B52BC 4E800020
814A52BC 7D495050
914B52BC 4E800020

**Comment by carnage702** [comment]
nintendont runs in wii mode swiss runs in gc mode, not all addresses are in the same place, this is the reason many cheats dont work on nintendont, some addresses we moved around because the wii os uses that area and the game crashed if it tried to read those areas ,as the values kept getting overwritten  so they arent in the same place.
