### ISSUE TITLE
Nintendont Mario Kart Double Dash LAN Black Screen

### ISSUE THREAD

**Issue by majuabir** [FIX94/Nintendont#1055]
Greetings. I'm trying to use the BBA Emulation feature. When I click LAN setup on MKDD's title, the screen goes to black and the menu music keeps playing. Mashing buttons and spinning sticks don't appear to do anything. Not even the reset button works, so I have to power off the Wii to exit it. I tried this with an nkit iso and a full 1:1 iso. I have tried Network Profile set to Auto and 2 (which is the profile chosen in the Wii settings). I'm trying to connect to Dolphin. The instructions said to make sure Dolphin look for consoles first, but that doesn't appear to do any difference. Any suggestions on what to do?

**Comment by majuabir** [comment]
update: I decided to clear all my connection settings, tried a wired connection on Connection 1 (which failed), went to Nintendont and set the Network Profile to 1, ran MKDD, picked LAN Mode, and now it's stuck on Establishing LAN Link screen. anything missing?

**Comment by majuabir** [comment]
Update: Dolphin just now decides to move to the "Looking for Gamecube systems" countdown screen

**Comment by majuabir** [comment]
Might be worth detailing what hardware and software I'm using:

Version 4.3E Wii
Nintendont v6.499
UGREEN ethernet adapter: https://www.amazon.com/dp/B00MYT481C?ref=ppx_yo2ov_dt_b_product_details&th=1
NETGEAR switch: https://www.amazon.com/dp/B07PFYM5MZ?psc=1&ref=ppx_yo2ov_dt_b_product_details
PC with Dolphin 5.0-17269

My ethernet switch has an ethernet cable coming in from my Wii, my PC, and a MOCA adapter which is connected to my router.

**Comment by carnage702** [comment]
I never actually tried to use this feature so I can't help much but from the reports over the years I can ask afew things

Is your router connected to the internet? If it isn't it won't work  

Second try another router, bit all routers worked, due to being an old connection type.

**Comment by majuabir** [comment]
Thanks for the response. I have a network switch that's connected to a router via a MOCA adapter and the router is connected to the internet. I assume I need to have a direct connection to the router instead which I can try.

**Comment by carnage702** [comment]
> Thanks for the response. I have a network switch that's connected to a router via a MOCA adapter and the router is connected to the internet. I assume I need to have a direct connection to the router instead which I can try. Also, what do you mean "bit all routers"?

that was a typo lol i meant "not all routers work" and yes try with a direct connection to the internet, i remember people saying without the router connected to the internet the wii didnt do the connected flag so  nintendont never got the connection flag from wii os.

**Comment by eku** [comment]
I can confirm that it works within the same subnet, as the Gamecube uses broadcast to find other consoles. And broadcast is, to my knowledge, not routed.

Try to sniff the network traffice on the PC side. Wireshark might be the right choice.

**Comment by carnage702** [comment]
so did it work for you?

**Comment by majuabir** [comment]
Sorry for not updating this. I haven't had a good moment to test this out just yet, but I'll make sure to update this thread when I do.

**Comment by carnage702** [comment]
> Bumping this. Playing on real hardware, Wii goes to black screen w/ menu music when lan mode is selected. If I disconnect the ethernet cable before hitting lan mode it goes to the next screen (although displaying an error because there's no connection) so it's definitely freezing. I've tried all the profiles (auto,1,2,3). None work. I have a real gamecube w/ a bba adapter in the other room connected to the same switch and it connects just fine. Surely this is a bug? Running on a pal system, pal copy of double dash, 60hz mode. Official wii lan adapter.

is the switch itself connected to the internet? for bba to work on the wii there has to be an actual internet connection.

**Comment by Kamon62** [comment]
> 
I eventually figured out there needed to be an active connection assigned in the wii menu, once that was done I was able to reach the lan setup screen. It was able to start searching for other systems but never found my gamecube. I figured it was because I had my gamecube connected through a separate switch that then connected to my router. So I simplified it by plugging them both into a basic switch, re setup the connection and tired again. This time setting it up on a connection without internet made it so that it could get to the lan screen but could never establish a lan link. So I went even more basic. No switch, crossover cable between the wii and my gamecube (Used this cable before with 2 gcs so I know it works) Once again it can't establish a link. Does the BBA emulation actually work like a lan adapter or only for online connectivity? Does the emulation demand that the connection has an internet connection?

**Comment by carnage702** [comment]
> > is the switch itself connected to the internet? for bba to work on the wii there has to be an actual internet connection.
> 
> I eventually figured out there needed to be an active connection assigned in the wii menu, once that was done I was able to reach the lan setup screen. It was able to start searching for other systems but never found my gamecube. I figured it was because I had my gamecube connected through a separate switch that then connected to my router. So I simplified it by plugging them both into a basic switch, re setup the connection and tired again. This time setting it up on a connection without internet made it so that it could get to the lan screen but could never establish a lan link. So I went even more basic. No switch, crossover cable between the wii and my gamecube (Used this cable before with 2 gcs so I know it works) Once again it can't establish a link. Does the BBA emulation actually work like a lan adapter or only for online connectivity? Does the emulation demand that the connection has an internet connection?

the wii requires to be  online to establish a connection, its the wii os that does that so just connect both your wii and gamecube to the router and that router has to have internet

**Comment by Kamon62** [comment]
> the wii requires to be online to establish a connection, its the wii os that does that so just connect both your wii and gamecube to the same router and that router has to have internet.

It does? This section from the readme has me a little confused:

> It works just like a real BBA and works from both a USB LAN adapter and over WLAN.
> To enable BBA Emulation, simply go into nintendonts settings and enable it.
> If you are on a Wii, you can also switch the Network Profile as configued in your Wii Settings used for it.
> This can be useful if the profile cannot be selected as a default in the Wii Settings when it has no internet access and you just need LAN acccess.

Makes it seem like the internet connection isn't necessary as long as a connection of some kind has been set up. Makes things a little more awkward to setup. I'll give it a go though...

**Comment by carnage702** [comment]
> > the wii requires to be online to establish a connection, its the wii os that does that so just connect both your wii and gamecube to the same router and that router has to have internet.
> 
> It does? This section from the readme has me a little confused:
> 
> > It works just like a real BBA and works from both a USB LAN adapter and over WLAN.
> > To enable BBA Emulation, simply go into nintendonts settings and enable it.
> > If you are on a Wii, you can also switch the Network Profile as configued in your Wii Settings used for it.
> > This can be useful if the profile cannot be selected as a default in the Wii Settings when it has no internet access and you just need LAN acccess.
> 
> Makes it seem like the internet connection isn't necessary as long as a connection of some kind has been set up. Makes things a little more awkward to setup. I'll give it a go though...

well the wii os can only say a connection is established if it has internet, not sure if you can spoof the connection flag with some  netwrok settings or something but i remenber everyone trying bba and needing the wii to have internet connection to connect

**Comment by Kamon62** [comment]
> well the wii os can only say a connection is established if it has internet, not sure if you can spoof the connection flag with some netwrok settings or something but i remenber everyone trying bba and needing the wii to have internet connection to connect

Success! Finally got it working. You were correct, without an active internet connection it never establishes a link. It began to search fine from there on. After that the issue was that I had two different regions of the game, doesn't matter if both are running at 60hz pal and ntsc won't talk to each other. Now that I know this works I'll put the wii back on a separate router and see if that works too. Lots of trail and error but I got there, thanks for the help.
