### ISSUE TITLE
Pokemon Colosseum Bonus Disc (JPN) [PCSJ01] - Memcard Emulation Issue

### ISSUE THREAD

**Issue by centershck** [FIX94/Nintendont#1058]
I am encountering the same issue as described in issue #195.
Rev v6.499 , Nintendont Settings are default except for Native control wich is turned on.

Whenever I start the bonus disc iso with memcard emulation turned off, the game boots up, I select the Celebi Distribution programm, it boots up and gives me the error, that it didnt find a memcard in Slot A. Since I dont have a physical memcard inserted everything seems to be going perfectly fine.
However, when I boot up the game with Memcard Emulation, it only works up to the point where I want to start the Celebi Distribution programm and then the screen turns black.
[" https://www.youtube.com/watch?v=bVyTw2Vj67o <- at the 0:25 mark is when it hangs"]

As the Distribution Programms needs to check if there is a Pokemon Colosseum file on the memcard wich meets the requirements, I assume that i need to turn Memcard Multi on. I tried to boot it with block size 59 and and 251 with no success. Same results with Memcard Multi turned off. However, the videos on the disc also dont work at all while memcard emulation is on. I also tried to boot the game from an UBS-to-SD-Adapter and not from the internal SD. I also tried another iso of the Bonus disc (Kakucho disc). On that one i cant get the Distribution Programm to start up at all, even with memcard emulation turned off.

Is there anything I am doing wrong or missing? Thanks in advance :)

**Comment by carnage702** [comment]
Did you tried with native to off? You don't need native to get controllers working even through the Wii GC ports

**Comment by centershck** [comment]
Will try this when I'm back home tomorrow.
Stupid me didn't look far enough into the process of transferring the Celebi to my JPN Ruby Save and it turns out that you first transfers it to Colosseum and then to the GBA with the link cable. So yeah, as native is not required it could be the root of the problem, hopefully. Thanks for the quick reply!

**Comment by centershck** [comment]
Native control was indeed the problem. Turned it off and it worked like a charm. For anyone interested: I used 59 and multi for the first start of the game. Injected a complete Colosseum JPN file into the .raw memcard file with Dolphin and voilà! (make sure you have enough space in your party to receive the Celebi on Colosseum AND turn on native again before starting the transfer process for obvious reasons). Thanks for the help again, appreciate the support.
