### ISSUE TITLE
Nintendont ever run as a native WiiU application?

### ISSUE THREAD

**Issue by manaboy** [FIX94/Nintendont#1060]
Can it or will it ever be ported to run as a native WiiU homebrew so it utilises the higher system memory and clock speeds

**Comment by carnage702** [comment]
No. Nintendont is not an emulator, so nintendont uses the Wii Gx GPU without any modifications, since both GC and Wii use the same GPU, Wii u uses gx2 which is totally different, meaning you would need to emulate all the graphics, si it would run even worse than Wii in the end.
