### ISSUE TITLE
my wiimote + nunchuk doesn't work

### ISSUE THREAD

**Issue by Naimer457** [FIX94/Nintendont#1063]
i've been trying it and in the wii u and vwii menu works, but when i open a game it doesn't work
i've tried with super mario sunshine and with super smash bros melee

**Comment by carnage702** [comment]
Are both wiimote+nunchuck official controllers? or one of them is fake/3rd party?
there is no guarantees of any fake/3rd party controllers to work at all.

If they both are official does any off the 4 lights on the wiimote stays turned on?

**Comment by Naimer457** [comment]
yes they were 3rd party, but anyways i bought a gc controller so isn't a problem now
