### ISSUE TITLE
(Request) Remove Widescreen Support for Mario Party 4, 5, 6, and 7.

### ISSUE THREAD

**Issue by Toadfan69kinopio** [FIX94/Nintendont#1065]
The widescreen codes for Mario Parties 4-7 only work in Board Games. Everything else is stretched. Can Mario Parties 4-7 be added to the exceptional list?

**Comment by carnage702** [comment]
to remove widescreen you only need to **not force widescreen on games**... games that have exceptions is because they have their own specific codes they arent removed from being forced by the default hack at all.

**Comment by Toadfan69kinopio** [comment]
OK, maybe MP4's widescreen code should be updated, since the Dolphin Wiki gecko code (At least the USA Code) does work on nintendont. Here's the code:

Widescreen (USA):
041D4980 44555555
0400C040 2C000356
C200B0F4 00000003
1C000004 3BA00003
7C00EFD6 B01F0004
60000000 00000000
041D49F8 44400000
041D4F0C 44400000
C20CF3D8 00000005
3C003B2A 6000AAAB
80830000 7C002000
40820010 3C00BF40
60000000 9003000C
C003000C 00000000
C20423EC 00000002
3C004410 9001000C
C041000C 00000000
C20BBC08 00000003
3FE03FAB 93E30000
C3830000 EF620732
60000000 00000000
C20BBE04 00000003
3C003FAB 90030000
C0A30000 EFA20172
60000000 00000000
04014874 38600001
0405DDBC 4E800020
C208955C 00000005
3CA03FAB 90A1FFFC
C001FFFC C03F0004
EC010032 3CA042C0
90A1FFFC C021FFFC
EC200828 00000000
C20885A4 00000005
3CA03FAB 90A1FFFC
C001FFFC C03F0004
EC010032 3CA042C0
90A1FFFC C021FFFC
EC200828 00000000
C208B500 00000005
3C803FAB 90810040
C0210040 7C03042E
EC210032 3C8042C0
90810040 C0010040
EC010028 00000000
C208C4B4 00000005
3C803FAB 90810040
C0210040 7C03042E
EC210032 3C8042C0
90810040 C0010040
EC010028 00000000
C208C1A8 00000006
83C10044 3CA03FAB
90A10044 C3C10044
7FE4042E EFFE07F2
3CA042C0 90A10044
C3C10044 EFFFF028
93C10044 00000000
48000000 800030C8
DE000000 80008180
30010010 C0010064
D2010088 00000005
3C603FAB 906100A4
C04100A4 C01F0110
EC420032 3C6042C0
906100A4 C00100A4
EC020028 00000000
E0000000 80008000

**Comment by Toadfan69kinopio** [comment]
I don't know if this code works though:

Widescreen (Mario Pary 6):
040183EC 38600001
C20A17B0 00000002
C0A29F48 EFA22824
60000000 00000000
C20A152C 00000002
C0029F48 EF620024
60000000 00000000
042C30F8 3FCCCCCD
C202C18C 00000002
C01F000C C3A29F48
EC00E824 00000000
0414E760 C3A30000
041932E0 388002D0
042C14B8 3FCCCCCD
04151324 38600001
