### ISSUE TITLE
Nintendont looks fine before opening 

### ISSUE THREAD

**Issue by Schneidsta** [FIX94/Nintendont#1068]
Nintendont looks as it should before opening on wii but when i try to load it, it goes black screen and closes.. Any fixes to this i have all the proper files I believe but nothing seems to work.

**Comment by carnage702** [comment]
nintendont only uses offical iso 58 do you have the official ios 58 on your wii and not a cios? also its your homebrew channel ios 58 based? and take a picture of your apps folder inside the nintendont folder.
