### ISSUE TITLE
"Nintendont-XBOX360" implementation code?

### ISSUE THREAD

**Issue by PedroRafael215** [FIX94/Nintendont#1072]
Actually theres a "Nintendont" release ( https://github.com/revvv/Nintendont-XBOX360 ->this one) that able us to play with a wired usb xbox360 controller and with china Wii Remotes (2 in one). 
Unfortunately it doesn't load "\games" from usb (at least i tried several times and nothing). It boots from disk and works great with xbox360 controllers and with not originals Wii remotes (2 in one from aliexpress). 

It would be amazing to see this implementations Here:
*Wired xbox360 controller support
* Non original Wii remotes (2 in one from Alixpress) support 
(cause these in original build aren't recognized as a controller but in "Nintendont-XBOX360" works like a charm).

**Comment by carnage702** [comment]
That fork replaces hid controllers with xinput,  so no can do, it would break everyone using standard hid controllerd
