### ISSUE TITLE
Updating emulated memory card "last modified" date?

### ISSUE THREAD

**Issue by nyanpasu64** [FIX94/Nintendont#1073]
I'm playing Nintendont using emulated memory card on a USB hard drive. It would be convenient if saving in-game would update the "Last Modified" date of the corresponding memory card image in /saves, so I can tell if a particular game's save file was last modified in Dolphin Emulator or Nintendont on my real hardware, and so I can plug my hard drive into a PC and sort /saves by modified date to see which games I played most recently (instead of having to scan the list of game IDs and look for one matching the game name).

**Comment by carnage702** [comment]
this has no utility and doesn't matter at all...if you want this type of changes your free to fork nintendont and mod it yourself, its an open source project.
