### ISSUE TITLE
Crash on start up for The Fairly OddParents - Shadow Showdown

### ISSUE THREAD

**Issue by liftedterps** [FIX94/Nintendont#1075]
Same as with Taz Wanted and so on. Resolution makes no difference.

**Comment by carnage702** [comment]
The games work perfectly fine, if the games are crashing is because you are using incompatible settings or bad isos.

Take a picture of your nintendont settings to start, also make sure you use full 1.35gb isos with md5 matching resumo.org, no nkit stuff.

**Comment by liftedterps** [comment]
my game works fine now, had to activate force ntsc in the game setting for those 3 games. that just wasn't mentioned at all anywhere

**Comment by carnage702** [comment]
The game is already NTSC so if you need to force anything is because you are using others settings that were causing issues.
