### ISSUE TITLE
[Enhancement] Always send a full-analog R/L press whenever a R/L digital-press occurs

### ISSUE THREAD

**Issue by NintendoManiac64** [FIX94/Nintendont#1078]
Some games, like Mario Party 4 (particularly in the minigame "Mario Speedwagons"), do not send a full-analog press of the R or L button when a digital-press of the R or L button is transmitted.

This is most noticeable on controllers that have their shoulder button springs not functioning in their stock configuration (whether removed, lost, damaged, worn out, etc) since, with that minigame "Mario Speedwagons", the dragster basically won't accelerate unless you specifically give it a full-analog press of the R button.

There's a [fork of Nintendont that implements this for non-pro classic controllers](https://github.com/libertyernie/Nintendont/releases/tag/v20230121b), but it'd be great if this were merged upstream and support was also added for other controllers with analog triggers/shoulder buttons including actual GameCube controllers (whether connected to an early-revision Wii or via the official Nintendo USB-GameCube adapter).

For completion sake, it'd be great if it was supported on non-Nintendo controllers like a PS4 controller or other USB controllers, but 99.99% of non-Nintendo controllers aren't even mechanically designed to be able to have a digital-press of R/L without also being a full-analog press anyway, so...

**Comment by carnage702** [comment]
this would be awful, all games that actually use the pressure trigger would  just be stuck on full presses for no reason, why would you remove this feature from ps3 controller, wii classic controller(original) and gc controllers? makes no sense, if your controller has damaged l/r just fix it or buy a new one but removing the ability from other controllers is not the answer and i wont make yet another menu option for this to even be a thing...

**Comment by NintendoManiac64** [comment]
...you have completely misunderstood the issue.

From the games/console's point of view, the a single analog shoulder button is actually two separate buttons - one that is analog, and another that is digital.

The problem was about how some games, e.g. Mario Party 4, completely ignore the digital button and *only* look at the analog button.  In other words, even if the analog button is fully pressed to 100%, the digital button is not transmitted.

My entire point of this issue was so that, when an analog button is fully pressed to 100%, that the digital button should *also* be transmitted.  The aforementioned fork already implements this and it works great *without removing analog button functionality*.
