### ISSUE TITLE
Issues with mayflash w014 adapter and suggested workaround

### ISSUE THREAD

**Issue by LexamusPrime** [FIX94/Nintendont#1083]
I absolutely love this adapter because it allows full wireless control with an original GC controller connected to a wiimote. Even works flawlessly with analog triggers. The issue is that the start button is mapped to work as a minus button when double tapped. This of course is an issue because it swaps the face buttons every time you pause buffer or spam the start button to skip a cutscene.  

If there was a simple option in the menu to disable the swap this would be awesome. It would be nice even outside of this adapter because my 5 year olds accidentally hit the minus button on the classic controller too.

**Comment by carnage702** [comment]
this will not happen, i wont add an option because of some random 3rd party adapter, of i added a menu option for everything people ask for nintendont menu would be 300 options.

**Comment by LexamusPrime** [comment]
I get not wanting to add 300 menu options but this is something that isn’t related to simply one controller or adapter. As I said later, this also relates to the classic controller and 5 year olds. Can someone tell me where to find the option so I can disable this in my own private build then? Sent from my iPhoneOn Mar 4, 2023, at 11:05 PM, pedro702 ***@***.***> wrote:﻿
this will not happen, i wont add an option because of some random 3rd party adapter, of i added a menu option for everything people ask for nintendont menu would be 300 options.

**Comment by eku** [comment]
@LexamusPrime you may fork this repo and make your private changes.
