### ISSUE TITLE
hangs at initializing virtual 59-block memory card...

### ISSUE THREAD

**Issue by firecurious** [FIX94/Nintendont#1084]
running clean install of tiramisu with ONLY tiramisu itself, nintendont, and bloopair. it used to work on cbhc but nintendont no longer works after "upgrading" to tiramisu

![IMG_20230305_165520109](https://user-images.githubusercontent.com/10892929/223030830-08e87083-4b1c-4e8d-9430-f9c093c5bb26.jpg)

**Comment by carnage702** [comment]
make sure your sd card is unlocked also make sure your inject is installed into nand and not into an wiiu formatted hdd.
