### ISSUE TITLE
nintendont does not appear on homebrew channel

### ISSUE THREAD

**Issue by firecurious** [FIX94/Nintendont#1085]
![IMG_20230305_155733698](https://user-images.githubusercontent.com/10892929/223031225-8f04dd6c-b2fe-48bf-9c73-691f54eef3ca.jpg)

tested on CBCH WiiU and VWii, and Tiramisu CBHC and VWii

**Comment by carnage702** [comment]
You are not using the homebrew channel...

you are using the homebrew launcher

nintendont is a vwii app so it will never ever appear on the wiiu homebrew launcher...  it only appears on the vwii homebrew channel.
