### ISSUE TITLE
failed to load ios58 from nand

### ISSUE THREAD

**Issue by Paledivine** [FIX94/Nintendont#1086]
here is two screenshots to explain my specific error, I haven't found a solution but I've been looking all morning.

![image](https://user-images.githubusercontent.com/125704669/226129554-133dc8dc-e3e6-4e89-b144-6a7d0cd9dd6f.png)
![image2](https://user-images.githubusercontent.com/125704669/226129584-14fa0817-d85e-4fd7-ae28-207326cc0935.png)

**Comment by carnage702** [comment]
is the xml correctly saved?  try this xml it will auto update to latest version  so no need to change it.
[meta.zip](https://github.com/FIX94/Nintendont/files/11009473/meta.zip)

**Comment by Paledivine** [comment]
thank you that worked perfectly :)
