### ISSUE TITLE
Video Width Does Not Persist After Selecting Progressive Scan Mode in Games

### ISSUE THREAD

**Issue by GK6475** [FIX94/Nintendont#1089]
When I set the video width to 640, it works fine when my games first boot, but does not work after enabling progressive scan mode, and instead defaults to the game's usual output resolution (in my case 660), which often does not match with the rendered image, causing blur. This is even with Force Progressive turned on. Also, maybe an option for Frame buffer video width (like USBLoader GX or Swiss) could be beneficial for games that use 608 or some other odd low horizontal resolution.

**Comment by carnage702** [comment]
width is a hack, it works on some games, it crashes others and does nothing on others, its a general hacks that patches a specific region, some games dont use that region so it doesnt work, you would need to make per game patches to work on every game perfectly being 480p or not, depends on the region the game uses.

**Comment by GK6475** [comment]
> width is a hack, it works on some games, it crashes others and does nothing on others, its a general hacks that patches a specific region, some games dont use that region so it doesnt work, you would need to make per game patches to work on every game perfectly being 480p or not, depends on the region the game uses.

Well, Swiss seems to be able to apply it to every game flawlessly. there a way that I could create a patch for each game? I can use HxD if it's something that can be hex edited into an ISO.

**Comment by eku** [comment]
> Well, Swiss seems to be able to apply it to every game flawlessly.

Then you may want to run Swiss on your Wii with [Wii Swiss Booter](https://github.com/pyorot/wii-swiss-booter).
