### ISSUE TITLE
Nintendont via VC Injection for the Wii U gives black screens during load

### ISSUE THREAD

**Issue by nitorita** [FIX94/Nintendont#1090]
Running Nintendont through the vWii on the Wii U works just fine, but trying to run a VC injected copy of a GCN game (which forwards though Nintendont, created via TeconMoon) just gives a black screen that indefinitely freezes the Wii U without any audio.

I've spent several hours testing out all sorts of fixes offered in the past, but to no avail--they primarily double back to "just use the vWii version" in a nutshell.

I've already made sure that the installed Nintendont files are freshly downloaded and installed, and that the required "nincfg.bin" was deleted and recreated via both Nintendont in vWii, and via TeconMoon as well.

Any suggestions?

**Comment by carnage702** [comment]
are the injection on wiiu nand or wiiu formatted usb? if they are not on nand and you are using tiramisu/aroma they will almost always freeze if used on usb.
