### ISSUE TITLE
Support for NTFS hard drives

### ISSUE THREAD

**Issue by yportier** [FIX94/Nintendont#1091]
Is there any plan to support NTFS ?
HDDs are all NTFS nowadays and It is a bit of a pain to format them to FAT32... is there any technical limitation that prevents this ?

**Comment by monta990** [comment]
Maybe the NTFS itself, because not is a open standard

**Comment by carnage702** [comment]
no, and never will be, 99% of all wii homebrew is fat32 only.

**Comment by AnonymousUser98** [comment]
This issue should be closed as "not planned" instead of "completed".
