### ISSUE TITLE
Nintendont games issues

### ISSUE THREAD

**Issue by Bjnielsen39** [FIX94/Nintendont#1093]
I’ve been having multiple issues with games on Nintendont. Some games crash and don’t load at all (Legend of Zelda Four Swords Adventure). Some just load to a blank green screen and stay there (Legend of Zelda Twilight Princess) and most load to a plain black screen and do nothing. Only a few have ended up working, like Mario Party 4 and Monopoly. No settings have been changed other than memory card emulation, and I have the latest version. Any help?

**Comment by carnage702** [comment]
take a picture of your nintendont settings.

**Comment by Bjnielsen39** [comment]
> take a picture of your nintendont settings.

Here it is. It’s mostly default I believe. https://imgur.com/a/7Nd7clL This should lead to it

**Comment by carnage702** [comment]
settings are fine, if the games arent startting im guessing you have bad isos.

nintendont needs full 1.35gb isos matching redump md5, not nkit,not shrunk or anything, those are never garanteed to work, another issue might be the save file, if your sd/usb are too fragmented nintendont might fail to creat a good memory card for the game  and making instead a bad save file, go to your saves folder and check if there are any 0kb files and delete them.

**Comment by Bjnielsen39** [comment]
> settings are fine, if the games arent startting im guessing you have bad isos.
> 
> nintendont needs full 1.35gb isos matching redump md5, not nkit,not shrunk or anything, those are never garanteed to work, another issue might be the save file, if your sd/usb are too fragmented nintendont might fail to creat a good memory card for the game and making instead a bad save file, go to your saves folder and check if there are any 0kb files and delete them.

What does it mean to have a full 1.35 gb iso? Don’t all files have varying sizes based on game size?
And what does ‘matching redump m5’ mean? Sorry, I’m pretty new to Wii modding.
They are normal iso files.
What does it mean that my usb is fragmented? That there are 0kb save files? I don’t think many files have been saved so far…
Thanks for your help so far!

**Comment by carnage702** [comment]
> > settings are fine, if the games arent startting im guessing you have bad isos.
> > nintendont needs full 1.35gb isos matching redump md5, not nkit,not shrunk or anything, those are never garanteed to work, another issue might be the save file, if your sd/usb are too fragmented nintendont might fail to creat a good memory card for the game and making instead a bad save file, go to your saves folder and check if there are any 0kb files and delete them.
> 
> What does it mean to have a full 1.35 gb iso? Don’t all files have varying sizes based on game size? And what does ‘matching redump m5’ mean? Sorry, I’m pretty new to Wii modding. They are normal iso files. What does it mean that my usb is fragmented? That there are 0kb save files? I don’t think many files have been saved so far… Thanks for your help so far!

**NO they arent all different sizes**, a clean gamecube game iso is a minidvdrip and they are all 1.35gb in size, if they are any other sizes then you are getting shrunken versions which might not work on nintendont since nintendont is not an emulator so therefore its a gamble if they are well shrunk or not, no nkit isos either.

**redump is a website where people list verified good dumps of games**
just search your game pick the region of it and then see the md5 for a known good dump
http://redump.org/

to check your own iso md5 use this program
https://www.mediafire.com/file/5y3tfpoil433rij/MD5_SHA-1_Utility.exe/file

if the iso is not 1.35gb dont even bother checking it since it wont match redump known good dump.

2-when you start any game on nintendont even if the game doesnt actualy start first nintendont creates a save file for that game and those files go into sd/usb:saves folder so check there is there are any 0kb files.

**Comment by Bjnielsen39** [comment]
Ok will check that out

**Comment by Bjnielsen39** [comment]
> > > settings are fine, if the games arent startting im guessing you have bad isos.
> > > nintendont needs full 1.35gb isos matching redump md5, not nkit,not shrunk or anything, those are never garanteed to work, another issue might be the save file, if your sd/usb are too fragmented nintendont might fail to creat a good memory card for the game and making instead a bad save file, go to your saves folder and check if there are any 0kb files and delete them.
> > 
> > 
> > What does it mean to have a full 1.35 gb iso? Don’t all files have varying sizes based on game size? And what does ‘matching redump m5’ mean? Sorry, I’m pretty new to Wii modding. They are normal iso files. What does it mean that my usb is fragmented? That there are 0kb save files? I don’t think many files have been saved so far… Thanks for your help so far!
> 
> **NO they arent all different sizes**, a clean gamecube game iso is a minidvdrip and they are all 1.35gb in size, if they are any other sizes then you are getting shrunken versions which might not work on nintendont since nintendont is not an emulator so therefore its a gamble if they are well shrunk or not, no nkit isos either.
> 
> **redump is a website where people list verified good dumps of games** just search your game pick the region of it and then see the md5 for a known good dump http://redump.org/
> 
> to check your own iso md5 use this program https://www.mediafire.com/file/5y3tfpoil433rij/MD5_SHA-1_Utility.exe/file
> 
> if the iso is not 1.35gb dont even bother checking it since it wont match redump known good dump.
> 
> 2-when you start any game on nintendont even if the game doesnt actualy start first nintendont creates a save file for that game and those files go into sd/usb:saves folder so check there is there are any 0kb files.

So I downloaded the md5 file but all that appears when I open it is text, what do I do from here? https://imgur.com/a/fXef7iv

**Comment by carnage702** [comment]
So you are not using windows are you? im not sure if this program works on mac or linux or whatever you are using but it seems the md5 matches according to redump  
http://redump.org/disc/6585/
four swords usa good md5 is 6156867bd3aa2fc410e9e307fe0fd98c

so did you checked your saves folder? for any 0kb files?
how are you sending the isos to the usb/sd? drag and drop? or using a program?

try starting the game with memory card emulation turned off, if it starts then you have a bad save file created.

**Comment by carnage702** [comment]
for me the program works like this 
![image](https://user-images.githubusercontent.com/12446178/232277180-86d62a3e-dcf9-49e5-80dc-010dd67e28fd.png)

**Comment by Bjnielsen39** [comment]
> So you are not using windows are you? im not sure if this program works on mac or linux or whatever you are using but it the md5 according to redump http://redump.org/disc/6585/
> 
> so for me the program doesnt work like that tough
> 
> so did you checked your saves folder? for any 0kb files? how are you sending the isos to the usb/sd? drag and drop? or using a program?
> 
> try starting the game with memory card emulation turned off, if it starts then you have a bad save file created.

No 0kb saves, but will try with windows later today.

**Comment by Bjnielsen39** [comment]
> for me the program works like this
> ![image](https://user-images.githubusercontent.com/12446178/232277180-86d62a3e-dcf9-49e5-80dc-010dd67e28fd.png)

https://imgur.com/a/MR76auX

Okay, so on windows, I download the file, clicking on the link in middle picture. Then it appears down below which is normal, top picture. I then open it up using chrome and I still get text. Do I need an application to open up the file and use it?

**Comment by carnage702** [comment]
> > for me the program works like this
> > ![image](https://user-images.githubusercontent.com/12446178/232277180-86d62a3e-dcf9-49e5-80dc-010dd67e28fd.png)
> 
> https://imgur.com/a/MR76auX
> 
> Okay, so on windows, I download the file, clicking on the link in middle picture. Then it appears down below which is normal, top picture. I then open it up using chrome and I still get text. Do I need an application to open up the file and use it?

why would you open the program on chrome or anything? its an executable you only double click it on it will open like cliclikng any program

**Comment by carnage702** [comment]
you seriously dont know how to open a program? you click on it it will open.
then  you either drag your iso to the file tab or click on it and then search for your iso 

then wait afew seconds and the program will tell you the md5 of your own iso

then you go to redump and see if your iso md5 matches with the one in there in no shape or form you open this program with anything, the program is a solo program, you double click and select your iso.

**Comment by Bjnielsen39** [comment]
> you seriously dont know how to open a program? you double click on it it will open. then you either drag your iso to the file tab or click browse on it and then search for your iso manually.
> 
> then wait afew seconds and the program will tell you the md5 of your own iso
> 
> then you go to redump and see if your iso md5 matches with the one in there in no shape or form you open this program with anything, the program is a solo program, you double click and select your iso.

When I double click on it it only brings up options to open with chrome or something else. I think I need that ‘MC5 & SHA-1’ app to open it, as I am double clicking but no program is running. Sorry if I’m being a little incompetent, I’m not the most technologically inclined person ever. Modding a Wii sure is harder than a 3DS.

**Comment by carnage702** [comment]
> > you seriously dont know how to open a program? you double click on it it will open. then you either drag your iso to the file tab or click browse on it and then search for your iso manually.
> > then wait afew seconds and the program will tell you the md5 of your own iso
> > then you go to redump and see if your iso md5 matches with the one in there in no shape or form you open this program with anything, the program is a solo program, you double click and select your iso.
> 
> When I double click on it it only brings up options to open with chrome or something else. I think I need that ‘MC5 & SHA-1’ app to open it, as I am double clicking but no program is running. Sorry if I’m being a little incompetent, I’m not the most technologically inclined person ever. Modding a Wii sure is harder than a 3DS.

if you are on windows and even mac you should be be able to open an executable without using another program.

anyway i made a video with my shitty phone so you know what to do 
https://www.youtube.com/watch?v=BDefqvZ8vgI&feature=youtu.be

**Comment by Bjnielsen39** [comment]
> > > you seriously dont know how to open a program? you double click on it it will open. then you either drag your iso to the file tab or click browse on it and then search for your iso manually.
> > > then wait afew seconds and the program will tell you the md5 of your own iso
> > > then you go to redump and see if your iso md5 matches with the one in there in no shape or form you open this program with anything, the program is a solo program, you double click and select your iso.
> > 
> > 
> > When I double click on it it only brings up options to open with chrome or something else. I think I need that ‘MC5 & SHA-1’ app to open it, as I am double clicking but no program is running. Sorry if I’m being a little incompetent, I’m not the most technologically inclined person ever. Modding a Wii sure is harder than a 3DS.
> 
> if you are on windows and even mac you should be be able to open an executable without using another program.
> 
> anyway i made a video with my shitty phone so you know what to do https://www.youtube.com/watch?v=BDefqvZ8vgI&feature=youtu.be

Alright, thanks, I think I understand it, but then what do I do if it doesn’t match/verify? Do I have to try a different rom website or is there a way that I can download the dump off the redump place?

**Comment by carnage702** [comment]
> 

yeah if it doesnt match you need to try another place to get the iso, i cant link you romsites because it is illegal but if you search stuff like "archive.org gamecube usa" on google you migth find some links with redump isos ;)

**Comment by monta990** [comment]
It´s the last nintendont version?

https://github.com/FIX94/Nintendont/blob/master/loader/loader.dol

**Comment by carnage702** [comment]
> It´s the last nintendont version?
> 
> https://github.com/FIX94/Nintendont/blob/master/loader/loader.dol
yes it is.
