### ISSUE TITLE
Wind Waker ISO not working as it is compressed.

### ISSUE THREAD

**Issue by DriftWare07** [FIX94/Nintendont#1094]
It would appear that 9zip wont fully extract the iso, so i cant use it on nintendont. Is there another way to extract the iso from a .7z?

**Comment by carnage702** [comment]
you need literally 7 zip program that is why its called 7z file...

**Comment by DriftWare07** [comment]
Yeah turns out 9zip doesnt do a particularly good job at extracting 7z files. My bad.
