### ISSUE TITLE
Add built in controller mapping

### ISSUE THREAD

**Issue by EpicDoodleboy2** [FIX94/Nintendont#1095]
Console: Over June 2008 Wii

So Recently I have heard that nintendont has GCN controller emulation with other controllers like for the ps4 controller but When I try to set it up via the PC it's... confusing so I downloaded a controllers.ini for switch, file and it didn't work with my PDP wired Nintendo switch controller so might as well say that nintendont should have built-in controller mapping and should be a option in the settings and would be layed out vertically and would show what controller is in the usb port and when finished it would make or replace the controllers.ini file.
also people saying add (this controller) could stop.

THIS PROBABLY A DUPLICATE IDK

Example layout
Settings, controller layout editor, top right the controller it picked up
A = (button on controller)
B =  (same thing)
Y =
X =
R =
L =
Z =
D pad up =
D pad down =
D pad left =
D pad right =
Start =
Right Analogue =
Left Analogue =

**Comment by carnage702** [comment]
Nintendont is an open source program , so if you can code that and submit a pull request that is fine, otherwise don't expect this to happen
