### ISSUE TITLE
Resident Evil 0 [GBZE08] Force NTSC 480p is glitchy

### ISSUE THREAD

**Issue by 60fpshacksrock** [FIX94/Nintendont#1096]
Is it possible to add a custom 480p mode for this game? The default causes issues and does not work properly.

**Comment by carnage702** [comment]
If you can create a code yourself and submit it as a pull request go right ahead but don't expect anyone to do it. Also why not play the Wii version of resident evil 0 ? It has everything you want.

**Comment by 60fpshacksrock** [comment]
I don't have the Wii version, only GC.

**Comment by carnage702** [comment]
> I don't have the Wii version, only GC.

if you are using nintendont your wii is hacked, if your wii is hacked then you can play any wii game... the wii version has 480p can be played with gc controller/wiimote+nunchuck/classic controller.

**Comment by 60fpshacksrock** [comment]
Yes my Wii is hacked, has been since late 2010/early 2011.

Also yes, I know all of that. I may eventually pickup the Wii version. Thanks for the helpful attitude though.
