### ISSUE TITLE
4:3 or 14:9 aspect ratio changer in options.

### ISSUE THREAD

**Issue by EpicDoodleboy2** [FIX94/Nintendont#1099]
Title says it Switch between 4:3 or 14:9 as GCN games are stretched to fill the side and just makes it blurry.

Yes I know there is a "widescreen" option which kinda acts as a 4:3 size but looks off as I see things that are offscreen.
Also IDK how to code.

**Comment by carnage702** [comment]
not gonna happen  you either play 4:3 or 16:9 with forced widescreen, if you want something so weird you do it yourself or find some one to do it for you but it wont be added to main nintendont ever.
