### ISSUE TITLE
Can an option to more accurately change the X offset be implemented?

### ISSUE THREAD

**Issue by 60fpshacksrock** [FIX94/Nintendont#1100]
I'm no sure why, if the issue is my TV, Wii or the Sewell HDMI adapter but no matter the scale I choose in Nintendont I can't get it directly in the middle. The closest setting is 2 or 3. But what would most likely fix it at least with Nintendont is 2.5.

The issue is not directly related to Nintendont, but my even on the Wii menu and HBC. In other words, everything. But I am not asking for a fix for everything, only Nintendont if possible.

**Comment by carnage702** [comment]
if this is a wii problem, then go to the **wii settings** and you can change the center there too, like you said  it happens even in wii menu so this is an issue on your end not nintendont.

**Comment by 60fpshacksrock** [comment]
I did set it before in the Wii menu. It is always more to one side than the other so I was hoping for a fix for at least ND.
