### ISSUE TITLE
Resident Evil 4 NTSC-U freezes

### ISSUE THREAD

**Issue by SpeckObst** [FIX94/Nintendont#1101]
I've been trying to play the NTSC-U version of Resident Evil 4 through Nintendont and non of my several Wii run it without issues. At some point - while trying to load - the game will either completly freeze or pause on the current frame and keep playing the audio of the cutscene without being able to skip it or play after its conclusion.

I have been testing this on three separate Wii (2 PAL and 1 Japanese) and several SD cards as well as hard drives. All of them reproduce the same issues. I have roughly played 20 hours of the village section with over 20 freezes so this isn't some freak accident. 

Also, I've tried lifting the reading speed restrictions and the same freezes still appear. No other game I have played through Nintendont has ever caused this issue.

Other than reading speed, all of my other Nintendont setting are the default wiht nothing else turned on.

Please fix it as RE4 is one of the greatest games of all time and should be playable in its original form through Nintendont.

**Comment by carnage702** [comment]
The game works perfectly fine, take a picture of your nintendont settings

**Comment by SpeckObst** [comment]
<img width="727" alt="Screenshot 2023-05-01 at 16 05 42" src="https://user-images.githubusercontent.com/132236706/235463791-32f9cad9-7a6a-412f-ab84-10c4e79f7c52.png">
<img width="740" alt="Screenshot 2023-05-01 at 16 05 52" src="https://user-images.githubusercontent.com/132236706/235463797-22bece52-a9e8-48bd-9237-14821a67c195.png">

I've been playing the game with both these settings. Only difference is unlocked read speed.

I've tried it with the redump ISO from archive.org, created one myself from the retail disc and even played the retail disc through Nintendont on both my PAL Wiis and my Japanese Wii. No matter matter the combination, no matter which hard drive or SD card I use, all of them experience the same freezes at different points in the game.

There is no definitive trigger. Sometimes it happend at the start of 1-3 when trying to load the Hunnigan conversion, sometimes it freezes at the end or start of the two El Gigante cutscenes in 2-1, sometimes it happens when closing the menu during the cabin fight in 2-2 and just now it froze randomly during the Mendez boss fight in 2-3.

It can happen after playing for 20 minutes or 3 hours. But it will always freeze somewhere. I've seen it being mentioned here in other threads and two of my friends have experienced the same issues this year. If the game actually runs fine then we are all collectively doing something wrong and after experimenting for over 20 hours the fast two weeks, I'm at my wits' end.

Again, I have never experienced anything like this with any other game I've played through Nintendont except for discovering the Disney Skateboarding issue in my stream last year that got fixed in the next update (thanks again for responding so quickly back then).

**Comment by carnage702** [comment]
i played the entire game and only got one freeze with that guy with the knife boss fight because i was forcing widescreen , what i see is that you are using an original memory card? did you ever tryed with emulated memory card? i did my entire playthrough with emulated memory card.

like you said there is no trigger it can happen in 3 hours or not at all, that way is extremely hard to fix something that cant be replicated  consistenly, but try with emulated memory card maybe that is the issue? who knows.

**Comment by SpeckObst** [comment]
I'll try to play with an emulated memory card. Always been using my own cards.

**Comment by carnage702** [comment]
> I'll try to play with an emulated memory card. Always been using my own cards.

yeah but there are some games, even like 2 that i forgot the name that have issues when using real memory cards, not sure why or how to fix that, maybe this is one of those games too.

Also all for all there is always the wii version of RE4, it has gc controller support,480p and widescreen too so you dont actually loose anything imo.

**Comment by carnage702** [comment]
before trying emulated memory card try this file , of course with read speed unlock to off
[boot.zip](https://github.com/FIX94/Nintendont/files/11366039/boot.zip)

**Comment by SpeckObst** [comment]
Thanks, I'll give it a go. Already started a new file on a virtual memory card though and I'm right before Mendez. So far no freezes, just a few moments of the game taking a bit longer to load after a cutscene. 

I'll try to do more testing later today and report my experience.

**Comment by SpeckObst** [comment]
<img width="708" alt="Screenshot 2023-05-02 at 02 51 04" src="https://user-images.githubusercontent.com/132236706/235556557-ee485e68-e2fb-4291-9331-6e8b7be4ae74.png">

Using the file (both virtual memory card and read speed unlock set to off) it took all but 5 minutes to get to the freeze you see above.

With the virtial memory card enabled, I've played for about 2 hours until chapter 3-2 and no freezes so far. Only some slightly longer pauses after cutscenes or exiting the menu.

**Comment by carnage702** [comment]
so the original or this file work the same as long as you are using emulated memory card right? so it was the memory card thing, i have no idea how to fix that.

**Comment by 60fpshacksrock** [comment]
Using emulated cards are better because you save your real memory cards. Also, disabling the disc read delay will cause issues with some games.

Originally Nintendont had no disc read delay. It was soon added and afterwards I requested the option (under a different username of course on gbatemp) to disable it because games like NFS UG2 take a really long time to load with delay on.

**Comment by carnage702** [comment]
So did using emulated memory card stop the freezes? [SpeckObst](https://github.com/SpeckObst)
