### ISSUE TITLE
My Nintendon't has issues in various games, Freeze in Mario Golf in GCN BIOS screen. missinputs in Pokemon XD

### ISSUE THREAD

**Issue by Moonyvek** [FIX94/Nintendont#1103]
![IMG_20230513_231903](https://github.com/FIX94/Nintendont/assets/93215451/ff1b7b32-a02a-4288-a75f-4875a92c372d)
![IMG_20230513_232021](https://github.com/FIX94/Nintendont/assets/93215451/0466222c-202c-4a8d-969a-acad5e751469)

In Mario Golf it freezes in the part of the Gamecube BIOS, it freezes on the particular frame showed in the picture every time. I have other issues like in pokemon XD, where my original GC controller being completely fine, the game recognizes a constant drift heading down, in a pokemon stadium game it just makes it unplayable. Most games work perfectly, even forcing NTSC in some of them. I launch nintendon't from usb loader GX in that app I didn't change the settings of the 2 games mentioned.

**Comment by Moonyvek** [comment]
I tried removing the iplusa/jap/pal from my USB and now it doesn't get stuck on the GC logo but the game still doesn't load, after the NGC boot animation it's just a black screen

**Comment by Moonyvek** [comment]
The game is the USA ISO file latest version from archive.org

**Comment by Moonyvek** [comment]
Changed the MMod version to the normal 6.5 in the github installation guide, nothing.

**Comment by carnage702** [comment]
Master mod is not official nintendont, like the name implies its a mod, i have no idea what they changed at all so i cant help you there, you either use the official one or ask the devs of master mod for help

latest official nintendont https://github.com/FIX94/Nintendont/raw/a4c8e0e3bda8e49491ff8f4c64a5893cd290614b/loader/loader.dol  just rename the file to boot.dol and replace in the apps folder

anyway seems you are using bad isos atleast for the freezes i would beleive, always make sure md5 matches redump.org website to verify you have a good iso.

**Comment by Moonyvek** [comment]
> Master mod is not official nintendont, like the name implies its a mod, i have no idea what they changed at all so i cant help you there, you either use the official one or ask the devs of master mod for help
> 
> latest official nintendont https://github.com/FIX94/Nintendont/raw/a4c8e0e3bda8e49491ff8f4c64a5893cd290614b/loader/loader.dol just rename the file to boot.dol and replace in the apps folder
> 
> anyway seems you are using bad isos atleast for the freezes i would beleive, always make sure md5 matches redump.org website to verify you have a good iso.

Exactly, the problem were the isos. In the tutorial I watched for nintendon't they recommended to shrink the games using GCM utility, but when I was in the Nintendon't menu I noticed that it says ciso, so I tried downloading the game in ciso format from Vimm's vault and the game worked. Later I read that people recommend to avoid shrunk isos and mods so that tutorial recommending shrinking and a mod version was kinda kekw

**Comment by carnage702** [comment]
For mario golf imo you have  2 issues
1bad save file was created or
2 bad iso

1- check  your saves folder on sd/usb if you see a 0kb file there delete it
2-check the iso md5 on sd/usb

**Comment by carnage702** [comment]
so the problem is solved? yeah you shouldnt use compressed isos unless you are really out of space, lots of games have issues when compressed in nintendont if you dont use the correct compression tool/settings, anway its always better to use full 1.35gb isos.

**Comment by Moonyvek** [comment]
The problem was downloading the game in .iso and shrinking the iso with GCM format.

**Comment by Moonyvek** [comment]
> so the problem is solved? yeah you shouldnt use compressed isos unless you are really out of space, lots of games have issues when compressed in nintendont if you dont use the correct compression tool/settings, anway its always better to use full 1.35gb isos.

yes man, thank you
