### ISSUE TITLE
Zelda Collectors Edition on Nintendont no signal

### ISSUE THREAD

**Issue by VincentGowland** [FIX94/Nintendont#1104]
Ocarina of time and majora’s mask have no video input when played. Audio is still there but no video. My nintendont settings:
![C62BEC74-AFE6-41F9-AFCF-703059DAF836](https://github.com/FIX94/Nintendont/assets/87896226/a5d9417c-e43c-4f6b-be2a-8e70361b7d65)

**Comment by carnage702** [comment]
make sure you are using a full 1.35gb iso with md5 matching redump, if you are using compressed iso or nkit there is no garantees that its working, also always try the games first with derfault settings that means puttind width back on auto/0
