### ISSUE TITLE
HIDTest Recognizes PS3 Controller input but Nintendont doesn’t.

### ISSUE THREAD

**Issue by GamerX9999** [FIX94/Nintendont#1105]
I just found my old Wii from 7 years ago and decided to home brew it to play some Luigi’s Mansion, so I got Nintendont and HIDTest and tested my PS3 Controller (It’s not an official one as they are hard to find now) and everything seemed to work fine, until I got into the game via Nintendont. I was stuck on the main menu screen and nothing worked, I tried everything I could think of and was wondering if I was doing something wrong.

**Comment by carnage702** [comment]
if it works on hidtest it means you need to make your own controller ini, nintendont doesnt have ini files made for every knockoff, hid test is too see the values to make your own ini.

**Comment by GamerX9999** [comment]
> if it works on hidtest it means you need to make your own controller ini, nintendont doesnt have ini files made for every knockoff, hid test is too see the values to make your own in

I did, but still no input

**Comment by carnage702** [comment]
> > if it works on hidtest it means you need to make your own controller ini, nintendont doesnt have ini files made for every knockoff, hid test is too see the values to make your own in
> 
> I did, but still no input

then you didnt do the ini file correctly or putted it on the correct place or correct name.

**Comment by GamerX9999** [comment]
> > > if it works on hidtest it means you need to make your own controller ini, nintendont doesnt have ini files made for every knockoff, hid test is too see the values to make your own in
> > 
> > 
> > I did, but still no input
> 
> then you didnt do the ini file correctly or putted it on the correct place or correct name.

Yep it was because I didn’t do the .ini file correctly as I had mappings for DPAD but DPAD was set to 0. Is that why it wasn’t working?

**Comment by carnage702** [comment]
i dont know , if it works now then problem solved.

**Comment by GamerX9999** [comment]
> i dont know , if it works now then problem solved.

Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”

**Comment by carnage702** [comment]
> > i dont know , if it works now then problem solved.
> 
> Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”

if you are having troubles making your own controller.ini make sure to ask for help on this thread 
https://gbatemp.net/threads/nintendont-controller-configurations.355035/

**Comment by GamerX9999** [comment]
> > > i dont know , if it works now then problem solved.
> > 
> > 
> > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> 
> if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/

I got it working, but nintendont just straight up ignores it

**Comment by carnage702** [comment]
> > > > i dont know , if it works now then problem solved.
> > > 
> > > 
> > > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> > 
> > 
> > if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/
> 
> I got it working, but nintendont just straight up ignores it

it works or it doesnt, you cant say it works and then nintendont ignores it...

**Comment by GamerX9999** [comment]
> > > > > i dont know , if it works now then problem solved.
> > > > 
> > > > 
> > > > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> > > 
> > > 
> > > if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/
> > 
> > 
> > I got it working, but nintendont just straight up ignores it
> 
> it works or it doesnt, you cant say it works and then nintendont ignores it...

It doesn’t work, I just got the error resolved in HIDTest

**Comment by GamerX9999** [comment]
> > > > > i dont know , if it works now then problem solved.
> > > > 
> > > > 
> > > > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> > > 
> > > 
> > > if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/
> > 
> > 
> > I got it working, but nintendont just straight up ignores it
> 
> it works or it doesnt, you cant say it works and then nintendont ignores it...

Is there a certain place I need to put custom configs?

**Comment by carnage702** [comment]
> > > > > > i dont know , if it works now then problem solved.
> > > > > 
> > > > > 
> > > > > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> > > > 
> > > > 
> > > > if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/
> > > 
> > > 
> > > I got it working, but nintendont just straight up ignores it
> > 
> > 
> > it works or it doesnt, you cant say it works and then nintendont ignores it...
> 
> Is there a certain place I need to put custom configs?

yes... you need to put on the root of sd or usb(depending where you have your isos) and named controller.ini  not any other name and must be controller.ini and not calling it controller.ini.ini because you have your extensions hidden on your pc.

Also just because it doesnt give errors on hid test dosnt mean the ini is well made, it just means it doesnt crash... it could still be badly done, also make sure you dont have settings on nintendont like native set to on or if you have other usb controllers plugged in at the same time.

**Comment by GamerX9999** [comment]
> > > > > > > i dont know , if it works now then problem solved.
> > > > > > 
> > > > > > 
> > > > > > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> > > > > 
> > > > > 
> > > > > if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/
> > > > 
> > > > 
> > > > I got it working, but nintendont just straight up ignores it
> > > 
> > > 
> > > it works or it doesnt, you cant say it works and then nintendont ignores it...
> > 
> > 
> > Is there a certain place I need to put custom configs?
> 
> yes... you need to put on the root of sd or usb(depending where you have your isos) and named controller.ini not any other name and must be controller.ini and not calling it controller.ini.ini because you have your extensions hidden on your pc.
> 
> Also just because it doesnt give errors on hid test dosnt mean the ini is well made, it just means it doesnt crash... it could still be badly done, also make sure you dont have settings on nintendont like native set to on or if you have other usb controllers plugged in at the same time.

I have my ISO’s in /games/ and I have read around 5 hours about making a custom ini so it shouldn’t be that bad, and I don’t have native control on nor do I have other usb controllers inserted as that is the only one that is compatible. I will try putting it in /games/ and see if that works.

**Comment by carnage702** [comment]
> > > > > > > > i dont know , if it works now then problem solved.
> > > > > > > 
> > > > > > > 
> > > > > > > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> > > > > > 
> > > > > > 
> > > > > > if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/
> > > > > 
> > > > > 
> > > > > I got it working, but nintendont just straight up ignores it
> > > > 
> > > > 
> > > > it works or it doesnt, you cant say it works and then nintendont ignores it...
> > > 
> > > 
> > > Is there a certain place I need to put custom configs?
> > 
> > 
> > yes... you need to put on the root of sd or usb(depending where you have your isos) and named controller.ini not any other name and must be controller.ini and not calling it controller.ini.ini because you have your extensions hidden on your pc.
> > Also just because it doesnt give errors on hid test dosnt mean the ini is well made, it just means it doesnt crash... it could still be badly done, also make sure you dont have settings on nintendont like native set to on or if you have other usb controllers plugged in at the same time.
> 
> I have my ISO’s in /games/ and I have read around 5 hours about making a custom ini so it shouldn’t be that bad, and I don’t have native control on nor do I have other usb controllers inserted as that is the only one that is compatible. I will try putting it in /games/ and see if that works.

no the ini must be on the root so sd:controller.ini or usb:controller.ini and not inside any folder.

**Comment by GamerX9999** [comment]
> > > > > > > > > i dont know , if it works now then problem solved.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> > > > > > > 
> > > > > > > 
> > > > > > > if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/
> > > > > > 
> > > > > > 
> > > > > > I got it working, but nintendont just straight up ignores it
> > > > > 
> > > > > 
> > > > > it works or it doesnt, you cant say it works and then nintendont ignores it...
> > > > 
> > > > 
> > > > Is there a certain place I need to put custom configs?
> > > 
> > > 
> > > yes... you need to put on the root of sd or usb(depending where you have your isos) and named controller.ini not any other name and must be controller.ini and not calling it controller.ini.ini because you have your extensions hidden on your pc.
> > > Also just because it doesnt give errors on hid test dosnt mean the ini is well made, it just means it doesnt crash... it could still be badly done, also make sure you dont have settings on nintendont like native set to on or if you have other usb controllers plugged in at the same time.
> > 
> > 
> > I have my ISO’s in /games/ and I have read around 5 hours about making a custom ini so it shouldn’t be that bad, and I don’t have native control on nor do I have other usb controllers inserted as that is the only one that is compatible. I will try putting it in /games/ and see if that works.
> 
> no the ini must be on the root so sd:controller.ini or usb:controller.ini and not inside any folder.

Ok, I put it in root and HIDTest recognizes input but Nintendont doesn’t still

**Comment by GamerX9999** [comment]
> > > > > > > > > i dont know , if it works now then problem solved.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> > > > > > > 
> > > > > > > 
> > > > > > > if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/
> > > > > > 
> > > > > > 
> > > > > > I got it working, but nintendont just straight up ignores it
> > > > > 
> > > > > 
> > > > > it works or it doesnt, you cant say it works and then nintendont ignores it...
> > > > 
> > > > 
> > > > Is there a certain place I need to put custom configs?
> > > 
> > > 
> > > yes... you need to put on the root of sd or usb(depending where you have your isos) and named controller.ini not any other name and must be controller.ini and not calling it controller.ini.ini because you have your extensions hidden on your pc.
> > > Also just because it doesnt give errors on hid test dosnt mean the ini is well made, it just means it doesnt crash... it could still be badly done, also make sure you dont have settings on nintendont like native set to on or if you have other usb controllers plugged in at the same time.
> > 
> > 
> > I have my ISO’s in /games/ and I have read around 5 hours about making a custom ini so it shouldn’t be that bad, and I don’t have native control on nor do I have other usb controllers inserted as that is the only one that is compatible. I will try putting it in /games/ and see if that works.
> 
> no the ini must be on the root so sd:controller.ini or usb:controller.ini and not inside any folder.

My wiimote+nunchuck goes to p2 so something’s happening.

**Comment by carnage702** [comment]
> > > > > > > > > > i dont know , if it works now then problem solved.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> > > > > > > > 
> > > > > > > > 
> > > > > > > > if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/
> > > > > > > 
> > > > > > > 
> > > > > > > I got it working, but nintendont just straight up ignores it
> > > > > > 
> > > > > > 
> > > > > > it works or it doesnt, you cant say it works and then nintendont ignores it...
> > > > > 
> > > > > 
> > > > > Is there a certain place I need to put custom configs?
> > > > 
> > > > 
> > > > yes... you need to put on the root of sd or usb(depending where you have your isos) and named controller.ini not any other name and must be controller.ini and not calling it controller.ini.ini because you have your extensions hidden on your pc.
> > > > Also just because it doesnt give errors on hid test dosnt mean the ini is well made, it just means it doesnt crash... it could still be badly done, also make sure you dont have settings on nintendont like native set to on or if you have other usb controllers plugged in at the same time.
> > > 
> > > 
> > > I have my ISO’s in /games/ and I have read around 5 hours about making a custom ini so it shouldn’t be that bad, and I don’t have native control on nor do I have other usb controllers inserted as that is the only one that is compatible. I will try putting it in /games/ and see if that works.
> > 
> > 
> > no the ini must be on the root so sd:controller.ini or usb:controller.ini and not inside any folder.
> 
> My wiimote+nunchuck goes to p2 so something’s happening.

if wiimote is going player 2 then nintendont is detecting ini file, if the controller has no input is because the ini is not correctly made even tough its detected.

**Comment by GamerX9999** [comment]
> > > > > > > > > > > i dont know , if it works now then problem solved.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Nope, I got an error code in HID. The code was, “ControlMessage():-7004 failed”
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > if you are having troubles making your own controller.ini make sure to ask for help on this thread https://gbatemp.net/threads/nintendont-controller-configurations.355035/
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I got it working, but nintendont just straight up ignores it
> > > > > > > 
> > > > > > > 
> > > > > > > it works or it doesnt, you cant say it works and then nintendont ignores it...
> > > > > > 
> > > > > > 
> > > > > > Is there a certain place I need to put custom configs?
> > > > > 
> > > > > 
> > > > > yes... you need to put on the root of sd or usb(depending where you have your isos) and named controller.ini not any other name and must be controller.ini and not calling it controller.ini.ini because you have your extensions hidden on your pc.
> > > > > Also just because it doesnt give errors on hid test dosnt mean the ini is well made, it just means it doesnt crash... it could still be badly done, also make sure you dont have settings on nintendont like native set to on or if you have other usb controllers plugged in at the same time.
> > > > 
> > > > 
> > > > I have my ISO’s in /games/ and I have read around 5 hours about making a custom ini so it shouldn’t be that bad, and I don’t have native control on nor do I have other usb controllers inserted as that is the only one that is compatible. I will try putting it in /games/ and see if that works.
> > > 
> > > 
> > > no the ini must be on the root so sd:controller.ini or usb:controller.ini and not inside any folder.
> > 
> > 
> > My wiimote+nunchuck goes to p2 so something’s happening.
> 
> if wiimote is going player 2 then nintendont is detecting ini file, if the controller has no input is because the ini is not correctly made even tough its detected.

How should the ini file look. Mine is this,
[controller]
VID=054C
PID=0268
Polltype=2
DPAD=0
DigitalLR=2
Power=4,01
A=3,20
B=3,40
X=3,80
Y=3,10
Z=3,08
L=12,F0
R=13,F0
S=2,08
Left=2,80
Down=2,40
Right=2,20
Up=2,10
StickX=6
StickY=7
CStickX=8
CStickY=9
LAnalog=12
RAnalog=13

**Comment by carnage702** [comment]
Are you sure your polltype is 2? And not zero?

**Comment by GamerX9999** [comment]
> Are you sure your polltype is 2? And not zero?

I set it to 0 and it gave me the error

**Comment by GamerX9999** [comment]
> Are you sure your polltype is 2? And not zero?

That’s why I have it on 2 assuming it would fix the problem

**Comment by carnage702** [comment]
> > Are you sure your polltype is 2? And not zero?
> 
> That’s why I have it on 2 assuming it would fix the problem

did you tried 1?too

also your ini is like 99% the same as the official ps3 controller ini with the only change being the polltype and power buttons so are you sure you did the ini correctly? find it hard a fake/knock off ps3 controller even shares the  same values tbh.

**Comment by GamerX9999** [comment]
> > > Are you sure your polltype is 2? And not zero?
> > 
> > 
> > That’s why I have it on 2 assuming it would fix the problem
> 
> did you tried 1?too
> 
> also your ini is like 99% the same as the official ps3 controller ini with the only change being the polltype and power buttons so are you sure you did the ini correctly? find it hard a fake/knock off ps3 controller even shares the same values tbh.

I think I tried 1

**Comment by GamerX9999** [comment]
> > > Are you sure your polltype is 2? And not zero?
> > 
> > 
> > That’s why I have it on 2 assuming it would fix the problem
> 
> did you tried 1?too
> 
> also your ini is like 99% the same as the official ps3 controller ini with the only change being the polltype and power buttons so are you sure you did the ini correctly? find it hard a fake/knock off ps3 controller even shares the same values tbh.

is there a poll type 3?

**Comment by GamerX9999** [comment]
> > > Are you sure your polltype is 2? And not zero?
> > 
> > 
> > That’s why I have it on 2 assuming it would fix the problem
> 
> did you tried 1?too
> 
> also your ini is like 99% the same as the official ps3 controller ini with the only change being the polltype and power buttons so are you sure you did the ini correctly? find it hard a fake/knock off ps3 controller even shares the same values tbh.

I tried 0,1 and 2 and still no input

**Comment by carnage702** [comment]
> > > > Are you sure your polltype is 2? And not zero?
> > > 
> > > 
> > > That’s why I have it on 2 assuming it would fix the problem
> > 
> > 
> > did you tried 1?too
> > also your ini is like 99% the same as the official ps3 controller ini with the only change being the polltype and power buttons so are you sure you did the ini correctly? find it hard a fake/knock off ps3 controller even shares the same values tbh.
> 
> I tried 0,1 and 2 and still no input

no idea really you should just get another controller imo.
