### ISSUE TITLE
Games not showing up even after putting game.iso not game.iso.iso

### ISSUE THREAD

**Issue by Clawstruckwizard** [FIX94/Nintendont#1109]
I’ve fallowed multiple tutorials and I have show file type and my game in games folder with its title (Mario Kart Double Dash) and when I put the SD card in my Wii U Nintendont says “warning: Sd:/games/ contains no GC titles.”

**Comment by carnage702** [comment]
if games are not found is becuase the path is not correct the path should be 

sd:games/anyname/game.iso
example for windwaker

sd:games/windwaker/game.iso

**Comment by Clawstruckwizard** [comment]
![image](https://github.com/FIX94/Nintendont/assets/136380947/f79e2582-25f4-4aa6-9939-635fa79a606d)
![image](https://github.com/FIX94/Nintendont/assets/136380947/3274b5d3-a4b0-4e0d-8e56-3b12f44e2623)
![image](https://github.com/FIX94/Nintendont/assets/136380947/cf979698-f87b-4a49-aef4-177695b1a566)
Im Super confused because believe the pathing is right but it still won’t launch.

**Comment by Clawstruckwizard** [comment]
I have a micro sd card to large sd card adapter should that change anything?  Do I need another home brew app to launch games I have no idea what’s wrong.

**Comment by Clawstruckwizard** [comment]
That worked! Thank you so much for all of your time, I really appreciate it!
