### ISSUE TITLE
Issue: Some Of My GCN Games Don't Ask Me To Enable Progressive Scan When I Use Gamecube Bios

### ISSUE THREAD

**Issue by SuperWeegeeGameplays2401** [FIX94/Nintendont#1111]
Please Help Me, Some Of My GCN Games Ask Me To Enable Progressive Scan When Using Bios, But Some Of The Other Games Don't Ask Me To Enable Progressive Scan, And To Make Them Ask, I Need To Disable The Use Of Bios.

**Comment by carnage702** [comment]
you can hold b while booting any game that is progressive scan compatible to make it show up, it was like this on the gamecube too.

not every game shows it automatically, obviously the game needs to have progressive scan coded in the first place tough.

 from nintendo itself
"Manual data
Visit www.nintendo.com or call 1-800-255-3700). To activate the progressive scan mode, press and hold the B Button while the Nintendo GameCube logo is being displayed until the message "Display in Progressive Scan mode?" appears. Select YES to activate the mode."

**Comment by SuperWeegeeGameplays2401** [comment]
Oh I Didn't Know That
