### ISSUE TITLE
Quick setup links (not including loader.dol) just redirect me to pages with meta.xml and the icon on it respectively

### ISSUE THREAD

**Issue by 4ur3o** [FIX94/Nintendont#1113]
Meta.XML redirects to https://raw.githubusercontent.com/FIX94/Nintendont/master/nintendont/meta.xml
Icon.PNG redirects to https://raw.githubusercontent.com/FIX94/Nintendont/master/nintendont/icon.png
Loader.DOL just downloads the file normally.

**Comment by carnage702** [comment]
that is normal... you right click the link and choose save link to keep those files.
