### ISSUE TITLE
Sonic Gems Collection has no sound??

### ISSUE THREAD

**Issue by thfKelsey** [FIX94/Nintendont#1115]
wanted to play sonic gems collection on wii since i dont have a gamecube or a ps2 anymore
but theres absolutely no sound coming from the game, its silent
any way to fix this?

**Comment by thfKelsey** [comment]
nevermind theres sound. but only on sonic the fighters. and its a buzzing sound

**Comment by carnage702** [comment]
Is your ISO 1.35gb? Does the md5 match redump?
