### ISSUE TITLE
Nintendont don't show my Games

### ISSUE THREAD

**Issue by Kirmazz** [FIX94/Nintendont#1118]
Hello,
Like i said in the title. Nintendont won't show my games, it only show me the disc in the Wii. I already did /games/"anything"/game.iso (I've been careful, it is really game.iso, and not game.iso.iso). I tried on my USB and my SD card, but it is the same. I also tried /games/"anything".iso and /games/game.iso, but still the same. Also, USB loader GX shows me the game. I'm waiting for your response.
Thanks
(Sorry if I appear to be disrespectful, I'm french, and I wanted to be kind, just to know)

**Comment by carnage702** [comment]
Are your isos actual isos? i mean 1.35gb iso and not those nkit isos?

**Comment by Kirmazz** [comment]
Hello, thank you to take some of your time for my problem. I don't know if it is nkit, but it it is 1.36 gb (super Mario sunshine)

**Comment by carnage702** [comment]
dolphin and nintendont are totally different things, one is an emulator the other is not.

take a pcture off your nintendont screen that shows no games and then a screenshot of the root of sd /usb, then a picture of the games folder and then a picture inside mario sunshine folder.

**Comment by Kirmazz** [comment]
Hello, here's are the photo (sorry if my response was late, but yesterday, it was late in France) :

Nintendont:

![ADMIX • 2.6 • 20230707_092420174.MP.jpg](https://github.com/FIX94/Nintendont/assets/138782902/36ea198a-15d8-4c7f-bfac-71e8976aa146)

USB root:

![Screenshot_20230707-084816_Files by Google.png](https://github.com/FIX94/Nintendont/assets/138782902/bc6eb155-bd7a-4fa7-81df-82cad4c848d1)

USB/games:

![Screenshot_20230707-084819_Files by Google.png](https://github.com/FIX94/Nintendont/assets/138782902/119e0289-9a56-4cf7-b3a0-06edadc65e79)

USB/games/Super Mario Sunshine [GMSP01]:

![Screenshot_20230707-084822_Files by Google.png](https://github.com/FIX94/Nintendont/assets/138782902/e53cd90f-ef37-4b85-96b7-2094edacad83)

**Comment by carnage702** [comment]
What are you using? A Mac or something? How is your USB device formatted? Fat 32? Are you choosing USB when booting nintendont?  Does your USB device work on any other Wii homebrew?
Is your USB device partitioned?

**Comment by carnage702** [comment]
Are you connecting the USB directly to the Wii USB ports?   Do you have an SD card? Could you try the games on SD card to see if they work? To see if it's a file error or just your usb.

**Comment by carnage702** [comment]
What does it say when you pick USB or SD? Does it say no games found on games folder? Or no games directory found?

**Comment by Kirmazz** [comment]
Thank you for your help, really, but don't worry anymore, it was a file problem, I tried with Zelda Wind Waker, and it found it. Thank you again and have a great day, goodbye

**Comment by carnage702** [comment]
Yeah nintendont prefers perfect is, no those modified versions running around, try to compare your ISO md5 with redump.org to make sure they are good isos
