### ISSUE TITLE
Question: What are all the buttons to change the layout of controllers?

### ISSUE THREAD

**Issue by udcnicanisidcshbiu** [FIX94/Nintendont#1120]
What are all the buttons or button combinations to change the layout of the controller? i mainly play double dash and sometimes the layout just changes and i cant figure out why it happens. also by layout i mean like it changes what buttons 
"press". like the wii + nunchuck for example, i was playing and suddenly it changes and now the back buttons are doing something else (i dont remember what they were set to but i think it was L and R)

**Comment by IceYetiWins** [comment]
This link details how to switch control configurations: https://gbatemp.net/threads/nintendont-wiimote-nunchuck-support-discussions.371356/
