### ISSUE TITLE
meta.xml outdated (easy, low prio, ocd fix)

### ISSUE THREAD

**Issue by kevintosh** [FIX94/Nintendont#1122]
Hi, I noticed that the meta.xml was still showing the 4.431 version and a 2016 release date, which prompted me to try to download the v6.500 from elsewhere.

But I'm curious, so I diff'd the loader.dol with the v6.500 from somewhere else, and no diff.

I also noticed the last commit (2022-12-15) to loader.dol showed minor v change to 6.500. So I just figured the meta.xml must be outdated. (is there any way to generate it auto? I bet there must be, if not feel free to ask me, I might try to find a way)

Just for my inner peace of mind I changed it manually on my system. Here it is updated:
```html
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<app version="1">
	<name>Nintendont</name>
	<coder>FIX94, crediar</coder>
	<version>6.500</version>
	<release_date>20221215000000</release_date>
	<short_description>Gamecube Loader</short_description>
	<long_description>Commiters: GerbilSoft, JoostinOnline, GreyRogue, Howard, Cyan 

 Project website: https://github.com/FIX94/Nintendont 

Nintendont allows you to run GameCube games on a Wii or Wii U from an SD or HDD device.</long_description>
	<no_ios_reload/>
	<ahb_access/>
</app>
```

**Comment by carnage702** [comment]
The meta.xml is updated automatically everytime you start a game in nintendont, no need to do it here
