### ISSUE TITLE
Wii Classic Controller repeatedly disconnecting when playing Pokémon Colosseum (Europe)

### ISSUE THREAD

**Issue by Barbarossa893** [FIX94/Nintendont#1128]
Hello,

there is a strange issue I'm experiencing when playing Pokémon Colosseum with a genuine Wii Classic Controller. About 20-40 minutes into playing the game, the Classic Controller suddenly stops recognizing inputs, freezing while pointing northeast (↗) according to the game. While this is temporarily fixed by disconnecting and reconnecting the Classic Controller from and to the Wiimote, it does occur repeatedly after some time has passed and so far only happens when playing Pokémon Colosseum.

![Nintendont Settings](https://github.com/FIX94/Nintendont/assets/143424303/ddf7f755-f1f1-4bc2-98b9-8527feeeab03)

**Comment by carnage702** [comment]
are both classic controller and wiimote 100% official? none of them is 3rd party? this never happened to me so i dont know how to fix since i cant replicate it.

**Comment by Barbarossa893** [comment]
> are both classic controller and wiimote 100% official? none of them is 3rd party? this never happened to me so i dont know how to fix since i cant replicate it.

They are. The Nintendo and Wii brand logos as well as the model number are in all the right places.

And while I only have one other Gamecube game dumped (FE: Path of Radiance), the disconnecting issue only happens when playing Pokémon Colosseum.

I've also seen that there was another issue with the controls in Pokémon Colosseum some years back (https://github.com/FIX94/Nintendont/issues/282). Might what I'm experiencing somehow be related to that?

**Comment by carnage702** [comment]
> > are both classic controller and wiimote 100% official? none of them is 3rd party? this never happened to me so i dont know how to fix since i cant replicate it.
> 
> They are. The Nintendo and Wii brand logos as well as the model number are in all the right places.
> 
> And while I only have one other Gamecube game dumped (FE: Path of Radiance), the disconnecting issue only happens when playing Pokémon Colosseum.
> 
> I've also seen that there was another issue with the controls in Pokémon Colosseum some years back (#282). Might what I'm experiencing somehow be related to that?

hmm no that wasnt a disconnect but a bad value they never disconnected, just having model number and wii logos doesnt make a controller official

check the screws only nintendo uses triwing screws

![maxresdefault](https://github.com/FIX94/Nintendont/assets/12446178/3990faae-dccb-42b5-b39d-bab71f17a477)
if they are regular 4 sided screws then its fake.

**Comment by Barbarossa893** [comment]
All the screws on my controller look exactly like the one shown in the picture.

**Comment by carnage702** [comment]
> All the screws on my controller look exactly like the one shown in the picture.
> 
> Edit: Thinking about it, I'm not sure if it's actually a disconnect that I'm having. The Wiimote's blue lights don't go out, but the Classic Controller simply freezes and stops registering inputs.

that happens to me randomly during wii games too due to the connection on my CC being a bit loose and rusty sometimes a position is all it takes.

**Comment by Barbarossa893** [comment]
>> that happens to me randomly during wii games too due to the connection on my CC being a bit loose and rusty sometimes a position is all it takes.

I see, gotta try that out. Thanks for your help.

**Comment by carnage702** [comment]
> > that happens to me randomly during wii games too due to the connection on my CC being a bit loose and rusty sometimes a position is all it takes.
> 
> So it just happened again and repositioning the Wiimote does nothing to restore the connection. Still, the issue lies most likely with my controller, right?

so it never happened to me but who knows, do you have any other controllers around? maybe try with any different one?

**Comment by carnage702** [comment]
so any updates?

**Comment by Barbarossa893** [comment]
> so any updates?

So far, it doesn't happen when using Wiimote + Nunchuk. But that seems to deplete the battery of my Wiimote much faster.

Still, it's probably just my Classic Controller getting old.
