### ISSUE TITLE
Dualshock 4 V1 with no battery

### ISSUE THREAD

**Issue by ThiGhisleri** [FIX94/Nintendont#1130]
I tried to connect a DS4 V1 via usb on wii nintendont and my console just shutdown. My controller doesn't have battery anymore and my other PS4 controllers with battery connect just fine.

**Comment by carnage702** [comment]
So?  What do you want me to do? The Wii USB ports probably don't have enough power to direct feed a controller without battery, just get a battery and charge  it...

**Comment by ThiGhisleri** [comment]
OK arrombado.

Em sáb., 2 de set. de 2023 às 03:00, pedro702 ***@***.***>
escreveu:
