### ISSUE TITLE
Crashes on Init DI

### ISSUE THREAD

**Issue by MrE-Buckets** [FIX94/Nintendont#1131]
Hi. I am unable to load Teenage Mutant Ninja Turtles (GTFEA4). It gets to Init DI then just shuts the system off.
I am on WiiU
Loader v6.501
Firmware 58.25.32

Tried both nkit and iso
I've tried changing setting for forced widescreen etc on/off and no combination has made a difference.

Any help would be appreciated.

**Comment by carnage702** [comment]
take a picture of your nintendont settings and check your iso md5

**Comment by carnage702** [comment]
also check your saves folder and delete any 0kb file

**Comment by MrE-Buckets** [comment]
I deleted the 0kb file I found and still no success.
I also posted all the pictures I thought could be helpful.

![WIN_20230904_15_19_40_Pro](https://github.com/FIX94/Nintendont/assets/143972370/d85781f0-23dc-4742-ab80-4718588ddcb6)
![WIN_20230904_15_19_53_Pro](https://github.com/FIX94/Nintendont/assets/143972370/bf36b9b5-af09-47f0-8e39-a20b90110a4d)
![WIN_20230904_15_25_56_Pro](https://github.com/FIX94/Nintendont/assets/143972370/e9340d13-7a17-46ef-92db-76b30f42701f)
![WIN_20230904_15_26_21_Pro](https://github.com/FIX94/Nintendont/assets/143972370/e1b80830-b5d1-4a26-8cec-5315f98598a4)
![WIN_20230904_15_26_30_Pro](https://github.com/FIX94/Nintendont/assets/143972370/079401ac-a7f1-4b37-bed4-f0bbd8eab36f)

https://github.com/FIX94/Nintendont/assets/143972370/13dd2cee-0973-48dd-a1f1-edf79e6c7187

**Comment by carnage702** [comment]
your full of settings that can break games, you should always turn this off before starting a game 

force progressive to off
Unlock read speed to off
language to auto
video to auto

only after you see that a game works is when you can start enabling settings to see if they dont break.

**Comment by carnage702** [comment]
also make sure your sd card is unlocked and has space to creat the savefile.

**Comment by MrE-Buckets** [comment]
There's plenty of room on the SD card and it is 100% unlocked. Changed all those settings and still nothing

![image](https://github.com/FIX94/Nintendont/assets/143972370/5ea72448-dc48-48fb-a977-6e81833dcb4d)
![WIN_20230905_07_44_35_Pro](https://github.com/FIX94/Nintendont/assets/143972370/a9ac0c32-27a0-42c2-9cb7-250ba1cd3e8d)

https://github.com/FIX94/Nintendont/assets/143972370/bb18d1fc-8297-4b1e-9e12-c6e7e24f47b5

**Comment by carnage702** [comment]
just wondering turn memory card emulation off and try starting it 

if it still does that 


 download the pal version and try that if it still does the same then i will check it out myself. but init di doesnt even load the iso imo

**Comment by MrE-Buckets** [comment]
Turning off Memcard emulation seems to have worked. The new problem being that I can't save. So just to see I turned Memcard Multi on and that seems to have done the trick. Now it loads the game and I'm able to save.

Thank you so much!

https://github.com/FIX94/Nintendont/assets/143972370/4ef6405f-31cb-4ff5-96cd-f148f47962ee

![WIN_20230905_10_43_31_Pro](https://github.com/FIX94/Nintendont/assets/143972370/92742449-32cc-4556-9f47-fd1b59b57ba2)
![WIN_20230905_10_47_37_Pro](https://github.com/FIX94/Nintendont/assets/143972370/589a9116-338a-48d4-affc-3f70713d8dd9)
![WIN_20230905_10_46_55_Pro](https://github.com/FIX94/Nintendont/assets/143972370/48d8b37f-42f0-472e-a707-fd2c86606e92)

**Comment by carnage702** [comment]
the error is you didnt delete the correct memory card that was corrupted in the first place. turning multi on will make your other games not see the memory cards you have for them.

So go to your sd card go to saves folder and delete the save for this specific tiutle, it should have the gameid and let it create a new one.

**Comment by MrE-Buckets** [comment]
Yup, you're right and now it boots no problem. I didn't delete it because it was 192kb and not 0kb. Everything else is 256kb and I didn't notice it was an outlier.

Thanks again for all your help
