### ISSUE TITLE
Can't Compile Using Available Versions

### ISSUE THREAD

**Issue by godreborn** [FIX94/Nintendont#1132]
I can compile nintendont on the latest, but it has the freezing when exiting issue.  however, compiling it with the mentioned versions doesn't work for me neither in msys or cmd prompt.  it fails at the asm section, almost immediately, during compiling.  I think I remember having this issue in the past, but I don't remember how to fix it.

**Comment by carnage702** [comment]
i only compile nintendont with the bat file and works fine for me.

**Comment by godreborn** [comment]
> i only compile nintendont with the bat file and works fine for me.

this is what happens to me:

![image](https://github.com/FIX94/Nintendont/assets/13548481/56342608-7d0d-4eb5-8af8-40d10f40cded)

**Comment by godreborn** [comment]
my thinking is that it has something to do with libfat, but I do not know for sure.  I'd need your libfat.a, fat.h, and fatversion.h.

**Comment by godreborn** [comment]
alright, I tried my libfat.  it didn't do any better, so I have no idea what's going on.  something must be missing.

**Comment by carnage702** [comment]
i only use this and i dont even have those libfat files you mentioned tbh

https://www.mediafire.com/file/x16huuoyap8kina/devkitPro.zip/file

**Comment by godreborn** [comment]
> i only use this and i dont even have those libfat files you mentioned tbh
> 
> https://www.mediafire.com/file/x16huuoyap8kina/devkitPro.zip/file

thanks.  I'll try to figure out what's missing from that as it goes past the error.

**Comment by godreborn** [comment]
it's something in the tools folder that's the problem.  I never figured it out, but I was able to build with yours with some modifications.  the keys were outdated, the rules seemed to be too old, and b2s was also too old.  I mixed the old with the new.  nintendont works well (no freezing upon exiting):  https://www.mediafire.com/file/658xpwduxbnn3a7/devkitPro.zip/file

**Comment by godreborn** [comment]
thanks for the dump of your devkitpro folder.  I wouldn't have been able to manage this without you.

**Comment by carnage702** [comment]
glad you sorted it out.
