### ISSUE TITLE
8BitDo SN30 pro Xbox version won't work

### ISSUE THREAD

**Issue by Mohanned2530** [FIX94/Nintendont#1133]
i have 8BitDo SN30 pro Xbox version i tested it on hid test and it changes the values after changing controller ini when i go to nintendont it auto select usb when i click down on controller it go to games menu then stuck

https://assets.xboxservices.com/assets/da/d9/dad9c70e-e3cb-4c61-b4f3-0b2fe7775388.jpg?n=7701441_gallery_01_1056x594.jpg

**Comment by carnage702** [comment]
you need to make your own controller ini by scratch since that controller is probably different from the rest, you cant expect to just work.

**Comment by Mohanned2530** [comment]
after a lot of search on gbatemp i made controller config for it yesterday now it works perfect so i can send it to you to put on controllers folder here
