### ISSUE TITLE
Speedrunning Mode

### ISSUE THREAD

**Issue by Figgy2112** [FIX94/Nintendont#1146]
Could there be a mode added that adds speedrun capabilities from USB, because with speed running, you don’t need saves and that type of stuff since it’s a speedrun and it would just need to load the rom into the default GameCube hardware that Wii already has and give read speeds as if you
were reading a real disc, you wouldn’t need the virtual stuff since saves aren’t needed most of the time Nintendont is currently banned from most speedrunning communities because of the enhancements, but couldn’t this be added to make it easier for people to speed run from USB

**Comment by carnage702** [comment]
No... nintendont runs in wii mode with wii cpu speed you cant change that, you cant make it run slower because we dont control the cpu its just a wii app running on wii mode...

**Comment by Figgy2112** [comment]
Then, is there a way to get a ROM to run in the native game cube mode?

**Comment by eku** [comment]
> Then, is there a way to get a ROM to run in the native game cube mode?

[DiosMios (Lite) ](https://github.com/Homebrews/DIOS-MIOS)might be an option.
