### ISSUE TITLE
Physical JVS I/O Hardware Support (Triforce)

### ISSUE THREAD

**Issue by NewGBAXL** [FIX94/Nintendont#1147]
Would it be possible to route the emulated JVS I/O signal (for Triforce hardware) through the Wii's USB slots?
The arcade JVS daughterboard could then be directly connected to the Wii allowing the Wii to run the actual arcade machines and custom hobbyist hardware.

**Comment by carnage702** [comment]
this will never happen, crediar was the one that bought a triforce machine and made the code and he left even before nintendont could play more than windwaker so no more triforce work was ever done, and this seems like it would be used by like 2 people in the world at best... your better off just buying an arcade cabinet yourself why use the wii at that point seems pointless.

**Comment by NewGBAXL** [comment]
Couple of oversights on my part, primarily that JVS wires up the USB port in such a way that is incompatible (and dangerous!) to use with standard USB ports, the actual solution would be much more simpler: allowing SI passthru for Triforce, coupled with a RP2040, would get the job done.
That being said the hardware side of things would be much more complicated and largely unhelpful. Instead of emulating JVS on the hardware, it would make much more sense to **hook the Triforce SDK functions and simply route them to extra hardware** if created, usable with standard USB.
The Triforce SDK hasn't been well reversed and documented (yet!) but should improve things like this in the future.
