### ISSUE TITLE
"sd:/games/" not found despite all paths being named properly. No game.iso.iso or anything.

### ISSUE THREAD

**Issue by luigiman106** [FIX94/Nintendont#1148]
Title says it all. I've tried EVERYTHING and nothing has worked. I keep getting this same error.
![image](https://github.com/FIX94/Nintendont/assets/43503169/c8a3cd7a-b0c3-42b6-ae0c-0633c9b8e0b2)
![image](https://github.com/FIX94/Nintendont/assets/43503169/70422ae7-b47d-4062-8ff3-f2ac906a96ef)
![image](https://github.com/FIX94/Nintendont/assets/43503169/511d0431-4bd8-424f-8693-e9027f5e4534)

**Comment by luigiman106** [comment]
Forgot to mention, the SD card I'm using is formatted as FAT32. It is a 256GB SD card, and for some reason, it works on a 2GB SD card but not the 256GB.

**Comment by carnage702** [comment]
> Forgot to mention, the SD card I'm using is formatted as FAT32. It is a 256GB SD card, and for some reason, it works on a 2GB SD card but not the 256GB.

this jsut screams fake card...

you bought it cheapo from one of those online retaillers right?

sd card is probably fake and its all messed up.
get a new sd card or try from usb.

**Comment by luigiman106** [comment]
It's a SanDisk SD Card, and I bought it from Best Buy. I used guiformat to format it as FAT32. I don't know what's going on.

**Comment by luigiman106** [comment]
Had to buy a new card yesterday anyway, the 256GB one was on its deathbed and died. The 32GB one I got from Best Buy also didn't work... until I formatted it with guiformat for some reason? I'm confused, but hey, it works now. Thanks.

**Comment by luigiman106** [comment]
Nevermind. "sd:/games/" was not found again. I've formatted this card at least 5 times now with guiformat to make sure nothing's going wrong, but this keeps happening. I knew something started going wrong after any game I tried to load... didn't load. I don't know why it's not working anymore. I literally just bought this card and now Nintendont isn't working anymore?

![image](https://github.com/FIX94/Nintendont/assets/43503169/1ad6e40d-7fe2-407a-8603-29a3092aa2c3)

Does it have to do with this? Because whenever I try to turn this off, it turns back on. And also, the SD card isn't locked. What the hell am I doing wrong?

**Comment by carnage702** [comment]
yeah read only means nintendont cant write on it, therefore it wont work, why is your card being read only i have no idea.

usually cards go read only when they are about to die, could it be your console sd card slot is dying and corrupting your cards? or something, since you said  you bought new cards and such.

**Comment by carnage702** [comment]
Also why are you using giu formatter? isntead of sd card formatter?
https://www.sdcard.org/downloads/formatter/

**Comment by luigiman106** [comment]
I used the SD Card Formatter, same results. I doubt the SD card slot is corrupted, because I have a 2GB card that still works completely fine, but only holds one game. So, I don’t know.

**Comment by carnage702** [comment]
because its most liely your micro sd adapter, the 2gb card works because its a straight up sd card im guessing while you are using the same adapter on all your tests, those adapters fail very easily and are crap, try another adapter.

**Comment by luigiman106** [comment]
No, I don't use a microSD card. I've already tried one and it hasn't worked. I've resorted to using a USB to load the Gamecube games anyway, since it's been working flawlessly.

**Comment by carnage702** [comment]
this just seems to be an issue with your sd cards or adapters or whatever since like you said 2gb card works and usb too so its not nintendont fault, better check those sd cards imo.
