### ISSUE TITLE
Please consider implementing alternative storage destination for memory card emulation

### ISSUE THREAD

**Issue by littlegamer87** [FIX94/Nintendont#1149]
Hello,

Rationale for my request is improved performance on mini form factor usb sticks like Sandisk Ultrafit usb. 

I have been running tests with this memory type in a wii u application. I recognize many advantages like not requiring a power solution, it is so small it can be hidden, high capacity and likely reliable. It performs fine in read only applications like Wii (U) games as data is saved to nand. 

Nintendont requires memory card emulation on the same usb device. When memory card emulation is writing to this memory while playing a game, it results in issues like no controller response for 5 seconds, stuttering audio, in a specific condition crash a game. Is it feasible to have this written to different locations like sd or nand, rather then requiring it on the same medium? That would likely fix this nuisance with otherwise very useful memory devices.

Thank you

![image](https://github.com/FIX94/Nintendont/assets/17988200/e34f877f-260a-4471-acce-23e7eeaa3319)

**Comment by carnage702** [comment]
no, when nintendont games are running nintendont can only mount the device its running the games, there is no memory free to mount multiple devices and then the games.
