### ISSUE TITLE
Inputs frozen with USB controllers

### ISSUE THREAD

**Issue by Revolucoin** [FIX94/Nintendont#1174]
Hi! I've been having this issue for more than a year so right now I want to know if this is a normal behavior or there is something wrong with my configuration or my console.

My objective was to recreate the conditions I used to play a game on Dolphin emulator in the past, now on the Nintendo Wii I bought, so this included using a DS4 controller (v2) with custom mappings. 

To remap the controller, I edited the corresponding file swapping the values except that I couldn't find the exact value for L1 since the original gamecube controller only got one button in the left shoulder so I "guessed" the value after trial and error to make it work as I wanted (I bound what it would be the Y button on the gamecube controller to L1 in my DS4). 

**My issue** is that everything works smoothly until after some time playing my inputs get frozen on intervals that vary between 2 and 8 seconds approximately. This doesn't work as a controller disconnection: instead of shutting down my inputs, my game keeps pressed the last inputs from before this happens. As an example, if I hold forward in the stick when this happens, the forward input is forced to be kept during the mentioned interval and I'm unable to do anything in the meantime. 

The intervals happen seemingly at random times, I can't figure a pattern at all, just that this starts happening after some time playing. I discarded anything related to heat already so it doesn't seem to be a physical issue, just in case. 

This issue happens in any USB controller I connect, I tested 4 different controllers with and without the custom mapping files present and it persists. The only exception is the Gamecube controller through the native port, which I rather avoid for what I'm doing but still I want to get the issue fixed.

As I said before, first I would want to know if this is a somewhat expected or common issue so any suggestion or idea about what could fix the problem is very welcome.

**Comment by carnage702** [comment]
Never heard anything like this from anyone so no it's not common error or expected, and since it's random I don't know how to help you.

**Comment by Revolucoin** [comment]
Well, you did already by telling me this is not common or expected. If my configuration works in other systems then I can start looking at hardware problems instead. Thanks for the quick response!

**Comment by Revolucoin** [comment]
For the sake of precedents in case anybody gets the same issue, if you ever hear again about this it was a hardware issue. Everything works perfectly with different hardware so that's a closure for this.
