### ISSUE TITLE
gamecube nintendont games wont load

### ISSUE THREAD

**Issue by augustskies234567** [FIX94/Nintendont#1196]
so i use a usb and um i put the gamecube isos on it and none of them work it takes me to a black screen and shit and also they dont work when i have on emulate mem card so idk what the issue is but wii games work perfectly fine on usb loader soo someone help me please

**Comment by carnage702** [comment]
not all usb devices work with nintendont specially if your using a flashdrive, even tough wii games might work nintendont might not, try using an sd card first put nintendont and one game in there and if your setup is right and the game works then its your usb device issue.

**Comment by augustskies234567** [comment]
I put nintendont on the sd card and the game on ther but now it wont show up in the homebrew channel

**Comment by augustskies234567** [comment]
nevermind i got it to work but the game still doesnt run and its a black screen

**Comment by augustskies234567** [comment]
its been sitting on a black screen for like a hour

**Comment by augustskies234567** [comment]
it also initiates mem card emulation and everything.. but the game just doesnt work and goes to a black screen..

**Comment by augustskies234567** [comment]
welp i dont know what to do because i was gonna try a better sd card i had but it got jammed in the sd card slot on my laptop and it wont come out sooooooo

**Comment by augustskies234567** [comment]
Ok update: i tried running the game with memcard emulation, it went through but it was just a black screen, i check the sd card and it made a saves folder and theres a save data thingy in it? but idk why the games not loading/playing ?? 
![Screenshot 2024-04-25 132632](https://github.com/FIX94/Nintendont/assets/168047184/0aa1539a-8075-4c59-9e73-a717bede199e)

**Comment by carnage702** [comment]
could be you are just forcing bad settings or using a bad iso.

first take a picture of your nintendont settings, second make sure you use a full iso 1.35gb with has MD5 check with known good dumps  on redump.org.

**Comment by augustskies234567** [comment]
![image](https://github.com/FIX94/Nintendont/assets/168047184/e6b67258-1b94-4ad8-94e9-9e349437024c)

**Comment by augustskies234567** [comment]
i got it to work thanks for your help!
