### ISSUE TITLE
REQUEST: Ability to cleanly exit a game running in Nintendont

### ISSUE THREAD

**Issue by GoogleCodeExporter** [FIX94/Nintendont#120]
```
What steps will reproduce the problem?
1. Launch a game
2. Try to exit back to the launcher/HBC/WiiMenu/whatever.
3. Realize that the only way is to hit the Power button on the Wii, which 
initiates a full shutdown.

What is the expected output? What do you see instead?
I would expect some sort of Wii Menu / Reset like you get with a Wii game when 
you hit the Home button on a Wiimote.

The issues this causes are the following. First, there is no consistent way to 
get out of a game. The RZBdown combo is a half-fix that sometimes works. 
However, if you do this in Super Mario Sunshine, the system locks up 
completely, and then USB Loader GX (used to launch Sunshine through Nintendont) 
refuses to launch any games whatsoever and an IOS 249 reinstall is necessary.

What revision of Nintendont are you using? On what system Wii/Wii U?
r216 on Wii 4.3

Please provide any additional information below.

```

Original issue reported on code.google.com by `vassi1...@gmail.com` on 13 Nov 2014 at 7:34

**Comment by MT-Modder** [comment]
Could you maybe reopen this because it's still an issue? 

I'd like to use nintendont and USB loader GX together and have the game exit "cleanly". But if it can't be fixed then so be it.

**Comment by GB-CG** [comment]
@MT-Modder I wonder about this too as I couldn't button-reset Nintendont before. I've tried 4.409 with Twlight Princess just now and it seems to be working now.

**Comment by carnage702** [comment]
you can just ask cyan for a usbloader gx fowarder with a full stub once you have it you can always exit back to the usbloader gx main menu.

**Comment by MT-Modder** [comment]
@GB-CG Hitman 2 and others don't work for me...maybe it's just certain games.

@carnage702 Well I have priiloader and use USB loader GX as the installed file. I don't like to use the wii menu.

**Comment by tallpr24** [comment]
method to force GC games to autoboot directly in nintendont when opened via wiiflow?  currently when i launch a GC game it brings up the default nintendont screen where i have hit a for usb or sd and then the list of GC games pulls up.  I dont see any options in the wiiflow gui for autoboot ?

I'm using WiiFlow Master mod (4.2.3-r1054)
nintendont v3.324
on wii u--virutal wii
usb external hard drive fat 32, 32kb cluster

**Comment by carnage702** [comment]
why are yoy using nintendont that is old as hell? latest nintendont is 4.423

**Comment by sonic78fast** [comment]
I'm having an issue too. I exited mario kart double dash on my wii u by powering it off. Then when I turned it back on, after i click to login with my mii, nothing loads and the background still play music and background move. I have to power it by unplugging it since it freezes when using the power button.

**Comment by carnage702** [comment]
his issue is outadated nintendont so its yours most likely, redownload rom here the latest version.

**Comment by GormAuslander** [comment]
I would also like this functionality
