### ISSUE TITLE
Need help compiling

### ISSUE THREAD

**Issue by Willicious** [FIX94/Nintendont#1208]
Downloaded the devkitPro folders as instructed, set these up in C:\, followed the limited build instructions as best as I could. Can't seem to get past this error when running Build.bat:

Documents/GitHub/Nintendont/loader/include/global.h:24:10: fatal error: gctypes.h: No such file or directory
 #include <gctypes.h>

gctypes.h is present in libogc-1.8.23-1\include, so... what am I doing wrong???
 
 Anyone have a proper step-by-step compiling guide (i.e. from having _nothing_ on your system to having a successfully built boot.dol)?

**Comment by Willicious** [comment]
Managed to do it, and created [this pull request](https://github.com/FIX94/Nintendont/pull/1209) to change the button combo (if rejected, at least people can see which code needs to be changed if they wish to mod & build their own copy).

Here are build instructions for those that might need it:

**How to build your own copy of Nintendont on Windows - a step-by-step guide**

1) If you haven't already, Clone [the Nintendont GitHub repo](https://github.com/FIX94/Nintendont)
2) Install the latest version of [devkitPro](https://devkitpro.org/) (you'll replace some folders later)
3) Download the folders from [the mediafile like on Nintendont's GitHub page](https://www.mediafire.com/folder/j0juqb5vvd6z5/devkitPro_archives)
4) Go to C:\devkitPro\ and rename the following folders:

devkitARM - rename to "devkitARM-original"
devkitPPC - rename to "devkitPPC-original"
libogc - rename to "libogc-original"

5) Paste the replacement folders from Nintendont - make sure they're named devkitARM, devkitPRO and devkitPPC respectively (you have to unzip everything to get to the actual folder itself)
- NOTE that the mediafire link contains 2 devkitPPC versions. The one called devkitPPC r35-2 is the latest. Copy the other one in first (it should simply be called devkitPPC), then paste the one called devkitPPC r35-2 over it, choosing to replace any duplicate files

6) Once you're sure the above folders have been correctly replaced, go ahead and open your cloned copy of Nintendont
7) In the root directory, run Build.bat - if all went well, it should build a brand new copy of loader.dol in the "loader" folder (check the timestamp to make sure it's the one you just built)
8) Go ahead and make any changes you want to Nintendont!

**Comment by simulified** [comment]
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by Jonaykon** [comment]
It keeps failing on the 'Building FatFS library for ARM' stage for me

```
Building FatFS library for ARM

make -C fatfs -f Makefile.arm
make[1]: Entering directory '/home/user/Downloads/Nintendont-master/fatfs'
CC      ff-arm.o
make[1]: *** [Makefile.arm:42: ff-arm.o] Error 1
make[1]: Leaving directory '/home/user/Downloads/Nintendont-master/fatfs'
make: *** [Makefile:45: fatfs/libfat-arm.a] Error 2
```
