### ISSUE TITLE
NGC Controller doesn't work on game selection screen.

### ISSUE THREAD

**Issue by izackp** [FIX94/Nintendont#121]
The Controller works fine when selecting between SD and USB, and when starting Mario Party 6 and selecting whether not to enable progressive scan mode. However, the controller doesn't work in game, or in the game selection screen. 

Normally, I would figure that this is a configuration issue, but the fact that it works on certain screens leads me to believe that it is a bug.

This is for adapter BX-W201
http://www.focalprice.com/GW0119B/BX_W201_Game_Cube_Controllers_Adapter_for_Wii_U_Black.html

Tried with and without controller.ini for the Official Wii-u gamecube adapter. I also tried running Super Smash Brothers (for Wii-U) prior to running nintendont. 

Also tried running the HID Test app. When using the controller.ini the app freezes after the program displays the max packet size (I believe), and before the program displays the instructions.

Without the controller.ini the HID Test app loads up but no values change when operating the controller.

V3.33 of Nintendont. I believe 4.3 of vWii.

**Comment by FIX94** [comment]
fun fact: all usb input is always handled in the exact same file with the exact same code in a loop so the fact that it starts not working at some point leads me to believe something is wrong with the usb port you are using.

**Comment by izackp** [comment]
hmm maybe the usb adapter is conflicting with the usb hard drive that I'm using to load games? If it is not working when the game list is shown or when the game is running then those are the times that the usb hard drive is being used. That would coincide with your suggestion that the usb port is not working. I can try loading games on an sd card as well as different ports and see what happens.

**Comment by FIX94** [comment]
is the adapter connected via both usb ports? Also no it most likely is not affected by the hdd, the IOS modules for that dont confuse one thing for the other. Also as soon as you have the sd/usb selection the usb hdd is fully mounted and never gets touched again.

**Comment by izackp** [comment]
well.. looks like its just mario party 6 that has problems.. Just tried time splitters 3 and it works great :/

**Comment by izackp** [comment]
Should have tried another game in the first place.. I suppose I can just use the wii-mote to load games. Thanks for your help :+1:  Maybe, I'll try redownloading mario party 6 to see if that would fix it. Otherwise, its probably just a game specific problem.

**Comment by izackp** [comment]
Figured it out! Mario Party only works when the controller is plugged in the furthest left slot of the adapter which I guess is first player. It's sort of strange because super smash brothers (wii-u) only works when the controller is plugged in the furthest right slot of the adapter. Wasted so much time lol. Sorry for wasting your time too, but thanks for the help!

**Comment by FIX94** [comment]
good to know it works now, and yea I also noticed some games only accept a single port, I also noticed some games dont even notice when you take out a controller from a port and it continues pressing the buttons you had last pressed before taking it out.
