### ISSUE TITLE
Melee won’t load at all

### ISSUE THREAD

**Issue by GeniusArkade** [FIX94/Nintendont#1210]
So I installed melee from vimms lair it didn’t work and I tried everything even looking at 9yo posts and changing my settings etc but nothing is working please help me

**Comment by carnage702** [comment]
you need a good working iso, if your using iso like nkit and such there is no garantees they will work, you need a full 1.35gb iso with correct md5

**Comment by CaptainJokes** [comment]
Use Dolphin to convert the rvz to ISO, or use Nkit (windows only) to convert the file to a nintendont compatible iso file
