### ISSUE TITLE
NBA Street (USA) freezes

### ISSUE THREAD

**Issue by mehzemo** [FIX94/Nintendont#122]
NBA Street (USA) freezes (hangs with noise) after a random time of playing (usually from 10 to 30 minutes), I'm sure the ISO is correct because I dumped it from my miniDVD which plays correctly.
It seems, but I'm not sure, game randomly freezes when background music change.
Tested with v3.333 and v3.334 on vWii!

Keep the good work!
--
Massimo

**Comment by carnage702** [comment]
Are you using force widescreen by any chance?not wiiu widescreen but forced widescreen?

**Comment by mehzemo** [comment]
Yeah, I'm forcing widescreen and progressive on this game!
But neither of them broke other games…
-- 
Massimo

**Comment by carnage702** [comment]
force widescreen(not force wiiu widescreen) is a hack and makes manny games randomly freeze so try to play without forced widescreen and see if the freeze still happens.

**Comment by carnage702** [comment]
if it still freezes after 30mins or so let me know becuase it might need an arstartdma exception but i just want to know if it isnt caused by the widescreen hack in the first place before start making dols for you to try.

**Comment by mehzemo** [comment]
You're absolutely right: force widescreen hack breaks this game!

-- 
Massimo

**Comment by carnage702** [comment]
So no more freezing im assuming without forcing widescreen?If so i will edit the compat list and say force widescreen causes random crashes if you confirm it.

**Comment by mehzemo** [comment]
Sure: force widescreen always freezes the game!
Without force widescreen hack all works flawlessly!

**Comment by carnage702** [comment]
thanks wiki has been edited.
