### ISSUE TITLE
Request for advice: Modifying input code

### ISSUE THREAD

**Issue by MrTrick** [FIX94/Nintendont#124]
I'd like to add support for an exponential gain option, as in games like FZero GX with the classic pro controller the controls are so twitchy it's close to impossible.
I'm thinking it might be a global option, as monkeying around with controller configs would probably break a lot of existing code.

I've managed to build nintendont successfully. (having installed devkitpro)
Where would you suggest I start looking in the source code? What section is responsible for translating and passing through controller input?

**Comment by FIX94** [comment]
for one there is this file which converts all inputs to gc input:
https://github.com/FIX94/Nintendont/blob/master/loader/source/ppc/PADReadGC.c
and this file specifically for bluetooth input handling:
https://github.com/FIX94/Nintendont/blob/master/kernel/BT.c

**Comment by MrTrick** [comment]
Ah fantastic, thank you.

I'm guessing `Pad[chan].stickX` and `Pad[chan].stickY` are the ones to modify, if I wanted something global? I notice they're set in several places, across 3 for-loops, so I think I'd add something after all of them like (at about line 1218 of PADReadGC.c) `for(chan = 0; chan < MaxPads; ++chan) { ... modify Pad[chan].stickX and Pad[chan].stickY ... }`

It would be nice to be able to toggle it on and off in the config screen, but one thing at a time...

**Comment by carnage702** [comment]
remenber the CC inputs are way inferior to the GC ones thats why the games arent as accurate.

CC limitations are he values from the sticks range 
LX,LY are the left Analog Stick X and Y (0-63), RX and RY are the right Analog Stick X and Y (0-31)

The GC range is 
Both sticks 0-256

so you see how much crap they work when you are converting values specialy for the CC/CCpro  C stick to the GC one they have crap range.

**Comment by MrTrick** [comment]
Got something working. :-) If you are inclined, give it a try.
https://github.com/MrTrick/Nintendont
https://github.com/MrTrick/Nintendont/commit/7048a254edccdb1e97b280980036dec2e91a8745

The modification works really well - FZero GX is now very playable with the classic controllers, and it'd probably work well with other thumbstick controllers.

@carnage702 I hear you. The issue I was facing though wasn't granularity of control, it's that even when tilting the stick gently the game would interpret that as "turn hard". In the game's calibration screen it seemed smooth enough, just that it covered the first half of the range too quickly.
I had the same problem in Mario Kart, though as the gameplay is slower it was less severe.

Here's what the mapping looks like:
![input_linear_vs_squared](https://cloud.githubusercontent.com/assets/127012/7652397/8deeeb20-fb4f-11e4-996d-fbf8a78c11b1.png)
Even though the zero point and limits are the same, more stick angle is needed to make small movements.

I'd put in a pull request, but it should be configurable first.

**Comment by FIX94** [comment]
I just made a video for you comparing the existing configurations of the gc controller, the classic controller pro and the wiiu pro controller via the gx configuration menu. as you can see at the moment all sticks are fairly close together so I dont really know why this code you posted up there would be needed, I find it pretty weird if you ask me.
https://www.youtube.com/watch?v=TU4np00-w1o
I also wrote a quick dol file just to compare the sticks also outside a gc game and I got the same result, didnt make a video of it but you can also have that dol file:
http://www.mediafire.com/download/e1jzius5he7225w/padtest.7z

**Comment by MrTrick** [comment]
Interesting!
I don't have another type of controller to compare with, but on the calibration screen **my** Classic Pro controllers (with the plain version of nintendont) go to 127 / -127 and trace out a rectangle shape.

Maybe that should be a warning not to go cheap on your controllers.

**Comment by carnage702** [comment]
Nintendont is not very friendly with fake/3rd party controllers, all the testes abode fix made were with offcial controllers.
