### ISSUE TITLE
All games are visable on usbloader gx but not nintendont 

### ISSUE THREAD

**Issue by Squidster773** [FIX94/Nintendont#1241]
I have all of my folders labeled correctly with the corresponding "game.iso" in each folder yet only a portion of them are visible on nintendont.  Usb loader gx sees them but is unable to load them. Anyone have any ideas? 

> 
![17292824520424839455753249084028](https://github.com/user-attachments/assets/ebbc3afe-34de-4c6d-9e72-00cdaa61a94d)
![Screenshot_20241018_161540_Gallery](https://github.com/user-attachments/assets/620b60b6-e3b4-425b-878a-15a7c796d1de)
![Screenshot_20241018_161518_Gallery](https://github.com/user-attachments/assets/30e0e6d2-3ad5-4598-a819-59c41b34b590)
![17292826888415353040683835410142](https://github.com/user-attachments/assets/a1ed7b99-50f6-4d5d-a244-b778778145a1)

**Comment by carnage702** [comment]
What outdated nintendont is that 286?latest nintendont is 500+...
Also maybe you have hidden extensions on your PC, so some isos are actually called game.iso.iso

**Comment by Squidster773** [comment]
> What outdated nintendont is that 286?latest nintendont is 500+... Also maybe you have hidden extensions on your PC, so some isos are actually called game.iso.iso

I modded it years ago bit never got around to setting up the gamecube end of things. I'll have to try updating it but I'm positive I don't have the hidden extension issue

**Comment by Squidster773** [comment]
I just don't get any it shows some games but not others.

**Comment by carnage702** [comment]
> I just don't get any it shows some games but not others.

just call the games that dont show up just "game" delete the .iso

**Comment by carnage702** [comment]
and again just udpate nintendont 286 will have tons of compatibility errors still  just download this rename it to boot.dol and replace it under apps/nintendont

https://github.com/FIX94/Nintendont/raw/refs/heads/master/loader/loader.dol
