### ISSUE TITLE
Add “Special Thanks” to credits 

### ISSUE THREAD

**Issue by DoctorWhosThat** [FIX94/Nintendont#1243]
This is not exactly an issue, it’s more of a request (which I should have actually asked for years ago, sorry!).

“To those who originally donated towards quadforce for this to happen, Nintendont wouldn’t be what it actually is today.

Thank you to those kind generous people who helped pave the way ahead.” or similar words like that.

**Comment by DoctorWhosThat** [comment]
Completed? 😕

**Comment by carnage702** [comment]
Do you know wh0o made quadforce? Crediar ... do you know who made nintendont first release? Crediar...  Do you know who added triforce to nintendont? Crediar.... he has bem credit since the first release since he was the one who made nintendont to begin with.

**Comment by DoctorWhosThat** [comment]
Only because they was motivated by donations, otherwise they wouldn’t have actually bothered in the first place!
