### ISSUE TITLE
(Possible Bug) FMVs don't run on Kirby Air Ride NTSC when forced to PAL60 on PAL-consoles

### ISSUE THREAD

**Issue by Daddu3** [FIX94/Nintendont#1245]
Most likely quite a minor issue, but was curious if it's matter of fixing it on my own. 

While the FMVs can't play, you can still advance past the intro sequence to the game.  I'm guessing this is due the FMVs not getting patched to PAL60 (though again somehow FMVs work on Melee-hacks like Training Pack).

**Comment by carnage702** [comment]
Any forced setting is a general hack it doesnt work on every game, also pal version supports pal60 so why are you forcing the ntsc version to do what it isnt supposed to do?

**Comment by Daddu3** [comment]
> Any forced setting is a general hack it doesnt work on every game, also pal version supports pal60 so why are you forcing the ntsc version to do what it isnt supposed to do?

Because KAR's hacking community is focused on PAL60-version when it comes to it's Gecko codes, forcing me to migrate there as many of them aren't supported on PAL. 

I can live without FMVs and non-functioning intro for now but maybe hear someone out first before dismissing them outright.

**Comment by Daddu3** [comment]
> @Daddu3 I don't quite understand the issue here. If you already have the NTSC version of the game then you don't need PAL60, PAL Wii's can do NTSC just fine?

On HD TVs, I suppose so. But on CRTs, no. On RGB-output, it's completely red or black and white depending on the model you're having. 

But yeah, like I said, I just found this a minor issue and wondered if it could be done something about - especially as on some other game I have the FMVs seem to work just fine (Melee Training Mode Hack)

**Comment by Daddu3** [comment]
> > But on CRTs, no. On RGB-output, it's completely red or black and white depending on the model you're having.
> 
> That...doesn't sound right. You're not forcing it in 480p, are you? Does it show color in 480i?


Long time on replying to this but nope, it's 480i. That's how games forced on NTSC will end up looking on RGB-output on PAL CRTs, due using wrong color coding determined from the different clock frequencies between NTSC and PAL TVs.
