### ISSUE TITLE
problem with 3 HDd conected

### ISSUE THREAD

**Issue by snakemoral** [FIX94/Nintendont#125]
The nintendont crashes when I have the HDd with Gc games and HDd I use to Wii U games plugged into any of the USB inputs. HDd GC has two partitions, one FAT32 and NTFS, give the indicative led reading is enabled in HDd with Wii U games, the correct HDd is not even being acknowledged.

**Comment by carnage702** [comment]
Nintendont does not support multi hdds being connected, just disconnect your wiiu hdd everytime you want to play GC games.

Its not an error or an issue its simply not supported more than one hdd connected at a time.
