### ISSUE TITLE
PS3 oficial Controller with usb cable crash Nintendont 

### ISSUE THREAD

**Issue by mouravitor313** [FIX94/Nintendont#1251]
Hi there!

I plug my controller in usb on my Wii, launch Nintendont and then in the screen selection of usb or sd card, the cursor is always goin to up, even when I press down in the Wii remote.

When I select the usb (where my games is) the application crash and I need to reboot my Wii.

When I start and go to the games list without the PS3 controller plug in, the cursor works fine with the wii remote, and I can select a game.

When a game starts and I plug my PS3 controller, the game not crash but my controller still not working.

My PS3 controller works on HIDtest. I also edit the ps3controller.ini (setting the Polltype to 1) that comes inside HIDtest app folder and moved to Nintendont. Not work. Then I restore without any edition and do not work too.

Can you help me with that? My controller its a CECHZC2U. Works perffectly on my ps3 with sixaxis, wireless and wired.

Sorry for the bad english. Thank you for your attention. A big hug from Brazil

**Comment by carnage702** [comment]
what is the PID and Vid of your controller? it its a diferent revision it might need its own ini file and cant use the one made for older ones.

**Comment by mouravitor313** [comment]
I'm sure of it. it's a official one, i tested it on jorney to uses sixaxis and works fine. already opened too.

VID:054C
PID:0268

thank you for you attention

**Comment by carnage702** [comment]
> I'm sure of it. it's a official one, i tested it on jorney to uses sixaxis and works fine. already opened too.
> 
> VID:054C PID:0268
> 
> thank you for you attention

fake ones will always work on the console their are made for... like a fake wiimote will work on wii games but not on nintendont and so on, if you didnt actualy buy it new or came with a new console if you bought it used online or onsome random shop that carries 3rd party fake stuff most likely it isnt official controller therefore its code is actually diferent from when its used on the ps3 games.

**Comment by mouravitor313** [comment]
The point is that the fake ones don't work with the PlayStation 3's sixaxis. It's a technology that bootleg controllers that try to look like the PS3 controller couldn't replicate. That's why I'm sure it's an original control. And as I said, I opened the control... The construction of an original SONY controller is very unique.

It´s not a 3rd party controller

**Comment by carnage702** [comment]
> The point is that the fake ones don't work with the PlayStation 3's sixaxis. It's a technology that bootleg controllers that try to look like the PS3 controller couldn't replicate. That's why I'm sure it's an original control. And as I said, I opened the control... The construction of an original SONY controller is very unique.
> 
> It´s not a 3rd party controller

then im not sure what to tell you, maybe make your own controller.ini file maybe the vaules for that controller model will be diferent i only own the original sixaxis and the original dualshock3 those more recent ones i dont own so i cant do much try making your own controller.ini and place it on the root of your sd or usb where the isos are, maybe those controller values are diferent on the joysticks/buttons than the older ones.

**Comment by mouravitor313** [comment]
ill try. thank you for your time bro
