### ISSUE TITLE
Twilight princess crashes on Nintendont

### ISSUE THREAD

**Issue by danxilys** [FIX94/Nintendont#1254]
Hello, I don't know much about modding or emulating anything on Wii, I just got Nintendont on mi Wi and I've been playing twilight princess on it, and everything seemed fine but when I get to play with wolf link for the first time and try to attack anything the game crashes like this  ![image](https://github.com/user-attachments/assets/bf3705ba-9754-45a8-94ad-717ab43ab139)
Does anybody know how to fix this? I would really appreciate some advice's :(

**Comment by carnage702** [comment]
well since you closed it i guess you found the issue.
