### ISSUE TITLE
load GC Isos from wbfs container on a wbfs formated device

### ISSUE THREAD

**Issue by snoer** [FIX94/Nintendont#128]
the wbfs container allows to hold gc images.
recognizing those via usbloader gx also seems possible.

see this request.
https://code.google.com/p/usbloader-gui/issues/detail?id=2320

**Comment by carnage702** [comment]
wbfs is a very outdated format, there is no need to waste a drive to be pure wbfs nowadays in the wii hacking scene, you make your drive fat32 and then make a wbfs folder on it and put your wbfs isos in there and still keep your device for every homebrew need, be it nintendont or any other homebrew app, all isos bigger than 4gb can be split and used in split format on usbloader gx or wiiflow perfectly, its like your asking to add compat to a format almost everyone has dropped becuase its uselss now, no one that keeps up with the wii scene uses a full wbfs drive nowadays.

**Comment by Squall-Leonhart** [comment]
nobody particularly cares about your opinion on wbfs Carnage, next time just give a flat no as an answer.
