### ISSUE TITLE
no HID option in the settings menu!

### ISSUE THREAD

**Issue by harmjanhaisma** [FIX94/Nintendont#133]
i have a controller plugged in, hidtest sees the controller and the values change, but in nintendont there is no option for hid....
EDIT: just noiticed that the option isnt needed, but my controller does not work.

**Comment by harmjanhaisma** [comment]
also the controller does not work ingame.

**Comment by carnage702** [comment]
the option is always activated, if the controller has one of the hid PID/Vids inside nintendont controllers zip it will work automatic if it doesnt you have to make a ini file for yourself, nintendont does not have hid ini files for every hid controller ever made.

what is your controller? if it isnt listed on controllers zip then you need to make your own ini and put it on the root of the device where your games are stored and rename it controler.ini

**Comment by harmjanhaisma** [comment]
i made a controller.ini but i think it doesnt load it? i put it on the root of the usb

**Comment by carnage702** [comment]
it needs to be on the root of the device you have your isos and named "controller.ini" without the " and of course you need to make a good controller ini if its good or not i have no idea i dont know what you created if the values are correct or not anyone to confirm would need that controller.

**Comment by harmjanhaisma** [comment]
its without the " i aint stupid, and my values are correct, last time i checked.

**Comment by carnage702** [comment]
you dont have any oher hid or gamecube controllers plugged at the same time?

**Comment by harmjanhaisma** [comment]
my roms are on a usb, does that count?

**Comment by carnage702** [comment]
No, as long as the controller.ini is on the usb root it should work, does your controller works on nintendont menu?

**Comment by LeninC22** [comment]
There's this controller I have, its called the Controller Pro U. It's basically wireless wii classic controller. All im saying, how do I make a controller. ini file about this type of controller? Answer ASAP please!!

**Comment by carnage702** [comment]
Bluetooth controllers have no ini files they are hardcoded into nintendont, ini files is just for usb controller, so use nintendont and activate it if it works it will work great if not its becuase its some 3rd party wierd controller.

**Comment by LeninC22** [comment]
Its not really an official nintendo controller, so its a 3rd party controller?

**Comment by LeninC22** [comment]
And if do have an official wireless controller, like the Wii U Pro controller, how do i use it in nintendont. I need specific instructions step by step ASAP!

**Comment by carnage702** [comment]
yes those are 3rd party so they can work or not its a mter of trying t activate it on nintendont menu and see if it responds.

the wii u pro is very easy, if you are on the wii U and already sinced it to the system before just activate it either on nintendont menu or ingame by pressing any button like A for example.

On a wii when seeing the wii menu hit sync  on the wiiu pro and the wii it will flash 2 times or so and shut down that means it has synced but since wii menu doesnt support it shuts it down of course, then its the same when on nintendont menu or ingame press any button to activate it.

**Comment by LeninC22** [comment]
Sounds complicated, and I have a wii u.

**Comment by carnage702** [comment]
How is that complicated? if you have a wiiu and you already used the wiiu pro in some game so its already synced so all you have to do is hit a button when seeing nintendont menu or ingame...

**Comment by harmjanhaisma** [comment]
why is this closed?? its not solved yet!

**Comment by carnage702** [comment]
you never posted anything else and someone highacked your thread. all hid controllers work perfectly as long as the ini file is well made you never posted your ini file either.

**Comment by JacobAL** [comment]
Is there an existing HID-test application link? The ones on the GBATemp thread don't work for me.
