### ISSUE TITLE
hid bluetooth

### ISSUE THREAD

**Issue by acenatsu** [FIX94/Nintendont#134]
please can you make hid ds4 bluetooth compatible please it is what i most want..
thank's a lot for everything

**Comment by Zetchzie** [comment]
So you don't have to connect it with usb i'm guessing? Because DS4 works you just can't use it wirelessly same as DS3.

**Comment by Zetchzie** [comment]
This would be cool so I can use the ds3 wirelessly. I don't know if this would work though. Sony products use a different protocol from what I read. The bluetooth they use is incompatible with wii. So a driver would need to be developed.

**Comment by GerbilSoft** [comment]
AFAIK, DS4 is a standard HID Bluetooth controller, so it works with any system that supports HID over Bluetooth. (DS3 is also standard, except it requires some initialization quirk, much like how the official GameCube adapter is standard USB HID but requires a single byte to enable it.)
