### ISSUE TITLE
MGS: The Twin Snakes & Eternal Darkness problems

### ISSUE THREAD

**Issue by pancho21** [FIX94/Nintendont#135]
At the start of Eternal Darkness (Edgar Allan Poe quote) the game stuck (HID on).

At the start of MGS: Twin Snakes (progressive mode on/off screen) pad doesn't respond with HID on. In-game everything is OK.

Tested on Wii U with r343.

**Comment by carnage702** [comment]
what are your nintendont settings? 
all of them say them here.

**Comment by pancho21** [comment]
I had bad dump of Eternal Darkness. Thanks! But my isos of MGS:TT are correct...

**Comment by JFizDaWiz** [comment]
having freezing issues on Eternal Darkness as well (CRC/MD5 match redump)
crashes at random intervals after switching characters.

**Comment by carnage702** [comment]
tell all your nintendont settings and version please we cant help with no info.
