### ISSUE TITLE
Testing some games.

### ISSUE THREAD

**Issue by tavofox** [FIX94/Nintendont#136]
Hi! probe some games and found these that did not work well at all, Geist and Teen Titans hung when loaded, and Rayman 3 stops working when I press star. Greetings!

**Comment by carnage702** [comment]
thats probably becuase they are audiostreaming games and you are either badly compressing them with bad tools like GCISOTOOL or using bad dumps.

**Comment by tavofox** [comment]
Yes! the problem is that GCISOTOOL used and modified MD5, probe and correct MD5 Geist checked and works great, thanks carnage702, it was something that had in mind, proves the other and will comment. greetings and hugs!
