### ISSUE TITLE
Cheats aren't working correctly or causing adverse effects; loading from USB loader GX 1239

### ISSUE THREAD

**Issue by SevenWillis** [FIX94/Nintendont#137]
With the new code handlers in effect, it made a lot more codes work, but they cause some games to crash. 

Twilight Princess experiences a framerate drop in Hyrule Field, and when trying to save it soft crashes (music still plays but can't get out of save menu)

Tales of Symphonia crashes at the start of battles

Windwaker crashes after the Nintendo watermark

F-Zero GX fails to load models and crashes when loading tracks

OSReports should provide more information.

Tested on Wii with r3.344

**Comment by FIX94** [comment]
its not a code handler thing, its a hook thing. Right now I made up a "solution" I dont really like either, I want some sort of option to select from multiple code handlers and not just apply all of them at once because that can slowdown/crash the game just like you experienced.

**Comment by SevenWillis** [comment]
Does kenobiwii affect it at all? I'm afraid to delete it because of USB Loader GX's dependency...

Cheats really aren't that big of a deal but they're really fun haha
I want this app to be most perfect in every aspect and it's come a very long way.

**Comment by carnage702** [comment]
kenobiwii is no longer used at all, Fix94 has already made nintendont not need it, so having it or not doesnt affect how cheats are loaded on nintendont.

**Comment by SevenWillis** [comment]
Well since I have yet to find usb loader gx r1246 I'm keeping it despite whether it's needed or not. Better to have and not need than need and not have.

**Comment by FIX94** [comment]
please check out the latest 346, it should help.

**Comment by carnage702** [comment]
Best to try 350 since Fix forgot something andprevious versions didnt have cheats for while, so try 350 with your cheats and report back when you can.

**Comment by SevenWillis** [comment]
Oh, yeah!! It works great. I have Twilight Princess running and the cheats work and there's no lag in the game, but I'll have to test my other games to verify further.

**Comment by SevenWillis** [comment]
Also I updated USB GX to r1247 so that helps it run smoother too.

**Comment by carnage702** [comment]
If you can teste all the games abode that you said had issues and report back if they still do, if they are all working well now then that means the new cheat codding is working great.

**Comment by SevenWillis** [comment]
Twilight Princess works great

Tales of Sypmhonia starts battles but attacks will crash the game.. It may be the code itself and not the hooks

F-Zero GX loads 3D models and crashes when trying to load the tracks themselves. Again, it may be issues with the code itself and not Nintendont. 
Also, not a cheat issue, but the custom machines don't load any parts but the body. It doesn't affect the gameplay and it looks funny to see the driver floating above the machine, but I'd like to see my machine in its entirety.

Windwaker also still has code issues, mainly with button conditionals.

**Comment by FIX94** [comment]
so for all that stuff I assume most is really just code related since after all the codes were written for gc and not for wii and button codes obviously wont work anymore because they try to speak to registers which dont even exist anymore so do alot of other codes.
