### ISSUE TITLE
Triforce

### ISSUE THREAD

**Issue by IanMoonex** [FIX94/Nintendont#141]
Only managing to get GFZJ8P F-ZERO AX running - both Mario Kart Arcades are hanging on a black screen. Current version 6th June 2015 update of Nintendont. This is on a Wii not WiiU

**Comment by carnage702** [comment]
That is becuase you arent finding the right isos for sure, if your isos have this md5s they will work, also make sure your not forcing random settings like forced progressive or videomodes, triforce games are picky with video stuff.

F-Zero AX TriForce Arcade ISO
-ISO with "virtuastriker2002" title in Header
ab1e442313cc0cc2dd1f52f0407aed1a
-ISO with "F-Zero AX" title in Header (Best ISO)
1632826dab98f02f87ca474345f59db1

Mario Kart Arcade GP TriForce Arcade ISO
-ISO with "MKAGP1" GameID in Header.
32fc2fc04980ad713360d5d5a834e6e9
-ISO with "GGPE01" GameID in Header.
59eccd51f04664c9667900c9ebdec4f7
-ISO with Infinite Credits Patch (Thanks Cyan)
8520010c65f06b4867a68a5f15ecb9ec
-Wierd ISO with GGPE01 GameID and "Mario Kart Arcade GP" title in Header (Thanks DJ_skual)
e9bd95bec1a69bedcae171b6629876b0


Mario Kart Arcade GP 2 TriForce Arcade ISO
-ISO with "MKAGP2" GameID in Header
83922403a5f413552dcd1cb89a0a2a86
-ISO with "GGPE02" GameID in Header
70f261a2f10d00c7d77b4fd13307843a
-ISO with infinite Credits Patch (Thanks Cyan)
2b63cbe6bc1cc8b38c2c9ad783d66bb9
-Wierd ISO with GGPE02 GameID and "Mario Kart Arcade GP2" title in Header (Thanks DJ_skual)
6a07e7ab97112ae9b5d8277eb9628a02

Virtua Striker 4 Ver.2006 (Export) TriForce Arcade ISO
-ISO with "GVSJ8P" GameID in Header
53a0eb3d593b3280911269d2aee2f6b1
-Modified ISO with "GVS46E" GameID in Header
3a28d974b96546a89c279a20c3360b04
-Modified ISO with "GVS46J" GameID and "Virtua Striker 4 Ver.2006" title in Header
74a63de8768f688a47dfe274ece5e74f

Virtua Striker 4 Ver.2006 (Japan) TriForce Arcade ISO
-ISO with "GVSJ8P" GameID in Header
236561a6fe8b6387a1f0558372d9c4ce
-Modified ISO with "GVS46J" GameID in Header
c22de9a93a99ddad44085052357f5f8c
-Modified ISO with "GVS46J" GameID and "Virtua Striker 4 Ver.2006" title in Header
5c9928bdb4c9d3793a5db6b0cf3cc18f

**Comment by IanMoonex** [comment]
Thank you for the reply.
Have been googling MKAGP1 & MKAGP2 all afternoon for a good iso but everything is '404 page not found'. Could you point me in the right direction?

**Comment by FIX94** [comment]
you could come over to the channel #cdi over on irc.abjects.net and maybe get into direct contact with us...

**Comment by IanMoonex** [comment]
Managed to get onto abjects.net via chatzilla but no #cdi channel showing up in list. Am I doing something wrong....?

**Comment by carnage702** [comment]
well server is irc.abjects.net and channel is #cdi so yeah there is no mistake to be made imo try again you can even use online ircs like webirc and such so you dont need t install anything.

**Comment by IanMoonex** [comment]
Thanks - used Mibbit - OK can see FIX94

**Comment by carnage702** [comment]
people are there but arent so if you havent found help try connecting later
