### ISSUE TITLE
Launching Metroid Prime 2 from HDD causes freeze (apploader error), launching from disc works just fine.

### ISSUE THREAD

**Issue by Techinicabor** [FIX94/Nintendont#142]
Wii 4.1U, r349
The game was reinstalled but the problem still exists, other titles launch with no issue. Below is the log made at this point.
![g2me01 nintendont](https://cloud.githubusercontent.com/assets/13040464/8361953/a7e6c8d4-1b3b-11e5-97bc-651b6d5ef38b.png)

**Comment by carnage702** [comment]
You sure you got a good dump on your hdd?

full iso md5 checked with redump?

**Comment by VinsCool** [comment]
I tested the game and still work fine for me.

**Comment by Techinicabor** [comment]
I was making compressed dumps using USBLoaderGX, and this was the only game that didn't work, so I made a 1:1 copy using SuperDump and the MD5 matched redump's. The system now powers through the BIOS just before "An error has occurred." I can see why... 
![yeah that obviously didn t dump correctly](https://cloud.githubusercontent.com/assets/13040464/8364588/f6659524-1b4c-11e5-9833-d8d228fd3bc8.png)

**Comment by carnage702** [comment]
works fine for me full iso 1.35gb md5 matching redump.

You arent using any wierd forced settings? or cheats or ssomething diferent?

also to dump discs never use usbloaders, use cleanrip that is the only kinda thrusty ripper.

having  error has ocurred message means the connection to your hdd was cut at some point?

Tbh i have games on disc but i much rather get them online rather than ripping old scratched and worn out discs but that is just me.

**Comment by VinsCool** [comment]
Widescreen, cheats and force progressive works fine with this game for me.

I'm sure the iso file is to blame, according to the screen shot of debug log.

**Comment by Techinicabor** [comment]
Even after using CleanRip, (Thanks, btw) which resulted in a matching dump, my copy just refuses to run. There probably is something wrong with my copy of the game and/or the HDD, maybe even the console.

**Comment by FIX94** [comment]
I very much suggest you doing a full format on your hdd because what you get seems like bad sectors.

**Comment by Techinicabor** [comment]
The drive checked out OK using HDAT2. I dumped the game to another device and the same scenario occurs. This has to be the console.

**Comment by carnage702** [comment]
just get an iso online and try it, maybe your disc is bad to dump, if the wii plays the other games just fine then the console has nothing wrong with it, you said it yourself it plays perfectly with the disc so yeah nintendont uses the disc just like an usb or SD, just to read data and then it does the same exact thing to play the game, aso you never stated your nintendont version or your settings.

Try getting a download of the game online and put it on a random usb stick if it works its either your hdd or your disc dump, or try to delete MP2 from the hdd and put another big file in there and then add itfresh again, maybe somehow your mp2 iso is getting corrupted when transfering to that particular section of the hdd.

**Comment by Techinicabor** [comment]
With a downloaded copy on a completely different storage device, the same thing happens. Screenshots of error and of Nintendont's version+settings.
![wp_20150626_02_57_20_pro](https://cloud.githubusercontent.com/assets/13040464/8373217/3fd6c396-1bb0-11e5-8837-a86507187fbd.jpg)
![wp_20150626_02_57_59_pro](https://cloud.githubusercontent.com/assets/13040464/8373222/4e440718-1bb0-11e5-94ce-a4e9f44c5107.jpg)

**Comment by carnage702** [comment]
try turning off log and osreport those options break most games if you arent using a usb gecko incase you didnt know. also why dont you have maxpads set on the standard 4? and language on auto? forced english is pointless all games are english by default unless another region langauge is forced, or if you are using some very very rare japanese game that happens to have englsih option besides the default japanese.

**Comment by Techinicabor** [comment]
These settings were like this already, thanks to USB Loader GX. Everything works just fine. Sorry for the mixup! c:
