### ISSUE TITLE
SRAM updating with real memory cards still doesn't work

### ISSUE THREAD

**Issue by VinsCool** [FIX94/Nintendont#143]
I just tested nintendont r349, and the feature doesn't seem to work. I tested with Metroid Prime 2, since it's one of my games having another language on the disc. Tested with MC emu OFF, with ISO and actual disc. Forcing SRAM with Open Sram modifier works still. I think something in the feature is missing of broken.

**Comment by FIX94** [comment]
are you sure you are settings a force language in the settings? I'm very sure it is a mistake on your side.

**Comment by VinsCool** [comment]
I found the problem. I was using mastermod, and for odd reasons, there are missing features. Bios with mcemu OFF wasn't working either. MasterMod was to blame, sorry for the false report :P
