### ISSUE TITLE
Feature request: Simulate "Constant Angular Velocity" in ReadSpeed.c

### ISSUE THREAD

**Issue by lifning** [FIX94/Nintendont#145]
It seems the [Dolphin folks did this](https://dolphin-emu.org/blog/2014/12/01/dolphin-progress-report-november-2014/#40-4222-support-constant-angular-velocity-for-disc-reads-by-josjuice) in the name of timing accuracy (https://github.com/dolphin-emu/dolphin/commit/ba1a8d2ef3e5dd602fa9ac054bcc787d7b400b16, previously they were using 3MB/s like Nintendont currently does) and not only made speedrunners happy, but also transparently fixed some issues in games like Sonic Riders that previously required game-specific workarounds like https://github.com/FIX94/Nintendont/commit/66043c7efe3ae765a5d0f55e521ce8b12e2b921c and https://github.com/FIX94/Nintendont/commit/e3885c6447d4673481f84d03c440080040957d25  :)

Cheers!

**Comment by carnage702** [comment]
Fix added the contant angular velocity way back but it did nothing to sonic riders, he talked with the dolphin dev and they also didnt know how sonic ridders was fixed they said it was luck, but Fix found out the issue and it was processing power, sonic ridders had too much processing power for its own good and tryed to initialize the stage before everything else was loaded.

Nintendont already has a limiter for the read speed so games dont trip over themselves.

**Comment by FIX94** [comment]
on another note, nintendont has very limited math and is bringing its ARM core to its limits at times so thinking about a feature like that wont work for one and also wont help. on top of that you have to realize that read speeds differ anyways on every single read for us so we got more than enough guessing already anyways, we cant get more accurate really than we are now anyways thanks to that. Oh and of course, the 100% game compatibility speaks for itself ;)
