### ISSUE TITLE
Double/cloned titles + crash

### ISSUE THREAD

**Issue by hokky** [FIX94/Nintendont#146]
I'm not sure if this can be reproduced elsewhere, but I am having an issue with a single title (Mario Kart: Double Dash!!) showing up twice in the game selection menu. The title may change according to the number of games loaded onto an SD card (64GB Sony SDXC UHS-1). This has happened previously with other titles like Pikmin and Metroid Prime. Essentially, the fourth title in the library is a duplicate of the third and only the clone crashes/blank screens the vWii or original Wii upon execution, thus requiring a pull of the power cable.

**Comment by hokky** [comment]
Also, exiting Nintendont to the Wii menu crashes/blank screens.

**Comment by carnage702** [comment]
Are you using nintendont directly from homebrew channel? or are you using a loader/fowarder?

never ever saw a game twice in nintendont lol, unless you happen to have the same gameid twice on your card like a modified game that has the same id as mkdd.

**Comment by hokky** [comment]
You're right about the forwarder.

As for the duplicate, nothing found for titles with same gameids. It is really baffling me.

**Comment by carnage702** [comment]
preety much all fowarders will crash when exiting, only foawrderss with a full stub work for returning or if you launch nintendont from the homebrew channel it will always exit perfectly to the homebrew channel.

Maybe you got some iso with a modified gameid that happens to match mkdd?
