### ISSUE TITLE
"Modification of the video width" Not really working :(

### ISSUE THREAD

**Issue by Nashismo** [FIX94/Nintendont#147]
Dear Fix94:

The recent Nintendon't with Width modification support is not really working. When I just saw this I thought finally my dreams came true!! :)

But no, no gamecube game I own "stretches" to fill the screen, not at 4:3 or at 16:9 (with or without widescreen patch).

Sure, it works on Nintendon't Menu screen, but not on games. I am using a 2010 black Wii, component cables at 480i.

The PS2 gives me this problem too using component, it has always been a problem with these consoles using component and I was SO AMAZED that it could finally be solved at least for Gamecube games, but well, doesn't work.

Thanks for listening, my admiration goes to you, thanks.

**Comment by carnage702** [comment]
what stretch value are you trying? most games require more than the nintendont logo uses to fill the screen if even with the max setting your game doesnt fill the screen then its your tv settings for sure.

**Comment by FIX94** [comment]
just to give you some numbers, for me nintendont is fullscreen with 668 and offset 1, for the games though I need 676 and offset 1 so just play around with it, most games just dont render full.

**Comment by Nashismo** [comment]
Thanks for your answers guys. I have mostly tried Mario Sunshine and Zelda Windwaker. I have tried many values, from 720 to 670. But like you said it must be that most games just don't render full. By the way, I always remember Metroid Prime, cause that game had an option to strech out the image. It has been the only game that has allowed me to fill the screen ever (a 4:3 image though).

Thanks again, I will try your numbers. And thanks for such wonderful program! Norris approved :)

**Comment by mirrorbender** [comment]
I am also encountering this issue.  Neither the horizontal position setting not the horizontal size modification actually have any effect outside of the nintendont menu as far as I can tell, even at the most extreme settings.

**Comment by carnage702** [comment]
Are you using bios? Pal or ntsc game? wich game?

**Comment by mirrorbender** [comment]
Not using bios (is that necessary to use this feature?)  NTSC Wii running NTSC games (I've tried Melee, Twilight Princess, and F-Zero GX) @ 480i via component cables.  I can test other games/other cables if you think that might help find where the issue is occurring.

**Comment by FIX94** [comment]
found the issue, check out 356 ;)

**Comment by mirrorbender** [comment]
Okay, much better, still one lingering issue.  Everything seems to work perfectly except when you try to scale the width of games that don't natively use the gamecube's scaling feature.  For example, Smash Bros Melee.  Games that do natively use the scaler work perfectly (like twilight princess).  Based on my experience with gamecube video output, I would guess that you just need to manually enable the scaling function of the video interface so that it works in games that wouldn't normally enable it.

**Comment by FIX94** [comment]
melee appears to run fine ingame, just for the menus it forces a different width. I assume that will require a hardcoded patch.

**Comment by mirrorbender** [comment]
Oh wow, thats super weird.  I can confirm that it behaves this way for me too.  A fix at some point would be nice, but obviously it's not super important because the gameplay itself is fine.  Thanks for looking into this =)

**Comment by FIX94** [comment]
I already found a fix for the 1.0 ntsc and jap versions, it'll take me a while to check the rest.

**Comment by FIX94** [comment]
there we go, check out 357, melee should be fine now with all the existing versions. if you find any other game with those weird issues let me know.

**Comment by SirPrimalform** [comment]
Oh... it doesn't look like this was fixed for the PAL version after all. :( 
I've been having trouble with this and when I saw the message that it should be fine with all existing versions I took that to include PAL, but I've just looked at the commits and it only covers 1.00, 1.01 and 1.02.
The PAL version is essentially "v1.03", it's even later than NTSC v1.02 and contains more bug fixes and tweaks.

@FIX94 I know you seem to have moved on to other things, but is there any chance of extending this fix to the PAL version? No one else seems to know where to begin with such a patch but it looks like you fixed it all within a single day so I'm wondering if you could have a look? Sorry for dragging you back, let me know if I'm asking too much.
