### ISSUE TITLE
Fast loading?

### ISSUE THREAD

**Issue by 47iscool** [FIX94/Nintendont#149]
Would it be possible to have feature optional for games that have no issue with it?

**Comment by 47iscool** [comment]
Sorry for the bad wording, I meant "have this feature"

**Comment by 47iscool** [comment]
Didn't mean to close it either. Typing on a droid is not fun.

**Comment by FIX94** [comment]
what the hell is fast loading? Nintendont is already on its limit loading speed wise.

**Comment by 47iscool** [comment]
Faster disc read speed.
You know, like dios mios 2.11

**Comment by 47iscool** [comment]
I guess I worded it wrong. I meant sort of how disc loading was faster but then was reduced for compatibility. A few games as I said before work flawless with it. Sonic and Zelfat games have no issues with fast read speed.

**Comment by 47iscool** [comment]
I meant Zelda. If you still don't understand what I mean look at game setting for Dolphin. It has a an option to make games load a lot faster.

**Comment by 47iscool** [comment]
In-game loading speed. There, that's the best way I can put it.

**Comment by FIX94** [comment]
there you go, added an option for that.

**Comment by 47iscool** [comment]
Thanks a lot. Every game I have has no issue with this.
