### ISSUE TITLE
Issue with Luigi's Mansion unable to save to physical Memory Card

### ISSUE THREAD

**Issue by lotsofluna** [FIX94/Nintendont#150]
As the title says, I'm having a minor issue saving Luigi's Mansion at all to my 1st party Nintendo GC 251 memory card.
![p_20150721_212331](https://cloud.githubusercontent.com/assets/13444703/8816916/b26bed38-2ffa-11e5-8113-86a0c011eb96.jpg)

Attached picture shows the issue, but it also says this on the main menu. My original disc no longer works, which is why I made this backup to play. Not sure why it's doing this, any help would be great thanks!

Nintendont Version: v3.358
Wii Version: 3.4U
Running off 1.5TB WD Green 7200RPM HDD over USB 2.0.
Memory Card emulation is off, and I've many other saves on the card, so I know the card works.

**Comment by carnage702** [comment]
ntsc or pal luigi mansion?

Also 3.4U wii? I tought everyone letted the wii be on 4.3U/E/J but i doubt that is the issue.

**Comment by VinsCool** [comment]
Wii version doesn't matter.

**Comment by lotsofluna** [comment]
NTSC, sorry forgot to mention that. Any idea yet why this happens?

**Comment by carnage702** [comment]
full md5 checked iso?

**Comment by FIX94** [comment]
I'll fix it ASAP.

**Comment by FIX94** [comment]
just commited, I dont own a 1st party card so please test it.

**Comment by lotsofluna** [comment]
Oh wow, that was fast, thanks! I'll check it in a little bit.

carnage702: I don't have any md5 to compare to, I know there's a site that has a huge list of proper md5 and other checksums for loads of games, but I constantly forget the name.

**Comment by FIX94** [comment]
you mean redump.org, they got all gc games registered.

**Comment by lotsofluna** [comment]
yes I do mean redump.org, thanks for reminding me of that!

**Comment by FIX94** [comment]
so it works I assume?

**Comment by lotsofluna** [comment]
I'm so sorry for not responding earlier, yes it works perfectly, thank you
so much! I've really been enjoying Luigi's Mansion now :)

**Comment by Ocultobr** [comment]
Hi, I'm with the same problem here and didn't catch the solution. Could someone please explain what I have to do? Thanks in advance.

**Comment by lotsofluna** [comment]
Hey, all you have to do is update youe Nintendont, I believe. The fix was a
missing piece of code, which was added into a new release of Nintendont.

As well, I'd make sure to use a memory card in slot A.
