### ISSUE TITLE
Spider-Man 2 generally crashes when exiting to hbc

### ISSUE THREAD

**Issue by SuperrSonic** [FIX94/Nintendont#151]
It is possible to exit successfully but most of the time it just fails. In certain spots it always fails, like the title screen.

**Comment by FIX94** [comment]
just checked it and I assume the game has a memory protection on the used area, I will need to disable all protections then I guess on exit to ensure it not failing.

**Comment by FIX94** [comment]
finally got back to this and I think I got it all figured out, the latest version should get rid of this issue.

**Comment by SuperrSonic** [comment]
Thank you, it's working for me so I'll close the issue now.
