### ISSUE TITLE
IPL Enable/Disable?

### ISSUE THREAD

**Issue by 47iscool** [FIX94/Nintendont#152]
Could an option be added to disable the IPL?

**Comment by VinsCool** [comment]
^ I second this. This sure could be useful. Please? :)

**Comment by Zetchzie** [comment]
You cant even get into the bios if you dont dump it into your game folder. By default it is disabled unless you dump it.

**Comment by 47iscool** [comment]
I know that, that's not the point though.

**Comment by Zetchzie** [comment]
It would be easy to implement i bet but i doubt thell do it because that option is pretty usless when you can just remove the ipl yourself.

**Comment by GB-CG** [comment]
Since the https://github.com/FIX94/Nintendont/commit/8d6754a4366516e1fb326b50c3ebe9488cce0ff3 commit, this now can be closed.
