### ISSUE TITLE
Failed start up - Metroid Prime NTSC - PAL Wii - PAL60 video mode

### ISSUE THREAD

**Issue by templar701** [FIX94/Nintendont#154]
Failed start up - Metroid Prime NTSC - PAL Wii - PAL60 video mode

To recreate the issue:

PAL Wii
RGB scart cable and therefore must use Pal60 video mode instead of NTSC mode to avoid red tint in game.
Metroid prime NTSC - disc or ISO
Most basic settings of Nintendon used, i.e. no cheats, no wide screen, no mem card emulation etc.

**Comment by templar701** [comment]
Okay issue fixed:

within - loader\source\main.c 

Insert code to line 895:

if(vmode == &TVEurgb60Hz480IntDf)
{
	*(vu32*)0x800000CC = 5;	
}

This overides *(vu32*)0x800000CC = 1 which breaks metroid prime NTSC in pal60 mode,

Purposes was to be as least disruptive as possible to existing code, hence only apply when PAL60 mode is activated.

Tested it on a few games, on PAL wii, with various modes and settings and nothing breaks thus far.

However I do not know the full implications of the *(vu32*)0x800000CC variable so hopefully when Fix94 gets some free time he can approve or disprove..

**Comment by templar701** [comment]
The same fix can also be achieved if:

(vu32)0x800000CC = 0; 

which is the same value  when NTSC video settings/region are set.

**Comment by FIX94** [comment]
well try out the newest file, I've made some logical changes to it codewise so see how it does.

**Comment by templar701** [comment]
tested with latest version and can confirm that this issue has been fixed.  Metroid Prime 2 also suffered from the same issue, but no longer, many thanks.
