### ISSUE TITLE
Super Smash Bros. Melee cheat crash

### ISSUE THREAD

**Issue by PerfectChaos5** [FIX94/Nintendont#155]
Every time i try to use the debug mode cheat it crashes plz help

**Comment by carnage702** [comment]
Not all cheats work in nintendont, every cheat that talks to stuff that doesnt exist like some registers and such wont work, cheats are a hit and miss on nintendont.

**Comment by PsiLupan** [comment]
I can't even get Super Smash Bros. Melee to run with the Debugger active and a Shuriken USB (Gecko SE Clone) present. The device itself works fine with USB Loader GX and Super Smash Bros. Brawl, so I don't think it's related to the hardware.

If I leave it unplugged until the game starts, it'll crash the game as soon as it's plugged in. Leaving it in during Nintendont start up will freeze Nintendont till it's unplugged, or if I send 3 "init" commands via Gecko.NET (Not sure why 3, but I can consistently get it to load if I sent 3 inits.) I can even get it to send the memory Gecko.NET before the crash will occur sometimes.

As for this issue:
If you're referring to the Developer Menu code, the code that I'm aware of just changes a single "li" instruction to point from Tournament Mode's offset to the Developer Menu. It doesn't change any device registers.

**Comment by Akorax** [comment]
I had cheats working yesterday. Today I updated to nintendont 4.439 and the game now load into black screen when cheats are enabled. This also seem to affect my other games even though I have no cheats installed for them.
I haven't tried filtering out individual cheats yet but those I had working yesterday were:
Unlock All Characters and Stages (PAL) 
Disable Name Tag Reset After Closing Character Port (PAL) 
Extended Character Names (PAL)
Normal C-Stick Functionality in 1Player Modes (PAL) 
Costume Dependent Marth Sword Swing Colors (PAL)
16:9 Widescreen Support (PAL)

My setup
WiiU 5.5.1
Nintendont 4.439
USB HDD WD MyPassport 1TB (Fat32, 64kb clusters)
SDXC 128 GB class 10 level 3

**Comment by FIX94** [comment]
it now ACTUALLY should be good again with 4.440, I actually DID break cheats there for a while, now on my side its all good again though as you can see here:
https://s27.postimg.org/cfdqzoh2b/TV2017050600414800.png

**Comment by Akorax** [comment]
Confirmed working again! Version 4.440. Can't thank you enough for this software. Go fix that donate button in the GBA thread or something :D
