### ISSUE TITLE
Mega Man X Collection video issue

### ISSUE THREAD

**Issue by SevenWillis** [FIX94/Nintendont#156]
This is what happens when trying to use progressive mode.
![img_20150805_071549 1](https://cloud.githubusercontent.com/assets/12851886/9085594/bfb4c07e-3b43-11e5-9404-a6cb6555f220.jpg)

This is what happens when trying to use interlaced mode. 
![img_20150805_072329 1](https://cloud.githubusercontent.com/assets/12851886/9085508/11e7bac8-3b43-11e5-8784-c113b0cf7f06.jpg)

This game does not like widescreen TV's... 
Is there any way to fix this?

**Comment by FIX94** [comment]
just tried for me and though the menus are broken, ingame its smooth 240p with and without force progressive so I might just remove the force progressive patch entirely in megaman because it already uses progressive in the games, so it tries to use 240p for the menu which wont work properly.

**Comment by FIX94** [comment]
so I just commited, also I am sorry to tell you that your tv cannot display 240p which is the default video mode of the game, I cant do anything about that heh.

**Comment by SevenWillis** [comment]
Dang!! 
Would the regular yellow A/V cable work? 
I'll just have to bring out the old tube I guess lol
