### ISSUE TITLE
enhancement: Widescreen and Progressive Patch: Skies of Arcadia Legends

### ISSUE THREAD

**Issue by SevenWillis** [FIX94/Nintendont#157]
I'm not sure about the progressive patch, but know for a fact that there's no widescreen patch, or if there is, it's not being applied.

**Comment by StateOfException** [comment]
Where Widescreen's concerned, Nintendont's inability to force it in Skies can be worked around in the NTSC-U release by using the following Ocarina code: 

04345894 3F400000

That results in relatively issue-free 16:9 support with stretched HUD. Not tested it in the NTSC-J or PAL versions.

**Comment by VinsCool** [comment]
Cool code! It could be implemented by an hardcoded patch for this game :P

**Comment by SevenWillis** [comment]
I don't mind a stretched HUD. Thanks a bunch!
 


     On Monday, August 24, 2015 9:21 PM, VinsCool <notifications@github.com> wrote:
   

 Cool code! It could be implemented by an hardcoded patch for this game :P —

**Comment by FIX94** [comment]
I'll check out that code and see if we cant include it in nintendont.

**Comment by FIX94** [comment]
finally had the time to check this cheat code out and guess what, its inaccurate for some parts :P the value ingame is either 1.1 or 1.0 by default, this cheat only accounts for 1.0 so at parts its getting set too small, I'll have that issue solved in my own version of the patch though.
