### ISSUE TITLE
Enhancement Request - Add moden support 

### ISSUE THREAD

**Issue by carnage702** [FIX94/Nintendont#158]
Just adding this request here so its not forgotten and it would be preety neat to have PSO games and homeland online using the still active fan servers.

**Comment by athendrix** [comment]
Second this! I would totally link my Wiis and play some 8 player of the best Mario Kart ever!

**Comment by hunterbridges** [comment]
+1

**Comment by wangzhenxyz1** [comment]
+1

**Comment by GB-CG** [comment]
Maybe this should be closed since BBA emulation is now working.
