### ISSUE TITLE
Metroid Prime (Eur) showing black screen on start

### ISSUE THREAD

**Issue by askotx** [FIX94/Nintendont#159]
I can load Metroid Prime (Eur) on NTSC TV (60 Hz) through wiiflow loader works fine, but if try to load it from sd:/app/nintendont/boot app directly I get a black screen so I need to press Home button to get back to loader.

**Comment by carnage702** [comment]
Thats most likely becuase your wiiflow has videosettings forced by default, check your default wiiflow nintendont settings i bet it aint in auto.Obviosly you cant run a 50hz game on a 60hz only tv eu either need to force  its videomode to ntsc or atleast pal60.
