### ISSUE TITLE
Classic Controller not working.

### ISSUE THREAD

**Issue by al5ina5** [FIX94/Nintendont#160]
Could you give me a hand to make the CC work? The one with the analog sticks, that connects to the Wiimote.

**Comment by carnage702** [comment]
If your wiimote or Classic controllers are fake/3rd party products the chance they will work is slim, if they are official they always work.

**Comment by al5ina5** [comment]
Mine is official. It doesn't seem to work. Is there some kind of extra set-up needed to use them? I got a PS3 controller to work but my Classic won't work. Can you help?

**Comment by carnage702** [comment]
So both your wiimote and classic controller are official? if so all you need to do is press a button once its ON it will connect, GC/Hid cntrollers have priority over BT controllers like classic controller so if any of those is plugged it will take away the 1st player from classic controller making it be player 2 or more.

**Comment by al5ina5** [comment]
Yeah. I'll try tomorrow and send you another message. Thanks for the replies!

I have the controller that you plug into the Wiimote.

**Comment by carnage702** [comment]
Remenber to check if your controllers are official just look at the screws, if the screws are three sided then its almost certain official if the screws are normal screws then its almost certain its fake/3rd party.

**Comment by al5ina5** [comment]
It's official, I'm 100% sure. Has those screws, has Nintendo logo, and I bought it from GameStop. Doesn't seem to work. Doesn't control anything at all.

**Comment by carnage702** [comment]
tell me all your nintendont settings and version number, maybe you got some bad settings or version.

**Comment by al5ina5** [comment]
Is their a way I could export all settings? I downloaded the latest from the github repo.

If I were to run the "default settings" and reset to defaults it should work, right? It's not.

**Comment by carnage702** [comment]
well just typing them should be easy since there arent that manny sometimes people have acidentaly stuff On that they dont realize.

**Comment by al5ina5** [comment]
Silly me, I was thinking about the USB Loader GX confit, that has a shit load. 

Here are my Nintendont setting:


Here you go. Sorry for the terrible screenshot.

Sent from my iPhone

**Comment by carnage702** [comment]
i see no screenshoot? forgot to upload it?

**Comment by al5ina5** [comment]
Sorry, here’s an Imgur link: http://imgur.com/SC1htTG

**Comment by carnage702** [comment]
Settings and version seem fine so here are some quick questions.

Is your wiimote already sinced with the console before entering nintendont?
do you have any controller plugged to the usb ports?
does the wiimote+CC work fine in nintendont menu?

**Comment by al5ina5** [comment]
Yes, it’s synced.
No, I unplugged the PS# controller.
Yes, it works. I thought it was faulty too, but it works.

**Comment by al5ina5** [comment]
So I just tried connecting my official CC with my non-offices Wiimote and it worked. So weird. My official Wiimote isn't faulty because it works with the CC in the Wii menu.

Another issues I've had is that when using USB Loader GX alongside Mintendont, when laughing, it gets to the Nintendont screen and then freezes and does nothing. Is this something you'd know how to fix? 

Thank you so much!

**Comment by carnage702** [comment]
"when laughing, it gets to the Nintendont screen and then freezes"

no idea what when laughting is, im guessing its loading? it has been stated that the latest usbloadergx rev sometimes freezes when loading nintendont but that is a usbloader gx issue you would need to go to the previous rev of usbloader gx but i dont know where to get it tbh.

So loading nintendont diretly from homebrew channel using only your wiimote and classic controller then choosing a random game on the list, what happens? does the wiimote shut off when the game launchs? gets stuck indefinitly on player 1 light/2/3/4?

**Comment by al5ina5** [comment]
It actually isn't working. My official, on launch all four lights go on and I can't do anything. I've tried re-syncing, batteries, ect.

With my 3rd party Wiimote, it works on the menu then stops working.

**Comment by carnage702** [comment]
the third party one its suposed to do that but the official doesnt even work on nintendont menu? with the classic controller plugged?

**Comment by al5ina5** [comment]
The official works in the menu but does not work in game (ofc).

The CC connected to the official doesn't work in the menu and does not work in game.

**Comment by carnage702** [comment]
i think your classic controller is the issue if it doesnt even work in the menu  im guessing its not official, there is no reason for an official one to fail, just try this, get your original nunchuck and connect it, if the original  wiimote can sync ingame with the nunchuck then your CC isnt officiall most likely..

**Comment by al5ina5** [comment]
The nun chuck doesn't work either.

**Comment by carnage702** [comment]
something wrong with your BT devices either if they dont work no idea why.

**Comment by al5ina5** [comment]
Okay. I'm going to try to install it again. :( thanks anyway.
