### ISSUE TITLE
Controller.ini issue

### ISSUE THREAD

**Issue by quemsabe** [FIX94/Nintendont#165]
Hello,
I'm trying to customize a new controller.ini file to my USB 3rd party controller, with HIDtest. Actually, the controller is recognized by Nintendont and the buttons work without issues, except the DPAD: it works as if the button UP was always pressed. It continues to going up in every game or Nintendont menu even without me touching it.

In the HIDtest the values doesn't change if I leave the controller alone. But in Nintendont menu or ingame the controller acts as if the UP button was always pressed.

This could be some mistake with my controller.ini file? Or there's nothing I can do about it?

Thanks in advice!

![clone](https://cloud.githubusercontent.com/assets/14932457/10235162/600b809a-6870-11e5-9482-313c4e111b2a.jpg)

Controller.ini file: http://pastebin.com/qX68WPbs

**Comment by carnage702** [comment]
Up=6,00 wont this mean that on 00 up is pressed? i think it does so tahts why its always pressed since when not pressed its 00 lol.

**Comment by quemsabe** [comment]
The defaut value of 6th position is 88:

80 80 80 FF 00 00 88 00 

When "up" is pressed, the 6th position goes to 00.

**Comment by carnage702** [comment]
Thats your controller problem,  by using 00 your basicaly saying that when the controller isnt sending anything up is pressed, so no idea what you can do really maybe get ride of it is all i can think off loose dpad up lol.

**Comment by quemsabe** [comment]
Thank you for the help.
I'll try another controller.

**Comment by H0neyBadger** [comment]
Maybe you can test your controller on a computer (e.g: on an emulator)
Often with this kind of controllers the initial position is set up when you plug it in.
So I encourage you to recapture your initial position without touching the dpad.

**Comment by quemsabe** [comment]
In computer emulator the controller works fine.
I deleted the controller.ini file and started from scratch. The results are the same:

![controller](https://cloud.githubusercontent.com/assets/14932457/10260490/aef75df0-694c-11e5-9075-87e30d6ae8d5.jpg)

Tried to invert the values (6,88 instead of 6,00) but it fails.
Maybe Nintendont can't map the 00 value for DPAD position? 

I'm really confused.

**Comment by FIX94** [comment]
hey man, I have a test file for you:
https://www.mediafire.com/?ycrn777jx5sd23h
Use 6,00 for this, with this file it should detect that and check for 0 when up is pressed. Please report back so we might add this to the actual nintendont versions.

**Comment by quemsabe** [comment]
Hey, that works! Now the controller is working flawless. 
This is the new controller.ini file: http://pastebin.com/CCGhwxQG 
Thanks a lot, FIX94! It was an honor to receive a reply from you.

**Comment by FIX94** [comment]
cool, does rumble work with that as well? that would be one of the very few with it working.

**Comment by FIX94** [comment]
oh well, we can close this issue for sure.
