### ISSUE TITLE
Progressive Scan Display

### ISSUE THREAD

**Issue by AquaPheonix** [FIX94/Nintendont#166]
I'm trying to play super smash brothers melee and whenever I load up the game it leads me to a screen that tells me if I want to enable progressive scan. My GameCube nor wireless controllers can get past this screen. I keep clicking A and Start and Plus but it won't take me past the screen

**Comment by AquaPheonix** [comment]
I'm on a wii u and I'm using the official GameCube adapter btw

**Comment by carnage702** [comment]
you made sure you didnt activate native controlls in the settings?
