### ISSUE TITLE
Problems with official gc adapter for wii U 

### ISSUE THREAD

**Issue by WayneMario** [FIX94/Nintendont#168]
The problem is that at certain times in specific games (for example at the vehicle select screen in Kirbys air ride PAL and during the four player micro games in the wobbly turtles mode of Warioware Mega Party games PAL) the controllers in ports 3 and 4 miss some inputs as well as outputting inputs with severe lag.  Ports 1 and 2 work fine however and ports 3 and 4 work the rest of the time.  Also other controllers such as WiiU pro work fine at these parts as controller 3 or 4. Using nintendont version 3.373.  Adapter plugged into front USB ports.  Games run off SD card on a wiiU. Mc emu on and MD5 hash confirmed.  Any help is much appreciated

**Comment by FIX94** [comment]
sorry for taking so long but I have that fixed in the latest 378 commit, let me know if it all works now so we can close this issue.

**Comment by WayneMario** [comment]
Thank you very much.  Working great now with all games.  :)

**Comment by FIX94** [comment]
cool that was fast, also I made a even newer commit because I made a mistake in that fix again heh, I always realize things like that when its already too late :P

**Comment by WayneMario** [comment]
Cool I make sure to get it.  Thanks for all your hard work.
