### ISSUE TITLE
Enhancement Request - Wii U Gamepad Support

### ISSUE THREAD

**Issue by Zetchzie** [FIX94/Nintendont#169]
I don't know if this is possible but it would be nice to be able to use the gamepad to play.

**Comment by carnage702** [comment]
Not possible, this could only be possible when all the wiiu keys are dumped and someone dumps Cafee2wii(vwii bootup) and  modifies it to enable gamepad control on vwii.

**Comment by Zetchzie** [comment]
Well then time to play the waiting game.
