### ISSUE TITLE
Enhancement Request - Individual Game Configs

### ISSUE THREAD

**Issue by Zetchzie** [FIX94/Nintendont#170]
I think there should be an option to use a config file for games so that you can load special fixes (Widescreen, No Limit, etc) For certain games and leave the options off for the games that don't work so you don't need to flip the options on and off when loading and unsupported game.

**Comment by carnage702** [comment]
Nintendont will never support this, nintendont is not made to be a Full GUI, if you want per game configs you can simply use usbloadergx,wiiflow or cfg, they allow per game configs and use nintendont to boot up the games.

**Comment by Zetchzie** [comment]
I didnt know this was possible thank you.
