### ISSUE TITLE
Enhancement Request - De-Flicker Disable

### ISSUE THREAD

**Issue by Zetchzie** [FIX94/Nintendont#171]
Apparently Swiss on Gamecube can disable the De-Flicker to make games look sharper is this possible to get on Nintenont?

**Comment by carnage702** [comment]
Yes if you have the latest nintendont 373 go to video options and change force videomode

the videomodes 
force ntsc,Force pal and such have defliker disabled

the videomodes
force ntsc(defliker),and such have defliker enabled.

**Comment by Zetchzie** [comment]
Thanks i was unaware of this feature ^^
