### ISSUE TITLE
Metal Gear Solid Twin Snakes Renders Very Dark

### ISSUE THREAD

**Issue by Zetchzie** [FIX94/Nintendont#172]
MGSTS Renders everything extreamly dark idk if theres anything you can do but im just throwing it out there.

**Comment by carnage702** [comment]
Nintendont does not mess with the graphics, if its very dark its probably due to your TV settings or wii settings connection.

**Comment by GB-CG** [comment]
@Zetchzie That's odd. Both my PAL copy & the NTSC worked fine on my end, disc and ISO too. If you using an ISO, it may be a bad dump?

**Comment by Zetchzie** [comment]
im not the only one apparently someone has this on issues for it on gbatemp on compatibility. when crawling in vents everything is almost black unless your tv is at max brightness.

**Comment by GB-CG** [comment]
Have you tried loading the ISO straight from the SD card? I play Twin Snakes from SD:/games/ and my picture is fine. I haven't tried USBLoader GX to be honest.

**Comment by Zetchzie** [comment]
ive played from both. could it be a compression issue, or the disc being scratched? I really dont want to look for another copy >.<

**Comment by VinsCool** [comment]
Brighten the tv settings lol.

**Comment by Zetchzie** [comment]
I did but it still shouldnt be so dark that vents are pitch black. All the colors are washed out when too bright.
