### ISSUE TITLE
Custom Files Support 

### ISSUE THREAD

**Issue by Zetchzie** [FIX94/Nintendont#173]
Would it be possible to load custom textures, music, models, etc. Into gamecube games. It would be a cool feature. You could have a folder that Nintendont loads in the game folder to apply your own things onto the game.

**Comment by carnage702** [comment]
Or you could just inject them on your iso no? 

you can use extracted isos and replace everything you want since the begiining of nintendont, an alert is that extracted isos load much slower.

**Comment by SystemRevolution** [comment]
Like GeekoOs to wii games. But is better to inject custom files into the iso files.

**Comment by Zetchzie** [comment]
Yeah but if only there was a way without messing with the iso
