### ISSUE TITLE
Option to load both USB and SD at once 

### ISSUE THREAD

**Issue by Zetchzie** [FIX94/Nintendont#174]
It would be nice to be able to load both games from USB and SD so you wouldn't need to choose and just have one list you can choose from.

**Comment by carnage702** [comment]
Nintendont can only mount one device at a time so no, also please stop opening issues left and right with sugestions every noone real issues are not to be posted here but on the actual nintendont thread http://gbatemp.net/threads/nintendont.349258/  .

**Comment by Zetchzie** [comment]
Sorry
