### ISSUE TITLE
Save/ Load GCI From Folder & Import/ Export GCI From Raw's

### ISSUE THREAD

**Issue by Zetchzie** [FIX94/Nintendont#175]
So whenever you save it goes into a virtual memory card in the saves folder on [GameID].raw. How about we just add the option to just save the files themselves (files in the raw) into a folder. It's easier to manage them instead of navigating them with dolphin. Dios Mios does this with No More Memory. So why not here too.

**Comment by SystemRevolution** [comment]
The complication could be caused by GC-mem size report, mainly because some games don't work property if an non standard size is reported.

**Comment by Zetchzie** [comment]
Couldn't there be a way to trick it? larger then 128 is unstable if i remember.

**Comment by SystemRevolution** [comment]
251 blocks are safe, beyond, comes unsafe area...
In all case, is better to create a bath importer/exporter, but it should be in linux/windows.

Another possible solution could be an function to import the GCI to raw files and export it when home button is pressed (or power button, or exit combo).

**Comment by Zetchzie** [comment]
that would be so much better. its not much of a needed feature but it would save some space on your storage device without the extra memory that isnt used if it could just load the gci files from a folder. is it possible to apply rules to a folder or is raw the best format?

**Comment by Zetchzie** [comment]
An export/ import feature would be usfull since some games require saved files from other games to unlock things.

**Comment by carnage702** [comment]
To do that it would be a tremendous amount of work to fake a memory card not to mention alot of issues for something so useless again please stop opening issues left and right if its a sugestion please post it on nintendont thread http://gbatemp.net/threads/nintendont.349258/ .

**Comment by Zetchzie** [comment]
seriously?! Why would this be useless?

**Comment by Techinicabor** [comment]
Just use a physical memory card and/or some save managers. No need to get fancy when it can already be done.

**Comment by Zetchzie** [comment]
not many managers when you're a linux user. and dolphin does not support my specs so I cant install it. Can't find anything that does just that. but anyways sorry to be a burden Nintendont already does everything the devs are willing to let it do at this moment so won't hear from me unless i experience game issues.

**Comment by carnage702** [comment]
Its uselss becuase you dont need to manage saves ... why do you want to continuasly inject and delete saves to begin with. Nintendont already has settings for individual memory card(1 per game) and multi card (1 for all the games)  and again i see no reason why would one person constantly manage their saves.

Also about DM do you see DM no memory card compatibility list? Just see it and you will be amazed on how bad it is, theres a reason why we use full raws and not loose gci files.

**Comment by Zetchzie** [comment]
A few games unlock stuff when another save is present on the memory card. Sega games mostly but anyways its a useless feature so nevermind ill find a tedious work around.

**Comment by GerbilSoft** [comment]
Dolphin does let you manage memory cards even if you can't run games due to an unsupported video card.

I have been working on adding write support to GCN MemCard Recover, which runs on Linux, but I've been working on other projects as well. Once that's done, you'll have an option for a better memory card manager.

**Comment by carnage702** [comment]
that is basicaly 5 or 6 games and you only need to inject the save once and doing memory card management once for 6 games isnt n hassle at all.

**Comment by Zetchzie** [comment]
Plz tell me when you get it done lol thanks ^^ Ill try to run an old dolphin ver in wine until then. dolphin does not support x86 architecture anymore
