### ISSUE TITLE
Swap through games from Gamecube Bios

### ISSUE THREAD

**Issue by Zetchzie** [FIX94/Nintendont#176]
Would it be possible to switch games that are on storage from the gamecube bios. Just somthing purly asthetic. so you get that feeling your really swapping games out.

**Comment by carnage702** [comment]
No, nintendont doesnt work like that the game list is when nintendont is not doing anything so its easy to show, but when in the bios a game is already loaded for the bios to work not to mention you would need to make a custom bios that would read usb and game ids, this would basicaly be amking a totaly new bios altogether.
