### ISSUE TITLE
Control glitch on Wii Remote + Nunchuck

### ISSUE THREAD

**Issue by GeorgXtremE** [FIX94/Nintendont#177]
I got a problem with the controls on the wii remote with the nunchuck. When I was playing Super Smash Bros. Melee with the Wiimote + nunchuck, for some reason, the shield stays on and I'm not pressing any buttons. Also, whenever I press the B button on the back, for some reason, it activates the shield instead of the special attack sometimes. And last, but not least, in Mario Kart Double Dash, sometimes when I move the thing on the nunchuck, it makes the drivers start drifting(and normally I just move without drifting.) I have to keep shaking the controls, pressing the buttons, and unplug and rep lug the nunchuck to make the glitch stop. It works, but not for long. (Also, I know that the Wiimote and nunchuck aren't broken.) Can someone help me out?

**Comment by carnage702** [comment]
Are they official produtcs both wiimote and nunchuck? if they are 3rd party/fake ones then that might be the issue.

**Comment by Ryuzaki-MrL** [comment]
Same here. Some games keep the L button held down when I use a third party Classic Controller (doesn't occurs when I use an original one)

**Comment by carnage702** [comment]
thats becuase the 3rd party one for sure sends the L pressed button signal to nintendont constantly, like manny homebrew apps 3rd aprty/fake controllers compat isnt the best.

**Comment by GeorgXtremE** [comment]
Okay

**Comment by shine-spike** [comment]
Change your controller configuration, more info [here](https://gbatemp.net/threads/nintendont-wiimote-nunchuck-support-discussions.371356/).

**Comment by Timowa-crtl** [comment]
I’m hitting the same issue as @GeorgXtremE, even **10 years later**, using **official Wiimote + Nunchuk**.

I took me quite some time to find out the reason for this behaviour: The default Wiimote+Nunchuk mapping uses **Nunchuk tilt** for GC **L/R**, which causes **phantom L/R presses** (shield stuck in Melee, random drifting in Double Dash) from normal movement. This is not a hardware issue and not a bug, it is the intendet default behavour of Nintendont, that is not well suited for games like Melee or Double Dash.

The link posted by @shine-spike explains the available Wiimote+Nunchuk mappings:
[https://gbatemp.net/threads/nintendont-wiimote-nunchuck-support-discussions.371356/](https://gbatemp.net/threads/nintendont-wiimote-nunchuck-support-discussions.371356/)

In my opinion, the default mapping is fine **except** for using Nunchuk tilt for L/R, which causes these problems. Changing the default to a non-tilt L/R mapping (or documenting this more clearly) would help avoid confusion.

Below is the default controller layout showing Nunchuk tilt mapped to GC L/R.
The mapping can be changed in-game by holding **“2”** on the Wiimote:

<img width="560" height="435" alt="Image" src="https://github.com/user-attachments/assets/0f2c13e8-5b71-496f-8eeb-a6779603c092" />
