### ISSUE TITLE
Crashes with 2 harddrives plugged in

### ISSUE THREAD

**Issue by jiBYo** [FIX94/Nintendont#178]
Hey, I have two usb harddrives for my Wii. When I try to play a game loaded from usbloader gx, it will crash unless only one drive is plugged in. Is there a way to fix this or is this not possible?

**Comment by carnage702** [comment]
There is no fix, nintendont can only mount one hdd at a time and the way usb was made to work for nintendont it panics when it sees 2 hdds so yes the only way to fix this is unplug the other, however anyone is free to recode the usb code for this if they want.

**Comment by jiBYo** [comment]
I worked it out.

You need to setup usbloader gx to use both usb ports, then make sure the gamecube drive is the second one instead of the first. I've done this and now it is all working perfect :)

I figured it out when I ran nintendont by itself outside of usbloader gx, and tried to load usb and it said there was no games folder on the drive, so I made one on the second drive to test and then it loaded. All I had to do was swap what drive was on what port and bingo
