### ISSUE TITLE
Can't play Grand Prix mode on F-Zero GX

### ISSUE THREAD

**Issue by LaureHebrero** [FIX94/Nintendont#179]
When I try to play Grand Prix mode the screen goes black and the game says something that I don't understand (English is not my first language) the music keeps playing but the screen stays in black. I have the Nintendont v3.373.

**Comment by carnage702** [comment]
nintendont settings please and iso md5,  also it would be nice if you posted the error.

**Comment by LaureHebrero** [comment]
My nintendont settings are everything in off exepct for:
Memcard emulation: on
MaxPads: 4
Video: Force
Videomode: PAL50
Memcard Blocks: 251
Video Width: Auto
Screen Position: 0
The MD5 is: B3E4932731C63B98F0617E6764CC364D (I think maybe this is the problem)
And thank you for helping me.

**Comment by carnage702** [comment]
why are you forcing pal50?old crt tv that only has pal50?

Also that md5 does not match any md5 of any f zero gx iso, try to get a 1.35gb iso which md5 matches redump

usa 81293462cf48c6a482c33e25c4097ac0
eur  e1081d2e1701de9dd5114388e361dbdf

**Comment by LaureHebrero** [comment]
I have and iso now and its md5 matches with the USA, and if I try the video on auto the game is black and white now (but I can play grand prix mode). I try any combination on video mode but still black and white or can't play grand prix mode.

**Comment by carnage702** [comment]
on what console are you?wii? if you are on wii what are you using to connect to the tv? what cable?
Are you using the ntsc version on a Pal tv?

**Comment by LaureHebrero** [comment]
Problem solved, that was the problem I was using the wrong cable. Thanks for your help.
