### ISSUE TITLE
Analog Triggers

### ISSUE THREAD

**Issue by Gnawty** [FIX94/Nintendont#180]
I removed my springs from my game cube controller and whenever nothing is pressed it acts as though L and R are pressed. I resolved this issue by setting the value in controller ini file to 1. But this makes it so there is no analog functionality with a controller with springs. Is there anyway to fix this trigger issue without setting the analog values to 1? I'm using this to play melee with friends that's why I need that functionality.

**Comment by carnage702** [comment]
What? so you remove the springs and expect everything to work? lol  no there is no way to fix it why would anyone remove springs and then expect the pressure sensitive trigger stuff to work correctly when there isnt a spring pushing the button out after its let go...

**Comment by GB-CG** [comment]
I wonder if the Hori Nintendo Game Boy Player Controller works with Nintendont & Melee combined? At least that pad doesn't have springs on it.
