### ISSUE TITLE
Nintendont crashs Wii U if started without USB-Stick

### ISSUE THREAD

**Issue by CaptainCoward** [FIX94/Nintendont#181]
Usually Nintendont works pretty well for me but today i started Nintendont without having my USB-Stick (where my games are stored) connected. I expected that Nintendont will start anyway since i have it installed on my SD-Card but the WiiU just blackscreened and i had to pull the plug to reset it. Is there any way to prevent that to happen?  I don't really want to keep my USB Stick connected all the time since the WiiU keeps asking me to format it.

**Comment by carnage702** [comment]
So explain this to me you say you have nintendont isos on usb  and you want to start nintendont without any games for some reason? why? i mean if you dont have anything on the SD card whats the point of even starting nintendont?

**Comment by CaptainCoward** [comment]
The WiiU keeps asking me to format my Flashdrive so i don't have the flashdrive connected most of time. It sometimes just happen that i forget it and fire up Nintendont.
All i wanted to know is if there is a way to prevent it from crashing when i do that.

**Comment by carnage702** [comment]
there is no crash for anyone, afaik unless you are using a fowarder that probably is directly linked to the usb nintendont will never crash atleast it doesnt for anyone that uses it on the homebrew channel directly but if your using a loader or a fowarder it might be hardcoded for usb.

**Comment by carnage702** [comment]
upps clicked wrong button.

**Comment by CaptainCoward** [comment]
I start nintendont via homebrewchannel. So i really don't know what's the issue. I mean it's not a big deal. It just would be nice if i wasn't punished with a crash/blackscreen for forgetting to connect the usb stick. I guess i will force myself to just not forget it anymore. Thank you anyway.

**Comment by carnage702** [comment]
you probably had a corrupted loader dol then.
