### ISSUE TITLE
F-Zero AX vehicle speeds are slower than they should be

### ISSUE THREAD

**Issue by yoshifan** [FIX94/Nintendont#182]
Nintendont v3.373 (also happens with 3.375, latest at time of writing): https://www.youtube.com/watch?v=QG_xoy50AmM
Quadforce v4.0: https://www.youtube.com/watch?v=gH6qCoWDU3o

In the video descriptions, there are links to camera recordings of gameplay on real AX arcade machines. As far as vehicle speed goes: Arcade machine = Quadforce > Nintendont.

All vehicles and accel/maxspeed settings are affected, but it's more noticeable on high max speed configurations. It is generally better to test in Time Attack because in Race mode, the farther you are behind the CPU, the faster you go.

I have a decent guess about the cause of this speed issue. Whenever I re-press the accelerator after releasing it, it's supposed to make a distinct sound. That sound occurs in Quadforce, but not in the Nintendont versions I've tried. My guess is that the accelerator input is off in Nintendont - either the analog accelerator input is not allowed to be pressed all the way, or there exists a separate digital input that is not being triggered.

The implications of not getting the whole accelerator input aren't precisely understood, but here's what I know. F-Zero GX also has analog acceleration, which is observable if you map the accelerator to a shoulder button. In GX, holding the accelerator only partway makes you accelerate slower and go slower: https://www.youtube.com/watch?v=cEtneG44I_I
AX and GX physics are NOT the same, but I'd at least expect them to behave similarly in regards to holding the accelerator partway.

**Comment by FIX94** [comment]
I bet thats because I only set 0x7F, will have to check that in all games again.

**Comment by FIX94** [comment]
yea that fixed it, 0xFF is needed in nintendont and in quadforce its only 0x7F, just shows how different the much more hacky quadforce controls behave differently from nintendonts clean controls.

**Comment by yoshifan** [comment]
Well that was quick. And it's definitely fixed now, thanks a lot!
