### ISSUE TITLE
[PAL] Tony Hawks 4 disc does not run on NTSC signal

### ISSUE THREAD

**Issue by GB-CG** [FIX94/Nintendont#184]
Seems like this 50hz-only game is not working with NTSC (480i/480p) signal.

Using v3.380 on a PAL Wii, I've tried -

'Patch PAL50' with 'Auto' Video: No signal.
'Patch PAL50' with 'Force PAL60: 288p 50hz, but stable. (that's new to me)
'Patch PAL50' with 'None' Video: 576i only.
'Force NTSC' video but Patch PAL50 turned off and on: 480i, but no signal.

**Comment by carnage702** [comment]
Most pal games do not work when forcing videomodes on them it depends on how much the game is hardcoded to the 50 hz.

im preety sure you can play the game with video on auto and patch pal 50 off.

**Comment by GB-CG** [comment]
Yeah, I mean it runs fine on 576i but I was just curious, that's all. I've managed to run 60hz with a PAL disc of Luigi's Mansion, Twin Snakes and Wave Race Blue Storm with the Patch PAL50 mode.

**Comment by carnage702** [comment]
some games are very hardcoded to force videomodes and would need custom pathces and hack for them wich is too much work really specialy when the ntsc iso exists already.
