### ISSUE TITLE
[NTSC] "Ocarina of Time: Master Quest" Missing Textures

### ISSUE THREAD

**Issue by OTFree** [FIX94/Nintendont#186]
Currently running the most recent version of Nintendont as I'm typing this. For some reason, there are certain textures that either display incorrectly or don't appear all together. It's worth mentioning that this issue doesn't occur with the Gamecube port of OoT from the Zelda Collector's Disc. It'd be one thing if the graphic issue was only cosmetic, but since Gohma's eye texture doesn't render correctly, it's impossible to trigger the fight.

**Comment by FIX94** [comment]
I did play a lot of zelda with nintendont over the development phase and oot master quest from the bonus disc was one of them, I had no issues with it whatsoever, are you sure you are using a clean copy of this?
http://redump.org/disc/707/
Make sure the checksums match and also dont modify the files you use with any "compressors" or anything like that to ensure they work properly.

**Comment by OTFree** [comment]
Huh, strange. I suppose it could be the disc I used for the rip then! Thank
you for the quick reply, it's much appreciated and keep up the good work (:
