### ISSUE TITLE
"Call of Duty: Finest Hour" (Europe) Not work

### ISSUE THREAD

**Issue by DubKiller13** [FIX94/Nintendont#189]
I start the game without settings enabled, but frezzes, no show the proggress of load (Mounting Sd/Usd... Etc) only show the background of nintendont and no start (sorry for my bad english, i talk in spanish) if someone can help me, i want to play it

**Comment by carnage702** [comment]
Are you using a usbloader? if so try starting the game directly from the homebrew cahnnel using nintendont.

**Comment by DubKiller13** [comment]
Nintendont via HBC

**Comment by DubKiller13** [comment]
I tried with USB Loader GX and doesn't work too

**Comment by carnage702** [comment]
iso md5 value?

**Comment by DubKiller13** [comment]
The iso work in dolphin

**Comment by carnage702** [comment]
is your wii european? just making sure your not one of those people using a ntsc wii  on a ntsc tv with no pal mode compat, you sure wide and videomodes are in auto?

**Comment by carnage702** [comment]
if all abode is true try turning mcemu on.

**Comment by DubKiller13** [comment]
My Wii is Ntsc, my tv is region free, i can run super mario sunshine pal (with 60/50hz) and works fine, no problem, i run the CoD in auto and pal, pal50 and pal60 not anythin works

**Comment by DubKiller13** [comment]
I do not know what is mcemu :c

**Comment by SevenWillis** [comment]
MCemu is memory card emulation

**Comment by DubKiller13** [comment]
Ok, i have the wii black (Family edition) and i use that funtion, but in off or on dont work, but only in that game, now i playing the Resident Evil 4 (Europe) and works fine, but the CoD dont work

**Comment by carnage702** [comment]
the only reason for it not to work is becuase of the iso imo just becuase it works on dolphin doesnt mean it works on nintendont since nintendont is more picky, get a md5 checking app and see if the iso is full 1.35gb iso md5 is valid.

http://www.mediafire.com/download/5y3tfpoil433rij/MD5_SHA-1+Utility.exe

**Comment by DubKiller13** [comment]
Ok. I will try it, but mi pc is dead ;-; when i try it, i post my results here

**Comment by DubKiller13** [comment]
I checked the md5 and show this: http://prntscr.com/9ldye2

**Comment by DubKiller13** [comment]
I compare with this http://redump.org/disc/8669/ and have the same md5

**Comment by carnage702** [comment]
tell me all your nintendont settings and i mean all same for the nintendont version number please dont say latest.

**Comment by DubKiller13** [comment]
Nintendont version is 3.34 (i guess) when i try the game i run with all setting in default (mcemu off, only the hid USB controller support on) i deleted nin.cfg file many times, but doesn't work

**Comment by DubKiller13** [comment]
I try to running from a SD card and USB bot no works

**Comment by carnage702** [comment]
34? no wonder it doesnt work, the latest version is 3.381 try updating nintendont to the latest.

**Comment by DubKiller13** [comment]
I updated nintendont and still stucks here: http://prntscr.com/9ln6lk

**Comment by GB-CG** [comment]
@DubKiller13 I tried it out too. It works for me, but for some reason, I had to press 'A' to make it run. https://www.youtube.com/watch?v=Eeh-rgH4WVU (PAL wii)

Booted from the SD card, The md5 I use is the same too. If I use MCemu, it fails to read to the card.

**Comment by carnage702** [comment]
GB-CG i noticed you were using some noone standard options, try making the languae on auto(auto is always english btw) and maxpads on 4 and width on auto it should fix those wierd bugs in the video lol.

**Comment by GB-CG** [comment]
Whoops. Ok, I'll do that tonight. haha

**Comment by carnage702** [comment]
well i talked to Fix94 and he took a look at it and there was a bug, where COD pal matches a multidisc tool id which is why it had all those issues lol.

New rev is out 382 wich fixes that and the game works with no problems now with mcemu and not pressing A and whatnot so check 382 out.

Either by updating inside nintendont or downloading it manualy here.

**Comment by GB-CG** [comment]
By the way, I've tried what you've suggested and it didn't fix the text alignment issue. (If that's what you've meant that is.) So, I'll try the new version in a bit.

**Comment by DubKiller13** [comment]
i going to update in the night

**Comment by GB-CG** [comment]
Yep, everything's aligned correctly now, for me, at least.

**Comment by DubKiller13** [comment]
Yes, I Update to 382 and works fine, no load problem or perfomance problem, works 100℅, i use the mcemu on 251 blocks and no problem, works on all games, thank for you help, you help me a lot
