### ISSUE TITLE
A/B button reversal

### ISSUE THREAD

**Issue by SevenWillis** [FIX94/Nintendont#193]
Is it possible to add A/B button reversal for games like Mega Man AC? They totally messed up the mapping and naturally there is no way to change that.
However I don't expect a commit for one person and one game.

**Comment by FIX94** [comment]
well you are in luck, I wrote a patch for that back in 2014!
http://www.mediafire.com/download/ctkj7ww9r46qqbe/Mega_Man_Collection_Button_Changer.7z

**Comment by SevenWillis** [comment]
Sweet deal. You are the man! Cheers!
