### ISSUE TITLE
Zelda: Collector's Edition compatibility issues with recent revisions

### ISSUE THREAD

**Issue by Kialect** [FIX94/Nintendont#194]
Using the latest January 3, 2016 revision, the video signal drops upon loading Ocarina of Time or Majora's Mask. The Wind Waker demo and FMVs run fine, although I didn't check Zelda I & II. Anyway, I got a hold of revision 3.341 as it was the version listed in the Nintendont Compatibility List and sure enough, my issues were resolved. I'm not sure which revision between 3.341 and 3.382 is the culprit for this bug, but I thought I'd report it in for future compatibility.

Game: The Legend of Zelda: Collector's Edition
Region: NTSC (USA)
System: Wii
Revision: 3.382
Last working revision: 3.341
Storage: SD card
ISO: 1:1 (md5 verified)
Memory card: Tested on real & emulated
Native control: On
Video output: HDMI

**Comment by carnage702** [comment]
im guessing your using width options? post all your nintendont options.

**Comment by Kialect** [comment]
Thank you for your response, that fixed the issue. The width options seemed so trivial that it didn't occur to me that they were causing anything. It also explains why I had success with 3.341, as the width options were absent in that revision.

**Comment by carnage702** [comment]
yeah we need a warning saying width is extremely unstable sort of thing, glad it fixed your issue, when you have another issue be sure to report by putting all your nintendont setings too.

**Comment by earithramir** [comment]
Hi Could u please elaborate what to do to fix this problem?
My image is disturbed when there is no moving image on screen, on the classic versions on this disc. (like the nes/snes versions) 
Tried juggling with the video settings but none seem to work.
https://imgur.com/a/GuxB9jF
Also i do not see any width options. (currently trying to change these options from within usb loader gx, maybe thats the problem?)

Thanks in advance!!

**Comment by carnage702** [comment]
width setting is imcompatible with most games including that one, put it at zero or auto whatever default value it was.

**Comment by earithramir** [comment]
What can i do to rectify the image, is there a way?
My wii wont read the disc, "unable to read the disc." it tells me uppon inserting the disc.
There are some minor scratches. I was hoping to be able to play the game.
Can u tell me if this game should be working or do i need to do some tuning with the settings?

**Comment by GB-CG** [comment]
@earithramir What version of Nintendont do you use? And have you tried launching the iso directly from Nintendont?

**Comment by earithramir** [comment]
Nope not yet directly. And using the latest download from repo 4.443 the file that is referred to in the readme

**Comment by earithramir** [comment]
Will try directly tonight and post results

**Comment by earithramir** [comment]
Hi,

Just updated the version to the suggested one.
And resetted all settings to 0, except for maxPads: 4, Video: None, Video width: auto and Language: auto. The game loads faster but the image is still desturbed / fuzzy like the picture. 
Its now showing version 5.485 by the way.
I used these settings: https://imgur.com/a/HL2Jm3h
Do i need to do something more ?
Really apriciate your help!

**Comment by earithramir** [comment]
Hehe I know I know, but the image has horizontal lines over the full screen, they disappear when there's movement of u like I can post a vildeo. Some emulators have a feature that mimics crt,  almost like that. But then only when image is still e.g. paused or just a image without movement. The strange thing is it only occurred on the "emulated" versions of the disc the other games look sharp.

**Comment by carnage702** [comment]
well have you ever saw videos of it on youtube to see if they runned like that in the first place?
Fix94 the nintendo developer even made some videos of some games

https://www.youtube.com/watch?v=9kiJ4z1csDg

**Comment by earithramir** [comment]
No, i haven't.
But the issue described looked like my own.
As said most games (even on that disc) are looking good, even better then my Wii games.
