### ISSUE TITLE
Usb drive problems

### ISSUE THREAD

**Issue by DewyTheD** [FIX94/Nintendont#196]
I recently uograded from using my 16GB Usb flash drive to my 320GB Usb HDD, they are both FAT32 and the 320GB Doesnt work, It DOES work however that only works on my Wii and Not my Wii U whereas the 16GB Flash Drive works on both, is this to do with Nintendont at all or is it to do with the Wii U's Usb ports?

**Comment by FIX94** [comment]
thats the wiiu for you, terrible power output. get yourself a usb y cable for that hdd and it should work, you only have these issues with usb-powered devices, hell even the official gamecube usb adapter needs 2 ports on wiiu and on wii it only needs one lol.

**Comment by DewyTheD** [comment]
Hey thanks man for such a quick response
