### ISSUE TITLE
USB Hard Drive Problem

### ISSUE THREAD

**Issue by nutella511** [FIX94/Nintendont#197]
I am launching Nintendont via CFG USB Loader version 70r78.10, and on launching a game, it black screens. My drive works when launching Wii backups, but not Gamecube. I have it formatted to Fat32 with a 32KB Cluster size.

**Comment by FIX94** [comment]
then please dont use a backup loader but just use it as intended through the actual file and the homebrew channel, if even that doesnt work we can talk.

**Comment by nutella511** [comment]
I tried that, and the game boots, but then gives me an error has occurred.

**Comment by nutella511** [comment]
Found the issue was progressive mode.
