### ISSUE TITLE
Sonic Mega Collection randomly freezing

### ISSUE THREAD

**Issue by SevenWillis** [FIX94/Nintendont#198]
The game freezes about a minute or two after booting. The ISO is a clean 1:1 rip from disc.

Nintendont IOS58 v24.32
Built   : Jan 23 2016 20:46:16
Version : 3.385
Game path: /games/Sonic Mega Collection (US) [GSOE8P]/game.iso
ISO:Fragmented, allocating 00000006
EXIInit Start
Trying to open /saves/GSOE.raw
Kernel Start
DIP:DOL EntryPoint::0x80002F8C, GameEntry::0x80003140
Patch:Offset:0x00003100 EOffset:0x004002C0 Length:003FD1C0
Patch:Game ID = 47534f45
Patch:[SI] applied 18 times
Patch:[AI] applied 17 times
Patch:[DI] applied 42 times
Patch:[ReadROM] applied (0x0019F890)
Patch:[SetInterruptMask] applied (0x001A0364)
Patch:[__OSDispatchInterrupt] applied (0x001A074C)
Patch:[__OSResetSWInterruptHandler] applied (0x001A14B4)
Patch:[OSGetResetButtonState A] applied (0x001A1550)
Patch:[EXIImm B] applied (0x001A3980)
Patch:[EXIDMA B] applied (0x001A3C7C)
Patch:[EXISync C] applied (0x001A3D68)
Patch:[__EXIProbe B] applied (0x001A4034)
Patch:[EXISelect B] applied (0x001A44A4)
Patch:[EXIDeselect B] applied (0x001A45D0)
Patch:[EXIntrruptHandler C] applied (0x001A46E8)
Patch:[TCIntrruptHandler C] applied (0x001A47B0)
Patch:[EXILock B] applied (0x001A4B9C)
Patch:[EXIUnlock B] applied (0x001A4CF0)
Patch:[CompleteTransfer A] applied (0x001A5518)
Patch:[SIEnablePollingInterrupt A] applied (0x001A5B88)
Patch:[SIEnablePollingInterrupt A] applied (0x001A5B8C)
Patch:[SIInit D] applied (0x001A5DCC)
Patch:[SIInterruptHandler] applied (0x001A57E4)
Patch:[SIInterruptHandler] applied (0x001A5910)
Patch:[__SITransfer A] applied (0x001A5E7C)
Patch:[__SITransfer A] applied (0x001A5F64)
Patch:[SIGetType A] applied (0x001A6854)
Patch:[__DVDInterruptHandler]: 0x001A755C (0x001A755C)
Patch:[VIConfigure] applied (0x001AC3A8)
Patch:[PADRead A] applied (0x001ADD1C)
Patch:[ARStartDMA] applied (0x001AF420)
Patch:[ARInit] skipped (0x001AF5BC)
Patch:[__ARHandler] applied (0x001AF6BC)
Patch:[__ARChecksize A] applied (0x001AFC6C)
Patch:[ARQPostRequest] skipped (0x001B023C)
Patch:[__DSPHandler] applied (0x001B4918)
Patch:[__CARDReadStatus] applied (0x001B55B0)
Patch:[__CARDClearStatus] applied (0x001B56A0)
Patch:[__CARDStat A] applied (0x001B5B2C)
Patch:[__CARDUnlock A] applied (0x001B67AC)
Patch:[GXInit] stw r5,-0x7248(r13) (0x001BBB3E)
Patch:[PI_FIFO_WP] rlwinm r6,r6,0,3,1 (0x001BCDB4)
Patch:[PI_FIFO_WP] rlwinm r0,r0,0,3,1 (0x001BCE30)
Patch:[__GXSetVAT A] applied (0x001BDB10)
Patch:[GXInitTlutObj A] applied (0x001BFE0C)
Patch:[GXLoadTlut] skipped (0x001BFE54)
Patch:[__fwrite A] applied (0x001CCEC8)
Patch:[DSP v2] patched (0x002AF280)
Patch:Replaced NTSC with 480p (0x002B1C80)
Patch:Replaced PAL60 with 480p (0x002B1CBC)
Patch:Replaced PAL60 with 480p (0x002B1D34)
Patch:[PADInit] applied (0x001ADD18)
Patch:[C_MTXPerspective] applied (0x001A71C0)
Patch:[C_MTXLightPerspective] not found
Patch:[__OSInitAudioSystem] not found
Patch:[PADControlAllMotors] not found
Patch:[PADControlMotor] not found
Patch:[PADIsBarrel] not found
Patch:Using a EXI Timing of 1900
Jumping to 0x80003140

Dolphin OS $Revision: 49 $.
Kernel built : Dec 17 2001 18:46:45
Console Type : Retail 3
Memory 24 MB
Arena : 0x80410300 - 0x817fcbc0
app booted from bootrom
Unhandled Exception 6
------------------------- Context 0x80367488 -------------------------
r0   = 0x8010360c (   -2146421236)  r16  = 0x00000000 (             0)
r1   = 0x80410268 (   -2143223192)  r17  = 0x00000000 (             0)
r2   = 0x80405160 (   -2143268512)  r18  = 0x00000000 (             0)
r3   = 0x2da3d1ac (     765710764)  r19  = 0x00000000 (             0)
r4   = 0x00000000 (             0)  r20  = 0x00000000 (             0)
r5   = 0x0000b032 (         45106)  r21  = 0x00000000 (             0)
r6   = 0x00000000 (             0)  r22  = 0x00000002 (             2)
r7   = 0x00000000 (             0)  r23  = 0x802f83ac (   -2144369748)
r8   = 0xfffffff4 (           -12)  r24  = 0x00000000 (             0)
r9   = 0x0000000c (            12)  r25  = 0x802f83a8 (   -2144369752)
r10  = 0x00001000 (          4096)  r26  = 0x80410380 (   -2143222912)
r11  = 0x00000000 (             0)  r27  = 0x802f83a8 (   -2144369752)
r12  = 0x00000000 (             0)  r28  = 0x802f8928 (   -2144368344)
r13  = 0x80404160 (   -2143272608)  r29  = 0x802f83a8 (   -2144369752)
r14  = 0x00000000 (             0)  r30  = 0x70a20000 (    1889665024)
r15  = 0x00000000 (             0)  r31  = 0x804103bc (   -2143222852)
LR   = 0x80103610                   CR   = 0x40200088
SRR0 = 0x80103614                   SRR1 = 0x0008b032

GQRs----------
gqr0 = 0x00000000 	 gqr4 = 0x00060006
gqr1 = 0x00000000 	 gqr5 = 0x00070007
gqr2 = 0x00040004 	 gqr6 = 0x00000000
gqr3 = 0x00050005 	 gqr7 = 0x00000000

FPRs----------
fr0 	= 1 	 fr1 	= 0
fr2 	= 0 	 fr3 	= 0
fr4 	= 0 	 fr5 	= 0
fr6 	= 0 	 fr7 	= 0
fr8 	= 0 	 fr9 	= 0
fr10 	= 0 	 fr11 	= 0
fr12 	= 11 	 fr13 	= 0
fr14 	= 0 	 fr15 	= 0
fr16 	= 0 	 fr17 	= 0
fr18 	= 0 	 fr19 	= 0
fr20 	= 0 	 fr21 	= 0
fr22 	= 0 	 fr23 	= 0
fr24 	= 0 	 fr25 	= 0
fr26 	= 0 	 fr27 	= 0
fr28 	= 0 	 fr29 	= 0
fr30 	= 0 	 fr31 	= 0

PSFs----------
ps0 	= 0x0 	 ps1 	= 0x0
ps2 	= 0x0 	 ps3 	= 0x0
ps4 	= 0x0 	 ps5 	= 0x0
ps6 	= 0x0 	 ps7 	= 0x0
ps8 	= 0x0 	 ps9 	= 0x0
ps10 	= 0x0 	 ps11 	= 0x0
ps12 	= 0x1e4f59 	 ps13 	= 0x0
ps14 	= 0x0 	 ps15 	= 0x0
ps16 	= 0x0 	 ps17 	= 0x0
ps18 	= 0x0 	 ps19 	= 0x0
ps20 	= 0x0 	 ps21 	= 0x0
ps22 	= 0x0 	 ps23 	= 0x0
ps24 	= 0x0 	 ps25 	= 0x0
ps26 	= 0x0 	 ps27 	= 0x0
ps28 	= 0x0 	 ps29 	= 0x0
ps30 	= 0x0 	 ps31 	= 0x0

Address:      Back Chain    LR Save
0x80410268:   0x80410288    0x80103610
0x80410288:   0x804102b8    0x80108cb8
0x804102b8:   0x804102e8    0x8003a714
0x804102e8:   0xffffffff    0x80003250

DSISR = 0x00000000                   DAR  = 0x00000000
TB = 0x006d6dca5b241310

Program exception : Possible illegal instruction/operation at or around 0x80103614 (read from SRR0)

Last interrupt (19): SRR0 = 0x80037920  TB = 0x006d6dca2da3d08b
Got Shutdown button call
EXI: Saving memory card...Done!

**Comment by carnage702** [comment]
tell me all your nintendont settings.

**Comment by SevenWillis** [comment]
All settings are default except force widescreen and progressive.

**Comment by SevenWillis** [comment]
Seems like turning force widescreen off fixes this problem. Thanks anyway!

**Comment by carnage702** [comment]
Remenber manny games are imcompatible with force widescreens,forced videomodes,width and so on.
