### ISSUE TITLE
Virtual slot B memory card

### ISSUE THREAD

**Issue by Shadicbypass** [FIX94/Nintendont#200]
So when you enable memory card emulation you get one virtual memory card for each game if the setting is set to individual. I would like to see the ability to have a slot b memory card. It would be nice if this could be enabled on a per game basis for games like sonic adventure 2 battle. So just my 0.2 cents

**Comment by Zetchzie** [comment]
That would be nice but i dont see them doing it since there not concerned with non essential features.

**Comment by GB-CG** [comment]
That's a good idea actually. This would be also useful for F-Zero GX if you want to load the Slot B garage, and games with access to the B slot in the options settings too.

**Comment by Shadicbypass** [comment]
I would love to see this for the ability to clone chao in sonic adventure 2 battle and to have double the chao storage.

**Comment by Zetchzie** [comment]
Ah the clone glitch lol i remember that.

**Comment by GerbilSoft** [comment]
I had been looking into implementing support for Slot B in my MemCard-hax branch. Currently, it detects that there's a card present, but it claims it's damaged. I'm probably missing something required to get Slot B to work correctly.

**Comment by GerbilSoft** [comment]
(copy/paste from the GBAtemp thread)

Here's a new build with (experimental) support for virtual Slot B memory cards:
https://github.com/GerbilSoft/Nintendont/raw/v4.432-MChax1/loader/loader.dol

Thanks to [USER=330924]@GreyRogue[/USER] for getting Slot B working in the IPL and in games. Tested with both Sonic Adventure DX and Sonic Adventure 2: Battle.

**WARNING**: Make sure you BACK UP your memory card images before using this build. I didn't experience any data corruption when testing, but it's always possible.

Nintendont will not create a Slot B card by default. To use Slot B, you'll need to copy a valid memory card image to one of the following filenames:
* `/saves/GSNE_B.raw` (where GSNE is the 4-character game ID)
* `/saves/ninmemb.raw` (USA/PAL games when using Multi)
* `/saves/ninmemjb.raw` (JPN/KOR games when using Multi)

Note that the total size of both cards must not exceed 16 MB. If this happens, the Slot B card will not be loaded.

**Comment by GB-CG** [comment]
https://www.youtube.com/watch?v=uniUNs97H80
Works great so far with F-Zero GX. I haven't tested the AX version though.

**Comment by GerbilSoft** [comment]
Slot B is currently disabled on Triforce games. Apparently Triforce machines have a full DOL-001 system board (with different IPL), so I guess it should be possible to use Slot B; I don't know if any machines actually expose this to the user.

**Comment by uCallHimDrJ0NES** [comment]
Hi, newbie here with first post and noob questions.  I've been enjoying this build with Animal Crossing using two towns on two cards.  I noticed that the feature is not in the current Nintendont build just released in February 2017.  Is the slot B feature being considered for the main distribution?  Is testing needed in order to make this happen?  Thanks.

**Comment by nastys** [comment]
@GerbilSoft Will you consider updating your MemcardHax branch and make a pull request?
I would do it myself but I've been busy lately.

**Comment by GerbilSoft** [comment]
New test build, rebased on v5.460: https://github.com/GerbilSoft/Nintendont/raw/v5.460-MChax2/loader/loader.dol

Basically the same as MChax1, but rebased.

**Comment by thebeastgamer25** [comment]
@GerbilSoft do u know if thiswill be in the offical version?

**Comment by GerbilSoft** [comment]
This issue should be closed; it was merged with PR #474.
