### ISSUE TITLE
Objects un-render in Metroid Prime 2 multiplayer mode.

### ISSUE THREAD

**Issue by MissingNO123** [FIX94/Nintendont#205]
I've only tested this/seen it happen in multiplayer mode with two players, on both a real Wii and vWii. Singleplayer seems unaffected.
Anyone using the morph-ball will have some objects on their half of the screen un-render once they reach a certain distance from them. 
It also only seems to apply to parts of the level itself, not to players and other objects.
Changing the video settings does not seem to help.

(and yes, I do have a proper 1:1 iso)

**Comment by carnage702** [comment]
Doesnt that also happen on original game on the gamecube? seems preety possible due to GC limitations and 2 players they had to do render distances somewhat limited for multiplayer.

**Comment by MissingNO123** [comment]
Oh, no, I don't mean at a distance
Things start to disappear within about a metre or two away from the player, making the multiplayer mode completely unplayable.

**Comment by GB-CG** [comment]
@MissingNO123 What level(s) are you having problems with? I never had render issues with it AFAIK.

**Comment by MissingNO123** [comment]
I don't remember exactly what levels (except the sky level), though I think it affected most of them
I  can't exactly check right now as I cleared that ISO from my USB drive to make space, but once I get to my computer I'll do some tests and grab a few screenshots.

**Comment by FIX94** [comment]
Do you use the widescreen patch? That might affect object loading.

**Comment by MissingNO123** [comment]
Figured it out, it was one of the video patches that was causing it
Not sure which one though, I just disabled a bunch until it worked.
