### ISSUE TITLE
Mario Party 5 beep sounds

### ISSUE THREAD

**Issue by Mimimax** [FIX94/Nintendont#206]
There are "beep" sounds that play in super duel mode when selecting your character and other options. I'm not sure if this was also in Dios Mios.

**Comment by carnage702** [comment]
never had any beep sounds and i play all mario party titles alot on nintendont so try to awnser the following  questions.

nintendont version number.
all settings you have set on nintendont
is your iso a full 1:! iso that matches redump?

**Comment by Mimimax** [comment]
v.3.386
all settings on default
1:1 iso
no alterations made to the iso
I tested on Dolphin and didn't have the issue

**Comment by carnage702** [comment]
please dont say default list them, i cant count the times someone said default and they werent default.

are you using a usb device or SD card?

**Comment by Mimimax** [comment]
I once changed the settings but erased the config file afterwards
USB

**Comment by carnage702** [comment]
so you use real memory card and all that? well that beep does happen in games like ssbm character select screen and there is no fix is just for games that request too much data too fast and nintendont does a little beep keeping up with the data requests.

**Comment by Mimimax** [comment]
Yeah, real memory card and stuff. Thanks

**Comment by Drflash55** [comment]
So, if this is fixed, can the issue be closed?
Just making sure to keep the issues section clean of problems that have already been solved, or something.

**Comment by carnage702** [comment]
well this isnt fixed its just the way nintendont is, same way ssbm Character select screens will sometimes beep there isnt a fix unless code gets highly optimized or the wii gets a faster processor xD so yeah this can be closed.
