### ISSUE TITLE
Sonic Heroes (USA) Widescreen Patch failure (R3.387)

### ISSUE THREAD

**Issue by Drflash55** [FIX94/Nintendont#207]
Quoted from the reddit page.

>I'm trying to get the Widescreen Patch for Sonic Heroes NTSC, but it doesn't seem to have worked... It still shows at a 4:3 Ratio. I looked on the compatibility list, and it says it worked with version v3.307 of Nintendont.
I'm basing the ratio off of a 16:9 ratio hack for the PC version of Sonic Heroes, that looks like this. http://www.wsgf.org/f/u/contrib/dr/657/ingame_16x9_0.png
Did a recent version break Sonic Heroes, or is it just me?

I decided to bring this issue here, as I have not gotten a response within 24 hours...
Hope posting here would get me faster results.

**Comment by GerbilSoft** [comment]
Checking the PatchWidescreen.c file, there's no "specific" patch for Sonic Heroes, so it's using the generic patches.

Can you test v3.307? If it works there, and you have a local git client, I'd suggest doing a 'git bisect' to determine which version broke it.

git bisect reference: https://git-scm.com/docs/git-bisect

Note that since Nintendont has percompiled .dol files in the source tree, you don't have to recompile it. You just need to run the git bisect steps, then copy loader.dol to your SD card (as boot.dol) [or use wiiload, which is easier if you have it already set up].

**Comment by Drflash55** [comment]
I'm not quite certain about what you mean for having 'a local git client'.

Github Desktop will not work for me, as I don't have Windows 7, so that's out of the question.
If someone would be willing to test this out for @GerbilSoft, that would be great, so we can find out the version that broke the specific patch for Sonic Heroes.

By the way, I got the compatibility list from here... http://wiki.gbatemp.net/wiki/Nintendont_Compatibility_List

**Comment by GerbilSoft** [comment]
Plain old command line git is all you need. Github Desktop just provides a fancy GUI.

Alternatively, you can try downloading previous releases of loader.dol from the history page:
https://github.com/FIX94/Nintendont/commits/master/loader/loader.dol

I'll check out the widescreen issue later tonight.

**Comment by Drflash55** [comment]
This point in history, is V3.307. https://github.com/FIX94/Nintendont/blob/e740bc81bfd177da28115cdf3e690e481cfaac6e/loader/loader.dol 

This was the version that last reported that the Sonic Heroes Widescreen Patch worked. I'll make a backup of my Nintendont app folder and try it out and see if it really works for that version

**Comment by Drflash55** [comment]
@GerbilSoft I loaded up V3.307 and when I loaded up Sonic Heroes, the Widescreen Patch did not work still. It didn't even stretch the screen or anything, still showing at 4:3.

Does it matter if you load the game from a USB/SD Device, or was there never a widescreen patch for Sonic Heroes to begin with?

**Comment by GerbilSoft** [comment]
I don't think there ever was a specific patch for Sonic Heroes widescreen.

Source device shouldn't matter; patches are applied to USB and SD the same way.

I'll check it out myself tonight.

**Comment by Drflash55** [comment]
Okay then, let me know if you can make some kind of way for Sonic Heroes to have it's own widescreen patch.

**Comment by carnage702** [comment]
remenber that wiki was made by random people and seeing stretched they just putted widescreen works becuase it fills the entire screen, widescreen code does not work in most games.

**Comment by Drflash55** [comment]
@GerbilSoft Have you been able to take a look at the Widescreen Patch for Sonic Heroes, yet?

**Comment by carnage702** [comment]
make sure if your using a wiiu to set on wiiu widecreen and forced widescreen, becuase if your still seeing 4:3 and not stretched 4:3 you dont have the correct settings set up.

**Comment by Drflash55** [comment]
@carnage702 I'm using the Original White Wii... So I can't use Wii U Widescreen.

**Comment by carnage702** [comment]
if your seeing 4:3 screen  and not stretched 4:3 is becuase you have your wii settings in 4:3 instead of widescreen? ever since rev 1 nintendont displays stretched 4:3 for all games.

**Comment by Drflash55** [comment]
@carnage702 I do remember having my Wii settings set to Widescreen, so I'm not sure what else is happening.

When I get back home, I'll check out the Wii settings and see if I have the option enabled...

**Comment by Drflash55** [comment]
@carnage702 I checked my Wii settings, and the Widescreen Option is selected. 

When I turned it off, the display stretched across the screen, so when I turned it back on, and went to turn off the Widescreen Patch for Nintendont, the game appears as 4:3, as normal.

Turning it back on, doesn't change anything... So, there's something wrong with the Widescreen Patch, as it doesn't stretch the screen for Sonic Heroes, since there's no 'specific' path for it.

**Comment by carnage702** [comment]
the stretched 4:3 isnt a patch at all all games show that way do other games play stretched 4:3 normaly?

**Comment by Drflash55** [comment]
@carnage702 The only one I've tried other than Sonic Heroes is Kirby's Air Ride, and it that game doesn't have any kind of Widescreen, plus the screen does not stretch as well.

So, something is wrong here... as it doesn't appear to change ANYTHING at all, it's just normal. The Widescreen Patch doesn't even affect the way the game appears, it's just normal.

**Comment by carnage702** [comment]
Lets get this straight there isnt a normal widescreen patch nintendont displays the game in stretched screen by default  that isnt a patch since rev 1 if the console is on widescreen and not forcing 4:3 in settings so maybe its your tv settings? if you have everything off (including widescreen patches) an auto it should display te entire tv with some small black bars on the sides those tiny black bars from 1 to 3 cm are normal and that isnt what is called 4:3, 4:3 is huge black bars with 5 or 6 cm on each side having some tiny black bars is normal.

**Comment by Drflash55** [comment]
@carnage702 Huh, now that you mention it, black bars do appear on the sides of the screen, and they are tiny... Does that mean that the Widescreen Patch displays the game correctly if you have those black bars on the side?

I can't seem to understand how the function there seems to be useless, when it actually DOES something.

**Comment by Drflash55** [comment]
I now tested out the Kirby Air Ride code that was provided.
I put it into a .txt file, converted it to .gct, put it in the .iso folder, and loaded up the game without Widescreen Patch on.

The results seemed to be weird. The game didn't LOOK like it was 16:9 (Be aware, I'm looking for things to be unloaded off the side of the screen that you can't normally see in 4:3), but the side black bars were totally gone! Not only that, but the characters seemed to be thinner, as opposed to them being thicker.

Does it mean that the widescreen hack worked, or was it another cause?

**Comment by carnage702** [comment]
widescreen doesnt fill the entire screen just makes the game display in the correct aspect ratio so yeah your seeing the "full screen" nintendont shows all along.., 

The widescreen patch just makes the game display unstretched if it works so you dont see a slightly  deformed image(since all gc games with some exceptions were pure 4:3 games), to fill the entire screen you use the width option but this option its extremely unstable and can break manny games same as force widescreen some games are compatible others arent.

to see if widescreen patch actualy works just mark something of the game ingame to its position on the tv screen and then restart it with forced widescreen if the same object isnt on the same spot then widescreen is indeed working.


So i was talking to someone all this time that doesnt know what a 4:3 image is lol, set your wii on 4:3 and see the diference.

**Comment by carnage702** [comment]
Games have diferent sizes of black bars to the sides, it depends on the game, some games have tiny bars some have it slightly bigger.

**Comment by Drflash55** [comment]
>So i was talking to someone all this time that doesnt know what a 4:3 image is lol, set your wii on 4:3 and see the diference.

Funny you mentioned that, as I have already set my Wii to 4:3, as mentioned earlier... I saw that the screen looked stretched across the TV. It looks very off, so I fixed it.

What I was actually looking for, was the Widescreen Hack that makes the display hud stay where it is, but you can see more off the sides then when you were playing it normally.

To emphasize my point, something that looks similar to this... http://www.wsgf.org/f/u/contrib/dr/657/ingame_21x9.png

**Comment by Drflash55** [comment]
I went and looked up about what Aspect Ratios were for screens, and realized that 16:9 is 1600 x 900, HD+. Yet, the Wii has it set to 480i.

21:9 is 2100 x 900, and I thought my TV was displaying 400 x 300.

Guess what I'm REALLY asking here is a hack that makes it 1600 x 900 that widens the Field of View, rather than the resolution.

**Comment by carnage702** [comment]
that is what the widescreen patch does if it works, it shows more but its a gc game it doesnt show much more you get like afew % more on each side the bonus of widescreen is the correct aspect ratio.If you try like metroid prime you see an amazing effect of the widescreen shwoing more, becuase someone took his time to make a custom widescreen code that was implemented in nintendont if widescreen was set to on.

default widescreen shows more if it works but doesnt fix noone 3d stuff like huds and stuff, for that you need a custom  code made for it,

**Comment by Drflash55** [comment]
So, was @GerbilSoft planning on making a custom code for Sonic Heroes to make it display in True 16:9?

He hasn't responded since yesterday, when he said that he'd look into it 'yesterday night' (assuming that he doesn't live in the EST zone).

**Comment by carnage702** [comment]
no he was just cheking the custom codes included on nintendont and of course there isnt one for sonic heroes, that is all that he showed.

**Comment by Drflash55** [comment]
So, someone would have to take their time to implement a 16:9 custom code to make it work for Sonic Heroes...

Dang... Looks like it's more harder than I thought it would actually be.

**Comment by GerbilSoft** [comment]
Hi,

Unfortunately I haven't had time to actually check it, but from the sounds of it the generic widescreen patches aren't working. I haven't done much PowerPC assembler, so me writing a patch for this probably won't happen, but I'll take a look anyway.

**Comment by Drflash55** [comment]
@GerbilSoft I discussed this with @carnage702, who explained to me that the generic widescreen patch doesn't work for ALL games. You can try to make it work with Sonic Heroes, but you'd still have other games to worry about.

**Comment by Drflash55** [comment]
By the way...

>Unfortunately I haven't had time to actually check it, but from the sounds of it the generic widescreen patches aren't working.

@GerbilSoft If that's true, then should you mark this issue as a bug? I don't know anything about how the Widescreen Patch is applied, but if there IS something wrong with it, better label this as a bug so that @FIX94 is aware of this.

**Comment by carnage702** [comment]
technicaly this isnt a bug the general widescreen patch uses a very wide code so it affects most games that use standard code, it will not be tweaked for a random sonic game and loose hundreds of games it worked on before, what sonic heroes needs is a custom patch thats it, but good luck finding someone with a usb gecko and analysing game functions while it runs to make a widescreen patchs on sonic heroes.

Most of this widescreen patches came from a user on gc-forever forum  named  Ralf@gc-forever  he is the guy that does most of this amazing work and Fix94 made some himself like metroid prime games and such but yeah 90% are from  Ralf@gc-forever maybe contact him on gc-forever.com and ask if he has any interest in making a widescreen code for sonic heroes.

**Comment by Drflash55** [comment]
@carnage702 I tried registering but I can't get this friggen verification question right.

"What was the code-name for the GameCube, backwards.:"

I tried putting in nihpold, but THAT doesn't work.

**Comment by carnage702** [comment]
i had a rough time registin too in the past it was becuase i had an hotmail email adress or something if i remenber, i needed to creat a gmail account to registry correctly.

**Comment by Drflash55** [comment]
Over the past two days, I've been looking at widescreen (and 60 FPS) codes that were made specifically for games.

I saw a picture for TLOZ: WW, 16:9, and the game didn't look different, until I realized what it looks like in 4:3. The huds were all displayed properly, along with a wider field of view.

Star Fox: Assault's 60FPS code allowed it to play at 60FPS for Arwing stages, but any stage that involves land missions it plays at a slower framerate, but it doesn't skip frames, so it just plays in slow-mo.
Cutscenes also don't play at 60FPS, and instead just play at about 10 FPS instead.

So, for someone to make a Widescreen code for Sonic Heroes, it would make a wider field of view, and it would adjust the HUD display properly...

I am not able to contact Ralf, as gc-forever's registration system has a rigged verification code...

**Comment by carnage702** [comment]
Like i said even if you asked him he would probably not have done it anyway, people only loose countless hours when they are doing a code they want, for a game such as sonic heroes and considering he never made much sonic stuff since even for sonic adventure he said he didnt own the game so we wouldnt make the codes anyway, the chance of anyone actualy wanting to make the codes is very low and for a crappy game like sonic heroes is even lower.

well i will close this since this isnt really a bug its just the way the patch is coded for general porpose.

**Comment by Drflash55** [comment]
So, I'll just have to live with Sonic Heroes being in regular resolution... At least Sonic Adventure DX has a 16:9 Widescreen Code, but one is missing for Sonic Adventure 2...

Wonder if someone will put the time and effort to make one for that.

**Comment by carnage702** [comment]
if your loading the game trough nintendont being on sd,usb or disc doesnt matter all pathces are in effect, and if you fell unhappy that no one is making a widescreen code for a random sonic GC game you can start learning and try to make one yourself, remenber that no one has to do it, people do those becuase they just felt like it, be happy the game works on nintendont at all lol, also the game plays preety well in stretched 4:3, its not like you wont like the game becuase it isnt widescreen, when the exact original game never had that option to begin with on any platform.

**Comment by GerbilSoft** [comment]
FWIW this was fixed in v4.406 for USA, JPN, and the 10.8 prototype. I attempted to port the code to the PAL version but it didn't work.

**Comment by Pixeleg** [comment]
Apologies for reopening an old thread, but the fix added to v4.406 in 2016 no longer works in v6.489 from 2019. Is there any possibility of reviving it for us old-school Sonic fans?
