### ISSUE TITLE
Interactive Multi-Game Demo Disc Version 27 (USA)

### ISSUE THREAD

**Issue by Mimimax** [FIX94/Nintendont#208]
Crashes with glitched green screen when attempting to play any video and Softlocks on Mario Baseball demo before starting the match (didn't test other demos)

**Comment by carnage702** [comment]
try latest nintendont version where heavy support for demos was made.

**Comment by FIX94** [comment]
I did actually forget mario baseball going through the demo list so thats still something I have to do.

**Comment by Mimimax** [comment]
Tried the latest version. Still the same.

**Comment by FIX94** [comment]
as I said I did not add that but just now I pushed out a new file which finally deals with it correctly.
