### ISSUE TITLE
Twins enemies in Killer7

### ISSUE THREAD

**Issue by mehzemo** [FIX94/Nintendont#209]
The game has a strange bug using video width option (so width >40): enemies and some backgrounds are replicated and act like shadows.
Is this issue similar to SSBM which was fixed some time ago?

**Comment by carnage702** [comment]
width is very unstable and even completely crashes manny games its not recomended to use  mostly, ssbm issue was widescreen code wich was fixed by making a custom widescreen code, width isnt recomended like i said unless it works  for that game, not all games are compatible with width.

**Comment by Zetchzie** [comment]
You found the secret hard mode twin enemies. lol
