### ISSUE TITLE
Use tags

### ISSUE THREAD

**Issue by febLey** [FIX94/Nintendont#211]
I've noticed that you don't use tags. I think it's an awesome feature for a better overview of the versions. You can spot the changes between the versions a lot easier and also download a specific version.

To tag the last commit you can run

`git tag v0.4.2`

Also you can tag any commit, you just need the commit id

Example here: https://git-scm.com/book/en/v2/Git-Basics-Tagging#Tagging-Later

After that you need to push them, either each on it's own

`git push origin v0.4.2`

or all together

`git push origin --tags`

**Comment by NicoHood** [comment]
I also support this suggestion. You can upload all .dol files to the github release itself. That would make most sense and is common git(hub) usage. Please consider to reopen this/tag releases :)
