### ISSUE TITLE
A lot of games not showing up.

### ISSUE THREAD

**Issue by ZSlasher** [FIX94/Nintendont#212]
So, I downloaded the whole USA library, and got them prepped for nintendon't, and there are plenty of games missing. Also, I noticed the loading times are very long.

**Comment by GerbilSoft** [comment]
There's currently a hard-coded limit of 500 games:
https://github.com/FIX94/Nintendont/blob/e19e86faa90aa6ec7a00827391824535de7236d3/loader/include/menu.h#L26

Changing this value requires recompiling Nintendont. The best option might be to change it to a more flexible data structure, such as an std::vector or std::list.

Also, the order in which the games are read depends on how the directory is laid out on the FAT file system, which isn't normally visible in the OS (unless you use a low-level disk editor). Nintendont sorts what it reads from the HDD afterwards, so it won't show you the actual directory ordering.

**Comment by carnage702** [comment]
As stated this is not an issue its a limit of 500 games maybe someday the limit will increase but bigger game list the longer it will take for nintendont to load it.

**Comment by GerbilSoft** [comment]
I increased the limit to 1024 games in my "menuhax" branch. The branch isn't quite ready for merging yet, but if you have a devkitPPC+devkitARM toolchain set up, you can test it out.

https://github.com/GerbilSoft/Nintendont/tree/menuhax
