### ISSUE TITLE
Issue with multiplayer using a PS2 USB adapter

### ISSUE THREAD

**Issue by luk234** [FIX94/Nintendont#213]
Hello everyone.

I've been having problems setting up this specific adapter for multiplayer. 
[Adapter image](http://www.ebanggood.com/uploadfiles/facep/sony-playstation-usb-psx-ddr-converter-cable-6569n.jpg)
The adapter works great for single player, but when I try using both ports for multiplayer, I can't get both controllers to work at the same time.

In controller.ini, if I set MultiIn=1 and MultiInValue=01, only the first controller works. Changing MultinValue to 02 makes only the second controller work.
But if I set MultiIn=2, I actually get a response from both controllers, but they don't work the way they should.
This happens for all games, but is most notorious in SSBM. With both controllers plugged in, I navigate to the rumble menu, and I see this:

Player 1 controller is plugged in, for a short interval (~2-3 seconds), then P1 is unplugged and P2 is plugged in right after, P2 stays for a short interval (~2-3 seconds), after which the controller is unplugged, and the process repeats.
I can provide a video if necessary.

Are adapters like this not supported? or am I not configuring something properly?
Thanks in advance.

**Comment by carnage702** [comment]
if its an hid adapter it should work as long as you made the controller ini correctly.

**Comment by luk234** [comment]
Interestingly, my adapter is recognized correctly. Even if I don't use a controller.ini file, nintendont recognizes it as a ps2 controller. The problem is setting up multiplayer. Whenever I set multiin to 2, stuff goes crazy. I can't use both controllers at the same time without them alternating every 2 seconds.
This is the controller.ini file I'm using. Any help is appreciated.

[PS2 USB Controller]
VID=0810
PID=0001
Polltype=1
DPAD=1
DigitalLR=1
MultiIn=2
MultiInValue=01
Power=6,30
A=5,40
B=5,80
X=5,20
Y=5,10
Z=6,08
L=6,01
R=6,02
S=6,20
Left=5,06
Down=5,04
Right=5,02
Up=5,00
RightUp=5,01
DownRight=5,03
DownLeft=5,05
UpLeft=5,07
StickX=3,1A,100
StickY=4,1A,100
CStickX=2,1A,100
CStickY=1,1A,100
LAnalog=0
RAnalog=0
Rumble=1
RumbleType=0
RumbleDataLen=05
RumbleDataOn=01,00,00,7F,7F
RumbleDataOff=01,00,00,00,00
RumbleTransferLen=05
RumbleTransfers=1

**Comment by carnage702** [comment]
are both if your dualshock 2 controller official?
