### ISSUE TITLE
Gamcube controller not working

### ISSUE THREAD

**Issue by 9tendo** [FIX94/Nintendont#215]
I have an original wii with GC ports etc., but I can not for the life of me play games with my GC controller. Everything else on Nintendont works great. Am I missing something simple here?

P.S. Classic Controller Pro works great, I just prefer to play with original GC controllers.

**Comment by carnage702** [comment]
are you pluggin your gc controller on port1? isntead of port 4?

**Comment by 9tendo** [comment]
OK, now I feel really stupid. That is exactly what I was doing wrong. I have the GC laying flat on the rubber feet, and apparently the leftmost slot is port 4, not port 1. I'll go test in port 1 now.

**Comment by 9tendo** [comment]
Worked. Sorry for the annoyance, and thanks again.

**Comment by carnage702** [comment]
common issue, people are too spoyled nowadays  since wireless controller sync in on the first free port, back in the day you had to choose teh correct port :P
