### ISSUE TITLE
-

### ISSUE THREAD

**Issue by bagelnomnom** [FIX94/Nintendont#216]

**Comment by carnage702** [comment]
delete your controller ini and controller folder and let nintendont try and use the coded in config files, remenber to try both ports and making sure native is set to off and a gc controller isnt plugged on port1

**Comment by bagelnomnom** [comment]
I tried deleting the controller files/folder and it still did not work. I have my usb in the port that does not have the usb controller plugged in. I have native set to off and no gc controller in port1, but there is one in port2.

**Comment by carnage702** [comment]
make sure only the hid device is plugged in remove all gc controllers, then make sure there is no controller.ini file anywhere on usb or sd delete them all, make sure you are using nintendont 386 and try both ports of that ps2 adapter either ingame or in nintendont menu itself.

**Comment by bagelnomnom** [comment]
I tried all that and it still is not working.

**Comment by carnage702** [comment]
no idea then i dont have a ps2 adapter  but all my hid devices work perfectly from wiiu gc adaper to DS3 and DS4.
