### ISSUE TITLE
GameCube port

### ISSUE THREAD

**Issue by fwannmacher** [FIX94/Nintendont#217]
Is it possible to port Nintendont to GameCube? Some people, like me, use Wode or Wasp/WiiKey on their cubes and it would be awesome to have de ability to run audio streaming games with those.

It just needs to run the game "on the tray" because Wide and Wasp emulates de DVD drive.

**Comment by carnage702** [comment]
No... Nintendont works on wiimode that was the entire point of the app to run GC games with wii memory and speed tahts why we can do all that fun stuff like audiostreaming and mcemu and such gc memory would never fit any of that thats why nintendont needs wiimode to begin with to get audiostreaming.

**Comment by fwannmacher** [comment]
Ok. Thanks for the answer.
