### ISSUE TITLE
Gba link won't work on nintendont on my original wii

### ISSUE THREAD

**Issue by Michaelcaff** [FIX94/Nintendont#219]
When I try to use the gba link it will not recognise the gba and I have native controls on

**Comment by carnage702** [comment]
lets start with simple info.
Game your using?
nintendont version number(dont say latest please)
all your nintendont settings

**Comment by Michaelcaff** [comment]
The games I am using are 
1. Zelda four swords adventures
2. Pokemon XD
3. Pokemon Box ruby and sapphire 

Version number: 3.387

Settings
Cheats: off
Debugger: off
Debugger wait: off
Memcard emulation: off
Cheat path: off
Force widescreen: off
Force progressive: off
Auto boot: off
Unlock read speed: off
Osreport: off
Wii u widescreen: off
Drive read led: off
Log: off
Max pads: 4
Language: auto
Video: auto
Video width: auto
Screen position: 0
Patch pal50: off
Native controls: on

**Comment by carnage702** [comment]
is your cable 1st party? i just tryed collosseum and pokemon box with native on  my gc controller on port 1 and my gba link on port 2 and following the instructions everything works fine, are you turning the gba on when  prompted and not before? and following every intructions like saving at the pokecenter and such?

**Comment by carnage702** [comment]
remenber if your pal you must use the gba game region and the gc iso on the same region and language.

you cant connect pokemon fire red pal to gc pokemon xd ntsc

and if your pokemon game is in german then you need to have the pal iso also in german and so on.

**Comment by Michaelcaff** [comment]
My link cable is not official and I am following th steps.
Yesterday I got a European ISO of Pokemon xd and my Pokemon games are also European 
I used some other GameCube emulator called dios mios and the link cable works on it but it often crashes and is overall slow so I would like it to work on nintendont

**Comment by carnage702** [comment]
is both the pokemon xD and your gba pokemon game on the same language?both english or both german or whatever language you use?

Btw noone official stuff rarely works on homebrew maybe thats why? they send wierd signals and such that nintendont  might not know how to read, my cable is official and everything works fine, getting an official gba link cable used on ebay or amazon should be preety cheap.

**Comment by Michaelcaff** [comment]
They are both the same language 
Well I guess I will have to buy a official cable how much would you say they are
Thank you for your help

**Comment by GB-CG** [comment]
> remember if your pal you must use the gba game region and the gc iso on the same region and language. <
I don't see why it shouldn't work becuase my NTSC Pokémon Box ISO read my PAL UK Ruby/Sapphire. And I used a 3rd party GBA Link cable. I also have a official one too, which I'll test again.

**Comment by Michaelcaff** [comment]
Will it affect it if my battery has run dry

**Comment by Michaelcaff** [comment]
Wait I just tried mt Pokemon leafgreen with Pokemon box which battery has not run dry and it still didn't work

**Comment by Michaelcaff** [comment]
What settings do you have on @GB-CG

**Comment by GB-CG** [comment]
@Michaelcaff Here's mine:
![- screen shot 20 03 2016 17 17](https://cloud.githubusercontent.com/assets/11931125/13905723/c35e3950-eebf-11e5-9fb0-b5bba224bab8.png)

I just tried putting my Ruby on my GBA SP with the official GBA cable and it worked.

**Comment by Michaelcaff** [comment]
I have the same settings so what's the problem with mine

**Comment by Michaelcaff** [comment]
![image](https://cloud.githubusercontent.com/assets/17964946/13905873/b4acf172-eec3-11e5-92f6-941e84bde2f3.jpg)
![image](https://cloud.githubusercontent.com/assets/17964946/13905874/b4ce7ac2-eec3-11e5-9854-b0f75d4bb478.jpg)
My link cable and my settings

**Comment by Michaelcaff** [comment]
When I go into update I try and update the controllers.zip or titles.txt it will say restart nintendont to complete update and when I do it doesn't work.

**Comment by carnage702** [comment]
when nintendont says that you just press home button and exit back to homebrew menu and get back in.

maybe its your third party gba link cable that isnt compatible with nintendont, not all 3rd party ones use the same codding but yeah for me and GB-CB the gba link cable works maybe its becuase we use mcemu instead of an actual MC card? i see your not using memory card emulation? maybe try that?

**Comment by GB-CG** [comment]
Have you tried the cable on a gamecube of Wii with any of the discs mentioned above?

**Comment by carnage702** [comment]
http://www.ebay.com/itm/Nintendo-Official-GameCube-Game-Boy-Advance-Link-Cable-GBA-GC-DOL-011-JP-USED-/221765199977?hash=item33a23c6869:g:3DEAAOSwrklVSiys

you can get an official one cheap on ebay.

**Comment by Michaelcaff** [comment]
Does it matter what gba your using

**Comment by carnage702** [comment]
no idea i use the original gba but it shouldnt matter since sp its just the gba with a new design and backlight.It could be your cable might be damaged or something, if you an try with an original gc disc on the wii itself and see if its working.

**Comment by FIX94** [comment]
it works just fine with my original nintendo gba link cable and four swords adventures so your cable is probably broken.

**Comment by Michaelcaff** [comment]
It's not broken because I tried a GameCube game and it worked and it works with dios mios maybe nintendont just doesn't recognise it I'll just buy a original one

**Comment by carnage702** [comment]
its probably your 3rd party cable that uses a wierd code that nintendont cant support, it has been confirmed by 3 people oficial works and one 3rd party also worked so i advice getting an official one from amazon or ebay or a local website on your country.

**Comment by MattHillUK** [comment]
I appear to have the same issue:

Nintendont 3.387 (Wii)
Built Feb 14 2016 15:43:03
Firmware 58.24.32
Native Control: On
Memcard Emulation On or Off, it makes no difference.

I'm trying to link Pokemon Box to Pokemon Fire Red on the GBA.

I have tried this with the original disc in the Wii, loaded through the disc channel and it works. However booting the original disc though Nintendont doesn't work, same booting an ISO with Nintendont.

I can only guess it's because I also have a 3rd party cable going by what others have said. It's a "Gamester" branded one which I got with my GameCube in 2002. Ill try see if I can pickup an official Nintendo cable and report back.

**Comment by MattHillUK** [comment]
Just a quick update - I purchased an official GameCube to GBA link cable and everything now works perfectly.

**Comment by carnage702** [comment]
as expected, dkn why people go for third party stuff when they can get a used official aricle on ebay or amazon much cheaper.

**Comment by libertyernie** [comment]
I know this is an old post, but 've got two third-party cables (same brand, bought them at the same time); they both work on the GameCube but only one of them works on Nintendont. I'll either find another way to run Four Swords Adventures or (more likely) just buy an official cable online.

**Comment by DarkMasterChief** [comment]
And I also know the post is old but it may help someone.I have the exactly the same problem
"I'm trying to link Pokemon Box to Pokemon Fire Red on the GBA.

I have tried this with the original disc in the Wii, loaded through the disc channel and it works. However booting the original disc though Nintendont doesn't work, same booting an ISO with Nintendont.

I can only guess it's because I also have a 3rd party cable going by what others have said. It's a "Gamester" branded one which I got with my GameCube in 2002. Ill try see if I can pickup an official Nintendo cable and report back."
With the only difference that I am using the official GBA Link cable.

**Comment by carnage702** [comment]
> 
> 
> And I also know the post is old but it may help someone.I have the exactly the same problem
> "I'm trying to link Pokemon Box to Pokemon Fire Red on the GBA.
> 
> I have tried this with the original disc in the Wii, loaded through the disc channel and it works. However booting the original disc though Nintendont doesn't work, same booting an ISO with Nintendont.
> 
> I can only guess it's because I also have a 3rd party cable going by what others have said. It's a "Gamester" branded one which I got with my GameCube in 2002. Ill try see if I can pickup an official Nintendo cable and report back."
> With the only difference that I am using the official GBA Link cable.

make sure you have native control set to on and it should work as long as the gba link cable is 100% genuine and not a fake, also remenber pokemon games are language locked so you cant use lets say an spanish pokemon gba game and usa pokemon box.

just tested with both original disc and iso on nintendont 491 and it works preety well i got english pal fire red cartridge and original pal pokemon box gc disc/iso.

adventure mode does not work and if you select the go to list option on the box management it will crash but besides that you can deposit and withdraw pokemons just fine from fire red or any Pokemon game from gen 3 as long as the game are compatible with the pokemon box language.

remenber native must be on, it must be an offical pokemon link cable and everything must be official during the process.

i
