### ISSUE TITLE
Video bug when soft resetting in Pokémon XD

### ISSUE THREAD

**Issue by GreenSaint** [FIX94/Nintendont#220]
Video flickering problem after soft resetting in the game (pressing start b and x)  it happens after one reset then if you reset again it will be OK,  this is the pattern so it will be broken then fine and this pattern will repeat. 
I'm on version 3.376 vWii

**Comment by carnage702** [comment]
update to 386 and try again to see if th issue is still there.

**Comment by GreenSaint** [comment]
Just preformed update, testing now

**Comment by GreenSaint** [comment]
Still having the problem in the newest update

**Comment by carnage702** [comment]
list your nintendont settings all of them or maybe post a picture of them. also ntsc or pal version?

**Comment by GreenSaint** [comment]
Pal, my settings are 
memory card emulation
Force progressive 
WiiU widescreen 
Forced video to pal60

The forced video didn't make a difference from default settings and I made a quick video about it 
https://youtu.be/9IFvS_YpyO8

**Comment by carnage702** [comment]
try taking everything off except mcemu and  wiiu widescreen.

**Comment by GreenSaint** [comment]
Seems to be OK now, guess the problem is with progressive scan or just my setup thanks anyways

**Comment by carnage702** [comment]
yeah forced stuff is usualy the issue not all games like being forced with hacks due to how their gamecode works  glad it fixed your issue, it isnt recomended to force progressive on pal games btw most can crash  on boot and such.
