### ISSUE TITLE
Paper Mario TTYD freezes at 3.385

### ISSUE THREAD

**Issue by dc0013** [FIX94/Nintendont#222]
Hi.

I was playing Paper Mario "2" on Nintendont Fix 94 ver 3.385, PAL version on NTSC Wii (my native lang is spanish so I enjoy better the game like that), the game ran smoothly, I've played it for >16 hours, with not even minor problems. It was perfect. 

Yet, when I reached to this part the game freezes.

https://wiki.dolphin-emu.org/index.php?title=File:PM2ShopCar.JPG

Is just a reference pic to mark the room. The crash happens when is at night and you try to cross that room, exactly at the middle everything dies. 

I tried messing with the options (wide screen, etc). the only thing that "worked" for me was using PAL 60, I crossed the room and saved because is very hard to play with the screen flickering, then ran it again forcing NTSC, and seems like the problem repeats here 

https://i.ytimg.com/vi/8UPBDqZyANI/hqdefault.jpg

Only happens when the scenery changes at night; may be a background loading problem?, idk.

As a last resource I could donwload the NTSC version but, I want to be certain that the game is "clearable" that way ):

TY in advance

**Comment by carnage702** [comment]
you sure you werent forcing settings before?

im guessing you need to force the pal game to ntsc to view it on your tv or something?

Try the game with every option in auto,default and off except mcemu if you use it.

**Comment by dc0013** [comment]
I put everything in off (except memory card emulation), and it ran black and white with unstable screen.

Then I tried "Force NTSC" only (again, with mc emu), and apparently is gone!

Went back and fort by the rooms with the issue and was ok, I hope it never happens again.

Thanks.

**Comment by carnage702** [comment]
So yeah your tv doesnt support pal50 correctly, that is the default  videomode on all pal games some have 60hz option but its not manny, so in the future remenber that you need to force ntsc video or use ntsc copies becuase your tv doesnt support pal 50. Also remenber forced videomodes dont work for all pal games manny will just crash when forced videomodes onto them.
