### ISSUE TITLE
Gamecube controller stops working at random points 

### ISSUE THREAD

**Issue by GreenSaint** [FIX94/Nintendont#223]
Playing pokemon xd and the controller just stops working, I'm on the 3.386. 
This also happens during soft resetting, after 3 or 4 soft resets the controller will no longer work. It seams to happen at random.

**Comment by carnage702** [comment]
well the only issue with xD and colosseum is on boot the  sticks can become inverted when fully pressed that is a known issue but i never heard of a controller stopped working randomly on any game ever on nintendont lol.
what settings do you have?  write them all.

**Comment by GreenSaint** [comment]
Yeah it kinda sucks when you are just about to capture a shadow pokemon and it doesn't work, the settings I have are only memory card emulation and wiiu widescreen.  Also I'm using the mayflash 4 port adapter in wiiu mode to connect my gc controller but I had used it on my pc for months and I've never had an issue with it

**Comment by carnage702** [comment]
but you said 3 or 4 soft resets why are you soft reseting the game? are you trying to get good nature and ivs pokemon on nintendont? lol

you sure you dont have forced progressives or vidomodes or the likes?

did you try unplugging the mayflash adapter and pluggint it back in when this happens?

**Comment by GreenSaint** [comment]
It happens during normal gameplay too as well as soft resets, and the only reason I do is because I have this thing with genders and I don't know why, like for example I SR for female eevee at the beginning of the game, I tired unplugging the controller from the port and unplugging usbs but still doesnt work, trying to connect the wii remote will always connect as player 2 even if the gc adapter is unplugged. 
Pretty sure I have no forced video modes but my custom channel I use to boot the game from the wii menu might do, if it does I'll recompile the wad without any forced modes

**Comment by carnage702** [comment]
well you could try just using directly from nintendont menu i played both collosseum and xD fully on nintendont on wiiu with my wiiu gc adapter(official) and never once did it became unresponsive and i did play times of 3 and 4 hours at a time.

**Comment by GreenSaint** [comment]
It kept happening to me so I just went and played hit and run, I've been playing for awhile and I haven't had any issues with my controller, I'll boot from nintendont directly and I'll document any shit that happens here later, I'll make sure I'm running with only memory card emulation and wiiu widescreen only

**Comment by GreenSaint** [comment]
Well with about 3.hours of normal play with some soft resetting and the controller seams fine but my whole spastic screen problem is back. I can deal with the screen issue though and just seems to be a by product of soft resetting even if I think that makes no sense.
Ill fix my custom channel I use to load the game and I should be all good, thanks for the help
