### ISSUE TITLE
NTFS support? A fork already implements it

### ISSUE THREAD

**Issue by timofonic** [FIX94/Nintendont#225]
Hello.

Are there hopes to have NTFS support? This fork already implements it.

https://github.com/hito16/Nintendont/tree/usb-dvd-ntfs

It could be quite useful because:

- FAT32 is quite annoying to use on a USB HDD for general use: 4GB file limit.
- I would like to share the same HDD for different purposes: Wii stuff, videos, data, etc.

Thanks for this great project!

Kind regards.

**Comment by carnage702** [comment]
incase you didnt followed that it failled, nintendont cant run full librarys even the fat32 library had to be butchered to fit in nintendont thats why the usb compat isnt 100% and some wierd devices dont work, Fix94 already said several times that ntfs library is way to  big to fit in nintendont and would need a huge rewrite and butchrement wich would take an amazing amount of work so he wont had it, and like i said that fork failled to add it.

So as fix94 said several times he wont add ntfs support.
