### ISSUE TITLE
Gamcube controller not working 

### ISSUE THREAD

**Issue by sev42lora** [FIX94/Nintendont#226]
I have the usb adapter for Wii and commanding officer gc nintendo. When I try to play some game gc, it does not work, but when I go to choose options in nintendont, if it works. This put to use the 4 ports in the configuration. I tried a per-port and nothing. To do something with the controller.zip file. You have to use a specific ini? Where you have to configure it. Thank you

**Comment by carnage702** [comment]
if you have nintendont version 387 you dont need to do anything other than having Native set to Off and having the gc controller plugged in port 1 of the adapter.

**Comment by sev42lora** [comment]
thx
