### ISSUE TITLE
game is shifted right when memory card emulation is not enabled

### ISSUE THREAD

**Issue by nqztv** [FIX94/Nintendont#227]
strange issue on one of my crts (sony pvm). when i load a game without memory card emulation, the game pictures is shifted right and cuts off. however, when i turn memory card emulation *on*, the game is centered on the screen. any ideas on what may be causing this problem?

**Comment by FIX94** [comment]
your wii probably has some screen position changed, check it out in your settings. with memory card emulation on it just uses the settings hardcoded in nintendont.

**Comment by FIX94** [comment]
also check out 3.388 which will clear a sram setting related to this issue.
