### ISSUE TITLE
Please fix Red Screen

### ISSUE THREAD

**Issue by filevans** [FIX94/Nintendont#228]
this stops pal users playing ntsc jap/us games on their consoles, as they run completely in red, with no other colours on screen at all, and it is unplayable

the force pal60 option doesnt work, on nearly all games i tested it stops the game loading completely or switches the console off when loading

please could you fix this?
thank you for listening

**Comment by FIX94** [comment]
simple solution, dont use a RGB cable, they are incompatible with NTSC video modes and I cant change their hardware properties.

**Comment by Optiroc** [comment]
Actually most games I've tried work with the PAL60 patch active, but a couple won't work if MCEmu is also used.

Ikaruga (NTSC/U) is a very annoying exception that doesn't seem to work with the PAL60 option regardless of others patches (the main annoyance being that the european version doesn't have a 60Hz option). Using composite video is a workaround, but not an ideal one.

**Comment by filevans** [comment]
yes but you could fix the force pal60 so that games still work and dont just give a black screen, all the games i tested except one give a black screen

**Comment by filevans** [comment]
![img_20160417_212433](https://cloud.githubusercontent.com/assets/14978933/14589832/a3413016-04e3-11e6-96d0-4b9dc299147e.jpg)
![img_20160417_212311](https://cloud.githubusercontent.com/assets/14978933/14589834/a395919c-04e3-11e6-823a-0e25cb7016bd.jpg)
![img_20160417_211732](https://cloud.githubusercontent.com/assets/14978933/14589833/a394340a-04e3-11e6-913d-a3b2485220b2.jpg)

**Comment by FIX94** [comment]
s-video works just as well on a pal console as it does on a ntsc console, there is no console region differences as they are on a gamecube for example so if you play a game with ntsc video mode on a wii a s-video cable will work just fine as that is the main input I use myself actually.

**Comment by FIX94** [comment]
also homebrew in general has a lot of problems with rgb cables because you have to use a special flag which is pretty much undocumented and I dont have a rgb cable myself. Oh and how exactly am I supposed to just "fix" pal60? you know it already took me months to get the video patcher to the point it is now and I dont believe just one game worked with it, you probably do it wrong then. And on top of that, why not just use the pal games if you so want to use the rgb cable in the first place? you can just hold down "b" on start anyways to switch to pal60 in most cases.

**Comment by FIX94** [comment]
OH and I just see you are using a far, far outdated nintendont version, that one is almost a year old! so please update that as well.

**Comment by FIX94** [comment]
also I forgot to say you can also just use a cheap component cable and you would have all these issues just eliminated all at once while having the best overall picture quality and access to all my custom progressive patches.

**Comment by filevans** [comment]
multiple posts on the internet say that s-video does not work on pal wii, ive read it on more than one page

https://gbatemp.net/threads/s-video-cable-for-pal-wii.52682/

plus ive tested s-video on my console and i just get a black screen, no picture at all

also i downloaded that nintendont version from the main page just today and that is the version on download: Nintendon-T - Google Developers

so why dont *you* update it there?

**Comment by filevans** [comment]
component cable does not work on CRT tv, i use my wii for emulation too, running low native resolutions (240p), i hate LCD

**Comment by FIX94** [comment]
"so why dont you update it there?" because google code is dead and only a uneditable static archive for a over a year now? it even says so on the top of the page! on top of that I wasnt even the project owner back with google code anyways so I couldnt do anything even if I wanted that. also as long as you use a ntsc video mode it'll work just fine, ntsc triggers s-video functionality, pal triggers rgb functionality. you can force a wii to start with any video mode with any region changer or wiimod or anything among those lines.

**Comment by FIX94** [comment]
oh and how did you find this issue tracker but no download? there is a giant text file directly on the front page of this project with a quick installation guide with the link to the files needed.

**Comment by filevans** [comment]
when you search google, the main link that is first displayed is the google code one

**Comment by FIX94** [comment]
![rly](https://cloud.githubusercontent.com/assets/12349638/14590043/760aba5a-04f1-11e6-9469-f6506a00a8bd.png)

**Comment by GB-CG** [comment]
@filevans You download this: https://github.com/FIX94/Nintendont/blob/master/loader/loader.dol?raw=true

**Comment by filevans** [comment]
id already found it now. no point giving the link now. downloaded going to test now my games in pal60, will report back

**Comment by filevans** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14978933/14590067/9d5dea94-04e9-11e6-98fa-128dde4b3526.png)

**Comment by filevans** [comment]
tested the new version now and still games are not loading for me on force pal60, just either go to a black screen or don't load at all, are my settings correct?
![img_20160417_222732](https://cloud.githubusercontent.com/assets/14978933/14590145/e27c5bea-04eb-11e6-8a2d-f4e90d84c331.jpg)

**Comment by filevans** [comment]
also, my console is set to pal 60hz, yet nintendont loads straight into ntsc mode (presumably thats why its a red screen) shouldnt it load into the native video mode of the console?

**Comment by FIX94** [comment]
as said already, homebrew and rgb cables dont understand each other because of that one weird undocumented flag you also have to set in addition to pal60 because nintendo made some shit with it.

**Comment by filevans** [comment]
ok, going to try to change my console to ntsc region and try to use my s-video cable

**Comment by filevans** [comment]
can i patch the region of the isos to euro, will that work to run the games on rgb scart then?

**Comment by FIX94** [comment]
you cant just do that no.

**Comment by filevans** [comment]
thanks
so far ive tested:
F-Zero
Ikaruga
Star Wars Rogue Squadron 2
Luigi's Mansion
Super Mario Sunshine

the only game that works when i force pal60 is Super Mario Sunshine, the others dont load in at all, just go to a black screen only, so could you guess what might be the matter with them?

**Comment by carnage702** [comment]
You dont get that most games dont like being forced to videomodes that arent native to them? and no one is going to randomly go trough all ntsc game library and make single patches one by one becuase you refuse to use a video cable that supports ntsc signal or  use the pal versions of said games.
Each games needs specific patching and while there is a general patcher its obvious that manny games wont work with it, you would probably be luckyier forcing a pal game to pal 60 rather than a ntsc game.

But yeah dont count on anyone going randomly game by game making single patches to fix ntsc games into pal 60 lol.

just use the damn composite cable or get a decent tv and buy a component cable that way you can see manny ntsc gc games in glorious 480p you cant get better picture than that.

**Comment by filevans** [comment]
ok ve changed my console to ntsc and now im using my s-video cable and everything is working, so i am bordering on happy

is there a way to run ikaruga in pal60 if using the pal iso, does holding the b down work on that?
thank you for your help

**Comment by carnage702** [comment]
Nobody know some pal games have that option others dont, but if your wii is now in ntsc mode you can run the ntsc versions wich are always 60hz anyway.

**Comment by filevans** [comment]
i know but i am only using s-video cable as a last resort so i can actually play some gamecube games now, i would prefer to go back to pal60 and scart if i can run everything that way, i dont like pal50

**Comment by carnage702** [comment]
You dont have to like or dislike, if the game is hardcoded into pal50 then its pal50  no matter how much you want otherwise lol.
Unless you find a willing coder with manny free hours that wants to waste said hours looking into each of those games engines and doing customs patches to each game engine.

**Comment by filevans** [comment]
ao the force pal50 wont work on any of those?

is there a list of games that dont support pal60, just to foretell how upset i am likely to be in that situation?

**Comment by filevans** [comment]
![img_20160417_231513](https://cloud.githubusercontent.com/assets/14978933/14590437/5e769d68-04f2-11e6-871b-637c7f87bead.jpg)

everybody likes gamecube games in normal colour and in 60hz!! woo yeah (albeit with s-video)

**Comment by filevans** [comment]
does anyone know why my ntsc isos wont run in force pal60 (apart from mario sunshine)

**Comment by FIX94** [comment]
if I knew I would've told you but I dont even own a rgb cable so I have no clue, for me everything just goes through s-video and ntsc for my tv card.

**Comment by filevans** [comment]
i think its something to do with the program running in ntsc automatically on my wii, so it cant switch out of ntsc into pal60 maybe while in the program, i dont know why the program is loading into ntsc, when my console was in pal60 mode, is there anyway you could put an option to choose the video mode just in the menu, or is there anyway i can force the program to run in pal60

**Comment by filevans** [comment]
just as a test, i am in ntsc mode still on my console using s-video, and i tried to run luigi's mansion in force pal60, obviously the display is weird, but it gets to the memory card message and freezes, so even when my console is actually in ntsc the force pal60 doesnt work

**Comment by carnage702** [comment]
nintendont menu being made for pal would made no diference since the part that runs the games is a totaly diferent thing.

your not suposed to force ntsc games into pal 60 just try to put video on auto and it should work fine..

**Comment by filevans** [comment]
i already know that, was just doing a test to see why the or force pal60 wouldnt work when i was using scart

**Comment by carnage702** [comment]
Because your forcing a  general hack into a game engine that might be totaly diferent and messing it up, not all games use the standard functions to  their videomodes manny developers used totaly diferent functions on a crazy way to optimize stuff or due to being rushed ports and so on, the force stuff is a general hack it will never work on all games its to cover a decent ammount of games.
Any game that uses the functions for diferent stuff  will be broken obviously.

**Comment by filevans** [comment]
people here are saying that neogamma will fix the red screen issue
https://gbatemp.net/threads/ntsc-games-with-rgb-scart-red-screen.385799/

so wouldnt it be possible to implement the same fix as that in nintendont? could you look at the code they use in it?

**Comment by FIX94** [comment]
it seems like you are right about the loader always being in NTSC, I really wonder when that happend, I assume it was because of this newer interface somebody added to it.

**Comment by FIX94** [comment]
check out 3.388, might fix a lot of issues you had.

**Comment by filevans** [comment]
thanks for your help

also ive read on forums people are also running ntsc gamecube on a pal wii through rgb scart without any colour problems using gecko os

http://www.bordersdown.net/threads/96837-Playing-NTSC-GameCube-games-on-PAL-GameCube-or-PAL-Wii-through-RGB-CABLE

so seems that neogamma and gecko os is capable of running ntsc games on rgb ok, so could this code be looked at?

**Comment by filevans** [comment]
just downloaded 3.388 going to test it now, thanks

**Comment by filevans** [comment]
not sure if this swiss program is relavant too:
http://gc-forever.com/wiki/index.php?title=Swiss/Forced_Progressive_Compatibility_List

**Comment by FIX94** [comment]
looked at luigis mansion really quick and that game REALLY tries to force its NTSC video mode so that already would require a individual game patch, the others you mentioned probably would need custom ones too.

**Comment by FIX94** [comment]
the exact same issue occurs in rogue leader it seems, I assume this was a really old sdk version, basically these games do not know that pal60 even exists so they crash because of a unhandled case, they dont even have the timings or anything in them.

**Comment by filevans** [comment]
thanks, do you know if the same thing happens on an ntsc gamecube? in another forum someone mentions he rewired his wii scart cable to fix the red problem, but doesnt say how he did it

**Comment by FIX94** [comment]
well is it still red even with the new build or is that gone now? also an actual ntsc gamecube will always give out a ntsc signal just as a pal gamecube always gives out a pal signal. right now I'm looking more into this issue by the way so I might write a replacement patch for the problematic function.

**Comment by FIX94** [comment]
ok, so 3.389 should hopefully fix the rest of the games which crashed with a very small patch I wrote.

**Comment by filevans** [comment]
you are a genius
everything is working now with that fix, i am so happy ;-)

excellent work (pat on the back)

**Comment by Optiroc** [comment]
👍🌮🍷

**Comment by filevans** [comment]
for an _immediately _ closed and dismissed issue, this went very well!!!!!!

**Comment by filevans** [comment]
found an unusual anomoly with this fix

before the patch you wrote, F-Zero GX worked on force PAL60 as long as you don't use memory card emulation, and just use a normal GC memory card, but now it's doing it the other way round, it only works with memory card emulation on, and crashes for me using a normal memory card, just as it's loading in, before the title screen - the loaded game from memory card message comes up

not a big issue but thought i should report it as it's strange

thanks

**Comment by carnage702** [comment]
F zero Pal has native 60hz support so why are you forcing it anyway?

**Comment by filevans** [comment]
and why would i go through the headache and hassle of hunting down and finding out which pal games support 60hz? then getting disappointed when they dont? and then have to redownload them in ntsc

it is simpler to just use ntsc-u games and force them pal60

**Comment by carnage702** [comment]
https://en.wikipedia.org/wiki/List_of_GameCube_games_with_alternate_display_modes

you can easily see which games have pal60 here no  need to guess ...

**Comment by filevans** [comment]
@FIX94 hello, I just found 1 game that still doesn't work on force pal60: sonic adventure 2 battle, ive tried the US and Jap versions, and just goes to a black screen

works ok in ntsc - just i get the red screen as you know

thank you

**Comment by GerbilSoft** [comment]
@filevans SA2B supports PAL60 natively (on the European version).

**Comment by filevans** [comment]
thanks i'll download that, i just wanted to report the problem anyway

**Comment by FIX94** [comment]
just giving you an update, I fixed the SA2 crash with the latest file and I also looked at f-zero and I have absolutely no clue what the crash means, it happens in some compressed, post-game start loaded library we cant easly patch from what I can see.

**Comment by filevans** [comment]
thanks a lot for that, F-Zero was working on force pal60 before the patch was done to accomodate all the games like Luigi's Mansion,. but now it crashes only if you try to load or create a save game, otherwise it works ok still

also I found some other games that won't work, Crazy Taxi is one, I will test the new version with this game
thank you very much

**Comment by filevans** [comment]
just getting back to you to say that Crazy Taxi (USA) wont work in force PAL60 (black screen)

thank you for your help
