### ISSUE TITLE
Black screen on Wii U vWii for PAL game.

### ISSUE THREAD

**Issue by XShadowX01** [FIX94/Nintendont#231]
I can't get PAL games to work, all I get is a black screen and only sound on my NTSC Wii U.
These are games I was previously able to play on my old Wii no problem. I'd stick to my old Wii for this, but it finally gave out.
Is it a vWii issue only or something? At first I would get a distorted image moving around with green bars. Now it is just a black screen, even in the Gamepad.
Also I'm using it through HDMI, is that the problem? 
I know it might not be the same thing but PAL Wii game work fine, I also have the video option to Force NTSC on Nintendont so I don't know what else to move around in the settings other than the Force PAL 50/60 which don't really help.

**Comment by carnage702** [comment]
if you have the pal bios delete it, vwii is not compatible with pal bios. make sure your using the latest nintendont version 388. try video on auto aswhell.

**Comment by XShadowX01** [comment]
Oh wow Thanks! They work now!

**Comment by carnage702** [comment]
did you had 388 or it was  under 388, fix amde wiiu skip pal bios on 388 maybe instead of skipping it it black screens so  if you can tell me if you were on 388 or not.

**Comment by XShadowX01** [comment]
I updated, I was on the 386 i believe...

**Comment by carnage702** [comment]
well problem solved them glad i could help.
