### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by patri0t82** [FIX94/Nintendont#232]
I've got Rogue Squadron 2, (my first and only game attempt), I just downloaded Nintendont latest files from this site, and upon loading the game (standalone or through CFGUSB Loader), the Nintendont screen appears, shows version numbers, crashes back to Wii U menu.

Running off a FAT32 HDD, trying to load GCN game from :\\games\GSWE64\game.iso

Can't figure out why Nintendont always reboots the system.

**Comment by carnage702** [comment]
when nintendont restarts the console means its a bad iso what is your iso md5?

**Comment by patri0t82** [comment]
That's a great question - and at least a starting point; now I know it's the ISO. I'm not sure how to check the md5. 

It was a downloaded ISO, could re-downloading fix this issue perhaps, or would I have to find it from a different source?

(and thank you for responding)

**Comment by carnage702** [comment]
http://www.mediafire.com/download/5y3tfpoil433rij/MD5_SHA-1+Utility.exe

get this executable open your iso file with it  wait afew seconds and then post the md5 value you get.

Redownloading might work or not if the iso is broken on the host then redownloading does nothing, if itsbroken while downloading then it would fix it like i said might work or not but use this tool and post the md5 hash value.

**Comment by patri0t82** [comment]
Sure thing - I'll check it when I get home later. Thanks again

**Comment by patri0t82** [comment]
Hi! Sorry it took so long for me to write back. So I decided to redownload the file just in case. I've run the check and here are the results:
F4BD5A6E8A145B1FF847F6E04C177E0A

**Comment by patri0t82** [comment]
Whatever this one is: SHA-1: 00FA268681246A9F601897A424AA1EAE22326B62

**Comment by carnage702** [comment]
yeah that is not a good iso, get an iso from a diferent website make sure the iso is 1.35gb size and its md5 is  either

USA 0bf391bee90da09d6042016d23e7a9b1
Pal 15c49ff1dc836d19a1f275ac46ef4398
pal french 776a1046f8c47d7aad0cd732b53587ca
pal german fe32765ce6fcbb67ffd9e6f63d09cae0
pal spanish bb7eebbbb11fc8dc97f483a4dc3382cc

make sure your iso is untoched 1.35gb file and if the md5 doesnt match any of this ones then it isnt a good iso.

**Comment by patri0t82** [comment]
Wow that's great info. So all GCN isos are the same size? Or thats the max size for that proprietary disc?

**Comment by carnage702** [comment]
all full gc discs are 1.35gb size if you see anything smaller then they are compressed and might be bad files and such.

**Comment by patri0t82** [comment]
Okay, you've really helped. Thanks very much.

**Comment by patri0t82** [comment]
Hey again - is there any chance I'm doing something else wrong? I've tried three different isos, all with the same system reboot result.

The download source claims they work with Nintendont wii/vwii, etc. The files I'm trying appear to be 1.35gb. The md5s don't appear to be matching up, so I'm wondering why people would be seeding these files if they don't work?

Again, I trust you know what you're talking about, but there's no other possibility?

**Comment by carnage702** [comment]
if md5s dont match then why are you getting them? just get it from a decent website like hm well combine the word rom and hustler into on and google it xD

**Comment by carnage702** [comment]
all you need to do is having a decent working hdd or sd card get a gc game on iso format and put it on SD/USB:games/anyname/game.iso

**Comment by carnage702** [comment]
also try running nintendont directly trough the homebrew channel instead of with the cfg loader  try that too.

**Comment by patri0t82** [comment]
Will do. Got that site, I'll give all that a try. You've been a big  help

**Comment by carnage702** [comment]
well  i got rogue squadrons rogue leader 2 from there  now and i just confirmed and md5 matches perfectly.

**Comment by patri0t82** [comment]
Just going to give that one a try

**Comment by patri0t82** [comment]
So I tried that copy of RS2 and the md5 matches perfectly. Still reboots to Wii U menu. 
Also when I try Nintendont standalone from HB channel, reboots. I'm not sure if there's supposed to be a menu to pick a game from standalone Nintendont? 

I should be clear, Nintendont loads, the cube is on the screen, some message about Auto boot appears along with mounting information.

**Comment by carnage702** [comment]
that is becuase your probably using some outdated loader or something do this first delete your nin config on the sd card/usb root, then download this and rename it to boot.dol
https://github.com/FIX94/Nintendont/raw/4d5530df4c03608e28bc0ac5811e76f014122dad/loader/loader.dol

replace this dol on your nintendont folder on the apps be it on sd or usb, then select nintendont directly from homebrew channel and try again, im guessing cfg loader corrupted nintendont.

**Comment by patri0t82** [comment]
Hi again, I've tried what you suggested, I'll try to be clear about it all. First let me say, I use my FAT32 HDD for Wii games (in wbfs\#####\#####.wbfs format). I understand on Wii you use bottom port, WiiU top)

With that said, I have placed RS2 in the folder :\\games\Star Wars\game.iso
When I deleted the config file and replaced boot.dol, I ran Nintendont standalone. It got further this time. It let me select SD or USB. At this point, both options say no games were found in USB:\\games\ folder, or something along those lines.

I then tried placing the RS2 ISO in SD:\\games\game.iso and I got further. I selected SD from the two options and it let me see the settings menu.

After adjusting the screen size setting, I believe I hit A or B to see the games list, and the program kicked me out to the dump screen saying RELOAD.

I have no idea why it won't find the files on the USB drive. I mean I can get by just fitting one game on the SD card at a time if I have to, but still the fact that it crashed out is more important obviously.

I know this is dragging on, so if you're done trying I can understand.

**Comment by patri0t82** [comment]
Oh, I'll also mention, when I run it from CFGusb Loader, the hard drive at least flashes like it detects the ISOs - but then it reboots the WiiU

**Comment by carnage702** [comment]
does your hdd have multiple partitions?Btw using width values is not very recomended it breaks manny games, so if a single game is on the sd you can play it?

**Comment by patri0t82** [comment]
I'll leave the width alone next time. Trying a single game alone on SD didn't work either. That's when it gave me the dump screen. 

Is there any chance I need other cIOS installed?

**Comment by carnage702** [comment]
like i said nintendont only uses the default ios58 on wii/ vwii it needs no cios to work, the only thing messing nintendont up could be a cios installed over the original ios58 or some sort of homebrew channel that isnt ios58 or some wierd homebrew channel theme.

is your homebrew channel base ios58? did you ever installed a cios over ios58?

**Comment by patri0t82** [comment]
See that's a great question. I'm no expert. I followed a guide. Not sure how to check. I'm running the green homebrew channel for wide-screen support. Best way to check if base ios 58

**Comment by patri0t82** [comment]
?

**Comment by carnage702** [comment]
if its green homebrew channel then its definitely a mod, nintendont and homebrew channel mods conflict with one  another so that is your issue for sure, i have a normal homebrew channel that is also widescreen  on my wiiu dont have the link for mine but its basicaly a fowarder that amkes homebrew channel widescreen.

You can heck your homebrew channel base by pressing home menu  while seeing the apps on the top right corner it says the ios.

**Comment by carnage702** [comment]
My homebrew channel is 1.1.2 
ios58 v25.32 on vwii btw.

**Comment by patri0t82** [comment]
Okay the channel forward is green on the menu, the menu is version 1.1.2, running on IOS58 25.32

**Comment by patri0t82** [comment]
Guess that's the same after all. Crap

**Comment by carnage702** [comment]
not the same like i said you got a homebrew channel mod and nintendont is known to not work well with mods, dont you also have the original 4:3 homebrew channel installed on your vwii menu? tryed using that one? i have 2 homebrew channels on my home menu the original 4:3 and the widescreen one.

**Comment by patri0t82** [comment]
Forgot about the original channel. 
Trying.... 

Same dump screen. 
The two options were A select and so B settings. When I hit A, it dumps. I'm not sure exactly what it's selecting.. There's no game or ISO listed

**Comment by carnage702** [comment]
so no games appear on the list? then something is definitely off  could you take some screenshots of your entire hdd setup from the root to inside the game folder to inside a random game folder to seeing the iso?

**Comment by carnage702** [comment]
you dont have any other usb device connected to the console right?

**Comment by patri0t82** [comment]
For sure I'll get you a complete overview. Might be later today. Pretty sure we're in different timezones. I'll get it to you. Thanks again

**Comment by patri0t82** [comment]
Just checking if I can reply to this email without using forum

**Comment by carnage702** [comment]
btw it would be nice if you could see what is the last line that appears when games are loading before it restarts.

**Comment by patri0t82** [comment]
I've tried naming the files to help identify what you're looking at. Hopefully some of this makes sense.

![usbgcngames](https://cloud.githubusercontent.com/assets/18584468/14801487/eed14970-0b1f-11e6-9c69-b73afc89fb17.PNG)
![usbroot](https://cloud.githubusercontent.com/assets/18584468/14801489/eed6a352-0b1f-11e6-8df1-6b33714a3009.PNG)
![usbrs2game](https://cloud.githubusercontent.com/assets/18584468/14801501/ef0252a4-0b1f-11e6-95c5-373549d19067.PNG)
![usbwbfsgames](https://cloud.githubusercontent.com/assets/18584468/14801488/eed648c6-0b1f-11e6-9d56-204cb3f669e7.PNG)
![dumpscreen](https://cloud.githubusercontent.com/assets/18584468/14801491/eeda3abc-0b1f-11e6-8ce2-94e890f646f1.jpg)
![hbcfirmware](https://cloud.githubusercontent.com/assets/18584468/14801490/eed9bfba-0b1f-11e6-80c9-3757280dc431.jpg)
![loadwithusbon](https://cloud.githubusercontent.com/assets/18584468/14801493/eee35318-0b1f-11e6-8c83-43750ee0e734.jpg)
![loadwithusbonthencrashes](https://cloud.githubusercontent.com/assets/18584468/14801492/eee07788-0b1f-11e6-93a7-e08f65fa4786.jpg)
![nintendontfirmware](https://cloud.githubusercontent.com/assets/18584468/14801494/eee38338-0b1f-11e6-98ae-31689eadf30c.jpg)
![sdcard](https://cloud.githubusercontent.com/assets/18584468/14801495/eee949ee-0b1f-11e6-9fb6-829b57300632.PNG)
![sdcardroot](https://cloud.githubusercontent.com/assets/18584468/14801496/eeeddc3e-0b1f-11e6-808f-afd7becec48f.PNG)
![sdcardrs2game](https://cloud.githubusercontent.com/assets/18584468/14801498/eef30812-0b1f-11e6-901f-b76a1eb7fbda.PNG)
![sdcardselectednogameslisted](https://cloud.githubusercontent.com/assets/18584468/14801497/eef294a4-0b1f-11e6-8a8d-acab37b35e27.jpg)
![sdcardsettings](https://cloud.githubusercontent.com/assets/18584468/14801499/eef70912-0b1f-11e6-8a37-ed9e91a9b7e4.jpg)
![selectusborsd](https://cloud.githubusercontent.com/assets/18584468/14801500/eeff8506-0b1f-11e6-9424-e7339dde5091.jpg)

**Comment by carnage702** [comment]
tbh i have no idea whats wrong sd card doesnt show any games and usb crashes on dsi exception, do you have a wii? did you tryed on the wii to see if the same setup works?

**Comment by carnage702** [comment]
btw does your hdd use a ya cable or has its own power source?

**Comment by patri0t82** [comment]
I do have another Wii I could probably try with, and both HDDs have their own power supply.

**Comment by carnage702** [comment]
try teh same exact setup on your wii if it works then its some issue with your wiiu if it doesnt wort then maybe its your hdds or sd cards that arent good, maybe the fat32 is on some sort of hybrid partition setup instead of mbr or something?

**Comment by patri0t82** [comment]
Okay, I'll give that a whirl when I get a chance. I'm pretty sure the partitions are fine, and if I had to guess I'd say it's an issue with the WiiU somewhere. We'll see. Thanks again

**Comment by carnage702** [comment]
so did your wii worked?

**Comment by patri0t82** [comment]
Hey thanks for checking! I actually just tried it on the old wii and it worked great with RS2. Must have been an issue somewhere with vwiii. 
Thanks again

**Comment by carnage702** [comment]
probably some cios on place of ios58 im guessing.glad on the wii it worked for you.

**Comment by axle-h** [comment]
I'm having the exact same issue. Nintendont will warn about not seeing the games folder even though it's there then crash when selecting USB and reset the Wii u when started from USBLoader. My ios 58 is the same version. Never patched. Did you ever sort this out? Or just went to an older Wii?

**Comment by patri0t82** [comment]
Hey, sorry to say, the only way it worked was doing it on an older Wii, I'm afraid

**Comment by carnage702** [comment]
well before thinking its the same issue make sure you have an hdd/usb/or sd with the correct game path

the games folder must be on the root of the device and be called games and the iso needs to be called game.iso

example USB:/games/windwaker/game.iso

windwaker can be replaced with anyname you want.

Also make sure your device is fat32 formated correctly.

**Comment by axle-h** [comment]
I do know what I'm talking about, there is an issue here and I'd like to help fix it.
Paths are correct. Hard drive has a single FAT32 partition. Nintendont UI crashes right after selecting USB. It's a hard crash like a segfault, surely if the paths were incorrect I'd just see a no games. Nintendont wouldn't just give in and crash if there's nothing to play? Like the OP, Nintendont also crashes as soon as I press the home button to quit - presume not path or USB related.

Setup works with Wii games in USBLoaderGX also finds the GC games and attempts to launch them. All default settings in USBLoaderGX. 

Is there any verbose logging I can enable or compile with? Never looked at developing for libogc. Presume I can just attach a debugger?

**Comment by carnage702** [comment]
Try this just to make sure if you have an sd try redownloading nintendont dol to exclude the issue that its corrupt, delete all ninconfig and controller inis on sd root, unplug your usb device and put  a single game on the sd card and try to do everything with SD, since sd code is diferent from usb, if it still crashes with pure sd setup then its an ios issue or something wierd you installed.

**Comment by axle-h** [comment]
So I managed to sort it. Problem was that I didn't have a partition table on the disc. The whole disc was a fat32 filesystem. Think it may have been a result of having it wbfs formatted in the past. Be interesting if @patri0t82 could confirm his disc also doesn't have a partition table? Speculation time: USBLoaderGX uses libogc for USB which handles this, Nintendont uses IOS 58 for USB, the old Wii version of IOS 58 handles the lack of partition table but the vWii version doesn't.

**Comment by GerbilSoft** [comment]
Partition table functionality is entirely handled by Nintendont, not IOS. Not sure why it'd act up on vWii but not Wii.

I'll test an unpartitioned disk tonight to see if I can reproduce this.

**Comment by GerbilSoft** [comment]
Tested an unpartitioned disk on Wii, and it worked without any issues.

My Wii U is currently unhacked, so I can't test that at the moment.

**Comment by axle-h** [comment]
Not sure if it matters but I was using a FAT32 filesystem.
