### ISSUE TITLE
won't load isos from usb after adding new isos

### ISSUE THREAD

**Issue by filevans** [FIX94/Nintendont#234]
hello
sometimes when adding new isos to my usb stick, nintendont wont load any games at all, the games come up ok in the list but just it sticks on loading game and doesn't go to the launching screen where it shows the iso information, you then have to delete the nintendont config file in the root for the games to work again

i dont know what causes it, but as it is a bit weird i thought i should report it

**Comment by carnage702** [comment]
iso information? are you using nintendont directly? since there is no iso information just the name of the iso itself, also are you using a ps3/ps4 controller?

**Comment by filevans** [comment]
after you press A to load a game, it says game loading, then lots of "info" comes up, chunks etc. then the game launches, do you need me to do a photo of the screen? i thought you would know what i meant from the description

no, im using a gamecube controller only

**Comment by carnage702** [comment]
that isnt the iso info that is basicaly nintendont launch procedures checking stuff and such lol.

something is off with your hdd im guessing, its not normal for the ninconfig to not be updated on every bootup once new games are added that never happened to me lol, i add games and they always appear fine and launch fine, maybe your hdd has some rewrite protection enabled or soemthing? do you have other usb devices to try and replicate the issue?

**Comment by filevans** [comment]
no, because as i said if i delete the config then they work, so how can that have anything to do with rewrite?

**Comment by carnage702** [comment]
well when you delete the ninconfig nintendont makes a new ninconfig  so it writes a new file only,instead of deleting the older one and making a new one when a file already exists.

**Comment by carnage702** [comment]
btw usb sticks arent recomended in howbrew in general im guessing depending on the actions your usb stick isnt fast enough to keep with the precedure checks if it has any aditional stuff it needs to do tahts why it crashes im sure if you had an hdd or a fast sd card this would enevr happen btw.
