### ISSUE TITLE
meta.xml doesn't update when a new boot.dol is made

### ISSUE THREAD

**Issue by Ebola16** [FIX94/Nintendont#235]
If I'm understanding the README correctly, https://github.com/FIX94/Nintendont/blob/master/loader/loader.dol?raw=true should have the latest build of Nintendont. This currently appears to be 3.389.

https://github.com/FIX94/Nintendont/blob/master/nintendont/meta.xml?raw=true should have the latest meta.xml but it says that it's for version 3.341. Updating the meta.xml version would be a quick and easy way for people to see if a new version of Nintendon't is available (unless there's a better system for update notifications that I'm unaware of).

I'm also new to github, is starring this repository the best way to receive notifications when the version number increases (but not notifications for other issues)?

**Comment by FIX94** [comment]
nintendont on its own writes a new meta.xml on every start anyways with the version number so nobody bothers updating the file on here by hand.

**Comment by Ebola16** [comment]
Alright, I just wish there was an automated way to get update notifications on new Nintendont versions but manually checking the latest .dol isn't the hardest thing to do. Thanks!

**Comment by FIX94** [comment]
you also could just always check this file.
https://github.com/FIX94/Nintendont/blob/master/common/include/NintendontVersion.h
