### ISSUE TITLE
nintendont isn't reading the controller.ini file

### ISSUE THREAD

**Issue by ElectroBlueGuy** [FIX94/Nintendont#237]
i'm using an Xtreme gamepad, it is working very well, but i wanted to change the controls of it, only buttons, i used HID test to find the codes and then i create the controller.ini file, using 0079_0006.ini file and then modified it, but when i load a game in nintendont, the controls are like usual, they don't change, this is the controller.ini file i'm using:
[Generic USB Gamepad]
VID=0079
PID=0006
Polltype=1
DPAD=1
DigitalLR=1
A=5,80
B=5,40
X=5,20
Y=5,10
Z=6,08
L=6,01
R=6,02
S=6,20
Power=6,10
Left=5,06
Down=5,04
Right=5,02
Up=5,00
RightUp=5,01
DownRight=5,03
DownLeft=5,05
UpLeft=5,07
StickX=0
StickY=1
CStickX=3
CStickY=4
RAnalog=0
LAnalog=0
Rumble=1
RumbleType=1
RumbleDataLen=0E
RumbleDataOn=51,00,00,00,FF,00,00,FA,FE,00,00,00,00,00
RumbleDataOff=51,00,00,00,00,00,00,FA,FE,00,00,00,00,00
RumbleTransferLen=07
RumbleTransfers=2

**Comment by carnage702** [comment]
custom controller ini files to be readed need to be placed on the root of the device that has the games SD/USB named controller.ini also make sure its isnt controller.ini.ini or something like that.
