### ISSUE TITLE
Shadow the Hedgehog & Sonic Heroes widescreen

### ISSUE THREAD

**Issue by Pixelise** [FIX94/Nintendont#238]
I have an issue. Games that are writed above (Shadow the Hedgehog and Sonic Heroes) are working perfect, progressive scan, PAL60 etc. But widescreen isn't working. The both of these games are loaded from usb HDD and their region is EUR. Can someone help me? (Yes I have the latest Nintendon't version)

**Comment by carnage702** [comment]
the widescreen hack does not have 100% widescreen sucess, some games need custom widescreen hacks if you see nintendont widescrren file you can see like 12 games have custom hacks,  if  the game doesnt show widescreen when forced widescreen is applied then you need a custom hack,get some hacker to do them or else it will likely never work.

**Comment by teconmoon** [comment]
Shadow the Hedgehog and Sonic Heroes both have Widescreen AR codes that work very well, at least for the NTSC versions.

I could only find PAL for Shadow the Hedgehog, not Sonic Heroes. Try this: 04585194 3FB00000

I took this code from the Dolphin compatibility page for the game, should work on real hardware just fine. If you go the NTSC route I'd recommend searching the dolphin compatibility wiki for both games, as they both have good NTSC widescreen codes.

**Comment by GerbilSoft** [comment]
I implemented a widescreen hack based on the Dolphin Wiki AR code. Currently supports US, JP, and the 10.8 prototype. (I don't have the PAL version, so I can't test it.)

I tried adding the code for Shadow (NTSC-U), but it didn't seem to do anything.
