### ISSUE TITLE
Pokken Controller support?

### ISSUE THREAD

**Issue by gingerbeardman** [FIX94/Nintendont#240]
It would be great to be able too use this controller to play games that do not require analog.

http://store.nintendo.co.uk/wii-u-accessories/pokken-tournament-pro-pad-controller/11229357.html

I have the controller. Let me know how I can give you any other required details.

# Notes
It does not show up in HID Test on Wii U (vWii).

## Summary
VID=0F0D (Hori Co.,Ltd.)
PID=0092 (Pokken Controller)

13 buttons (3 unused?)
1 hat switch (d-pad)
1 X-axis (unused?)
1 Y-axis (unused?)
1 Z-axis (unused?)
1 Z-rotation (unused?)

page:0xFF00
usage:0x20

### Buttons 
button0 = Y = 0x0009:0x0001
button1 = B = 0x0009:0x0002
button2 = A = 0x0009:0x0003
button3 = X = 0x0009:0x0004
button4 = L = 0x0009:0x0005
button5 = R = 0x0009:0x0006
button6 = ZL = 0x0009:0x0007
button7 = ZR = 0x0009:0x0008
button8 = SELECT = 0x0009:0x0009
button9 = START = 0x0009:0x000A

### Hat Switch ( = 0x0001:0x0039)
neutral = 15
left = 6
right = 2
up = 0
down = 4

**Comment by carnage702** [comment]
if its not an hid controller than it cant be supported, it would need an enterely  new driver for a single controller, the reason xbox controllers dont work is becuase they also arent hid and there is no interest in writing a all new controller driver for one controller.

**Comment by gingerbeardman** [comment]
What's making you say it's not HID? 

It shows up as a HID controller on my Mac and PC.

**Comment by carnage702** [comment]
you said it doesnt show up on hid test and hid test is what nintendont uses for hid controller reads basicaly.

**Comment by gingerbeardman** [comment]
Still not recognised in that scenario loading vWii & HID Test after the game.

How do I go about looking into whether it needs to be activated like the GC adapter?

**Comment by carnage702** [comment]
well if it needed a bit t activate then it would have worked like that since the controller was active so no idea you sure its a normal hid controller? and not a controller that maybe installs a drive to be hid transformed on the pc or something?

**Comment by gingerbeardman** [comment]
It works on my Mac and an HID controller and no drivers are installed it
necessary. But I don't know any more about why it's different on Wii U
