### ISSUE TITLE
nintendont on WiiU vWii Mounting USB/SD device... Error! 13 Shutting down

### ISSUE THREAD

**Issue by littlebigboss12** [FIX94/Nintendont#242]
Hi there! 
Much respect to you guys for your awesome work, but I am sadly unable to benefit from it atm due to this error I keep getting when trying to load ANY Gamecube ISO, whereas Wii ISOs are completely fine (telling me the drive is reading correctly and being recognized). As you can see from the screenshots, that is the drive model I am using, as well as the version of Cfg USB Loader and the Nintendont loader. Other info I can provide is that the drive was FAT32 formatted with 32K cluster size using Wii Backup Manager (latest ver.) and all files are named appropriately 'game.iso' and 'disc2.iso' for those applicable. You'll even notice the Cfg USB Loader even recognized all the Gamecube ISOs being there as it downloaded all the covers for them (you can see them in the background of the screen with the ver. No)

Any help on this is greatly appreciated, as I'd love to be able to play some of my old Gamecube games again :]
![img_20160512_075635](https://cloud.githubusercontent.com/assets/19326043/15214158/7be4b1a2-1819-11e6-9194-6f86fbcafcd7.jpg)
![img_20160512_080000](https://cloud.githubusercontent.com/assets/19326043/15214157/7be30a5a-1819-11e6-8742-ca319fc8904b.jpg)
![img_20160512_080146](https://cloud.githubusercontent.com/assets/19326043/15214159/7be5526a-1819-11e6-93bb-961f08acd9e6.jpg)

**Comment by FIX94** [comment]
the kernel load fail happens right here:
https://github.com/FIX94/Nintendont/blob/master/kernel/main.c#L141
with this error:
https://github.com/FIX94/Nintendont/blob/master/kernel/ff.h#L198
so you probably should try different formatting tools with that HDD because whatever wii backup manager did is not compatible with the kernel fat library. I guess if no formatting tools work I hope @GerbilSoft will see this and maybe have some ideas for you.

**Comment by GerbilSoft** [comment]
@littlebigboss12 Can you post a screenshot of the partition layout of the drive, and possibly a dump of the MBR? (http://www.ghacks.net/2010/09/01/how-to-backup-and-restore-the-mbr-in-windows/)

**Comment by littlebigboss12** [comment]
Thanks for the quick replies and suggestions you guys, but as you will likely tell me at this point from the screenshots, it's because the drive is set with logical partitions including an unallocated 7.84MB for some reason at the beginning of the drive (as opposed to primary which I did read about many times before). 

My mistake was obviously in trusting Wii Backup Manager to format correctly, so I will try something else like Fat32 Formatter GUI which I have but didn't use this time. If you have a better utility for Fat32 formatting the drive, I'm all ears :]

![mbr info](https://cloud.githubusercontent.com/assets/19326043/15228046/0f5158a8-1858-11e6-880b-44a053d585d1.jpg)
![partition info](https://cloud.githubusercontent.com/assets/19326043/15228045/0f4e7b1a-1858-11e6-8801-0b8e982c38d0.jpg)

**Comment by GerbilSoft** [comment]
The 7.84 MB unallocated space isn't necessarily a problem, but the logical partitions is. Neither libcustomfat (loader) nor FatFS (kernel) support logical partitions.

EaseUS Partition Master supports converting logical to primary, so try using that function: http://www.partition-tool.com/easeus-partition-manager/help/convert-logical-to-primary.htm

**Comment by littlebigboss12** [comment]
No kidding!? You totally saved me over 2-3hrs of transferring and transferring back of all the 270GB of ISOs I just started moving before reformatting the drive. You're a life saver, I'll repost back as soon as I do the conversion and test afterwards for confirmation all is well :D

**Comment by littlebigboss12** [comment]
Sorry for my very late reply about how things went, but because I'm OCD about the 7.84 MB being unallocated and a waste of (very little and insignificant) space, I just HAD to reassign it to the primary partition afterwards and of course wait the 3hrs for all 270GB of data to be shuffled over to the beginning of the drive. Yes, I'm an idiot XP

On the plus side, you totally helped me out in no time flat and the games load correctly now as expected. Now if only Snes9x GX and Genesis Plus GX supported the official Gamecube adapter as you've made it work flawlessly with Nintendont... :]

If there's anything I could do or contribute to help, please let me know. Thanks so much again!
