### ISSUE TITLE
Background image makes menus hard to read.

### ISSUE THREAD

**Issue by CoolOppo** [FIX94/Nintendont#245]
It's nice to have the background image display when everything is still loading, but after that, it should go away, or at least have a really low contrast. The way things currently are makes it very hard to read menu text that is on top of the background image.

**Comment by carnage702** [comment]
never saw anyone complaining about this lol maybe its your bad tv or eyesight lol it never bothered anyone else on well over 1000 pages of the official thread lol.

**Comment by CoolOppo** [comment]
Me and a friend both had a conversation about this just the other day! I would totally just make a pull request to make an option for this, but I don't know how to safely modify the codebase.

**Comment by digicannon** [comment]
@carnage702 you've gotta be joking! It's not a problem when you only have one or two games, but when you have an actual list of games you need to look through it's ridiculous.

**Comment by carnage702** [comment]
No im not kidding i always had well over 40 games on my hdd and i never had any problem, heck most people on the nintendont thread have well over 50 games and one guy hitted the limite wich was over 500 games and now nintendont supports 1024 isos at the same time and i never had a single problem seeing anything and this was never mentioned by a single person on the nintendont thread and nintendont has been in developement well over 2 years lol so no im not kidding.

maybe you guys use some bad tv cables or something? like i said on 2 years and after 1650 pages on the official nintendont thread not one person complained about the background picture  lol.

**Comment by CoolOppo** [comment]
@carnage702 No, the background is seriously bad. There isn't enough contrast between it and the text.

**Comment by carnage702** [comment]
if you want diferent pictures you can use nintendont mod by abz where he has alot of pictures to choose from and whatnot just ask on his thread

https://gbatemp.net/threads/nintendont-themes-and-custom-mods.374469/
