### ISSUE TITLE
Bluetooth Wii U Pro Controller randomly rotates right face buttons

### ISSUE THREAD

**Issue by westonlast** [FIX94/Nintendont#247]
A, B, Y, and X rotate in that order while playing Twilight Princess.  A becomes B; B becomes X, etc.  Will someone please at least point me to the file that drives the input for this controller so I can poke around?

Everything else seems to work great, including rumble.  This is awesome.  Thank you.

**Comment by carnage702** [comment]
if you press  the - button the a,b,x,y buttons rotate its a feature not a bug lol also happens on CC.
