### ISSUE TITLE
USB Controller getting delayed for 5 second 

### ISSUE THREAD

**Issue by pftmclub** [FIX94/Nintendont#248]
When i play GC games with USB Controller  ( Dualshock 2 & Dualshock3 ) , it's getting delay after first 10 minutes gameplay , i can't press anything for 5 second, after 5 second it's back to normal but after 10 minutes it's gettig delay again.

Does anyone know this problem?

-------------------
( Sorry for my bad english )

**Comment by carnage702** [comment]
are you suing latest nintendont version? (403 now)
take a picture of your settings on the nintendont menu if you can.
