### ISSUE TITLE
Stick and CStick Y-Axis Inverted Using Mayflash 4-Port WiiU/PC Adapter

### ISSUE THREAD

**Issue by socheat0** [FIX94/Nintendont#251]
Using the following controller.ini from https://github.com/protomouse/nintendont/tree/master/controllerconfigs:

[Nintendo Wii U GameCube Controller Adapter]
VID=057E
PID=0337
Polltype=1
DPAD=1
MultiIn=3
MultiInValue=09
Power=3,0F
A=2,01
B=2,02
X=2,04
Y=2,08
Z=3,02
L=3,08
R=3,04
S=3,01
Left=2,10
Down=2,40
Right=2,20
Up=2,80
RightUp=2,A0
DownRight=2,60
DownLeft=2,50
UpLeft=2,90
StickX=4,0,100
StickY=5,0,100
CStickX=6,0,100
CStickY=7,0,100
LAnalog=8
RAnalog=9

Also, only the first port works. Is this normal?

**Comment by carnage702** [comment]
well that is probably an outdated ini? doesnt mayflash use the same exact ini as the real gc adapter? if so just delete your ini and let nintendont internal configs set your hid controller.

most gc games only first port works unless you are on the multiplayer portion of said game, if only one port works even on multiplayer make sure maxpads is set to 4 but yeah delete your ini file and let nintendont use its internal configds and report back.

**Comment by socheat0** [comment]
Accidentally using a Nintendont version from over a year ago. Newest version works flawlessly with no need to mess around with controller.ini. I'm beating myself over the head for being tripped up by something so small as not having the updated version. Cheers!

**Comment by DirtyDan123** [comment]
I am actually having trouble with my inverted y stick too.  Every button works fine except that y stick, is there any way to modify the ini so I can fix the problem?

**Comment by socheat0** [comment]
Check to see if you're using an old Nintendont version. For me, using the newest version had no issues.

**Comment by DirtyDan123** [comment]
Yep, I was using an old version and once I actually went to their website and downloaded the updated one, everything started working.  Thanks!

**Comment by FIX94** [comment]
what exactly do you mean with "to their website", besides my github and a post on gbatemp theres not exactly much more.

**Comment by DirtyDan123** [comment]
Sorry for being vague, I meant the gpatemp post which let me download the
latest version
