### ISSUE TITLE
Nintendont fails to load. Failed to load KERNEL from NAND

### ISSUE THREAD

**Issue by Protatoxxxeater** [FIX94/Nintendont#253]
My wii is on the latest version.
after updating nintendont cheats no longer work
i deleted the file used for cheats and the kernel.bin
would kernel.bin be the issue?
Is this in the wrong place

**Comment by GerbilSoft** [comment]
Make sure you have meta.xml setup correctly in the Nintendont directory. Otherwise, Nintendont can't get permissions to patch IOS.

**Comment by GerbilSoft** [comment]
Can you test the latest build of Nintendont? (v4.409) There's some additional diagnostics in the LoadKernel() function, so it should show more detailed information as to why it's failing to load.
