### ISSUE TITLE
2 disc games show identical names

### ISSUE THREAD

**Issue by filevans** [FIX94/Nintendont#254]
hello
would it be possible to make 2 disc games show disc 1 and disc 2, as i have put metal gear solid on and both disc isos show as exactly the same name with no distinction, so you don't know which disc you are running

thank you for listening

**Comment by GerbilSoft** [comment]
The second disc of 2-disc games should have a "(2)" appended to their name in the game list.

**Comment by SevenWillis** [comment]
Make sure you rename the iso to disc2.iso

**Comment by carnage702** [comment]
like people already said if you got both isos on the same folder, one named game.iso and the other named disc2.iso on the nintendont list the disc 2 will appear with a(2) in front of it.
