### ISSUE TITLE
Wii Remote Plus (partial) simulation

### ISSUE THREAD

**Issue by westonlast** [FIX94/Nintendont#255]
Any controller should be recognizable as and be mappable to the Wii Remote's 3-axis accelerometer and the Wii Motion Plus' (logically) 3-axis gyroscope.

This is partial simulation because the optical sensor input is ignored when a device lacks one, and the axes are not exclusively controllable using a typical controller. 

The Wii U Pro controller can already act like a Gamecube controller, for example, and it even uses the minus button to rotate the right face button mappings during gameplay.  The feature I'm describing is more complex, though.

I care about this because I'd love to play Skyward Sword without motion controls.  To make this playable, the x and y values for the gyroscope would be mapped to the right analog stick.  The y-axis would be hard-coded to some constant value (to create a bounded, cone-shaped orientation of the sword tip around the enemy, for example).  Once the player has selected the sword orientation, the next step is to swing the sword across the diameter of the x-y circular area.  Holding an "acceleration-mode" button (left shoulder, etc) would swing the sword using the acceleration value defined by an analog source (right trigger, etc).  Releasing the "acceleration mode" button immediately switch back to "orientation mode."

This should be enough precision for swordplay and point-and-click tasks.  I realize this is pretty game-specific, but what other game that requires this Motion Plus crap is worth playing? ;)

At the very least, could I please map my damn Dualshock 3 Sixaxis to play this game? :D

**Comment by GerbilSoft** [comment]
Skyward Sword is a Wii game; Nintendont only handles GameCube games. Adding Wii Remote Plus support to Nintendont won't help with Skyward Sword at all.

**Comment by westonlast** [comment]
Wow, I feel dumb.  Never mind.
