### ISSUE TITLE
wiimote + classic controller not working

### ISSUE THREAD

**Issue by pankisiel** [FIX94/Nintendont#256]
when i start up a game all four led are instantly on and i can not control anything. this happens with the newest version of nintendont and with original wiimote + original classic controller attached. wiimote and classic work good (wii games or retroarch).
any ideas?
thx

**Comment by carnage702** [comment]
let me guess fake/3rd party wiimote or nunchuck?

wich nintendont version did you try? say the number its on nintendont menu top left corner.

**Comment by pankisiel** [comment]
same answer here:

definitely not. original peripherals..

it worked once with the nunchuck (original, too) and once with the classic controller, but now it does not. also tried an older build from nov. 2015. same issue..

**Comment by carnage702** [comment]
take a picture of yur nintendont settings and i can probably help you, as long as i can see the settings  quality doesnt matter.

**Comment by pankisiel** [comment]
here is the picture and one of the wiimote and cc

thanks a lot for your efforts
![20160605_203743](https://cloud.githubusercontent.com/assets/8297568/15807410/1047c120-2b5e-11e6-8008-e4da108dff16.jpg)
![20160605_203812](https://cloud.githubusercontent.com/assets/8297568/15807411/10514c72-2b5e-11e6-9dc7-a11a365cba74.jpg)

**Comment by carnage702** [comment]
take native to off since your not using a wii with gc ports and gc controllers, taht disables all extra controllers, you might as wehll take debugger and log off too since that will just make games crash if your not a dev using a gecko device

**Comment by pankisiel** [comment]
fantastic. that worked! i thought, native control refered to memorycard only and not to controller, too.
thx a lot for your help and time!

**Comment by carnage702** [comment]
if you want to use the real memory card just turn memory card emulation off.
