### ISSUE TITLE
Melee Crashes During Use

### ISSUE THREAD

**Issue by TeffyOfficial** [FIX94/Nintendont#258]
I've been having problems running Melee using Nintendont. Sometimes during gameplay, the background music will loop the last two seconds played about five times, then crashes to a black screen with white text (which I assume is the Melee crash screen) reading something along the lines of "An error has occurred. Please power off the console and contact the NINTENDO GAMECUBE User Manual for more details". If necessary, I could attach a video.

I am using Nintendont v3.336 (The version on GBATemp).I installed it using the loader.dol file. I am loading Melee from a 2GB USB stick. My Melee ISO is v1.0 if that matters. My Melee ISO appears to work fine in Dolphin. I have not tested any other games, nor have I tested using an SD card to load Melee (as mine is too full).

Is this a bug in v3.336 that is already known? Should I reinstall Nintendont using the latest version? Am I just doing something wrong? Any answer would be greatly appreciated.

I apologize if this is the wrong place to put problems with v3.336.

**Comment by carnage702** [comment]
why arent you using version 402?

**Comment by TeffyOfficial** [comment]
Because I used the guide on GBATemp

**Comment by carnage702** [comment]
Still outdated since the person that made the first post wasnt updated in  over a year.Try 403, if the problem persist show me a picture of your nintendont settings, btw on ssbm try to leavue speed unlock to off since it needs accurate speed for background music, you can update inside nintendont app itself or manluly by downloading the dol and replacing it on your usb/SD.

**Comment by TeffyOfficial** [comment]
Updated to v3.403, still having the problem. Here are my Nintendont settings: 
![img_2646](https://cloud.githubusercontent.com/assets/19876081/15986786/b5192bc0-2fce-11e6-889e-db0fb261949b.JPG)

If by speed unlock you mean Unlock Read Speed, that was already off.

**Comment by TeffyOfficial** [comment]
Actually, I updated again, and the glitch appears to be gone, though I'm not 100% sure. I guess the old version got corrupted during install, IDK

Thanks

**Comment by carnage702** [comment]
well play for awhile to be sure but still usb stick arent recomended for running with nintendont since speed issues and whatnot, consider using an hdd if you can.
