### ISSUE TITLE
Same wiimote+nunchuck problem as GeorgXtremE had.

### ISSUE THREAD

**Issue by Blastphamoushdizzle** [FIX94/Nintendont#259]
I am having the same problem as GeorgXtremE did here https://github.com/FIX94/Nintendont/issues/177 plus sometimes it scrolls down without me pressing down, neither are third party controllers so that's not why, help!

**Comment by carnage702** [comment]
well he had a third party/fake wiimote/nunchuck.

**Comment by Blastphamoushdizzle** [comment]
Neither are third party controllers actually, Maybe its something wrong with the emulator?

**Comment by carnage702** [comment]
nintendont is not an emulator to begin with and like i said his issue is he had a 3rd party/fake wiimote/CC, your might be something totaly diferent maybe even the wiimote /nunchuck  dpad/joystick being a little worn out and such.

**Comment by shine-spike** [comment]
For anyone who still has this issue, it's not a problem with the controller. It has to do with the wiimote controller configuration, which can be changed by holding down 2 and pressing 1 and letting go of 2, or pressing the d-pad in a certain way and letting go of 2. More details [here](https://gbatemp.net/threads/nintendont-wiimote-nunchuck-support-discussions.371356/).
