### ISSUE TITLE
Freezing at "Initializing IOS58"

### ISSUE THREAD

**Issue by ronanlopes** [FIX94/Nintendont#263]
My Nintendont stop working suddenly (it loaded but doesn't show any text, just background image). So I download the latest version and now it shows the message "Initializing IOS58" and nothing happens after that

**Comment by carnage702** [comment]
try deleting your ninconfig file and try again.

**Comment by ronanlopes** [comment]
Tried it for both versions (latest and a 3.x one). Same errors i described above...

**Comment by carnage702** [comment]
getting stuck on ios58 is wierd you sure you didnt instal any cios over ios58 or something? take a picture of your nintendont settings screen if you can,

**Comment by ronanlopes** [comment]
I can't take a picture of nintendont settings cause it doesn't even boot, I don't get there. It's strange cause it worked before and stoped suddenly. I believe it can be something with the ios... but i checked with pimp my wii and the only ios it apoints error is on ios36 (then when I try download the fixes, it gives dsi error). But wii games on usb loader gx are fine

**Comment by carnage702** [comment]
take a picture of your nintendont folder on apps if you can then.

**Comment by ronanlopes** [comment]
![captura de tela de 2016-06-19 13 36 49](https://cloud.githubusercontent.com/assets/10854483/16178588/18c9c2e2-3623-11e6-992a-9c594a7ae685.png)
![captura de tela de 2016-06-19 13 37 08](https://cloud.githubusercontent.com/assets/10854483/16178587/18c9cd5a-3623-11e6-9ed8-d0f754e94c8f.png)

That's the content of the root folder of external hard drive and the nintendont app folder. If you need something more, let me know

**Comment by ronanlopes** [comment]
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<app version="1">
	<name>Nintendont</name>
	<coder>FIX94, crediar</coder>
	<version>3.341</version>
	<release_date>20150531000000</release_date>
	<short_description>Gamecube Loader</short_description>
	<long_description>Commiters: JoostinOnline, GreyRogue, Howard, Cyan 

 Project website: https://github.com/FIX94/Nintendont 

Nintendont allows you to run GameCube games on a Wii or Wii U from an SD or HDD device.</long_description>
	<ahb_access/>
</app>

That's the meta content

**Comment by carnage702** [comment]
if you cant even boot nintendont directly from the homebrew channel something is very bad tough you messed with ios or putted a theme on your homebrew channel? or anything else? did nintendont ever worked for you?

**Comment by ronanlopes** [comment]
No, it actually boots... but nintendon't don't boot its functions. It stuck on the main page with just the background image (in case of 3.x version, which I was using before and stoped working). The latest version, boots, and keeps with the nintendont background Image and the text "Initializing IOS 58"

**Comment by ronanlopes** [comment]
Yes, nintendont worked before and I used it together with usb loader gx. In both cases (booting nintendont by usb loader gx ou directly from the channel) it opens and get stuck in the way I explained before

**Comment by carnage702** [comment]
what i sugst is a fresh sd/usb  just get a new device and download a fresh new nintendont dol version 405 and new meta and new icon and try it again.

**Comment by ronanlopes** [comment]
Forgot to tell that I also tried to boot from SD card on homebrew launcher, and same result. I'll try with the 405 version. Where can I get it?

**Comment by carnage702** [comment]
i  meant 408 that is the latest 
https://github.com/FIX94/Nintendont/raw/803e651738887b236dbc65a1236f6c818c9a5450/loader/loader.dol

btw on your homebrew channel press home button then tell me what it says on the corner it should have ios58 info, but from what your saying im guessing you brooke your ios58 somehow wich nintendont needs to work.

**Comment by ronanlopes** [comment]
On the top right corner there are two lines: "1.1.0" and "IOS58 v24.32". Is there a problem with that version? Should I install another and if so, how I do it? Thanks for helping

**Comment by carnage702** [comment]
thats your problem, ios58 needs to be the official one that is 25.32 so you for sure changed your ios58 with a modded one or something you need the official latest ios58 by nintendo 25.32

**Comment by carnage702** [comment]
http://wiibrew.org/wiki/IOS58_Installer

**Comment by GerbilSoft** [comment]
IOS58 v25.32 (v6432) is the Wii U version; do NOT install this on a regular Wii!

Latest version for regular Wii is in fact v24.32 (v6176).

**Comment by carnage702** [comment]
yeah i forgot vwii version yeah still soemthing is wierd whith his ios58 if nintendont cant even start so maybe  running the ios58 intaller will clean his ios58 since its a wii app

**Comment by ronanlopes** [comment]
I already tried to run the ios58installer, via homebrew channel, and via wad (downloaded by NUSDownloader). Nothing worked too... anyway it's weird cause it worked before and I didn't change anything about the IOSs' before it stoped to work. I'll try to set up these dev kits to see what's going on

**Comment by carnage702** [comment]
dont you have acess to another wii or wiiu? maybe try the same sd or hdd on other console?

**Comment by ronanlopes** [comment]
Yeah, already tried... played with it last weekend on another wii. Everything was fine. Used 3.x version too. Have no idea how to use  devkitPPC+devkitARM. Is it too much complicated?

**Comment by carnage702** [comment]
try deleting the controller ini file and the font files on the root  they arent needed anymore and might be corrupted imo.

**Comment by ronanlopes** [comment]
It works now! Thanks a lot for the help, @carnage702 ! =)

**Comment by GerbilSoft** [comment]
There *was* a change that replaced the custom atoi() and atox() functions (used by the controller.ini parser) with strtoul() in the kernel.

I suppose you didn't back up those broken controller.ini and/or font files. If you encounter this issue again, please upload the broken files so I can attempt to make the parser more robust.

**Comment by carnage702** [comment]
its an issue since v1 of nintendont, controller inis sometimes go corrupt and break nintendont.

**Comment by lszad** [comment]
I am having the same issue (Nintendont freezing at "Initializing IOS58") when loading gc games through USB Loader GX. It used to just show the background, then I downloaded the up to date version and am now stuck at this initializing message. Nintendont loads games fine if I open it through HBC though. The only file in my root folder (besides the subfolders) is nincfg.bin. I've already updated IOS58 (even though it remained the same version).

**Comment by carnage702** [comment]
delete the ninconfig and a controller.ini that you might have on the root of your usb/sd those files sometimes corrupt.

**Comment by lszad** [comment]
it worked! thanks a lot! :)

**Comment by lszad** [comment]
Actually, it stopped working again :( When I said it worked, it didnt actually load the game. Instead, it just opened Nintendont like HBC would. So I tried changing some configs and it hanged in the same place as before. I tried erasing the ninconfig, but it still doesnt work <o> I'm using v.4.416 for Wii

**Comment by carnage702** [comment]
i think that is an issue with usbloader gx not nintendont, if it works when using nintendont directly then your usbloader gx is most likely   outdated and cant handle with nintendont 416.

**Comment by Moosecab** [comment]
I am having this issue now (freezing at "initializing IOS58"), starting seemingly out of no where. I have to hold the power button and turn the Wii off just to get off that screen when this happens. Everything on my Wii now seems to be exactly as it was before when it was working yesterday. I did nothing involving my IOS58 (or any other IOS for that matter), and made sure I have the correct version (v24.32 v6176 as this is Wii, not Wii U). I am using v4.422 of Nintendont and v1.1.2 of HBC. I made sure I was using the correct USB port and tried it in both. I verified that I have the latest version, and I also tried the loader/boot.dol file in a higher comment on this post with the same results. I deleted nintendont and redownloaded a new file (a new boot.dol and a new meta.xml files) with the same results. I have no controller.ini or font files on either the SD card (where my homebrew channel apps are) nor the USB drive (where the games are). I tried deleting the ninconfig file as suggested above, and it changed nothing. The only thing on my USB drive now is my games folder, and the game files within (it was only the games folder and the ninconfig file on the root before). If it helps, here is my meta and pictures of my nintendont folder (on my SD card) and of the root of my games' USB drive. Maybe, I'm missing something that you'll be able to see.
![meta](https://cloud.githubusercontent.com/assets/21076212/17729150/68ef4f84-6428-11e6-9e34-56c18164ef33.png)
![nintendont folder](https://cloud.githubusercontent.com/assets/21076212/17729155/703fa374-6428-11e6-9f98-5e21a148d0aa.png)
![game usb root](https://cloud.githubusercontent.com/assets/21076212/17729159/768fcc90-6428-11e6-92a6-cc82ae6886b6.png)

**Comment by Moosecab** [comment]
Hmm, I just noticed, it showed v4.422 on the screen (top left corner of the nintendont screen that shows "Initializing IOS58..."), but on this meta that was downloaded with it, it says v4.417. I don't think that's significant, but just in case.

**Comment by carnage702** [comment]
like abode delete any ninconfig,controller.ini or font files that you may have on the root of your device. its normal the 417 will update to 422 once you save some settings.

**Comment by Moosecab** [comment]
There were no controller.ini or font files, and I deleted the ninconfig files. I'm adding a picture of the root of my sd to see if that will help. 
![sd root](https://cloud.githubusercontent.com/assets/21076212/17750556/b58a40a0-6488-11e6-9f05-da59fd5812ea.png)

**Comment by Moosecab** [comment]
One more thing, I noticed that in my meta file, near the end, there's a line: <no_ios_reload/>, but that line was not in the original poster's meta file. Would that be affecting anything?

**Comment by Moosecab** [comment]
Sorry, left out, the line was no_ios_reload.

**Comment by carnage702** [comment]
why do you show me your sd card root? nintendont games are obviosuly on your usb device since i see no games folder on the SD so maybe you got some controller ini or something else on your usb root?
no_ios_reload is needed for people that use older homebrew channels wich was added recently.

**Comment by Moosecab** [comment]
Just in case there's something there that doesn't need to be or vice versa. I'm not the brightest when it comes to these things. Maybe I should also mention that I've tried nintendont through the system menu channel, through hbc, and even downloaded and tried through wiiflow all with the same result. In addition, I tried the Nintendont included with the wiiflow mastermod pack, and that one didn't even get to the initializing screen. The screen just remained dark and blank.

**Comment by Moosecab** [comment]
Another update: when I was trying to play it before, I had the gamecube mic plugged in which we used for Mario Party 7. I started it up again, and this time it went on and played like it normal did before. Sorry, I didn't notice that before to think to mention that.

**Comment by carnage702** [comment]
mic should only be plugged after the game has started and needs mcemu set to off.

**Comment by XIGmurky** [comment]
Ok i'm having the same issue with it stopping on the ios58 initialization but i cant find the ninconfig files to delete them or the controller.ini, please help

**Comment by carnage702** [comment]
first time running nintendont? is your iso58 the original umoded ios58 or you installed some cios?

**Comment by AlexS2412** [comment]
ive done everything from having no usb devices plugged in, empty sd with literally just the newest nintendont on it, reinstalling ios58 multiple times from nus... nintendont literally never loads anymore ;-;
