### ISSUE TITLE
Nintendont error -3

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#264]
Nintendont error -3 , estou tentando atualizar o Nintendont V4.408 para V4.409 o meu nintendo Wii está via Wii-fi e sempre atualizei normalmente pela internet por ele, mas nestas ultimas atualizações quando pedi para atualizar a lista.txt aparecia em vermelho Error - 3 , agora hoje quando fui atualizar para versão V4.409 apareceu o mesmo Error -3 , creio que seja problema no servidor do arquivo, e espero que logo volte a funcionar, um abração. 

Nintendont error -3, I'm trying to update the Nintendont V4.408 to V4.409 my nintendo Wii is via Wii-fi and usually always updated over the Internet for it, but these latest updates when asked to update the list.txt appeared in red error - 3 now today when I upgrade to V4.409 version appeared the same error -3, I believe that to be a problem on the file server, and I hope you come back soon to run a big hug.

**Comment by carnage702** [comment]
o servidor é aqui no github  o nintendont tira os ficheiros deste repositório, porque é que tentou actualizar a lista.txt? esse ficheiro nunca mais foi actualizado pois não saem jogos para a GC há muitos anos, pode ser um problema com o seu wifi visto que o github está a funcionar plenamente e o github é o nosso "servidor".

**Comment by spielvan** [comment]
carnage702 valeu mano também não só que me deu na cabeça de tentar atualizar o lista.txt, no caso do DOL eu acabei de atualizar manualmente para o V4.409, ficou show de bola esta nova versão. Aproveitando a postagem ando testando jogo de N64 injetados em um Zelda do GC exp-n64v2.gcm e alguns tem rodado muito bem no nintendont.

The Legend of Zelda: Ocarina of Time PT-BR = rodou perfeito com save funcionando joguei até poder controlar o link.
Mario Kart 64 = rodou normalmente com alguns bugs no menu e na mudança de pista.
Star Fox 64 = Rodou perfeito só ocorre um escurecimento de tela no primeiro movie quando eles estão dentro da nave, de resto rodou perfeito.
Duke Nuken 64 = Rodou perfeito.
Blues Brothers 2000 = Rodou perfeito.
Super Mario 64 = Rodou perfeito.

Quem sabe em um futuro o nintendont não rode os emuladores que rodavam no GC e tandem os jogos injetados tenho vários de GBA e Nes mas ainda não tive sucesso em roda-los pelo nintendont.

**Comment by carnage702** [comment]
esse emulador roda poucos jogos assim como as injects de gba ou nes, se tem uma wii ou wiiu tem muito mais escolhas de emuladores bem melhores xD, o nintendont nunca vai suportar homebrew da GC pois o nintendont funciona usando patches dos devkits e procura padroes o homebrew na gc não tem padrões visto que os devs escreviam qualquer coisa por isso o nintendont nunca vai conseguir rodar nenhum homebrew infelizmente, mas felizmente todo o homebrew da gc existe também para a wii e com melhor performance por isso não perde nada em usar os emuladores no homebrew channel da wii pelo contrario só ganha a única vantagem do nintendont e os hid controller e o wiiupro que qualquer dev se quisesse punha no seu emulador mas todos os projectos já estão abandonados há anos.
