### ISSUE TITLE
2 controls PS2 via USB with adapter

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#265]
A horas que tenho está duvida, principalmente com o meu outro wii que é o Family Edition sem entrada controle de GC, é possível usar dois controles ps2 através de um destes adaptadores de controles de ps2 para usb? tenho um parecido com este.

[http://soseletronicos.com.br/site/wp-content/uploads/2015/07/f49.jpg](url)

The hours I have is doubt, especially with my other Wii Family Edition which is no entry GC control, you can use two controls ps2 through one of these adapters PS2 controls for usb? I have a look like this.

**Comment by carnage702** [comment]
Alguns dão outros não, tivemos pessoas a dizer que funcionavam correctamente outros a dizerem que só o primeiro funcionava e etc , é meio tiro no escuro,  mas o que funciona melhor  e é garantido é o wiiu gc adapter, funciona mesmo na wii sem gc ports  para o nintendont somente e até pode jogar com 4 comandos da gc, é a melhor opção a meu ver especialmente se já tiver um comando de GC.

**Comment by spielvan** [comment]
Uma informação importante, até porque pode usar um adaptador de controle de ps2 para gc e utilizar controles de ps2 com ele. Muito obrigado.
