### ISSUE TITLE
Add option to disable power off combo/reset combo on HID controllers

### ISSUE THREAD

**Issue by HowManyNames** [FIX94/Nintendont#268]
Like the title says, an option to allow the power off combo to be disabled with non-native control would be great. The closest thing that can be done now is to remove the POWER entry from controller.ini, but at least with the Wii U GC adapter, it makes it reset the game instead of exiting to loader.

**Comment by carnage702** [comment]
why? dont tell me yu randomly press  Shutdown: R+Z+B+Down (D-pad) there is no reason to ramdonly press a 4 button combo that isnt used anywhere.

**Comment by HowManyNames** [comment]
Its not that on the GC adapter, its L+R+Z+Start, which unfortunately lined up with the salty runback code me and some friends used for Melee, and yes, one of them actually managed to accidently exit Nintendon't.

**Comment by carnage702** [comment]
then remap the exit combo to a combo you cant possibly hit or remove  it it makes no sence to  take out a  feature that can be customized very easily by adding a useless menu option for it.
