### ISSUE TITLE
Nintendont in retroarch...

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#269]
Nintendont no retroarch, eu estava pensando agora haveria alguma possibilidade de um dia o Retroarch ter entre seus cores o Nintendont ?

Nintendont in retroarch, I was thinking there would now be a possibility of one day Retroarch have among their colors the Nintendont?

**Comment by carnage702** [comment]
não pois nintendont não é um emulador, o nintendont é semi nativo, por isso todas as opcoes do retroarch não funcionariam visto que não tamos a emular os graphicos.

**Comment by spielvan** [comment]
carnage702 obrigado pela resposta mano, parecia uma pergunta boba, mas era duvida de vários.
