### ISSUE TITLE
Download Complete, Update Error: -3

### ISSUE THREAD

**Issue by OTFree** [FIX94/Nintendont#273]
Currently running Nintendont v4.407 on Wii U, but whenever I try to update over WiFi, I get this message after it says Downloading Nintendont v4.11;

"Download Complete
Update Error: -3"

Then it takes me back to the menu.

**Comment by spielvan** [comment]
Então não sou o unico a ter este problema, eu tenho atualizado manualmente:
Vai aqui https://github.com/FIX94/Nintendont/blob/master/loader/loader.dol e clica em REW para baixa o loader.dol depois de baixar renomeia o loader.dol para boot.dol e coloca dentro da pasta apps\nintendont vai mandar substituir pelo que tem tu manda substituir e ja vai carregar a versão mais atual.

Dica: pode usar o wiixplorer para este processo de passar do usb para sd, e aconselho a copiar o boot.dol antigo que tenha no sd para um backup.

So I'm not the only one having this problem, I have updated manually:
Go here and click https://github.com/FIX94/Nintendont/blob/master/loader/loader.dol REW to lower the loader.dol after downloading renames the loader.dol to boot.dol and places within the folder apps \ nintendont will send substitute for what you have already sends replace and will load the latest version.

Tip: You can use the wiixplorer for this process over USB to SD, and advise you to copy the old boot.dol that has the SD to a backup.

**Comment by Mckeyhan** [comment]
I have 4 Wii's and i have the same problem... I don' t understand what is happening

**Comment by carnage702** [comment]
there is a bug in the updater code since the new fatfs system was implemented so until then update manualy by downloading the latest dol here and replacing the boot dol in the nintendont folder.

**Comment by FIX94** [comment]
should be good now.
