### ISSUE TITLE
NTFS support in Nintendont?

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#275]
Teriam em mente uma implementação deste formado no nintendont, possuo 3 hd externos e os 3 estão em Ntfs?

Have in mind an implementation of this formed the nintendont, I have 3 external hd and 3 are in Ntfs?

**Comment by GerbilSoft** [comment]
NTFS is significantly more complicated than both FAT32 and exFAT. The standard NTFS library for Wii is around 500 KB, which is bigger than the entire Nintendont kernel.

tl;dr not likely to happen anytime soon.

**Comment by carnage702** [comment]
como o gerbilsoft disse a libraria do ntfs é maior que o nintendont e nos precisamos de todo o ram disponível por isso transforme em fat32 com aplicações externas que permitem transformar qualquer hdd em fat32 ou até uma partition chega.

**Comment by spielvan** [comment]
GerbilSoft e carnage702 Muito obrigado pela resposta, eu perguntei pois tenho os jogos de nintendo wii em uma pasta wbfs no meu hd externo 1tb samsung ntfs e rodo pelo Usb Loader gx e pelo Wiiflow ai eu estava a horas para fazer esta pergunta muito obrigado varias perguntas que eu tinha foram solucionadas. Muito obrigado pelo ótimo trabalho que vocês tem feito no nintendont.

Thank you for the answer, I asked because I have the game of Nintendo Wii in a WBFs folder on my external hd 1tb ntfs Samsung and squeegee the Usb Loader gx and the Wiiflow then I was on time to do this thanks asks several questions I had They were resolved. Thank you for the great work you have done in nintendont.

**Comment by carnage702** [comment]
ntfs é só mesmo suportado por usbloaders qualquer outro homebrew como emuladores e isso não suportan ntfs por isso eu recomendo mesmo tornar o seu 1tb hdd em fat32 todos os wbfs maiores do que 4gb podem ser divididos e ainda funcionam no usbloader gx.

**Comment by thericeking** [comment]
Does Nintendont support ExFat? I looked all over for an official Nintendont Wiki but everything I found was just an overview. I would love a wiki for this amazing application. I feel like I am not using it to the fullest potential due to hard to find documentation. Can you please point me to the right direction? Thank you
