### ISSUE TITLE
Save freezing

### ISSUE THREAD

**Issue by westonlast** [FIX94/Nintendont#276]
Using "Memcard Emulation," sometimes the game freezes while trying to save.

Initializing the save file in Zelda Collector's Edition: Ocarina of Time froze the first time.  On my second try, it worked.

I'm six hours into Skies of Arcadia Legends, and all of the sudden a save point didn't work.  It froze showing the save progress bar, but the game audio continued to play.

In both cases I had to hold the Wii U power button to shutdown.  Pressing the Home button didn't work.

**Comment by carnage702** [comment]
post all your nintendont settings.

**Comment by westonlast** [comment]
Renamed BIN to TXT to workaround dumb GitHub:
[nincfg.txt](https://github.com/FIX94/Nintendont/files/335466/nincfg.txt)

Force Progressive, Video Width "Auto,"  Cheats "On" with no cheats

**Comment by carnage702** [comment]
please take an actual picture of your nintendont settings screen  and btw i think that ninconfig is corrupted

**Comment by westonlast** [comment]
No picture, but more information: I upgraded Nintendont after the Skies of Arcadia freeze.  Started with a fresh (no file) configuration and the same settings changed as above.  At first the game didn't recognize my save files.  I turned "Memcard Emulation" off, restarted the game, quit, turned "Memcard Emulation" on again, and then the game recognized my save files.  The file I was in the middle of saving during the freeze was reported as corrupted, but luckily I had a backup file on the same emulated memory card that was still good.

**Comment by carnage702** [comment]
unless all your nintendont settings there is no help.

**Comment by westonlast** [comment]
Maybe I don't need help. :8ball:

**Comment by carnage702** [comment]
Again if you refuse to tell or even show all your nintendont settings and you still go around saying you dont need help then im gonna close this since its pointless.

**Comment by westonlast** [comment]
I didn't say I don't need help.  You're closing this because you're frustrated for no good reason.

**Comment by carnage702** [comment]
No good reason? You dont want to post your nintendont settings for whatever reason  since there are options that could make that happen and yet you keep posting and not putting your nintendont settings.

**Comment by westonlast** [comment]
There's never a good reason to be frustrated, by the way.

Let's summarize what happened in our exchange, because we all know that arguing on the Internet is productive: :lollipop:

I did post my settings in the most accurate format available, which is the binary "nincfg.bin."  You suggested that my file might be corrupted.  No fault of mine, but fine, I deleted the configuration to start fresh, and I updated Nintendont while I was at it.  (That's usually the next suggestion, "Use the latest version.")

Then you say this non-native-English-speaking, abrasive sounding thing, "unless all your nintendont settings there is no help."

IS NO HELP.  *GRUNT*
https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us

Who says you're the only person who could possibly "help," anyway?  That seems pretty self-important.  Do you write the code?

"yet you keep posting."  Yes I do, in response to your inflexible "do this OR ELSE we absolutely don't care."  If you have no information to add to the issue, instead how about breaking the mold of being a typical software asshole?  If you don't have anything nice to say, don't say anything at all?  Just close the issue next time since you know best and have the power.

Remember when we were friends?
https://github.com/FIX94/Nintendont/issues/257

I like you.  Be cordial to me, please.  Or ban me.  Your choice.

"there are options that could make that happen..."  Sounds like a bug to me.  Which options are they, I wonder?  Will you please tell me so that I can double check my settings?  Thank you.

**Comment by carnage702** [comment]
how hard is to either take a picture of your nintendont settings and posting it here or just type them manualy? why do you need to make this drag on? 

This is my last post here until you give me material to help, also im one of the fews that helps users around here since this  error screams user error all the way, since no game has frozen while saving been reported in over 200 revs and i dont need to tell you how manny people used nintendont.

**Comment by westonlast** [comment]
You're not obligated to help or post in any way, I agree.  Thank you again for all the help you have given me.

> why do you need to make this drag on?

Because software (or "hacker") culture sucks, and I'm changing the world.  lolol :P :P

I'm also not obligated to do what you suggest.  Typing my settings manually is now acceptable?  I've already provided the changed ones.  But I thought the whole point of the picture demand was the lack of trust in stupid, anonymous Internet user X (that's me).

I agree that this could be my own user error.  The problem is I can't figure out what my error could have been.  No combination of settings should be able to corrupt "nincfg.bin."  If some combination does, that's a human input validation bug.

I suspect that when a game has frozen while trying to quit a game, corruption happened somehow.  You told me that this is an expected case here: https://github.com/FIX94/Nintendont/issues/257

If this is the case, that's a Nintendont bug, not a user error (because Nintendont implements the quit behavior).  I'm not sure if it's a fixable bug, but it also wouldn't be my fault.  Maybe it's an unrecoverable error scenario that could be mitigated by tighter "nincfg.bin" validation on startup.  Who knows.

Thanks for listening.
