### ISSUE TITLE
Do you wish to enable progressive scan display freeze

### ISSUE THREAD

**Issue by eXTCy** [FIX94/Nintendont#277]
Ok so i am on my wii with gamecube support
I try to run any gamecube game and the screen that asks for do you wish to enable progressive refresh or whatever it freezes.
my gamecube controllers do not respond.

Settings: Everything is default except for Native control is toggled to On and Memcard emulation is set to on

**Comment by eXTCy** [comment]
hm as soon as i wrote that the issue seemed to fix itself.
maybe i needed to have the controller turned on throughout.
and maybe when i turned on memory card emulation it fixed itself.

**Comment by carnage702** [comment]
you dont need native on to sue gc controllers btw, native is only needed if you use random stuff like the gba link cable adapter and microphones that connect to the gc port and such.
