### ISSUE TITLE
vWii USB HD falling asleep too soon causing WiiU hard crash

### ISSUE THREAD

**Issue by littlebigboss12** [FIX94/Nintendont#278]
This is of course due to the drive's power save features causing it to spin down after a certain amount of inactivity, but is causing the WiiU to hard crash while playing games where drive is not constantly being accessed. An example of a game which this will happen to is Animal Crossing as I suspect that due to the small size of the game it must cache a lot of the game's data, requiring very infrequent access to the drive.

Is there a way to have the drive 'pinged' more frequently so as to prevent it from spinning down or does this even make sense? To be fair, the cfg USB Loader has the same issue if you load the vWii and sit on the HBC screen for a while before loading. If you do this cfg USB loader will hard crash the WiiU since it doesn't initialize storage devices before loading as you do with Nintendont.

**Comment by carnage702** [comment]
what nintendont version are you using say the number dont say latest, nintendont pings the hardrives since  maybe a year ago unless your using a very very outdated version.

**Comment by littlebigboss12** [comment]
![tmp_5626-img_20160627_182338-385506192](https://cloud.githubusercontent.com/assets/19326043/16398390/0928e11c-3c98-11e6-8239-878524b0b88e.jpg)
![tmp_5626-img_20160627_182414-1570601747](https://cloud.githubusercontent.com/assets/19326043/16398402/157a90fa-3c98-11e6-86d6-2a300b229637.jpg)

**Comment by littlebigboss12** [comment]
Thanks for the quick response, I should've included this info earlier. 😃

**Comment by carnage702** [comment]
well nintendont pings the hdd every 2 min and 30 seconds so unless your hdd sleep timer is  under 2min and 30 seconds i have no idea since this fixed most hdd sleeps long time ago.so im guessing you may need to disable your sleep timer i know there are some programs for seagate to do that.

**Comment by littlebigboss12** [comment]
No kidding, I believe it is under the 2m30s ping but I didn't realize there were people who would write such a program to disable the sleep timer. I'll look into it and see what I can find. Thanks for the suggestion! This is actually the 2nd drive I've tried that has this sleep problem as I thought the timer would be more on this drive. Seems I was wrong :/
