### ISSUE TITLE
Some games don't work with Video Width or Screen Position

### ISSUE THREAD

**Issue by cheatfreak47** [FIX94/Nintendont#279]
And yet another thing I've noticed is that some games, including Super Mario Sunshine don't work properly with the screen position or video width.

Is this something that can be fixed?

I've also noticed it happens in a few other games but I haven't exactly compiled a list, I might if that becomes relevant.

**Comment by spielvan** [comment]
Tentou ir nas definições do nintendont se não me engano a penúltima é para centralizar a tela, eu lembro de uma vez ter conseguido deixar ele em tela full, sem tarjas laterais mas alguns jogos europeus bugavam com está configuração.

We tried to go in nintendont settings if I am not mistaken the penultimate is to center the screen, I remember once having managed to leave it in full screen, without side stripes but some European games bugavam with is setting.
