### ISSUE TITLE
Delayed acceleration / brake in mk

### ISSUE THREAD

**Issue by ppsspp213** [FIX94/Nintendont#281]
The acceleration rate seemes delayed, I'm guessing because the game uses a analogue pressure / resistance rate for the pedals, where as nintendont uses the same rate at it's lowest value? because it's digital?
I'm using the default button profile so the pedals are located to the nunchuck tilt, I always position the nunchuck the to fullest 90 degree angles, maybe it produces different rates when the pedals are mapped to the analogue z and b buttons idk.

**Comment by carnage702** [comment]
your using a nunchuck on nintendont damn that is the worst possible controller, if your not playing an fps and want ir aiming, i would recomend getting gc controller or atleast a CC they are so much better on gc and triforce games,nunchucn and wiimote stuff were not made by nintendont team exactly they were made by the "fans"  and then were added to the main build, nunchuck controlls are preety poor.

**Comment by ppsspp213** [comment]
^ It's not so bad when used with Nagger's or Troopz profile, problem is I don't like messing about with 1 & 2 button to change profiles, half the time I mess up and press the wrong button.
I wish the used preset profiles could be selected via the nintendont settings rather than button combo, that way with usb loader gx you could just set it to whatever profile you wanted per game without having to worry.

**Comment by carnage702** [comment]
like i said the nintendont team didnt made it so it was forced him somewhat be glad fix94 letted it reach an official nintendont version xD.

**Comment by ppsspp213** [comment]
I wasn't complaining about the profiles, what I meant was something like

const char* OptionStrings[] =
{
	"Button Profile",

};


const char* Button ProfileStrings[] =
{
	"Howard",
        "Shooter",
        "Shooter sans IR",
        "Nagger's",
        "AbdallahTerro",
        "Troopage",
        "Digital Racing",
        "Analog Racing",

        "Switcher",
};


unsigned int		Button Profile;
	
	NIN_SETTINGS_Button Profile,
