### ISSUE TITLE
Analog stick radius issues for Pokemon Colosseum

### ISSUE THREAD

**Issue by RedZone908** [FIX94/Nintendont#282]
When using a Wiimote with a flight pad controller (technically classic controller pro) with Pokemon Colosseum, pushing the analog stick all the way down causes the controller to act as though the stick is pressed upwards, e.g. Character moves up instead of down.  Other directions don't have issues, and pushing the stick _partially_ down gets the correct behavior (character goes down).  This issue is not experienced in other games in Nintendont.  It does turn out, however, that Dolphin experiences this same issue with Pokemonw Colosseum.  I do nor know if there is any way to allow the Nintendont user to adjust the controller radius for some games to fix this?

**Comment by carnage702** [comment]
this is a known issue it happens randomly on the start of colosseum if on game start fully pushed analog stick doesnt go down then it wont until reset there is an issue with something as off yet undetected on boot, there is always a chance of happening both on xD and colosseum.

**Comment by FIX94** [comment]
fixed in the latest rev, wasnt a nintendont bug but an actual game bug.
