### ISSUE TITLE
Splinter Cell Chaos Theory - Z Button Not Recognized

### ISSUE THREAD

**Issue by boullose** [FIX94/Nintendont#283]
Hello, 

I appreciate all the hard work you guys put into this project! I was wondering if it would be possible to apply a fix for splinter cell chaos theory to recognize the Z button for controllers that are not official GC controllers. 

Thanks!

**Comment by carnage702** [comment]
what do you mean? z works great on my cc,wiiupro and such so what controller are you using?

**Comment by boullose** [comment]
Hi,

I'm using the super smash bros pad controller that hooks to a Wii controller. The Z buttons will work perfectly is recognizable for many games on Nitendont. However, when playing Splinter Chaos Theory on Nitendont, the game won't recognize the Z button. Any solution to this, I was thinking maybe configuring the settings to change the Z button for something else?

**Comment by carnage702** [comment]
it doesnt work like that what is hapening is your adapter has a custom config so what adapter are you using? mayflash adapter?

**Comment by boullose** [comment]
I'm using the smash logo controller with a Wiimote. When loading splinter cell chaos theory, I cannot load up my inventory by pressing the Z button or change the config buttons. 

Thanks!

**Comment by carnage702** [comment]
smash logo controller does not connect directly to a wiimote so what is the adapter you are actualy using to connect the gc controller to the wiimote?

**Comment by boullose** [comment]
Hello,

Sorry for the confusion, I am using the Wii U fight pad that connects directly to the Wiimote. 

Thanks!

**Comment by carnage702** [comment]
you jsut said you were using the smash logo controller lol that is the controller that is on sale to use with the wiiu gc adapter, also btw isnt it z+start to acess the menu?

**Comment by carnage702** [comment]
just confirmed it z alone does nothing on chaos theory because thats how it is coded to be

z+start opens menu
z+dpad up selets gear
z+A stick to the wall
z+dpad sides wistles
Z+cstick down opens the binoculars thing


this are the trus chaos theory controls please dont report stuff if you didnt even bothered to see the controls on the main menu option...
