### ISSUE TITLE
Error memory DSI v4.415

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#285]
Acabei de atualizar o nintendont para versão V4.415 , de três vezes que tentei, duas vezes quando entro nas opções e clico o botão Home do remote para sair para o HomeBrew channel, da o famoso erro DSI de memória e tenho que desligar e ligar o wii para voltar a usar.

I just upgraded to the nintendont V4.415 version, three times I tried twice when I enter the options and I click the remote's Home button to exit to the Homebrew Channel of the famous error memory and DSI have to turn off and on Wii for re-use.

**Comment by carnage702** [comment]
apague qualqurer controller.ini e ninconfig ficheiro que esteja na raiz do seu hdd/SD.

**Comment by spielvan** [comment]
carnage702 valeu mesmo, controller.ini acho que não tenho pois uso eles a tempos na pasta controllers, agora o ninconfig não sei dizer mas vou fazer este processo valeu mesmo, geralmente eu jogo com um controle ps3 via usb e com os jogos na pasta games do pen drive e o apps no sd.

**Comment by spielvan** [comment]
carnage702 fui ver aqui, e tinha só na raiz do sd destes arquivos um nincfg.bin não sei se era ele mas tirei ele da raiz do sd e coloquei em outra pasta provisoriamente abri o nintendont uma vez e não deu erro DSI não sei se era ele o responsável acho que o bom era eu fazer uns 4 ou 5 testes para ter certeza.

**Comment by carnage702** [comment]
esses ficheiros as vezes corrompem e precisam de ser apagados, e pode apaga-los a vontade o nintendont cria um ninconfig sempre que mudar as settings e entrar num jogo.
