### ISSUE TITLE
Error -3 when trying to update Nintendont to the latest version 

### ISSUE THREAD

**Issue by littlebigboss12** [FIX94/Nintendont#286]
Can't figure out what is causing this...
![img_20160712_124037](https://cloud.githubusercontent.com/assets/19326043/16775566/4520848e-482f-11e6-9aee-31fcb9c052d5.jpg)
![img_20160712_124045](https://cloud.githubusercontent.com/assets/19326043/16775582/52e70412-482f-11e6-8610-b1769c595d44.jpg)

**Comment by carnage702** [comment]
417 is the latest version, you cant update more than that lol.

**Comment by OTFree** [comment]
Same thing is happening on v4.11 when trying to update...

**Comment by carnage702** [comment]
411is still broken 412 and up are working.

**Comment by OTFree** [comment]
Ahhhh, okay. Thanks for clarifying!

**Comment by littlebigboss12** [comment]
Good to know, I appreciate the quick response and help😃
