### ISSUE TITLE
powera wiiu pro controller wireless support help and trick to get it somewhat working

### ISSUE THREAD

**Issue by monkeyman4412** [FIX94/Nintendont#290]
well powera controller does somewhat work, it doesn't work under all circumstances when game is loaded, unless (example sunshine) has a bit of a prolonged loading screen and getting it to connect disconect and reconnect all before players are properly counted for (so both times i connect it needs to show all lights twice and on the second time it will be fourth still, then quickly switch to first second ect.) which for what ever reason then controller is properly working. could you make a option to extend loading screens or just make power a support. besides that everything is amazing (i have a classic controller pro so I can still use it) and best of luck with this project

**Comment by carnage702** [comment]
what? extend loading screens why? you can connect a controller at any time being in game or in loading screens, also third party controllers/fake ones dont have perfect compat because they all use diferent code, and no its not possible to extend loading screens lol.

**Comment by monkeyman4412** [comment]
is there any way I can make a config file for said controller, or some modifcation for this controller

**Comment by monkeyman4412** [comment]
program side

**Comment by carnage702** [comment]
no BT controllers are hardcoded inside nintendont so you would need to edit nintendont source code and them compile it and i have no idea what you woudl edit for a third party/fake wiiu pro to begin with.

**Comment by monkeyman4412** [comment]
Here is the reason. I said to extend those loading screens, for what ever
reason it seems to correct the incapaiblity situation, no joke, it seems
connect it twice (so the console disconnects it automatically and then you
have to connect it again) which if done fast enough it will light up
connect say  all lights and go to 1 player, and by doing so it FIXES, the
issue under all circumstances the controller says it is connected but does
do anything. Just having a little option to extend the boot up screen
(loading screen is when the game is preparing to boot up the main
nintendont screen, when the screen goes black you need to do that) I'm
going to make a video maybe somebody can anylize it

**Comment by monkeyman4412** [comment]
ok here is the video (and I mean doesn't "it does do anything"

**Comment by monkeyman4412** [comment]
hang on just give me a sec

**Comment by monkeyman4412** [comment]
im uploading the video give me a little bit longer

**Comment by monkeyman4412** [comment]
https://youtu.be/9s2jyygkKPE and I had coffee so If i seem a little too talkative my bad

**Comment by monkeyman4412** [comment]
and it probly not the loading screens themselves but the bluetooth side of stuff while figuring out which pads are in (its just a guess I really don't know all I do know is there is something running in the backround when the loading screeen is going
