### ISSUE TITLE
A onde ficam os savegames do NintendoNT

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#293]
A onde ficam os savegames do NintendoNT

**Comment by GerbilSoft** [comment]
sd:/saves/ID3X.raw
usb:/saves/ID3X.raw

where ID3X is the game's ID3 plus the region character.

If you have "memory card multi" enabled, it's ninmem.raw for USA/EUR and ninmemj.raw for JPN.

**Comment by carnage702** [comment]
no dispositivo que tem os isos se o SD tem o nintendont e o usb tem os isos os saves vao estar no usb não no SD, sempre onde estão os isos. na pasta saves como ele disse, isto se estiver a usar mcemu multi exist um so unico ficheiro, se for individual tem varios, um para cada jogo(a maneira mais segura).

**Comment by spielvan** [comment]
GerbilSoft muito obrigado mano.

**Comment by spielvan** [comment]
carnage702 obrigado mano, um usuário la do blog acabou de perguntar vou colocar as duas respostas assim vai ajudar a duvidas futuras. Um abração
