### ISSUE TITLE
PS3 controller connect failed, please help.

### ISSUE THREAD

**Issue by onlynight** [FIX94/Nintendont#294]
when i test the ps3 controller, i got this error message. i dont know what this means, please help me connect the ps3 controller.

ControlMessage():-7004 failed

**Comment by carnage702** [comment]
how are you even getting a message? are you debugging nintendont?
Ps3 controller doesnt work trough BT  so you always need its cable connected at all times, also only 1 usb controller at a time.

1-Make sure you have the latest nintendont version, as off wrinting this the number is 421.
2- make sure native controller setting on nintendont settings is set to off.
3-make sure no other usb controller is connected at the same time as the PS3 one.
4-Delete any controller.ini that you might have on the root of your SD/USB
5-connect your ps3 controller to any usb port.
6- once the game starts press the home button to sinc it
7-profit?

**Comment by onlynight** [comment]
@carnage702 i get the error message by HIDTest.dol. it always shows connect error when i start HIDTest to test my ps3 controller. whatever i press any button, it always PS3-init...faild.

and i download the latest version of nintendont; set the native controller off;1 usb port for HDD and 1 usb port for ps3 controller;I have tried both with and without configuration file configuration file;

And i found something wrong, when ngc game start i press the ps home button, after that the HDD couldnt load, and after about 10s the wii auto shut down. **CRASHED**.

And the other situation, after start nintendont i connect my ps3 controller(which didn't work too), and start a game, i found it couldn't read HDD and stuck.


And the other problem, i use the unofficial wiimote controller. when i start ngc game by nintendont, the 4th led is on and i pressed any button it doesn't work.but in nintendont game select interface  the wiimote works well.


Thank you for answer my question.

**Comment by carnage702** [comment]
well is your ps3 controller official? does the usb cable transfers data  or just a power?maybe try another cable?

if the hidtest program cant read your controller then nintendont wont read it if your ps3 controller is official try connecting it to the ps3 to see if something got  stuck in the code then delete any ninconfig,controller ini on the root of your hdd/sd, maybe the controller needs t o be restarted on the ps3 first, but like i said if your controller doesnt work on hid test then it wont work on nintendont for sure.

**Comment by onlynight** [comment]
thanks a lot, i have tried lot of method and it doesn't work.

The truth is that several days ago the ps3 controller was worked, and i decided to change a long usb cable, after that i cant connect my ps3 controller any more with any usb cable.

Last year i use the wiimote(official) and classical pro controller it works fine, i think the fake wiimote(it just cast me ￥40, it just equal to about $7) cause the problem.

With a lot of attempt it doesn't work,so i decide to give up.**Thanks a lot for your hard work on nintendont, that's the best ngc emulator ever over all the platform.**

**Comment by carnage702** [comment]
fake wiimotes dont work in most homebrew programs they basicaly are very hacky and only work on wii games itself  they do very dodgy things that homebrew does like including nintendont.

if you have the official wiimote it will work with the official CC/CCpro no doubt, fake wiimotes are a no go tough.

**Comment by xXCheeseWizardXx** [comment]
Hey guys I know this is way late, but i recently Put nintendont on my wii u and i want to use a ps3 controller. wbut whenever i plug my ps3 controller in my wii u restarts any help??? please??
