### ISSUE TITLE
occisonal inputs on controller

### ISSUE THREAD

**Issue by monkeyman4412** [FIX94/Nintendont#295]
some times there are inputs that i don't make example melee every once in a while I'll attack when I didn't press the attack button, but it doesn't happen too often so its not to game breaking. custom controller of course

**Comment by carnage702** [comment]
well you are using a crappy third party and fix94 to make the controller work had to do  some agreesive code to get the controller comands being readed faster not slower so maybe now it catches some reads that the fake controller randomly sends.

**Comment by monkeyman4412** [comment]
its not one of those fake controllers, its a powera wiiu pro controller,
but I do see what you mean

**Comment by monkeyman4412** [comment]
it appears to be fixed in the newest version thanks
