### ISSUE TITLE
Nintendont crashing when choosing USB my external HDD on latest master

### ISSUE THREAD

**Issue by sellerie98** [FIX94/Nintendont#297]
Sadly, Nintendont does crash when I choose USB in the Nintendont menu. Error codes attached in the picture. This does always happen. I am using Nintendont version 4.421 and FW version 58.24.32, IOS58 rev 6176. It doesnt crash when I try to load a game from the sdcard, but I also dont have any games on it...
![nintendont usb](https://cloud.githubusercontent.com/assets/4631886/17194553/db4e13f6-5458-11e6-9d32-f972f5c01a83.jpg)

**Comment by carnage702** [comment]
wii or wiiu? try deleting controller.ini or ninconfig files that you might have on your hdd/sd root, did the hdd ever worked with nintendont?

**Comment by sellerie98** [comment]
It's one of the very first wii models. Also I installed Nintendont on it for the first time today...
What I know is that it also crashes when trying to access a usb pen drive with some games on it, its exactly the same error message.
This doesnt occur when I chose SDcard, it seems to read it fine...
Also there weren't any "controller.ini" or ninconfig files either on the sd or the hdd or sd root...

**Comment by dq100** [comment]
I have exactly the same Problem with the newest Release.
I'm now using Version 416 as suggested in issue #289

**Comment by carnage702** [comment]
do you have the corret ios58? or some modded one? go to your homebrew channel and press hoem button then on the top right corner it should say your iso58 version, also is your hdd correctly formated to fat32? is it partitioned?

**Comment by dq100** [comment]
I will lookup the ios version later today.
My HDD has two partitions. the first one is fat32, the second ntfs.

**Comment by sellerie98** [comment]
It's formatted to NTFS, but it happened with a usb pen drive formatted to FAT32 aswell.

**Comment by carnage702** [comment]
well  nintendont is fat32 only so an ntfs  hdd will never work at all.
either format it to fat32 or use something else, flashdrives with homebrew in general are a hit and miss and they are very unreliable ever since early wii days homebrew, some work some dont and etc.

**Comment by sellerie98** [comment]
I now copied the gc isos on a second partition formatted with fat32 behind the ntfs one. Nintendont itelf finds it and reads the games properly, the problem now is, that none of the USBloaders  are able to find my gc games on both of the partitions, even though at least the latest version of usbloader gx should be able to use Nintendont...

**Comment by carnage702** [comment]
i know usbloader has a checklist of stuff that appears and i know gc games are on the checklist but tbh i have no idea if any usb loader can read 2 diferent partitions at the same time but check if the gc isos are checked to be viewed.

**Comment by sellerie98** [comment]
I was just able to run a game with USB loader gx off my ntfs partition and run it with Nintendont. Also, GX eithers supports both usb ports and multiple partitions, according to settings...

**Comment by sellerie98** [comment]
My main fault was not reading everything properly and not looking into settings properly, it works now, thanks for taking you time!
