### ISSUE TITLE
2 controls adapter ps2 to usb in nintendont?

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#299]
Recently I took my nephew with this my two PS2 controls adapter usb players I have about 15 years and I wonder if they would have the .ini to use it with the nintendont, and if it would be possible to use both controls the adapter?

<a href="https://2.bp.blogspot.com/-TbWKRXJIAac/V5zqG0_3BtI/AAAAAAAAC2s/uFOTiz40VXU_7wD7Q3X5zc7D_Q6tBLsagCLcB/s1600/2016-07-20%252B15.11.07.jpg" imageanchor="1" ><img border="0" src="https://2.bp.blogspot.com/-TbWKRXJIAac/V5zqG0_3BtI/AAAAAAAAC2s/uFOTiz40VXU_7wD7Q3X5zc7D_Q6tBLsagCLcB/s320/2016-07-20%252B15.11.07.jpg" width="320" height="188" /></a>

**Comment by carnage702** [comment]
well you would need to use hid test to see if it works and then you would need to learn how to create a controller ini file by yourself, nintendont does have some inis codded in into memory for some ps2 adapters maybe it matches some of those? did you actualy tryed it in nintendont menu or ingame?

**Comment by spielvan** [comment]
I was with him loaned received a few days ago, where I get this program to test his compatibility? because I believe that this is my equal that blue adapter that is in format "V" would be very interesting to be able to put it to fduncionar, especially for those who have wii without input control gc.

**Comment by carnage702** [comment]
first try just to plug it in and see if it works if it doesnt you need to find the program called hidtest wich i dont have a link unfortunely.

**Comment by spielvan** [comment]
I did a test with the test hid, and this guy gave screen and when tightening the ps2 control buttons connected in the first adapter port changes of these numbers well below the screen.

<a href="https://4.bp.blogspot.com/-zLjhV3imXBk/V50HxW-fIaI/AAAAAAAAC28/njGkGt0TCzohHMH3_M35PKCe1ShN97SuwCLcB/s1600/2016-07-30%252B17.02.44.jpg" imageanchor="1" ><img border="0" src="https://4.bp.blogspot.com/-zLjhV3imXBk/V50HxW-fIaI/AAAAAAAAC28/njGkGt0TCzohHMH3_M35PKCe1ShN97SuwCLcB/s320/2016-07-30%252B17.02.44.jpg" width="320" height="188" /></a>

**Comment by carnage702** [comment]
like it says on the screen if when you hit the ps2 controller buttons the values change then its compatible if values dont change when hitting buttons then its not compatible.

i dont know how to make a controller ini maybe post on this thread on gba temp will get you help but remenber if buttons dont chnage when hitting the ps2 controller buttons then it isnt compatible.

https://gbatemp.net/threads/nintendont-controller-configurations.355035/page-32

**Comment by spielvan** [comment]
Thank you'll give it a try there to see if I can.
