### ISSUE TITLE
Black Screen After Loading GameCube Game

### ISSUE THREAD

**Issue by JonisNR1** [FIX94/Nintendont#302]
When I go to load an ISO from my USB or SD, it leads me to a black screen. What do I need to do?

-I'm using Nintendont Loader v4.422.
-The Wii remains on but the screen is black.

**Comment by carnage702** [comment]
take a picture of your nintendont settings, also you have a normal hombrew channel and normal ios58 with no mods?

**Comment by JonisNR1** [comment]
I didn't download ios58 .. but I'll do it now.

**Comment by carnage702** [comment]
no dont do it ... nintendont uses the original ios58 not those old mods that are outdated.

**Comment by JonisNR1** [comment]
![image](https://cloud.githubusercontent.com/assets/20956727/17569407/0a52eaec-5f16-11e6-836c-afc02027e86a.jpeg)
![image](https://cloud.githubusercontent.com/assets/20956727/17569408/0a540094-5f16-11e6-8f47-4bcbbd88158f.jpeg)

**Comment by JonisNR1** [comment]
Okay I didn't download it

**Comment by JonisNR1** [comment]
Update: I tried loading "Animal Crossing" and after being on the black screen for about a minute or two, the game loaded. I'm attempting to load "Cel Damage", but it is stuck on the black screen.

The games are both compatible for Nintendont, according to the compatibility website.

**Comment by carnage702** [comment]
there is something very off with your system, nintendont loads games instantly there is no load time tough so something is very off.

im guessing its your devices maybe both usb and sd card are extremely slow devices?

**Comment by JonisNR1** [comment]
I loaded games fine on USB Loader GX. I wanted to see if I could download GameCube games on my SD card. So I tried out Nintendont using both my SD card games and USB games.. but it doesn't work the way the videos of Nintendont show.

**Comment by carnage702** [comment]
yeah maybe its becuase of your formating? do you use  fat32 32k formating? nintendont works like the videos zero start up times the only load times are the ones on the games themselves, it boots teh games in less than 2 seconds for everyone.

**Comment by JonisNR1** [comment]
I formatted both the USB and the SD card fat32 .. not sure if it's 32k though. Let me check and I'll get back to you. Should I just reformat them again?

**Comment by carnage702** [comment]
well no idea, it cant hurt.

**Comment by JonisNR1** [comment]
Well I reformatted both the SD card and the USB and the same has happened.. I formatted each fat32 with 32k.

**Comment by carnage702** [comment]
what is the speed of your sd card? or even usb device are they old devices?

**Comment by carnage702** [comment]
there isnt much we can do you said animal crossing loaded but animal crossing is the smallest gc game ever with a mere 24mb and even then you said it took 2 minutes to load lol, something is very wrong on your side not usre if its your wii or your devices becuase nintendont takes 2 seconds to start any game on the gc and i mean any for everyone, this is the first time i ever saw this issue, you sure you havent installed some  wierd cios or something?

**Comment by JonisNR1** [comment]
How can I check if I downloaded cios?

**Comment by carnage702** [comment]
no idea tbh but a syscheck app for homebrew shows all your cios and ios, but you never replyed to my question is what is your sd card class?

**Comment by JonisNR1** [comment]
I have a SanDisk 16 GB. I'm not sure how to check its speed though..

**Comment by carnage702** [comment]
sd cards have classes class 2,3,4,5,6... it usualy says so in the front of the card.

**Comment by JonisNR1** [comment]
It says 4

**Comment by carnage702** [comment]
that is indeed a very low speed sd card its the minimum aceptable for nintendont so yeah the only thing preventing your games from working is if your wii has some cios that is causing issue, google syscheck wii app and find a link and use it.

**Comment by JonisNR1** [comment]
I found my solution. Apparently some games work on the SD card while some work on the USB. So the games that didn't work on the USB, I moved them to the SD card. Thanks for your help! :)

**Comment by carnage702** [comment]
lol there is something very off on your setup tough.
