### ISSUE TITLE
Unable to compile on Windows 10

### ISSUE THREAD

**Issue by athairus** [FIX94/Nintendont#304]
OS: Windows 10 x64 Build 10586
devkitPPC: 27

@FIX94 or anyone else who regularly compiles this, can you tell me about your dev environment so I can replicate it?

I start the build like this:
```
athairus@athairus-mk2 ~/Nintendont
$ cmd
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\devkitPro\msys\home\athairus\Nintendont>Build.bat
```

The problem is make.exe crashes with an unhandled exception:
```
[...snip...]
Building FatFS libraries

rm -f *-arm.a *-arm.o *-arm.d
CC      ff-arm.o
CC      ff_utf8-arm.o
CC      option/ccsbcs-arm.o
AR      libfatfs-arm.a
rm -f *-ppc.a *-ppc.o *-ppc.d
CC      ff-ppc.o
      0 [main] make 19476 handle_exceptions: Exception: STATUS_ACCESS_VIOLATION
    637 [main] make 19476 open_stackdumpfile: Dumping stack trace to make.exe.stackdump
```

[This topic](http://devkitpro.org/viewtopic.php?f=3&t=2182) suggests that it might be that Windows Defender's the culprit. Disabling real-time protection and adding `C:\devkitpro` as an exception did not fix the issue. Any ideas? I'll keep looking into it and maybe try a Linux VM later.

**Comment by FIX94** [comment]
I'm on windows 10 x64 build 10586 and use devkitppc r27 and devkitarm r45, I have no clue why you experience problems to be honest, never had any myself with devkitpro in general... maybe your PATH variable isnt set up properly or something and some other files get used? on windows you can use the "where" command to check that, it should come out like this with a standard devkitpro setup:
C:\>where make
c:\devkitPro\msys\bin\make.exe
C:\>where powerpc-eabi-gcc
C:\devkitPro\devkitPPC\bin\powerpc-eabi-gcc.exe

**Comment by athairus** [comment]
Nothing in my path that's abnormal, except the folder for devkitPPC isn't in my PATH so `powerpc-eabi-gcc.exe` won't get found. The file does exist where you have it though.

**Comment by athairus** [comment]
Something I've noticed is the environment variables like `DEVKITPPC` use Unix paths instead of Windows paths. Is that how it's like on your box?

**Comment by FIX94** [comment]
thats normal yea.

**Comment by athairus** [comment]
Adding that to PATH got me past that stage. Next error is:
```
Building Nintendont Codehandler

codehandler.s
codehandleronly.s
Could Not Find C:\devkitPro\msys\home\athairus\Nintendont\kernel\bin2h\codehandler.bin
The system cannot find the file specified.
The system cannot find the file specified.
```

**Comment by FIX94** [comment]
can you remove the @echo off from the build.bat in codehandler? this doesnt give enough info.

**Comment by athairus** [comment]
```
C:\devkitPro\msys\home\athairus\Nintendont\fatfs>cd ..\codehandler

C:\devkitPro\msys\home\athairus\Nintendont\codehandler>echo.


C:\devkitPro\msys\home\athairus\Nintendont\codehandler>echo Building Nintendont Codehandler
Building Nintendont Codehandler

C:\devkitPro\msys\home\athairus\Nintendont\codehandler>echo.


C:\devkitPro\msys\home\athairus\Nintendont\codehandler>call build.bat

C:\devkitPro\msys\home\athairus\Nintendont\codehandler>setlocal

C:\devkitPro\msys\home\athairus\Nintendont\codehandler>set devpath=C:\devkitPro\devkitPPC\

C:\devkitPro\msys\home\athairus\Nintendont\codehandler>set devpath=::\devkitPro\devkitPPC\

C:\devkitPro\msys\home\athairus\Nintendont\codehandler>echo codehandler.s
codehandler.s

C:\devkitPro\msys\home\athairus\Nintendont\codehandler>echo codehandleronly.s
codehandleronly.s

C:\devkitPro\msys\home\athairus\Nintendont\codehandler>cd ../kernel/bin2h

C:\devkitPro\msys\home\athairus\Nintendont\kernel\bin2h>bin2h codehandler.bin

C:\devkitPro\msys\home\athairus\Nintendont\kernel\bin2h>bin2h codehandleronly.bin

C:\devkitPro\msys\home\athairus\Nintendont\kernel\bin2h>del /f codehandler.bin codehandleronly.bin
Could Not Find C:\devkitPro\msys\home\athairus\Nintendont\kernel\bin2h\codehandler.bin

C:\devkitPro\msys\home\athairus\Nintendont\kernel\bin2h>move /Y codehandler.h ..  1>nul
The system cannot find the file specified.

C:\devkitPro\msys\home\athairus\Nintendont\kernel\bin2h>move /Y codehandleronly.h ..  1>nul
The system cannot find the file specified.

```

**Comment by FIX94** [comment]
that is missing tons of calls, if you look into the batch yourself you'll see what I mean, how do you run the build.bat? I just double click it and it does a whole lot more...

**Comment by FIX94** [comment]
also why is DEVKITPPC not /c/devkitPro/devkitPPC/ anymore? it should still be that...

**Comment by athairus** [comment]
I think we're zeroing in on the problem. I've removed all the additions to PATH that the devkitpro installer made because I have other installs of msys and I want none of them to interfere with the vanilla command prompt. I'll try writing a quick batch file that sets the environment more properly then calls your build to see what happens.

**Comment by FIX94** [comment]
as you can see the devpath it sets because of that difference is invalid.

**Comment by athairus** [comment]
I assume the issue is that msys mangles (tries to fix) environment variables which is breaking your assumptions about the environment (I called cmd from sh to run the bat). I don't know why the devkitPro devs thought it'd be a good idea to store the variables like that.

Anyway, it builds clean now. Thanks for the help!

**Comment by DankRank** [comment]
@atharius
Protip: if you want to build it from sh, you can use `windows=1 ./build.sh` (all in one line)
