### ISSUE TITLE
Multiple games crashing with buzzing audio

### ISSUE THREAD

**Issue by SamMartins** [FIX94/Nintendont#305]
Nintendont version 4.422 loading through USB on a 1TB TOURO hard drive
Tried running both standalone and through USBLoader GX
Occurs during transitions into rooms or between cutscenes and gameplay
Tried with read speed limit ON and OFF, no change

**Comment by carnage702** [comment]
first take a picture of your nintendont settings, second  are your isos compressed? some compress tools break some games your always best using full 1.35gb isos with md5 checked on redump.

**Comment by SamMartins** [comment]
https://drive.google.com/open?id=0B3wnENHmy7rmY05ibG1wQnJpZ2M

No the isos are all uncompressed. The games in question are Skies of Arcadia and Wind Waker. So far each have segments that I have to skip over by transferring saves and using Dolphin

**Comment by carnage702** [comment]
this is a first i never heard anyone with similar issues are you using a wii or wiiu?
Also any chance of you checking for sure if the MD5 matches redump? to take out the issue of being bad dumps?

**Comment by SamMartins** [comment]
Using a wii v4.3u, the original white one, with a mem card and gamecube controller.
3E7FA5033C4A2704434FB6BA98195ECD, for Skies of Arcadia
D8E4D45AF2032A081A0F446384E9261B, for Wind Waker
Both are the correct MD5s listed by redump.org

**Comment by carnage702** [comment]
the only thing i can say is its your hdd that has compat issues tbh, or maybe you even have a corrupt nintendont.dol? or meta xml or ninconfig,controller.ini.

so first try deleting your nintendont doland meta xml and redownload it again and delete from your sd/usb wherever nintendont is and delete any controller.ini,ninconfig files  and try if the issue is still there try another usb device.

**Comment by SamMartins** [comment]
Deleted and reinstalled nintendont.
With iso on USB drive, no change
With iso on SD card, same problem
With iso on USB thumbstick, same thing.

It seems like its a Nintendont issue, but I'll test out DIOS-MIOS to see if I get the same problem.

**Comment by carnage702** [comment]
it isnt a nintendont issue becuase for everyone else it works fine, you didint installed any custom color homebrew channel or custom animation or anything like that?

**Comment by SamMartins** [comment]
Nope no custom things for me, I have a pretty basic setup. 
cios      :d2x v10 installed for wii games
cMIOS  :DIOS MIOS v2.11 (from before the Nintendont days)
Apps     : USBLoader GX, vbagx, fceugx, snes9xgx, Nintendont, and WAD manager

**Comment by SamMartins** [comment]
Same problem with DIOS MIOS, it must be some sort of internal problem with the wii itself. Not sure how to fix it though, any thoughts?

**Comment by FIX94** [comment]
sounds like some form of RAM or even worse hardware damage, wii games will probably crash too so that wii is probably done for.

**Comment by carnage702** [comment]
considering that its when the entering new areas or after loading stuff is probably like fix94 said its probably when nintendont clears the ram for more ram or something or some part of the ram is damaged and such and crashes on being cleared afew times who knows.
