### ISSUE TITLE
[Request] Tales of Symphonia's PAL release won't allow forcing 60Hz, but AR codes exist that allow it- any chance these could be integrated?

### ISSUE THREAD

**Issue by StateOfException** [FIX94/Nintendont#307]
The PAL release is notable for having a different, significantly more readable in-game font than the NTSC-U release, as well as supporting multiple languages- the only downside it has is the lack of a native 60Hz mode. Just seems a shame that the definitive version of the game can't be brought up to standard.

Nintendont doesn't manage to force the mode with its built-in patching functionality, but it looks like it's possible- at least, going by an AR code found here:

http://www.gc-forever.com/forums/viewtopic.php?t=2137

```
Enable 60Hz Mode [Ralf]
C21064EC 00000002
3FE0802B 63FF188C
93ED8670 00000000
04070A74 38C0000F
04070AC4 3804188C
04070B00 38C0000F
022B1892 000001C1
022B1894 000001C8
022B1898 0000000F
022B189C 000001C8
```

Just wondering- would it be possible to integrate this as a game-specific hack, as with Skies of Arcadia's Force Widescreen support?

**Comment by carnage702** [comment]
what version of nintendont are you using? you sure forcing videomode pal60 or even force ntsc videomode doesnt work?

**Comment by StateOfException** [comment]
>what version of nintendont are you using?

The most recent release- 4.422, I think? I updated the .dol today (manually, via GitHub) to doublecheck if the latest revision altered anything.

>you sure forcing videomode pal60 or even force ntsc videomode doesnt work?

Yes, I'm certain. Forcing PAL60 prompts the game to start with a black screen rendered at 480i/60, but it flips back to 576i/50 as soon as it begins displaying anything.

Forcing NTSC just results in a black screen- the game's running fine in the background, given that the intro music's audible if you wait thirty seconds or so, but there's seemingly no video ouput. Nintendont's built-in patcher just doesn't work.

**Comment by carnage702** [comment]
does the cheat code work on nintendont? since some cheats dont, so i wonder if that 60hz cheat works at all to begin with.
