### ISSUE TITLE
Controllers don't work when updating from v3

### ISSUE THREAD

**Issue by sensi277** [FIX94/Nintendont#308]
I had updated Nintendont on my Wii U to v4 and all my controllers (except Wiimote) stopped working. Updating controllers.zip fixed the issue. Here's my suggested solution: when Nintendont is updated, have controllers.zip be updated as well.

**Comment by carnage702** [comment]
what? this makes zero sence, nintendont for a long time had all the controller inis that are on the controller.zip file hardcoded into memory so you dont even need the controller.zip stuff you can delete them just fine,latest nintendont is version 422 and unless you had native turned ON, or maxpads set to 1 or something and were trying to do multiplayer, all controller work without controller.zip or controller folders you can delete all of those at will just try it and you will see it makes no diference.
