### ISSUE TITLE
Ps3 Controller

### ISSUE THREAD

**Issue by xXCheeseWizardXx** [FIX94/Nintendont#309]
Hey guys so recently I Installed nintendont on my wii u and every time i try to go to the regular wii menu with my ps3 controller plugged in my wii u restarts. i have tried to unplug it and wait till i load up nintendont, but it still resets and help? please? thank you. also how to i download any of the controller .ini folders?? any help would be greatly appreciated

**Comment by xXCheeseWizardXx** [comment]
is there a certain port i am suppose to plug it into? also i am getting a GC adapter pretty soon do i need anything special for it?

i am running v4.422 (Wii U)

**Comment by carnage702** [comment]
Probably have a corrupt controller.ini

delete any ninconfig.bin,controller.ini or font files you might have on the root of your usb and SD, also any usb port works.

**Comment by xXCheeseWizardXx** [comment]
i did that... everytime i plug my ps3 controller in it always restarts to my wii u and turns it off. i have tried to plug my ps3 controller in after it got to the wii menu and before i even turned on my wii u.

all i have on the roots of my sd card and usb are 
apps > Nintendont > boot.dol
                                   icon
                                   meta
games > Mario Kart - Double Dash!! (USA) > game
           > Pac-Man World 2 (USA) > game
saves > GM4E
         >GP2E

this is for my usb my sd card has the same folders except differnt games

**Comment by xXCheeseWizardXx** [comment]
is there a certain file im missing?

**Comment by carnage702** [comment]
well try having only either usb deive or SD card your probably confusing nintendont on having games on SD and usb at the same time try with only usb connected and sd card removed.

**Comment by xXCheeseWizardXx** [comment]
Well I tried it it worked but it crashed as the game loaded up and now every time I try it again it just resets back to the wii menu

**Comment by carnage702** [comment]
are you sure you dont have any controller ini on the root of the usb/sd? if no then it has to be an issue with your controller or wii.

**Comment by xXCheeseWizardXx** [comment]
I've gone through and deleted every controller.ini file I had on my SD card and usb. Is there a certain cord for the controller I am suppose to use? For now I will just be using my SD card. So I unplugged everything except the controller and took out the SD card it loaded up till I got to the homebrew Channel when I had to put in my SD card to load up nintendont and then it was working good tI'll I went to a game,  also I have a wii classic controller which I use to load up the games and what not could that be the problem I'm trying to get it so I can play 2 players

**Comment by xXCheeseWizardXx** [comment]
But I am trying it again now and it won't even let me load up the wii menu. It told me I have to plug in any usb items before u turn on my wii u so that was probably the reason why it kept resetting but now it just turns off when I try to get to the wii menu with just the ps3 controller plugged in

**Comment by carnage702** [comment]
if the wiiu says that your controlller is somehow being readed as a storage device instead of a controller tahts why the crash

reset your controller  see how here http://ccm.net/faq/35811-playstation-3-how-to-reset-your-controller

**Comment by Calistex** [comment]
This issue still persists on the Wii even in the latest version, resetting the controller solved it, thank you so much.
