### ISSUE TITLE
kenobiwii.bin no longer available

### ISSUE THREAD

**Issue by iruleuall4** [FIX94/Nintendont#312]
Does anyone have a backup of the necessary kenobiwii.bin file needed to run ocarina codes for backups of Wii games? The link that every site on the internet links to (http://sneeky-compiler.googlecode.com/files/kenobiwii.bin) is dead.

Any help on this matter is greatly appreciated.

**Comment by aznlilchino103** [comment]
You actually don't need "kenobiwii.bin" to use Ocarina codes. I used USBLoaderGX v3.1 to load Nintendont to then load my GC games.

**Comment by EspoTek** [comment]
https://code.google.com/archive/p/sneeky-compiler/downloads

Found it.
