### ISSUE TITLE
Nintendont compatibility with NEEK environments

### ISSUE THREAD

**Issue by NokonokoKoopa** [FIX94/Nintendont#313]
Hi
There is a issue when Nintendont is executed in a neek environment (uneek+DI specifically) on Wii. Nintendont is in the apps/nintendont folder on an SD card and a forwarder has been installed on the uneek nand. The nand was created with Modmii and is running System Menu 4.3U. When I run Nintendont using the forwarder, Nintendont runs but gets stuck at the "Initializing IOS58" screen and goes no further. As the System Menu is 4.3U I presume IOS58 is installed on the nand.

**Comment by carnage702** [comment]
Acording to fix94 nintendont is not compatible with neek at all.
