### ISSUE TITLE
Mario Kart Double Dash lagging in the intro

### ISSUE THREAD

**Issue by dylpickles2001** [FIX94/Nintendont#315]
Everytime I watch the intro of Mario Kart Double Dash, some parts lag. I am using Nintendont on my wii u and playing from a usb flash drive.

**Comment by carnage702** [comment]
is your iso a full 1:1 iso with md5 checked on redump? are you forcing settings?is your usb fast enough?

**Comment by dylpickles2001** [comment]
I now have a usb hard drive and runs perfectly.
