### ISSUE TITLE
How Can I Configure Buttons?

### ISSUE THREAD

**Issue by Markeron** [FIX94/Nintendont#318]
There are some default sets but i doesn't fit very well for the games I'd like to play I'd like to create my own sets, so how can I map each button on wiimote&nunchuck individually?

**Comment by Markeron** [comment]
Up

**Comment by carnage702** [comment]
you would need to change nintendont source code and recompile it, preety tedious and actualy hard to do, so my best advice is buy a gc controller or a CC, its miles better than any wiimote / nunchuck setup.
