### ISSUE TITLE
General Instability and Crashes, Controller Issues...

### ISSUE THREAD

**Issue by sensi277** [FIX94/Nintendont#319]
Since I updated to v4 of Nintendont, I've been having all sorts of issues, even on the latest version. Nintendont crashing both in loader and in-game and controllers working inconsistently (if at all) are just some of the issues I've been running into. I've tried deleting and updating controller configs, nothing. Running Nintendont from USB, nothing. Using different controllers, nothing. Any help, or at least a link to where I can download a pre-v4 version of nintendont, would be appreciated.

**Comment by carnage702** [comment]
take a picture of your nintendont settings.

**Comment by sensi277** [comment]
Can't. Going into the Nintendont game selection menu seems to like to crash my Wii U today.

**Comment by sensi277** [comment]
Off the top of my head, I think I had Force Progressive, Force Widescreen, Wii U Widescreen, and Memory Card emulation enabled. All other settings are default.

**Comment by carnage702** [comment]
if the app is crashing then i bet you got a corrupted dol or meta or something along those lines, just delete your nintendont apps folder and any ninconfig/controller ini you have on the root of the device and redownload  preferably manualy all the apps files back to your sd/hdd.

**Comment by sensi277** [comment]
Just did that, re-downloaded everything and deleted all config files. Now the system sits at a blank screen when a game is booted, and pressing any button on a GameCube controller connected via an adapter force reboots the console into Wii U mode.

**Comment by GB-CG** [comment]
This may sound weird, but have tried deleting the homebrew data save in the vWii settings? It's a cache file and it won't delete the homebrew channel.

**Comment by sensi277** [comment]
Holy crap that worked! How did you know that might solve the problem? What even was the problem, do you think?

**Comment by GB-CG** [comment]
I wonder if the Homebrew cache file is what causes problems for a lot of people here.
So if in doubt, try deleting the (1 block) Homebrew channel save file.

Anyway, when I used to use custom backgrounds for my homebrew Wii, I got fed up with them and wanted to delete them, but didn't know how. So when I was cleaning my Wii internal save drive, I found the HB icon and deleted it; and hey presto, it went back to normal. Guess it just refreshed itself.

**Comment by sensi277** [comment]
My problems are back. Doesn't look like deleting the cache actually fixed anything.

**Comment by sensi277** [comment]
Now I have this new bug: GameCube controllers connected via an adapter crash Nintendont if any of the buttons on the controller is pressed.

**Comment by carnage702** [comment]
it seems you have a controller ini on your usb/sd root that is corrupted jsut delete it.

**Comment by sensi277** [comment]
I've already deleted all my controller config files on both the SD card and USB drive twice. The only USB devices I have connected are my GC controller adapter and a USB hard drive.

**Comment by carnage702** [comment]
not sure what to tell you then for everyone else everything just works, can you take a picture of your nintendont settings? also redeleting the homebrew channel data again didint work?

**Comment by sensi277** [comment]
Deleting homebrew channel data again did nothing. Here's a picture of my nintendont settings: http://imgur.com/a/GBU1d

Is there any sort of extra software stuff needed to get nintendont to run? I have a largely unmodified vWii on my Wii U. Are there any IOSs I need to install to get nintendont to work?

**Comment by carnage702** [comment]
turn off, force progressive and force widescreen since this settings can cause issues on some games you can leave force wiiu widescreen on since this doesnt affect compat.

if the issue still happens then its your hdd that is to blame imo, try using another hdd with its own power supply or y cable or a big sd card, im guessing your hdd might have some issues with nintendont if those 2 settings turned off dont do anything for you and your isos are md5 checked its definitevely your hdd fault.

Also why do you have multi on with 251 blocks? it will fill up rather qucikly, i alays choose a single memory card per game 251 blocks just so i never loose all my saves incase of corruption or some other thing.

**Comment by sensi277** [comment]
I'll take a look into seeing if my hard drive is the issue.

> Also why do you have multi on with 251 blocks? it will fill up rather qucikly, i alays choose a single memory card per game 251 blocks just so i never loose all my saves incase of corruption or some other thing.

I wanted to be able to transfer my game saves from my old GC memory card over to Nintendont. It had been working pretty well until Nintendont stopped working...

**Comment by sensi277** [comment]
Alright, so a month later, I wiped my HDD and SD card, put all my games and nintendont back on, and still controllers don't work reliably if at all. I've tried downgrading nintendont, using different controllers, and I still can't get it to work reliably.

**Comment by carnage702** [comment]
what do you have connected to the usb ports?

try this besides the hdd remove everything and even try using another usb port nintendont doesnt care wich port it is, then use a Bt controllers like CC,wiiupro or even wiimote+nunchuck

if it still crashes with bt controllers and the hdd  only connected something is damaged  in  your wii.

**Comment by sensi277** [comment]
Alright, just wanted to update you guys again. It was a difficult issue to fix, because there didn't seem to be anything wrong with the hardware, all the controllers were working in SSB/WiiU, the hard drive was working fine too, but at last it occurred to me nobody else seemed to be having the same issues, and the software was all fine, so it must have had something to do with my hardware configuration. So anyways, ditching the USB hub I was using as well as the USB hard drive and running the games off the SD card gave more power to the GameCube controller adapter, meaning it works more reliably now and my problem appears to be fixed. Not a software issue, closing.

**Comment by carnage702** [comment]
you never told us you were using an usb hub... i would tell you right off the bat taht nintendont was not coded to support hubs and they can cause all sort of issues.

**Comment by sensi277** [comment]
I should tell you that it wasn't a problem with the USB hub or the configuration with the hub, connecting both the GameCube controller adapter and the USB drive directly to the Wii U also had the same issue.

**Comment by carnage702** [comment]
the wiiu usbports are underpowered if your hdd isnt self powered you need an y cable same way the wiiu gc adapter needs boh usbports connected, and no the wiiu does offer enough power as long as your hddhas its own power supply or y cable wich you can connect to both back ports for example and the wiiu gc adapter to both front ports.

**Comment by sensi277** [comment]
The only y-cable I had was a miniUSB, and my hard drive was microUSB. By using the USB hub, I could connect the y-cable to that and all my devices could get enough power (or so I thought). In reality, the USB drive worked (and you're right, it was not externally powered), and the GC controller adapter worked (at least in SSB), but some combination of the USB hub, the hard drive and the GC controller adapter meant that one of those things was not getting power when it needed it.

**Comment by carnage702** [comment]
like i told you its basic common knoledge you need a y cable or an hdd with its own power supply for wiiu, even nintendo has it on its on official  website, they know they  messed up on the usb ports.

http://en-americas-support.nintendo.com/app/answers/detail/a_id/1359/~/what-external-storage-devices-can-be-used-with-wii-u%3F

"To ensure maximum performance between your Wii U and an external storage device, we recommend using a hard-disc drive (HDD) with a dedicated power source (i.e., using an A/C adapter). Due to the wide range of external storage devices, usability and performance will vary."


So yeah you either use an hdd with its own power supply or get an y cable, i can garantee you that your hdd will work perfectly with an y cable or its own ac adapter.
