### ISSUE TITLE
Wiimote + Nunchuck Not Working

### ISSUE THREAD

**Issue by 26lor** [FIX94/Nintendont#320]
I have the wiimote with the nunchuck but it only works on the nintendont menu, then stops working when I load a game. None of the buttons do anything when I load the games. Please help﻿

**Comment by GB-CG** [comment]
Wiimote + Nunchuck is not recommended for Nintendont. Why not use a Gamecube controller?

**Comment by 26lor** [comment]
@GB-CG  I don't have a Gamecube controller unfortunately.

**Comment by GB-CG** [comment]
Try turning 'Native Control' off?

**Comment by 26lor** [comment]
@GB-CG I've tried that, nothing in the settings seem to make a difference

**Comment by GB-CG** [comment]
Are you using v4.423? and your wiimote + nunchuck are 1st party, right? and nothing else is plugged in? I've tested Mario Sunshine with my official Wiimote + Nunchuck and it's working (except for lack of inputs to squirt water, obviously) Otherwise you can try a classic controller, WiiU pro controller or look somewhere for a GC controller (Official ones are recommended)

**Comment by 26lor** [comment]
@GB-CG I'm using v4.423, as for the wiimote + nunchuck, they came with the pre-owned wii I bought from Gamestop so they should be official. Nothing else is plugged into my wii. Maybe my wiimote isn't official? I'll just have to try to find a different controller. Thank you regardless

**Comment by GB-CG** [comment]
Does it say 'RVL-003' near the Input socket of the Wiimote?

**Comment by 26lor** [comment]
@GB-CG Yep

**Comment by GB-CG** [comment]
Hmm. I think it's best if you find yourself a official GC pad to be honest.

**Comment by carnage702** [comment]
im guessing wiimote or nunchuck arent official.

**Comment by 26lor** [comment]
@carnage702 How can I tell if its official or not?

**Comment by carnage702** [comment]
Look at the screws. if the small screws heads are tri wing screw heads instead of the normal 4 then its official since nintendo always uses those damend triwing screws.

**Comment by darkto62** [comment]
when wiimote is not from nintendo it not work for Nintendont, i have both wiimotes
