### ISSUE TITLE
Problem with setting memcard emulation on vWii (Exception DSI)

### ISSUE THREAD

**Issue by fepvp** [FIX94/Nintendont#321]
* Running Nintendont from HBC on vWii.
* Running latest Nintendont version
* Game: Paper Mario TTYD
* Wii U and game are both NA versions
* The game was on the SD card (also tried on a USB)
* The game works fine when I don't change the options, but as soon as I click the Home button after trying to change the settings to enable Memcard emulation, it presents this screen:

![image](https://cloud.githubusercontent.com/assets/20618761/19221982/e3715dd4-8e02-11e6-8e97-864f383ea7f7.png)

Things I've tried:
* Older Nintendont version (4.416,4.417,4.418)
* Trying the game on both USB and SD card (both FAT32 formatted and USB is MBR partitioned)
* Reformatting both the USB and SD cards to wipe hidden files and caches
* Deleting Homebrew Channel save data from vWii Disk Management.

**Comment by carnage702** [comment]
first take a picture of your nintendont settings.

does your hdd have its own power supply?
is your sd card unlocked? and the speed class is?

**Comment by fepvp** [comment]
Thanks for your reply @carnage702.

Attached is a picture of my nintendont settings:
![image](https://cloud.githubusercontent.com/assets/20618761/19223375/e69451f4-8e22-11e6-8ea2-f1d3b7e40aae.png)

The 'Memcard Emulation' works when it is set to Off, but then when I set it to On and then press the Home button, it shows the error screen above.

* My USB isn't a HDD, it's just a regular USB stick so it doesn't need its own power supply.
* The SD card is unlocked (the switch on the left side is in the up position and Nintendont has definitely written some cache files to it before). It's a standard 2GB SD card (this one: https://www.amazon.com/gp/product/B000YH5FOK).

I _think_ the first time I tried loading the game on the SD card instead of the USB the save worked (it produced a G8ME.raw in the saves folder) but then on subsequent tries I get this error and haven't been able to fix it using any of the debugging steps above.

**Comment by carnage702** [comment]
always use the latest version 423, also why do you press home? just turn mcemu on then press B and go to the game list and choose the game. by pressing home your exiting nintendont and no settings are saved.

**Comment by fepvp** [comment]
Thanks, pressing B was the problem :) I'll look into upgrading the SD card (I just used it to install HBC so I guess I can look for a bigger one now)

**Comment by GerbilSoft** [comment]
For what it's worth, I can't seem to reproduce this in my CISO test branch (v4.422-CISO-test4), but I did reproduce it on an old version on my SD card. (v3.405-exFAT-test4)

**Comment by carnage702** [comment]
the issue wasnt that, he was pressing home therefore exiting nintendont and i guess is exit was from some sort or fowarder or  wierd homebrew thing, he was never entering the games after setting mcemu to on lol.

**Comment by GerbilSoft** [comment]
Yeah, that's what I tested. Changing a setting and pressing Home instead of B results in a crash. It works fine on my CISO branch, so I'll send a PR once it gets some more testing.
