### ISSUE TITLE
vertical stripes in some games makes them unplayable

### ISSUE THREAD

**Issue by darknesspyro** [FIX94/Nintendont#323]
in some games i experience alot of vertical stripes that ruin the gameplay for me.
in the lord of the rings the third age it is especially bad.
i also experienced it in Prince of Persia warrior within.
i dont know why this happens but it is quite bad and it has nothing to do with the settings of nintendont or the region of the game and my tv is not the source either because every other game works perfectly.
i tried multiple isos of lord of the rings the third age i tried the european one first then i noticed the stripes and after that i tried a US copy of the game and the same thing happens.
i also tried with and without widescreen and i also tried with everything in the default settings.
does anyone know why this happens?
thanks in advance.
DarknessPyro

**Comment by Zetchzie** [comment]
sounds like your gpu is fried

**Comment by GerbilSoft** [comment]
Does this happen if you use the original disc in standard MIOS? (i.e. Disc Channel)

**Comment by carnage702** [comment]
what do you consider default settings? because most people dont know what default is. take a picture of your nintendont settings, after that we can help you.

**Comment by darknesspyro** [comment]
no my GPU is not fried becouse it works 100% correctly with everything else it is only with these two games.
the only settings i did was use memcard emulation and the video width is 702 but it also happens if this is on auto
those two games are the only ones that it happens on but mostly on lord of the rings the third age
i have also put a picture of windwaker to show that everythings okay with it
i have unlock read speed on but even if it is off it happens also so that is not the problem either.
![wp_20161017_20_30_15_pro](https://cloud.githubusercontent.com/assets/22893830/19450535/26128e1c-94aa-11e6-9373-94243e8196c4.jpg)
![wp_20161017_20_38_06_pro](https://cloud.githubusercontent.com/assets/22893830/19450537/261e521a-94aa-11e6-95cf-5aa5ed3a3d90.jpg)
![wp_20161017_20_40_06_pro](https://cloud.githubusercontent.com/assets/22893830/19450536/261a4ef4-94aa-11e6-8134-8f321d73cec1.jpg)

**Comment by carnage702** [comment]
that is far from default ... make width on auto and unlock read speed t off and try again.

**Comment by panicbit** [comment]
Interesting, I saw stripes like these in another game too, but I don't remember which one.

**Comment by darknesspyro** [comment]
if i put it on auto and unlock read speed off it happens aswell i noted that before and i still dont know what those stripes may come out because everything else on all other games works fine that is why i am a little confused.

**Comment by panicbit** [comment]
Ah, it was Prince of Persia Sands of Time

**Comment by carnage702** [comment]
i tryed that game long ago and i didnt notcied anything like that, could be the videomode the game uses or how your tv handles it, prince of persia warrior within works fine for me.

Also for suture reference the width breaks manny games so use it with caution.

is the game onscreen ntsc or pal?

**Comment by darknesspyro** [comment]
right now? onscreen it is pal but i tried both regions and the videomode never failed me also its not my tv either because it handles almost every console without problems and i tried the videomodes aswell but it does the same thing but i put it back on auto again i find it very odd i love the third age and warrior within but it is hard to play with those stripes and i have played more games lately without any problems so it took me by suprise.

**Comment by panicbit** [comment]
The stripes are a lot more subtle in The Sands of Time (I did notice them more on another monitor though).
![img_20161017_205857](https://cloud.githubusercontent.com/assets/628445/19451259/e1a2ca64-94ac-11e6-8967-9e98a6a71c2a.jpg)
![img_20161017_205907](https://cloud.githubusercontent.com/assets/628445/19451268/eb31f1c2-94ac-11e6-894a-d201acb7b602.jpg)

This is the PAL version with default settings of *USB Loader GX* and width set to 120 (whatever that actually corresponds when translated to nintendont).

**Comment by darknesspyro** [comment]
Exactly my problem but if i am in battle with the third age or when i am in light areas such as snow i can barely see because of all the stripes its wierd how this happens huh i tought i might be the only one but this proves me wrong.

**Comment by carnage702** [comment]
if you have dios mios try it on that? to see if hey dont appear?

**Comment by darknesspyro** [comment]
im not a fan of dios mios and have not installed that i just wonder if there is a fix for it on nintendont.

**Comment by carnage702** [comment]
as off now no, its probably a very badly coded vidomode those games use, if it was perfect on dios mios it could be easy to replicate the fix on nintendont if its also like this on dios mios then it would give some trouble, since nintendont is basicaly and overblown wii mode dios mios of some kind.

**Comment by darknesspyro** [comment]
i appreciate the help maybe it is good that i posted this problem here so it could be checked out i hadnt seen it in the forums or anything so i tought i posted my own thread about it.

**Comment by carnage702** [comment]
most people probably saw it and didnt care enough to report it since scan lines arent exactly gamebreaking, i could play the game fine without them bothering me xD.

but yeah probably some very wierd videomode this games use to show stuff on the screen i guess.

**Comment by darknesspyro** [comment]
i dont know hahaha but on these games they are so bad the graphics get also blocky and it makes it very unplayable especially at places with alot of light who knows it might get better in later updates.

**Comment by panicbit** [comment]
Can you provide a screenshot of a scene where it is really bad?

darknesspyro <notifications@github.com> schrieb am Mo., 17. Okt. 2016,
21:34:

**Comment by darknesspyro** [comment]
hmmm then i must travel a bit but i can if you have a while i will travel and take the photo

**Comment by darknesspyro** [comment]
i couldnt enter the place where it happened alot anymore because it was an event but here is another example
![wp_20161017_21_54_59_pro](https://cloud.githubusercontent.com/assets/22893830/19453203/8c0a344a-94b4-11e6-9074-096950975437.jpg)

**Comment by GerbilSoft** [comment]
What is the game ID and MD5/SHA1/etc of the disc image? I'd like to check this out for myself.

Also, disc revision number if possible - this is byte $07 in the header. The loader should probably display the revision number, but I'm not sure how to format it so it doesn't look out of place.

**Comment by darknesspyro** [comment]
The ID is G3AP69 if i use the US version or the PAL version this ID stays the same this is what nintendont shows me i hope this helps.

**Comment by GerbilSoft** [comment]
The US version should be G3AE69. If it's showing G3AP69 for the US version, then something's wrong with your disc image.

I'll check this out once I can get a copy of the game.

**Comment by darknesspyro** [comment]
the wierd thing is i tried it in dolphin too and in nintendont the iso needs to be called "game" i believe so i did that and if i change the name THEN it shows me the PAL ID and if i change it in something else it changes to america and it did that the whole time but either way the stripes happen with both versions.

**Comment by darknesspyro** [comment]
with both the MD5sums it happens and i tried again that happened when it changed to europe and it didnt happen anymore but it still works wierdly

**Comment by darknesspyro** [comment]
i started to just play the game with the stripes even tough they annoy me alot in light areas its just horible and darker areas you see them clearly but its not that noticeble as it was bright i dont know what it could be but it sure is interesting how this happens

**Comment by FIX94** [comment]
sad to say but that is normal for gamecube games, you can also see that happen from real game discs on actual gamecubes. it basically happens because of the video buffer having a different size as the current picture displayed, so the console internally "rescales" the picture to fit, producing those lines in the process because the scaler is pretty bad.
