### ISSUE TITLE
Nintendont funcionando em NTFS

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#326]
De uns tempos pra cá estão tendo relatos de usuários que tem conseguido rodar o nintendont pelo usb loader gx com o hd em ntfs, eu tentei rodar e realmente mostra a capa dos jogos de gc no menu do usb loader gx, mas quando carrego para começar o jogo abre um pop up no usb loader gx informando que o nintendont só funciona em fat 32, , não sei o que posso estar fazendo de errado.

Estou usando ultima versão nintendont, usb loader gx v1262 e um hd externo de 500 gb simple save da HP todo em NTFS.

For some time now are having reports of users who have longer runs nintendont by gx loader usb with hd in ntfs, I tried to run and really shows the cover of gc games on usb menu loader gx, but when I click to start the game opens a pop up on usb loader gx stating that the nintendont only works in fat 32, I do not know what I may be doing wrong.

I am using latest version nintendont, usb loader gx v1262 and an external hd 500gb simple all HP save on NTFS.

**Comment by GerbilSoft** [comment]
Nintendont does not support NTFS. What is supported, however, is a dual-partition FAT32+NTFS setup with GameCube games on the FAT32 partition and everything else on the NTFS partition.

If your HDD is only used for GameCube and Wii, I'd recommend just switching to FAT32 entirely. It gets rid of the headache of managing two partitions. (Wii games larger than 4 GB can be handled as split files, e.g. GAME.wbfs and GAME.wbf1.)
