### ISSUE TITLE
Fire Emblem: Path of Radiance hangs on load of Chapter 3

### ISSUE THREAD

**Issue by maslevin** [FIX94/Nintendont#329]
Using most recent Nintendont on WiiU vWii, I started a new game, played through to Chapter 3 normally.  When you start Chapter 3, the intro movie plays and the screen shows pure white and hangs.  You can repro by loading the attached memory card image, and restarting Chapter 3 from the in-game menu.

Memory card image is attached. [GFEE.raw.zip](https://github.com/FIX94/Nintendont/files/573560/GFEE.raw.zip)

**Comment by carnage702** [comment]
take a picture of your nintendont settings and is your is a full 1.35gb iso with md5 matching redump?

**Comment by maslevin** [comment]
Nintendont settings
![2016-11-05 16 38 25](https://cloud.githubusercontent.com/assets/1467824/20034313/aac85238-a376-11e6-8151-8dbece2a8fd6.jpg)

iso is from TOSEC and is 1459978240 bytes, MD5 = 4098af6d672eeae8749f9da67309c537 matching database value

**Comment by carnage702** [comment]
works fine for me, i even took a picture, i selected restart chaper, then chapter 3 and everything worked preety well.

https://s17.postimg.org/bl0zgvrm7/IMG0342_A.jpg

ii used my wiiu, my hdd and your save file and settings, restarted the game 6 times and everytime i could start chapter 3 normaly.

i remenber this game being time sensitive what hdd/sd card are you using?

**Comment by maslevin** [comment]
I'm running off of a Lexar 128GB 633x SD Card; I tried again this morning after you posted and had no problems starting the save, whereas I got 3 stalls in the same place in a row prior to making the bug report yesterday.

I think I have figured out the cause of the crash.  I was launching from vWii System Menu -> HBC -> aspect_fix (by tueidj) -> HBC -> nintendont -> fire emblem.  Not running aspect_fix in the chain seems to have cleared the issue up entirely.  The prologue and Chapters 1 and 2 were not affected by having this software enabled first but Chapter 3 is.  Just to confirm, after I got it running without aspect_fix, I restarted the game again with aspect_fix enabled and had the stall happen again.

Thanks for checking this out on your side!

**Comment by carnage702** [comment]
i launch from the aspect ratio fix gb channel aswhell, this game is very timing needy so since you are suing an sd card  im guessing sometimes the speed isnt up to par with the request since on  vwii and wii the sd cards speed is pure crap due to the sd card readerm this shouldnt happen with any fast hdd and sorts.
