### ISSUE TITLE
Half pressed button don't work

### ISSUE THREAD

**Issue by suzsuzuki** [FIX94/Nintendont#330]
I have a Wii Classic controller Pro (not official) and a WiiU. I'm trying to play SM Sunshine but can't do the half pressed button trick for run and using the FLUDD at the same time. The mapping seems to be different for me. If i hold L Mario just do the sidestep and I can't run while using the FLUDD instead. Tried with ZL pressed without success, nothing happens.

For me the Wii Controller Pro mapping > Nintendont mapping is:

L > L
R > R
ZR > Z

Is that right? I though from the 1st page information should be ZL > L, ZR > R and R > Z? Right?

Also for reset I need to use L+R+ZR+start (L+R+Z+Start). 

I also have an generic USB controller and can't simulate the half pressed button as well. Can I do this with one of my controllers? Maybe is this a problem with my IOS58?

**Comment by carnage702** [comment]
that is the right for original CC, if your CC isnt original im guessing it reports the same to nintendont as an original CC does codewise, it is identified as such, and cinse the original CC had pressure sensitive triggers no half presses are coded for it.

**Comment by suzsuzuki** [comment]
Make sense. Thanks. Do you know how can i configure it for regular USB controllers?

**Comment by carnage702** [comment]
unfortunely no you have to find someone who know about controller inis maybe try asking for some help on this thread.

https://gbatemp.net/threads/nintendont-controller-configurations.355035/page-32

**Comment by Shadowfox364** [comment]
An Alternative is if you're using a CC Pro controller or Wii U Pro Controller the Left Bumper button will simulate half pressed L or R as long as you also are pressing on the trigger.
