### ISSUE TITLE
Resident Evil Remake Freezes 

### ISSUE THREAD

**Issue by rgreen1221** [FIX94/Nintendont#332]
Hi there, I have a problem with Resident Evil Remake freezing on me when I play the game.

Before you enter the Lab area of the game, the game will ask you to switch from disc 1 to disc 2. Nintendont does its job to switch the disc but upon loading, the game would freeze with a buzzing sound. I try again and it freezes. 

Does anyone know a solution to this problem, I'm using Nintendont Version 3.334 by the way.

Thank you in advance.

**Comment by GerbilSoft** [comment]
Please try the latest version from my CISO branch: https://github.com/GerbilSoft/Nintendont/raw/v4.428/loader/loader.dol

**Comment by carnage702** [comment]
First-you are using an ancient version of nintendont to begin with, almost 100 revs behind, the latest version officialy is 4.425.

Second- is your iso md5 checked with redump?

third- take a picture of your nintendont settings.

**Comment by rgreen1221** [comment]
Okay, I got the latest version of nintendont and ran a MD5 check for the ISO files.

Nintendont is now running Version 4.425 (Built Oct 14 2016)

The winMD5Sum software did a MD5 check and found out my ISO Disc 1 has the correct MD5 but Disc 2 doesn't have the correct MD5 (That might be the reason why it freezes when loading)

**Comment by carnage702** [comment]
also some settings can break some games, for instant i remenber using 16mb mc emus brooke disc cnaging among other things. and some forced settings can break them too.

**Comment by rgreen1221** [comment]
My settings are all set to normal. Looks like i'm going have to look for a good ISO for this game.

I appreciate the help guys!

**Comment by carnage702** [comment]
yeah try fiding a disc 2 iso that matches redump, also you have disc 2 on the same folder as disc one named disc2.iso correct?

**Comment by rgreen1221** [comment]
Yes Disc 1 and Disc 2 are in the same folder with Disc 1 renamed game.iso and Disc 2 as disc2.iso

**Comment by carnage702** [comment]
and if you sya you dont think you have any agressive setting turned on, then it has to be the bad iso.
