### ISSUE TITLE
Mem Card Emulation 

### ISSUE THREAD

**Issue by Shadowfox364** [FIX94/Nintendont#334]
So I'm running Nintendont on vWii 64gb SDXC card formatted FAT32 and it runs normally, however sometimes I have the issue where Memory Card Emulation doesn't work properly, by that I mean it stops saving and doesn't remember the last game I played, but the ones before it. (Last game it remembers me playing is Monkey Ball 2) I try booting up another game (this case Sonic Mega Collection) and when I go back to the loader menu it shows Monkey Ball as my last recently played game. the emulated memory card I'm running is a 1019 block. though with each build update, the issue seems fixed, but after a while it goes back to this issue, any fixes.

**Comment by GerbilSoft** [comment]
Emulated cards larger than 251 blocks are known to have issues. Can you try again with 251 or smaller? (You can use Dolphin's memory card manager to transfer saves between .raw files.)
