### ISSUE TITLE
Open cover error on animal crossing game

### ISSUE THREAD

**Issue by tetradog** [FIX94/Nintendont#339]
i have an issue with animal crossing using miniDVD to play.
the game works but the error open cover stop the game...

any solution??
sorry my bad english.

[spanish]
tengo un problema con el juego de animal crossing desde miniDVD y es que despues del titulo y hablar con totake me dice "la tapa esta abierta" o algo similar y no me deja continuar...alguna solucion???

**Comment by carnage702** [comment]
are you using an original gc disc?

**Comment by tetradog** [comment]
Is original disk :)

The settings only change virtual memory,log,debug.

I try to play mario party 6 original and play very well :) (the issue no repeat in fuese case)

**Comment by carnage702** [comment]
well log and debug break manny games try turning those off.

**Comment by tetradog** [comment]
I try to turn off debug and log and works fine.
Other wise, the issue open cover it reapear if the miniDvd is not clean...but not problem only report (if is possible eject,clean and try again with out turn off more better) thanks for support ;) [sorry my bad english]

**Comment by carnage702** [comment]
sadly not once you eject a disc nintendont stops working  like a real GC, unless its a multidisc game  the game isnt coded to work without a disc.
