### ISSUE TITLE
it's possible export/import savegames?

### ISSUE THREAD

**Issue by tetradog** [FIX94/Nintendont#340]
I wondering if is possible on the next updates include these feature.

Thanks

**Comment by carnage702** [comment]
you can already export and import saves.

To use savegames from real memory cards to virtual memory cards you need a wii with gc ports an an homebrew program called gc saver if im not mistaken and you use the program to dump the savefiles to your sd card then use DOLPHIN  memory card manager and import the gci saves into a nintendont save file.

Same way for gci saves from the PC use DOLPHIN memory card manager on the pc.
