### ISSUE TITLE
Not compatibile with devkitPPC r28

### ISSUE THREAD

**Issue by nastys** [FIX94/Nintendont#348]
I cannot successfully compile Nintendont.
Full terminal output:

> nastys@ULNS:~/Documents/Nintendont$ make clean
>  
> Cleaning all subprojects...
>  
> make -C multidol clean
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/multidol'
> rm -f -rf multidol_ldr.elf ../loader/data/multidol_ldr.bin crt0.o cache.o main.o global.o apploader.o dip.o utils.o .deps
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/multidol'
> make -C kernel/asm clean
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/kernel/asm'
> clean ...
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/kernel/asm'
> make -C resetstub clean
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/resetstub'
> rm -f -rf tinyload.elf ../loader/data/stub.bin crt0.o memory.o ios.o utils.o cache.o usbgecko.o main.o .deps
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/resetstub'
> make -C fatfs -f Makefile.arm clean
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/fatfs'
> rm -f -f *-arm.a *-arm.o *-arm.d
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/fatfs'
> make -C fatfs -f Makefile.ppc clean
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/fatfs'
> rm -f -f *-ppc.a *-ppc.o *-ppc.d
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/fatfs'
> make -C codehandler clean
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/codehandler'
> rm -f codehandler.h codehandleronly.h codehandler.bin codehandleronly.bin
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/codehandler'
> make -C kernel clean
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/kernel'
> rm -f -f ../loader/data/kernel.zip *.elf *.o *.bin *.d *.map lwbt/*.d lwbt/*.o option/*.d option/*.o
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/kernel'
> make -C loader/source/ppc clean
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/loader/source/ppc'
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/loader/source/ppc'
> make -C loader clean
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/loader'
> clean ...
> rm -f -rf build /home/nastys/Documents/Nintendont/loader/loader.elf /home/nastys/Documents/Nintendont/loader/loader.dol
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/loader'
> nastys@ULNS:~/Documents/Nintendont$ make
>  
> Building Multi-DOL loader
>  
> make -C multidol
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/multidol'
>  ASSEMBLE    crt0.S
>  COMPILE     cache.c
>  COMPILE     main.c
>  COMPILE     global.c
>  COMPILE     apploader.c
>  COMPILE     dip.c
>  COMPILE     utils.c
>  LINK        multidol_ldr.elf
>  OBJCOPY     ../loader/data/multidol_ldr.bin
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/multidol'
>  
> Building reset stub
>  
> make -C resetstub
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/resetstub'
>  ASSEMBLE    crt0.S
>  ASSEMBLE    memory.S
>  COMPILE     ios.c
>  COMPILE     utils.c
>  COMPILE     cache.c
>  COMPILE     usbgecko.c
>  COMPILE     main.c
>  LINK        tinyload.elf
>  OBJCOPY     ../loader/data/stub.bin
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/resetstub'
>  
> Building FatFS library for PPC
>  
> make -C fatfs -f Makefile.ppc
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/fatfs'
> CC	ff-ppc.o
> CC	ff_utf8-ppc.o
> AR	libfatfs-ppc.a
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/fatfs'
>  
> Building asm files
>  
> make -C kernel/asm
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/kernel/asm'
>  ASSEMBLE    DVDLowAudioStream.S
>  ASSEMBLE    EXIDMA.S
>  ASSEMBLE    FakeRSWLoad.S
>  ASSEMBLE    SIInitStore.S
>  ASSEMBLE    FakeAIInterrupt.S
>  ASSEMBLE    RestoreSettingsAX_RVD.S
>  ASSEMBLE    CalcGXWidescreen.S
>  ASSEMBLE    PADReadGP.S
>  ASSEMBLE    patch_fwrite_Log.S
>  ASSEMBLE    PADControlAllMotors.S
>  ASSEMBLE    ARQPostRequest.S
>  ASSEMBLE    EXISelect.S
>  ASSEMBLE    CheckTestMenu.S
>  ASSEMBLE    SonicRidersCopy.S
>  ASSEMBLE    RestoreSettingsYAKRVB.S
>  ASSEMBLE    DatelTimer.S
>  ASSEMBLE    PADReadVS.S
>  ASSEMBLE    ARStartDMA_PM.S
>  ASSEMBLE    DVDLowRequestAudioStatus.S
>  ASSEMBLE    RestoreSettingsAX_RVE.S
>  ASSEMBLE    OSReportDM.S
>  ASSEMBLE    ARStartDMA.S
>  ASSEMBLE    CheckTestMenuYakyuu.S
>  ASSEMBLE    CheckTestMenuVS.S
>  ASSEMBLE    EXIProbe.S
>  ASSEMBLE    GXLoadTlut.S
>  ASSEMBLE    RestoreSettingsYAKRVC.S
>  ASSEMBLE    EXILock.S
>  ASSEMBLE    PADRead.S
>  ASSEMBLE    RestoreSettingsAX_RVC.S
>  ASSEMBLE    DVDSendCMDEncrypted.S
>  ASSEMBLE    FakeRSWStore.S
>  ASSEMBLE    PADControlMotorGP.S
>  ASSEMBLE    RestoreSettingsVS4V06EXP.S
>  ASSEMBLE    __CARDClearStatus.S
>  ASSEMBLE    MajoraSaveRegs.S
>  ASSEMBLE    MajoraAudioStream.S
>  ASSEMBLE    OSExceptionInit.S
>  ASSEMBLE    PADControlMotor.S
>  ASSEMBLE    SIGetType.S
>  ASSEMBLE    CalcWidescreen.S
>  ASSEMBLE    __DSPHandler.S
>  ASSEMBLE    GCAMSendCommand.S
>  ASSEMBLE    codehandler_stub.S
>  ASSEMBLE    SwitcherPrs.S
>  ASSEMBLE    DVDLowAudioBufferConfig.S
>  ASSEMBLE    FakeInterrupt.S
>  ASSEMBLE    RestoreSettingsVS4EXP.S
>  ASSEMBLE    PADReadF.S
>  ASSEMBLE    RestoreSettingsVS4JAP.S
>  ASSEMBLE    CheckTestMenuGP.S
>  ASSEMBLE    PADIsBarrel.S
>  ASSEMBLE    FakeEntryLoad.S
>  ASSEMBLE    GXInitTlutObj.S
>  ASSEMBLE    TCIntrruptHandler.S
>  ASSEMBLE    FakeInterrupt_DBG.S
>  ASSEMBLE    CalcWidescreenDiv.S
>  ASSEMBLE    EXIImm.S
>  ASSEMBLE    SITransfer.S
>  ASSEMBLE    PADReadVS3.S
>  ASSEMBLE    __ARHandler.S
>  ASSEMBLE    __DVDInterruptHandler.S
>  ASSEMBLE    RestoreSettingsVS3V02.S
>  ASSEMBLE    EXIGetID.S
>  ASSEMBLE    __CARDReadStatus.S
>  ASSEMBLE    ARStartDMA_TC.S
>  ASSEMBLE    ReadROM.S
>  ASSEMBLE    ARStartDMA_Hook.S
>  ASSEMBLE    patch_fwrite_GC.S
>  ASSEMBLE    SIIntrruptHandler.S
>  ASSEMBLE    MajoraLoadRegs.S
>  ASSEMBLE    RestoreSettingsVS4V06JAP.S
>  ASSEMBLE    __GXSetVAT.S
>  STRIP       DVDLowAudioStream.elf
>  STRIP       EXIDMA.elf
>  STRIP       FakeRSWLoad.elf
>  STRIP       SIInitStore.elf
>  STRIP       FakeAIInterrupt.elf
>  STRIP       RestoreSettingsAX_RVD.elf
>  STRIP       CalcGXWidescreen.elf
>  STRIP       PADReadGP.elf
>  STRIP       patch_fwrite_Log.elf
>  STRIP       PADControlAllMotors.elf
>  STRIP       ARQPostRequest.elf
>  STRIP       EXISelect.elf
>  STRIP       CheckTestMenu.elf
>  STRIP       SonicRidersCopy.elf
>  STRIP       RestoreSettingsYAKRVB.elf
>  STRIP       DatelTimer.elf
>  STRIP       PADReadVS.elf
>  STRIP       ARStartDMA_PM.elf
>  STRIP       DVDLowRequestAudioStatus.elf
>  STRIP       RestoreSettingsAX_RVE.elf
>  STRIP       OSReportDM.elf
>  STRIP       ARStartDMA.elf
>  STRIP       CheckTestMenuYakyuu.elf
>  STRIP       CheckTestMenuVS.elf
>  STRIP       EXIProbe.elf
>  STRIP       GXLoadTlut.elf
>  STRIP       RestoreSettingsYAKRVC.elf
>  STRIP       EXILock.elf
>  STRIP       PADRead.elf
>  STRIP       RestoreSettingsAX_RVC.elf
>  STRIP       DVDSendCMDEncrypted.elf
>  STRIP       FakeRSWStore.elf
>  STRIP       PADControlMotorGP.elf
>  STRIP       RestoreSettingsVS4V06EXP.elf
>  STRIP       __CARDClearStatus.elf
>  STRIP       MajoraSaveRegs.elf
>  STRIP       MajoraAudioStream.elf
>  STRIP       OSExceptionInit.elf
>  STRIP       PADControlMotor.elf
>  STRIP       SIGetType.elf
>  STRIP       CalcWidescreen.elf
>  STRIP       __DSPHandler.elf
>  STRIP       GCAMSendCommand.elf
>  STRIP       codehandler_stub.elf
>  STRIP       SwitcherPrs.elf
>  STRIP       DVDLowAudioBufferConfig.elf
>  STRIP       FakeInterrupt.elf
>  STRIP       RestoreSettingsVS4EXP.elf
>  STRIP       PADReadF.elf
>  STRIP       RestoreSettingsVS4JAP.elf
>  STRIP       CheckTestMenuGP.elf
>  STRIP       PADIsBarrel.elf
>  STRIP       FakeEntryLoad.elf
>  STRIP       GXInitTlutObj.elf
>  STRIP       TCIntrruptHandler.elf
>  STRIP       FakeInterrupt_DBG.elf
>  STRIP       CalcWidescreenDiv.elf
>  STRIP       EXIImm.elf
>  STRIP       SITransfer.elf
>  STRIP       PADReadVS3.elf
>  STRIP       __ARHandler.elf
>  STRIP       __DVDInterruptHandler.elf
>  STRIP       RestoreSettingsVS3V02.elf
>  STRIP       EXIGetID.elf
>  STRIP       __CARDReadStatus.elf
>  STRIP       ARStartDMA_TC.elf
>  STRIP       ReadROM.elf
>  STRIP       ARStartDMA_Hook.elf
>  STRIP       patch_fwrite_GC.elf
>  STRIP       SIIntrruptHandler.elf
>  STRIP       MajoraLoadRegs.elf
>  STRIP       RestoreSettingsVS4V06JAP.elf
>  STRIP       __GXSetVAT.elf
>  BIN2H       DVDLowAudioStream.bin
>  BIN2H       EXIDMA.bin
>  BIN2H       FakeRSWLoad.bin
>  BIN2H       SIInitStore.bin
>  BIN2H       FakeAIInterrupt.bin
>  BIN2H       RestoreSettingsAX_RVD.bin
>  BIN2H       CalcGXWidescreen.bin
>  BIN2H       PADReadGP.bin
>  BIN2H       patch_fwrite_Log.bin
>  BIN2H       PADControlAllMotors.bin
>  BIN2H       ARQPostRequest.bin
>  BIN2H       EXISelect.bin
>  BIN2H       CheckTestMenu.bin
>  BIN2H       SonicRidersCopy.bin
>  BIN2H       RestoreSettingsYAKRVB.bin
>  BIN2H       DatelTimer.bin
>  BIN2H       PADReadVS.bin
>  BIN2H       ARStartDMA_PM.bin
>  BIN2H       DVDLowRequestAudioStatus.bin
>  BIN2H       RestoreSettingsAX_RVE.bin
>  BIN2H       OSReportDM.bin
>  BIN2H       ARStartDMA.bin
>  BIN2H       CheckTestMenuYakyuu.bin
>  BIN2H       CheckTestMenuVS.bin
>  BIN2H       EXIProbe.bin
>  BIN2H       GXLoadTlut.bin
>  BIN2H       RestoreSettingsYAKRVC.bin
>  BIN2H       EXILock.bin
>  BIN2H       PADRead.bin
>  BIN2H       RestoreSettingsAX_RVC.bin
>  BIN2H       DVDSendCMDEncrypted.bin
>  BIN2H       FakeRSWStore.bin
>  BIN2H       PADControlMotorGP.bin
>  BIN2H       RestoreSettingsVS4V06EXP.bin
>  BIN2H       __CARDClearStatus.bin
>  BIN2H       MajoraSaveRegs.bin
>  BIN2H       MajoraAudioStream.bin
>  BIN2H       OSExceptionInit.bin
>  BIN2H       PADControlMotor.bin
>  BIN2H       SIGetType.bin
>  BIN2H       CalcWidescreen.bin
>  BIN2H       __DSPHandler.bin
>  BIN2H       GCAMSendCommand.bin
>  BIN2H       codehandler_stub.bin
>  BIN2H       SwitcherPrs.bin
>  BIN2H       DVDLowAudioBufferConfig.bin
>  BIN2H       FakeInterrupt.bin
>  BIN2H       RestoreSettingsVS4EXP.bin
>  BIN2H       PADReadF.bin
>  BIN2H       RestoreSettingsVS4JAP.bin
>  BIN2H       CheckTestMenuGP.bin
>  BIN2H       PADIsBarrel.bin
>  BIN2H       FakeEntryLoad.bin
>  BIN2H       GXInitTlutObj.bin
>  BIN2H       TCIntrruptHandler.bin
>  BIN2H       FakeInterrupt_DBG.bin
>  BIN2H       CalcWidescreenDiv.bin
>  BIN2H       EXIImm.bin
>  BIN2H       SITransfer.bin
>  BIN2H       PADReadVS3.bin
>  BIN2H       __ARHandler.bin
>  BIN2H       __DVDInterruptHandler.bin
>  BIN2H       RestoreSettingsVS3V02.bin
>  BIN2H       EXIGetID.bin
>  BIN2H       __CARDReadStatus.bin
>  BIN2H       ARStartDMA_TC.bin
>  BIN2H       ReadROM.bin
>  BIN2H       ARStartDMA_Hook.bin
>  BIN2H       patch_fwrite_GC.bin
>  BIN2H       SIIntrruptHandler.bin
>  BIN2H       MajoraLoadRegs.bin
>  BIN2H       RestoreSettingsVS4V06JAP.bin
>  BIN2H       __GXSetVAT.bin
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/kernel/asm'
>  
> Building FatFS library for ARM
>  
> make -C fatfs -f Makefile.arm
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/fatfs'
> CC	ff-arm.o
> CC	ff_utf8-arm.o
> AR	libfatfs-arm.a
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/fatfs'
>  
> Building Nintendont code handler
>  
> make -C codehandler
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/codehandler'
>  COMPILE     codehandler.s
>  STRIP       codehandler.s
>  OBJCOPY     codehandler.s
>  BIN2H       codehandler.bin
>  COMPILE     codehandleronly.s
>  STRIP       codehandleronly.s
>  OBJCOPY     codehandleronly.s
>  BIN2H       codehandleronly.bin
> rm codehandler.bin codehandleronly.bin
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/codehandler'
>  
> Building Nintendont kernel
>  
> make -C kernel
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/kernel'
> AS	start.o
> CC	common.o
> CC	alloc.o
> CC	GCAM.o
> CC	JVSIO.o
> CC	JVSIOMessage.o
> CC	FST.o
> CC	DI.o
> CC	RealDI.o
> CC	Patch.o
> CC	PatchTimers.o
> CC	TRI.o
> CC	PatchWidescreen.o
> CC	ISO.o
> CC	Stream.o
> CC	adp.o
> CC	EXI.o
> CC	SRAM.o
> CC	SI.o
> CC	HID.o
> CC	diskio.o
> CC	Config.o
> AS	utils_asm.o
> CC	ES.o
> CC	NAND.o
> CC	main.o
> AS	syscalls.o
> CC	ReadSpeed.o
> CC	vsprintf.o
> CC	string.o
> CC	prs.o
> CC	SDI.o
> CC	usb.o
> CC	usbstorage.o
> CC	lwbt/bte.o
> CC	lwbt/btmemb.o
> CC	lwbt/btmemr.o
> CC	lwbt/btpbuf.o
> CC	lwbt/hci.o
> CC	lwbt/l2cap.o
> CC	lwbt/physbusif.o
> CC	BT.o
> LD	kernel.elf
> ZIP	../loader/data/kernel.zip
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/kernel'
>  
> Building Nintendont HID
>  
> make -C loader/source/ppc
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/loader/source/ppc'
>  COMPILE     PADReadGC.c
>  OBJCOPY     PADReadGC.bin
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/loader/source/ppc'
>  
> Building Nintendont loader
>  
> make -C loader
> make[1]: Entering directory '/home/nastys/Documents/Nintendont/loader'
> multidol_ldr.bin
> background.png
> font.zip
> PADReadGC.bin
> stub.bin
> kernel.zip
> ssl.c
> menu.c
> In file included from /home/nastys/Documents/Nintendont/loader/include/exi.h:28:0,
>                  from /home/nastys/Documents/Nintendont/loader/source/menu.c:23:
> /home/nastys/Documents/Nintendont/loader/include/global.h:179:7: error: conflicting types for 'memalign'
>  void *memalign( u32 Align, u32 Size );
>        ^~~~~~~~
> In file included from /home/nastys/Documents/Nintendont/loader/include/grrlib.h:446:0,
>                  from /home/nastys/Documents/Nintendont/loader/include/global.h:28,
>                  from /home/nastys/Documents/Nintendont/loader/include/exi.h:28,
>                  from /home/nastys/Documents/Nintendont/loader/source/menu.c:23:
> /opt/devkitpro/devkitPPC/powerpc-eabi/include/malloc.h:69:13: note: previous declaration of 'memalign' was here
>  extern _PTR memalign _PARAMS ((size_t, size_t));
>              ^~~~~~~~
> /home/nastys/Documents/Nintendont/loader/source/menu.c: In function 'PrintLoadKernelError':
> /home/nastys/Documents/Nintendont/loader/source/menu.c:1834:113: warning: format '%d' expects argument of type 'int', but argument 7 has type 's32 {aka long int}' [-Wformat=]
>  S_X, MENU_POS_Y + 20*5, "LoadKernel() error %d occurred, returning %d.", iosErr, err);
>                                                                      ^
> /home/nastys/Documents/Nintendont/loader/source/menu.c:1838:102: warning: format '%d' expects argument of type 'int', but argument 6 has type 's32 {aka long int}' [-Wformat=]
>  ON, MENU_POS_X, MENU_POS_Y + 20*5, "ES_GetStoredTMDSize() returned %d.", err);
>                                                                      ^
> /home/nastys/Documents/Nintendont/loader/source/menu.c:1859:98: warning: format '%d' expects argument of type 'int', but argument 6 has type 's32 {aka long int}' [-Wformat=]
>  MAROON, MENU_POS_X, MENU_POS_Y + 20*5, "ES_GetStoredTMD() returned %d.", err);
>                                                                      ^
> /home/nastys/Documents/Nintendont/loader/source/menu.c:1864:115: warning: format '%d' expects argument of type 'int', but argument 6 has type 's32 {aka long int}' [-Wformat=]
>  X, MENU_POS_Y + 20*5, "IOS_Open(\"/shared1/content.map\") returned %d.", err);
>                                                                      ^
> /home/nastys/Documents/Nintendont/loader/source/menu.c:1874:103: warning: format '%d' expects argument of type 'int', but argument 6 has type 's32 {aka long int}' [-Wformat=]
>  N, MENU_POS_X, MENU_POS_Y + 20*5, "IOS_Open(IOS58 kernel) returned %d.", err);
>                                                                      ^
> /home/nastys/Documents/Nintendont/loader/source/menu.c:1879:103: warning: format '%d' expects argument of type 'int', but argument 6 has type 's32 {aka long int}' [-Wformat=]
>  N, MENU_POS_X, MENU_POS_Y + 20*5, "IOS_Read(IOS58 kernel) returned %d.", err);
>                                                                      ^
> /opt/devkitpro/devkitPPC/base_rules:51: recipe for target 'menu.o' failed
> make[2]: *** [menu.o] Error 1
> Makefile:106: recipe for target 'build' failed
> make[1]: *** [build] Error 2
> make[1]: Leaving directory '/home/nastys/Documents/Nintendont/loader'
> Makefile:72: recipe for target 'loader' failed
> make: *** [loader] Error 2

Using Build.sh doesn't work either.

Part of my .bashrc file:

> export VULKAN_SDK=/home/nastys/Documents/VulkanSDK/1.0.21.1/x86_64
> export DEVKITPRO=/opt/devkitpro
> export DEVKITPPC=$DEVKITPRO/devkitPPC
> export DEVKITARM=$DEVKITPRO/devkitARM
> export PATH=$PATH:$DEVKITPRO/devkitPPC/bin:$DEVKITPRO/devkitARM/bin:$VULKAN_SDK/bin
> export LD_LIBRARY_PATH=$VULKAN_SDK/lib
> export VK_LAYER_PATH=$VULKAN_SDK/etc/explicit_layer.d
> export JAVA_HOME="/usr/lib/jvm/java-8-oracle"

I haven't compiled Nintendont in a while.
@FIX94 (or anyone who has compiled it recently), any ideas why it doesn't work? Maybe it's related to the C compiler and/or devkitPro but I don't know how to fix it. By the way, I used devkitARMupdate.pl and devkitPPCupdate.pl to install it.

**Comment by FIX94** [comment]
go complain to the people behind devkitppc, maybe they'll actually fix their dumb move of changing the definition of an int, in the meantime replace the stdint.h in devkitppc/powerpc-eabi/include with this one:
https://mega.nz/#!Ih5BAYJR!8IitApECKcn9TSKvBb8qTjQ8Qjl6XvLXzzg5h6NcxHk
seriously though, the change in r28 basically breaks compiling any homebrew app and I do not see a point of us adjusting that but them just changing that stdint.h back to a sane version like this.

**Comment by nastys** [comment]
It's working now, thanks!
I don't see the point of their move either, but maybe we should leave this issue open until it's solved.
I think the definitions can be bypassed completely.

**Comment by FIX94** [comment]
just commited a rather simple wrapper to keep our definitions the same so it should now properly work with the stock dkppc r28.
