### ISSUE TITLE
What's keeping multiple drives from working?

### ISSUE THREAD

**Issue by missionfloyd** [FIX94/Nintendont#351]
Is it something that can't be fixed? Because it'd be nice if I could keep my Wii U drive connected.

**Comment by GB-CG** [comment]
Are you using a USB hub for your Wii U? Also, are you using a USB-Y cable for your drive?

**Comment by GerbilSoft** [comment]
Is this issue reproducible if you have the same drive configuration on a regular Wii? If not, I might as well go ahead and hack my Wii U later this week to test it.

**Comment by missionfloyd** [comment]
I guess I could've been clearer. What I mean is that Nintendont doesn't work if you have more than one drive plugged in, a known problem according to [the GBAtemp thread](https://gbatemp.net/threads/nintendont.349258). So I have to unplug the Wii U formatted drive. Otherwise, it works fine.

**Comment by missionfloyd** [comment]
On a Wii, i get "WARNING: USB FAT device could not be opened" followed by "The disc drive could not be initialized." Then it exits.

On a Wii U, the same warning, then this:
```
Exception (DSI) occurred!
GPR00 8006BBAC GPR08 00000000 GPR16 00000000 GPR24 802047C8
GPR01 801FF768 GPR09 801FF778 GPR17 00000000 GPR25 80156768
GPR02 80168C20 GPR10 00000000 GPR18 801FF778 GPR26 0000CAFE
GPR03 93002914 GPR11 00000000 GPR19 80160000 GPR27 CD8005A0
GPR04 00000000 GPR12 30C30C31 GPR20 00000001 GPR28 00000001
GPR05 000000FF GPR13 8016B060 GPR21 801567BC GPR29 93002900 
GPR06 00000000 GPR14 80003143 GPR22 80156780 GPR30 00000000
GPR07 00000000 GPR15 CD8005A0 GPR23 8015660C GPR31 00000000
LR 8006BC48 SRR0 8006cc3c SRR1 0000b032 MSR 00001000
DAR 00000003 DSISR 04000000 

STACK DUMP:
8006cc3c --> 8006bc48 --> 800043d4 --> 800a3630 --> 800a35e4

CODE DUMP:
8006cc3c: 892A0003 6929003A 21290000 7D4A0194
8006cc4c: 388A0003 48058F01 7D32F02E 38800220
8006cc5c: 7FA3EB78 913D0218 4BFEFA31 41920054

Reloading in 10 seconds 

Reload
```

Then nothing. I have to pull the power cable,

**Comment by missionfloyd** [comment]
If it matters, I tried it again on 4.435.

![img_0748](https://cloud.githubusercontent.com/assets/4073789/22180899/8a3d438c-e03b-11e6-88a0-cd06ca17a35f.jpg)

It works fine with just the one drive, or with games on an SD card.

**Comment by KreativeKrise** [comment]
I have the same issue! But I'm not sure if it's nintendont related, because I have the same issue with usb loader gx.

**Comment by carnage702** [comment]
nintendont usb code would need a total rewrite to allow multiple drives at once and that aint gonna happen soon  if ever at all, so unplug the drives that arent for nintendont if you still wanna use nintendont if not try devolution.

**Comment by missionfloyd** [comment]
Any chance it can somehow ignore the Wii U drive? Or look for fat32 partitions and mount the first one it finds? If not, games run fine from an SD card, so that works.

Aside from that, it may be worth looking into why this makes it crash on vWii but not Wii (the exceptions above happen only on Wii U; it exits to HBC on Wii.)

**Comment by carnage702** [comment]
everyone is free to change the usb code and  submit a pull request.

**Comment by missionfloyd** [comment]
Sounds like it's more trouble than it's worth. SD cards work fine, so it's not a big deal.
