### ISSUE TITLE
Radical Entertainment Games(NTSC)/Video Width/Screen Position Error

### ISSUE THREAD

**Issue by SuperMoonKnight** [FIX94/Nintendont#353]
There seems to be an issue regarding most of Radical Entertainment's games (Simpsons Hit and Run, The Incredible Hulk: Ultimate Destruction). Their games do not recognize any changes with the Video Width and Screen Position functions. No matter how far you stretch the screen or "move" it, it will always be set in its default setting. I've tested The Hulk, The Incredible Hulk: Ultimate Destruction, and Simpsons Hit & Run, all of which were developed by Radical. They all have this issue. However, Simpsons Road Rage and Crash Tag Team Racing, which were also developed by Radical Entertainment, don't have this issue. Is this something that can be fixed manually? Or is it a more complicated issue? Thanks in advance for any help.

**Comment by SuperMoonKnight** [comment]
There seems to be an issue regarding most of Radical Entertainment's games (Simpsons Hit and Run, The Incredible Hulk: Ultimate Destruction). Their games do not recognize any changes with the Video Width and Screen Position functions. No matter how far you stretch the screen or "move" it, it will always be set in its default setting. I've tested The Hulk, The Incredible Hulk: Ultimate Destruction, and Simpsons Hit & Run, all of which were developed by Radical. They all have this issue. However, Simpsons Road Rage and Crash Tag Team Racing, which were also developed by Radical Entertainment, don't have this issue. Is this something that can be fixed manually? Or is it a more complicated issue? Thanks in advance for any help.

**Comment by GB-CG** [comment]
Have you asked about this at the [Support forum](https://gbatemp.net/threads/nintendont.349258)?

**Comment by SuperMoonKnight** [comment]
It's all good, fixed the issue. Had to edit something. Closing this issue.

**Comment by jmorale** [comment]
I'm actually have the same problem with Simpsons Hit and Run.  On my tv, proper 4x3 is achieved by setting the screen width to 720, but when I play the simpsons, it seems to display at the skinnier default of 640.  How did you go about fixing the issue?

**Comment by carnage702** [comment]
some games do not work with width setting.

**Comment by jmorale** [comment]
It sounded like the OP managed to fix it though?

**Comment by carnage702** [comment]
no idea he never said how im guessing maybe his tv had a setting or something.

**Comment by SuperMoonKnight** [comment]
Yeah this seems to be an issue with Radical's games that have progressive scan, as games such as Road Rage and CTTR do not have this issue it seems. Games like Hit and Run and The Incredible Hulk Ultimate Destruction however do not recognize any screen changes you make.

This also affects Spyro A Hero's Tail for some unexplained reason. I haven't checked any other Eurocom games such as Chamber of Secrets and Ice Age 2, so I'm not sure if it's widespread for them. And no, I haven't been able to find a fix for the issue. For some reason I guess I somehow glitched this issue page, so I apologize for that.

**Comment by carnage702** [comment]
you litery replyed 

"It's all good, fixed the issue. Had to edit something. Closing this issue."
lol
