### ISSUE TITLE
Wii (Original) GBA Link Issues

### ISSUE THREAD

**Issue by WiiNovice** [FIX94/Nintendont#356]
I am having problems connecting my GBA to my wii through nintendont.  I am able to do it when just using the Wii's default player as I am able to play legend of zelda 4 swords on it.  However, I cannot trade in Pokemon Colosseum when using nintendont. Is there something special I have to do to enable this functionality? I'll appreciate any help.
Some detail: Nintendont Loader v4.432 Frimware 58.24.32

**Comment by FIX94** [comment]
nintendont by default only passes through controls to all devices to allow all the different control options, if you want the game to fully use the physical gamecube ports on your wii then enable native controls, that will directly pass through any gamecube port commands going to for example the gba link cable while of course taking away the other control options.

**Comment by WiiNovice** [comment]
Thanks by enabling native mode I managed to get it to work but only when I launch the game from nintendont but not USBLoader (I have all my save data and stuff on USBLoader GX).  I am pretty sure USBLoader uses nintendont but I can't find out how to get it to work when I launch it from USBLoader. If USBLoader doesn't offer this functionality is there a way to get my save data to work when launching the game directly from nintendont?

**Comment by FIX94** [comment]
you are looking for the memory card emulation option I assume.

**Comment by WiiNovice** [comment]
Yes! Thank you!
