### ISSUE TITLE
unable to build current version

### ISSUE THREAD

**Issue by RandomMan25XX** [FIX94/Nintendont#357]
i'm not exactly sure what the issue is but when it starts to build from the "loader" folder it says that the target does not contain a % then it cancels building, what could be causing this?

**Comment by RandomMan25XX** [comment]
C:\Users\Michael John Blanton\Downloads\Nintendont-master>make forced windows=1

Cleaning all subprojects...

make -C multidol clean
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/multidol'
rm -f -rf multidol_ldr.elf ../loader/data/multidol_ldr.bin crt0.o cache.o main.o global.o apploader.o dip.o utils.o .deps
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/multidol'
make -C kernel/asm clean
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/kernel/asm'
clean ...
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/kernel/asm'
make -C resetstub clean
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/resetstub'
rm -f -rf tinyload.elf ../loader/data/stub.bin crt0.o memory.o ios.o utils.o cache.o usbgecko.o main.o .deps
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/resetstub'
make -C fatfs -f Makefile.arm clean
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/fatfs'
rm -f -f *-arm.a *-arm.o *-arm.d
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/fatfs'
make -C fatfs -f Makefile.ppc clean
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/fatfs'
rm -f -f *-ppc.a *-ppc.o *-ppc.d
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/fatfs'
make -C codehandler clean
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/codehandler'
rm -f codehandler.h codehandleronly.h codehandler.bin codehandleronly.bin
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/codehandler'
make -C kernel clean
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/kernel'
rm -f -f ../loader/data/kernel.zip *.elf *.o *.bin *.d *.map lwbt/*.d lwbt/*.o option/*.d option/*.o
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/kernel'
make -C loader/source/ppc clean
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/loader/source/ppc'
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/loader/source/ppc'
make -C loader clean
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/loader'
clean ...
rm -f -rf build /c/Users/Michael John Blanton/Downloads/Nintendont-master/loader/Michael John loader.elf /c/Users/Michael John Blanton/Downloads/Nintendont-master/loader/Michael John loader.dol
rm: cannot remove `/c/Users/Michael': Permission denied
rm: cannot remove `/c/Users/Michael': Permission denied
make[1]: [clean] Error 1 (ignored)
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/loader'

Building Multi-DOL loader

make -C multidol
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/multidol'
 ASSEMBLE    crt0.S
 COMPILE     cache.c
 COMPILE     main.c
 COMPILE     global.c
 COMPILE     apploader.c
 COMPILE     dip.c
 COMPILE     utils.c
 LINK        multidol_ldr.elf
 OBJCOPY     ../loader/data/multidol_ldr.bin
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/multidol'

Building reset stub

make -C resetstub
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/resetstub'
 ASSEMBLE    crt0.S
 ASSEMBLE    memory.S
 COMPILE     ios.c
 COMPILE     utils.c
 COMPILE     cache.c
 COMPILE     usbgecko.c
 COMPILE     main.c
 LINK        tinyload.elf
 OBJCOPY     ../loader/data/stub.bin
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/resetstub'

Building FatFS library for PPC

make -C fatfs -f Makefile.ppc
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/fatfs'
CC      ff-ppc.o
CC      ff_utf8-ppc.o
AR      libfatfs-ppc.a
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/fatfs'

Building asm files

make -C kernel/asm
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/kernel/asm'
 ASSEMBLE    ARQPostRequest.S
 ASSEMBLE    ARStartDMA.S
 ASSEMBLE    ARStartDMA_Hook.S
 ASSEMBLE    ARStartDMA_PM.S
 ASSEMBLE    ARStartDMA_TC.S
 ASSEMBLE    CalcGXWidescreen.S
 ASSEMBLE    CalcWidescreen.S
 ASSEMBLE    CalcWidescreenDiv.S
 ASSEMBLE    CheckTestMenu.S
 ASSEMBLE    CheckTestMenuGP.S
 ASSEMBLE    CheckTestMenuVS.S
 ASSEMBLE    CheckTestMenuYakyuu.S
 ASSEMBLE    DVDLowAudioBufferConfig.S
 ASSEMBLE    DVDLowAudioStream.S
 ASSEMBLE    DVDLowRequestAudioStatus.S
 ASSEMBLE    DVDSendCMDEncrypted.S
 ASSEMBLE    DatelTimer.S
 ASSEMBLE    EXIDMA.S
 ASSEMBLE    EXIGetID.S
 ASSEMBLE    EXIImm.S
 ASSEMBLE    EXILock.S
 ASSEMBLE    EXIProbe.S
 ASSEMBLE    EXISelect.S
 ASSEMBLE    FakeAIInterrupt.S
 ASSEMBLE    FakeEntryLoad.S
 ASSEMBLE    FakeInterrupt.S
 ASSEMBLE    FakeInterrupt_DBG.S
 ASSEMBLE    FakeInterrupt_Datel.S
 ASSEMBLE    FakeRSWLoad.S
 ASSEMBLE    FakeRSWStore.S
 ASSEMBLE    GCAMSendCommand.S
 ASSEMBLE    GXInitTlutObj.S
 ASSEMBLE    GXLoadTlut.S
 ASSEMBLE    MajoraAudioStream.S
 ASSEMBLE    MajoraLoadRegs.S
 ASSEMBLE    MajoraSaveRegs.S
 ASSEMBLE    OSExceptionInit.S
 ASSEMBLE    OSReportDM.S
 ASSEMBLE    PADControlAllMotors.S
 ASSEMBLE    PADControlMotor.S
 ASSEMBLE    PADControlMotorGP.S
 ASSEMBLE    PADIsBarrel.S
 ASSEMBLE    PADRead.S
 ASSEMBLE    PADReadF.S
 ASSEMBLE    PADReadGP.S
 ASSEMBLE    PADReadVS.S
 ASSEMBLE    PADReadVS3.S
 ASSEMBLE    ReadROM.S
 ASSEMBLE    RestoreSettingsAX_RVC.S
 ASSEMBLE    RestoreSettingsAX_RVD.S
 ASSEMBLE    RestoreSettingsAX_RVE.S
 ASSEMBLE    RestoreSettingsVS3V02.S
 ASSEMBLE    RestoreSettingsVS4EXP.S
 ASSEMBLE    RestoreSettingsVS4JAP.S
 ASSEMBLE    RestoreSettingsVS4V06EXP.S
 ASSEMBLE    RestoreSettingsVS4V06JAP.S
 ASSEMBLE    RestoreSettingsYAKRVB.S
 ASSEMBLE    RestoreSettingsYAKRVC.S
 ASSEMBLE    SIGetType.S
 ASSEMBLE    SIInitStore.S
 ASSEMBLE    SIIntrruptHandler.S
 ASSEMBLE    SITransfer.S
 ASSEMBLE    SonicRidersCopy.S
 ASSEMBLE    SwitcherPrs.S
 ASSEMBLE    TCIntrruptHandler.S
 ASSEMBLE    __ARHandler.S
 ASSEMBLE    __CARDClearStatus.S
 ASSEMBLE    __CARDReadStatus.S
 ASSEMBLE    __DSPHandler.S
 ASSEMBLE    __DVDInterruptHandler.S
 ASSEMBLE    __GXSetVAT.S
 ASSEMBLE    codehandler_stub.S
 ASSEMBLE    patch_fwrite_GC.S
 ASSEMBLE    patch_fwrite_Log.S
 STRIP       ARQPostRequest.elf
 STRIP       ARStartDMA.elf
 STRIP       ARStartDMA_Hook.elf
 STRIP       ARStartDMA_PM.elf
 STRIP       ARStartDMA_TC.elf
 STRIP       CalcGXWidescreen.elf
 STRIP       CalcWidescreen.elf
 STRIP       CalcWidescreenDiv.elf
 STRIP       CheckTestMenu.elf
 STRIP       CheckTestMenuGP.elf
 STRIP       CheckTestMenuVS.elf
 STRIP       CheckTestMenuYakyuu.elf
 STRIP       DVDLowAudioBufferConfig.elf
 STRIP       DVDLowAudioStream.elf
 STRIP       DVDLowRequestAudioStatus.elf
 STRIP       DVDSendCMDEncrypted.elf
 STRIP       DatelTimer.elf
 STRIP       EXIDMA.elf
 STRIP       EXIGetID.elf
 STRIP       EXIImm.elf
 STRIP       EXILock.elf
 STRIP       EXIProbe.elf
 STRIP       EXISelect.elf
 STRIP       FakeAIInterrupt.elf
 STRIP       FakeEntryLoad.elf
 STRIP       FakeInterrupt.elf
 STRIP       FakeInterrupt_DBG.elf
 STRIP       FakeInterrupt_Datel.elf
 STRIP       FakeRSWLoad.elf
 STRIP       FakeRSWStore.elf
 STRIP       GCAMSendCommand.elf
 STRIP       GXInitTlutObj.elf
 STRIP       GXLoadTlut.elf
 STRIP       MajoraAudioStream.elf
 STRIP       MajoraLoadRegs.elf
 STRIP       MajoraSaveRegs.elf
 STRIP       OSExceptionInit.elf
 STRIP       OSReportDM.elf
 STRIP       PADControlAllMotors.elf
 STRIP       PADControlMotor.elf
 STRIP       PADControlMotorGP.elf
 STRIP       PADIsBarrel.elf
 STRIP       PADRead.elf
 STRIP       PADReadF.elf
 STRIP       PADReadGP.elf
 STRIP       PADReadVS.elf
 STRIP       PADReadVS3.elf
 STRIP       ReadROM.elf
 STRIP       RestoreSettingsAX_RVC.elf
 STRIP       RestoreSettingsAX_RVD.elf
 STRIP       RestoreSettingsAX_RVE.elf
 STRIP       RestoreSettingsVS3V02.elf
 STRIP       RestoreSettingsVS4EXP.elf
 STRIP       RestoreSettingsVS4JAP.elf
 STRIP       RestoreSettingsVS4V06EXP.elf
 STRIP       RestoreSettingsVS4V06JAP.elf
 STRIP       RestoreSettingsYAKRVB.elf
 STRIP       RestoreSettingsYAKRVC.elf
 STRIP       SIGetType.elf
 STRIP       SIInitStore.elf
 STRIP       SIIntrruptHandler.elf
 STRIP       SITransfer.elf
 STRIP       SonicRidersCopy.elf
 STRIP       SwitcherPrs.elf
 STRIP       TCIntrruptHandler.elf
 STRIP       __ARHandler.elf
 STRIP       __CARDClearStatus.elf
 STRIP       __CARDReadStatus.elf
 STRIP       __DSPHandler.elf
 STRIP       __DVDInterruptHandler.elf
 STRIP       __GXSetVAT.elf
 STRIP       codehandler_stub.elf
 STRIP       patch_fwrite_GC.elf
 STRIP       patch_fwrite_Log.elf
 BIN2H       ARQPostRequest.bin
 BIN2H       ARStartDMA.bin
 BIN2H       ARStartDMA_Hook.bin
 BIN2H       ARStartDMA_PM.bin
 BIN2H       ARStartDMA_TC.bin
 BIN2H       CalcGXWidescreen.bin
 BIN2H       CalcWidescreen.bin
 BIN2H       CalcWidescreenDiv.bin
 BIN2H       CheckTestMenu.bin
 BIN2H       CheckTestMenuGP.bin
 BIN2H       CheckTestMenuVS.bin
 BIN2H       CheckTestMenuYakyuu.bin
 BIN2H       DVDLowAudioBufferConfig.bin
 BIN2H       DVDLowAudioStream.bin
 BIN2H       DVDLowRequestAudioStatus.bin
 BIN2H       DVDSendCMDEncrypted.bin
 BIN2H       DatelTimer.bin
 BIN2H       EXIDMA.bin
 BIN2H       EXIGetID.bin
 BIN2H       EXIImm.bin
 BIN2H       EXILock.bin
 BIN2H       EXIProbe.bin
 BIN2H       EXISelect.bin
 BIN2H       FakeAIInterrupt.bin
 BIN2H       FakeEntryLoad.bin
 BIN2H       FakeInterrupt.bin
 BIN2H       FakeInterrupt_DBG.bin
 BIN2H       FakeInterrupt_Datel.bin
 BIN2H       FakeRSWLoad.bin
 BIN2H       FakeRSWStore.bin
 BIN2H       GCAMSendCommand.bin
 BIN2H       GXInitTlutObj.bin
 BIN2H       GXLoadTlut.bin
 BIN2H       MajoraAudioStream.bin
 BIN2H       MajoraLoadRegs.bin
 BIN2H       MajoraSaveRegs.bin
 BIN2H       OSExceptionInit.bin
 BIN2H       OSReportDM.bin
 BIN2H       PADControlAllMotors.bin
 BIN2H       PADControlMotor.bin
 BIN2H       PADControlMotorGP.bin
 BIN2H       PADIsBarrel.bin
 BIN2H       PADRead.bin
 BIN2H       PADReadF.bin
 BIN2H       PADReadGP.bin
 BIN2H       PADReadVS.bin
 BIN2H       PADReadVS3.bin
 BIN2H       ReadROM.bin
 BIN2H       RestoreSettingsAX_RVC.bin
 BIN2H       RestoreSettingsAX_RVD.bin
 BIN2H       RestoreSettingsAX_RVE.bin
 BIN2H       RestoreSettingsVS3V02.bin
 BIN2H       RestoreSettingsVS4EXP.bin
 BIN2H       RestoreSettingsVS4JAP.bin
 BIN2H       RestoreSettingsVS4V06EXP.bin
 BIN2H       RestoreSettingsVS4V06JAP.bin
 BIN2H       RestoreSettingsYAKRVB.bin
 BIN2H       RestoreSettingsYAKRVC.bin
 BIN2H       SIGetType.bin
 BIN2H       SIInitStore.bin
 BIN2H       SIIntrruptHandler.bin
 BIN2H       SITransfer.bin
 BIN2H       SonicRidersCopy.bin
 BIN2H       SwitcherPrs.bin
 BIN2H       TCIntrruptHandler.bin
 BIN2H       __ARHandler.bin
 BIN2H       __CARDClearStatus.bin
 BIN2H       __CARDReadStatus.bin
 BIN2H       __DSPHandler.bin
 BIN2H       __DVDInterruptHandler.bin
 BIN2H       __GXSetVAT.bin
 BIN2H       codehandler_stub.bin
 BIN2H       patch_fwrite_GC.bin
 BIN2H       patch_fwrite_Log.bin
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/kernel/asm'

Building FatFS library for ARM

make -C fatfs -f Makefile.arm
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/fatfs'
CC      ff-arm.o
CC      ff_utf8-arm.o
AR      libfatfs-arm.a
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/fatfs'

Building Nintendont code handler

make -C codehandler
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/codehandler'
 COMPILE     codehandler.s
 STRIP       codehandler.s
 OBJCOPY     codehandler.s
 BIN2H       codehandler.bin
 COMPILE     codehandleronly.s
 STRIP       codehandleronly.s
 OBJCOPY     codehandleronly.s
 BIN2H       codehandleronly.bin
rm codehandler.bin codehandleronly.bin
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/codehandler'

Building Nintendont kernel

make -C kernel
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/kernel'
AS      start.o
CC      common.o
CC      alloc.o
CC      GCAM.o
CC      JVSIO.o
CC      JVSIOMessage.o
CC      FST.o
CC      DI.o
CC      RealDI.o
CC      Patch.o
CC      PatchTimers.o
CC      TRI.o
CC      PatchWidescreen.o
CC      ISO.o
CC      Stream.o
CC      adp.o
CC      EXI.o
CC      SRAM.o
CC      SI.o
CC      HID.o
CC      diskio.o
CC      Config.o
AS      utils_asm.o
CC      ES.o
CC      NAND.o
CC      main.o
AS      syscalls.o
CC      ReadSpeed.o
CC      vsprintf.o
CC      string.o
CC      prs.o
CC      SDI.o
CC      usb.o
CC      usbstorage.o
CC      lwbt/bte.o
CC      lwbt/btmemb.o
CC      lwbt/btmemr.o
CC      lwbt/btpbuf.o
CC      lwbt/hci.o
CC      lwbt/l2cap.o
CC      lwbt/physbusif.o
CC      BT.o
LD      kernel.elf
ZIP     ../loader/data/kernel.zip
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/kernel'

Building Nintendont HID

make -C loader/source/ppc
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/loader/source/ppc'
 COMPILE     PADReadGC.c
 OBJCOPY     PADReadGC.bin
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/loader/source/ppc'

Building Nintendont loader

make -C loader
make[1]: Entering directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/loader'
/c/Users/Michael:1: *** target pattern contains no `%'.  Stop.
make[1]: *** [build] Error 2
make[1]: Leaving directory `/c/Users/Michael John Blanton/Downloads/Nintendont-master/loader'
make: *** [loader] Error 2

**Comment by GerbilSoft** [comment]
There's a space in the path. `make` doesn't like spaces in the path.
