### ISSUE TITLE
nintendont freezes on loading devices

### ISSUE THREAD

**Issue by atsoka** [FIX94/Nintendont#358]
its the first time i intalled nintendonts, download boot, meta and icon, and put the games on /games/, but when i start nintendots from hbc, says. loadins ios58, then checking devices, and then it freezes there, cant select anything nor reset, must unplug my wii.

**Comment by carnage702** [comment]
nintendont version you are using say number not "latest"
wiiu or wii
sd or usb

**Comment by jjaldridge2009** [comment]
This happens to me as well on version 4.432

Games are on USB formatted FAT32, 32kb clusters

**Comment by carnage702** [comment]
im guessing your hdds arent correctly formated, some user said he just switched the enclosure with the same hdd and it worked so yeah some enclosures or foramted specialy partitioned formats get issues on nintendont.

**Comment by jjaldridge2009** [comment]
I'll try doing a full format, instead of a quick format and report back. If that doesnt' work, I'll try a different usb

**Comment by jjaldridge2009** [comment]
Okay so, clean format actually worked... at first.

Was able to get past "checking storage devices" into the SD/USB select screen. However, I could not choose between SD or USB, My gamecube controller stopped working. I figured I'd try booting from USB Loader GX instead, maybe the new Smash 4-era gamecube controllers are funky.

So I boot from USB loader and I got to the "creating virtual memory card" portion.

It got thru 2048 kb of 2048 kb, and then it held there for a while. Then the Wii turned itself off.

Upon restarting Nintendont, I can no longer get past the "Checking storage devices..." portion of the loading menu, even after deleting the save file that was created.

**Comment by carnage702** [comment]
im guessing your hdd usnt compatible, try another usb device.

**Comment by atsoka** [comment]
i try changing the format of the hdd, still same, then, checking on internet i found an older version of nintendont from may, downloaded it and it works, i havent update it, but its working now, except for mi hdd, its on wii format but cant read the folder, but i prefer put GCN games on a usb, bthan format my hdd, thanks anyway

**Comment by Zetchzie** [comment]
Your update broke something my 500gb WD mypassport formated to fat32 32k clusters and it takes 5mins to load also games are slower yet wii games work fast on usbloader gx
