### ISSUE TITLE
I cannot play multiplayer

### ISSUE THREAD

**Issue by fabigilbertolotti** [FIX94/Nintendont#364]
Hello. Congratulations, the app works really well! But i have only one serious problem over there... I cannot play in multiplayer.
I have 4 oficcial wiimotes and 3 official classic controllers... But nintendon't seems to recognize only the first one: The player 1 controller. I don't have this issue with the others gamecube emulators... Only nintendon't.
I entered settings, i activated 4 players, but all remains the same... Only wiimote 1 seems to work.
When i try with the others wiimotes, they have only the fourth light on... Even if there's 3 or 4 wiimotes activated at the same time! All of them (with the only exception of "wiimote 1") have the same fourth light activated at the same time... not the second, not the third light... only the 4th. How is this possible? I even tried to change my nintendont for a newer version, but all remains the same. Do i have to download something to make my other controllers work, so i can play multiplayer?
Please, Help.

**Comment by carnage702** [comment]
do you have any hid controller or gc controller pluged in? is maxpads set to 4? is native set to off? are you using nintendont directly from the homebrew channel?

**Comment by fabigilbertolotti** [comment]
no, i don't have any HID or gc controller plugged. Yeah, maxpads is set to 4 and native is set to off. And yes, I am using nintendon't from the homebrew

**Comment by carnage702** [comment]
there is 2 possibilities are the other wiimotes paired with the console already? can they be used to move and select stuff on the homebrew channel?

second one is you only have one official wiimote and/or CC and think the others are too and they arent.

check the screws, every official nintendo stuff has triwing screwswhile fakes/third partys have normal screws.

**Comment by fabigilbertolotti** [comment]
they are paired. Yes, they can select stuff and move around o the homebrew channel.
Now that you mention it. One of the wiimotes is white and have the normal "cross" screws. The other 3 are black and have that special screws of Nintendo. I'm afraid that the white one is fake... But the others not.

**Comment by carnage702** [comment]
what about the CC? do they all have trywing screws instead of cross ones?

**Comment by fabigilbertolotti** [comment]
what is CC?

**Comment by fabigilbertolotti** [comment]
They even seem to work at the nintendont game menu... the just don't work when i play a game. Only the wiimote 1 works succesfully.
When i'm in a game and try to press any button on the other wiimotes, i can see for a split of second that the second light turns on and then the fourth light... where it remains until i quit the game or turn off the console.

**Comment by carnage702** [comment]
nintendont only allows wiimotes to works with cc or nunchucks, and yes CC is classic controllers.

every thing you are saying seems to be fake wii remotes or CC since those ususaly work on menu and not ingame.

do this do not use your confirmed wiimote that works leavue it unpluged, then just connect the CC that was attached to it to one of your others wiimotes one at a time and try to play any game if the remote doesnt work  alone with that wiimotes CC on any game then its a fake wiimote, there are some fakes with trywing screws too and unless you bought them yourself sealed on a shop and not online there is no garantted they are official.

**Comment by fabigilbertolotti** [comment]
The problem persist... if they are really fake, is there any way to make them work?

**Comment by carnage702** [comment]
so they dont work alone with a classic controller either? then they are fake and no there is no way to make them work becuase fake controller used very wierd codding and nintendont doesnt know how to handle them becuase  they dont comunicate with standard code.

**Comment by fabigilbertolotti** [comment]
DAMM!

**Comment by fabigilbertolotti** [comment]
That explains everything
