### ISSUE TITLE
RESLAB metroid prime 3

### ISSUE THREAD

**Issue by thenintendofreak** [FIX94/Nintendont#366]
I have a problem with a game not booting. I thought it would work because Nintendont is a modified wii kernel and I believed it would utilize all the wii memory. Not sure if this is even possible to fix. So if it is not a true issue it's ok
Because the game requires more memory due to the fact it was created in between GameCube and wii 
Thanks

**Comment by carnage702** [comment]
mp3 alpha needs 128mb ram to work wich the wii doesnt have ...

**Comment by GerbilSoft** [comment]
There are some debug Wiis that have 128 MB RAM... in the wrong region. These Wiis have 128 MB MEM2; the GCN Metroid Prime prototype requires 128 MB MEM1.

All retail models, of course, have 24 MB MEM1 and 64 MB MEM2, so that's basically a moot point.
