### ISSUE TITLE
Animal crossing will not save via emulated memory card

### ISSUE THREAD

**Issue by thenintendofreak** [FIX94/Nintendont#367]
The game boots fine in the beginning a detects the card but when I go to save by the house it keeps me at "saving town data" forever. The game didn't freeze or anything it just won't save so the only way to end the game is to quit. (It's stuck on saving, the still runs while saying it)

**Comment by thenintendofreak** [comment]
Forgot to say that I'm running the Jan 21(27?) 2017 release

**Comment by carnage702** [comment]
game saves fine for everyone else using sd/usb? take a picture of your nintendont settings.

**Comment by cheatfreak47** [comment]
I can't reproduce this either. Considering the lack of response from the original reporter, it may be best to close this.
