### ISSUE TITLE
"An error has occurred" - Paper Mario The Thousand Year Door

### ISSUE THREAD

**Issue by zacharyvincze** [FIX94/Nintendont#369]
For some reason, when I'm playing Paper Mario The Thousand Year Door, the game decides to crash and gives me the error "An error has occurred".  It tells me to refer the the Gamecube manual so I'm guessing this happens when there is a disk read error.

This seems to happen at random (When the game tries to load something from the disk).

I have Memcard emulation turned on and I am using a Lexar 8GB USB Flash Drive to run the games off of.  Is it the USB drive I'm using that's the problem?  I have no clue, but some help with this issue would be excellent.

**Comment by GreyWolfSC** [comment]
Did you check the game MD5?

**Comment by SevenWillis** [comment]
Is it a 1:1 rip?

**Comment by carnage702** [comment]
also take a picture of your nintendont settings, this error happens usualy when the usb/sd card cant keep up with the speed required by the game reads, wich can be some options being turned on that shouldnt or just a very slow  usb device.

**Comment by zacharyvincze** [comment]
Turned out to just be the USB I was using.  The game might've been reading faster than the USB could handle.  Everything seems fine now, I haven't received any more of those errors.
