### ISSUE TITLE
Nintendont error message

### ISSUE THREAD

**Issue by mrhale** [FIX94/Nintendont#373]
Hi,

I am using Nintendont through Homebrew on my Wii and am currently using an 8GB SD card with what I believe are all of the components necessary to run Nintendont correctly. I say this having successfullly started and played Super Smash Brothers Melee with no problems.

I have place a couple more iso files, renamed as "game.iso", in their own [separate] folders inside the "games" folder on the SD card.

The issue I am having is once I am in Nintendont and I attempt to start one of the games from the list I receive the following error message:

CheckForMultiGameAndRegion() = failed

After about 3-4 seconds, it automatically kicks me out of Nintendont and back to the Homebrew page where I originally selected Nintendont from my program choices.

What am I doing wrong?
Do I need to "prepare" the iso in some other way than renaming it "game.iso" and placing it in its own folder within the "games" folder? (btw: I get the whole "game.iso."iso renaming challenge...it's not that.)

If I don't need to prepare the iso, why am I receiving this message and what can I do to resolve this issue.

Thank you for your  time and assistance!
Henry

**Comment by GerbilSoft** [comment]
This is a known issue on some systems. I'm working on adding extra debugging to that function, which should help to narrow it down.

**Comment by carnage702** [comment]
are you using nintendont directly? or through usbloader or something? does selecting ssbm still works? maybe your nintendont dol went corrupt try to delete the boot dol and redownload it, also try to delete your ninconfig.bin and make sure your sd card isnt locked.

**Comment by mrhale** [comment]
I downloaded boot.dol, along with ninconfig.bin. After rebuilding the contents of the SD card, I copied the roms over. It now works perfectly! Even though SSBM continued to work throughout this issue, something must've been wrong with the original two nintendont files.

Anyway, I appreciate both of your responses. Thank you!

**Comment by carnage702** [comment]
sometimes a boot.dol is corrupted when transfering to the usb or even downloading from github.
