### ISSUE TITLE
Issues with Melee and GameCube controller

### ISSUE THREAD

**Issue by FateForWindows** [FIX94/Nintendont#375]
When I attempt to play Melee with a GameCube controller, the game either hangs or stays on a black screen for a while before saying to power off the GameCube (in my case it's an original Wii). Additionally, if I try to connect it mid-gameplay, it usually will freeze loop the last ~2 seconds of the background music 4-5 times and give the same error. If I disconnect it, the game plays fine, however it's difficult to play the game with a wiimote and nunchuk (the only thing I have for playing the game with since XInput controllers like the Xbox One controller don't work). I've tested this on the latest version (4.496 I believe) with both NTSC 1.0 and 1.2/1.02. I have tried Native Control but that doesn't work either. Other games work perfectly like Sonic Adventure 2. Are there any solutions?

**Comment by carnage702** [comment]
is it an official controller or some fake/3rd party gc controller?

last version of nintendont is 4.436, the issue your talking about is unheard.
 your using an md5 checked iso? are you inserting the gc controller on port1 of the wii? you dont any anything on slot b of the memory card?

if with native on it still does that then its the controller doing some shifty thing, with native on nintendont doesnt even touch the controller code it straight up uses gc original controller code.

so lets try this first tell me if your gc cotroller is official or fake/3rd party.
second check to see if your ssbm isos are full isos and md5 cheked to match redump
thrid take a picture of your nintendont settings.

**Comment by FateForWindows** [comment]
I'm using a 3rd party controller, that might be why. Strangely it seems to work with Brawl.

Also, yes, the iso was md5 checked and I am using Port 1 and (because Melee requires it) Slot 1. I'll send a picture later.

**Comment by carnage702** [comment]
well that is probably the issue, i got a 3rd party gc controller that doesnt even work on the wiiu gc adapter on msash4 and worked fine on the gc for instance. also you sure you dont have any on wii memory card slot b?

**Comment by FateForWindows** [comment]
I only have one memory card and Melee doesn't allow Slot B. The memcard works fine with the wii remote.

**Comment by carnage702** [comment]
not sure what to tell you then all i can say is take a picture of your nintendont settings.

**Comment by FateForWindows** [comment]
I'll try that as soon as I can.

**Comment by FateForWindows** [comment]
My friend tried to use his GameCube controller (an official one) and it didn't work, so I'm trying another USB device. I'll take a picture of my settings as soon as possible but right now I only have my laptop's webcam.

**Comment by FateForWindows** [comment]
I think I figured it out, the partition is not the first one in the partition table.

**Comment by FateForWindows** [comment]
Closing this issue since I know the cause now, I tried a few other non-disc games and they had the same issues as well.

**Comment by FateForWindows** [comment]
Fixed the issue with my partition table but still having problems. I can confirm that this is fixed because USB1 and USB2 have been swapped in USB Loader.

**Comment by FateForWindows** [comment]
![img_20170430_122331_hdr](https://cloud.githubusercontent.com/assets/14127573/25566015/ffdc7e80-2d9f-11e7-810e-ed3f33d62989.jpg)

**Comment by FateForWindows** [comment]
I haven't updated yet but here's the settings.

**Comment by carnage702** [comment]
with native on there is not controller patches, its pure gc controller code so if its still freezing with your console theres something damaged somewhere.

**Comment by FateForWindows** [comment]
Oops, thanks for pointing that out :P It's the exact same as auto though, but that might be causing the issues.

**Comment by FateForWindows** [comment]
Also now it's refusing to work whether I have a controller and memcard or not.

**Comment by carnage702** [comment]
my best guess is a corrupted file be it nintendont or iso.

do this redownload nintendont from scratch and delete any inis,ninconfig bin and such from your device, then try again.

**Comment by FateForWindows** [comment]
Turns out neither were corrupted, it seems to be the hard drive (the way it's set up, not the drive itself). Since I have a backup of my entire old PC on there, I didn't want to lose it. I gave up until today, when I found out two things were/could be causing Nintendont to not read the game off my USB stick (not the external hard drive, a standard USB stick):

1. There was a corrupted file for SA2 in my games folder from a failed attempt by USB Loader to dump it (it froze, had more than enough space though). This was causing my Linux computer to fail to read the games folder. My PC couldn't see it, but read-wise, my old 10.6 Mac was able to detect the corrupted file and read the games folder and repaired the disk.
2. This is probably the big mistake I made, and it's an obvious one: game.iso.iso. 'Nuff said.

After I fixed the two things above, Nintendon't loaded, and Hallelujah! It found the iso! This was the same iso as before, by the way. Well, I launched the game up, anxious, and guess what? Black screen.

Just kidding.

The game worked like a charm! It ran at a fluid framerate and ran perfectly! I didn't even notice any beeps. What's even better is that the controller I used is the third party controller I was using before. No problems!

Thank you for helping me out here.

**Comment by carnage702** [comment]
so there was a corrupted file after all same for a bad renamed iso, but it was probably the corruption main issue.

**Comment by FateForWindows** [comment]
If you read, I tried an entirely different USB flash drive that didn't work before, instead of the hard drive.nI checked the hard drive and there aren't any errors or corrupted files. The iso was renamed properly on the other drive, it just seems like the partition setup was causing issues since HBC was having issues launching apps from the FAT32 partition (USB Loader doesn't have any issues).

Since my USB stick has a single-partition setup with just FAT32, I didn't have any issues whatsoever related to that. I don't even know if the corrupted file actually affected Nintendont.

But here's the logical conclusion here: if you want to use Nintendont, a single-partitioned compatible USB HDD is your best bet.
