### ISSUE TITLE
Melee won't load when using USB Loader GX

### ISSUE THREAD

**Issue by itsjimbofresh** [FIX94/Nintendont#377]
Hey! I have a small issue I hope can be resolved. I hate the latest issue of both USB loader GX & Nintendont on my Wii. When I launch Nintendont from the HBC all my games load perfectly from both SD cards and USB flash drives with the games loaded on them. When I go into USB Loader gx however, I have an issue. My paths seem to be all correct (set path to my Nintendont) because when I boot Super Mario Sunshine or other games they will go into Nintendont & load. But Melee will just halt at a black screen and not load. Melee does indeed work perfect if I boot it from right from  Nintendont, but why docI have this issue with USB loader gx? It seems to be the only game that has a black screen when launching from USB loader. Is there any other info I can provide to fix this? I just want to have my Wii games & Gamecube games all in USB loader and to boot correctly so any advice would mean alot, thanks!!

**Comment by itsjimbofresh** [comment]
I have* not hate, sorry

**Comment by carnage702** [comment]
since it works directly from nintendont then it isnt a nintendont issue is it?

but try to delete your config from nintendont and try again.

**Comment by itsjimbofresh** [comment]
Thanks, I guess youre right. But what do you mean to delete my config from nintendont? Not sure I understand but thanks for the speedy reply @carnage702

**Comment by carnage702** [comment]
nintendont creates a config,bin everytime is launched so maybe usbloadergx wrote something bad in there, or your usbloadergx options for nintendont are forcing some settings ssbm doesnt like that the default nintendont doesnt force it.

**Comment by itsjimbofresh** [comment]
Hi, just wanted to post how I fixed my issue with the gamecube games. If you have everything set up, and it goes black - go into USB loader settings and change the gamecube video mode from auto to system default! Should boot up right after
