### ISSUE TITLE
F-Zero AX memory card support

### ISSUE THREAD

**Issue by yoshifan** [FIX94/Nintendont#378]
F-Zero AX's Gamecube memory card support would enable two things:

- Load vehicles from an F-Zero GX garage file, for use in F-Zero AX. This is the only way to use certain custom vehicle parts in F-Zero AX, including the Mars -EX booster, which is probably the best booster for AX Time Attack.
- Transfer vehicles and custom parts you use in F-Zero AX to an F-Zero GX savegame file, in the event that the GX savegame doesn't have those things unlocked yet. Finishing AX races should also give tickets to the GX save.

I can't get AX to recognize my memory card in Nintendont 4.436 (2017/02/05). I have a GC memory card in Slot A of my original-model Wii, and the memory card has an F-Zero GX garage file. After pressing Start at the title screen:

- If Nintendont **does** have license card data saved, that license card data is auto-loaded and the memory card isn't loaded. Then the game moves on to the license card screen. Before that, the announcer says "insert the memory card before inserting the F-Zero license card", so I'm guessing that means the memory card was skipped.
- If Nintendont **doesn't** have license card data, nothing automatic happens on the insert memory card / insert license card screen. None of the GC controller buttons do anything except the A (accelerator) buton, which moves onto the menu prompting to create a license card / play without a license card. Whatever I choose, the memory card doesn't get loaded.

I tried a US-formatted memory card with a F-Zero GX US version garage file, and same for JP. Neither worked. I think my AX iso is revision D, judging from the file `AX_RVDsettings.bin` that was created on my SD card.

Last time I heard, F-Zero AX memory card support wasn't working and the dev(s) didn't seem sure how to make it work - but that was around 2 years ago, maybe closer to 3. I'm not sure of the status now. If it's supposed to work, I'm wondering what I'm doing wrong; if this is all old news, I'd like to be reminded about what's stopping it from working (if that is known).

Let me know if I can do anything to help test this, such as providing a GX garage .gci file.

**Comment by FIX94** [comment]
Well the problem is that the game just crashes on any form of memory card access so I hardcoded it to be disabled to run at all, and indeed last time I looked at it I was unable to find any cause for the crashing so that is sitll in place.

**Comment by yoshifan** [comment]
Okay, yeah, that sounds kinda familiar. Thanks for the quick reply.

I'm not sure if/when I'll get around to learning the Nintendont code, but might as well ask: where is this hardcoded? And is it simple to change the code to switch memory card access on, in order to see the crash for myself?

**Comment by yoshifan** [comment]
Also: By any chance, did you try memory cards in AX revision C? For what it's worth, it seems the GUI related to memory cards is slightly different there:

Title screen:

- Revision C has a box on the upper-left saying "NINTENDO GAMECUBE Memory Card can not be used at this time."
- Revision D and E have no such box.

License card setup screen:

- Revision C's bottom box says "NINTENDO GAMECUBE Memory Card can not be used at this time."
- Revision D and E's bottom box says "Playing without the Memory Card."

**Comment by yoshifan** [comment]
It doesn't seem like the recent memcard-related commit has changed this issue, unless I missed something.

**Comment by carnage702** [comment]
this will never be added since fix94 said every memory card acess crashes the game remenber nintendont got quadforce ported into it so unless you can ask crediar to use the arcade machine he got to find the memory card patches there is no "fix"

**Comment by yoshifan** [comment]
I see. Well, thanks for confirming the status.
