### ISSUE TITLE
Crazy Taxi Visual Artifacts

### ISSUE THREAD

**Issue by YellowMacho** [FIX94/Nintendont#380]
First post here so sorry if this is the wrong location.  U.S. Release of Crazy Taxi has nonstop black artifact boxes while in game.  Menus are fine.  This is on version 4.436.

**Comment by carnage702** [comment]
im guessing you either have a bad iso or are forcing widescreen/progressive on it.

**Comment by YellowMacho** [comment]
No prog or widescreen patches are applied, but I'll try verifying the iso's
integrity.

On Mar 14, 2017 2:20 PM, "pedro702" <notifications@github.com> wrote:

im guessing you either have a bad iso or are forcing widescreen/progressive
on it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FIX94/Nintendont/issues/380#issuecomment-286531562>,
or mute
the thread

**Comment by carnage702** [comment]
also take a picture of your nintendont settings, it always helps.

**Comment by YellowMacho** [comment]
Here are my settings and a link to a video of the issue.

![20170314_163619](https://cloud.githubusercontent.com/assets/19942718/23923963/d94821cc-08d6-11e7-849e-cd179cdefe24.jpg)

![20170314_163619](https://cloud.githubusercontent.com/assets/19942718/23923965/da50ff30-08d6-11e7-8b00-2e7a6a45d086.jpg)

https://www.youtube.com/watch?v=vBNDz8VMJI4&feature=youtu.be

**Comment by YellowMacho** [comment]
Doesn't appear to be the ISO, really not sure what could be causing this.

**Comment by FIX94** [comment]
from my knowledge I would say that your console gpu is close to death from the looks of it, artifacts like that are a good indicator for that.

**Comment by YellowMacho** [comment]
Don't think that's it either really, I have ~35 games of different degrees of graphical intensity and this is the only game to show any sort of unusual behavior.

**Comment by carnage702** [comment]
does your iso md5 matches redump?
also using sdcard or usb?

**Comment by YellowMacho** [comment]
I'm using USB.

Here is a confirmation that the md5 is accurate:
http://imgur.com/a/wl7vU

**Comment by ViiMaster** [comment]
Like FIX94 said... unfortunatelly your GPU is dying. I have two Wii consoles. One started doing the same and it only got worse over time...

**Comment by YellowMacho** [comment]
The issue does indeed to appear to be GPU failure.  It has had the occasional off color pixel issue with other games in the past which I assumed to be the fault of my HDMI converter.  It seems crazy taxi is just the first game (of 40!) to properly rear its ugly head.  You can bet I'll be purchasing a new Wii and homebrewing it again!  RIP lil buddy.
