### ISSUE TITLE
Sonic Heroes menu bug

### ISSUE THREAD

**Issue by Yeniaul** [FIX94/Nintendont#381]
Well, here we go again... On trying to load the Sonic Heroes team selection menu, the game will hang. This does not occur in Dolphin. It seems like the drive might be timing out, as the actual "hang" occurs 10 seconds AFTER trying to load said menu. Enabling the Drive LED reveals that data is read and/or written up until around .5 seconds of the hang. I'm using the USA version, Nintendont version... latest.

**Comment by carnage702** [comment]
take a picture of your nintendont settings, also is your iso a 1:1 iso md5 cheked with redump md5? just because dolphin works doesnt mean anything at all.

**Comment by Yeniaul** [comment]
It is classified as a 1:1 by Nintendont. Hash checks pass. Settings attached.
![20170320_164224](https://cloud.githubusercontent.com/assets/13092842/24123297/eba87bfe-0d8c-11e7-858b-32cf9f2ec42d.jpg)

**Comment by carnage702** [comment]
turn log and osreport to off... why do you have this on? this crashes 80% of all games, this is for devs only.and cheats too also if you dont have any for that game and even if you do it might crash the game depending on the cheat.

i see you have video width value too, some games dont like this setting either and crash like f zero among others.

to try a game first turn everything off  and auto then try it, if it works you can try startint settings on it.

you dont need native to be on even for the gc controller incase you didnt knew but this doesnt hurt anything  so it makes no diference. language should be auto too  it will default to english if your console is in english unless it isnt in that case yeah english is fine.

**Comment by Yeniaul** [comment]
Ah, cool. Thanks. I actually had no idea about that, I thought OSReport was logging the game instead of "Homebrew Channel" in the Play Log. xD whoops. I have Native Control on due to button activators. I'll give that a shot. BRB...

**Comment by Yeniaul** [comment]
That fixed it. Thanks!
