### ISSUE TITLE
Is this a new error or something? (error -116)

### ISSUE THREAD

**Issue by suolo** [FIX94/Nintendont#382]
I've been looking for a solution for this error all day now and I've just about given up. The problem that occurs is whenever I try to update nintendont or get the controller zip, the wii u stutters, and then tells me  "update error:  -116". It would be a big help if someone can help me figure it out. 

I'm using:
A sony micro sd card 32 gb
Wii U with CFW
1 TB WD Passport Ultra USB Drive

PS: I've tried using the drive as well, but the results are the same. I'm using nintendont version 3.24
and don't know where to go to get the updated version.

**Comment by suolo** [comment]
Oh

**Comment by carnage702** [comment]
what nintendont version do you have to begin with?

also you are sure you have internet on your wiiu?did you opened the browser to check.

**Comment by carnage702** [comment]
https://github.com/FIX94/Nintendont/raw/a1e4a337f903f5d229c658f5bcf61ab4de372ba7/loader/loader.dol

download this and rename it to boot.dol and replace it on your nintendont app folder.

also delete your ninconfig just to be safe before launching it.

**Comment by suolo** [comment]
Thank you for your suggestion. This instantly fix the problem. I knew I could use internet because it allowed me to download covers for usb loader gx 5 mins prior to when this issue occured.  I all know bout my version of nintendont was that it was v3.
