### ISSUE TITLE
Tomb Raider Legend widescreen patch

### ISSUE THREAD

**Issue by Haendelh** [FIX94/Nintendont#383]
In the [compatibility list](https://wiki.gbatemp.net/wiki/Nintendont_Compatibility_List), it says the Europe version of Tomb Raider Legend supports widescreen hack, but I enabled it and it keeps on 4:3 ratio

**Comment by carnage702** [comment]
the compatibility for extra  options is highly outdated/wrong lots of people saw stretched 4:3 and marked as working, if your screen doesnt have sctretched 4:3 is becuase either your wii isnt in widescreen mode or on wiiu you dont have forced wiiu widescreen active alongside forced widescreen.
