### ISSUE TITLE
Controller Issues

### ISSUE THREAD

**Issue by suolo** [FIX94/Nintendont#384]
Just found out that the gamecube adapter will work inside nintendont, but, won't work whilst playing a game. The game that I tested it on was Pokemon Colosseum. Also, I've tested the different types of controllers that I should be able to use and none of them worked. Any suggestions?

**Comment by suolo** [comment]
Just found out that the gamecube adapter will work inside nintendont, but, won't work whilst playing a game. The game that I tested it on was Pokemon Colosseum.

**Comment by carnage702** [comment]
yeah this is an issue if you had it on before updating, wiiu gc adapter is an hid device to obviously it needs it off, go to your sd card/usb and delete you ninconfig.bin

**Comment by suolo** [comment]
Thanks for your help, carnage. You've saved me more than once now. Sorry for relying on you too much.
