### ISSUE TITLE
Controller.ini in a per game basis

### ISSUE THREAD

**Issue by DongVGH** [FIX94/Nintendont#385]
Basically, all i want, is that Controller.ini would be placeable into the individual folders and have Nintendont read one of them from the game folder, if not present, use the one in the device root.

The reason i want this, is for playing Duke Nukem 64 with my USB Pad, so i can remap Z to R1, R to L1 and L to R3 so i can select inventory items with just R3, but i also play other games, and that would need me to plug the USB onto the PC and swap Controller.ini, which is just really bothersome.

**Comment by DongVGH** [comment]
Okay, since this probably wont be added any time soon, i decided to just make the loader look for Controller.ini in "USB:\Apps\NintendontAlt\Controller.ini"

Now, if you want this too, download this http://www.mediafire.com/file/vzyv5vdy5j8b5ww/nintendontalt.zip and unzip into the Apps folder, then change the PNG or Meta.xml by adding custom text to the image or changing the name on the .xml file, so you can difference it, and drop your alternate Controller.ini file in the above mentioned folder, open up your alternate Nintendont in your Wii/ Wii U and Have fun!

**Comment by mistertoze** [comment]
How can I apply this to the current version of Nintendont?
