### ISSUE TITLE
Game freezing

### ISSUE THREAD

**Issue by Ventallo** [FIX94/Nintendont#386]
When I play Legend of Zelda wind waker and twilight princess they keep freezing in the same place. I have photos of my settings and the games md5
[Settings] https://cloud.githubusercontent.com/assets/26951148/24823750/f2262f7a-1bb6-11e7-87e6-649d4ebc8048.jpg
[Twilight Princess]
https://cloud.githubusercontent.com/assets/26951148/24823788/4864606e-1bb7-11e7-9f0b-9f40a95ddb91.jpg
[Wind Waker]
https://cloud.githubusercontent.com/assets/26951148/24823847/e4156972-1bb7-11e7-86de-a74adc9b508f.jpg

**Comment by carnage702** [comment]
what do you mean they keep freezing on the same place? since they are 2 diferent games they cant freeze on the same place since there is noone.

**Comment by Ventallo** [comment]
Sorry for the confusion what I mean is in wind waker when I enter a room in a dungeon the game freeze and the audio becomes messed up.
In Twilight princess I enter a new area in order to proceed in the game. The screen fades into white then it stays white.

**Comment by carnage702** [comment]
seems its an issue with your device try another usb device or even straight up SD beause those games work great and the freezes seems that the hdd or whatveer your using stop sending new data to the game.

Also try redownloadining nintendont boot.dol just incase it isnt corrupted.

**Comment by Ventallo** [comment]
Alright I'll try that when I get home.
