### ISSUE TITLE
Tales of Symphonia audio glitch

### ISSUE THREAD

**Issue by combatistor** [FIX94/Nintendont#387]
Hi, thanks for you awesome work !
I noticed there is still the audio glitch in tales of Symphonia, before starting the battle and after returning to the world map.
I used the latest version of Nintendont, I also tried to load the game via USB or SD card but the result is the same.

**Comment by carnage702** [comment]
take a picture of your nintendont settings.

**Comment by SuperrSonic** [comment]
A picture won't help. FIX94 has acknowledged this issue a couple of times before.

On SSBM
https://gbatemp.net/threads/nintendont.349258/page-1498#post-5638282
On Tales of Symphonia
https://gbatemp.net/threads/nintendont.349258/page-1301#post-5391072

**Comment by carnage702** [comment]
oh yeah the beep thing. if its that he is refering too then yeah no fix tough.

**Comment by combatistor** [comment]
Oh okay, thanks anyway, 
I hope there could be a fix someday

**Comment by carnage702** [comment]
so supersonic you made a video wich has a dol linking and says you fixed those issues? its true or not?

**Comment by FIX94** [comment]
should be good now, just needed to be in the artstartdma exception list.
