### ISSUE TITLE
Nintendont always crashing with these key combo

### ISSUE THREAD

**Issue by batsche** [FIX94/Nintendont#388]
Hi, 

Nintendont is always crashing when I use following key combo:
D-Pad Left + D-Pad Down + L Trigger + R Trigger + Z Button + B Button

I need this combination in SSX Tricky to make a special move. I need to press these whole buttons together and everytime nintendont crashes and the usb loader is restarting.

Tried in other GC games, everytime the same thing. You can press these keys everywhere (title screen fe) and nintendont crashes. 

Tried this direct with HBC -> Nintendont and with USB Loader GX

Is there anyone with the same problem and can you give a fix for that? Otherwise this game is unplayable anymore for me :/

**Comment by carnage702** [comment]
that isnt a crash ...

that is the exit combo for nintendont

dpad down+L+r+b makes nintendont exit the games, to well "fix it"  are you using a wii with gc controllers? if so try turning native on.

**Comment by batsche** [comment]
Ok that's what i guessed too with exit the game... I have a Wii Mote Controller, a Wii Classic Pro Controller and a GameCube Controller.

Where can I do the setting you mean? I would prefer to play on my GC Controller...

**Comment by carnage702** [comment]
if you are on a wii not wiiu when turning the setting on nintendont menu "native  ON" you will disbale all exits, but unfortunely with native set to ON you will loose  the ability to use BT controllers like  classic controller and only gamecube controllers will work through the wii gc ports.

**Comment by rootyElf** [comment]
I made a build which has got a different shutdown combo. Check out this issue: #328

**Comment by batsche** [comment]
@rootyElf you are my hero! My left thumb is damaged cause I made all the tricks yesterday with a cheap gamecube controller which buttons are not so smooth to press ;)

Is your build up to the latest version of nintendont? Do I only have to overwrite the files with your build or do I have to install it?

**Comment by rootyElf** [comment]
@batsche I compiled the master branch of this repo 2 days ago, so it should be as recent as it gets (as of now). Just put it on your SD card as you would with a normal build.

**Comment by batsche** [comment]
@rootyElf yeah tried it yesterday and it worked :+1: no crash, so I can play SSX Tricky with every controller i want - awesome work! Thank you!
