### ISSUE TITLE
Pokemon Box Adventure Mode doesn't work.

### ISSUE THREAD

**Issue by kleinlordspitzi** [FIX94/Nintendont#389]
When i selecting the Adventure Mode i turn on my GBA, then it transfer something. And then comes the 
GameBoy Advance Bootscreen. So but it just like when i turn on my GBA without an Game Cartridge in it.

Also i'm sorry for my poor English. :)

**Comment by GB-CG** [comment]
Duplicate of https://github.com/FIX94/Nintendont/issues/224
