### ISSUE TITLE
3 Games By BlueTongue Entertainment need Timer Patches

### ISSUE THREAD

**Issue by cheatfreak47** [FIX94/Nintendont#390]
Pre-rendered video for these games developed by Bluetongue Entertainment play at approximately 1.5 times as fast on Nintendont as on Dios Mios or GC hardware, meaning it likely needs a timer patch.

Known titles:
- GNOE78 - Nicktoons Unite! / GNOX78 - Spongebob Squarepants & Friends: Unite! 
- GU6E78 - Nicktoons - Battle for Volcano Island
- GYAE78 - Barnyard / GYAP78 - Barnyard

The only other BlueTongue game on GC is The Polar Express which doesn't seem to have the issue. (I checked)

Setup:
Latest Nintendont at the time of posting (a1e4a33)
Wii w/ Homebrew Channel 1.1.0 on IOS58.
All my images are 1:1, I don't shrink GC games.

Things tried that didn't fix the problem:
- Turning off all video options and turning off unlock read speed
- Turning on Native Controller and using a real Gamecube Controller
- Turning off MemCard Emulation and using a real Memory Card
- Verifying the ISOs are correct. (I checked with redump.org)

**Comment by carnage702** [comment]
make sure you dont have unlock read speed to ON.

**Comment by cheatfreak47** [comment]
Doesn't seem to be related, game moves too fast with the setting on or off.

**Comment by carnage702** [comment]
probably needs another timer patch then.

**Comment by carnage702** [comment]
pal or usa btw?

**Comment by cheatfreak47** [comment]
USA, specifically- in PAL it's called "Spongebob Squarepants and Friends Unite!" or something of the sort.

**Comment by cheatfreak47** [comment]
It appears another game by the same developer, "Nicktoons Battle for Volcano Island" made by the same developer and same engine has the exact same issue present.

**Comment by cheatfreak47** [comment]
Because of this I'd recommend checking other games by the same developer (Blue Tongue Entertainment) for issues as well.

**Comment by cheatfreak47** [comment]
Per the suggestion of @GerbilSoft I measured the time on a cutscene for comparison on Nintendont and Dios Mios. I did it by recording the video with a camera and finding the same frame on both videos and measuring the exact time between the start and end of the video.

The difference comes out to be about 1.44 or 1.45 x faster on Nintendont then the Dios Mios recording, which is in line with what he said, that it should be about 1.5x faster if it just needs a timer patch.

**Comment by cheatfreak47** [comment]
Updated the title and OP with more relevant information.
Looks like the problem is also on one other Blue Tongue entertainment game- Barnyard.

**Comment by carnage702** [comment]
just making sure you are using nintendont version 4.436 right?

**Comment by cheatfreak47** [comment]
Yes, right from the OP- "Latest Nintendont at the time of posting (a1e4a33)"
I talked to GerbilSoft on IRC and he said it sounds exactly like the game needs a timer patch.

**Comment by FIX94** [comment]
confirmed and fixed, these games had the video playback code in a externally loaded .rel file instead of in the executable itself, polar express worked just fine because it does not have such a external .rel file.
