### ISSUE TITLE
No load prince of persia warrior within

### ISSUE THREAD

**Issue by Arnold1985** [FIX94/Nintendont#393]
When you try to start the game, only the black screen remains. I have tried it on the pc with dolphin and it works perfect.

**Comment by carnage702** [comment]
take a picture of your nintendont settings

**Comment by Arnold1985** [comment]
https://www.dropbox.com/sh/hqu1a5y7lgta6fz/AABL9pRvZaJaq5yBrAM79VsUa?dl=0

**Comment by carnage702** [comment]
try putting videoscale to auto or off or whatever teh default value is on usbloader gx, some games dont like being scalled at all, also to document the issues your better off using nintendont directly rather than using it through usbloader gx since its much easier to find whats wrong in there.

**Comment by Arnold1985** [comment]
I did what you told me, but it did not work. Then I leave you a capture of the Nintendont configuration.
https://www.dropbox.com/s/oi3zkapsl36u4k3/IMG_20170423_145215.jpg?dl=0

**Comment by carnage702** [comment]
you sure you putted video width to auto and screen position to zero? put that on nintendont itself then press b and start the game.

**Comment by pawhtiobo** [comment]
I just checked my game "Prince of Persia - Warrior Within (USA)" and its OK, without changing any settings, is your ISO ok?

**Comment by carnage702** [comment]
if it works with width and center values his iso is a bad one for sure, just becuase an iso works on dolphin doesnt mean it works on nintendont since nintendont is much more picky, get an iso with 1.35gb and an md5  matching redump and then rename it to game iso and use it fully, dont shrink the iso or use any tool to pass it to the hdd7sd or whatever you use.

**Comment by Arnold1985** [comment]
My ISO downloaded emuparadise, and copied it directly to my hard drive. From that page downloaded yours?
Thanks for helping me with my problem

**Comment by pawhtiobo** [comment]
Same place, as yours :)

PAL or NTSC?

**Comment by carnage702** [comment]
but you confirmed it booted with width values and center values pawhtiobo?

**Comment by pawhtiobo** [comment]
Just checked:

All settings: off
Video Width: Auto

**Comment by carnage702** [comment]
yeah but he doesnt have video width on auto nror center on zero, my guess is that is the issue and i didint see him say that he tryed with width on auto and center on zero.

**Comment by Arnold1985** [comment]
I have downloaded from another page the ISO, and I have reloaded but nothing. I am occupying the NTSC version, I read that another person had the same problem with an updated version of Nintendont. So I left the configuration now.
https://www.dropbox.com/s/4i7hxzlaisymod8/IMG_20170423_164319.jpg?dl=0

**Comment by carnage702** [comment]
do this download this
http://www.mediafire.com/file/5y3tfpoil433rij/MD5_SHA-1+Utility.exe

open your iso on your hdd and wait abit to show you the md5 then post it here, then delete your ninconfig.bin and your save file for the game wich if its ntsc should be named G2OE.

maybe the save file got bad when creating it, i just tryed the game and works fine here too i dont used width or center value tough this two things can break manny games.

**Comment by pawhtiobo** [comment]
If **Carnge702** advice also fail...don't waste any more time with this particular game, its one of the few GCN games that the graphics are very poor (even in 480P NTSC - a little better in 576i PAL)... you can also check some of the info regarding this particular issue in this report:

https://github.com/FIX94/Nintendont/issues/323

**Comment by GB-CG** [comment]
Works on my end with v4.436 with no graphic issues. I just use the Nintendont loader.
@Arnold1985 Unless you're using IPL, turn on 'Skip IPL'? Or your Wii is probably almost kaputt. Otherwise, I can't think of anything.
And please don't mention rom websites.

**Comment by carnage702** [comment]
3 people confirmed working, it has to be his iso that was corrupted when passing to the hdd for sure.

**Comment by Arnold1985** [comment]
Yes, I have tried again and nothing. But I'll look for another copy and then tell them. :-)

**Comment by carnage702** [comment]
did you do every step i told you? use the md5 checker, delete ninconfig.bin and save file?

**Comment by Arnold1985** [comment]
Yes, I did the steps but nothing. Same is strange that of the 42 games that I have installed, I only miss this one.
But there was a user from another forum who told me that he also had the same problem when he updated to the latest version of Nintendont.

**Comment by carnage702** [comment]
if you followed the stepss why didint you posted the md5 it gave you so we can see?

**Comment by Arnold1985** [comment]
I had no idea I had to post the results (I'm new to this). When I leave work I publish it. ;-)

**Comment by Arnold1985** [comment]
MD5 that appears to me
DCE5A1A75982905554D9D465A743FF3B

**Comment by carnage702** [comment]
iso is good for sure so lets try that last thing i can think of, delete your save file if it was created   with the id  of G2OE then copy any other save file from any other game and rename it to G2OE, maybe your hdd or sd is having issues making the save file correctly.

**Comment by Arnold1985** [comment]
Ok, I'll replace the existing one with another (I'll copy one of the others Prince of Persia) I think it will serve to increase compatibility. I'll tell you later

**Comment by cheatfreak47** [comment]
Try using JoostinOnline's Settings Editor GUI to set the Wii to 480i mode.

**Comment by Arnold1985** [comment]
Never change one save file for another. I just lost all my files for doing that. The console crashed and then when you see the hard drive on the computer the save folder has been corrupted. I could not save my saved games :-(

**Comment by carnage702** [comment]
what? im thinking there was a problem with your storage device to begin with, lol renaming a save file made you loose all your save files? doesnt make any sence.

**Comment by Arnold1985** [comment]
that happens. Got stuck trying to read the replaced file and left the corrupted save folder. But do not believe me, do the test. I close this topic.
Note: I have thousands of other games on the hard drive that work perfectly. I will not change it because only one fails.

**Comment by carnage702** [comment]
i did lol i did this alot on nintendont since manny older versions had save issues so i would contantly rename save files from other games and put it there and never had an issue.

im not saying for you to change your hdd im saying grab the iso put it on the sd card or another hdd to test if it works is because that game does something your hdd doesnt like.
