### ISSUE TITLE
via button combo changed？

### ISSUE THREAD

**Issue by nictse2013** [FIX94/Nintendont#396]
Reset/Power off via button combo (R + Z + Start) (R + Z + B + D-Pad Down)

(R + Z + Start)  doesnt work
but (R + Z + Start+ B）can go back to homebrew on vwii

**Comment by carnage702** [comment]
exist combo changes depends on the controller, for isntance wiiu gc adapter exit is diferent from actual gc controller through wii ports.

also there is no power off combo and no restart game one only exit combo.

the reset game combo was the devs that made it themselves and its on some games while it isnt on others.
