### ISSUE TITLE
Chibi Robo save doesn't work with Nintendon't without real memory card.

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [FIX94/Nintendont#397]
Chibi Robo game save doesn't work with Nintendon't without real memory card.

**Comment by cheatfreak47** [comment]
I can't reproduce this, it saves fine with Memory Card Emulation on for my end.

**Comment by carnage702** [comment]
saves for me too, img uessing you have either a very old nintendont or you are using a  wierd setup.

**Comment by OrangeSkeleton** [comment]
I just faced an issue with Chibi Robo Japanese rom, when the game creates save file at the start, it corrupts raw file, and then the game is unable to boot. No matter which mcemu size I choose in settings, the GGTJ.raw file size becomes 16.09 MB.

**Comment by carnage702** [comment]
> I just faced an issue with Chibi Robo Japanese rom, when the game creates save file at the start, it corrupts raw file, and then the game is unable to boot. No matter which mcemu size I choose in settings, the GGTJ.raw file size becomes 16.09 MB.

take a picture of your nintendont settings and post it here.

**Comment by OrangeSkeleton** [comment]
I tried to reformat my SD card (didn't help), and tried US rom. US rom works fine.
I guess save file's size gets corrupted, and some random data stored on SD card appears in that save file.
[saves.zip](https://github.com/FIX94/Nintendont/files/9283960/saves.zip)
![IMG_20220809_023156__01](https://user-images.githubusercontent.com/13693729/183480999-1ec5ebbe-a5d0-4e64-9cfe-bb0d29711657.jpg)

**Comment by carnage702** [comment]
> I tried to reformat my SD card (didn't help), and tried US rom. US rom works fine. I guess save file's size gets corrupted, and some random data stored on SD card appears in that save file. [saves.zip](https://github.com/FIX94/Nintendont/files/9283960/saves.zip) ![IMG_20220809_023156__01](https://user-images.githubusercontent.com/13693729/183480999-1ec5ebbe-a5d0-4e64-9cfe-bb0d29711657.jpg)

tryed saving with force widescreen turned off? also you have any other jap games? or its the only one?

**Comment by OrangeSkeleton** [comment]
Yes, I have tried without forcing widescreen. Nothing has changed.
Other Japanese games work fine. I had multi memcard turned on before, and noticed that other Japanese games stopped booting. After testing I figured out that Chibi Robo corrupts memcard file.

**Comment by carnage702** [comment]
> Yes, I have tried without forcing widescreen. Nothing has changed. Other Japanese games work fine. I had multi memcard turned on before, and noticed that other Japanese games stopped booting. After testing I figured out that Chibi Robo corrupts memcard file.

Did you tried deleting the save file and copying a raw file from other of your Jap games and rename to chibi robo game Id?

**Comment by OrangeSkeleton** [comment]
No, I didn't.
When I run the game for the first time and don't create save file (don't start a new game), good 2 MB raw file is created. When the game tries to write a new save to memcard (at the start of a new game), raw file becomes corrupted.

**Comment by carnage702** [comment]
> No, I didn't. When I run the game for the first time and don't create save file (don't start a new game), good 2 MB raw file is created. When the game tries to write a new save to memcard (at the start of a new game), raw file becomes corrupted.

then try it, it could be the raw file is being badly created, or with wrong parameters, try grabbing another jap game raw file and just rename it to chibi robo gameid and see if it saves correctly on that.

**Comment by OrangeSkeleton** [comment]
Yes, I have tried to rename a raw file from another game. Chibi Robo boots, but when I start a new game and create a new profile, then it corrupts that raw file.

**Comment by carnage702** [comment]
> Yes, I have tried to rename a raw file from another game. Chibi Robo boots, but when I start a new game and create a new profile, then it corrupts that raw file.

So i dont know japanese or ever played chibi robo so  any chance you can make me a step by step guide on the paths until saving? so i could try for myself.

**Comment by OrangeSkeleton** [comment]
Yes, actually, there is only one necessary step, just launch the game and choose a save slot. The game will create an empty save file. After the game loads to a cutscene you can exit it.
In case of US game when you launch it again, you will be able to see a Load game option on a home screen. But in case of JPN game, the raw file will be corrupted and the game will not be able to boot anymore. 
![IMG_20220812_164721__01](https://user-images.githubusercontent.com/13693729/184310958-3839943e-1598-4a67-9b46-a19430e0f20f.jpg)
![IMG_20220812_164927__01](https://user-images.githubusercontent.com/13693729/184310965-8a04f54a-a8c7-4fe6-8717-83bd3e80ca64.jpg)

**Comment by carnage702** [comment]
> Yes, actually, there is only one necessary step, just launch the game and choose a save slot. The game will create an empty save file. After the game loads to a cutscene you can exit it. In case of US game when you launch it again, you will be able to see a Load game option on a home screen. But in case of JPN game, the raw file will be corrupted and the game will not be able to boot anymore. ![IMG_20220812_164721__01](https://user-images.githubusercontent.com/13693729/184310958-3839943e-1598-4a67-9b46-a19430e0f20f.jpg) ![IMG_20220812_164927__01](https://user-images.githubusercontent.com/13693729/184310965-8a04f54a-a8c7-4fe6-8717-83bd3e80ca64.jpg)

you are right the jap version is incompatible with memory card emulation for whatever reason so if your not on a wii with gc ports and use a real memory card you cant save on nintendont but if you really want to play the game in japanese for whatever reason you are in luck since nintendo for japan only made a new controller version of the gc game on the wii, so you can play the wii port of chibi robo in japanese on any wii or wiiu and it has like native widescreen and such  you can see it here any usb loader or even wiivc inject will probably let you play chibi robo in english https://www.amazon.com/Chibi-Robo-Wii-Asobu-Japan-Nintendo/dp/B001HBIPIK

**Comment by OrangeSkeleton** [comment]
Thank you for checking that, much appreciated.
