### ISSUE TITLE
Not Enough Storage In Memory Card Slot A

### ISSUE THREAD

**Issue by JellyMana** [FIX94/Nintendont#399]
Even if I delete all of my game saves it still won't let me create any new saves.

**Comment by carnage702** [comment]
real memory card or memory card emulation?

**Comment by JellyMana** [comment]
Memory card emulation on the stable size

> Not enough storage in Memory Card A
> Continue without saving (On all games)

**Comment by JellyMana** [comment]
Emulated storage  

    On Wednesday, April 26, 2017 5:14 PM, pedro702 <notifications@github.com> wrote:
 

 real memory card or memory card emulation?—

**Comment by cheatfreak47** [comment]
Have you tried deleting the virtual memory card on your storage device and creating a new one?

**Comment by carnage702** [comment]
is multi  option set to off?
