### ISSUE TITLE
Triforce titles not saving

### ISSUE THREAD

**Issue by Mimimax** [FIX94/Nintendont#403]
Triforce titles are unable to save data. I tested saving on Mario Kart Arcade GP 1 but the game softlocks while attempting to save. Also tested with F-Zero but it simply didn't save nor softlocked. Tested using official 251 block gc memory card.

**Comment by carnage702** [comment]
game saves jsut fine you need to create a card on mari kart gp and then you can only save after you finish a race when it says you want to continue you pick not it will say saving to card and after like 15 seconds on that screen your good to exit nintendont or shutdown the console since it wont disapear from that screen.

**Comment by Mimimax** [comment]
Ok then I will try again and see for myself.

**Comment by Mimimax** [comment]
Well maybe the game does save but when it asks if I have a card upon starting, pressing on yes does nothing.

**Comment by cheatfreak47** [comment]
First of all, @Mimimax Triforce games don't use physical Memory Cards- as they are not gamecube games, they are arcade hardware similar enough to a GameCube that with custom code, can be run under a GC like environment. The "cards" it's ask for are not "memory cards" they are cardboard license cards that arcade maintainers would sell you to save progress on- I believe the cards were magnetic or something. (can't be bothered to check)

Second, @carnage702 is right- I think it should save no matter what- and that sometimes it hangs after saving.

**Comment by Mimimax** [comment]
Oh I didn't think about it that way. So I just gotta set the save storage as sd card or usb, right?

**Comment by carnage702** [comment]
you already have it sd or usb since the save files go where the iso is loaded and you need to have the iso somewhere to get it to play lol.

**Comment by Mimimax** [comment]
It worked now. Thanks a lot

**Comment by Mimimax** [comment]
While I'm at it, may I ask if the little lag that happens in the game sometimes due to Nintendont or is it my game partition or the loader's partition?

**Comment by carnage702** [comment]
lag on gc games or triforce.

**Comment by Mimimax** [comment]
Triforce

**Comment by FIX94** [comment]
f-zero should run fairly good, the only part that should lag is during the save emulation kicking in, the mario kart gp games normally are on dedicated NAND chips which have nearly instantly load response so if you load data off a hdd with high latency to start loading data that would be why those lag from time to time, you may be better off to use a good sd card for them instead.

**Comment by Mimimax** [comment]
Nice! I tried using my SD card for MKGP and it didn't lag at all. I guess this issue can be closed now. Thanks guys.
