### ISSUE TITLE
vWii freezing

### ISSUE THREAD

**Issue by nictse2013** [FIX94/Nintendont#406]
inter the nintendont from vWii,dont enter any game,just press home to quit,100% freezing....

**Comment by carnage702** [comment]
why do you want to enter nintendont, not pick a agme and then exit? ... makes no sence.

**Comment by nictse2013** [comment]
when u finish update,u must reboot nt,make sense!

**Comment by DongVGH** [comment]
This isn't actually important at all and is most likely a flaw of vWii, if you need to reboot then just turn the console off and then on again.
