### ISSUE TITLE
Support for GC Homebrew/ SD Gecko emulation

### ISSUE THREAD

**Issue by DongVGH** [FIX94/Nintendont#407]
So i just stumbled upon some cool homebrew apps for Gamecube, namely Snes9x, Quake, CubeDoom, NeoPop GX (Which to my knowledge isn't ported to Wii) and Genesis Plus GX.
And thought about how cool would it be to boot them up on Nintendont, unfortunately, Swiss and SD-Load don't work, as they freeze on a black screen, i thought about making a CISO with start.dol being replaced by the .dol of the app i'm trying to run, but it doesn't work, and even then if i got to it to work i would need a SD Gecko to run Apps that are not self-sufficient. (Eg. require anything else than just the .dol file, so only Tetris would work)

Althrough a release of the library used to make USB HID Gamepads work would be enough.

**Comment by FIX94** [comment]
nintendont only patches official nintendo sdk functions so your only chance at something like homebrew is to get their source and recompile them for direct wii use or use cMIOS and the actual gamecube mode since homebrew uses its own code which you cannot actually patch properly unless you write several thousand lines of code which I most definitely will never do.

**Comment by DraconicNEO** [comment]
> nintendont only patches official nintendo sdk functions so your only chance at something like homebrew is to get their source and recompile them for direct wii use or use cMIOS and the actual gamecube mode since homebrew uses its own code which you cannot actually patch properly unless you write several thousand lines of code which I most definitely will never do.

I never thought about this much before but I'm thinking. Would it not be possible to simply patch the devkitppc functions themselves to achieve a similar effect for most Homebrew? Obviously it won't work for all Homebrew but you could get some Homebrew games to run, the ones that use Devkitpro. And I think it might be worth it because the GameCube scene these days is Booming, while the Wii scene by contrast is withered and stagnant despite the fact the hardware is near identical.

**Comment by carnage702** [comment]
> > nintendont only patches official nintendo sdk functions so your only chance at something like homebrew is to get their source and recompile them for direct wii use or use cMIOS and the actual gamecube mode since homebrew uses its own code which you cannot actually patch properly unless you write several thousand lines of code which I most definitely will never do.
> 
> I never thought about this much before but I'm thinking. Would it not be possible to simply patch the devkitppc functions themselves to achieve a similar effect for most Homebrew? Obviously it won't work for all Homebrew but you could get some Homebrew games to run, the ones that use Devkitpro. And I think it might be worth it because the GameCube scene these days is Booming, while the Wii scene by contrast is withered and stagnant despite the fact the hardware is near identical.

rewriting nintendont to serve an entirely different devkit would be an huge amount of work, also almost every homebrew most ppl care about like emulators and such run better on wii/wiiu than they do on GC so unless someone wants to do that for whatever homebrew you think its better in gc mode over wii mode they would have to do it themselves.

**Comment by DraconicNEO** [comment]
> > > nintendont only patches official nintendo sdk functions so your only chance at something like homebrew is to get their source and recompile them for direct wii use or use cMIOS and the actual gamecube mode since homebrew uses its own code which you cannot actually patch properly unless you write several thousand lines of code which I most definitely will never do.
> > 
> > 
> > I never thought about this much before but I'm thinking. Would it not be possible to simply patch the devkitppc functions themselves to achieve a similar effect for most Homebrew? Obviously it won't work for all Homebrew but you could get some Homebrew games to run, the ones that use Devkitpro. And I think it might be worth it because the GameCube scene these days is Booming, while the Wii scene by contrast is withered and stagnant despite the fact the hardware is near identical.
> 
> rewriting nintendont to serve an entirely different devkit would be an huge amount of work, also almost every homebrew most ppl care about like emulators and such run better on wii/wiiu than they do on GC so unless someone wants to do that for whatever homebrew you think its better in gc mode over wii mode they would have to do it themselves.

That is true. I was mainly thinking of Homebrew Games specifically since there are a few out there which aren't on Wii. Emulators which have GameCube versions all have Wii versions which also support GC controllers. Definitely niche use case.
