### ISSUE TITLE
Black screen when launched from USB Loader GX with WiiU HDD attached

### ISSUE THREAD

**Issue by RobeeeJay** [FIX94/Nintendont#408]
Thanks for a great loader, I've been using this for a while on my original Wii!

I've just got a Wii U and I've run into a bit of a problem. I have two drives, in Port 0 I have a USB HDD with a FAT32 partition on it, containing Wii and GC games. This works fine in USB Loader GX, even with the partition hidden from the WiiU.

But if I power up my WiiU with the WiiU formatted drive attached in Port 1, Nintendont no longer works. :( If I launch it standalone it can't find any USB FAT32 drives, if I launch it from USB Loader GX it just freezes the WiiU with a black screen.

**Comment by carnage702** [comment]
nintendont does not support multiple drives connected to the console, only one drive at a time.unplug your wiiu drive when using nintendont.

**Comment by RobeeeJay** [comment]
Um surely that is an issue then? And this shouldn't be closed?

**Comment by carnage702** [comment]
something not being supported isnt an issue, nintendont will never support multiple drives unless someone wanta to redo the entire usb code so you can go ahead and do it and submit a pull request.

**Comment by RobeeeJay** [comment]
I'm not expecting it to support multiple drives, just not freeze when multiple drives are attached. :(

I think this is a stability issue, not a feature issue.

If you can point me at the source that iterates the USB devices I'll take a look. Without reading the code I'm not sure the entire thing needs to be redone to solve this, but I suspect not.
