### ISSUE TITLE
Virtual memory card data corruption after disc change

### ISSUE THREAD

**Issue by XploitOcelot** [FIX94/Nintendont#409]
[GGSP.zip](https://github.com/FIX94/Nintendont/files/980881/GGSP.zip)

Hi!
I discovered the issue when playing Metal Gear Solid: The Twin Snakes (US).
After the disc change, I wanted to save the game, but when going to do that, the game recognised the data as corrupted. I was using a global vmc and I lost the savegames of other games as well.

I started a new game with the EU version of the game.
After doing the disc change, the data was again corrupted, but it was not so dramatic since now I was using an individual vmc for each game.

One can still go on playing, but any extra data on the vmc (photos, records, ... ) will be erased everytime the game changes the disc.

My setup is a black Wii running Nintendont v4.440 though USB Loader GX (last revision).
It happens with both versions of the game, I don't know yet if happens with other multidisc games.
The games are loaded from a Sandisk 64GB pendrive with two partitions (FAT32 for GC + NTFS for Wii) without issues.

EDIT: I'm sending the file of the vmc for the game (EU version). After loading the savegame, the disc will change automatically. Then, if you want to save again (calling Mei Ling) it will recognise already the memory card data as corrupted.

**Comment by FIX94** [comment]
it should be fine again, GerbilSoft broke it in his ciso additions.
