### ISSUE TITLE
Add support to edit Wiimote + Nunchuk controllers

### ISSUE THREAD

**Issue by sero583** [FIX94/Nintendont#410]
Please add that, it's a real struggle to with that weird C-stick tilting etc. I want to make my own mappings which would be better like pressing C and just moving the stick from NC for example.

**Comment by carnage702** [comment]
you would be so much better off using a real controller like gc controller or even CC or wiiu pro controller, wiimote+nunchuck is the worst setup to play gc games.

**Comment by sero583** [comment]
@carnage702 I don't really care about that + if you map it right youre also good & I dont got a GCN port on my wii because at times it cost less than the one with the wii port but I'd would like to play my gamecube old games with more controllers because I got more wiimotes+nunchuk than GCN controllers.

**Comment by carnage702** [comment]
well then your better off learning to code and make it yourself, fix94 has no intention of ever adding any  controller mapping stuff be it for normal bt controllers or wiimote+nunchuck and since github is opensource anyone can modify nintendont and add their stuff, if you find anyone willing to do such job.

**Comment by sero583** [comment]
@carnage702 I know how to code but what I dont know on this project where are the mappings hardcoded and how can I build my own boot.dol file?

**Comment by sero583** [comment]
Also where can I get the values at each button press? I tried HIDTest but nothing works and it says could not open config & older doesn't let me even reconnect my wiimote to it.

**Comment by sero583** [comment]
Oh totally forgot about that also I'm not really want install something only to compile, isnt there some online solution or is it possible to build on ubuntu/linux?

**Comment by sero583** [comment]
Soo how could I check which controlls/controll combination is which value on a wii?

**Comment by sero583** [comment]
Also just doing a .ini file would be so much easier for everyone I'm gonna code on C without any pre knowedgle, well thats shitty, I only know Java & PHP

**Comment by carnage702** [comment]
bt controllers  dont use ini files its how its codded and it will always be, you can check the values i guess comparing with the already made setups, to actualy check the values on each button you would need to go and find some wii homebrew apps or sdk stuff i have no idea, nunchuck and wiimote werent added by the official nintendont dev tem, they were made becuase the comunity basicaly paid a guy and he deloped that stuff and added it to the main branch after it was accepted by the nintendont dev team.

also afaik without devkit pro installed you cant compile it.

**Comment by sero583** [comment]
@carnage702 Do you know how to create a basic Wii app (ofcourse for homebrew) like Nintendont from scratch? I've been searching but hadn't any success yet, I want to create a basic app which displays which value current button (combination) got to edit the BT controlls.

**Comment by carnage702** [comment]
no idea, im mainly a tester for fix94  if i can confirm the issue i tell him and hopefully he is in working mood and fixes it :P

**Comment by sero583** [comment]
Would @FIX94 be able to help me at this point? Wouls s-/he even respond to this?

**Comment by carnage702** [comment]
dont think so since he and even myself think nuncuck ad wiimote should never be used on nintendont xD, it was only added becuase fix94 didint had to do  any work on it xD.

**Comment by sero583** [comment]
@carnage702 But with the right implementation wiimote would be awesome on GCN, only wiimote there I also would think out myself something; very basic controlls and if I'm able to make it, I would make it like that 2 repos one main and the other with other bt controlls, so you could easily update the other branch also

**Comment by carnage702** [comment]
like i said i dont code and fix has no intention of doing anything with this since he hates wiimote+nunchuck so unless you code it or find someone to do it for you it wont happen.

**Comment by sero583** [comment]
@carnage702 I'm gonna try to work on it, but I need a documentation or something like that about Homebrew apps (create a simple app to gather the values from the Wiimote), could @FIX94 help me in this topic?

**Comment by sero583** [comment]
@carnage702 By the way do you know a way to connect other bluetooth controllers with the wii except USB?

**Comment by sero583** [comment]
@carnage702 Like a bluetooth gamepad since the wii also supports bluetooth shouldnt be impossible, or?

**Comment by carnage702** [comment]
you would need another bt stack wich is like thousands og lines of complicated stuff.
