### ISSUE TITLE
 Dead pixels 

### ISSUE THREAD

**Issue by nydalap** [FIX94/Nintendont#411]
Sorry for my english
 It looks like the pixel problem is game specific to Nintendont since Dios Mios runs the games without the pixel problem. The dead pixel do not appear in menus or cutscenes only during gameplay.  Not all games have this problem. Dead pixels appear in:
The Legend of Zelda: The Wind Waker
Resident Evil 4 
Resident Evil
Mega Man X Collection 
Metal Gear Solid The Twin Snakes does not have the dead pixel problem and runs perfect.  These are the few games i have played where the problem occurs every time.

![diosmios](https://cloud.githubusercontent.com/assets/28576301/25870498/8c157af8-3504-11e7-861f-f590f75c5ee0.JPG)
![diosmios2](https://cloud.githubusercontent.com/assets/28576301/25870497/8c144c8c-3504-11e7-9cb9-ea0d5aaed780.JPG)
![nintendont](https://cloud.githubusercontent.com/assets/28576301/25870499/8c15f78a-3504-11e7-88ad-db40fd34b585.JPG)
![nintendont2](https://cloud.githubusercontent.com/assets/28576301/25870500/8c192a72-3504-11e7-8590-b76f9e84f061.JPG)

**Comment by carnage702** [comment]
fix94 took a very good  look at WW when this was reported same for me and we dont have any dead pixels on our screens, maybe its a combination of your setup or something.

http://gbatemp.net/threads/nintendont.349258/page-1810#post-7178988

he played alot same way for alot of people, WW was the first compatible game on nintendont so thousands of people played it by now, i cant see any dead pixels neither can fix94 and what cant be seen cant be fixed check the link and see if you see any dead pixels on his post he posted alot of pictures those 2 were just the ones he choosed to put there.

**Comment by cheatfreak47** [comment]
it's likely either a weird problem with your TV or something wrong with your Wii hardware.
