### ISSUE TITLE
Triforce games named wrong...

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#412]
I converted the MAME chd files with the FIX94 tool and, after that, I applied the FixHeader tool (from FIX94 either). The games works fine, but I noticed a problem with the names. I noticed that these games names are not editable like the GameCube ones, so I let you know.

- Virtua Striker 2002 [Export] (Triforce) (Game ID GVS32E after use the FixHeader tool) appears as Virtua Striker 3 Ver. 2002... it should be named just "Virtua Striker 2002". The name that appears is the name of the GameCube Virtua Striker. The name appears in red, don't know why. It works fine anyway.

- Virtua Striker 4 [Export] (Triforce) (Game ID GVS45E after use the FixHeader tool) appears as Virtua Striker 3 Ver. 2002. It should be named "Virtua Striker 4". This one is the standard Virtua Striker 4, NOT the 2006 version.

The game "Gekitou Pro Yakyuu - Mizushima Shinji All Stars vs. Pro Yakyuu" appears in red too. It works fine.

I use the last version of Nintendont updated to day. The configuration is all by default, nothing enabled or forced, just the Memory Card emulation activated with a 251 blocks memory card.

**Comment by carnage702** [comment]
obviously all triforce games will appear in red since they got no md5 matching on redump :P , abot the names well its basicaly hardcoded on nintendont and no one bothered to change them i guess.

**Comment by SieKensou** [comment]
Thanks for the reply. It would be great if they could be fixed, specially the Virtua Striker 4 that appears as Virtua Sriker 3... I understand that is something too small to bother about it, but since this project is the best it would be great if it could have these small things fixed.
About the names in red, I asked it because only these 2 games appears in red to me (Virtua Striker 2002 and Gekitou Pro Yakyuu)... The other ones, F-Zer AX, Mario Kart GP and Virtua Striker 4 appears in black like the other games, that's why I was asking about that.

**Comment by SieKensou** [comment]
I post a picture of this problem too. As you can see, 2 different games appear as Virtua Striker ver. 2002.
GVS45E should be "Virtua Striker 4".
GVS32E  should be "Virtua Striker 2002".
As you can see, these 2 are the only games that appear in red.
![triforce](https://cloud.githubusercontent.com/assets/28622717/25987487/849c904e-36f4-11e7-997a-be52efd2964d.jpg)

**Comment by FIX94** [comment]
seems like several triforce titles werent in the hardcoded list giving this exact problem, it should be fine now. Also, it displaying "Virtua Striker 3 Ver. 2002" is in fact correct.

**Comment by SieKensou** [comment]
Thanks for fixing the names! Nintendont is going to be perfect :)

About "Virtua Striker 3 Ver. 2002", if you take a look to the game itself, the title screen says "Virtua Striker 2002" and here is the info in Wikipedia:
https://es.wikipedia.org/wiki/Triforce (sorry it's in Spanish, I don't find the info in English)
As you can see, in the released games it says: "Virtua Striker 2002 (2002) de Sega"
And to clarify, it have a note at the end that says "El juego de arcade Virtua Striker 2002 y el juego de Nintendo GameCube Virtua Striker 3 Ver.2002 no son el mismo juego. La versión de GameCube está basado en el de Virtua Striker 3."
That means: "The arcade game Virtua Striker 2002 and the Nintendo GameCube Virtua Striker 3 Ver.2002 are not the same game. GameCube's version is based in Virtua Striker 3.

So with this, "Virtua Striker 3 Ver.2002" is the GameCube version and "Virtua Striker 2002" is the arcade Triforce game.

You know that I want the best for Nintendont ;)

**Comment by SieKensou** [comment]
Hi again. I don't know if FIX94 read my last message... If yes, my explanation and proofs are not enough to convince you that the right name of the game is just Virtua Striker 2002? :P

More proofs:
https://www.youtube.com/watch?v=Pzq4oNKRfZI
Minute 2:04... the title screen says: "Virtua Striker 2002"

Triforce disc:
![virtua_striker_2002_triforce_gd-rom_jp_disc](https://user-images.githubusercontent.com/28622717/27948278-960c1c06-62f9-11e7-9c19-94e7e4778a96.jpg)
It says: "Virtua Striker 2002"

And wait... let's see your youtube video of the "Triforce Virtua Striker 3 Ver. 2002 Intro"... go to minute 1:08... What can you read at the title screen?
https://youtu.be/6L-5uF7UyEw?t=1m8s
Again... just "Virtua Striker 2002"
