### ISSUE TITLE
Sonic Gems Collection doesn't load Sonic The Fighters in the PAL version

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#413]
The other games of this game works well, but when I try to load Sonic The Fighters, the game doesn't load and the controller doesn't work. Sometimes you can see the SEGA logo, but it freezes there inmediately. It doesn't happen in the JAP version of the game. I tried my original GameCube disc PAL with Nintendont and it does the same as the backup.
I use the last version of Nintendont updated to day. The configuration is all by default, nothing enabled or forced, just the Memory Card emulation activated with a 251 blocks memory card.

**Comment by carnage702** [comment]
you sure you dont have forcd video mode/width/widescreen whatever? are you using version 441? can you take a picture of your nintendont settings? sometimes people say they dont have anything its all default and it isnt.

**Comment by SieKensou** [comment]
Yes, I am sure that I didn't have any option activated (more than the memory card emulation),, but I can post a picture later if needed.
Yes, I'm using the v4.441, but this issue/bug was there always for me (at least for the time since I started to use Nintendont).

**Comment by carnage702** [comment]
if you supply me a picture of your nintendont settings it would be great.

**Comment by SieKensou** [comment]
Okay, no problem. Here is the picture:
![nintendont4441](https://cloud.githubusercontent.com/assets/28622717/25987296/afb56d56-36f3-11e7-82cb-f1500f1ae54b.jpg)

**Comment by carnage702** [comment]
download the new version 442 wich fixes sonic fighters on the pal version that has never worked lol for some reason fix94 fixed the usa and jap versions and forgot about the pal one :P.
