### ISSUE TITLE
Naruto - Gekitou Ninja Taisen 3 (JAP) doesn't work

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#415]
This game freezes at the title screen without possibility to play and playing a weird noise.

I use the last version of Nintendont updated to day (v4.441). The configuration is all by default, nothing enabled or forced, just the Memory Card emulation activated with a 251 blocks memory card.

**Comment by carnage702** [comment]
i remenber there is only a bad dump available online i bet you got that bad dump wich the md5 doesnt match redump correct? i know i had to go worlds apart to get a good dump for this game, always check your isos md5s.

**Comment by GB-CG** [comment]
Apparently there are two versions of this game: v1.00 and v1.01. So maybe only one of them works or it could be just your setup.

**Comment by SieKensou** [comment]
Thanks to both of you for the replies.
Yes, the md5 doesn't match, so it seems I have a bad dump. I will try to find the right one because I don't have the original disc of this game anymore. If not, if someone can provide me the correct iso (preferible the v1.01 if it works fine).

**Comment by carnage702** [comment]
we cant link you warez in here so try and find a md5 matching iso,i i know i had to look into jap websites and such to find it back in the ay for testing, its very very hard to find a md5 checked iso off this game.

**Comment by SieKensou** [comment]
Okay, I confirm that the problem was a bad iso and I confirm that the v1.01 works fine too. Thanks!

**Comment by Hakamdeebad** [comment]
So it is a bad dump that causes this issue? 'Cause I am having the same exact problem and haven't been able to find another dump of the game at all. @SieKensou

**Comment by carnage702** [comment]
yeah its a bad dump on one of those known iso sites wich is the only easily found dump, if you find a dump that matches the md5 on redump it will work no problem, remenber audiostreaming games cannot be shrunken with most tools or their audio files get disaligned and crash nintendont.

**Comment by GB-CG** [comment]
Mentioning rom websites or asking for links are not advised on Github. So please don't.
