### ISSUE TITLE
Prince of Persia: Warrior Within (NTSC-U) doesn't work

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#416]
The game doesn't load, just a black screen.

I use the last version of Nintendont updated to day (v4.441). The configuration is all by default, nothing enabled or forced, just the Memory Card emulation activated with a 251 blocks memory card.

**Comment by GB-CG** [comment]
I can't reproduce it on my end. Try deleting the Homebrew save (1 Block) on the Wii save management settings if deleting the config file doesn't work. And check its MD5.

(For those who have a Mac, open Terminal and type `md5 ` then drag the file and hit Enter.)

**Comment by SieKensou** [comment]
I deleted the Nintendont config, the memory card for this game and the Wii save of the Homebrew Channel and I tested the md5 and CRC and they match:
MD5: dce5a1a75982905554d9d465a743ff3b
CRC-32: 546484d5
So the iso is correct, but I still have the same problem, when try to load this game, it creates the memory card and goes to the black screen and is there forever. I tried without using memory card and the result is the same... As note, the console seems to continue working because if I just press the power button the console shut down, there is no need to hold the button a few seconds.
This is too weird, I have tested toons of games and except the problems I'm commented those days, the games works great. If you said the game works for you, I don't know what can be... Any idea of what to try or check?

**Comment by GB-CG** [comment]
'Skip IPL' is turned on, right? Having it off without an IPL file may cause weird side-effects.

**Comment by SieKensou** [comment]
It was OFF, but I tried turning it on and the result is the same...
I tried using the IPL too, but after the GameCube logo it keeps with the screen in black as always...

**Comment by carnage702** [comment]
so i got the iso and didi a fresh instal on my sd card of prince of persia ww and the game starts as normal ask me for proressive and saves and everything, so my guess is your device has issues, i remenber someone reportin this game too and they couldnt get it to start im guessing this game is very very picky with speeds and if your sd or usb dont give enough response it doesnt start, what device are you using on your isos? i just used a class 10 32gb sd card and works great, same way for my moded hdd.

**Comment by SieKensou** [comment]
I'm using a 80GB HDD. I tested in a PenDrive USB too and the game doesn't work either. Is your Wii PAL?
I tried the PAL version of this game and it works fine, so it seems it could be something about the NTSC-U version of the game and the PAL Wii.
The first that appears when the game is loaded is the memory card check, so it could be related with that. Any help to make this game work in its NTSC version would be much appreciated.

P.D.: Thanks to all for the Sonic fix, it works fine now :)

**Comment by carnage702** [comment]
yeah my wii and wiiu are pal and the game works perfectly. heck i only use ntsc games due to 60 hz xD.
Also just for the fluke try it on the SD card if you got one that has any decent speed.

**Comment by SieKensou** [comment]
Yes, I prefer this one too for the 60hz. I tried on a SD card. I don't know if it is too fast (but it should), it is a 32GB Toshiba SDHC. I only tried using it on the Wii SD card slot, I tried with an USB SD card adapter but for some reason it says it can't read the SD.
This is too weird, why is not working? :/

**Comment by carnage702** [comment]
badly formated? maybe needs a good format? i use a scandisc 32gb  also dont use it as usb use it directly on the wii sd card slot.

**Comment by SieKensou** [comment]
Maybe it is the USB adapter, but directly on the Wii SD card slot I load the game, but with the same result as always, just the black screen...

**Comment by carnage702** [comment]
i wonder what do you have your wii connected with? just for the sake of it did you tryed forcing pal60 on the game?

**Comment by SieKensou** [comment]
No, I didn't have tried forcing video.
But I tested right now forcing PAL60 and, again, just the black screen.
My Wii is connected with the Nintendo official component cable for Wii.

**Comment by carnage702** [comment]
not sure what to tell you then, i cant reproduce this and all my consoles are pal too so no idea, maybe you got some wierd cios or something no idea really.

**Comment by carnage702** [comment]
do you have acess to another wii or wiiu?

**Comment by carnage702** [comment]
also just for the heck of it try  putting the av cables back on the wii instead of component who knows, i dont have component on my wii just the default av.

**Comment by SieKensou** [comment]
What the...????? Can you believe it? I changed to the AV cable as you suggested, just to try, and it works! :/ (I didn't remember how bad it looks with this cable lol)
Why doesn't work with the component cable? It works perfectly with the PAL version of the same game (and the other hundred of GameCube games I have tested)... It would be some incompatibility if the game load OK and I can see it, but when I use the component cable, the game doesn't load...
Do you think that could be fixed? I would be very thankful.

**Comment by GB-CG** [comment]
I've never heard of this AV problem before. I just use a £2 third party component cable. You could try use a Wii-to-HDMI adapter.

**Comment by carnage702** [comment]
my guess was correct lol, still is preeety wierd since i use my wiiu wich nintendont just says its a wii with component cable and it works fine, like i said i dont have a component cable on my wii so i cant test this, and every other game works fine so its very very wierd.

**Comment by SieKensou** [comment]
Yeah, its too weird. As I said, my component cable is the official from Nintendo for Wii, so it shouldn't be a problem (specially because all the other games I have tested works perfectly). This is the only one that seems to have this problem. And what makes it weirder is that the PAL version works fine too, why the NTSC-U version doesn't? It's a mistery, but I hope it can be fixed, it would be a pain to have to change the cable any time I want to play just this game :/
If it was cable incompatibility, the game should work anyway, but I wouldn't see the game (but it should load and work anyway), but what makes it weird and weird is that with the component cable the game doesn't start, just the blank screen... Maybe FIX94 knows where this problem could come from... I really hope he can know something about it...

**Comment by carnage702** [comment]
the problem is fix94 and I dont have a component cable to test sadly, so it will be very hard to debug the problem per say.

**Comment by carnage702** [comment]
maybe playing with forced stuff will work

force ntsc and forced progressive turned on, then try force pal60 an force progressive and so on.

**Comment by SieKensou** [comment]
I tested with:
Force NTSC: Black screen.
Force PAL60: Black screen.
Force Progressive: Black screen.
Force Progressive + Force NTSC: Black screen.
Force Progressive + Force PAL60: Black screen.
Force Widescreen: Black screen.

I can try to test everything to find the problem if you tell me (always that doesn't require to install nothing on my Wii). I really would like to fix this problem and make this game load normally as it should.

**Comment by carnage702** [comment]
just wondering did you acutaly played any ntsc game with 480p on your wii? can you actualy play them?

Also fix94 has the idea that your tv is the fault and cant handle the resolution the game uses internaly, do you have any other tv? could you try to put your wii connected to a diferent tv and try?

**Comment by SieKensou** [comment]
A NTSC GameCube game with 480p? Like wich one? Or you mean anyone but forcing 480p on Nintendont?
I don't think it can be the TV. As I said, the game doesn't load, if it was a TV problem, I wouldn't see it, but the game should be running anyway. I know it for sure because I loaded the game with the AV cable, then changed to the component cable and I can see the game (black and white but it was running), then I loaded the game with the component cable (black screen...) and changed to the AV cable and the black screen continue, so for some reason it seems the game doesn't start and that is imposible to be the TV (I think, isn't it?)...

**Comment by carnage702** [comment]
changing cables does not do the same effect, when the game detects component on boot  it changes to a diferent res so even if you changed the cables mid throughthe game woudlnt change resolution anymore after boot.

just try hooking up to a diferent tv and you might be surprised.

**Comment by SieKensou** [comment]
OK. I will try on another TV and we will see (it's still too weird, is this the only game that runs in that way???). And how I have to do the other game test? Just any NTSC-U forced to 480p in Nintendont?

**Comment by carnage702** [comment]
any ntsu game with native 480p support  is fine 
https://en.wikipedia.org/wiki/List_of_GameCube_games_with_alternate_display_modes

take your pick and get any 480p  native game and leavue the video on auto.

Like i said some games do not use standard  resolutions we have an example of the megaman collection wich uses 240p and 288p when progressive is enabled wich manny tvs dont support nowadays and people cant play the game, this game might use a noone standard defenition aswhell.

**Comment by SieKensou** [comment]
I checked the list and I have some NTSC-U and NTSC-J games that I remember that I already have tried and they worked perfect (in the same TV, of course):
 - Auto Modellista [NTSC-U]
 - Buffy the Vampire Slayer: Chaos Bleeds [NTSC-U]
 - Donkey Konga 3 [NTSC-J]
 - FIFA Street 2 [NTSC-U]
 - Hudson Selection Vol. 2: Star Soldier [NTSC-J]
 - Hudson Selection Vol. 4: Adventure Island [NTSC-J]
 - Ikaruga [NTSC-U]
 - Kururin Squash! [NTSC-J]
 - Phantasy Star Online Episode I & II [NTSC-U]
 - Prince of Persia: The Sands of Time [NTSC-U]
 - Prince of Persia: The Two Thrones [NTSC-U]
 - The Simpsons: Hit & Run [NTSC-U]
 - Tony Hawk's Pro Skater 4 [NTSC-U]
 - Tony Hawk's Underground [NTSC-U]
 - Tony Hawk's Underground 2 [NTSC-U]
 - Tony Hawk's American Wasteland [NTSC-U]
 - True Crime: Streets of LA [NTSC-U]
 - Wave Race: Blue Storm [NTSC-U]
 - X-Men: Next Dimension [NTSC-U]
That ones for sure I have tried (and probably some others more that I'm not sure now) and they worked with the default Nintendont options and with the same component cable. I can test again one specific game if you tell me wich one.
I will try in another TV too.

**Comment by carnage702** [comment]
like i said i just want you to try prince of persia on another tv.

**Comment by SieKensou** [comment]
Okay, I tried and the result is the same, black screen and the game doesn't start.

**Comment by carnage702** [comment]
like i said i cant try it, maybe next month i will order a component cable for my wii and try it out even tough it works great on my pal wiiu.

**Comment by carnage702** [comment]
btw did you tryed the pal version forcing  either pal60+progressive or force ntsc+progressive? if they work you get 480p 60 hz pal game :P

**Comment by FIX94** [comment]
Just hooked my wii back up to my 3rd party component cable, started warrior within, it asked me if I wanted to display in progressive, said yes and it works just fine from there so I have no clue as to what could be wrong for you.

**Comment by SieKensou** [comment]
I didn't try that configuration, but the thing would be to try to find what is hapening with this game, if there is no other solution I will use the PAL version, but I would like to find what is hapening here.

**Comment by SieKensou** [comment]
Thanks for the test FIX94. Is your "Prince of Persia: Warrior Within" PAL or NTSC? The PAL version works fine for me too and shows the message of progressive, but when I try the same with the NTSC version of this game nothing happens, it just show a black screen. When I tried the original AV cable, as carnage702 suggest to try, the game loaded ok... So this is too weird :(

**Comment by FIX94** [comment]
I tested the NTSC redump.org-verified "Prince of Persia - Warrior Within (USA) (En,Fr,Es)" image.

**Comment by carnage702** [comment]
since fix94 has a pal wii and a component cable and he confirmed the game working im guessing its something wrong on your end maybe even your wii or something, do you have acess to some other wii you could test just incase?

**Comment by SieKensou** [comment]
Mine is NTSC redump.org-verified "Prince of Persia - Warrior Within (USA) (En,Fr,Es)" image too. The only difference seems to be that my component cable is the Nintendo official cable.
I don't think it can be my Wii. I have another Wii and a Wii U, but these ones are without homebrew, so I can't test there because my original game is PAL, I don't own the NTSC version of this game. I know that is not worth to try to find a solution for something that works for you both, but I'm sure there is something weird here. If you think is something more I could try, please, tell me.

**Comment by carnage702** [comment]
well you dont need to own it to test xD, why ahvent you moded your vwii on your wiiu? games look abit better on vwii a tiny bit but its still better due to wiiu upscalling xD, you dont even need a game to hack your vwii you can hack your wiiu vwii with wuphax made by fix94 himself xD.

**Comment by SieKensou** [comment]
Yes, right, I could, haha, but I want to keep that other Wii and the Wii U clean. Does it really looks better in Wii U? When I play Wii games in Wii U I think I see it worse than in the original Wii with the component cable... I didn't play too much Wii games on Wii U anyway. I only use this other Wii for all the homebrew. It's a pity what is happening with this game, I really don't understand why I'm experiencing this, I really would like to find someone with the same cable to test if it is something related to it or what... and why it works for you both and it doesn't for me when I use the component cable... All this is too weird and I'm not doing nothing wrong (I think)... Something more I could try?
Sorry if I'm bothering too much with this :(

**Comment by carnage702** [comment]
tbh i have no more ideas on what you can try you used diferent usbs,SD,diferent settings, iso is md5 cheked  since you claimed it so, tryed 2 tvs, some the only logical conculsion is your wii's fault is all i can say, being original or not makes no diferent its the same exact resolution going through the cable.

i remenber someone doing some testings and while is barely noticable the games do look like 2% better on vwii since wiiu upscales the vwii picture but its barely noticable unless you pay alot of attention and do shot per shot compares.

So yeah unfortunely we cant fix what doesnt happen at all and even CBCG said he cant reproduce the issue, i just remnebered one last thing did you always copyed the save file for the game around when you tested? maybe corrupted save file? did you try with mcemu off and removed anything that is on wii memory card doors?

**Comment by carnage702** [comment]
Also fix94 had another idea what language is your wii set? maybe try forcing language to english? could be that the game is shitty codded and both me and fix94 have english langauge pal wiis/wiius.

**Comment by SieKensou** [comment]
Great! Now we have more info to create a fix. The FIX94 idea worked, so for some reason, my component cable + Spanish Wii does that bug to happen.
Can FIX94 check if you forcing the languaje to Spanish with the component cable will cause the black screen as it happens to me?
Why that only affects when I'm using the component cable? Why it doesn't like the Spanish Wii?
I hope you can now find some answers now that you know where to look.

**Comment by carnage702** [comment]
So the ntscu version of the iso has support for **english,spanish and french** and im guessing the devs did a shiity coding on the prompt screen of  progressive display (yes or no) does not exist in spanish becuase they rushed the code and the forgot to put it translated, there is another game called bmx xxx where it doesnt even work with component cable on real gc because even in english they forgot to put the prompt screen for it, this is one of those issues since the component cable was so rare manny devs did a shitty codding the only way to "fix" this is a hack, im preety sure if you had a spanish ntscu GC(mexican,peru,etc) and used this agme with component it wouldnt boot either like bmx xxx.

**Comment by carnage702** [comment]
Also if you get a progressive prompt with pal version then the pal version will be 480p and 60hz so you dont gain anything from using the ntsc one instead.

Also fix94 said to me this isnt a nintendont bug but just pure dev error, they screwed the game and you cant get it to boot on a real ntscu gc with spanish and component either.

**Comment by SieKensou** [comment]
Okay, but even if it is not a Nintendont bug, now that we know about it, would be possible to be fixed? In that way I can load the game fine and I don't have to change any options, I know this is nothing important, but avoiding this error this game can be loaded in a Spanish Wii with Nintendont and Nintendont will be even more compatible than the original GameCube :D

**Comment by carnage702** [comment]
the only way to fix it would be doing a hack wich is a dirty work and fix94 said he didnt want to do it so yeah use the pal version you still get spanish,480p and 60 hz.

**Comment by SieKensou** [comment]
Oh :(
It would just require to apply that patch if component cable and Spanish Wii detected and this game would be playable directly in Nintendont. I know is nothing prioritary, but it would be nice to take it into account for creating that patch some day. I would be very thankful.
Thanks a lot for the help finding where the problem come from.

**Comment by carnage702** [comment]
its not just a "patch" you cant just click a button and make a game skip a progressiv prompt, it would need a very ugly patch.

**Comment by GB-CG** [comment]
Spanish Wii's are literally the same as the rest of the european Wii's because it's PAL. I can't imagine changing the Wii system langauge to English to make it work. That would be ridiculous.

**Comment by SieKensou** [comment]
OK cargange702, I understand. I know this things are not easy, but I thought that identifiying the problem will make the things easier (and I really was hoping a fix). I wonder what is really checking when the game keeps in that black screen and why it doesn't let the game start :/

Yeah GB-CG, sounds ridiculous but after the toons of tests we found that 2 conditions has to be at the same time to this happen, 1. Use a component cable and 2. Wii with Spanish languaje... (I didn't tested with ohter languajes, maybe others are affected too). These 2 things even doesn't seem to be related, but they are. If I use the AV cable it works with no need to change the languaje to English, and if I force the lenguage to English it works with the component cable... too weird... and it is the only game I have found with a problem like this...

**Comment by carnage702** [comment]
its not ridiculous  the CB CG  games check the system language and if the game supported that language they would start it on that lanuage and games that supported progressive would show when detecting a component cable connection the progressive screen prompt on that supported language, the game recognizes the wii/gc system langauge is spanish so it tries to start the game in spanish and before starting the game itself it needs to bring the progressive screen prompt and when it tryes to bring this screen in spanish language it doesnt detect one and the game crashes not nintendont but the game logic thats why you can exit the game fine, the game itself refuses to start until that screen appears and you choose an option.

i hope you guys understood all that.

**Its not wierd it works in english becuase the english progressive screen prompt is there to be called** no idea if the french one is there you can try forcing french(ntscu version supported english,spanish and french) and if the progressive prompt appears in french they didint forgot about it like they did with spanish.

When using AV/noone progressive capable cable the progressive prompt is never called so they game never crashes and starts normaly.

just because you are using a wii this game is still gc and the nintendont program turns wii calls into gc calls so anything that crashed the official gc will still happen here, there are manny gc games badly programed  that even crashed on the gc and then people think its nintendonts fault when it isnt.

**Comment by SieKensou** [comment]
Oh, yes, the way you explained it has sense, thanks. I don't know why they check the languaje, but doesn't have Spanish language for that screen (in the previous game and the newer of Prince of Persia that screen appears in English anyway, it doesn't matter my Spanish language Wii). So the full game is in Spanish, but if your Wii is using Spanish language, the game won't work lol
We know it is not a problem of Nintendont, but wouldn't be possible to just put a check when loading this game and if it detects the component cable AND Spanish language, force English language automatically. In that way the game would work in a Wii with Spanish language and it would work as always in the rest of cases.
I tested forcing French and yes, the prompt message appears in French... they completely forgot about the Spanish or there is a bug that doesn't load the Spanish prompt... who knows...

**Comment by FIX94** [comment]
so basically the actual question if you want progressive appears to be just missing, what I could write as a patch is to just not ask for progressive and all and if you actually want it then you could for example enable force progressive or switch to another language.

**Comment by SieKensou** [comment]
I really thank you for thinking about fixing this. The best would be that the game load with the progressive message to select (as it does the game normally), even if it appears in English (that is the way it appears in the other Prince of Persia games). Without any patch, forcing English it works, so that patch you describe won't worth because I would have to change options to make it work in progressive anyway. The best way should be something like what I described before (if it is possible), something that check for the component cable and the Spanish language in this game and if both conditions are true, in that case force English language so the progressive message will appear, after that there wont' be any problem because when it loads the game and my save file it will use Spanish language in the game.

**Comment by FIX94** [comment]
It was essentially easier for me to just ignore the progressive flag setting since I already had to do that for another game so its at least better than crashing IMO. I did of course make sure that setting force progressive works fine before committing this new version, so if you update just enable force progressive and you should be fine.

**Comment by SieKensou** [comment]
I tested the new version and yeah, it works fine. I really thank you for adding this fix, it is much better than crashing, of course. In fact, I checked again the PAL version and it is how it works, it doesn't show the progressive video message, just start checking the memory card (in Spanish) that is how now the NTSC-U version starts with your fix. THANKS!
It would be better to have the option of the progressive video mode, but it seems they corrupted the Spanish text and it doesn't find it (although in the picture you posted of Dolphin display correctly the selector of "SÍ" and "NO" :/

**Comment by FIX94** [comment]
also fun fact, I did read through memory in a hex editor and there IS a progressive question for spanish but it somehow cant converted to be displayed so on real console it crashes and since dolphin doesnt do any memory checks just doesnt display any question at all ;)

**Comment by SieKensou** [comment]
That confirms that they broke it in some way, nice find.
I was looking if there could be a v1.01 with that fixed but it seems it doesn't exist.
It would be really nice if you would have found a way to fix what they did wrong with the Spanish, but doesn't look easy (or yes, maybe it's only a bad offset or who knows...).
