### ISSUE TITLE
BloodRayne (PAL), sound bug...

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#417]
I tested the PAL version (PAL version from Spain) of this game long ago and I found this problem (I tested again with the actual version and the problem is still present).
In the sequences where the characters talk (with the in-game engine), the sound are constantly cut, if the phrases are short, it won't play nothing, its like it waits too much to start to reproduce the sound, so the begining of the phrase is mute and you only can hear the end.
I tested my original GameCube game disc of this game with Nintendont and it does the same.
I don't know if this happens in the other PAL/NTSC versions...

I use the last version of Nintendont updated to day (v4.442). The configuration is all by default, nothing enabled or forced, just the Memory Card emulation activated with a 251 blocks memory card.

**Comment by FIX94** [comment]
was easy enough to fix, just required to be in a special audio patch list.

**Comment by SieKensou** [comment]
Nice! It works perfect now. Thank you!
Congratulations for the great job you have done and you are doing with Nintendont! ;)
