### ISSUE TITLE
Problem with 2 different games but with the same 3 letters ID

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#421]
This 2 games are different games but they have the same ID:
GRO-Road Trip: The Arcade Edition
GRO-Gadget Racers
So both appear as "Road Trip: The Arcade Edition".
Gadget Racers is the sequel but it only was released in Europe.

The same case happens with this 2 discs:
D4B-Resident Evil 4 (Preview Disc)
D4B-Resident Evil 4 (BonusDisc)
That discs are different (one has a playable demo and some videos, the other has some videos and the making of).

Is there any way to make this games to appear with the right name?

**Comment by carnage702** [comment]
its not possible 

also that agame is not a sequel... its just the pal name

https://en.wikipedia.org/wiki/Road_Trip:_The_Arcade_Edition

Road Trip: The Arcade Edition USA , known as Gadget Racers in Europe and Choro Q! in Japan

no company can use the same gameid for diferent games nintendo does not allow that at all or else the save files would overwrite themselves, what you are seeing is the american name but the game is exactly the same acording to everything i saw.

**Comment by SieKensou** [comment]
Woow... yeah, my mistake... sorry. I should have tested both games before thinking the information I readed was true. I readed: "Gadget Racers (known in Japan as Choro Q HG 3) is a role-playing, racing game for the PlayStation 2. It is the sequel to Road Trip Adventure. It was also meant to be published in North America by Conspiracy Entertainment under the title Road Trip: Adventure Avenue but was cancelled."
It seems that is for PS2, the GameCube version, as you said, is the same (now I tested both and can confirm it). So the only problem is with the RE4 bonus discs, that is not a big problem.
Sorry!

**Comment by carnage702** [comment]
the ps2 version is diferent from the gc version

ps2 version is called gadjet racers in usa and its a port of choro q hg 3 and the gc has 3 names but its a port of choro Q!.

BTW isnt resident evil preview and bonus disc the same exact thing excpet its called bonus disc in europe and preview disc on usa?

Redump has no bonus disc on USA and pal has no preview disc, seems to be the same exact thing, did you tryed both versions to make sure they arent the same exact disc but on usa called preview and on Pal called bonus?

**Comment by SieKensou** [comment]
I have that 2 original discs of Resident Evil 4. The PAL disc (Bonus Disc) is just a disc with one video of each Resident Evil for GameCube plus a video of the Making Of Resident Evil 4. Nothing more and nothing playable. The USA disc (Preview Disc) contains the videos of each Resident Evil plus a playable demo of Resident Evil 4.
Even the menu where you select the videos are different...

**Comment by carnage702** [comment]
still it looks like its the same stuff but they added the demo in, sometimes even games have diferent content on usa/pal region, for instance luigi mansions is one of those where they have more stuff on pal.

**Comment by SieKensou** [comment]
Yes, maybe is suposed to be the "equivalent", the videos of the Resident Evil games are the same, but one having a playable demo and the other just a making of and the different look of the menú makes think they are different discs.

**Comment by carnage702** [comment]
when devs make the same gameid and just change the region they are the equivalente release on another region.

**Comment by SieKensou** [comment]
Okay, thanks!
Anyway it would be better if we could put the same game with different names if it is the case. That would work if Nintendont read the name with the first 4 character of the game ID, so we could set a name for D4BE and a different one for D4BP. I know this would require to rewrote the entire titles txt file, but would make the things better. Like this:
GROE-Road Trip: The Arcade Edition
GROP-Gadget Racers
D4BE-Resident Evil 4 (Preview Disc)
D4BP-Resident Evil 4 (BonusDisc)

**Comment by filevans** [comment]
yes but 2 disc games seem to use the same ID and show up the same, and you cannot distinguish which is disc 1 and 2, I've reported this before, for example, Metal Gear Solid Twin Snakes Disc 1 is the second one in the list, and DIsc 2 is the first one even

**Comment by carnage702** [comment]
well fix94 said nintendont only reads the first 3 letters and says the ntsc name its how its coded and he doesnt think its worth a rewrite.
