### ISSUE TITLE
Menu Resolution / Text Position

### ISSUE THREAD

**Issue by filevans** [FIX94/Nintendont#422]
hello 

Please could you change the menu resolution, or at least add as an option, 240p, as the font and menu is actually lo-res, and really suits 240p better (just like ELFLauncher on the PS2)

If that is too much hassle for now, could you move all the menu text down 1 pixel, as the position is 1 pixel out and straddles 2 scan lines on a CRT TV, so the text flickers then unnecessarily (in non-interlace mode)

thank you for listening

**Comment by carnage702** [comment]
manny newer tvs dont even display 240p anymore so yeah not gonna happen and nintendont menu isnt a gui if you want fancy looking stuff just use usbloader gx or wiiflow to load grames using nintendont and those loaders have all the fancy gui stuff.

**Comment by filevans** [comment]
240p is hardly fancy gui stuff, I don't see why it can't be added as an option for people who use CRT TVs, because one the main points of the Wii is its ability to output 240p for old games / emulators to be run in native and authentic low resolution on CRT TV, and a lot of people have a Wii connected to a CRT TV for that sole purpose

In the menu it lets you move the screen left and right, could you at least add up and down option then? or at least can you move the menu text down 1 pixel, as it is in the wrong place, surely that would be easy, so it slots correctly onto the CRT TV scan lines

**Comment by filevans** [comment]
Just move the Menu Text down exactly one pixel then and ill be happy, and then it will be correctly positioned for CRT TVs, at the moment its oddly positioned

**Comment by carnage702** [comment]
like i said nintendont menu is barebones becuase it was never meant to be used durectly, nintendont was mde so you could use a normal loader like cfg,usbloadergx,wiiflow and load gc games through it, the menu was basicaly done for people that dont care about gui stuff and just want to start the games the fastest way possible and the emnu is something you see for like 2 seconds before starting the game so i dont get why resolution or 1 pixel matters to you.People who like gui stuff just use loaders people who dont  just start the game the fastest way possible so who cares about the menu really.

**Comment by filevans** [comment]
none of what you just said explains why the gui has lots of options like move left and right and menu width. I dont want fancy gui stuff, I just want the text positioned where it should be, based on TV scan lines, instead of half way between them. I don't why it can't be done when it is such a simple request to move it down 1 pixel, then it suits all CRT TVs and scan line generators correctly, and would be just a case of setting the vertical screen coordinates 1 value higher, it is so easy to do when updating it along with other things next time

**Comment by carnage702** [comment]
those options do not affect the menu only they also affected some games that are pushed to the side and such same for width  this are not options made for the menu only but for the games.

every option there affects the games no option was even made for the menu the problem is just becuase  it stays like that on your crt doesnt mean moving one up will affect someone else tv saying now the menu is on this place and that place.
this is the reason a 240p option cant be made becuase imagine someone toying with the options, they hitted 240p and now they cant see shit and cant change it back either without putting nintendont folder on the pc and either changing the config or delete it.

**Comment by filevans** [comment]
rubbish, the menu items on the right column move gui left and right, and screen width also affects gui width, are you a coder on nintendont? as you should know that if so

**Comment by carnage702** [comment]
of course they also affect the menu i never said they didint... they also affect the games and they were made for the games lol affecting the menu is just an effect of affecting everything lol.

**Comment by filevans** [comment]
most wii emulators support 240p so they could accidentally switch that on there too so what's the difference! and big deal they have to delete / edit the config after on a PC! they have to put their ISOs on on a PC anyway!

**Comment by filevans** [comment]
I don't care if some modern LCD TVs don't support 240p now anyway, that's irrelevant, when the Wii has native 240p support and it is used in lots of things, so if someone chooses to buy the latest TV that doesn't support that's up to them! they just use 480p or whatever! That's like saying don't have 240p on any emulator at all because it's not supported on latest TVs! Ridiculous logic. One of the biggest points of the Wii is its 240p ability!!

**Comment by carnage702** [comment]
nintendont is open souce so if you want just make a fork for you  and make your own changes.

**Comment by carnage702** [comment]
nintendont is not an emulator, it doesnt do graphical or display options, we  only use what is in the software so your gc games dont even run in 240p and we cant add an option for that becuase like i said **nintendont is nor an emulator**, just becuase a wii can output  to 240p we cant force gc games to do so since  we arent emulating them or any display or graphical capabilities. all your games will run in 480i,576i,480p whatever they support we can only force those videomodes becuase nintendo sdk had them.

**Comment by filevans** [comment]
never said nintendont was an emulator, nor ever thought it was, nor even asked for GC games to be run in 240p. 
Simply stating that the **menu** could have a 240p option, or moved down 1 pixel, for correct positioning in deinterlaced mode on CRT TV or scanline generator. It is not in the correct position for a CRT TV, and no amount of you arguing changes that fact. Obviously you run on an LCD and don't understand what i'm saying. When the GC came out, no one even had LCD TVs, so authentically CRT TV users should not be just abandoned.
