### ISSUE TITLE
Stop Searching HDD after finding a Wii U's HDD at USB0

### ISSUE THREAD

**Issue by Kaede393** [FIX94/Nintendont#423]
On Wii U stop searching HDDs if it find a Wii U's HDD at USB0.
It is posible to avoid reading USB0 first and jump directly to USB1 or make it keep cheking USBs for a HDD with FAT format? I was trying to figure where to edit the source code, but didn't make any progress.

**Comment by Kalli44** [comment]
Nobody interested in this issue? It is not possible to use the USB-disk containing the GC games when the WiiU memory is extended with a disk formated in WiiU format. So I'm forced to use the SD-card containing GC games to circumvent this problem.

**Comment by carnage702** [comment]
its no one cares its a matter of first you can solve this issue by just unpluging the wiiu drive and second it would need a totaly rewriten usb code wich is over 100 lines of code and fix94 said he rewrote the code twice he probably will never touch the usb code again.

**Comment by GerbilSoft** [comment]
Please test this build and see if it fixes the problem:
https://github.com/GerbilSoft/Nintendont/raw/v5.457-WiiUSB1/loader/loader.dol

I added some code to usbstorage.c to skip drives that don't have a valid MBR or UStealth MBR signature, which should fix the common case where you have both a Wii U drive and GCN/Wii FAT32 drive connected at the same time.

**Comment by sceptios** [comment]
I just tested the WiiUSB2 version on my Wii U. I already had my Wii U set up with both a Wii U drive and a Wii drive. I put some GC games on the Wii Drive, and Nintendont was able to find and launch them.

Thank you for working on this!

**Comment by Kaede393** [comment]
It works on my set up.
USB0: Wii U UStealth
USB1: Wii NTFS/GCN FAT32 (Partition Disc)
YouTube: https://youtu.be/Cyhup1GxMM8
