### ISSUE TITLE
Pokemon Colosseum / XD Gale of Darkness (both NTSC)  black screen with cheats

### ISSUE THREAD

**Issue by trigao** [FIX94/Nintendont#424]
im having problems with these 2 games when i turn on the cheats
just gives me black screen, freezes and i have to hard reset my wii, otherwise, turning off the cheats, the games runs just fine as expected

Wii 4.3u
Usb Loader GX v3.0 r1262
Nintendont v 4.444

its the only games i've experienced this... tested more than 30 so far

**Comment by FIX94** [comment]
confirmed and fixed in the latest rev.

**Comment by biggkeel** [comment]
i know this issue has been closed and fixed. but is there anyway i could get some help. im not good at these things and i don't know what im supposed to do to fix this issue? i went to FIX94's page but i dont know what files im, supposed to use to fix this issue with the black screen. please help.
