### ISSUE TITLE
Swingerz Golf - Black screen after Nintendo copyright message

### ISSUE THREAD

**Issue by filevans** [FIX94/Nintendont#426]
hello

Swingerz Golf (NTSC-U) gives a Black screen after Nintendo copyright message, running PAL60 through RGB SCART

this game isn't listed as having a PAL60hz video mode on the PAL version (Ace Golf)

thank you

**Comment by carnage702** [comment]
did you tryed it wth video on auto?

**Comment by carnage702** [comment]
also the pal cover has no 60hz message at all 
https://r.mprd.se/GCN/Covers/Ace%20Golf.jpg

**Comment by filevans** [comment]
yes of course auto will work, as that will just run it in NTSC - the game's default video mode, but that will give a red tint screen through RGB SCART cable

I don't think the PAL version has PAL60 mode, so it won't run in 60hz (I hate running games in PAL 50hz)

**Comment by filevans** [comment]
There are a quite a few PAL games that don't have 60hz video mode, so the NTSC one is better, but certain games refuse to be forced into PAL60, and in NTSC mode they will give a very reddened screen

**Comment by carnage702** [comment]
not all games like to be forced to ntsc/pal some are so hardcoded that just refuse to run on it, specialy from ntsc to pal is the worse compat, you can try forcing pal 60 on the pal release instead of forcing the ntsc release to pal.

**Comment by carnage702** [comment]
also if you have a wii using component cable would be the best imo but im guessing your crt tv probably doesnt have component port or even if it does it wont support ntsc signals.

**Comment by filevans** [comment]
Yes I will try to get the PAL one and try that

a while ago I discovered a few NTSC games that would not run in PAL60 (as the PAL versions only supported 50hz) there was a patch that was added which enabled a few troublesome games to run in PAL60, like Luigi's Mansion and some others

**Comment by filevans** [comment]
my CRT TV supports NTSC fine, but Wii is an exception as it is the console itself that refuses to output correct colours through RGB SCART when run in NTSC

**Comment by carnage702** [comment]
yes but that is merely patching the pal 50 mode that used a slightly diferent codding wich is the option patch pal 50 wich helps some pal games to be forced ntsc, but ntsc to pal is another story.

**Comment by carnage702** [comment]
no component why?

**Comment by filevans** [comment]
No, Fix94 patched Luigi's Mansion NTSC to work in PAL60 and some other games too, I have the list of games somewhere, all NTSC TO PAL60 the patch worked for, it is not another story, it is the same story

**Comment by filevans** [comment]
these NTSC games Fix94 fixed with a patch to run in PAL60:
Ikaruga
Luigi's Mansion
Star Wars Rogue Squadron II

see the bottom part of this thread
https://github.com/FIX94/Nintendont/issues/228

**Comment by filevans** [comment]
forcing PAL 50 games to PAL60 has never worked for me, the PAL game has to have a 50/60hz selector from my experience, eg. Crazy Taxi, F-Zero GX

**Comment by filevans** [comment]
please could FIX94 make the patch encompass Swingerz Golf

**Comment by GB-CG** [comment]
@filevans just a suggestion: have you tried using a component-to-SCART transcoder? Maybe the Kenzei Sync Combiner device may able to bypass picture issues.

**Comment by carnage702** [comment]
i doubt fix94 will make a custom patch, for him nintendont is preety much finished and he says he is tired of wii and wiiu coding so dont expect  him to go getting a random crappy game like this.

also did you even readed your own thread? you were asking for pal 60 support and some 50hz only pal games dont know what a 60hz timing was and  crashed and didnt start so he basicaly made a patch to give all games a 60hz timing number , so yeah dont hope for miracles either get pal version and try forcing it to pal 60 and hope it works or just get a decent tv with component cable and play ntsc or you play the pal version in 50hz if your hardcoded into a crappy rgb connection.

**Comment by filevans** [comment]
I'll look into that, but Swingerz Golf is the final game I'm having trouble with now as the patch fixed the other games

**Comment by filevans** [comment]
carnage702 you're totally and absolutely ignorant, and I wish you wouldn't contribute to my threads, as you offer absolutely no assistance, just mindless, argumentative and annoying comments, full of stupid inaccuracies

if FIX94 isn't going to carry on with Nintendont there's no point to this github section anymore

**Comment by carnage702** [comment]
well im done with your threads then, you do realize that github makes every project open right ? anyone can fork nintendont, fix all the issues  they see and then submit a pull request to the main fork. 

Also even if fix continued with nintendont even tough its preety much finished besides missing bba/modden emulation, Forced stuff is not even a secondary cocern to fix94, he main point of nintendont was playing all gc games and it does that then its preety much finished.

**Comment by FIX94** [comment]
So much unneeded drama lol, anyways I fixed this game and crazy taxi, this particular golf game actually had PAL60 as video mode but the devs forgot to just accept it and let the game crash instead, so I made a hardcoded patch that just skips over that crash and it works fine (interestingly enough the NTSC-J version DOES handle PAL60 properly out of the box) and for crazy taxi it was just a thing of my previous patch not reaching it because it had the memory turned around a bit so I now search a bigger area to find it.
