### ISSUE TITLE
Saves Corrupt When Saved to Memory Card

### ISSUE THREAD

**Issue by Mikaphewn** [FIX94/Nintendont#427]
Whenever I have mem card emulation off. Then save to my memory card. I says it's corrupted when I try to load it.

**Comment by carnage702** [comment]
nintendont settings picture when you can.

**Comment by Mikaphewn** [comment]
Sorry for the late reply, but can you reopen this?


My Nintendont settings

cheats - off
Debugger - off
Debugger Wait - off
Memcard emulation - off
Cheat Path - off
Force Widescreen - on
Force Progressive - on
Auto Boot - off
Unlock Read Speed - off
OSreport - off
Drive Access LED - off
Log - off
MaxPads - 4
Language - Eng
Video - Auto

Native Control - off

Video Width - 640
Screen Position - 0
Patch Pal50 - off
TRI Arcade Mode - off
Wiimote CC Rumble - off
Skip IPL - No

**Comment by carnage702** [comment]
what size is your memrory card? is it an official memory card?what game do you save with?

**Comment by Mikaphewn** [comment]
It's 1019 blocks (127mb). It is an official memory card. I've had saves corrupt for Resident Evil, Spongebob: Battle for Bikini Bottom, Sonic Gems Collection, and Sonic Adventure DX. For some reason Sonic Adventure only corrupts the Chao Garden save,

**Comment by carnage702** [comment]
1079 blocks is  crap on the wii, there is manny problems with wiis and 1019 blocks memory cards

http://www.nintendo.com/consumer/memorycard1019.jsp

this is from nintendo itself, those cards can be corrupted when older games did stuff and the data management for the new technology didnt match so yeah those cards bring nothing but trouble.

**Comment by carnage702** [comment]
So yes nothing nintendont ca do you should get a smaller card or just use mcemu since its a wii hardware issue.

**Comment by Mikaphewn** [comment]
Damn. I've had this card for 7 years and this is the first I'm hearing about this. Well that sucks but it's no big deal. I'll just use memory card emulation.
