### ISSUE TITLE
Gamecube Controller not working at menu?

### ISSUE THREAD

**Issue by RatedRpoed** [FIX94/Nintendont#428]
My Gamecube Controller is not working at the Nintendont game menu.

It used to work no problem (haven't used it for a few months).

Read online about changing the native control setting but i can't change any of the settings as none of my controllers are working.

I can see all the games i have on my sd cards, when i try to use the controller the screen jumps a little.

On one sd card the screen jumps repeatedly at the game screen menu now also when it didn't do this before.

Help please?

**Comment by carnage702** [comment]
delete your ninconfig.bin and delete your nintendont boot.dol and redownload it, im guessing something went corrupt.
