### ISSUE TITLE
extFAT USB flash drive seems to be natively supported (everyone knows why?)

### ISSUE THREAD

**Issue by crakmaniaque** [FIX94/Nintendont#429]
Hi.
Thanks for this great piece of homebrew.
I'm using Nintendont on a Wii. Games are loaded via a 128 GB Sandisk USB flash drive formated in extFAT.
Even if the manual says FAT32 is required, it works like a charm.
It also works on my friend's Wii U.
Is it intended to?
Thanks you very much.

**Comment by FIX94** [comment]
as it says on the main page at the very bottom, both FAT32 and exFAT are supported.
