### ISSUE TITLE
Phantasy Star Online Episode I & II Plus (v1.05) JAP doesn't work

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#430]
I was trying to load this version of the game and just a black screen but the game doesn't start...
I'm using the last version of Nintendont with all default options except that I'm using memory card emulation (251). I tried disabling the bios but the game doesn't work either.
The iso is confirmed to be a good dump and it matches redump CRC-32 and MD5.

**Comment by carnage702** [comment]
take a picture of your nintendont settings, and i hate when people say they are using the latest and dont even say the number, and manny people think they have default settings when they dont most of the time.

**Comment by SieKensou** [comment]
Okay... When I say the last version at this day, so it is version 4.445, of course. Here is the picture...
![100_4655](https://user-images.githubusercontent.com/28622717/27611796-e6dd5e78-5b93-11e7-9f9a-5f4728b86ba7.JPG)

**Comment by carnage702** [comment]
well fix94 said he has no memory if he even patched any jap pso game lol he wonders if he forgot :P, and since no one ever asked to play the jap ones no one said anything about those versions not being patched since all PSO games have very specific patches to run on nintendont they arent standard coded games.

**Comment by FIX94** [comment]
pso as always a bitch to do, sure hope this was the last of it.

**Comment by SieKensou** [comment]
Thanks! Now the game loads fine, but I found another problem. After confirming the date/hour, my TV shows the message "No Signal" and the game freezes (I think that because I couldn't return pressing Home and I had tu Power Off the console pressing the Power button various seconds). Any idea why? As always, I'm using the official component cable and my console is PAL. I didn't found nothing like this in any other game :/

**Comment by carnage702** [comment]
remenber to press no on the clendar screen.

**Comment by SieKensou** [comment]
Yes, sorry, that text appears in japanese even with other language selected and saved on the memory card and I mistakenly selected "no". It works fine :)
