### ISSUE TITLE
Nintendont folders

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#431]
Just a small question/suggestion, why don't to make the SD/HDD look cleaner?... Would be easy to make that all the folders and config files of Nintendont was into a "Nintendont" folder?
Like:
HDD: Nintendont/games
HDD: Nintendont/saves
HDD: Nintendont/nincfg.bin
HDD: Nintendont/ipljap.bin
...And like that with all bios files and other files Nintendont uses.

Everything would look better in the SD or HDD and the folders would be in the same place and not mixed between the other SD/HDD files. What do you think?

**Comment by carnage702** [comment]
changing anything at this day and age would break usbloaders since tehy all know where nintendont files are and are coded to find those files and most usbloaders on wii/vwii are abondoned so there is no one left to update them.

**Comment by SieKensou** [comment]
That's a pity...
And what about if we keep the 2 options?
I mean, it can look for the files in the "Nintendont" folder and if it doesn't find them there, check on the root...

**Comment by carnage702** [comment]
fix94 said he wont change this since it would give way too manny isues for something that has been established since v1, and every loader would need an update or they wouldnt ever load nintendont again.

**Comment by SieKensou** [comment]
I don't know about other loaders, but at least USB Loader GX ask you for the GameCube games folder and you can set the one you want. What other loaders doesn't let you set the folder you want for the GameCube games? In case that is still a problem you can keep the "games" folder for the games but the other files (saves, config, bios, etc...) can be in a Nintendont folder.

**Comment by Raflos10** [comment]
I understand why the default paths can't be changed, but I don't see how adding support for custom paths would cause problems. 
I came here in my search for a way to change the /saves/ path, because I have my games on usb but want my save files on the sd card.
