### ISSUE TITLE
Shrek Super Slam (PAL) doesn't work with Memory Card Emulation

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#432]
I was testing this game and the game keeps in the screen where it ask you to create a save game or not (you can't even select not save, the game keeps there forever). I deactivate the memory card emulation and I can start the game.
It's the PAL game with ID G3YX

**Comment by FIX94** [comment]
just tested all 3 releases (G3YP, G3YY, G3YX) with first gc controllers and then a wiiu pro controller and it worked perfectly fine in all versions so you must have some other problems.

**Comment by SieKensou** [comment]
Thanks for the tests. I tried lots of times and it didn't worked. Now I deleted the game from my HDD and copied it again and deleted the Nintendont config file, tried again and it worked. No idea what was happening before :/

**Comment by carnage702** [comment]
sometimes even when copying stuff to hdd/sd they have a chance to not pass properly, i know i had several times issues when passing even homebrew dols that would not work becuase they were bad or something and a simple copy paste worked again lol.
