### ISSUE TITLE
Fire Emblem Path of Radiance (NTSC) White Screen

### ISSUE THREAD

**Issue by lucaspanther** [FIX94/Nintendont#434]
hi
after the first chapter (tutorial) the game crashes into a white screen for me, haning up the console. 
I have did a little bit searching on internet and this seems a common problem for this game.

**Comment by carnage702** [comment]
this is a random problem for some people when changing chapters no one knows why it seems it has to do with the hdd speed or settings or something, some pleople play the entire game no problems others get white screens when changing chapters, make sure you are using an md5 checked iso and have no forced or extra settings turned on and that your hdd/sd  is fast.

**Comment by lucaspanther** [comment]
Settings on Nintendont are the default ones, i did not touch anything.
I tried the same .iso with Dios Mios and the same HDD and it works.
I tried the same .iso with Dolphin and it works too.
It is a Nintendont related bug (or whatever).

**Comment by carnage702** [comment]
dolphin and dios mios working or not has no efect on nintendont working on not also what you consider default is what might not be default, like i said lots of people played this game and some didint get any freezes while others did, a reason was never found tough. i played like until chapter 3 or 4 and never got a freeze at chapter ending, all i can say is it might be the hdd or sd not being optimal speed or some setting people use.

**Comment by lucaspanther** [comment]
Ok I found the fix or workaround.. or whatever you want to call it. 
I use USBLoaderGX to boot up the game, and if you go into USBLoaderGX game settings there is an option called "remove read speed limit" which is turned off by default. If you turn this to on the game won't crash after chapter ending (I tried until 3rd chapter, keep doing further tests). If it works I will modify Nintendont compatibility list leaving this solution for crash in a note.
Thanks for you help anyway, appreciated it.

**Comment by Saiklex** [comment]
I don't mean to necro-bump, but just wanted to say I also had the same problem on the latest version as of now (4.448?) and turning on "Remove speed limit" (I did it inside Nintendont but that's irrelevant) fixed the issue. Didn't find this fix anywhere else so I just thought I'd reconfirm it.

**Comment by FIX94** [comment]
well I just added it into that exception list to always have the limit removed, hopefully it helps at least somewhat.
