### ISSUE TITLE
Nintendont Freezes whenever picking a GCN game.

### ISSUE THREAD

**Issue by RedMountain95** [FIX94/Nintendont#436]
I have been using Nintendont on my Wii U since November via SD card however recently it has decided to freeze whenever I pick a game to play. Like I get to the screen where I pick a GCN game it loads but just freezes on the white screen with the various black loading text.

I have tried replacing the Oct 2016 Nintendont files with June 2017 but it STILL freezes. It gets so bad that I have to unplug my Wii U.

**Comment by donut3226** [comment]
Have you added any USB HDDs to the Wii U?

**Comment by RedMountain95** [comment]
I've always had my Dualshock PS3 Controller added to the Wii U. And ever since October it was working perfectly. 

I've never added any sort of new controllers or usb devices to the Wii U since.

**Comment by carnage702** [comment]
that is normal, sometimes  ps3/ps4 controllers corrupt some nintendont files, if you have a controller ini delete it same for ninconfig.bin.

**Comment by RedMountain95** [comment]
Alright so basically delete both of those files and find an alternative controller? Or keep using the dualshock? Does the gamecube adapter work on this guy?

**Comment by carnage702** [comment]
you can keep using it but ps3/ps4 controllers for whatever reason very very rarely corrupt those files no one knows why, also try to unplug the usb controller and start the gc games if they start normay its for sure the ps3 controller fault.

Also you dont need a controller ini to use a ps3 controller anymore if you have latest nintendont version.

some people had this issue i never did and no one knows what causes it tbh.

**Comment by RedMountain95** [comment]
Alright. PS3 controller IS the issue. I unplugged it and the game started up fine. I then plugged in the controller and the Wii U just restarted. I then loaded it up with USB connected switched ports when the GCN game started up and the Wii U restarted again.

I also confirmed that I DO have the latest update (the Jun 28 4.446 version I believe) and the PS3 controller still won't work even with the few seconds I use it before it restarts :(. 
I may have to use a different controller after all.

**Comment by carnage702** [comment]
did you deleted ninconfig.bin and any controller.ini you might have on sd and usb?

also you dont need another controller you need is a reset of it.

http://ccm.net/faq/35811-playstation-3-how-to-reset-your-controller

**Comment by RedMountain95** [comment]
Good News! I was capable of having work via PS4 controller after deleting my key.bin and nand.bin files.

However, it ONLYS works when I plug in the controller when the GCN game boots up. If I plug it in before or press any buttons it resets. 

Now how do I change the button map on the PS4 or do I just get used to it?

**Comment by carnage702** [comment]
go to the controller folder and grab the ps4 controler file, change what you want and  then rename that ini file  to controller.ini and place it on the root of where you have your iso being sd or usb.

**Comment by RedMountain95** [comment]
AMAZING! Nintendont is working just like it did last week.
LAST QUESTION! 
Now what "power" refer to in PS4 controller.ini? Does it reset the Wii U and what button is it referring to on the PS4?

**Comment by carnage702** [comment]
power is to exit nintendont and back to the homebrew channel. on the ps3 controller it was the select button on ps4 maybe its share or something lol.
