### ISSUE TITLE
Compiling Nintendont - bin2h: cannot execute binary file (OSX)

### ISSUE THREAD

**Issue by SuperMarioDaBom** [FIX94/Nintendont#438]
There seems to be a problem with the bin2h provided in the source. It never runs - it always gives a "cannot execute binary file" error. All necessary locations are in the PATH, so it can't be that. Even when I ran it outside of the Nintendont compiler, it still gives this error. If it helps, here is the output of the compilation:

Cleaning all subprojects...
 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C multidol clean
rm -f -rf multidol_ldr.elf ../loader/data/multidol_ldr.bin crt0.o cache.o main.o global.o apploader.o dip.o utils.o .deps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C kernel/asm clean
clean ...
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C resetstub clean
rm -f -rf tinyload.elf ../loader/data/stub.bin crt0.o memory.o ios.o utils.o cache.o usbgecko.o main.o .deps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C fatfs -f Makefile.arm clean
rm -f -f *-arm.a *-arm.o *-arm.d
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C fatfs -f Makefile.ppc clean
rm -f -f *-ppc.a *-ppc.o *-ppc.d
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C codehandler clean
rm -f codehandler.h codehandleronly.h codehandler.bin codehandleronly.bin
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C kernel clean
rm -f -f ../loader/data/kernel.zip *.elf *.o *.bin *.d *.map lwbt/*.d lwbt/*.o option/*.d option/*.o
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C loader/source/ppc clean
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C loader clean
clean ...
rm -f -rf build /Users/<username>/Downloads/nintendont/loader/loader.elf /Users/<username>/Downloads/nintendont/loader/loader.dol
 
Building Multi-DOL loader
 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C multidol
 ASSEMBLE    crt0.S
 COMPILE     cache.c
 COMPILE     main.c
 COMPILE     global.c
 COMPILE     apploader.c
 COMPILE     dip.c
 COMPILE     utils.c
 LINK        multidol_ldr.elf
 OBJCOPY     ../loader/data/multidol_ldr.bin
 
Building reset stub
 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C resetstub
 ASSEMBLE    crt0.S
 ASSEMBLE    memory.S
 COMPILE     ios.c
 COMPILE     utils.c
 COMPILE     cache.c
 COMPILE     usbgecko.c
 COMPILE     main.c
 LINK        tinyload.elf
 OBJCOPY     ../loader/data/stub.bin
 
Building FatFS library for PPC
 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C fatfs -f Makefile.ppc
CC	ff-ppc.o
CC	ff_utf8-ppc.o
AR	libfatfs-ppc.a
 
Building asm files
 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C kernel/asm
 ASSEMBLE    ARQPostRequest.S
 ASSEMBLE    ARStartDMA.S
 ASSEMBLE    ARStartDMA_Hook.S
 ASSEMBLE    ARStartDMA_PM.S
 ASSEMBLE    ARStartDMA_TC.S
 ASSEMBLE    CalcGXWidescreen.S
 ASSEMBLE    CalcWidescreen.S
 ASSEMBLE    CalcWidescreenDiv.S
 ASSEMBLE    CheckTestMenu.S
 ASSEMBLE    CheckTestMenuGP.S
 ASSEMBLE    CheckTestMenuVS.S
 ASSEMBLE    CheckTestMenuYakyuu.S
 ASSEMBLE    DVDLowAudioBufferConfig.S
 ASSEMBLE    DVDLowAudioStream.S
 ASSEMBLE    DVDLowRequestAudioStatus.S
 ASSEMBLE    DVDSendCMDEncrypted.S
 ASSEMBLE    DatelTimer.S
 ASSEMBLE    EXIDMA.S
 ASSEMBLE    EXIGetID.S
 ASSEMBLE    EXIImm.S
 ASSEMBLE    EXILock.S
 ASSEMBLE    EXIProbe.S
 ASSEMBLE    EXISelect.S
 ASSEMBLE    FakeAIInterrupt.S
 ASSEMBLE    FakeEntryLoad.S
 ASSEMBLE    FakeInterrupt.S
 ASSEMBLE    FakeInterrupt_DBG.S
 ASSEMBLE    FakeInterrupt_Datel.S
 ASSEMBLE    FakeRSWLoad.S
 ASSEMBLE    FakeRSWStore.S
 ASSEMBLE    GCAMSendCommand.S
 ASSEMBLE    GXInitTlutObj.S
 ASSEMBLE    GXLoadTlut.S
 ASSEMBLE    MajoraAudioStream.S
 ASSEMBLE    MajoraLoadRegs.S
 ASSEMBLE    MajoraSaveRegs.S
 ASSEMBLE    OSExceptionInit.S
 ASSEMBLE    OSReportDM.S
 ASSEMBLE    PADControlAllMotors.S
 ASSEMBLE    PADControlMotor.S
 ASSEMBLE    PADControlMotorGP.S
 ASSEMBLE    PADIsBarrel.S
 ASSEMBLE    PADRead.S
 ASSEMBLE    PADReadF.S
 ASSEMBLE    PADReadGP.S
 ASSEMBLE    PADReadVS.S
 ASSEMBLE    PADReadVS3.S
 ASSEMBLE    ReadROM.S
 ASSEMBLE    RestoreSettingsAX_RVC.S
 ASSEMBLE    RestoreSettingsAX_RVD.S
 ASSEMBLE    RestoreSettingsAX_RVE.S
 ASSEMBLE    RestoreSettingsVS3V02.S
 ASSEMBLE    RestoreSettingsVS4EXP.S
 ASSEMBLE    RestoreSettingsVS4JAP.S
 ASSEMBLE    RestoreSettingsVS4V06EXP.S
 ASSEMBLE    RestoreSettingsVS4V06JAP.S
 ASSEMBLE    RestoreSettingsYAKRVB.S
 ASSEMBLE    RestoreSettingsYAKRVC.S
 ASSEMBLE    SIGetType.S
 ASSEMBLE    SIInitStore.S
 ASSEMBLE    SIIntrruptHandler.S
 ASSEMBLE    SITransfer.S
 ASSEMBLE    SonicRidersCopy.S
 ASSEMBLE    SwitcherPrs.S
 ASSEMBLE    TCIntrruptHandler.S
 ASSEMBLE    __ARHandler.S
 ASSEMBLE    __CARDClearStatus.S
 ASSEMBLE    __CARDReadStatus.S
 ASSEMBLE    __DSPHandler.S
 ASSEMBLE    __DVDInterruptHandler.S
 ASSEMBLE    __GXSetVAT.S
 ASSEMBLE    codehandler_stub.S
 ASSEMBLE    patch_fwrite_GC.S
 ASSEMBLE    patch_fwrite_Log.S
 STRIP       ARQPostRequest.elf
 STRIP       ARStartDMA.elf
 STRIP       ARStartDMA_Hook.elf
 STRIP       ARStartDMA_PM.elf
 STRIP       ARStartDMA_TC.elf
 STRIP       CalcGXWidescreen.elf
 STRIP       CalcWidescreen.elf
 STRIP       CalcWidescreenDiv.elf
 STRIP       CheckTestMenu.elf
 STRIP       CheckTestMenuGP.elf
 STRIP       CheckTestMenuVS.elf
 STRIP       CheckTestMenuYakyuu.elf
 STRIP       DVDLowAudioBufferConfig.elf
 STRIP       DVDLowAudioStream.elf
 STRIP       DVDLowRequestAudioStatus.elf
 STRIP       DVDSendCMDEncrypted.elf
 STRIP       DatelTimer.elf
 STRIP       EXIDMA.elf
 STRIP       EXIGetID.elf
 STRIP       EXIImm.elf
 STRIP       EXILock.elf
 STRIP       EXIProbe.elf
 STRIP       EXISelect.elf
 STRIP       FakeAIInterrupt.elf
 STRIP       FakeEntryLoad.elf
 STRIP       FakeInterrupt.elf
 STRIP       FakeInterrupt_DBG.elf
 STRIP       FakeInterrupt_Datel.elf
 STRIP       FakeRSWLoad.elf
 STRIP       FakeRSWStore.elf
 STRIP       GCAMSendCommand.elf
 STRIP       GXInitTlutObj.elf
 STRIP       GXLoadTlut.elf
 STRIP       MajoraAudioStream.elf
 STRIP       MajoraLoadRegs.elf
 STRIP       MajoraSaveRegs.elf
 STRIP       OSExceptionInit.elf
 STRIP       OSReportDM.elf
 STRIP       PADControlAllMotors.elf
 STRIP       PADControlMotor.elf
 STRIP       PADControlMotorGP.elf
 STRIP       PADIsBarrel.elf
 STRIP       PADRead.elf
 STRIP       PADReadF.elf
 STRIP       PADReadGP.elf
 STRIP       PADReadVS.elf
 STRIP       PADReadVS3.elf
 STRIP       ReadROM.elf
 STRIP       RestoreSettingsAX_RVC.elf
 STRIP       RestoreSettingsAX_RVD.elf
 STRIP       RestoreSettingsAX_RVE.elf
 STRIP       RestoreSettingsVS3V02.elf
 STRIP       RestoreSettingsVS4EXP.elf
 STRIP       RestoreSettingsVS4JAP.elf
 STRIP       RestoreSettingsVS4V06EXP.elf
 STRIP       RestoreSettingsVS4V06JAP.elf
 STRIP       RestoreSettingsYAKRVB.elf
 STRIP       RestoreSettingsYAKRVC.elf
 STRIP       SIGetType.elf
 STRIP       SIInitStore.elf
 STRIP       SIIntrruptHandler.elf
 STRIP       SITransfer.elf
 STRIP       SonicRidersCopy.elf
 STRIP       SwitcherPrs.elf
 STRIP       TCIntrruptHandler.elf
 STRIP       __ARHandler.elf
 STRIP       __CARDClearStatus.elf
 STRIP       __CARDReadStatus.elf
 STRIP       __DSPHandler.elf
 STRIP       __DVDInterruptHandler.elf
 STRIP       __GXSetVAT.elf
 STRIP       codehandler_stub.elf
 STRIP       patch_fwrite_GC.elf
 STRIP       patch_fwrite_Log.elf
 BIN2H       ARQPostRequest.bin
../bin2h/bin2h: ../bin2h/bin2h: cannot execute binary file
make[1]: *** [ARQPostRequest.h] Error 126
make: *** [kernel/asm] Error 2

I would be very appreciative if someone could help me!

--SuperMarioDaBom

**Comment by FIX94** [comment]
the bin2h binary provided is for standard linux x86 envs so you have to run the make.sh in the bin2h folder first to make it compatible for your OS.

**Comment by SuperMarioDaBom** [comment]
Receiving this error when trying to build bin2h in the /nintendont/kernel/bin2h/ folder: 

main.c:22:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^
1 error generated.

Am I missing a library?

**Comment by FIX94** [comment]
I dont have a mac but from spending 2 seconds on google it sounds like on mac you have to include stdlib.h instead.

**Comment by SuperMarioDaBom** [comment]
Ok I will try that now

**Comment by SuperMarioDaBom** [comment]
bin2h file has disappeared, and no file has been put in its place. Terminal output:

main.c:64:48: warning: format specifies type 'unsigned int' but the argument has
      type 'size_t' (aka 'unsigned long') [-Wformat]
        fprintf(f,"#define %s_size 0x%x\n\n",basename,fsize);
                                     ~~               ^~~~~
                                     %zx
1 warning generated.
ld: warning: option -s is obsolete and being ignored
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
chmod: bin2h: No such file or directory

From what I can tell, a library is missing causing it to fail. Which one it is I have no idea.

**Comment by SuperMarioDaBom** [comment]
I tried messing around with the compiler, and I think I got it to work. I removed the -static flag, which removed that error and created a seemingly successful build of bin2h. I then ran the main compiler of nintendont, which appears to also have compiled successfully. I will test it on my Wii to make sure it actually worked.

**Comment by SuperMarioDaBom** [comment]
And it appears to be working! Thanks for the help @FIX94 !

**Comment by ccfman2004** [comment]
On newer Macs you need to use -m64 instead of -m32

**Comment by cystbear** [comment]
@ccfman2004 wow you have rescued me !
