### ISSUE TITLE
Nintendo Gamecube Service Disk 

### ISSUE THREAD

**Issue by TripAway** [FIX94/Nintendont#442]
i tried to play the ISO of "Gamecube Service Disk" on Nintendont,but when i play it,i get black screen.
Why and how i fix it?

**Comment by carnage702** [comment]
afaik its not supported becuase it uses an undocomented form of sdk.

**Comment by FIX94** [comment]
literally no patch in nintendont applies to it, so just to support it you would have to basically analyze and write a new set of patches for everything in it.

**Comment by FIX94** [comment]
well it boots now and the basic audio/video patches work, good enough for me.
