### ISSUE TITLE
Need For Speed Most Wanted start button

### ISSUE THREAD

**Issue by NoahBrown0** [FIX94/Nintendont#444]
I use the classic controller to play my nintendont games. When I boot up NFSMW and get to the start screen start button does not work. Is this a personal problem or is it the emulators issue? My start button works on other games perfectly.

Plzzzzz send help

**Comment by carnage702** [comment]
maybe the game is codded so that start doesnt work there lol, did you tryed pressing A?

**Comment by NoahBrown0** [comment]
Yeah I pressed everything on my fucking controller

**Comment by carnage702** [comment]
you sure you didnt enabled native to on? or plugged in a gc controller or an hid controller? those will take the player 1 status before bt controllers, also if native is on you cant use bt or hid controller.

BTW nintendont is not an emulator at all.

**Comment by NoahBrown0** [comment]
Oh. I'll try that. Thanks


BTW thanks

**Comment by NoahBrown0** [comment]
I'll get back to you.

**Comment by NoahBrown0** [comment]
I downloaded the ROM again and will try it again in the morning.

**Comment by NoahBrown0** [comment]
Hope it was a freak issue.

**Comment by NoahBrown0** [comment]
Well............. I tried again. It still does not work even with your native suggestion. Hope this can get fixed soon. I hear NSFMW is great.

**Comment by FIX94** [comment]
US version works perfectly fine in v4.451 here with native on and off, using a gamecube controller and wiiu pro controller, maybe you have some REALLY outdated nintendont version so make sure to get the current one.

**Comment by NoahBrown0** [comment]
Thanks for your help. I am on version v4.446 (Wii) and will update it now. Thanks! If i have a recurring issue i will get back to you.
