### ISSUE TITLE
Legend of Zelda: Four Swords Adventures - GBA loses connection during 2-player game

### ISSUE THREAD

**Issue by SedrynTyros** [FIX94/Nintendont#446]
Title is fairly self-explanatory.

I'm playing with two GBA consoles attached to a Wii with official GBA-link cables.  When playing with a genuine game disc (I own one) the games works fine; no problems.  But when playing with a redump copy of the game using USBLoaderGX with Nintendon't, one of the two GBAs will always lose its connection within the first 30 minutes of play.  When the connection is lost, the game quits and returns to the main menu.  Since you can only save at the end of stages, this makes the game unplayable with Nintendon't because one of the GBAs will always lose its connection before you can get to the first save point.

**Comment by FIX94** [comment]
It does not sound like a problem with nintendont but with the cable itself, I know from experience there are a lot of cables with dodgy contacts and inconsistent I/O leading to problems like this, when you have nintendont in native mode it does not touch any of the PAD registers and lets the game do it all through the original hardware without having a hand in them, so maybe clean the cables and I guess test both out to see which one is the troublemaker and switch it out for a different one in the worst case.

**Comment by SedrynTyros** [comment]
How is it a problem with the cable when playing the actual, physical game, outside of Nintendon't emulation, with the same cables, has zero problems?  The cable is fine.  The problem is almost certainly with Nintendon't.  Once you take Nintendon't out of the equation and use a physical disc, on the same exact hardware, there are no problems.

**Comment by SedrynTyros** [comment]
Having said that, I can play the game fine since I own a physical copy and therefore don't need Nintendon't to play it.  I was just trying to help you guys out by bringing to your attention what to me looks to me like a bug in Nintendon't.

**Comment by carnage702** [comment]
are  your cables official? or 3rd party? one user was having issues becuase he had 3rd party gc cable and he bought an official one and no more problems.

**Comment by SedrynTyros** [comment]
carnage702, please see my first post:

"I'm playing with two GBA consoles attached to a Wii with **official GBA-link cables**."

And I'll just say it one more time, there's nothing wrong with the cables!!!  When you use them with a real game disc on hardward (sans Nintendon't) they work without issue.

**Comment by carnage702** [comment]
well you dont have any options forced? like patched videomods,unlock read speed,log,osreport,etc? you have everything off or auto? since you never showed a pic of your settings.
