### ISSUE TITLE
James Bond 007: From Russia with Love support widescreen?

### ISSUE THREAD

**Issue by nictse2013** [FIX94/Nintendont#449]
http://wiki.gbatemp.net/wiki/Nintendont_Compatibility_List
says eurp version support widescreen
but i tested both us and eurp version,dont support widescreen.
anyone try it?

**Comment by carnage702** [comment]
remenber people filled the list long time ago and they saw stretched 4:3 and putted yes on the compatibility list, so preety much 90% of the widescreen stuff on there is wrong.

**Comment by nictse2013** [comment]
ok ....
i get it,but super mario sunshine support real 16:9

**Comment by carnage702** [comment]
the widescreen hack does not works for every game, on some it does nothing, on others it works on others it makes the games even crash.
