### ISSUE TITLE
[PS3/PCGamepad] VID=2563 PID=0523 not working

### ISSUE THREAD

**Issue by Vegeta780** [FIX94/Nintendont#450]
Hello my file 2563_0523.ini in controllers folder and setting 
`[PS3/PC Gamepad]
VID=2563
PID=0523
A=4,40
B=4,20
X=4,10
Y=4,80
CStickY=4
CStickX=4
StickY=4
StickX=4
Start=5,20
Up=4,00
Right=4,02
Left=4,06
Down=4,04
L=5,04
R=5,08
Z=5,02
`

please what should i do is there a way to work controller and my game controller work with PCSX2 and Dolphin 5.0 but i want too play on WIIU 
Thanks in advance

**Comment by carnage702** [comment]
just put all that in an ini file and rename it to controller.ini and place it on the root of the device you have your isos, if your isos are on usb put the controller.ini on usb root, if on sd put it on usb root.

**Comment by Vegeta780** [comment]
thanks for reply i do   that method  but nothing work still i can not control from (When i launch from HBL option Native = on and i cant change to off but then i try to change from USBLadergx2 and change HID Controller  "ON" and Native = Off but still don't work My game Pokemon is still running and i cant control from game and Wiimote ( am so amaze game running full speed WOWWWW but ????? Controller

**Comment by carnage702** [comment]
when you launch nintendont directly from the homebrew channel you can controll nintendont menu with it? if so try deleting the ninconfig bin on usb and sd so native is always turned off.

**Comment by Vegeta780** [comment]
I deleted file and Now it's native off but still not working controller I change both lights red etc
I used new.au3 script to create mapping button
see this [https://s2.filetrip.net/p/25065/387567-zz.jpg](url)
am using HomebreChannel 1.1.2 IOS58 V25.32
USB 4GB
SD CARD 64GB
Nindendont 4.448(WIIU) 12 Aug 2017 Built
Frimware 58.25.32

**Comment by Vegeta780** [comment]
i guess i Can't play GC games on Wiiu What a pain in Neck I  just purchase PS2 Adapter especially for Nindentdont But I have a no Luck Oh well
 (am thinking about PS3 Controller But no wait I cant spend money  am  just saving  money for Nintendo Switch ) 
Help me with this controller

**Comment by carnage702** [comment]
does your ini have pooltype on it and digital lr and such?  link me your ini.

**Comment by Vegeta780** [comment]
i just rename ini to txt

[2563_0523.txt](https://github.com/FIX94/Nintendont/files/1257518/2563_0523.txt)

**Comment by carnage702** [comment]
just try this file do not ranme it or change it
http://www.mediafire.com/file/fvud1bt34756m1m/Controller.ini

place it on the root if your usb and sd, you know what root means correct?

**Comment by Vegeta780** [comment]
![rt](https://user-images.githubusercontent.com/31349213/29784007-eaf8bfba-8c3b-11e7-9341-436a7af770c0.jpg)
Thanks and I try but not working only wiiremote is working with option
I have  SD CARD 64GB and games>pokemon.iso

**Comment by carnage702** [comment]
just use hud test becuase maybe the values on that program arent correct imo.

are you using nintendont directly? since i see no ninconfig.bin in there and when you use nintendont directly a ninconfig.bin is created on the root aswhell. or you are suing usbloadergx/wiiflow/whatever?

**Comment by Vegeta780** [comment]
am not using usbloadergx just  use nintendont directly and i deleted ninconfig.bin

**Comment by carnage702** [comment]
if you launched a game it would creat another one unless you delete it everytime for some odd reason.

so even on the nintendont menu you cant move the cursor up and down with the hid controller? not saying ingame but in nintendont menu  you cant move anything?

**Comment by Vegeta780** [comment]
when pokemon game running i cant use wiiremote and Controller both

**Comment by Vegeta780** [comment]
well nintendont create file and i use so many time run games for testing and to delete everytime ha ha ha am not a fool

**Comment by carnage702** [comment]
you didnt awnsered my question at all... when you are on nintendont itself cant you mvove the cursor up and down with your usb controller?

**Comment by Vegeta780** [comment]
> you didnt awnsered my question at all... when you are on nintendont itself cant you mvove the cursor up and down with your usb controller?
Yes i cant move teh cursor up and down with USB Controller But i can move with wii remote

**Comment by carnage702** [comment]
https://github.com/FIX94/Nintendont/raw/master/controllerconfigs/HID_Test.dol

launch this dol on your wii and use your usb controller and click the buttons to see if anything changes on it to see if the wii can actualy see your hid controller.

**Comment by Vegeta780** [comment]
Yes it's Working buttons but i cant understand i show the picture

**Comment by Vegeta780** [comment]
sorry for bad picture
![img_20170828_221659](https://user-images.githubusercontent.com/31349213/29785062-a4524e74-8c3f-11e7-94bd-39f3558e6ba7.jpg)

**Comment by Vegeta780** [comment]
Well I got something When i press X 
It's Change the value like 0F = 4F   A=1
How to write ?

**Comment by carnage702** [comment]
just delete your controller.ini from your sd card and launch that app again, it usualy shows pid bid and everything alos launch the app with the controller plugged in.

**Comment by Vegeta780** [comment]
Ok Whats next ?
Failed to open Config
....
...
....
VID 2563 PID 0523
bend point address 
press some button ig the value change the device is compt...

press power or turn the  wiimote off to powrer down :81
wmax packetsize 32 

7F 7F 7F 7F 0F 0000000000000000000000000
and button is working

**Comment by carnage702** [comment]
well tbh i dont really know how to use hidtest app but if buttons change then its compatible just making sure you have anything connected to your usb ports besides the hid controller?

**Comment by Vegeta780** [comment]
just SD Card and USB Adapter is connected 
SO I just  create ini file for my controller ??

**Comment by carnage702** [comment]
you use an sd card through usb adapter? and not through the wii sd slot?

technicaly people used hidtest to creat ini files for nintendont from there.

**Comment by Vegeta780** [comment]
No No I have SD card not Microcard i mean no using SD card adapter
 SD CArd put in WiiU Front SLot

**Comment by carnage702** [comment]
ITs not Start but S but yeah its preety wierd your controller doesnt work on nintendont, what version of nintendont are you using is it the latest 4.448?

**Comment by Vegeta780** [comment]
Yes Sir
Nindendont 4.448(WIIU) 12 Aug 2017 Built
Frimware 58.25.32

**Comment by carnage702** [comment]
try deleting nintendont boot.do and redownloading it it could have become corrupt and loose hid stuff, it happens sometimes.

**Comment by Vegeta780** [comment]
OK i did but not moving cursor  up and down X O Any button And When I test With HID Test Then It's Working Fine and I download Latest Version  ( iguess three times )
I used Old Version but Failed

**Comment by Vegeta780** [comment]
Well am too tired am testing and checking 1 week  i used every method but no luck
i need senzu bean

**Comment by carnage702** [comment]
maybe your controller just doesnt work on nintendont no idea what to tell you tbh.

**Comment by carnage702** [comment]
fix94 gave the idea of enabling log and osreport and go ingame and then plug and unplug your controller afew times then exit and put the log file that will be created on your sd card here if you wanna try that remenber to use a controller ini on the root while doing loag stuff.

**Comment by Vegeta780** [comment]
i rename .log to .txt ( just for Uploading)
[ndebug.txt](https://github.com/FIX94/Nintendont/files/1258880/ndebug.txt)
i just plug and unplug controller when pokemon Running ( 4 or 5 times i guess)

**Comment by Vegeta780** [comment]
Oh Yes Now it's working (just for once and only when i press Analog button i dont know how many time i press button and check everybutton I do some exit and restart Nintendont ) any suggestion am testing more and more but now it's not working I have PS2 Controller (What purpose is analog Button ???)

**Comment by carnage702** [comment]
analog button? you mean the analog sticks? or analog triggers?

**Comment by Vegeta780** [comment]
analog triggers?

**Comment by Vegeta780** [comment]
am working on trigger analog it's working but how times i press button sometime fast press button some time slow

**Comment by carnage702** [comment]
ps3 controllers have analo tiggers they are pressure sensitive and dont have just one value, it depends how deep you push the triggers.

**Comment by Vegeta780** [comment]
so many times i press the button (Mode / analog Light Red on/off) it turn light Red On and off

**Comment by carnage702** [comment]
that is normal, on ps2  controllers if analog button isnt on red you cant use the sticks only the dpad.

**Comment by Vegeta780** [comment]
Yes I know that But my case is different I press analog button  2 Times and then Press X Button Again
analog button  2 Times and then Press X Button Again analog button  2 Times and then Press X Button
analog button  2 Times and then Press X Button And Than It's Working all my Buttons I tested three times and it's worked ( really it's annoying ) Now Power=5,10
It's not going back to menu when i playing pokemon game

**Comment by Vegeta780** [comment]
what a pain in neck Now program is automatic cursor down ha ha ha ha ( i guess it's problem with my controller or Nintendont because In PC Controller is Perfect running )

**Comment by carnage702** [comment]
why dont you just press analog once and leavue it on? pressing twice just turns it on and off again.

no idea i only got a ps3,ps4,gc adapter that are hid and they all work fine.

**Comment by Vegeta780** [comment]
I giveup But Games is running in fullspeed thats makes me so happy ( oneday maybe i buy a PS3 or Ps4 Controller for GC games)  am going to play zelda BOT am waiting for Pokemon Ultra Sun /Moon and of Dragon Quest XI

**Comment by carnage702** [comment]
if you have a wiimote just buy a CC and your good to go, also every game runs fullspeed becuase nintendont is not an emulator at all.

**Comment by Vegeta780** [comment]
I have Motion Plus Remote Controller And Nunchuck  Sorry i dont know what is a CC ??

**Comment by pawhtiobo** [comment]
CC - Classic Controler ;)

**Comment by carnage702** [comment]
yeah classic controller or classic controller pro, or if you want the best controller ever for gc games you buy a wiiu gc adapter and a actual gc controller.

**Comment by Vegeta780** [comment]
wiiu gc adapter and a actual gc controller wow thats reminds me when i bought a PS2 Controller for (Nidendont) i thought , now i can play GC games But NO i need a Adapter to work Then i bought a adapter now I have issue with adapter and analog Mode Ha ha ha ha amazing ( i want to buy Nintendo Switch so badly and am saving money) if my controller worked  with Nidendont or wiiremote (no chance) maybe i just wait for while

**Comment by Vegeta780** [comment]
One more thing if my controller  is working with PC and no problem with HID Test & New Text Document.au3 software then i say my controller is not supported with nintendont Thats what i think

**Comment by carnage702** [comment]
your controller probably does something wierd that nintendont doesnt like or your controller ini was badly created or something, no idea what to tell you about your controllers, wiiu gc adapter is official adapter supported by nintendont since day one, no one ever had issues with it.

**Comment by Vegeta780** [comment]
Yeah  you are right i need another controller  thanks for all your help

**Comment by Vegeta780** [comment]
well now i have PS3 original Controller and working perfect am playing DBZ Sagas 
(PS2 is not a good controller gave me so much trouble )
