### ISSUE TITLE
usb fat device could not be opened ver 4.438

### ISSUE THREAD

**Issue by skullao** [FIX94/Nintendont#452]
So I followed every guide I could find and still only get this message for my USB drive. I did format it to FAT32 and 32k cluster and did set partition to active, did the same procedure with 64k clusters and still no luck.
Can't test with older versions cause I saw none lurking around.
Cheers!

**Comment by carnage702** [comment]
if its a flashdrive its very easy for it not to work since flashdrives are a hit and miss if its an hdd it depends on manny factores like wii or wiiu, mbr partition no hidden partitions or stuff like power saving mode among manny others.
