### ISSUE TITLE
054C_0268 Controller.ini not working

### ISSUE THREAD

**Issue by mysticvfx** [FIX94/Nintendont#453]
The buttons work in HID Test but once i play a game in nintendont nothing works

**Comment by carnage702** [comment]
make sure you dont have  native set to on and you dont have any gc controller or any other hid controller pluged in.

**Comment by mysticvfx** [comment]
Native was off the whole time and this is the only hid controller i have.

**Comment by carnage702** [comment]
if it works on nintendont menu it works ingame unless you have some other device like a gc controller plugged in port 1 or some setting like native on. if it doesnt even work on nintendont menu then it wont work.

**Comment by carnage702** [comment]
also are you renaming the ini to controller.ini and placing it on the root of your usb and sd?

**Comment by MetalMario** [comment]
@carnage702 This is similar to my issue I was talking to you about on gbatemp, my controller.ini doesn't work. My official gamecube controller does not work in the nintendont menu but does work once a GC game has loaded up, main issue been that the X an Y axes of the C-stick are swapped - X axes is Y axes...my coding skills are not yet good enough to edit the loader to swap Y axes of C-stick with X axes of C-stick so some help pointing me in the right direction would be highly appreciated. thanks
