### ISSUE TITLE
It crashes with GC HDD in back and WiiU HDD in front

### ISSUE THREAD

**Issue by 18Phoenix** [FIX94/Nintendont#454]
Hi everyone,
a big issue in my opinion is that Nintendont doesn't seem to work with a WiiU HDD connected.
My 2 partitions USB HDD for GC and Wii games works only on the back,
so I pluged my WiiU USB to the front where it works fine.
But Nintendont doesn't work anymore with a second HDD in the front.
That makes it very uncomfortable to unplug the front everytime and with time it kills the ports.

PLEEEEASE, even if it's a hard way, give it a try to solve that.

**Comment by carnage702** [comment]
nintendont does not support multiple drives connected you need to unplug one drive, if your not fine with it your open to make your own program.

**Comment by 18Phoenix** [comment]
It mustn't detect multiple drives but it must ignore the front or read out the back only.
I thought so bigger the problem is so more the programmer likes the challenge.
And it's not a small issue it's very big one. In the closed issues I see that I wasn't the first. Sure it has nothing to does with the functionality because it runs fine for me without front connection.
So it's sad that the most people never use Nintendont because before playing older games they have CW for WiiU titles they Play from USB. So the first experience will be a crash for the most part and the fewest will have the idea that they have to unplug their WiiU HDD.
So the programmer makes not half as many people as he could.

**Comment by GerbilSoft** [comment]
I have an idea for fixing this, but I need to get around to testing it.

**Comment by 18Phoenix** [comment]
Hi :) Your Avatar Looks like Rick Astley. I love "Never gonna give you up"
And so I say:  Never gonna give it up  ;D

**Comment by 18Phoenix** [comment]
Yeah, you did it with v5.460, works great.
Big thanks  👍
