### ISSUE TITLE
Sonic Mega Collection Freezing and Weird Sound Effect.

### ISSUE THREAD

**Issue by RedMountain95** [FIX94/Nintendont#456]
Alright I'm using 
Nintindont Loader v4.446
Built: Jun 28 2017
All settings default
Now whenever I play Sonic 3 and Knuckles on Nintendont the game keeps making a weird but loud graphical background noise that's sounds like something is tearing up. This happened back in January and AGAIN when I replayed the game today. 

For a while I thought it was the Forced Widescreen so I disabled it but it STILL makes that noise and either freezes the game eventually whenever I long play or just makes it impossible for me to progress through the game.

Has anyone else had this issue?

**Comment by carnage702** [comment]
tell all your settings since manny people say default and they arent default at all, also is your iso md5 checked?

**Comment by RedMountain95** [comment]
Well it's Nintendont Loader 4.446
Firmware 58.25.32

Cheats: Off
Debugger: Off
Debugger Wait: Off
Memcard Emulation: On
Cheat Path: Off
Force Widescreen: Off
Force Progressive: Off
Auto Boot: Off
Unlock Read Speed: Off
OSReport: Off
Wii U Widescreen: Off
Log: Off
MaxPads: 4
Language: Auto
Video: Auto
Video Width: Auto
Screen Position Auto
Patch PAL50: Off
TRI Arcade Mode: Off
Wiimote CC Rumble: Off
Skip IPL: No
Memcard Blocks: 251
Memcard Multi: Off

I'm THINK it is the iso which is causing the issue. I have not run md5 on it nor do I know how to. Athough the file size does say 1.4 GB which I guess is a round up of 1.35.

**Comment by carnage702** [comment]
1.35gb is a full iso still a full iso might not be ms5 checked either, there are alot of bad dumps just run md5 chker on it, i recall a timing issue on some random sonic game, dont remenber if it was mega collection or not , you can pause the game and come back to it to sync the audio and the game but you say it makes a very loud noise wich is wierd, try to run a md5 check on your iso and tell us what you got.

also are you running nintendont on sd or usb?

**Comment by RedMountain95** [comment]
I am running this game via SD. 
Anyway the sound that I'm hearing is more of a static background noise that just keeps getting louder the more I play the special stages or transverse a level. It mainly happens in S3K and just Sonic 3 alone. It's got to the point where once I get to Hydrocity Zone Act 2 the camera will just stop following Sonic and making it unable for me to continue.

I have now redownloaded the iso from a different website and the issue are STILL the same.
MD5 tells me that it is 85A525DF1481D0AD67D8761F832D and 1,459,978,240 in file size.

**Comment by carnage702** [comment]
what speed class is your sd card btw?

**Comment by RedMountain95** [comment]
I believe it is 10. I've always used it to play other GCN games and it works fine with those. Plus, I can even do those in Widescreen.

**Comment by carnage702** [comment]
try updating to 451 and try again also pal or usa iso?

**Comment by RedMountain95** [comment]
Sigh...both were USA isos and the update itself didn't prove anything.

Do you have a Wii U and if so could you try downloading the Mega Collection to see if you have the same issues? Because if you are then somebody needs to update the compatibility list.

**Comment by GB-CG** [comment]
@RedMountain95 I use 4.451 and I didn't get the freezing but only experienced 4 second crackles on Sonic 1 and the Sonic 2 minigame not too often on my Wii. Other games are working correctly, It's just the way Nintendont handles Mega Drive emulation. Also, why not just use GenesisPlusGX for S3&K?

**Comment by RedMountain95** [comment]
Well the issue usually arrives whenever I go into too many special stages at once. Like if I go into five in one playthrough then I gotta close out the game so that it won't freeze me or stop my progression.
As for not using the emulator on the homebrew it's mainly because that does not allow the use of a PS4 controller which is what I am using for Nintendont.

**Comment by GB-CG** [comment]
Hmm..You could try a controller adapter at http://www.raphnet-tech.com/products/genesis_to_wii/index.php They're good quality.

**Comment by FIX94** [comment]
while there was indeed a problem with audio (which I fixed by the way) I never heard anyone else say something about it crashing and I also didnt experience any crashes myself, also the game is emulated from the final ROM so if you get a crash it may just be a crash within the actual genesis game.
