### ISSUE TITLE
Main menu bug ? 

### ISSUE THREAD

**Issue by AlexFx7** [FIX94/Nintendont#458]
Hi, I think this is the most crazy issue in nintendont. I cant use the main menu, at the last version 4.451 when app load my cg controller doesnt respond at all, the app load and choise de usb port and show me the list game but i cant do anything. I try use an old version but is more crazy I press A and menu put me at the options , I press UP-PAD and  back to main menu, and i cant load any game. This main menu is crazy D:

**Comment by carnage702** [comment]
are you using wii or wiiu?  also maybe you got a corrupted file somewhere try deleting ninconfig .bin.

if you are using the wiiu gc adapter make sure you dont ahve any other hid controller connected.

**Comment by AlexFx7** [comment]
i using an old wii, (have gc port). I try dekete ninconfig.bin and nothing, nintendont is crazy yet. Am going to format my usb , maybe  somewhere is the corrup file.

**Comment by AlexFx7** [comment]
Ok, i dont know whats happening here D:, new ubs (format) and Nintendont s menu doesn work , now autoboot SD devise.

**Comment by carnage702** [comment]
just delete all nintentendont files, ninconfig.bin,boot.dol,meta xml,controller.inis if you have them and redownload nintendont and the meta.

**Comment by AlexFx7** [comment]
ok , i did it but nothing, can you send me a link ( i dont know how to download from this page). I downloaded from scenebeta.

**Comment by AlexFx7** [comment]
My good! nothing works, i just downloaded the file from here and nothing D:, i use an old wii (have gc port) , i use gc controller i dont have wii mote to try it. And main menu still crazy doing anything wrong. Maybe format the wii ?
