### ISSUE TITLE
Main menu bug. Cant load any game

### ISSUE THREAD

**Issue by AlexFx7** [FIX94/Nintendont#459]
Hi, I think this is the most crazy issue in nintendont. I cant use the main menu, at the last version 4.451 when app load my cg controller doesnt respond at all, the app load and choise de usb port and show me the list game but i cant do anything. I try use an old version but is more crazy I press A and menu put me at the options , I press UP-PAD and back to main menu, and i cant load any game. This main menu is crazy D:

**Comment by carnage702** [comment]
try taking out the gc controller and put it back or use wiimote

**Comment by AlexFx7** [comment]
trust me i try unplug gc, use other gc , try dualshock, deleted all nintendont files , and nothing. I was play normal all this days, and one day plafff this happen

**Comment by FIX94** [comment]
I wonder if your actual console memory chip is dying and now started sending out wrong signals or something...

**Comment by AlexFx7** [comment]
Maybe its posible, but only this app works wrong, im going to try reset the console.

**Comment by xp4xbox** [comment]
@AlexFx7 Don't format it. Formatting it doesn't actually format it, it just removes channels, preferences, ect.

**Comment by AlexFx7** [comment]
Now am thinking this is a hardware fail. I can only use gc pad at main menu and alternate in to game list options , pad up showme options , pad again game list..

**Comment by carnage702** [comment]
try the new 456 version please.

**Comment by AlexFx7** [comment]
Thanks you for new update, but my nintendont still working wrong D: this is obviously an hardware fail. I try load a game by usb loader gx and blackscreen t.t. I can load others apps and wii games by usb but doesnt nintendnt

**Comment by carnage702** [comment]
you sure you dont have anything connected to your usb ports? just try to remove everything from usb ports and launch it from usb card with an iso on sd card.

**Comment by AlexFx7** [comment]
Nothing new , the same issue from SD and nothing connected to usb.

**Comment by carnage702** [comment]
your using a wii with gc ports and a gc controller right? is the gc controller official or fake/3rd party?

**Comment by AlexFx7** [comment]
Yep it is an official GC controller, and WII has gc ports.

**Comment by AlexFx7** [comment]
No i cant use native, and i unplug gc controller and menu still crazy.

**Comment by carnage702** [comment]
nothing i can say then lol try another wii :P

**Comment by AlexFx7** [comment]
Yeah bro, nintendont is the best app for play gc , but this is a hardware problem, that one day this wii dont want more nintendont xD
