### ISSUE TITLE
Freezeng on checking storage devices

### ISSUE THREAD

**Issue by prowler86** [FIX94/Nintendont#460]
Hello! It freezeng on checking storage devices. Only power off.
ios58, latest homebrew channel. sdhc card 32 gb, formatted with 32k.

**Comment by carnage702** [comment]
so you are using the sd card only no usb? if so check to see if your sd card is correctly formated to fat32

**Comment by prowler86** [comment]
Yes, I'm usingonly sd card. It contains also apps for HBC. My card is formatted to fat32 via Windows 7.
Tried SHDC 32 GB Kingmax and 64 GB SDXC QUMO

**Comment by carnage702** [comment]
maybe you have a bad ios 58? or you are using an older homebrew channel that is not based on ios58? also jsut delete nintendont boot.dol and redownload it sometimes it can be corrupted.

sdcard never fail if they are failling something is very off.

**Comment by prowler86** [comment]
![img_20170912_155922_hdr](https://user-images.githubusercontent.com/1527966/30327382-7d444d14-97d4-11e7-89ca-bfcf4982a76c.jpg)
![img_20170912_160124_hdr](https://user-images.githubusercontent.com/1527966/30327380-7d0ab324-97d4-11e7-81f7-86cdae3c5491.jpg)
![img_20170912_160159_hdr](https://user-images.githubusercontent.com/1527966/30327381-7d0ddb58-97d4-11e7-88a4-fe0d0db38ba1.jpg)

**Comment by carnage702** [comment]
just wondering how much time did you actualy waited on checking storage devices? it cant take like 20 seconds sometimes if you dont have a usb device plugged in.


on your entire wii you dont have anything connected to your usb ports correct?
also did you try a fresh install? deleting every nintendont file and redownloading it?

**Comment by prowler86** [comment]
I have been waiting about 20 minutes. Only SD card inserted to front. Both back USB slots are empty.
I have tried new install, new download from GitHub.

**Comment by carnage702** [comment]
do you have an usb device to try it on? since usb code is diferent frm SD, tbh the only way i can think its not working is becuase the sd card is locked or badly formated really.

**Comment by carnage702** [comment]
try the new beta and report back https://mega.nz/#!1wBHlaiY!LwcfRM1DCSXSlqghJcb4TsVBsuHZglbTIsPWJLRp48s

**Comment by prowler86** [comment]
Unfortunately it is still hang on "checking storage devices". May be my Wii NTSC-J is not compatible. I'm thinking now about just buy original gamecube

**Comment by carnage702** [comment]
just try th e new 456 dol maybe it fixe your issues too?

also make sure your sd card is not locked.

**Comment by prowler86** [comment]
Wow! Version 456 is working for me. No freeze, no hang. Now I want to try launch GameCube game.
p.s. I had also try to launch 455 again. Many times. Only once it launch and show me menu select. Dunno why...
Anyway give me few minutes to test 456. Thank you so much!

**Comment by prowler86** [comment]
It works! Metroid is loading well. Also it works with bots USB backside ports, Unlike USB Loader GX.
Thank you again! Problem is solved.
p.s. Anyway next week I will have GameCube =)

**Comment by carnage702** [comment]
thansk that it worked for you now, gc sucks becuase gc to have 480p you need a very very expensive cable, wich on wii or wiiu is very cheap :P
