### ISSUE TITLE
Initializing Nintendont freeze.

### ISSUE THREAD

**Issue by lajax01** [FIX94/Nintendont#461]
Hi all.
Im just update my Nintendont (WII U) via Nintendont, and not working anymore..
Nothing has changed, only the the version of the software.
Before update the version number was 4.4XX, from now on what not working is 5.453.
FW: 58.25.32 (same before update)
SD card and file three is also same. 
Any suggestions?

**Comment by Jacksoft** [comment]
Same for me, on Wii first version (the one with Pad and MC ports). FW 58.24.32. Previous version was 4.x
IOS58 (rev 5662) USB 2.0
I've also deleted app cfg's but stil freeze on that message.

**Comment by carnage702** [comment]
are you both using sd card for the isos?

**Comment by Jacksoft** [comment]
No, I have all on a USB PenDrive. SDCard contain just the app.
I have already detached the USB PenDrive but the problem persist.

**Comment by carnage702** [comment]
tryed redownloading nintendont ? maybe bad dol or something?

**Comment by Jacksoft** [comment]
Yes, right now. I've also deleted gcn_md5.txt, titles.txt, controller folder and redownloaded meta.xml. Still freeze :/

**Comment by carnage702** [comment]
give me all the details.

booting nintendont directly from hbc or using a loader?

isos on sd? or usb?

your homebrew channel version?

**Comment by carnage702** [comment]
got anythybg at all on usb ports like even hid controllers?

**Comment by ThatEnigma** [comment]
Got the exact same problem lol, found my wii yesterday, decide I wanna nintendont my wii after like 4 years and then I get this problem lol like the day it updated I did this. Don't know what to do?

**Comment by Jacksoft** [comment]
[SysCheck.txt](https://github.com/FIX94/Nintendont/files/1308642/SysCheck.txt)
Nintendont is placed on the SD, under apps\nintendont\. I run it via Homebrew Channel (installed in NAND, it shows version 1.1.2 - IOS58 v24.32). ISOs are on USB PenDrive (correctly recognized by all homebrews and older, 4.x, Nintendont). There's no other device attached on the console except for the USB PenDrive.
Attached a system report.

**Comment by ThatEnigma** [comment]
Same as Jacksoft, placed on SD apps\nintendont. Version 1.1.2. My games are located in games folder on my SD card, get 'Initializing nintendont...' unresponsive, have to restart console to get anything to work. Not sure what's going wrong but could use with some help. Thanks.

**Comment by FIX94** [comment]
please re-report with the latest version which print you get now.

**Comment by Jacksoft** [comment]
Update: I've installed/upgraded some IOS/cIOS with ModMii Installer (with SysCheck analisys) and now seems works.
Here attached new sysCheck.
[SysCheckNew.txt](https://github.com/FIX94/Nintendont/files/1308665/SysCheckNew.txt)

**Comment by carnage702** [comment]
so its some cios issue. im guessing some old cios is messing with new codding somewhere.

**Comment by Jacksoft** [comment]
My D2X are the same (v10 beta), Others has been updated/modded. Maybe ND was searching some missing patched IOS.

**Comment by ThatEnigma** [comment]
So what do I need to do?

**Comment by Jacksoft** [comment]
Try like I've done (I've found the guide/files in SetMiiUp program for PC, maybe download it and check the full guide!), this is for WII only (I don't know how Wii U works). I have 4.3E System Software.
I TAKE NO RESPONSABILITY!
- Download and run SysCheck app and make a system report. Copy from the SD on the PC.
- Download ModMii Installer, install it and run classic mode. Type "I Agree" and then "SU" (without quotes), drag&drop the sysCheck.cvs report into the ModMii window. It will generate some files in a folder "COPY_TO_SD". (You can delete Priiloader, is not recommended, and Simple IOS Patcher)
- Copy all generated files into the root of SD and power on the Wii. Go to Homebrew Channel and run first "IOS236 Installer" and then MultiMod Manager for install generated WADs.
I've installed all WADs excepting for the d2x v8, because I have v10 beta52.
- Retry if Nintendont works.

NOTE: I DON'T KNOW which softmod you have, this guide MAYBE not work and/or MAYBE brick your console. I TAKE NO RESPONSABILITIES!

**Comment by carnage702** [comment]
well its a cache issue acording to fix94 updating ios probably cleared cache for it to work, he is trying to fix it as we speak.

**Comment by Jacksoft** [comment]
That's great! Thank you! :D
Did you know if there's another, simplest, way to clear cache if something like this happen?

**Comment by ThatEnigma** [comment]
I used letterbomb do this didn't really work for me, might wait for a fix, where will it be released?

**Comment by xp4xbox** [comment]
Im pretty sure nintendont only requires cios249.

**Comment by FIX94** [comment]
nintendont requires no cios, it only uses ios58, everything you get is a placebo effect, cache is random, just open and close stuff or move files on the sd and it may magically work.

**Comment by deathbrother527** [comment]
This also happened to me still no way to fix it I'm on the wii u version

**Comment by xp4xbox** [comment]
@FIX94 huh, im surprised it can load off a hard drive with a system ios.

**Comment by FIX94** [comment]
I pushed yet another version up, I hope it helped.

**Comment by carnage702** [comment]
try the new beta and report back https://mega.nz/#!1wBHlaiY!LwcfRM1DCSXSlqghJcb4TsVBsuHZglbTIsPWJLRp48s

**Comment by lajax01** [comment]
Not good, at we discuss on the other topic. ;)

**Comment by ThatEnigma** [comment]
@FIX94 Where do I find this new version?

**Comment by ThatEnigma** [comment]
@lajax01 Get's stuck on loading nintendont Kernel..

**Comment by carnage702** [comment]
fix made a new dol try it out and see if it hangs on what part

https://mega.nz/#!BwxEAYTD!xx5-nsvX46Riaxgwx53aXnwoH9tt6je-jfpF_t3Ieto

**Comment by carnage702** [comment]
https://github.com/FIX94/Nintendont/blob/02446e53b9e0dde5468f64a3005c7a695eaee0e3/loader/loader.dol?raw=true

try the new dol and report back if it still freezes

**Comment by monta990** [comment]
the new version .456 works perfect
