### ISSUE TITLE
Initializing Nintendont then stops. Wii U ver.

### ISSUE THREAD

**Issue by deathbrother527** [FIX94/Nintendont#462]
All I want to do is play paper mario randomizer but it freezes. I have the latest nintendont and homebrew

**Comment by monta990** [comment]
its happen to me, from ver 452, i do a rollback to ver 451

**Comment by carnage702** [comment]
try the new beta and report back https://mega.nz/#!1wBHlaiY!LwcfRM1DCSXSlqghJcb4TsVBsuHZglbTIsPWJLRp48s

**Comment by Kitasan0529** [comment]
I tried it but loading Nitendont Kernel is too long or stuck in there

**Comment by Kitasan0529** [comment]
Sorry for bad language

**Comment by ThatEnigma** [comment]
@carnage702 stuck on loading nintendont kernel

**Comment by carnage702** [comment]
that was what fix94 was expecting, when he wakes up he knows what to mess with to fix it, so until then i hope you guys can wait.

**Comment by oldmastershifu** [comment]
same problem( On the screen - Initializing Nintendont.... and console freezes. 
I replaced the file (boot.dol) with the above. Did not help. On the screen - 
Loading Nitendont Kernel.... and console freezes....again

**Comment by ThatEnigma** [comment]
@carnage702 Okay that sounds fine, I'll just wait until then, super annoying that the one day I decide to take my wii out after 4 years and use it that nintendont has a problem XD

**Comment by carnage702** [comment]
you can use the last working one
while the latest one isnt fixed

https://github.com/FIX94/Nintendont/blob/a960793ce4b61fbe90fc92b8acf9271d2689f99f/loader/loader.dol?raw=true

**Comment by carnage702** [comment]
fix made a new dol try it out and see if it hangs on what part

https://mega.nz/#!BwxEAYTD!xx5-nsvX46Riaxgwx53aXnwoH9tt6je-jfpF_t3Ieto

**Comment by echrono** [comment]
I've been having the same issue, just tried the new dol and it's still stuck on "Loading Nintendont Kernel..."

**Comment by carnage702** [comment]
tryed the new exact dol i posted here right before your coment?

**Comment by echrono** [comment]
Yessir

**Comment by oldmastershifu** [comment]
carnage702, after installing a new fix, it hangs on - Loading Nintendont Kernel...

**Comment by carnage702** [comment]
please try the new dol and report back 

https://github.com/FIX94/Nintendont/blob/02446e53b9e0dde5468f64a3005c7a695eaee0e3/loader/loader.dol?raw=true

**Comment by monta990** [comment]
the new version .456 works perfect

**Comment by oldmastershifu** [comment]
carnage702, 
Thank you! everything worked
