### ISSUE TITLE
Nintendont doesn't support gamecube adapter

### ISSUE THREAD

**Issue by gillie97** [FIX94/Nintendont#463]
Hello. My nintendont (tunning on vWii on Wii u) doesn't seem to support my gamecube adapter. I'm running the latest version of nintendont (5.455) firmware 58.25.32 and version 1.12 of homebrw channel. Both are booting from SD and i also tried it from the cfg loader (version 70r78.4) but still won't work. Someone help please!!

**Comment by carnage702** [comment]
are you using an official wiiu gc adapter?

**Comment by gillie97** [comment]
Yes. And i'm using the front usb ports from the wii u for it

**Comment by carnage702** [comment]
you putte dthe gc controller on port 1? since if you put it on port 4,3,2 some games will not let you control them.

**Comment by gillie97** [comment]
Yeah i also tried to put it in the other ports but no response. I also unplugged the adapter and plugged it in again but it still won't work

**Comment by carnage702** [comment]
just use an older version, it seems the rewrite is having some hid issues

last working one is this
https://github.com/FIX94/Nintendont/blob/a960793ce4b61fbe90fc92b8acf9271d2689f99f/loader/loader.dol?raw=true

**Comment by gillie97** [comment]
That did it for me. Thanks😁. One more thing, i'm playing pokemon colosseum on nintendont but it keeps crashing in a battle with a cipher peon in agate village (skrub if i'm not mistaken). I keep hearing the beeeeeeeeep sound. This happens on every version of the nintendont so far. Does anyone know what may cause this problem and how to solve it?

**Comment by carnage702** [comment]
i never had that crash you sure you got a md5 checked iso and didnt have it compressed or something?or have chetas?

**Comment by carnage702** [comment]
take a picture of your nintendont settings and check your iso md5 to make sure you have a good iso.

**Comment by gillie97** [comment]
Ehmm not sure if it's a md5 checked iso. How can i check that? It is not a compressed file and i also don't use cheats for it.

**Comment by carnage702** [comment]
take a picture of your nintendont settings please and then use this tool http://www.mediafire.com/file/5y3tfpoil433rij/MD5_SHA-1+Utility.exe open your colosseum disc and then paste the md5 here, i t migh take afew seconds to display md5.

**Comment by gillie97** [comment]
![img_2619](https://user-images.githubusercontent.com/15649437/30531606-af34372e-9c4f-11e7-985d-23f8a4951a04.JPG)

It seems the md5 hash is matching.

**Comment by carnage702** [comment]
you got force widescreen to on wich breaks manny games at some points turn that off and you should be good. turn on  force wiiu widescreen isntead.

**Comment by gillie97** [comment]
I changed the options like you said in your previous comment but it still freezes. I was also playing super smash bros melee in nintendont with wiiu widescreen on and force widescreen on but it didn't completely fill the screen. That problem seems to be fixed with the options you told me to use so thanks for that one :)

**Comment by carnage702** [comment]
also colosseum ntsc or pal?

**Comment by carnage702** [comment]
just upload your save somewhere like mediafire or something an then tell me exactly where to go to do the freeze.

**Comment by gillie97** [comment]
How can i dump my colosseum save file? Is that possible in the cfg loader? Also how can i check if it's ntsc or pal?

**Comment by carnage702** [comment]
you got the save file on your usb or sd card lol you are using mcemu so go to your sd card or usb and see the saves folder. then if its ntsc its called  GC6E if you are using pal GC6P

**Comment by gillie97** [comment]
ow hahah my bad. I'm still a newbie in this. It's called GC6E so i suggest it's ntsc.

https://www.mediafire.com/file/pmi984hi0a0gb9z/GC6E.raw

**Comment by carnage702** [comment]
so what about the instructions to get to said freeze fro your save file? lol

**Comment by gillie97** [comment]
I just tried it again and got a frozen screen again. To be more specific of the part where the screen freezes, I think it's when he calls his last pokemon. I've only seen geodude, wynaut and shadow hitmontop. When i beated his geodude he came with hitmontop. Right after that i beated his wynaut and he was about to throw in his last pokemon and that was where the screen froze.

**Comment by carnage702** [comment]
so i tryed it and it ws fine for me lol i killed it by acident secret power poisoned hitmontop and he died lol,  you sure you have a good iso?

I used everything off or auto except  mcemu to on and wiiuwidescreen.

want me to catch it ans save it? i mean it doesnt crash at all here.

**Comment by carnage702** [comment]
also im starting nintendont directly from homebrew channel isntead of being through a loader try that?

**Comment by gillie97** [comment]
If you want to do that for me i would appreciate that. I also downloaded a new iso so maybe that one doesn't crashes

**Comment by carnage702** [comment]
got mine from  a room hustler type of website just google those 2 words :P

**Comment by gillie97** [comment]
romhustler huh? I just downloaded my iso from that website

**Comment by carnage702** [comment]
we cant say rom websites xD just edit that :P also got your save fif it still freezes i will upload once you confirm it or not.

**Comment by gillie97** [comment]
Sorry my bad again xD I tried the other iso and it seems you were right, i think my iso was corrupted or something. I just caught that pesky hitmontop without crashing :P thanks a lot. not only did you solve my wiiu adapter for gc controllers which i almost forgot xD but also the display for many gc games playing from nintendont and now this problem. I owe you not one but three xD

**Comment by carnage702** [comment]
no problem, i love to help especialy with pokemon :P
