### ISSUE TITLE
Won't launch games on Multi-game burned disc

### ISSUE THREAD

**Issue by Bisonfan95** [FIX94/Nintendont#464]
Whenever I put a DVD on the Wii with various disc images, it shows them on a list but they are in red color and won't let me launch any of them.

**Comment by xp4xbox** [comment]
You need a patched mios for that, Nintendont won't launch burnt games.

**Comment by Bisonfan95** [comment]
Yes it can. I have a wii with a chip, not flashed and I can play Burnt gamecube games from the original internal DVD reader (not external at all). I can play individual burnt games but not games  that are clustered inside one disc (another app can do this, the problem is that it doesn't have the wonderful options of patching pal and forcing NTSC)

**Comment by xp4xbox** [comment]
With wanikokos mios patcher I can load multi-iso GameCube disc from the disc channel.

**Comment by Bisonfan95** [comment]
mmh ok, but i think it doesnt have the force options :(

**Comment by GerbilSoft** [comment]
There's known issues with multi-game discs. I'm not sure of the exact root cause of it, though.

I fixed some problems regarding the 4GB barrier a while back, but it's still problematic when using DVD-Rs. Multi-game ISOs on USB/SD did work last time I checked, though.
