### ISSUE TITLE
[Wii U VC injection issue] Whenever I press the power button while in game, it says press again to turn of console, i do that, and the console does not turn off!

### ISSUE THREAD

**Issue by thebeastgamer25** [FIX94/Nintendont#465]
I am running the latest loader from this github.

**Comment by carnage702** [comment]
when i press the wiiu power button my console reboots into wiiu mode what button are you pressing?

**Comment by carnage702** [comment]
i never even saw that press another time screen ever.

**Comment by thebeastgamer25** [comment]
when I press and hold the button on the gamepad, I'll take a picture if you want 


Sent from my Sprint Phone.
-------- Original message --------From: pedro702 <notifications@github.com> Date: 9/18/17  5:10 PM  (GMT-05:00) To: FIX94/Nintendont <Nintendont@noreply.github.com> Cc: Beast <rimorycz@icloud.com>, Author <author@noreply.github.com> Subject: Re: [FIX94/Nintendont] [Wii U VC injection issue] Whenever I press the
  power button while in game, it says press again to turn of console, i do that,
  and the console does not turn off! (#465) 
when i press the wiiu power button my console reboots into wiiu mode what button are you pressing?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FIX94/Nintendont","title":"FIX94/Nintendont","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FIX94/Nintendont"}},"updates":{"snippets":[{"icon":"PERSON","message":"@carnage702 in #465: when i press the wiiu power button my console reboots into wiiu mode what button are you pressing?"}],"action":{"name":"View Issue","url":"https://github.com/FIX94/Nintendont/issues/465#issuecomment-330357357"}}}

**Comment by carnage702** [comment]
well dont hold the power button either click home on gamepad or any wii controller or simply press the buton so nintendont can reboot your console in wiiu mode and then you can shut it down?

**Comment by carnage702** [comment]
Try the new 464 version  it fixes the shutdown you wanted.

**Comment by thebeastgamer25** [comment]
of nintendont?


Sent from my Sprint Phone.
-------- Original message --------From: pedro702 <notifications@github.com> Date: 9/24/17  6:01 PM  (GMT-05:00) To: FIX94/Nintendont <Nintendont@noreply.github.com> Cc: Beast <rimorycz@icloud.com>, Author <author@noreply.github.com> Subject: Re: [FIX94/Nintendont] [Wii U VC injection issue] Whenever I press the
  power button while in game, it says press again to turn of console, i do that,
  and the console does not turn off! (#465) 
Try the new 464 version  it fixes the shutdown you wanted.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FIX94/Nintendont","title":"FIX94/Nintendont","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FIX94/Nintendont"}},"updates":{"snippets":[{"icon":"PERSON","message":"@carnage702 in #465: Try the new 464 version  it fixes the shutdown you wanted."}],"action":{"name":"View Issue","url":"https://github.com/FIX94/Nintendont/issues/465#issuecomment-331743251"}}}
