### ISSUE TITLE
Initialising Nintendont on the newest version.

### ISSUE THREAD

**Issue by chamipon** [FIX94/Nintendont#466]
Whenever I try to use the newest version of Nintendont it never fully launches, but gets stuck on the screen that says 'Initialising Nintendont'. However if I use an older version of Nintendont the software launches fine and allows me to load my gamecube iso's. 

Any help would be much appreciated

**Comment by carnage702** [comment]
what do you consider latest? what does it say on top? say the actual number.

**Comment by ctwentytwo** [comment]
Same issue here...

It's....
Nintendont  Loader v5.455 (Wii)
Built: Sep 17 2017 02:41:50
Firmware: 0.13.37

It hangs on Initializing Nintendont...
Wii is running usb flash drive off of outermost (nearest bottom edge) USB port.

**Comment by FIX94** [comment]
we are up to 5.457 by now people, please update before making error reports.

**Comment by chamipon** [comment]
v4.451 is the version that works for me, v5.457 is the version that gets stuck on launch.

**Comment by carnage702** [comment]
you sure your not running 455? becuase on 456+ everyone that had nintndont stuck on initializing or kernel loading got it fixed, take a picture of your freeze.
