### ISSUE TITLE
its more a request than a isue

### ISSUE THREAD

**Issue by saitoh00** [FIX94/Nintendont#469]
Any way to code in Nintendont for select a gamecube backup inside usb hdd formated in wiiu format?

**Comment by carnage702** [comment]
if you make a wiivc inject and put a gameiso inside it you can launch it from there.

**Comment by saitoh00** [comment]
Imagine that i have 1000 isos, i can inyect one to one,  is the reason for this request

**Comment by saitoh00** [comment]
If Nintendont can read for the usb wiiu storage, the only step is copy to usb hdd from ftp

**Comment by carnage702** [comment]
there is no way for nintendont or any vwii app to read a wiiu formated drive, heck how could you even put game.isos inside it? no one cracked the file system so you cant even had game isos to it anyway...

**Comment by carnage702** [comment]
nintendont only reads it if its a wiivc inject becuase its inside its own launch iso, nintendont cant search for stuff on the drive becuase its filesystem is uncharted  heck not even wiiu apps like retroarch or any other app can read stuff from wiiu foramted drive let alone vwii apps, if you want you can go and decrypt the entire filesystem and let us know exactly what we need to do to search it.

**Comment by saitoh00** [comment]
If you want see the filesystem only use ftp Pedro ;)

**Comment by carnage702** [comment]
that doesnt help at all, when you find even a wiiu app that can actualy rea and search a wiiu formated drive let us know untl then your out of luck.
