### ISSUE TITLE
DSI Error Problems with Update 462

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#470]
Hello my friend Fix94

I went to update the nintendont now a little bit, it was in the 460 version and I was updating to the 462, I always update directly through the wii-fi of the Nintendo Wii, I tried twice and in the middle of the download occurs the default DSI wii error, I believe that is some problem in the server, because the error occurred twice in the same part. A hug and success always my friend.

**Comment by FIX94** [comment]
git somehow didnt push the loader executable itself on my last commit, just re-pushed it, no clue how this happend.
