### ISSUE TITLE
Problem with NTSC Roms

### ISSUE THREAD

**Issue by SuruUno** [FIX94/Nintendont#472]
I downloaded the new version, but now I can´t play my NTSC roms anymore, because the screen is almost completely black. I can merely see the outlines of what is supposed to be on the screen. I´m playing on PAL-System and PAL Roms work fine. Checked of the PAL patch box , but didn´t do anything...

**Comment by carnage702** [comment]
what number of the version? say the actual number, also what cable do you have to connect your wii or wiiu to tv?

**Comment by SuruUno** [comment]
The number is v5.462. My Wii is connected with the TV through a regular SCART cable. Maybe those new colors (1:1 Shrunk FST CISO Multi) aren´t working with my setup?

**Comment by carnage702** [comment]
those colors have nothing to do with anything just checking the isos size and such, also take a picture of your nintendont settings, and your tv does support ntsc signal? i mean you ever played an ntsc game without forcing videomodes?

**Comment by SuruUno** [comment]
![img_20170923_163332](https://user-images.githubusercontent.com/32208476/30774086-8f72b762-a07d-11e7-8eb8-11fd93ab18c6.jpg)
![img_20170923_163548](https://user-images.githubusercontent.com/32208476/30774089-9873b848-a07d-11e7-9599-9a88dc756bf8.jpg)
The second pic shows the black screen with some greenish shades, which occur when I boot an NTSC rom. I could play those without problems on older versions (PAL patch was probably activated)

**Comment by carnage702** [comment]
just go into video and put force pal 60 and see how it goes if you can.

**Comment by FIX94** [comment]
the wii video chip switches between S-Video and RGB modes depending on the game video mode, so starting a NTSC title will give you S-Video and starting a PAL one gives you RGB, you can easily force it to the other type though, just scroll down to Video, set it to Force and as mode select PAL60, basically PAL60 is equal to NTSC but will give you RGB as output as you want.

**Comment by SuruUno** [comment]
Thanks, it really was that easy. Sorry for bothering you guys. Keep up the great work!
