### ISSUE TITLE
[Wii U VC Inject] IOS58 load error

### ISSUE THREAD

**Issue by Noahkiq** [FIX94/Nintendont#473]
When trying to load Nintendont from a Wii U VC inject (which used to work), the program posts an error and returns to the Wii U menu.

```
Failed to load IOS58 from NAND:
IOS_Open("/shared1/content.map") returned -102.

This usually means Nintendont was not started with AHB access permissions.

Please ensure that meta.xml is present in your Nintendont application directory and that it contains a line with the tag <ahb_access/>
```
And yes, `<ahb_access/>` is in the `meta.xml` file in the same folder as the `loader.dol`

**Comment by carnage702** [comment]
take a picture of your screen.

**Comment by Noahkiq** [comment]
Didn't think it would be necessary as the image was blurry and I typed out the text but [here ya go.](https://cdn.discordapp.com/attachments/246729272549441536/361370332570845184/IMG_20170922_182728.jpg)

**Comment by carnage702** [comment]
you are using 4.448 wich is extremely outdated lol thats is why i wanted the picture, that version doesnt even have wii vc injection support or even gamepad codding ...

just download latest nintendont dol 463

**Comment by Noahkiq** [comment]
Isn't [this the file](https://github.com/FIX94/Nintendont/blob/master/loader/loader.dol) I'm supposed to be using? Because that's the one I've been downloading...

**Comment by carnage702** [comment]
yes but that file is updated everytime a rev is released and your version like you see is outdated has hell just redownload the loader dol from that link and you will see version 464 instead of 448.

**Comment by Noahkiq** [comment]
Ah, alright. Latest version does work, thanks for the help 👍
