### ISSUE TITLE
Black screen after Wii logo

### ISSUE THREAD

**Issue by bugahy** [FIX94/Nintendont#477]
I am using the nintendont forwarder on Wii U, when i run the app it loads the nintendont logo, enters wii mode and then black screen, i have to unplug the console everytime this happens, sometimes I get lucky and nintendont loads fine, but 8 times out of 10 wont load past the wii logo.

**Comment by FIX94** [comment]
see issue #487 right now there seems to be no consistent explanation for what exactly is going on.
