### ISSUE TITLE
[Request] Optionally triggering GCN bios

### ISSUE THREAD

**Issue by cucholix** [FIX94/Nintendont#478]
_This request is more focused to autoboot Wii VC injections_

Optionally triggering the GCN bios menu by holding the (*)"Y" button before the game start. 
The option would added under ipl settings:
ipl = on/off/**dynamic** 
- on = show the GCN intro from the iplxxx.bin file
- off = doesn't show the GCN intro from the iplxxx.bin file
- dynamic = it will show the GCN intro only when the "Y" is button held.

_(*)It can be other button, except "A" (it open the bios menu during the GCN logo animation), "Z" (it load the alternative intro sound), or "B" (it show the progresive scan setting after the GCN bios).   Minus, plus, HOME, L3, R3 buttons are not available on GCN controller so it's better exclude them too._

**Comment by carnage702** [comment]
you either want it or you dont i see no benefit to optionally turn it on or off on a whim...
