### ISSUE TITLE
Nintendo Switch Pro Controller

### ISSUE THREAD

**Issue by Hibiki0506** [FIX94/Nintendont#480]
Sorry for my bad english!

I would to play with the Nintendo Switch Pro Controller on my vWii with Nintendont. Is it possible to connect the Switch Pro Controller with Nintendont? That would be great, because my WiiU GamePad is broken and i can't play games how for example Super Mario Sunshine or Mario Kart Double Dash.

**Comment by GB-CG** [comment]
Someone else asked this question on this [thread](https://gbatemp.net/threads/does-nintendont-support-the-switch-pro-controller.473678/).
