### ISSUE TITLE
Update timer patches for unlocked Wii U multiplier

### ISSUE THREAD

**Issue by GerbilSoft** [FIX94/Nintendont#481]
https://github.com/FIX94/c2w_patcher allows starting Wii mode with the CPU multiplier set to the Wii U value (1,215 MHz). The timer patches are currently hard-coded to 729 MHz, so they won't work correctly if the unlocked frequency is used.

For reference:
* GameCube: 485 MHz (1.0x)
* Wii: 729 MHz (1.5x)
* Wii U: 1,215 MHz (2.5x)

I'm not sure if the CPU frequency can be easily determined at runtime, so some method will need to be used to determine if the CPU is running in standard Wii mode, or in Wii mode with the unlocked frequency.

**Comment by FIX94** [comment]
I'm very unsure as of yet, it may be possible to read out the registers from IOS that are responsible for setting the PPC speed in the first place, did not test that theory yet.

**Comment by FIX94** [comment]
well I was able to come up with a quite simple solution to this in the end, its now supported.
