### ISSUE TITLE
Latest Build

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#482]
Hello friend Fix94

I have noticed that in the last build of nintendont, it has been kind of specific to the wii u, there came the question I have the normal wii, these last build has change effect on it? a hug and success always

**Comment by FIX94** [comment]
The current nintendont build runs fine on wii, vwii and wii vc, I tested all of that. For a normal wii, the last few versions did not bring a whole lot of changes, just that you can now power off the console in the loader itself too.

**Comment by spielvan** [comment]
Thank you my dear for the answer. A big hug.

**Comment by GB-CG** [comment]
Visit the [Support thread at the GBAtemp forum](https://gbatemp.net/threads/nintendont.349258/) if you have any more questions.
