### ISSUE TITLE
sept 29th commit

### ISSUE THREAD

**Issue by rjwboys** [FIX94/Nintendont#484]
when i use the sept 29th commit with wiiu vc inject the game doesn't boot but it works with sept 24th

**Comment by rjwboys** [comment]
commit 2d83769 gives me an can't create memory card error then crashes to black screen, 6653c99 doesn't give any message and goes to black screen

**Comment by carnage702** [comment]
you sure your sd card isnt locked or full? im using latest  release and its creating memory cards just fine, just chked if the tab on your sd card didint went down.

**Comment by rjwboys** [comment]
double checking, have 32gb free on sd card, 
sd was locked so thats why it gave memory error
booting game with gamepad enabled, latest version 6653c99, sd card unlocked,  black screen, have to pull power to reboot wiiu
booting game with gamepad disabled latest version, 6653c99 sd card unlocked, , boots fine
so my testing shows gamepad causeing freeze up on latest for me

**Comment by carnage702** [comment]
not sure what to tell you it works for everyone else, maybe you got a bad download  or bad wup file when installed th e nintendont app. maybe delete your nintendont fowarder and reisntall it.
