### ISSUE TITLE
All 4 Wii Remote LEDs remain lit up when in game

### ISSUE THREAD

**Issue by sks316** [FIX94/Nintendont#486]
Basically, when I go into a game, all 4 of the player indication LEDs on my Wii Remote are constantly lit up and I can't use the remote or the Classic Controller to control the game. The GC Controller works fine.

**Comment by carnage702** [comment]
fake/3rd party wiimote or CC dont work ingame.

**Comment by sks316** [comment]
I found out what the issue was. The Classic Controller wasn't connected properly.

**Comment by Z0287yyy** [comment]
Hi, I meet the same issue as you.

**Comment by Z0287yyy** [comment]
How do you solve this issue, could you help me?

**Comment by carnage702** [comment]
you cannot use solo wiimote

you buy a Classic controller(official one) or classic controller pro or use the not very well recomended nunchuck + wiimote.

remenber most fake/3rd party wiimotes/Classic controllers dont work on nintendont when ingame also.

**Comment by Z0287yyy** [comment]
Thanks @carnage702 , maybe it's fake one, as I bought them from flea markets.

**Comment by sks316** [comment]
@Z0287yyy Ensure that your Classic Controller is plugged in correctly. Also, please make sure that native is disabled, like @carnage702 said.
If you bought it at a flea market, it's likely to be a fake. I'd recommend that you only buy them from trustworthy stores.
