### ISSUE TITLE
Buttons Not Working on Mario Kart Double Dash!! and F-Zero GX.

### ISSUE THREAD

**Issue by WiisleyU** [FIX94/Nintendont#488]
These games are not working properly, they load normally but on MKDD all the buttons do nothing, except the Home Button that quits from the game. On F-Zero GX is even more weird, some buttons works and some not, depending on the screen. On main menu no directions can be entered, you can only press the A button, when appears "Novice, Standard..." you can press up and down, and then A, on Grand Prix selection you can press left and right too, and so on. When Finally arrives to the race the acceleration button is disabled. Tried with the Nintendont Forwarder, shrunk and full-sized isos, same problem. Every another game tested working perfectly even the shrunk and the FST ones. It's not only for the GamePad, the Wii U Pro Controller and even GCN Controllers on the adapter have exactly the same problem. I've tried without and with the "controlers.zip" too.

**Comment by FIX94** [comment]
I greatly doubt you are on the very latest version, you probably are on one from weeks ago so always, always make sure to update before opening a issue and when opening an issue to include the used version because 99% of the time it'll be outdated and the bug was fixed a long time ago like this one.

**Comment by WiisleyU** [comment]
![nintendont fix](https://user-images.githubusercontent.com/20059831/31325821-be68b3fc-ac97-11e7-9ad3-d0cfde543be6.jpg)

The "Nintendont" (not the forwarder) has worked (downloaded from the USB Helper too).
Did you recommend me to stay on the Forwarder Version that can be updated from the SD or keep up with the full WiiVC version that will run every game perfectly well?

**Comment by FIX94** [comment]
for nintendont I would never recommend a full channel, always a better idea to be able to update it as it also was designed that way.

**Comment by WiisleyU** [comment]
The Channel here shows 5.466 version, is there an SD app with this version? Where can I download the newest updates, I picked the app on an YouTube link, it would not be up to date... By the way so many thanks! Your work is really wonderful and always you do so much for the community, congratulations!

**Comment by carnage702** [comment]
latest version is 468 you can always get the latest one from this link just reanme it to boot.dol
https://github.com/FIX94/Nintendont/blob/master/loader/loader.dol?raw=true

your controllers issue came from a bug on that old version so just update and you are good to go, and dont install nintendont as a full dol or else you will never be able to update it.
