### ISSUE TITLE
problem with 2 joy hid connected

### ISSUE THREAD

**Issue by juaco019** [FIX94/Nintendont#489]
hi  guys, nintendont presents a problem when two hid usb are connected. 2 ways both using a usb hub to connect the 2 joy. also the two usb ports with sd card to load the games. only one joy works taking it as player 1, the second does not work although this is correctly recognized by nintendont. regards

P.S. i try using the multi in command and nothing happens

**Comment by carnage702** [comment]
only one hid is allowed at a time, usb hubs are not officialy supported, and even if you connected both hid controllers only one woud work, the way hid  controllers are set up on codding only one is allowed at a time, this would require a rewrite of the controller code.
