### ISSUE TITLE
problems with Bios M PAL

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#490]
I got the bios ipl PAL-M Gamecube.bin, and I tested with this latest version of nintendont and could not make it work, it would have to be in some special game, I tried renaming it to bios usa, pal or japan and it does not load bios Have I been lost?

**Comment by FIX94** [comment]
call it "iplusa.bin" and set the video mode to force PAL-M and use regular NTSC games, it should then work as expected if it is the MPAL v1.1 IPL.

**Comment by spielvan** [comment]
I got my friend, it was perfect, under the language has Video put him in Force
and the bottom Videomode put it in MPAL, thank you very much.
