### ISSUE TITLE
Crash if games folder missing or empty

### ISSUE THREAD

**Issue by missionfloyd** [FIX94/Nintendont#494]
I'm using version 5.471 on a Wii U with a Wii U formatted HDD connected. I'm using WiiVC for GCN games, and trying to open Nintendont via vWii to access settings and updates (is there a better way to do that?)

If the games folder on the SD card is missing or empty, Nintendont crashes upon selecting SD or USB, regardless of whether the HDD is connected or not.

```
Exception (DSI) Occurred!
GPR00 8006AF90 GPR08 00000000 GPR16 66666600 GPR24 80170000
GPR01 8020A168 GPR09 00000000 GPR17 00000000 GPR25 80160DD0
GPR02 80173EE0 GPR10 000A01D0 GPR18 00000000 GPR26 0000CAFE
GPR03 00000000 GPR11 0000000E GPR19 8020F1C8 GPR27 8020A178
GPR04 8016DDCC GPR12 88202248 GPR20 80160CC0 GPR28 CD8005A0
GPR05 8016DDCC GPR13 80177380 GPR21 00000000 GPR29 80160CC4
GPR06 8016DDC4 GPR14 00000001 GPR22 00000000 GPR30 8016BFC4
GPR07 8020A178 GPR15 8020A178 GPR23 00000000 GPR31 00000000
LR 8006C0C8 SRR0 800ceedc SRR1 0000b032 MSR 00001000
DAR 00000000 DSISR 04000000

STACK DUMP:
800ceedc --> 8006c0c8 --> 8005dfec --> 800a6904 --> 800a68a8

CODE DUMP:
800ceedc: 81090000 3CE08080 60E78080 3D48FEFF
800ceeec: 394AFEFF 7D4A4078 7D483839 4082001C
800ceefc: 85090004 3D48FEFF 394AFEFF 7D4A4078
```

If the games folder is present with at least one game, both options work as expected.

The first time i tried to capture the code dump, it decided to work right, but I haven't gotten it to again.

WiiVC injections still work correctly.

**Comment by carnage702** [comment]
there is a much better method install a nintendont fowarder on wii vc one that isnt autobootable and put a single game on sd card a small one like aniaml crossing compressed(around 24mb or so), change the settings and then boot the game, after it boots just hit home button and you are back on home menu

**Comment by missionfloyd** [comment]
I do actually have animal crossing on my sd card to get around this, so that works. And changing settings isn't something I need to do often, if at all. so this isn't really a big deal.

Looking at the code, it looks like what's supposed to be happening in this situation, is returning an error, "WARNING: sd:/games/ was not found." and as I said, it do do that, once. For whatever reason, it usually just crashes here instead.

**Comment by FIX94** [comment]
confirmed and fixed.
