### ISSUE TITLE
Possibility of frame interpolation (enhancement)

### ISSUE THREAD

**Issue by SevenWillis** [FIX94/Nintendont#496]
Is there a possibility that a patch can be implemented just like the widescreen patch to make non-60fps games run at 60fps, or will it be too much for the CPU to handle?
I know it's a thing on dolphin, but I'd like to see this happen on Nintendont.

**Comment by GB-CG** [comment]
If you're thinking of Mario Sunshine, it originally ran 60fps in its alpha build, but then they changed it to 30fps for some reason, but the code is still there to 'unlock' it.

**Comment by carnage702** [comment]
doesnt work like that each games has specific funtions for their framerate there isnt a function at all for that, while widescreen you just look for the image ratio function.

**Comment by SevenWillis** [comment]
That's exactly why I closed the issue after reading about it
