### ISSUE TITLE
Tales of Symphonia (PAL - Spain) bug

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#497]
Testing this game I found that a weird "bip" sound appear when a battle is starting and when it finishes... that weird "bip" doesn't sound in the original game through the disc channel... I don't know if this happens in the other PAL versions of the game, but I think that probably yes.
This happens in other parts like when all that special conversations that are activated with "Z" button.
I'm using las version 5.471 with default options, just the Memory Card Emulation enabled.
![100_4663](https://user-images.githubusercontent.com/28622717/31669200-b23bb89a-b354-11e7-90ae-793a1c4cd646.JPG)

**Comment by carnage702** [comment]
this is a very old and known bugs every version will beep same for ssbm if you slect characters too fast when using mcemu the only way to do this would be a rewrite of nintendont mcemu code so yeah this has been there since the very beggining.

**Comment by SieKensou** [comment]
Okay, thanks for let me know. I hope it can be fixed someday to make Nintendont the most perfect possible. I was back up and testing all my games, but I have too much, so it took me a lot to test everyone.

**Comment by carnage702** [comment]
i asked him, even on gbatemp and he never replayed to anything or provided any codding whatsoever.

**Comment by FIX94** [comment]
see issue #387.
