### ISSUE TITLE
Reign of Fire (PAL) dialog error

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#498]
It doesn't happen always, but I noticed that sometimes some dialogs doesn't sound (only the subtitles appear), and other times the same dialog sound with voice too.
I'm using las version 5.471 with default options, just the Memory Card Emulation enabled.

**Comment by FIX94** [comment]
didnt have any issues with that, played for a bit.

**Comment by SieKensou** [comment]
I noticed it in the "training stage", when your partner is explaining what you have to do. The most times when he said that you have to fire the zeppelins.

**Comment by FIX94** [comment]
I played through the whole training stage and did not have any issues.

**Comment by SieKensou** [comment]
It doesn't happen always... but maybe is problem of the game itself.
