### ISSUE TITLE
Is there any limit of games for Nintendont?

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#499]
I was back up and testing all my games, but I have too much, so it took me a lot to test everyone. The tests was being done in a USB pendrive with just a few, and after the test, I copied them to my HDD but didn't test them there until today. When I load Nintendont and I select USB, it keeps there in the screen that says "Loading, please wait..." some seconds and after that Nintendont crashes and resets... I have 300 GameCube games there but the limit should be 500 as far as I know.
![100_4666](https://user-images.githubusercontent.com/28622717/31678915-d1d5ad3a-b36f-11e7-8e52-77df676da329.JPG)

![100_4665](https://user-images.githubusercontent.com/28622717/31678921-d7384274-b36f-11e7-8151-2e9907f29150.JPG)

**Comment by SieKensou** [comment]
I have done lots of tests with this and it's not caused by the 300 games. It always happen if I have more than just 1 game in the games folder :/
With just one game it appear correctly and I can load and play the game fine, if I put 2 or more games, the list is not showed and happened what I described in the message before. Please, any help with this? Any idea of what can be happening or what to try? Thanks.

**Comment by carnage702** [comment]
probably have a corrupt nintendont file be it the dol itself or the config bin.

**Comment by SieKensou** [comment]
I tried with an older version of Nintendont and I tried with the new version (downloaded today), and it happens the same. The config.bin file isn't even created...

**Comment by carnage702** [comment]
preety sure you have something corrupt there try deleting every nintendont file including controller inis you might have onn your ninconfig and dol and meta and such from usb/sd delete everything then redownload fresh stuff, also exception dsi usualy happen with controllers are you using hid controllers?

**Comment by SieKensou** [comment]
Okay, I deleted everything as you suggested and redownload. I use original Nintendo GameCube pads, but I had the controllers folder with all the ini files just for if one day I want to use other pad.
After redownloading I tried Nintendont without any extra file (like controllers or titles.txt) and it runs perfect, no problems. Then I added the "titles.txt" and the problem appeared again, so it's my titles file. Is there any character not suported? for example "ó" or symbols like "&"?

**Comment by carnage702** [comment]
im guessing your tiltles txt may be corrupted or you changed it with something that nintendont is not licking, no idea about special stuff.

**Comment by SieKensou** [comment]
Yes, I edited it to make the titles match their right names. I deleted the "ó" and even the "$" in "Wario Ware Inc.: Mega Party Game$!", but the problem persits.... :(
I don't know wich character can be problematic :/

**Comment by carnage702** [comment]
just use the default titles.txt and delete yours.

**Comment by SieKensou** [comment]
Okay, I just deleted the "suspicious" caracters and now it works perfect without errors. Thanks a lot.
