### ISSUE TITLE
Nintendont games list refresh enhandment

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#500]
I noticed that Nintendont checks the entire games folder each time you init the USB or SD from it. This takes too much time if you have too much games so maybe Nintendont could use a file to "save" all the list of your games and that file would be loaded when you select USB or SD (instead of reading all games folder again) and you could use a button (I think button "Y" is free in the game list menu) to refresh the list only when you want to load a new game or remove one. What do you think?

**Comment by geogolem** [comment]
I would definitely love a feature like this.
