### ISSUE TITLE
Tony Hawk's Pro Skater 3 (USA) videos not being showed

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#501]
Why the videos are not being showed (logos, intro and rest of videos)...? When they are playing, the TV put a message saying "video mode not compatible". I remember having this same issue with the first of the James Bond games, but that didn't happen if I used the original game disc through the Wii disc channel. Why does this happen in Nintendont? I don't force any video mode, just default options as always and the official Nintendo components cable.

**Comment by carnage702** [comment]
probably outputs at a resolution your tv cant handle. not nintendont fault.

some games on gc outputted at wierd resoultions that some tvs dont like kinda like megaman collection.

**Comment by SieKensou** [comment]
With the James Bond game, it happens in the PAL version, but not with the USA version. I have the original game PAL and it can't be problem of the TV because it works fine with the original game in the Wii disc channel, so I supose this Tony Hawk's 3 is the same problem.

**Comment by carnage702** [comment]
i never saw anyone having issues with james bond videos not showing or tony hawks tbh well could you try using the scart pin instead of component? and try that again?

**Comment by GB-CG** [comment]
@SieKensou According to my XRGB-mini upscaler while I was using my component cable, the THPS3 FMV's output at 240p, instead of 480p like in THPS4, for example.

**Comment by carnage702** [comment]
so yeah i dont know if his tv supports 240p manny tvs dont support that nowadays.

**Comment by SieKensou** [comment]
I'm out of home now and I can't test with different cable. Please, don't close this issue until I can do all the pertinent tests.

**Comment by carnage702** [comment]
so?

**Comment by SieKensou** [comment]
I still couldn't test with the other cable but I tested the game in a different TV and everything works fine, so probbably is what you said, just some incompatibility with the resolution. I guess we can't do nothing in that case, right?

**Comment by carnage702** [comment]
yeah we cant do anything since the videos are on that resolution we cant change them.
