### ISSUE TITLE
Init DI Reboot problem

### ISSUE THREAD

**Issue by RikyoK10** [FIX94/Nintendont#502]
I've having a problem lately.

I installed Nintendont on the Wii U main screen to play with the gamepad, and it works just a bit.

Everytime i enter it, its normal, i try to launch my game, and it freezes at "Init DI" and then reboots the console.
Everything i need is in the SD Card, and i use IOS58 25.32 with Wii U 5.5.2 at Nintendont at version 5.461.
I use Mocha CFW and i used together to install the app a Signature Patcher.

Does anyone know what's wrong?

**Comment by carnage702** [comment]
461? that is very old update and try again

**Comment by RikyoK10** [comment]
Thank you! It works perfectly now!

And i also did not notice that my SD Card was on lock XD
