### ISSUE TITLE
Exit to OHBC in Wii U Wii VC mod

### ISSUE THREAD

**Issue by jlozes** [FIX94/Nintendont#503]
Helo,

I have injected a Wiivc_Chan_Booter for your OHBC 1.4.1. The OHBC work well and when I quit homebrews, the OHBC reload without problem but Nintendont is the only exception. When I quit Nintendont, my Wii U go back to the main menu, like it does if it's injected dirrectly in a Wii VC.

Do you think it's possible to quit Nintendont and reload OHBC in a Wii VC or it's too difficult to implement?

PS: I use the last version of Nintendont.

**Comment by FIX94** [comment]
the issue is, nintendont injects its kernel into the wii vc fw.img on booting the loader, and since the fw.img never gets reloaded you cant just remove it again which is why I made the decision to forcefully reboot into wiiu menu to get rid of it.

**Comment by jlozes** [comment]
OK, it's not possible, I understand. Thanks for all your work.
