### ISSUE TITLE
Multi ISO not seeing savefile on memory card

### ISSUE THREAD

**Issue by errol23** [FIX94/Nintendont#504]
I have a game burned separately on a dvd and a multi ISO with the same game and another game on it burned on a dvd and the separate one can see the save file on the memory card and works, but the multi ISO with the same game can't see the save file on the memory card.

**Comment by carnage702** [comment]
your actualy sure its the same game and not from another region? if it doesnt see the save file nintendont created a mcemu for it just check your save files and you probably have 2 diferent region games maybe one is pal and the other ntsc or from another pal region.

**Comment by errol23** [comment]
It's from the same region. I used the same gamecube ISO for both.

**Comment by carnage702** [comment]
did you had the same mcemu settings? when you started it for the first time? also what game is it?

**Comment by errol23** [comment]
I use a real memory card for the game and it's Extreme-G Racing Association.

**Comment by carnage702** [comment]
if you use a real memory card make sure mcemu is turned off and open your real mc and see if the save file is actualy there maybe it was deleted.

**Comment by errol23** [comment]
It's still on my memory card and mcemu is not turned on.

**Comment by carnage702** [comment]
not sure what to tell you then, nintendont grabs the gameid of the game and uses that to check the savefile unless you somehow changed it i have no idea, also what do you mean it doesnt detect it? what happens says no save file on card? if so if you try to save would it save or overwrite?

**Comment by errol23** [comment]
It says no save file detected and when I make a new save it shows 2 save files of the same game on the memory card.

**Comment by carnage702** [comment]
then your iso is not the same,  because the mc cant have 2 save files that are the same just do the 2 save files and upload your memory card here, you can extract your save files from real mc using http://wiibrew.org/wiki/GCMM

just upload it here and i will tell you why it isnt the same iso.

**Comment by errol23** [comment]
Both separate and multi ISO game ID's are GXAE51 and the save file from the separate one is also ID GXAE51, but the ID of the save file from the multi ISO is GCOPDV.

**Comment by carnage702** [comment]
maybe the tool you used to make a multi iso changed the gameid on top of the iso thats why nintendont cant fin the save becuase inside your multi iso the header for that game was changed by the program you used.
