### ISSUE TITLE
Pool Edge (JAP) doesn't work

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#505]
After the screens with the logos it show a black screen and nothing more. I have to shut down the Wii because nothing responds. The iso is 1:1 with the right CRC-32 and MD-5. As always, no options activated more than the Memory Card Emulation. Tested with version 5.471 and with the last 5.476.
A continuous noise sounds if I press a button to try to skip the logos.

**Comment by FIX94** [comment]
should be fine now, it does some weird out-of-bounds memory actions on bootup.
