### ISSUE TITLE
Force progressive issue / Blackscreen

### ISSUE THREAD

**Issue by seewood** [FIX94/Nintendont#506]
Hey Fix94, first of all great work you did for the Wii ! 

I got an issue when i start to play a PAL Game and force progressive Mode on my Wii. I tested it with Mario Kart DD and Zelda WW. When i start the Games with "force progressive - off" it start normal - The Red Nintendo Logo shows up and i can decide between 50 and 60Hz Mode and the counter runs down to zero. 

When i start these Games with "force progressive - on" the sound starts as normal but i get a blackscreen as long as the counter from 50 and 60Hz Mode runs to zero, then it shows me the screen and my TV told me he is in 480p mode ! So i didnt see the Red Nintendo Logo and the Decide Screen for 50 and 60Hz Mode.

What is my fault ? I asked other People and they havent this issue. 

Nintendont loads from IOS58
I have the games on SD Card (USB Fat 32 tested as well - same issue)
Latest Nintendont Version installed
Official Nintendo Wii Component Cable installed

**Comment by carnage702** [comment]
you cant just force progressive without forcing videomodes for pal games since progressive is 60hz only and games start in 50 even if they have a selection afterwards so to force progressive you force need to  force ntsc  videomode alongside it.

note that not every game will work when forced to ntsc videomode or progressive.

**Comment by seewood** [comment]
Ok thanks, the other settings are on default.  Additionally when i Set Patch Pal 50 to ON it Works fine, Red Nintendo Logo and the screen where i can select the 50/60Hz. 

What does Patch Pal 50 did exactly? I think I didnt understand the Code exactly 

What do you think are the recommended settings for me?

**Comment by carnage702** [comment]
patch pal 50 is for some games that the force ntsc videomode isnt enough its basicaly an alternative complementary patch to force videomodes. turn it on if needed basicaly.

**Comment by seewood** [comment]
Ok you said it is normal that i didnt see the Red Nintendo Logo and the 50/60Hz on Start because the pal Game Start in 50Hz? Is that correct?

**Comment by carnage702** [comment]
if you see red is becuas your tv does not support ntsc signal? or your using some rgb cable?

**Comment by seewood** [comment]
Got a 100Hz bravia, kdl-40we5 with Nintendo official component cable

**Comment by seewood** [comment]
Not See Red, See the Red Nintendo Logo! For example Mario Kart DD the Red Nintendo Logo comes up and Mario said "Nintendo"  in force prog. "ON" cant see it.

**Comment by carnage702** [comment]
jut turn force videomode to ntsc and force progressive to on problem solved.

**Comment by seewood** [comment]
Ok, I will Test it and give you Feedback. THX.

**Comment by FIX94** [comment]
PAL50 simply doesnt have a default progressive display in gc games so you see nothing when you boot them, just press A on the PAL50/PAL60 selection which is open in the background and it'll then show up, thats just how it is.

**Comment by FIX94** [comment]
oh and also, patch PAL50 is disabled by default as that is a very aggressive patch trying to change the default PAL50 bootup to PAL60 which can cause a lot of crashes, display bugs, screen flicker and all sorts of other weirdness depending on the game, so I personally prefer the blackscreen first, press A to see something over having the game crashing on you or being unplayable.

**Comment by seewood** [comment]
Okay tested it, issue is still there. Tried it with Video Force - NTSC

Never Show me the Nintendo Logo and the 50/60Hz desicion at Start up.

Sound Works great 

My settings are:
Force Progressive - On 
Video - Force
Videomaterial - NTSC

Tried this too:
Force Progressive - On
Video - Auto and None 
Same issue

Tried this:
Force Progressive - On 
Video - Auto
Patch Pal 50 on the right side below screen Position and that shows me the Nintendo Logo and the desicion screen for 50/60Hz.

I think it is What it is. The Game starts with 50Hz and this cannot be forced, when the 50/60Hz desicion is done by default 60Hz the TV gave me the 480p Mode. I have to like with it, or any other ideas?

**Comment by FIX94** [comment]
see my comments above as to why things are how they are, honestly I dont see it as much of a problem as it is just one button press you have to do.

**Comment by seewood** [comment]
Yeah that's right. But i didnt see anything. The Game starts without a picture. When i press A at the right moment the game starts in 60Hz or i press nothing and the game will Start by default in 60Hz. So or so it will Result in 60hz Mode, I thougt that isnt right because the Logo and desicion is not shown up for me.

**Comment by FIX94** [comment]
as I said thats because that stuff is displayed in PAL50, every PAL game starts in PAL50 thats just how nintendo designed the gamecube.

**Comment by seewood** [comment]
Okay so its normal! Thanks a Lot

**Comment by FIX94** [comment]
this is indeed perfectly normal behaviour, not a whole lot you can do about it except I guess switch to NTSC game versions if you REALLY want to see the logos that badly ;)

**Comment by seewood** [comment]
Not so badly:-) ok great, mark it as solved!
