### ISSUE TITLE
Wii U Shuts off After Launching an Injected Gamecube Game

### ISSUE THREAD

**Issue by JustStache** [FIX94/Nintendont#507]
Not sure if this was the right place to put this, but I thought I'd try.

So basically, my Wii U shuts off after launching an injected version of Paper Mario: The Thousand-Year Door and I have no idea why. All of my other Gamecube games work 100% fine though! I've been trying to find a fix to this for HOURS and it seems nobody bothered to help me out. The ISO dump is legit, and I even tried other ISO's of the same game just incase mine was messed up. But every ISO I've tried resulted in shutting off my Wii U after trying to load. It basically shuts off after the Wii logo shows up and sits at a black screen for about 10 seconds.

I don't know if its the ISO, a Nintendont setting, something else on my Wii U or what. But for some reason its just this certain game! This hasn't happened with any other Gamecube game (so far?).

If someone would be so kind to help me figure this out, you'd honestly make my day!

**Comment by carnage702** [comment]
are you shrinking the iso? because some shrink tools break the alligment and when nintendont huts the wii or wiiu off means its a bad iso.

you can list your nintendont settings but im preety sure it has to be your iso since that is expected when nintendont seems misalignement, you can enable log and osreport on the settings so we can see what nintendont says when it shuts the iso out.

**Comment by JustStache** [comment]
I don't think I am shrinking it? I am using a tool called WiiVC Injector Script. Mind telling me how to enable log? I am somewhat new to this, but not too new lol.

**Comment by JustStache** [comment]
I enabled log and OSReport. But idk how to check them since it just turns off the Wii U. Literally when I load it up it stays black and shuts off.

**Comment by JustStache** [comment]
Okay I don't think its the ISO. I tried 7 different versions of the ISO and I am still getting the same results. I even found a few USB Ready versions to see if those were any different. The problem seems to be the Wii U or Nintendont I think. Now I am very confused.

**Comment by carnage702** [comment]
if you had log enabled check your sd card root and a log is there  just past it here.

**Comment by JustStache** [comment]
There is no log file. Hmm it might be my Wii U then? And I did enable the log setting.

**Comment by carnage702** [comment]
just use the wiivc inject script but choose not to autboot so you can enter nintendont menu before launching the game and then just to be sure put also the iso  on sd card if noone autoboot nintendont inject launches papper mario fine from sd card then its the scrit destroying the iso.

**Comment by JustStache** [comment]
Okay, I tried to launch Paper Mario off of the SD card and it shut off my console again. But this time it saved a log! This is what the log says

Nintendont IOS58 v25.32
Built   : Oct 30 2017 22:41:43
Version : 5.479
Game path: /games/G8ME01/game.iso
EXIInit Start
EXI: Trying to open /saves/G8ME.raw
Got Shutdown button call
EXI: Saving memory card(s)...Done!

Idk what any of this means.

**Comment by JustStache** [comment]
Oh wait! I finally got it working! I didn't know what the log ment at first but I deleted the G8ME/raw file to see what happens, and it began to work. Sorry about all this haha. But thanks for your help regardless!

**Comment by carnage702** [comment]
probably had a corrupt save somehow that was created when you first started the game for some odd reason.

**Comment by ABIDE99** [comment]
Hey I'm having the same issue and I was wondering if you could tell me exactly what you did to fix it and hwlp me out a bit.

**Comment by carnage702** [comment]
he had a corrupt save on the sd card, when wiiu shuts off means bad iso, bad save or bad file like corrupt ninconfig,bin or nintendont boot.dol, so you have a bad file somewhere.

**Comment by ABIDE99** [comment]
How can I tell if it's a bad file?

**Comment by carnage702** [comment]
well first does this happen on all games or just one?

**Comment by ABIDE99** [comment]
It's happened on the two recent games I've injected so far. Previous games I have installed load and work just fine.

**Comment by carnage702** [comment]
then first make sure yyour settings arent being the issue since some games dont like certain settings set take a pictue of your nintendont settings.

**Comment by ABIDE99** [comment]
Okay I've taken a picture of them, what do you want me to tell you?

**Comment by carnage702** [comment]
everything in there

**Comment by ABIDE99** [comment]
Cheats:off
Debugger:off
Debugger Wait:off
Memcard Emulation:on
Cheat Path:off
Force Widescreen:off
Auto Boot:off
Unlock Read Speed:off
OSReport:off
Wii U Widescreen:on
Drive Access LED:off
Log:off
MaxPads:4
Language:Auto
Video:Auto
Memcard Blocks:251
Memcard Multi:off
Native Control:off
Video Witdh:Auto
Screen Position:0
Patch PAL50:off
TRI Arcade Mode:off
Wiimote CC Rumble:off
Skip IPL:no

**Comment by carnage702** [comment]
settings are fine so try deleting the saves file with those game ids i dont know wich games your having trouble with but the saves files are using the same gameid also make sure your sd card is not locked.

**Comment by ABIDE99** [comment]
What do you mean by delete the save file, where is it? The games I was having trouble on was mario party 7 and spongebob battle for bikini bottom. I just installed Mario Party 5 and it worked so maybe it could be the iso?

**Comment by ABIDE99** [comment]
Actually I replaced the nincfg file so maybe that was the file that was not working.

**Comment by ABIDE99** [comment]
Mario Party 4 worked fine so I'm certain it was just the iso on those 2.

**Comment by carnage702** [comment]
sometimes saves get corrupted or isos to make sure its not the save just delete your save file for that game its under saves on the sd card 

Mario party 7 usa would be called GP7E.raw while pal GP7P.raw
spongebob its usa GQPE.raw or pal GQPP.raw

**Comment by carnage702** [comment]
if you delete the save and they still dont work then yes you used some bad isos.

**Comment by LabRat46** [comment]
Carnage702 - you legend!! 

I have just spent about 6 hours smacking my head against the WiiU gamepad trying to figure out the issue with a Gamecube injection not launching from the WiiU menu. 
After reading your post, I went through and found a 0kb save file, deleted it and spent the rest of the night gaming away. 

Many thanks!!
