### ISSUE TITLE
Gamercard in triforce games?

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#508]
Does anyone know how to activate the gamercard in triforce games? Without it it does not work save, and every time that reboot has to start from scratch.

**Comment by carnage702** [comment]
its activated if you have mcemu on, when you start if it says for you to creat a mario card if you creat it then do some races when it says continue after a race ends you choose no, and it will say writing to mario card , after afew seconds give it 5 or 6 just exit or shutdown the console to keep the save.

btw triforce only saves mario gp 1 and 2 and f zero.
