### ISSUE TITLE
Super Mario Sunshine possible issue or game mechanic?

### ISSUE THREAD

**Issue by DanteMele** [FIX94/Nintendont#511]
I got a USA iso (1.35GB) of the game but when certain items (ie coins) are in a distance behind buildings/or when underground they are rendered as question marks, collecting or acting with them grant the normal traits. Is this an issue with the game or this is a game mechanic to maintain performance?

**Comment by GB-CG** [comment]
That's normal.  You could've checked on Youtube for this.

**Comment by DanteMele** [comment]
I tried, couldn't find any information. Anywho thanks for the advice!

Get Outlook for Android<https://aka.ms/ghei36>
