### ISSUE TITLE
USB Controller Crash 

### ISSUE THREAD

**Issue by taebot64** [FIX94/Nintendont#512]
Everytime I plug in a USB device nintendont crashes i'm using to forwarder for Wii U and it crashes. when I plug it in when I start it up with the controller in the wii u it takes about 3 seconds to crash everytime it restarts my wii u pls help ASAP. its Friday and my brother love gcn so I wanted to surprise them!

**Comment by carnage702** [comment]
delete you r controller.ini if you have any on the root of your sd card, also whay versin of nintendont are you using? say the actual number.

**Comment by taebot64** [comment]
let me check
and I don't have a controller ini in my root

**Comment by taebot64** [comment]
5.463

**Comment by carnage702** [comment]
you are way behin last rev update and try again
