### ISSUE TITLE
"An error has occurred"

### ISSUE THREAD

**Issue by fielrg01** [FIX94/Nintendont#514]
I've currently updated to the 10/30/17 revision of Nintendont for my Wii.  Occasionally I was getting the "An error has occurred" message, but now it seems more frequent.  I'm using a 2TB HDD.  I'm loading my games through USB CFG.  So far I have tested Lego Star Wars, SSB Melee, Need for Speed Underground and Super Mario Sunshine.  I was having these issues before the update, so I updated thinking this would resolve the issue.  What could possibly be causing this?  My Wii games are loading just fine from the HDD, so I wouldn't think there would be an issue with the HDD.  Any help would be greatly appreciated.

**Comment by carnage702** [comment]
error is ocurring happens when your hdd is to slow to respond im guessing your hdd might have a hidden sleep mode and slows down and when nintendont calls it he isnt fast enough to respond and game throws an error it could also mean its underpowered and needs a y cable or its own power supply.

**Comment by fielrg01** [comment]
Ok awesome.  I'll try out a Y cable.  Thanks for the info.

**Comment by fielrg01** [comment]
Ok so I tried out the y cable.  It seems to work on the games I was having issues with, but I'm still seeing that error occasionally on other games.  Any other suggestions?

**Comment by carnage702** [comment]
not really maybe your hdd does have some sort of sleep mode integrated and goes to sleep, its all i can think off.

**Comment by bandiban** [comment]
Hello, i'm french (so i have not a good level in engish), "an herror has occured" appears a lot on my screen, i don't put the games on my sd or an external hard drive, but i put my games on a usb key in /games/[name of the game]/ and i rename them as "game.iso". "an herror has occured" appears all of the time on all of my video games. I don't understand what's th e problem with my usb key because i can play wii games with usb loader gx. So, can you help me ?

**Comment by bandiban** [comment]
I just noticed that my games deleted themselves

**Comment by carnage702** [comment]
nintendont requires much more speed than wii games, and seems you have a faulty flashdrive, the error has ocurred message happens when nintendont cant read the iso or write to the device fast enough, just get an decent sc card class 10 and up or an hdd.

**Comment by bandiban** [comment]
ok ,thank you.

**Comment by bandiban** [comment]
Nintendont can reed nkit.iso game ?

**Comment by carnage702** [comment]
> 
> 
> Nintendont can reed nkit.iso game ?

nintendont reads regular isos no idea what is a nkit.iso.

**Comment by bandiban** [comment]
it's a shrunked iso.

**Comment by carnage702** [comment]
> it's a shrunked iso.

Badly shrunken isos cause issues on nintendont, if you want shrunk use dmtoolbox and pick 32k alligment

**Comment by bandiban** [comment]
hi, I bought an "y cable" and now it works.
