### ISSUE TITLE
USB port issues with CronusMax Pro (Xbox360 Controller)

### ISSUE THREAD

**Issue by B00daW** [FIX94/Nintendont#515]
Seems to be some compatibility issues with the [current release](https://github.com/FIX94/Nintendont/commit/d6bf7e53bf27b99e648d983b3c09b50f5e1374ce) of Nintendont loader USB port locations and CronusMax Pro with an Xbox360 Controller connected.

Setup works fine with CronusMax Pro plugged into port 0 and USB HDD plugged into port 1.  With HDD plugged into port 0 and CronusMax Pro plugged into port 1 the Wii will turn off when it reads the "HDD."

This is a compatibility issue with USB Loader GX.  USB Loader GX with its IOS or w/o its IOS seems to only load HDD images through port 0.  When loading a Gamecube game with Nintendont, it will just reset back to the application.

Please add additional checks to see if a FAT32 file system can load from either port 0 or port 1 before crashing or resetting.

Thank you so much for all of the effort going into this project!

**Comment by carnage702** [comment]
usbloader has an option to use port 1,port 0 or both so try that? its somwhere on usbloadergx settings.

**Comment by B00daW** [comment]
I have that working fine now using meta.xml; thanks.  The issue still
exists in Nintendont if CronusMax Pro is in "port 1".
