### ISSUE TITLE
Video Width is bugged in new version

### ISSUE THREAD

**Issue by KainXVIII** [FIX94/Nintendont#516]
Updated Nintendont from version 4.something to 5.479 and looks like "Video Width" option is bugged - i set it to 674 so my image is stretched for my tv without borders, but in some games it scales perfectly (like Killer 7) in other (like Day of Reckoning or Timesplitters 2) image just offsets too far (behind border of the screen), Auto options works fine for this games, but without scaling off course.
I don't remember that happen in 4.* version of Nintendont, all games worked fine =(

**Comment by carnage702** [comment]
each games has its own value and some games even crash when using this its a per game setting, its a hack it will never be perfect since some games have diferent values than others.

**Comment by KainXVIII** [comment]
I need to find older versions to check this for sure =)

**Comment by KainXVIII** [comment]
Yeah, you was right, Video Width option depends on game, on some it works on others - don't (even in earlier 4.x version)

**Comment by carnage702** [comment]
like i said its a hack it will never be 100% compatible.
