### ISSUE TITLE
Super Mario Sunshine: possible issue with iso/emulation or part of the game?

### ISSUE THREAD

**Issue by DanteMele** [FIX94/Nintendont#517]
At times when I lose a life (not getting game overs), I am sometimes redirected back to the hub world. Is that part of the game or an issue with emulation/iso?

**Comment by carnage702** [comment]
are you serious ...

**Comment by GB-CG** [comment]
@DanteMele That's normal too. If you have any miscellaneous questions that doesn't quite fit into being an Nintendont issue, you can ask at the official [support thread](https://gbatemp.net/threads/nintendont.349258) over at GBAtemp.net, in case you didn't know.

**Comment by DanteMele** [comment]
Sorry about that, I never signed up on GBAtemp.

**Comment by GB-CG** [comment]
No worries, just a friendly reminder that's all.
