### ISSUE TITLE
Native  control issue 

### ISSUE THREAD

**Issue by luigifan200** [FIX94/Nintendont#519]
I use wii u with  the gc adapter i set it to native  control off and  nothing  works im using the  latest version of Nintendont the game is Metal Gear Solid the twin Snakes
Also the controller is in controller port 1 I'm not sure why this happens please fix

**Comment by carnage702** [comment]
native control does not work on wiiu, native only works on wiis with gc ports, the wiiu gc adapter is an hid controller, also mgs you cant press A or anything on the progressive prompt after that you can.

tell me your exact set up.

wii or wiiu?
using normal vwii or wiivc inject?
nintendont version number?
what do you have connected to usb ports?
all your nintendont settings?
