### ISSUE TITLE
Resident Evil 3 crackling sound issue. 

### ISSUE THREAD

**Issue by Raphfriend** [FIX94/Nintendont#521]
Well, I don't find something about, so I'm opening this.

The sound in this game with Nintendont keep crackling (like a popcorn) time to time, if you guys can not find it, I can put here a video.

Thanks.

**Comment by carnage702** [comment]
there is no issue with the sound of this game so you either have a bad iso, a very slow sd card or you have settings turned on that are slowing it down.

check your iso md5 first
then post a picture of your nintendont settings.

**Comment by raphfriend** [comment]
I'm using the 1:1 dump, MD5 check fine and a good HDD. I've noted that turn on the Disc Speed option the crackling is less present. I'll post a video later.

**Comment by carnage702** [comment]
make sure you dont have log set to on or osreport by acident.

**Comment by raphfriend** [comment]
Sorry, but how i know if what you said are enable?

**Comment by carnage702** [comment]
take a picture of your nintendont settings you know how to see them right? or are you using an autobooter to get ingame or an usb loader?

**Comment by raphfriend** [comment]
I'm using homebrew channel so Nintendo tem.

**Comment by raphfriend** [comment]
Sorry, Nintendont.

**Comment by carnage702** [comment]
whn seeeing the list of game names press B or 1 to see the settings and them take a picture of them.

**Comment by raphfriend** [comment]
Let me know if you can see it well.
![img_20171126_182505582](https://user-images.githubusercontent.com/11281309/33244712-1c4f5ed0-d2db-11e7-96a1-7069b962fa8a.jpg)

**Comment by carnage702** [comment]
try putting unlimited read speed to off and videomode to auto.

also are your games on sd card?

**Comment by raphfriend** [comment]
Like i said the games are on a HDD. With Unlock read speed on i can't hear the crackling so much, so i think i'll play like this. Just got some bugs with high speed GCs but i don't care.

**Comment by carnage702** [comment]
its very very wierd because re3 is not an high speed game at all.


could you try something, you have an sd card? try putting the re3 on sd card and play it from there if it doesnt crakle it means your hdd has some issues reading becuase sd cards are much slower.

**Comment by raphfriend** [comment]
I'll try later and give the report!

**Comment by FaunoLab** [comment]
Would it be possible to reopen this issue? I am having the exact same issue. The song that plays when we are being chased by Nemesis crackles. I've tried playing on another drive, via the sd, and checked all settings discussed above.
