### ISSUE TITLE
Games sometimes load to black screen

### ISSUE THREAD

**Issue by DanteMele** [FIX94/Nintendont#522]
Ok,  I fixed all my other issues, but my games (NTSC, Crash Bandicoot: Wrath of Cortex, The Simpsons: Hit and Run, Super Mario Sunshine, Paper Mario: The Thousand Year Door, Sonic Heroes, WarioWare Mega Party Game$!, Kirby Air Ride) sometimes load to black screens and get stuck there (the Wiimote doesn't light up and the gamecube animation doesn't appear) after using USBLoaderGX, my save data is always safe when this happens. Any way to fix this or prevent this from happening?

USB: Staples 16GB (Unknown USB brand)
SD: 1GB PNY
Console: Black Wii U 5.5.2U

**Comment by carnage702** [comment]
if your using the bios then its normal, sometimes the bios will blackscreen no one knows why.

**Comment by DanteMele** [comment]
Ok
