### ISSUE TITLE
Mario Party 4 Softlock 

### ISSUE THREAD

**Issue by RyanmFisher** [FIX94/Nintendont#528]
After selecting a character in the Extras room the game freezes but the music keeps playing happens no matter what option you pick in that mode

**Comment by FIX94** [comment]
This is already an issue if you just looked on page 2 of the issues, see this comment I've made for a sort of workaround for now.
https://github.com/FIX94/Nintendont/issues/437#issuecomment-347103701
Basically start game, immediately reset the game with either controller reset or pressing reset on the console, after that it should work correctly.
