### ISSUE TITLE
Will this 3rd Party Controller Work on Nintendont for the original Wii? 

### ISSUE THREAD

**Issue by nanashi89** [FIX94/Nintendont#529]
https://www.ebay.com/itm/NEXiLUX-Wireless-3-Pro-Controller-Gamepad-for-Nintendo-Wii-U-Gray-Free-Shipping/272665637996?epid=2254545930&hash=item3f7c23746c:g:7ZMAAOSwcB5ZEuoP

Feel like I should ask before spending money...

**Comment by v0idst4r** [comment]
No reason to ask here. Why don't you ask Nintendo if they support 3rd party controllers?

**Comment by carnage702** [comment]
99% of third party or fakes dont work, so i wouldnt spend money on it tbh, just buy a wiiu pro official used controller.
