### ISSUE TITLE
An error has occurred. (latest version of nintendont)

### ISSUE THREAD

**Issue by Glen0120** [FIX94/Nintendont#530]
Please help, I get "An Error has Occurred" on every game I play on Nintendont, Dios Mios and Devolution doesn't work for my wii.

**Comment by carnage702** [comment]
an error has ocurred is usualy shown when the evice you are suing is too slow to play gc games either a very slow sd card or usb or you have settings turned on that are making the game crash like osreport and log set to ON in the settings.

**Comment by Glen0120** [comment]
I'll check my settings later, thx for the info.

**Comment by GerbilSoft** [comment]
For reference, the "latest" version as of the creation of this issue is the recompiled build of v5.480.

https://github.com/FIX94/Nintendont/commit/7bdfaca4836549c6c2ca1204926c5ac6353e0a31
