### ISSUE TITLE
Just updated - freezes now at Init DI...

### ISSUE THREAD

**Issue by millenius** [FIX94/Nintendont#531]
Hi i updated nintendont from the settings and now I can't load a game it will just freeze up and require I restart the Wii at the "Init DI" stage.  Version # escape me but it's definitely the latest, November 27 2017 or something like that. 

Where do I find older versions and/or how can I fix this

Old Wii with gc controller ports
d2x v10 beta52
320GB WD Scorpio drive in enclosure. 1 big FAT32 partition with only 2 folders wbfs and games

Wii games work great and emulator stuff is fine nintendont is just broken

Edit I have v5.480 (Wii)

**Comment by millenius** [comment]
I figured out how to browse Code history... I've only ever downloaded 'releases' on this site b4 sorry I'm a bit dense I guess lol

I don't remember what version I had but I'm having a much better time with v4.435 than v5.480 so far. 

still got a couple quirks though, mainly that it only wants to load games properly when the HDD is in the _left_ USB port, but USB Loader GX can only initialize the HDD in the _right_ port. I've had to use Nintendont from HBL and filter USBGX to only show Wii games, swapping USB ports between using the two, as a workaround but it's a pretty inconvenient/messy solution.

**Comment by carnage702** [comment]
go into usbloader gx  options and choose both usb ports instead of the 1 or 0 that is there.

**Comment by millenius** [comment]
that didn't work and now USBLoaderGX can't mount the HDD at all, on any port/USB ports option combo. Tried deleting config files, tried an older version of it, tried reinstalling d2x, tried running on ios58(251) 

However, Nintendont is working perfectly, I read that it's only supposed to work in the bottom port. I guess I should close this, reformat my drive, and ask elsewhere if the new problem persists.
