### ISSUE TITLE
Wipeing my memory unit

### ISSUE THREAD

**Issue by FireHonor** [FIX94/Nintendont#536]
I had three games on my PNY 32GB USB stick, Super Mario Sunshine, Ed Edd and Eddy the Mis-Edventures, and Scooby Doo Unmasked. I played Super Mario Sunshine for about an hour, everything worked fine, but when I went to boot Nintendont the next day, I selected USB as normal, because my games are on there, it said USB/games didn't have anything in it. I shut off my Wii, put the USB in my computer, and no files were on the USB, even the games and saves folders were gone. Super Mario Sunshine was the only game I played, I didn't even boot the other two at all. I was ready to play Ed Edd and Eddy, when the message appeared.

**Comment by carnage702** [comment]
flashdrives are very inconsistent with homebrew in general either get an sd card or an hdd.

**Comment by carnage702** [comment]
also always make sure you have log and osreport set to off in the settings.

**Comment by FireHonor** [comment]
Log and osreport were both set to off from the start. To clear something up, I have Homebrew and my apps for Homebrew installed on a sd card, the only reason why I have the Nintendont games and saves on a USB is that I am concerned that I might run out of space on my sd card.
