### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by martinmagic** [FIX94/Nintendont#537]
Hi with wii2hdmi I can play at 720p but when I load through CFG usb loader it does not detect settings screen.

**Comment by carnage702** [comment]
you still only play with 480p there is no magic to make wiis into 720p or 1080p, the wii only outputs 480p, so you never ever get 720p just a 480p with a very very poor upscale at best.

**Comment by martinmagic** [comment]
I mean some wii2hdmi don’t fill the screen but the dol on nintendont has an
option to fill screen on “720” settings within the nintendont settings...

**Comment by GerbilSoft** [comment]
Are you referring to the video width? "720" is the maximum output width of the Wii's framebuffer.

"720p" refers to the image height, not width. (1280x720)

**Comment by martinmagic** [comment]
Yes i move it and it stretches it to full at 720 mark I guess, it’s weird
the hdmi doesn’t go full anywhere else but nintendont I can play it full

**Comment by carnage702** [comment]
it depends on the game, some games stretch with 720 seting some dont, and some even crash.

**Comment by martinmagic** [comment]
All the GameCube games work on that settings

**Comment by carnage702** [comment]
no they dont, try zelda collectors edition any of the n64 games and f zero x, and manny more straight up crash with anything but default.

**Comment by martinmagic** [comment]
I’ll try those games but it works with metal gear solid and GameCube indies
