### ISSUE TITLE
Switch Joycon Support

### ISSUE THREAD

**Issue by Radtendo** [FIX94/Nintendont#538]
Hi, sorry if this has been asked a million times before already, and I get that the Joycons are newer hardware, but would Joycon support be possible in a future release?

I ask because my Gamecube controller is broken, and I currently have no other controllers other than my wii remote and nunchuck that would work with Nintendon't. Only other ones I have are my Joycons.

Like I said, I apologize if this has been asked before, but I'm just curious as to whether such a thing is even possible, given that it's newer hardware.

Also I should say, I do have a PS3 controller, but it's a wired Rockcandy controller, I've tried it but it doesn't work. Best guess for that is that it's just not supported.

**Comment by Radtendo** [comment]
Also I should say, I do have a PS3 controller, but it's a wired Rockcandy controller, I've tried it but it doesn't work. Best guess for that is that it's just not supported.

**Comment by GerbilSoft** [comment]
Switch joycons use standard Bluetooth HID (with some minor adjustments) as opposed to the proprietary application layer protocol used on Wii controllers.

It would be possible to support Switch controllers if standard Bluetooth HID was added, but that hasn't been done yet, and I'm not sure if anyone is interested in doing so.

**Comment by Radtendo** [comment]
Ah, I see. Well thanks for clearing that up.
Guess I'll just have to wait until I can buy another Gamecube controller for now.

**Comment by Missingphy** [comment]
reopening the issue... https://gbatemp.net/threads/how-to-use-xbox-one-switch-pro-and-more-controllers-wirelessly-on-nintendont.540706/#post-8676288
