### ISSUE TITLE
Disney's Magical Mirror Starring Mickey Mouse - Game Crash

### ISSUE THREAD

**Issue by cheatfreak47** [FIX94/Nintendont#541]
Was reported on GBAtemp by DaTank45, the jist is that the game just outright crashes little way in under a handful of circumstances from the sound of it.

Nintendont v5.480

Affected GameIDs: 
GDME01 - Disney's Magical Mirror Starring Mickey Mouse (USA)
GDMP01 - Disney's Magical Mirror Starring Mickey Mouse (EUR)
GDMJ01 - Disney's Mickey Mouse no Fushigi na Kagami (JAP)

I checked the problem on the USA version- both with ISO I dumped from my physical disc (which is verified against redump's dats so it's a good dump for sure) plus I tried running my physical disc in Nintendont with the "Boot Disc in Drive" option and the issue is still present.

Nintendont settings are all the defaults. (untouched config)

The specific instructions for reproducing it from DaTank45 were probably accurate, though I actually attempted it and got a crash as well in a different fashion which is a bit easier and more consistent to execute, and chances are it's the same issue causing both crashes. (Probably.)

To easily reproduce:
Boot the game and start the game in kids mode, watch the introductory scene, repeatedly click on the door on the left until you see a cutscene with Mickey Mouse being attacked by a clone of himself and randomly in the middle of it it will crash to a solid green screen.

This is 100% consistent to reproduce, and since this is not the first time people have complained about this game.

@carnage702 says that the issue was not present on v5.467 (which he tested it against first before updating his copy of Nintendont), meaning the problem was likely introduced after that point.

**Comment by cheatfreak47** [comment]
Edit: Apparently this is not the first reporting of a Disney Magical Mirror crash issue on the tracker, who knew? #520 is likely the same problem.

**Comment by cheatfreak47** [comment]
I thought to do this when I some trial and error too and determined it began happening at f5a27ba (477), which is when some changes to ARStartDMA were made, I guess those changed caused this to start happening in Disney Magical Mirror somehow. ¯\_(ツ)_/¯

Adding it to the arstartdma exception list stops the game from crashing and I see no other adverse effects in doing so, so I suppose this is an adequate solution, eh?

**Comment by carnage702** [comment]
fixed with 481.
