### ISSUE TITLE
Add support for using D-pad as left analog stick

### ISSUE THREAD

**Issue by libertyernie** [FIX94/Nintendont#546]
Four Swords Adventures uses the joystick for movement, but the input is limited to 8 directions. It doesn't allow movement with the D-pad - the D-pad does the same thing as the X button, IIRC.
It would be nice to be able to use the D-pad instead when using the Classic Controller, which has a bigger D-pad than the GameCube controller.

This weekend I might work on a pull request that would add an option for this.

**Comment by FIX94** [comment]
honestly I think you'd be better off with just creating a cheat for things like this as its very specific to just one game and I really dont want to add more complex stuff to the already far too long pad read function.

**Comment by libertyernie** [comment]
Thanks for the note. I use a set up where each game has its own nintendont .dol, so it'll be easy enough for me to just compile a custom version.

**Comment by vaguerant** [comment]
I'm years late on this one, but this game always bothered me, so I made an attempt at fixing it by adding D-pad controls. I'm not very familiar with the game, so I'm not at all sure that I didn't break anything, so you can consider these codes untested.

```
D-pad Control (USA)
0430A7FC 48000014
0430A834 48000014
0430A86C 48000014
0430A8A4 48000014
0430A8E4 60000000
0430A900 60000000
0430A91C 60000000
0430A938 48000010

D-pad Control (Europe)
04311DF4 48000014
04311E2C 48000014
04311E64 48000014
04311E9C 48000014
04311EDC 60000000
04311EF8 60000000
04311F14 60000000
04311F30 48000010

D-Pad Control (Japan)
043ED424 48000014
043ED45C 48000014
043ED494 48000014
043ED4CC 48000014
043ED50C 60000000
043ED528 60000000
043ED544 60000000
043ED560 48000010
```
