### ISSUE TITLE
Mario Party 5 & 6 Music Stops

### ISSUE THREAD

**Issue by diettelo** [FIX94/Nintendont#548]
On MP 5 & 6 Music stops on the Field when playing for about 1 Minute or an Mini Event is loading
Like Capsule Shop. On Mini Games or other Events it works fine and loops.

I also was watching when Music stops it freezes about 1 Second.

**Comment by Funnybunnym** [comment]
For me, Mario Party 7 also loses its music in the main menu after booting the game, then it crashes and I get an error about having to restart the gamecube or something (and I'm on wii). This error happens every time I boot the game and I just can't seem to fix it.

**Comment by G3K20** [comment]
> seems like a bad dump or shrunken badly iso or using imompatible settings, i played all mario party games just fine on nintendont for several hours each.

Which options do you choose in the config.file? Bc if i start mario party 6 my wii u shuts down and if i start mario party 5 is just shows the initializing screen and freezes.

**Comment by carnage702** [comment]
wii shutting off means bad save file was created, bad nintendont config files or corrupt iso.

check you save folder see a 0kb file there and delete it, same for ninconfig.bin if its corrupted and the iso needs md5 check.

for perfect compatibility everything should be off or auto or zero except memory card emulation.
