### ISSUE TITLE
Wii U / Nintendont / Wavebird on Adapter / Twilight Princess / Lights on wiimote go from 2 (working) to 1 back to wiimote only

### ISSUE THREAD

**Issue by danman1982** [FIX94/Nintendont#549]
I am using a Wavebird through adapter connected to wii u on nintendont playing twilight princess. It has worked fine like 1/3 through the game, now after about 5-10 minutes of gameplay the wavebird GC controller stops working, and the blue lights on the wiimote (normally 2 is illuminated on wiimote when wavebird is working perfectly) now the light randomly goes to 1 which takes functionality away from wavebird and forces wiimote + nunchuck only...is there some glitch within nintendont causing in-consistent controller recognition?

**Comment by carnage702** [comment]
remove all attachements from wiimote.

**Comment by danman1982** [comment]
Thank you that worked!!

**Comment by carnage702** [comment]
any attachement to the wiimote is considered a controller so yeah.
