### ISSUE TITLE
Enhancement: Add USB Microphone support for GC Microphone emulation

### ISSUE THREAD

**Issue by Wolfy76700** [FIX94/Nintendont#550]
Hi there! Would it be possible to add USB Microphone support to have access to some Microphone-related features in Nintendont when you don't have access to a GC Microphone, like in Mario Party 6/7?

**Comment by carnage702** [comment]
it would be extremely hard work to reverse enginer gc microphone and make it work using usb microphones considering only like 5 games use it and 2 are jap exclusive, but if you find someone who wants to reverse enginer it they can make a pull request when they have it working.
