### ISSUE TITLE
Memcard size limit (Wii)

### ISSUE THREAD

**Issue by BitPatty** [FIX94/Nintendont#554]
For a specific game mod we need as much extra space as possible and abusing the emulated memory card would be the easiest way to accomplish this.

The mem_map reads the following:

```
0x91000000-0x92000000=memcard emu - end point depends on memcard size
0x92000000-0x92E80000=cache - start point depends on memcard size end point depends on Triforce
0x92B80000-0x92E80000=(In Triforce mode this is reserved for DIMM memory)
```

And also: https://github.com/FIX94/Nintendont/blob/3e81dadcfc4b19129f08a947905331f1d45a1b0b/kernel/ISO.c#L386

Does that imply that a bigger range than 0x91000000-0x92000000 is available for the emulated card if required?

**Comment by GerbilSoft** [comment]
That range is 16 MB, which is the largest size available. (2043 blocks)

If a smaller card is used, the cache's starting point is moved up to make use of the unused memory card area.

**Comment by BitPatty** [comment]
Alright, thanks for the quick reply.
