### ISSUE TITLE
Enhancement Request# Add dialup modem support.

### ISSUE THREAD

**Issue by lazareth241** [FIX94/Nintendont#555]
Sorry, I'm assuming that my last message was just a dumb idea that was tried already on the BBA thread.  Perhaps the issue is BBA support.

While I was looking up on how to get devolution (the clearly inferior GC emulator by now) working on my Wii U for some good old PSO online play, I realized that devolution doesn't use BBA for PSO, it uses modem support.  Would it be possible to add modem support? I know the technology is super outdated but that might make it easier to emulate?

**Comment by carnage702** [comment]
devolution or nintendont arent gc emulators ...

**Comment by RevoltsRevolution** [comment]
I really would like to see that feature too. And emulator or not, the inferior app does it and Nintendont does not. Still it seems to be in the "yet to come" section so my hopes are still there ;) I only softmodded my wii u for pso so it would be awesome to have a working version
