### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by eggsamillion** [FIX94/Nintendont#556]
Is there a way to remap the controls because on most of my 3rd party Wii classic controllers I cant slightly press with them because they aren't built with the Gamecube triggers/bumpers. In other words, if I wanted to run and spray in Mario Sunshine I couldn't because it's defaulted to press in all the way. Otherwise this app is perfect and I thank you for that.

**Comment by carnage702** [comment]
you can press zl+l fir mid press or zl+R for r mid press.
