### ISSUE TITLE
Sudden black screen after loading Nintendont from Homebrew Channel on Wii

### ISSUE THREAD

**Issue by clementine15** [FIX94/Nintendont#558]
Recently, I have had an issue where I get a black screen after loading Nintendont from the Homebrew Channel on my Wii. This issue has never happened before, and I could always play games without hassle. How do I fix this?

**Comment by carnage702** [comment]
maybe your nintendont boot.dol got corrupted or ninconfig.bin file, try redwnload the latest boot.dol and deleting your ninconfig.bin and even a controller.ini if you have one.
