### ISSUE TITLE
(request for fix 94 ) usb hid

### ISSUE THREAD

**Issue by juaco019** [FIX94/Nintendont#559]
First of all I want to thank for this excellent program, I would like to ask the developers for usb support for more than one control, we have many wii without gamecube ports and every day it becomes more complicated to find wii accessories, if possible enable USB controls for more than one player would be many who would be deeply grateful (especially those fans of racing games and fights to play as a family), finally to thank the entire team of nintendont for their work every day go improving this excellent program, few write it but we are thousands who are deeply grateful, blessings

**Comment by spielvan** [comment]
juaco019 an interesting idea, the retroarch of the wii got that it supports more of a control of ps3 by usb, through a usb hud, connected to one of usb ports of nintendo wii, who knows with nintendont not to do the same .
