### ISSUE TITLE
(request) fix widescreen for paper mario the thousand year door pal

### ISSUE THREAD

**Issue by diigsol** [FIX94/Nintendont#560]
the actual widescreen for this game have some issues.

**Comment by carnage702** [comment]
nintendont uses a general widescreen ahck which means it doesnt work perfectly with all games, some games need custom widescreen hacks so you can just use cheats from dolphin and use it on paper mario
https://wiki.dolphin-emu.org/index.php?title=Paper_Mario:_The_Thousand-Year_Door#16:9_Aspect_Ratio_Fix
