### ISSUE TITLE
Nintendont Freezes After Loading The Sims 2

### ISSUE THREAD

**Issue by KayK567** [FIX94/Nintendont#561]
I'm using an Usb Stick for holding my games, and when I load The Sims 2 sometimes it freezes on the game choosing screen or it will freeze loading the game. Sometimes if I'm lucky the game up starts up, but after that my wii shuts down. I dont know what the problem is!! It's only with that game! I have 6 or 7 other games on there, and The Sims 2 is the only game that freezes!

**Comment by carnage702** [comment]
say your nintendont version, all your nintendont settings and your sims 2 md5 value for the iso.

**Comment by KayK567** [comment]
My nintendont version is v5.481, my settings is everything default besides memcard emulation thats on. The MD5 value of the iso is "dc5038fa00bcf4a7c507cd6a92fb3429".

**Comment by carnage702** [comment]
manny people think they have default when they dont, take a picture of it or write your settings.

**Comment by carnage702** [comment]
also you probably have a badly created save file for the game  go to your usb and deletete the save file inside saves folder it should be called something like  G4ZE.raw delete it.

it seems your save file got created corrupted imo.

**Comment by KayK567** [comment]
- Cheats Off
- Debugger Off
- Debugger Wait Off
- Memcard Emulation On
- Cheat Path Off
- Force Widescreen Off
- Auto Boot Off
- Unlock Read Speed Off
- OS Report Off
- Drive Access Led Off
- Log Off
- MaxPads 4
- Language Auto
- Video Auto
- Memcard Blocks 251
- Memcard Multi Off
- Native Control Off
- Video Width Auto
- Screen Position 0
- Patch Pal50 Off
- TRI Arcade Mode Off
- Wiimote CC Rumble Off
- Skip IPL No
and okay I will delete the .raw file.

**Comment by carnage702** [comment]
considering everything seems good i can only think its the save file sometimes the memory card can be created badly.

**Comment by KayK567** [comment]
Okay I'll go try, and start the gameup! I will tell you if problems seem to continue! Thanks

**Comment by KayK567** [comment]
Thank you so much!!! I started up Sims 2, and it worked!! My Wii didn't shut down or freeze! Thank you for helping me.

**Comment by carnage702** [comment]
no problem, glad it worked, remenber anytime a game does something wierd it can be forced settings imcompatible with said game, bad iso or  a bad save file.

**Comment by KayK567** [comment]
Okay I will keep that in mind!
