### ISSUE TITLE
Can't boot JPN Pokemon Colosseum Bonus Disc [PCSJ01]

### ISSUE THREAD

**Issue by msmikesc** [FIX94/Nintendont#563]
So my overall goal is to successfully follow the first part of these instructions I found:

https://gbatemp.net/threads/finally-hack-for-japanese-colosseum-bonus-disc-for-us-games.253401/

I have an ISO for the JPN bonus disc that boots in dolphin.

However, trying to boot it through Nintendont gives the following error.

CheckForMultiGameAndRegion failed: 2

Unable to read the disc header.

I've tried to load both an unmodified iso and the iso with the three hex edits mentioned in that link, and both give the same result.

I have booted other games using Nintendont before, I'm using my original release USA wii.

Not sure if my ISO is bad somehow, Nintendont is getting confused by the weird game id (why does it start with a P?), or if I'm just doing something wrong.

Is there a way to hex edit the disc header to work?

**Comment by carnage702** [comment]
obviously nintendo boots games with region using the header, if you change the header nintendont will apply the patches badly, since your getting an jap game wich is ntsc and alling it P which is pal its trying to boot the game as if it was a pal game, with E it might work since usa and jap are both ntsc region.

**Comment by msmikesc** [comment]
Ok, just checked the MD5 for my unmodified iso and it matches with the MD5 found here: http://redump.org/disc/26012/

So my iso is good at least. Still get the CheckForMultiGameAndRegion error though.

**Comment by carnage702** [comment]
what version of nintendont are you using? also what  settings?

**Comment by msmikesc** [comment]
Using version 5.481

Setting

Cheats off
Debugger off
Debugger wait off
memcard emulation off
cheat path off
force widescreen off
force progressive off
auto boot off
unlock read speed off
osreport off
wiiu wide screen greyed out and off
drive access led off
log off
maxpads 4
language auto
video auto
native control on
video width auto
screen position 0
patch pal50 off
tri arcade mode off
wiimote cc rumble off
skip ipl no

**Comment by carnage702** [comment]
what are you using to load the game ? sd?usb? did you ever used other games or first time nintendont?

i see you dont have memoryc ard emulation set to on wich measn your using real memory card? jap games dont save well on same memmory card as usa and pal games do to diferent alphabet and such.

**Comment by FIX94** [comment]
error 2 is this:
https://github.com/FIX94/Nintendont/blob/master/loader/source/main.c#L265-L271
meaning it could not properly read the file, delete it, do a checkdisc on your device and copy it over again, something must've went wrong when initially copying over the file. If it still does not work afterwards, try another storage device.

**Comment by carnage702** [comment]
probably partition issue or not fat32?

**Comment by msmikesc** [comment]
Ok yup, that SD card I was using was the problem, tried another one and it booted.

I wasn't able to get my hex modified copy of the bonus disc to find the US Colosseum save on my real Gamecube memory card, but I was able to get it to work with Memcard Emulation.

Just in case anybody else finds this later, here's the steps I took to get this to work.

Step 1: Open your Japanese Bonus Disc ISO in your hex editor of choice.
Step 2: Replace the following hex offsets with the capital letter 'E' (or 'P' if you have a PAL copy of Colosseum): 29AB8003, 29F4FEBB, 29F50AC3.
Step 3: In Nintendont settings, change Memcard Emulation to On and Memcard Multi to On
Step 4: Run the Colosseum Disc and the JPN Bonus Disc once to create the memcard raw files, ninmem.raw and ninmemj.raw.
Step 5: Make sure your save file is complete with all 48 shadow pokemon purified, and have at least one party slot free in-game.
Step 6: Inject your Colosseum save file into the JPN memory card. I used dolphin for this, it has a GC memory card manager.
Step 7: Boot the game, Press A to proceed through the menus until you arrive at a screen with two options. The Shrine should be the right option, select it. A cutscene will play featuring Celebi, and you'll be told in Japanese that Celebi is now in your Colosseum party!
Step 8: Export the save from the JPN card and into the other card.
Step 9: Start up Colosseum and check your party. You should have a genuine Ageto Celebi!

I was also able to get this to work using a similar process in Dolphin, but only with the memory card set to GCI Folder, it wouldn't work with the regular memory card setting.

**Comment by FIX94** [comment]
just so you know the formatting on japanese and non-japanese memory cards is different, nintendont will decide which one to use depending on the internal game region, thats why your non-japanese card did not work, good thing you didnt format it or anything, I remember doing that way back when I didnt know there was a difference...
