### ISSUE TITLE
Nintendont froze my wii u loading screen after exiting

### ISSUE THREAD

**Issue by sonic78fast** [FIX94/Nintendont#564]
I'm having an issue too. I exited mario kart double dash on my wii u by powering it off. Then when I turned it back on, after i click to login with my mii, nothing loads and the background still play music and background move. I have to power it by unplugging it since it freezes when using the power button.

**Comment by carnage702** [comment]
nintendont does not do anything at all to the wiiu menu or vwii menu, also if you dont have the latest 581 version of nintendont there might be freezing stuff.

**Comment by sonic78fast** [comment]
I do have the latest version. This is the first and only time this happen right after I played mario kart double dash using the nintendont forwarder. I played it many times in the last 6 months and I never encountered anything like this. What could be the possible other ways to fix this?

**Comment by carnage702** [comment]
probably something went coorrupt on your wiiu i dont know, if you cant shutdown wiiu on wiiu mode even something went corrupt on your nand .

**Comment by sonic78fast** [comment]
Everything is fixed now. It had nothing to do with the nand or Nintendont. It just needed to stay unplugged and off for a couple of days. Everything is working good as new.
