### ISSUE TITLE
WARNING: USB FAT device could not be opened.

### ISSUE THREAD

**Issue by Idunno1** [FIX94/Nintendont#565]
So, I decided to try out Nintendont with a Seagate Expansion Drive, and I get the error, stated word for word in the title. I am using the Jan 23, 2018 build on vWii. I also heard some odd beeping sounds coming from the hard drive itself, which might be the reason, but I don't know, I'm not a programmer. Also, should I format the drive? I don't have anything on it.

**Comment by carnage702** [comment]
does your hdd have y cable or its own power supply?

**Comment by Idunno1** [comment]
I don't know what a Y cable is, but I know it doesn't have a power supply, and the cord that came with it is USB male on one end and the part that connects to the drive itself looks like 2 cords shoved together.

Hope you can make that out.

**Comment by carnage702** [comment]
wiiu has an handicapted power supply so it needs to have its own power supply or the 2 cords connected to the wiiu itself, also your hdd must be fat32 to work with nintendont and only with nintendont started from vwii, if you are using a wiivc inject on wiiu menu usb does not work from wiiu menu only from normal vwii.
