### ISSUE TITLE
Eternal Darkness Sound Crackling?

### ISSUE THREAD

**Issue by Markeron** [FIX94/Nintendont#566]
Eternal darkness has weird sound issues, it makes scratchy noises. Tested with other loaders with no issues. Any idea?

**Comment by carnage702** [comment]
are you using an sd card to load the game or usb? what version of nintendont are you using? what are your settings?

played the game up too half and never heard a single crackling.

**Comment by Markeron** [comment]
I use USB to load games, the latest version of Nintendon't, my settings are default except unlock load speed on and memory card emulation, oh and video mode force pal60(deflicker)      

Are you sure you had no problem, because if you do. it's from my end, Normally scratching start at the very beginning of the game and comes and goes regularly. Since I can boot it with Dıos it's not such a big deal, I just wanted to let you know but only a small group of people have this problem it seems.

**Comment by FIX94** [comment]
eternal darkness has audio streaming in its intro, you probably have a broken iso file or something, make sure to load clean iso files for games that include audio streaming to get proper audio playback.

**Comment by Markeron** [comment]
@carnage702 I tried the settings you suggested it's the same. 
@FIX94 Today I tried with a different iso and it does make scratchy noises again. Maybe that iso was bad, too. It's interesting that the sound issue only exist in Pal versions, though. Ntsc version hasn't that sound problem it seems, runs fine.

**Comment by carnage702** [comment]
you checked the md5 of the iso to see if its a good iso and compared it with redump?

**Comment by Markeron** [comment]
Ah, you guys ARE right. md5 did not check out. Bad iso, then. Sorry to bother you without checking it first. 
I guess I've download the same bad iso three times.

**Comment by carnage702** [comment]
nintendont is much more picky than dolphin so yeah you need a good iso matching md5 with redump, i always check the md5 before anything else.

**Comment by Markeron** [comment]
From now on I'll do the same

**Comment by animekai** [comment]
hi, can you tell me were you get the md5? or can you attach it here? my copy of Eternal Darkness pal version sounds with a lot of noise, im trying to download another iso but i cant find the md5 to ensure if is the corrrect iso

**Comment by carnage702** [comment]
> 
> 
> hi, can you tell me were you get the md5? or can you attach it here? my copy of Eternal Darkness pal version sounds with a lot of noise, im trying to download another iso but i cant find the md5 to ensure if is the corrrect iso

redump is where you find it 
http://redump.org/discs/quicksearch/eternal-darkness/

also crackingling might  be due to poor speed usb/sd since eternal darkness is an audio streaming game so it requires speed, or you may even have forced settings that are slowing the read speed.

**Comment by carnage702** [comment]
> For me the crackling audio problem was caused by the GPU: in fact, I switched from OpenGL to (at least) DirectX11, selecting the GeForce (by default was using the integrated one), but nothing happened APPARENTLY... the real cause was that I didn't plug the power cable, so it was not supply energy to the GeForce -.-' . Another reason was the v-sync, that slow down the GPU and causing the issue again. So turned it off.

this is nintendont it runs on wii or wiiu nothing of those things are even options or possible on wii/wiiu...
