### ISSUE TITLE
Why haven’t these fixes been implemented to Nintendont Yet?

### ISSUE THREAD

**Issue by YellowHoneyBear** [FIX94/Nintendont#567]
Okay, so the first issue is with certain games making a buzzing sound on selecting different things. For example in Super Smash Bros. Melee whenever you pick a character it will sometimes make a buzzing sound, I noticed that it seems to happen more when there is more then 1 controller connected.  I heard it also happens in Other games like Fire: Emblem Path of Radiance.  Now apparently someone has fixed it and even released there own version of Nintendont

Here’s a video that the guy made showing it the fix. 

https://m.youtube.com/watch?v=CuLpGCiV57I

Secondly is haveing two virtual memory cards one for Slot A and one for Slot B still being considered for official builds?

**Comment by carnage702** [comment]
that guys "fixes" were merged with official ninteno so if you are on the latest 481 and it still buzzes then those fixes didnt fixed anything.

as for mcemu for slotb that still hasnt been asked for merging by the author so ask him.

**Comment by GerbilSoft** [comment]
Slot B was merged in v5.463. It's not well documented on how to use it, though.

To use Slot B, you need to create a second memory card file named e.g. GALE_B.raw (for Melee) or ninmemb.raw (for multi). The total size of both A and B must not exceed 16 MB; if it does, Slot B will be silently ignored.
