### ISSUE TITLE
Gamepad GC for WiiU (Wired Fight Pad) always as controller 2 (player two) - Classic Wii

### ISSUE THREAD

**Issue by maxwelmota** [FIX94/Nintendont#570]
Hello!
When connect the GC wiiU controller in wii remote, running any GC game in Nintendont, the controller never function as "player one". If the physical controller GC pad is connect, the controller GC for WiiU is changing the LED order in wiimote. Even if you do not connect another physical controller on port 1 #GC, it is recognized as controller 2.

Thank you

**Comment by carnage702** [comment]
that is how it works there are priorites system
real gc ports on wii with bc >wiiugamepad>hid controllers>wireless controllers.

**Comment by maxwelmota** [comment]
All right! I understand it, but then isn't possible to play as "player one" playing with "wireless mode" using GC controller wiiU? I wish play Zelda WindWaker in this mode :)

**Comment by carnage702** [comment]
to use classic controller as player one simply say no to use the wiiu gamepad if using an inject and dont connect any hid controllers to the usb ports, that way wireless controllers will be player one.

**Comment by maxwelmota** [comment]
Ohhhh!!!! Thank you Very much!!!!!
