### ISSUE TITLE
Wii freezes and says waiting for nintendont

### ISSUE THREAD

**Issue by oshuncruz** [FIX94/Nintendont#571]
Im having a problem whenever i load new versions of Nintendont and when I run older versions of nintendont this doesnt seem to be an issue. I am running ios58 and im on firmware 4.1u 

![unnamed](https://user-images.githubusercontent.com/37771084/37874181-083889fe-2ff0-11e8-95f6-7870735fb68b.jpg)

**Comment by carnage702** [comment]
preetys sure your wii needs to be on 4.3

**Comment by carnage702** [comment]
there are ios stuff that can be outdated,  and such, i know nintendont uses stock official ios58 wich wasnt on older version of fw, no idea when it was introduced, but its the original one, some people still have old cios of ios58 and such because they didnt want to update the console and such.

**Comment by GerbilSoft** [comment]
58.23.30 is v5918, which is the original release. Nintendont is designed for v6176 (58.24.32), and a slightly later version for Wii U.

We should probably add an immediate error message if the wrong IOS subversion is detected.

**Comment by carnage702** [comment]
thats why updating to 4.3 is the easiest way.

**Comment by RS55** [comment]
@GerbilSoft Well I have the 58.24.32 and sometimes it happens to me too. What would it be then?

**Comment by carnage702** [comment]
if its waiting for nintendont and crashes its because its your sd card or usb device that is way too slow to respond to nintendont.

**Comment by baby-yoshi** [comment]
I have the same issue but I am on 4.3u
