### ISSUE TITLE
Zelda FSA with 2x GBA SP's and 2x OEM Nintendo GBA Link cables won't detect the GBA's

### ISSUE THREAD

**Issue by Drakonas** [FIX94/Nintendont#574]
Using the actual Nintendon't loader version v5.483 (Wii) from the Homebrew channel.

Built : Mar 18 2018 22:02:10
Firemware: 58.24.31

The only option I changed in settings is I enabled Native Control as per instructions for getting the GBA Link functionality to work.

I wish I could play the game disc I actually own, which I just bought the game and some cables to play this only to find my Wii disc drive has stopped spinning since I last used it. T^T I have ordered a replacement drive, hoping it will run from that but I can't test it.

Loading a compressed CISO, properly named (Game is reported working compressed on the compatibility list), loads the game just fine, but it will not detect the GBA's I have.

I am using two US release GBA SP's both model AGS-001 (AGS-USA) with two US release Zelda ALttP&FS carts, both model AGB-AZLE-USA (AGB-002)

Is there something I'm missing? I turn on the GBA's once I'm on the screen where it asks you to connect the GBA's and it just loads the carts from the GBA's.

**Comment by carnage702** [comment]
does your wii have gc ports? is your link cables legit? are you sure you have native set to on and didnt toogled it on and then exited nintendont before launching a agme so the setting can save?

**Comment by Drakonas** [comment]
I have an original model Wii (2006 with the original disc drive) with Gamecube ports. I double checked that native is set to on. It has been set to on even after restarting Nintendont. My OEM Link cables have the Nintendo logo with DOL-011 model number.

**Comment by Drakonas** [comment]
WELL.... Nobody told me that you're not supposed to have the official Link to the Past Four Swords cartridge in the cartridge slot. Someone told me I need the games... Ffs.

**Comment by Drakonas** [comment]
I swear the documentation on the GBA to GC link functionality is limited on the internet.
