### ISSUE TITLE
Black screen when loading games from USB HDD

### ISSUE THREAD

**Issue by lukasfink1** [FIX94/Nintendont#575]
Hello,
I have a problem with loading games from my USB HDD. When I load games from the SD card, they work fine, but while the games on the HDD are displayed at the menu and also the md5 calculation works fine on them, I get a black screen when trying to load them (I'm using default settings).
I tried to activate logging to get any useful information, but then it freezes at “Init DI...”.
The HDD has a LED that blinks on access, which is the case while it's frozen/blank.
The HDD has three partitions: The first is FAT32-formatted and contains my homebrew apps and my GC isos (They're 1:1). The remaining two are formatted with NTFS and contain nothing, that should influence Nintendont.
I use a Wiimote+Nunchuk combination as controller.
Also, when the screen goes blank, all LEDs on the Wiimote are on and it doesn't respond to any buttons pressed. Only the power and eject buttons works.
When I activate logging, even the power button doesn't work (I have to hold it to turn the console off). Additionally the Wiimote gets disconnected.

Thanks to everybody, who can help me with this issue and also thanks to the developers of this awesome application.

**Comment by carnage702** [comment]
partitions were always iffy.

is your partition table mbr and its your fat32 partition set to primary? also make sure your running the latest nintendont and not an outdated version, still there is no garante that your hdd will work sometimes some hdds just do wierd stuff and nintendont doesnt like them.

**Comment by lukasfink1** [comment]
Yes, I'm using an mbr partition table and the partition is primary (I also made it the boot partition, if you meant that). My version of Nintendont is up to date. I also tried reformatting, but it still doesn't work. Well, then I'll probably have to invest into a bigger SD card for now.

**Comment by Funnybunnym** [comment]
I also have the same problem. It seems to me that my wii just freezes, and I have to restart it. However, there is a chance that if I wait long enough (5 mins maybe), the game will start to load. After it loads though, it then sometimes freezes or it plays. It is very frusterating how only like 10% of the time it loads.
