### ISSUE TITLE
Super Smash Bros. Melee beeps CSS (PAL)

### ISSUE THREAD

**Issue by Catarax** [FIX94/Nintendont#576]
Super Smash Bros Melee (PAL) still freeze on CSS, after a fight with 3 players for example.

I think this fix is only for the NTSC release,
https://github.com/FIX94/Nintendont/commit/8f1ff3fdc6e85832d488825f71c6b218fd2014bf

**Comment by carnage702** [comment]
game never frooze at all that fix was just for some beeps that hepened when selecting characters on main menu, if your game is freezing is becuase you have bad iso or imcompatible forced setttings.

**Comment by SuperrSonic** [comment]
If it weren't for carnage702's post I'd have assumed the op was talking about a different issue altogether.
Isn't "freeze" associated with crashing, hanging, etc.? A crash typically involves a loud beep.

What https://github.com/FIX94/Nintendont/commit/8f1ff3fdc6e85832d488825f71c6b218fd2014bf changes is showcased in this video https://youtu.be/CuLpGCiV57I, if these are the beeps you hear, then yeah it didn't fix it. I am interested in knowing if it's true that it still beeps on just Wii U, I have yet to see anything truly definitive.

**Comment by Catarax** [comment]
Sorry I'm talking about the loud freezing/crashing beep of character selection, 
I have not experienced the small beep on Wii U at all.

I switched to the NTSC release actually, the CSS is much more stable, 

It literraly crashs the second/third time you got into it for the PAL version, I think it crashs more easily with multiple controller plugged.

**Comment by carnage702** [comment]
there is no crash , ssbm never crashed, so if its crashing you have bad iso/imcompatible settings, the small beep sounds when choosing characters are not crashes those are just inevitable, with less players less chnace obviously, if your pal version does indeed crash/freeze and its not just a beep sound when seletcing characters you have a bad iso or imcompatible forced settings.
