### ISSUE TITLE
I cant use any usb-hid controllers. 

### ISSUE THREAD

**Issue by matoomeeethis** [FIX94/Nintendont#578]
I cant get any controller at all besides the GameCube controller to work

**Comment by matoomeeethis** [comment]
No, its not set to native and no controllers work with USB. And my USB ports work because I can load my Wii games from USB.

**Comment by carnage702** [comment]
take a picture of your nintendont settings, also which hid controller are you trying to use?

**Comment by matoomeeethis** [comment]
https://www.amazon.com/PlayStation-4-Mini-Wired-Gamepad/dp/B076MQ34PQ and here's a pic
![image](https://user-images.githubusercontent.com/38028656/38449991-e52a690a-39db-11e8-9d79-01f2ff86847e.jpg)

**Comment by matoomeeethis** [comment]
Thanks! Good to know its a bit outdated... Also I thought that that ps4 controller used the same input as a normal ps4 controller, so thanks!

**Comment by carnage702** [comment]
ps4 is compatible with all hid controllers so yeah they dont need to be the same pid/vid and such so yeah you need to make your own ini.
