### ISSUE TITLE
Some issues with Melee

### ISSUE THREAD

**Issue by keystone76BMA** [FIX94/Nintendont#579]
I just started using this, and it's very impressive. But occasionally, while I'm playing, it will freeze and make a buzzing noise. Anyone else having this issue?

**Comment by carnage702** [comment]
you mean an actual crash? or just some tiny beeps when choosing characters?

if its an actual freeze make sure your not forcing settings, some settings can make games freeze also make sure you got an good iso with md5 checking with redump.

**Comment by XModxGodX** [comment]
I've been having the same issue too even when Nintendont was new. I don't know if this is necessarily the case but I've noticed it generally happens in menus and not exactly when in matches but it's still annoying...
