### ISSUE TITLE
Nintendont Forwarder black screen after Wii Logo

### ISSUE THREAD

**Issue by Ardi-san** [FIX94/Nintendont#581]
[Have low knowledge of the names and terms so sorry if I make mistakes]

I used the install files from WIIU USB Helper and placed the .dol in the correct place. After installing it and opening the Nintendont Forwarder with Mocha CFW on and then it just black screens after the Wii logo. Spent weeks trying to get it to work and nothing seemed to be successful. 

Works fine when I: open nintendont in vwii > go back to wiiu main menu > open haxchi > open mocha cfw > open nintendont forwarder.
For others it seems to work fine when they open nintendont forwarder after CFW.
Only forwarder I got to work perfectly was WiiSXR

**Comment by carnage702** [comment]
you sure you renamed the folders correctly? the fowarer looks for
SD:apps/nintendont/boot.dol

**Comment by Ardi-san** [comment]
Yeah I renamed it correctly.

**Comment by carnage702** [comment]
well take a picture of your sd card root, inside the apps folder and inside nintendont folder.

**Comment by Ardi-san** [comment]
In Root:
https://i.gyazo.com/575944d9e22dba5dcd7de6d50e4f0baf.png
In App Folder:
https://i.gyazo.com/1049e0ec1f6cfe5090fccba5d81c51d1.png
In Nintendont Folder:
https://i.gyazo.com/0aca6cfed4e35478387a4c27713b462b.png

**Comment by Ardi-san** [comment]
backup.backup was the old dol.

**Comment by carnage702** [comment]
my only guess is the fowarder itself was a corrupt install, go to system settings and uninstall it, and redownload and install again.

**Comment by Ardi-san** [comment]
Uninstalling and reinstalling with Wup Installer didnt seem to do the trick.

**Comment by carnage702** [comment]
are you using emunand or some wierd cfw?

**Comment by Ardi-san** [comment]
Im using the Mocha CFW I got from the app store

**Comment by carnage702** [comment]
well mocha does not mean if your using rednand or not, i just use cbhc and haxchi built in cfw, never used mocha, also are you sure your sd card is not locked?

also what version of nintendont does it display when you open vwii? actual number on top left corner.

**Comment by Ardi-san** [comment]
v5.483 (Wii U)

**Comment by carnage702** [comment]
dont use mocha, just use haxchi built in cfw and try it i guess, if all else fails try another sd card, your sd card might be the culpright too.

**Comment by Ardi-san** [comment]
Thanks for the help; I tried MattKimura's method since he got a similar issue and it worked out.
