### ISSUE TITLE
The message "INTI DI" pops up and then turns off my Wii

### ISSUE THREAD

**Issue by MarkTheFreak** [FIX94/Nintendont#582]
I try and boot a GameCube game of an USB Stick but as soon as I do, the message "INTI DI" pops up and then turns off my Wii console.

**Comment by carnage702** [comment]
make sure your running the latest version off nintendont, also not all usb devices are compatible, specialy usb sticks are very easy to not work with wii homebrew in general.

**Comment by MarkTheFreak** [comment]
It is the latest version, also when I first downloaded Nintendont, it worked perfectly but now it just fails to load a game.

**Comment by MarkTheFreak** [comment]
Alright.
