### ISSUE TITLE
A connection with virtual memory card with a real memory card

### ISSUE THREAD

**Issue by Soney-EZ** [FIX94/Nintendont#583]
Heya everyone! I'm not sure if nintendont can do it, but today I was trying to make the virtual memory card in (slot A) connect with a real memory card in (slot B) in Animal Crossing. As I was trying to go to a different town for some reason it did not recognize the real memory card (slot B). I'm not sure if I'm doing something wrong here but I'm guessing that if I'm using an emulated memory card it disabled slot B?, or I'm doing something wrong here?

P.s. Nintendont is an awesome Homebrew application and it has such potential too!

**Comment by carnage702** [comment]
cant be done, you either use emulated memory cards or real memory cards you cant use both at the same time.

**Comment by GB-CG** [comment]
@Soney-EZ You can use [GCMM](https://github.com/suloku/gcmm) to rip the save from your memory card and then try this (as said by GerbilSoft):

> Slot B was merged in v5.463. It's not well documented on how to use it, though.
> 
> To use Slot B, you need to create a second memory card file named e.g. GALE_B.raw (for Melee) or ninmemb.raw (for multi). The total size of both A and B must not exceed 16 MB; if it does, Slot B will be silently ignored.

**Comment by carnage702** [comment]
yeah but like i said either 2 virtual mc emus or 2 real mc cards, you can do one virtual and one real.

**Comment by Soney-EZ** [comment]
Okay I understand thank for answering! Also I heard about the slot B Problem with VMC. I forgot was the users name ( maybe two people is working on it?) but they been working on the dual virtual memory card project on nintendont and it's REALLY good! but im useing nintendont verison 5.483 will there be an update later on?
