### ISSUE TITLE
[Request] Switches to invert x-axis and y-axis

### ISSUE THREAD

**Issue by Catw3azle** [FIX94/Nintendont#586]
First of all I'd like to thank all the people who made Nintendont possible. Great work!
But one thing drives me bonkers, that I am not able to invert the x-axis and the y-axis of the analog sticks of the controller. Some games are unplayable for me because of that.
What I would like to have:

- The possibility to invert the x-axis and the y-axis of the right analog stick independent from each other
- The possibility to invert the x-axis and the y-axis of the left analog stick independent from each other

**Comment by TopTenTiger** [comment]
This would be a killer feature since many games especially from the Gamecube era suffers from this kind of customization. There's another issue posted on this topic: https://github.com/FIX94/Nintendont/issues/360
