### ISSUE TITLE
Nintendont MD5 Errors

### ISSUE THREAD

**Issue by Shirien** [FIX94/Nintendont#587]
I started recently, perhaps in the last week or two, having problems with Nintendont. Until then, it had worked like a dream. The problem began when my children went to load Mario Kart Double Dash; a game we've played countless times.

This time, however, we recieved a message saying that the 'MD5.txt' not found.
Bearing in mind, no changes or alterations to Nintendont, or even ROMs added, has happened since I put Nintendont on there.

When I add a MD5.txt file, it says that it needs to be calculated. It freezes at this point. With the MD5.txt files on the SD card, however, I'm able to at least select different games to attempt to load. Without an MD5.txt, simply moving the indicator error freezes Nintendont.

I've wiped the SD card and attempted a new install of Nintendont. Same issues. I've tried older versions of Nintendont, They allow me to play the ROMs, but when I attempt to go to settings to alter the 'emulate save slot' option, I am unable to select anything. I can click 'start' to return to 'load screen', but repetition of the aforementioned actions produce the same result. 

Any suggestions or ideas? Any information I can provide to help narrow this down, I will be glad to post, simply ask.

**Comment by carnage702** [comment]
maybe you got a corrupted save file, check in save folder and see if there arent any 0kb ones.

**Comment by Shirien** [comment]
It's not  a save file. This happens before the ISOs load. Nintendo loads and gives me a list of all the ISOs I have available. Before I can select them, I get MD5 errors. Interestingly, I get MD5 errors -before- I can select an ISO. Just moving to select one causes such an error and then it freezes. When I wiped to restart, I reformated my SD, (To verify, FAT32 at 64kb) and removed the save files, incase they -had- indeed caused some kind of error.

**Comment by carnage702** [comment]
well nintendont does not read md5s unless choosen to read them on settings menu, did you made a new config file? ninconfig.bin? and your sure you download every file fresh? because this seems there is a corrupt file somewhere even a controller.ini

also you got any usb stuff connected to the console?

**Comment by Shirien** [comment]
You know, I didn't think about there being an option to read MD5s. This happened when my kids did something, it's entirely possible that maybe the problem. That's what was throwing me off in the first place, we've NEVER had MD5 files at -all- in Nintendont. I was very much under the impression it didn't need it. No USB anything connected during this testing period, (every now and again, I might have something charging, but not for weeks). I'll check to see if I can get into settings and adjust the MD5 options.

Having said that, I also did complete wipe of the Nintendont I had on it, and re-installed it. Should that not have set all the settings back to default?

**Comment by carnage702** [comment]
depends, ninconfig.bin and controller.ini files are on the root of the device that has the isos and not inside the app folder.

**Comment by Shirien** [comment]
I wiped and reformatted the root device (in this case, my SD card) to clear all that, though. I took no chances regarding that and lingering settings, just in case.

**Comment by carnage702** [comment]
your isos are on sd too? or usb?

**Comment by Shirien** [comment]
SD. I don't have an USB drive, only thumb drives.  ScanDisk 16GB, as recommended by Nintendo.

**Comment by carnage702** [comment]
you sure the sd card is not loked?

**Comment by Shirien** [comment]
Alrighty, I'm going to go with 'Tentative fix' on this one.
I FINALLY managed to get into settings and adjust the controls for the GCN controllers. It APPEARS that the problem was the controllers. It -appears- that, without the settings in the Nintendont being set to allow GCN controllers, simply -touching- the GCN controller caused this MD5 problem. After removing the controllers from the Wii, I was finally able to get into the settings. (I did not think of the controllers being a problem, since they weren't being touched, simply plugged in.) In doing so, I changed the settings to allow GCN controllers. As of right now, it -appears- to be working fine. I will update as I learn more, whether positive or negative.

**Comment by carnage702** [comment]
there is no such thing as a setting to allow gc controller on nintendont unless your using some  front end or very outdated nintendont

the only setting current nintendont has that affects controllers is 
native on or off wich reads the wiiu gc ports only and disables all else
max controller 1-4 wich reads  controller 1 to 2 or just 1 or all 4 at all times.

**Comment by Shirien** [comment]
That's it: the 'native on or off'. Turning it from 'off' to 'on' seems to allow it to work.

**Comment by Shirien** [comment]
No controller.ini, and -nothing- connected to USB ports. I have the Wii Controller, and two GCN controllers plugged into their ports. That's all. SD card wiped and reformatted, the -only- thing on it is the boot.dol and meta.xml, in it's apps folder, and MarioKart DD, Luigi's Mansion, and Animal Crossing isos, in their appropriate folders, along with a newly created save folder that MKDD just made when I tested. That's all that's on the SD card.

**Comment by carnage702** [comment]
hmm got any extension connected to your wiimote?

**Comment by Shirien** [comment]
Nope. I leave the nunchuck off unless the game specifically requires it.

**Comment by carnage702** [comment]
and both the wiimote and nunchuck are official products? or fake/3rd party?

**Comment by Shirien** [comment]
Official products. I do have a 3rd party one, but for some reason it almost never works, so we don't use it.

**Comment by carnage702** [comment]
all i can think off is nintendont often has issues with 3rd party stuff and your kids used the 3rd party one whcih clicked a bunch of random buttons and did something to the settings screen, you should turn native off again and test.

**Comment by Shirien** [comment]
I will do that, after they play for a little while. I know that some settings were messed with: that's the only conclusion I can reach. A whole bunch of accidents all at once. I shall test further with this to see if I can recreate the problem, now that thinking the native is the fix. Once I'm able to do such, I shall report my findings.

**Comment by GerbilSoft** [comment]
Regarding the MD5 functionality: Are you sure it's requesting "MD5.txt"? The MD5 calculator I added a while back uses a file called "gcn_md5.txt", and it's only used if you press X/1 on the game list, then press A to calculate the MD5.

**Comment by victo103** [comment]
I’m having the same issue. I boot up Nintendont from HBC, and I’m able to select SD or USB. Once I make the selection, I am only able to move selection and once I do, it selects the game and says MD5 is calculating, but it is frozen. 

As I attempt to fix the error, the other error I’m given is MD5 Database error: gcn_md5.txt not found, and freezes there.

**Comment by GerbilSoft** [comment]
This really doesn't make sense, since the MD5 code should only ever be triggered if you go to the Game Info screen. I'll try it again sometime this week to see if there's anything that might've gone wrong.

**Comment by kraken-star** [comment]
solo tienes que mover la pestaña de la sd, es lo que impide que la wii cree la carpeta de guardado, y por eso no puedes jugar
