### ISSUE TITLE
resident evil 3 nemesis pal

### ISSUE THREAD

**Issue by Masana1** [FIX94/Nintendont#588]
Hello everyone, 
I have a weird problem with Resident Evil 3 Nemesis Pal version.
When I activate the pal60 in the game I get n black screen on the tv but the screen of the gamepad works,
when I pass it in pla50 the game functions on the 2 screens ... Is this a bug?
Thank you for enlightening me. 

Masana 

ps: sorry for spelling this is a google translation.

**Comment by carnage702** [comment]
im gurdding yur tv does not like getting a pal 60 signal while gamepad screen acepts all signals, did you ever played an european game on pal 60 on your tv before?

**Comment by Masana1** [comment]
yes I configure abituelment my games in pal 60 ma tv is a samsung led

**Comment by carnage702** [comment]
no idea, maybe that games has a diferent than normal pal60 resolution wich your tv does not support, there is no code to make the game appear on either screen its the same codding going to both and nintendont does not control the codding that is wiivc inject codding, so the same code is going to your tv and gamepad, if gamepad shows the game then the code is good, if your tv doesnt its becuase it does not support that game resolution at pal60, do you have any other tv you could try it on?
