### ISSUE TITLE
changing video width cause Resident Evil 4 to crush on load

### ISSUE THREAD

**Issue by Arctic7** [FIX94/Nintendont#589]
I am using Nintendont on my WiiU.
The game that would crush is Resident Evil 4 NA Version(G4BE08).
Setting everything to default except Video Width would cause this game to crash on start up.
If I change Video width back to auto or 640, the game would run normally.
But since Nintendont on WiiU is not strictly 4:3 or 16:9, the image is ofen a little narrower when looked, so can you look at it? Thanks anyway.

**Comment by carnage702** [comment]
video width crashes alot of games becuase its a hack, and you would need to make a per game hack for most games so yeah use it only for compatible games or use your tv and adjust the image.

hacks like forced videomodes,widescreen and video width are hacks that break some games funcionality theres nothing to be done for them, if you fix them for one game you break them on another 20 and so on.
