### ISSUE TITLE
Wii Keeps turning off

### ISSUE THREAD

**Issue by CVFireDragon** [FIX94/Nintendont#590]
I launched SMS and it worked fine. Then, I turned on virtual memory card and tried to launch SMS. It hung at a screen and I waited for a good 30 minutes but it was still there. So I reset my Wii, launched Nintendont and tried to launch SMS but my Wii turned off. Every single time I try to launch any game, it does this.

**Comment by CVFireDragon** [comment]
![img_1687](https://user-images.githubusercontent.com/39099814/40279517-ffb13210-5c11-11e8-8acc-08e9308483cf.JPG)
This is the screen it hangs on btw

**Comment by carnage702** [comment]
seems it got corrupt files, check your device for corrupted stuff.
