### ISSUE TITLE
Only reads from the 2nd USB port on Wii

### ISSUE THREAD

**Issue by danylopez123** [FIX94/Nintendont#591]
I have my GameCube games on an USB i plugged on the 1st USB port from my Wii, but it won't read them unless i plug it back to the 2nd port, and im using 2 USBs to use them for USB Loader GX.

They do read on USB Loader GX from the 1st port but they will fail to load if i try loading them from USB Loader GX.

But the problem: If i plug that USB to the 2nd Port, it won't read the games on USB Loader GX but they will read on Nintendont and they will load with no problems.

**Comment by carnage702** [comment]
that is not a nintendont issue... go to usbloadergx options and choose both usb ports isntead of port 0 or port 1 that is the default option, nintendont reads from any port usbloadergx doesnt it has options, on wiiu you can even plugg nintendont on front usb ports.
