### ISSUE TITLE
Sonic Adventure 2 Chao Regions?

### ISSUE THREAD

**Issue by nickel1817** [FIX94/Nintendont#592]
I'm a fan of SA2, and the chao garden really brings me back, so when I found out there was a demo disc that let you download a Tails chao, Knuckles chao, and Amy chao onto your Gameboy Advance I had to do it. so I have the ISO for the demo disc boot it up, and downloaded one of the chao on my Gameboy Advance. So far so good. I boot up an NTSC-J Japanese ISO of SA2 and when I try to transport the chao to SA2, the game doesn't recognize a chao in there. It knows the GBA is connected, it shows a GBA slot where a chao would be, but on the GBA there's no transporter visible like their normally is, and there's the chao to pick up on the Wii's screen. This same problem happened when trying to transport the chao to an NTSC-U American copy of the game, but I just don't see the problem here with a Japanese copy. Do I need a Japanese GBA too?

**Comment by nickel1817** [comment]
The demo used to download the chao was only released in Japan, only a Japanese ISO exists.

**Comment by carnage702** [comment]
you probably need a jap gba sonic game really.

**Comment by nickel1817** [comment]
I thought that too, but it won’t drop the chao in the GBA if there is a game inserted, it installs a Japanese Tiny Chao Garden. Having a game in creates some barrier between the two.

**Comment by carnage702** [comment]
probably never meant to be transferable to main gba games becuase their data isnt there.

**Comment by nickel1817** [comment]
Over on GBAtempt is a fix to this issue for anyone who is interested, https://gbatemp.net/threads/region-patch-the-sonic-dx-chao-distribution-disc.508216/
