### ISSUE TITLE
Confusion with cheats (Low Priority)

### ISSUE THREAD

**Issue by nickel1817** [FIX94/Nintendont#594]
I've looked up many ways on how to get cheats working with Nintendont, but I haven't got any of those methods to work. Putting the .gct (which is already in ocarina format) in a cheats folder, and turning on cheats didn't work. I tried making a folder with the game.iso format, and the iso + plus the .gct cheat inside the folder, but the application doesn't seem to recognize a folder that's in the games folder. I'm just at a lost, I have no idea what I'm doing wrong, any help is appreciated, although this issue is low priority.

**Comment by GB-CG** [comment]
I'm assuming your cheat folder is `cheats`, right? it should be `codes` . The codes folder only works on the root of the drive.

**Comment by Kirbytone** [comment]
Hi. I'm looking for cheats for Pokemon Colosseum, and there is none. I want to make all pokemon shiny, and have infinite master balls and time flutes. Can you find a .gct file with those?

**Comment by GB-CG** [comment]
Better to ask here: https://gbatemp.net/threads/nintendont.349258/
