### ISSUE TITLE
Metroid Prime Randomizer crashes on boot

### ISSUE THREAD

**Issue by NElectron** [FIX94/Nintendont#595]
I've been trying to play the Metroid Prime Randomizer (this one: https://randomizer.metroidprime.run) using Nintendont, however, after showing the Nintendo logo for a split-second, it will crash showing a green screen. I tried loading the original Metroid Prime rom to see if it was a bad rom that I might be using for the randomizer or something like that, but it boots just fine. The randomized game runs fine on the Dolphin emulator. 

Is there a way to resolve this with different settings, or is it another problem entirely?

**Comment by carnage702** [comment]
many hacks don't work on nintendont, nintendont is not an emulator is more like an interpreter that runs gc games on wii mode and by doing that it changes alot of addresses due to the wii memory addresses, which if the hacks targets any of those addresses it wont work.

so to fix this you would need a coder to see which addresses it changes on normal metroid and where those addresses are in nintendont.

**Comment by NElectron** [comment]
Thanks for the response! I also went ahead and used an older version of Nintendont and it works fine.  But thanks nonetheless for the explanation.

**Comment by carnage702** [comment]
probably a version where a memory address wasn't moved and was latter moved for more compatibility i guess.

**Comment by NElectron** [comment]
The issue has been fixed by the [mod's iso tool](https://github.com/aprilwade/randomprime/releases/tag/0.2.1). Turns out the issue was related to a .pak file with 0 resources.

**Comment by etaylor8086** [comment]
Looks like it's a bug with a zero-length DMA transfer according to the author. [Here's the issue I opened on this bug](https://github.com/aprilwade/randomprime/issues/5) last week.

**Comment by etaylor8086** [comment]
I'll just copy/paste the relevant comment from AprilWade:

"More details for the curious: I believe the crash is cause by a bug in
nintendont (introduced in 5.477 as mentioned above). A bit of background: In
order to save space in main memory (MRAM), Metroid Prime stores metadata about
the contents of the Pak files in the DSP's memory ARAM, only copying parts of
it to MRAM when necessary. Nintendont's implementation for the DMA transfer
request appears to crash when a length of 0 is given. So, when a pak contains
0 resources, the table containing its metadata is empty, and a DMA transfer
with length 0 made."

**Comment by carnage702** [comment]
nintendont has exceptions lists for dma values wich if a game changes he isnt on the exception list obviously.
