### ISSUE TITLE
P1 Controller randomly disconnects NFS Carbon(wiiu gc adapter only)

### ISSUE THREAD

**Issue by MhxAir** [FIX94/Nintendont#598]
So this is the first time I've ever had this issue. I'm using Nintendont on vWii U, I don't have any settings changed from default, every game has always worked fine. I decided to dump NFS Carbon, it's a 1.35gb full iso. It plays, but at any random moment it will eventually pause and say player 1 controller is disconnected. I'm using an official gamecube adapter, and it works with all other games. I figured it was my dump, so I downloaded an iso, same issue. I downloaded the Europe iso, same issue. The downloaded isos were also full size 1.35gb uncompressed. Nintendont claims NFS Carbon is fully compatable. Like I said, all settings should be default from Nintendont install. Any ideas?

The only thing I found on it was from 2014 that says a 520mb fix should make it work, but I have no idea what they're talking about.

<a href='https://postimg.cc/image/eeqiuejbf/' target='_blank'><img src='https://s33.postimg.cc/4hfi1cbpr/20180726_215358-1.jpg' border='0' alt='20180726_215358-1'/></a><br /><a href='https://postimages.org/'></a><br />

**Comment by carnage702** [comment]
take a picture of your nintendont settings, also check your iso md5.

**Comment by MhxAir** [comment]
Forgot about this topic, added image.

**Comment by carnage702** [comment]
well yoour nintendont is very very outdated, just download the latest version.

**Comment by MhxAir** [comment]
Well I've been told some of the newer versions have issues, so I neglected to upgrade. What's the most recent stable version?

**Comment by carnage702** [comment]
who ever told you that is a moron lol, the latest one works perfectly, your basically behind 83 versions...

latest one is 483
https://github.com/FIX94/Nintendont/blob/10f52316a67d955e2c9608ae6cefc277ccfb8abe/loader/loader.dol?raw=true

just rename it to boot.dol and replace yours.

**Comment by MhxAir** [comment]
Alright, for whatever reason, it wouldn't update from the Wii loader, so I'll do it manually and see if Carbon works on this version. I appreciate it.

**Comment by CHA0SHACKER** [comment]
I have the same problem with both NFS Most Wanted and NFS Carbon. I'm using the NTSC version of both games. Official WiiU GameCube controller adapter and an original NGC controller. The nintendont version is 6.489

**Comment by carnage702** [comment]
try the 490 version, maybe the hid issue was fixed maybe.

**Comment by CHA0SHACKER** [comment]
Just tried it. Sadly it still does happen after around 15 minutes of gameplay. Is there some way i can provide you with debugging infos. A log file or something?

**Comment by carnage702** [comment]
does this happen with all type of controllers or just hid?do other hid controllers besides wiiu gc adapter do this? do bt controllers also get disconnected?wiiu pro/wiiugamepad/wiimote+CC, wiimote+CCpro?

one needs to know if first its a bug with just wiiu gc adapter ini file or all hid, and second if it also does happen with bt controllers to see if its a game issue or a controller code issue, if you can narrow that down it would help.

first try using a bt controller if it never disconects you can already tell its an hid issue.
second try another hdi besides wiiu gc adapter to see if it affects all hids or just the wiiu gc adapter.

**Comment by CHA0SHACKER** [comment]
So far it only happens with the WiiU GC Adapter + GC controller. Haven't tried other HID Controllers so far. Will try with a PS3 controller later. WiiU Pro Controller und Wii Remote + Classic Controller work fine...

**Comment by carnage702** [comment]
> 
> 
> So far it only happens with the WiiU GC Adapter + GC controller. Haven't tried other HID Controllers so far. Will try with a PS3 controller later. WiiU Pro Controller und Wii Remote + Classic Controller work fine...
> Also it really only seems to happen in NFS: Most Wanted and NFS: Carbon. All other games are fine too. It's really weird...

there are alot of games that use diferent controller codes and nintendont even has some exceptions for them like 007 russia and so on, so yeah we determined its not the controller code in general atleast since bt controllers work fine acording to you, now we need a confirmation a regular hid controller like dualshock 3 doesnt get this issue or not, too see if its a general hid code error or just some wiiu gc adapter error alone.

when you try please post the results with ps3 controller.

**Comment by CHA0SHACKER** [comment]
I just played a session of around 3h with a PS3 controller. Absolutely no issues. Works like a charm

**Comment by carnage702** [comment]
> 
> 
> I just played a session of around 3h with a PS3 controller. Absolutely no issues. Works like a charm

so its confirmed its a wiiu gc adapter only issue hmm, might be an issue with refresh rate the ports do or something that even if its a split second the game might think it was disconnected if its checking fast enough

**Comment by carnage702** [comment]
> 
> 
> I just played a session of around 3h with a PS3 controller. Absolutely no issues. Works like a charm

Can you try this dol? i just added both need for speed carbon and most wanted to the 007 russia exception wich reports the controller as always connected, not sure it it will help this with wiiu gc adapter or not tbh if you can give it a try and let me know the results, here it is

http://www.mediafire.com/file/4zq78a8algx8vtm/test_nfs_nintendont.zip/file

**Comment by CHA0SHACKER** [comment]
Have now played around 2 1/2h of Most Wanted and then around 1h Carbon to be sure. Seems to be working now. Thanks!

**Comment by carnage702** [comment]
> 
> 
> Have now played around 2 1/2h of Most Wanted and then around 1h Carbon to be sure. Seems to be working now. Thanks!
> Now it just needs to be integrated into the main version. Or should I use the test version you gave me for longer?

nice to know i will sometime push a 491 version with this fix in the future.
