### ISSUE TITLE
Nintendont Failed To Load IOS58

### ISSUE THREAD

**Issue by GreyD94** [FIX94/Nintendont#599]
Nintendont Loader v5.483
Built: March 18th, 2018

Failed to load IOS58 from NAND:
IOS_Open("shared/content.map") returned -102

[IOSsyscheck.log](https://github.com/FIX94/Nintendont/files/2173296/IOSsyscheck.log)

I just don't understand what's wrong. My SD has the meta.xml and icon.png downloaded from [https://github.com/FIX94/Nintendont/tree/master/nintendont](url). The boot.dol was downloaded from a link in this thread -> [https://sites.google.com/site/completesg/backup-launchers/gamecube/nintendont](url).

Anybody have any idea what could be wrong? Is there any further information I can provide that might assist in finding the solution?

**Comment by carnage702** [comment]
nintendont needs the official ios58 latest version, if you installed an cios 58 it wont work.

**Comment by czarjar** [comment]
I was having the same problem on my Mac, not sure if you'd have the same issue with windows. My Mac was automatically adding .txt after meta.xml, so I just removed the .txt & it worked fine.
