### ISSUE TITLE
BBA Stuff

### ISSUE THREAD

**Issue by fancythedeveloper** [FIX94/Nintendont#601]
Is it possible to integrate BBA features. I'm assuming this is gonna require testing in 4 areas:
1. Nintendont & GC LAN
2. Nintendont & Nintendont (2 Wiis) LAN
--------------------------------------------------
(Xlink Kai)
3. Nintendont & GC Online LAN
4. Nintendont & Nintendont (2 Wiis) Online LAN

**Comment by networkfusion** [comment]
Duplicate of #144 !
