### ISSUE TITLE
Slot B no more supported

### ISSUE THREAD

**Issue by Catarax** [FIX94/Nintendont#603]
Someone on reddit recommended me to use an older version for getting Slot B support.
https://www.reddit.com/r/GCNintendontLoader/comments/8mgnp9/slot_b_memory_card_multi_palus/

ninmemb.raw of 8192 ko is not recgonized at all on recent version, even when using a formated/created one by nintendont and renamed.

**Comment by FIX94** [comment]
for that name to work, you have to have memory card multi enabled, and if its a japanese title, it has to be 
named ninmemjb.raw, and if you use single saves, it has to be GAMEID_B.raw instead.
