### ISSUE TITLE
Sonic Heroes won't accept saves from Real MC

### ISSUE THREAD

**Issue by DudeNin64** [FIX94/Nintendont#605]
I'm using an original Wii with a real GCN memory card, and after creating a new save file, turning off the game, and trying to load it again, it doesn't recognizes it, it goes to the "an error has ocurred" screen. It still let's me play if i press "continue without saving" or if i take out the memory card, but it doesn't save or load.

I'm using version 5.483

**Comment by carnage702** [comment]
an error has ocurred can be becuase of a bad iso, bad forced settings or a device sd or usb that isnt fast enought to keep with the game requests.

take a picture of your settings, check your iso md5  first.
