### ISSUE TITLE
Double Issue: Memory Card Failure and CheckForMultiGameAndRegion

### ISSUE THREAD

**Issue by RichardTheEspeon** [FIX94/Nintendont#606]
![20180808_182819](https://user-images.githubusercontent.com/42222750/43868404-78f30096-9b3b-11e8-9d6d-5eaeb9c2af8a.jpg)
![20180808_182620](https://user-images.githubusercontent.com/42222750/43868405-7900ff0c-9b3b-11e8-8d80-d989a04b134b.jpg)
So, whenever I try loading up a game in Nintendont, I always get this error:
CheckForMultiGameAndRegion() failed: 2
Unable to read the disc header.

Filename: sd:/games/GC6E01/game.iso

And whenever I try to load up Metroid Prime, I always get this:
Failed to create Memory Card!

How can I fix this? I'm running 4.3U, Nintendont v5.483 (Wii) and Firmware: 58.24.32

**Comment by carnage702** [comment]
well that error means imcompatible usb device or SD.

**Comment by RichardTheEspeon** [comment]
Well, I'm using a SanDisk 32GB SDHC Micro SD

**Comment by RichardTheEspeon** [comment]
what do you recommend?

**Comment by carnage702** [comment]
just wondering do games appear in the game list normaly? or once you choose sd you get that error?

**Comment by RichardTheEspeon** [comment]
Yeah they do appear on the game list normally, most of the time, sometimes it says that it couldn't read the sd card

**Comment by carnage702** [comment]
just pick any sd card formating tool and use it to format to fat32 i have no idea what is good or not, but any is better than windows formater, since windows formater is made for usb devices.

**Comment by RichardTheEspeon** [comment]
Still doesn't work

**Comment by carnage702** [comment]
you sure your isos are good?

check your iso md5 with redump.

also you dont have hidden extensions on your computer do you? or you could have the iso named game.iso.iso

also your sd card is formated to fat32?

**Comment by carnage702** [comment]
if you used some random tool to put isos on your sd card you might break the isos your iso must be full and matching redump md5 to be fully compatible.

**Comment by GB-CG** [comment]
> Yeah they do appear on the game list normally, most of the time, sometimes it says that it couldn't read the sd card

If you have another Wii to test and works on that but not yours that means there's a fault with your Wii's SD slot, not Nintendont. Sometimes the SD slot eventually does get a bit wonky if it's used a lot.

**Comment by carnage702** [comment]
is he sure the sd card isnt locked too?

**Comment by RichardTheEspeon** [comment]
SD Card isn't locked and is formatted to FAT32, other Wii got bricked, no hidden extensions and I don't know what MD5 with Redump is. I took this problem up with GBATemp and they told me I shouldn't use tools like DiscEX and that I should just use the raw ISO; if that helps

**Comment by RichardTheEspeon** [comment]
DISCOERY MADE (I THINK):
So when trying to copy some files to my SD card normally on my PC, it said that my card was write-protected (I think read protection as well). But when I used a USB-SD card reader, it suddenly was disabled and I was able to transfer those files. And when I used the USB reader, those problems just disappeared and everything worked. GB-CG, since you told me about the SD card slot being wonky, do you think you know a way to fix it?

**Comment by carnage702** [comment]
writ e protected means your sd card has the the lock down, or that the sd adapter to micro sd card is dying and you need another sd adapter.

**Comment by RichardTheEspeon** [comment]
Thanks everyone, I've solved the issue thanks to your help.

**Comment by leandorr** [comment]
I have the same issue what did you do to solve it?

**Comment by garrettfuls** [comment]
Having just solved the same problem myself by reading the comments here, I would guess that he had accidentally flipped the write protection switch on his SD card to on. That's definitely what I had done. As soon as I turned mine back off it immediately started loading games without issue.

**Comment by olg-olg** [comment]
I always get this error with a specific game (animal crossing). but when loading another one, (ratatouille) it works perfectly. i don’t know what is wrong. please, i need help

**Comment by carnage702** [comment]
> I always get this error with a specific game (animal crossing). but when loading another one, (ratatouille) it works perfectly. i don’t know what is wrong. please, i need help

You should make your own issue instead of replying to a closed one, also what happens ? Since you never said what happens when you launch animal crossing
