### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Niamek** [FIX94/Nintendont#607]
Hello!

I'm creating this issue because not only I've exhausted all options I could try on my end.

Using a normal Wii (Got on the first year of release, so one of the first wiis batch).

At first I tried with USB storage devices (three total), none of them works stopped at a special line like (IIRC it's INIT DI... like #302. I have to hold the power button to force the wii to shut of, so I assume it crashed. I formated it to FAT32 all of them (and even tried a couple of the cluster size options).

I checked if I got the right homebrew and the right ios. They are indeed correct. So that's not the issue.
Nintendont was able to open my disc game. So it's not nintendontbeing unable to open a game since it can open a game (in this case a real disc game).

I even tried with an older(?) version of nintendont that the nice guy found. It seemed to be going further, but still didn't work back then.

So I gave up and waited until I got an external HDD. Like it's mentionned on the read me (IIRC), storage devidces are known to be problematic and thus HDD are better.

Then I got myself an external hard drive disk (About 2 TB) and tried 2 games.
-With the most recent nintendont, I get a black screen like #575 : All the lines are passed, it goes to a black screen and it stops right there. I have to close the wii by pressing the button for a couple of seconds. So it crashed. It's indeed a FAT32 HDD (I had to use an app to format it to that with 32 KB and I even tried with 64 KB). I took the entire night trying a bunch of different cluster sizes from exFAT to FAT32. So I doubt it's the issue right there.

With the nice "dark theme" package, it seemed to go better, but it stays at a black screen. But it *seems* that it did not crash because pressing the power button turned of the wii instantly. So it's was a softlock it seems.

I then tried to use a v2.229. I found a loader.bol file and put it right away in my nintendont apps folder without replacing anything. (I assume it's okay to do so). And it still didn't work.

I recently checked the MD5 of one of my game and the MD5 matches with a database of md5. So the game looks to be not the issue.

From what I've read, it seems to be a known issue. I've found only one related open issue and didn't bother looking in closed issues. If you need me to do something or to provide informations, I'll happily provide asked info (unless it's personnal infos hehe :D ).

Here is my HDD. 
![image](https://user-images.githubusercontent.com/15385566/43987534-27f90e36-9cf0-11e8-8d62-72b8d7c64a0c.png)

**Comment by Niamek** [comment]
Oh it's also a HDD that has a plug. So it "needs electricity in order to work".

**Comment by carnage702** [comment]
so you can see the isos on nintendont menu but clicking them just black screens?

**Comment by Niamek** [comment]
I dont use any theme on homebrew. The theme I mentionned is a theme of nintendont.

On the top right orner I see:
1.1.2
IOS58 v24.32

I even reran through the installation of IOS58 with YAWMM before trying the external drive disk.

Yes I see the isos on nintendont menu. Clicking them opens the file. I do see the multiple "checks" such as "Init DI...ok!" which is about the last line of the check Then it goes to a black screen. So my guess is that it gets stuck after those check.

**Comment by Niamek** [comment]
Rereading the ticket I realized how bad I wrote the thing about the theme. Dark theme was on an "old(?) nintendont" thing a nice guy found had the dark theme. Not the homebrew.

Here is it.

[nintendont_2(1).zip](https://github.com/FIX94/Nintendont/files/2280283/nintendont_2.1.zip)

**Comment by carnage702** [comment]
well if you have an sd card try puttin an iso  on the sd card and run it, if it runs it just means your hdd is imcompatible because it might have some hidden partitions.

**Comment by Niamek** [comment]
My sd car dis unfortunately too small for an iso. Ive tried to get rid of stuffs but 1,35 Go is too much to fit in the sd card (I got one o those WII sd card that has not a lot of space).

**Comment by Niamek** [comment]
But I'll try something. Thanks for the idea!

**Comment by carnage702** [comment]
you can try another usb, while flashdrives are very very unreliable with nintendont tring one doesnt hurt, and sd cards nowadays are very cheap a 32gb sd card isnt even 15 euros.

**Comment by Niamek** [comment]
I've read that some sd cards doesn't work with the first wiis. And also, I kinda use my sd card to boot the my stuffs (it has my bootmii thing).

**Comment by Niamek** [comment]
I have tried three of my flashdrives hehe. But yeah I guess I'll continue to try! :)

Currently trying something with sd card.

**Comment by Niamek** [comment]
Could open a game iso that is in a sd card. Looks like I'll have to find a flashdrive or hard disk that is compatible with nintendont.

**Comment by carnage702** [comment]
sd card only worry is to hack where you need a 2gb or lower
after hacked you can even put a 512gb one.

**Comment by carnage702** [comment]
yup, i use a 32gb sd card on my wii

**Comment by Golden-Slayer** [comment]
I had the exact same issue. For just a brief second when I tried to load one of the games nintendont flashed an error about not being able to make the virtual memory card. I found that when I disabled the memory card all together all my games would work. This was still inconvenient so I kept digging.
https://github.com/FIX94/Nintendont/issues/664
They found that if you at least have one game that works you can change the name of the save file that game and make copies of it. The save files are saved as the first 4 characters of the games official id. (ex. Luigi's Mansion [GLME01], it would just be GLME.raw).
Hope this helps anyone else out there as frustrated as i was for the last 12 hours.
