### ISSUE TITLE
Freezes on Initializng IOS58 

### ISSUE THREAD

**Issue by AlexS2412** [FIX94/Nintendont#611]
All V5 of nintendont have this issue for me. downgrading ios58 to 23.30 fixes this issue for me but causes a new screen that says waiting for nintendont. all versions up to 4.451 work just fine and do not display this strange message. since i have no other builds of nintendont to test due to the old builds seemingly being dmca'd in most locations i have checked this is all the infor i can offer atm. any assistance on what the issue could be would be helpful. (AND YES I DID TEST WITHOUT ANY USB INSERTED IN THE WII AS WELL. the issue seems to be the program istelf on newer revisions. my HDD is FAT32 Formatted.) @FIX94

**Comment by GB-CG** [comment]
Here's the list: https://github.com/FIX94/Nintendont/commits/master

**Comment by AlexS2412** [comment]
now if only my issue could be resolved rather than downgrading nintendont.

**Comment by carnage702** [comment]
the issue is on your end, it works just fine for 99% of the people, you must have something bad.

get the latest official(not modded or cios) ios58 for wii, make sure your homebrew channel is ios58 based(press home and see the top left), make sure you dont have any themes or such on homebrew channell .

**Comment by AlexS2412** [comment]
i redownloade everything official from nus as wads and instaleld each version. its not my end i assure you. please take my big report seriously.

**Comment by carnage702** [comment]
how is it not your on your end? if it wasn't it would happen to everyone, we cat fix what we cant reproduce.

you or your console have something different from everyone else, you need to find out what,

**Comment by BasimAhm** [comment]
I had this same issue, it happened all of a sudden after Nintendont was working perfectly for years.  What was causing it was the Mario Party microphone plugged into memory card slot B.  When I unplugged it, Nintendont started working flawlessly again. If I plugged the microphone in mid-game, it continued to work as expected.  Something about it plugged in messes with the startup of Nintendont.

**Comment by westhouseit** [comment]
Exactly the same problem I'm having and the mic is the issue.
