### ISSUE TITLE
Turn off rumble

### ISSUE THREAD

**Issue by dontcare145** [FIX94/Nintendont#615]
That is most likely a really stupid question, but how do i turn of the rumble for Wii U pro controller. 
In the controller setings from the Wii U it's turned off.

**Comment by carnage702** [comment]
you cant, unless the game itself has options inside  to turn off the rumble, you cant turn the rumble off, doesnt matter what you have on your wiiu menu, nintendont runs its own thing and doesnt care about wii or wiiu settings.
