### ISSUE TITLE
Nintendont game-by-game settings

### ISSUE THREAD

**Issue by ENunn** [FIX94/Nintendont#621]
Hello.

I'm trying to force widescreen on games that actually work well with widescreen, but when I enable it, it enables widescreen for every game on my SD card. Some games I don't want widescreen enabled due to glitches or bugs or whatever.

Is there any way to save settings on a game-by-game basis? I could've swore I was able to do that before.

**Comment by carnage702** [comment]
you can only do that if you use a loader like wiiflow or usbloader gx or by using vwii injects with forced settings on wiiu.
