### ISSUE TITLE
Weird error on latest version

### ISSUE THREAD

**Issue by rayabusa** [FIX94/Nintendont#622]
Here is my problem when loading a gamecube game with Nintendont 5.485 on a Wii:

So, when I load it directly with HBC, it print "Warning: USB FAT device could not be opened." and when loading throught USBLoaderGX "CheckForMultiGameAndRegion() failed."

And this error happens randomly, sometimes the game runs, sometimes i get the error. 

Already tried deleting nincfg.bin and downloading nintendont again, still get the errors.

This errors do not happen with version 5.483, it work perfectly.

**Comment by Luigimeansme** [comment]
Good to know that this wasn't just me. I put Fairly OddParents Shadow Showdown on my HDD so I coould play it, and encountered this problem multiple times until I finally downgraded.

**Comment by evertonstz** [comment]
Yeah, I'll have the same error "CheckForMultiGameAndRegion() failed" poping randomly too.

**Comment by carnage702** [comment]
that is an usb acess error, probably your usb isnt fast enough to reply sometimes, it depends on how many revisions you go back.
