### ISSUE TITLE
Wavebird does not work

### ISSUE THREAD

**Issue by stephanmax** [FIX94/Nintendont#623]
Hey,
I am using the latest Nintendont on a backwards-compatible Wii 4.3E with Fire Emblem - Path of Radiance and the Wavebird Controller does not seem to work when starting the game from hard drive. If I start it from disc the controller works fine.

I hope I am not missing anything obvious, thanks for your amazing work!

**Comment by carnage702** [comment]
wavebird are touchy, while on nintendont menu start the game with the wavebird directly instead of with a wiimote or any other controller.

**Comment by stephanmax** [comment]
You are a **genius**, @carnage702! Thank you so much, that did the trick!
