### ISSUE TITLE
Return to Nintendont menu using the Wii U gamepad

### ISSUE THREAD

**Issue by MCUdude** [FIX94/Nintendont#624]
Hi!
I'm running Nintendont on my Wii U through an injected VC title. This way I can use the Wii U gamepad to play games with. Games are working fine, but I can't really figure out how to return to the Nintendont menu in order to change games and settings. Does anybody know the secret button combination for the Wii U gamepad?

Thanks!

**Comment by MCUdude** [comment]
Turns out I'm able to secret the game itself by pressing R+Z+Start. 
However the combination R+Z+B+Down (D-pad) doesn't do anything..

**Comment by carnage702** [comment]
you can never return to nintendont menu, once a game is started you cant return to nintendont, you can exit but thats it.

**Comment by MCUdude** [comment]
OK. So is this because I'm loading Nintendon't using a VC title and not through hopebrew channel on vWii? IIRC this was possible to do on my old Wii.

**Comment by carnage702** [comment]
you can only return to nintendont on your wii or vwii if you use a nintendont channel with a full stub, otherwise you can return to like usbloadergx or homebrew channel.

**Comment by MCUdude** [comment]
Thanks for the quick response! I guess I got my answer then 🙂
