### ISSUE TITLE
Super Smash Bros Ultimate GC Controllers Drift

### ISSUE THREAD

**Issue by seanjones150** [FIX94/Nintendont#625]
Nintendo has a released a new batch of GameCube Controllers for the upcoming Super Smash Bros Ultimate. All of these controllers drift while using Nintendont plus the GC adapter on Wii U or native ports on the Wii. Setting Native Control to ON fixes the issue on the Wii but is not an option on a Wii U with the GC adapter. I tested the GC controllers on other games outside of Nintendont... No drift! When the GC adapter is used on a PC + this controller there is also no drift. There's some sort of issue between these controllers and Nintendont.

**Comment by cujomalainey** [comment]
Can confirm 3 out of 3 Smash ultimate controllers bought all drift in nintendont on wii but not outside nintendont or on wii u.

**Comment by virex210** [comment]
I’ve tried tried 6 Smash Ultimate controllers and they all drift in Nintendont on WiiU as well. They work fine on Nintendont for Wii if native is turned on.

**Comment by carnage702** [comment]
which games you guys tested? bought the new controller and im playing double dash on wiiu with gc adpater and new smash controller on port 2 and no drift

**Comment by seanjones150** [comment]
Any game that has precision movement. For example in Melee the hand to select characters drifts while at 0x and 0y. The same can be seen in RPGs like The Legend of Zelda collection that contain Ocarina of Time. Link walks backward at a slow pace consistent with a drift. You might not notice it in a game like Mario kart since the nature of those controls are more sensitive to left and right movements. The cart will still go forward since your movement control is an acceleration button.

**Comment by cujomalainey** [comment]
20XX training pack. Don't remember the version off by heart. Flipped to native controls and no more drift.

**Comment by shadowdeku** [comment]
Melee definitely drifts in the menus. The controller works fine with the new Smash Bros on the Switch and with Melee running on Dolphin.

**Comment by TopTenTiger** [comment]
I have bought two SSMB Controllers. One drifts and the other is fine. I think Nintendo may have messed up as @carnage702 suggests.

**Comment by cujomalainey** [comment]
Even if they did, they left something in their system to compensate for it that should be able to be ported to nintendont.

**Comment by SSBuug** [comment]
I have encountered the same problem with 2 separate Super Smash Bros Ultimate GC Controllers.
I tried to fix this by changing the DeadZone value from 0 to 10 for the StickY variable in 057E_0337.ini (it goes from StickY=5,0,100 to StickY=5,10,100)
It effectively removes the drifting but makes it a bit harder to input an "upwards" control. 
Depending on the game, i think this could still work while FIX94 works on a better fix (if it's planned).

**Comment by figo5211** [comment]
Just acquired 2 Smash Ultimate Controllers and the new WUP-028 adapter. Yeah, noticed drifting downwards on SSBM running on Nintendont vWii but none at all on Dolphin nor SSB4. So yeah, I assume that's something on the loader side. Hopefully we'll get a fix. Fingers-crossed.

**Comment by fatefulatom** [comment]
I can validate this is an issue related to the new Smash Ultimate Controllers. I was having issues with Paper Mario (there was a drift pushing Mario up). After reading these comments, switched out the controller to my old 3rd party wireless GC controller and drift issue has been resolved. It also affects a few other games, but not all.

**Comment by hurda** [comment]
Are your controllers drifting on a GC or when playing a GC-game on Wii natively, too?
Not really Nintendont's fault when the new controllers are just broken, and some game/system-combos are working around that by using bigger deadzones.
IIRC F-Zero GX's calibraton and SSBM with 20XXTE are good ways to show if the sticks are good or not.
Let Nintendo know about this flaw, maybe it's widespread enough to get some attention.

**Comment by z861gz6wb2** [comment]
The controllers are just fine. No need to get Nintendo involved. The config just needs to get updated.

**Comment by Porkite** [comment]
yeah, i bought two GC controllers (for switch ones, with GC plug) in two different shops and both has drift problem. Native option on solved the problem.

Native Control to OFF:
![20190117_201742](https://user-images.githubusercontent.com/4449083/51344903-f4269b00-1a99-11e9-97fd-fe2cec72f2cb.jpg)

Native Control to ON:
![20190117_205044](https://user-images.githubusercontent.com/4449083/51344915-f852b880-1a99-11e9-8ab9-67502d096944.jpg)

**Comment by z861gz6wb2** [comment]
Didn’t work for me. I have the same offsets as you except my Y offset is positive 19.

**Comment by redditlord58** [comment]
> I tried to fix this by changing the DeadZone value from 0 to 10 for the StickY variable in 057E_0337.ini (it goes from StickY=5,0,100 to StickY=5,10,100)
> It effectively removes the drifting but makes it a bit harder to input an "upwards" control.


Increasing the third numeric value (radius) of StickY and/or StickX seems to mitigate this issue.

**Comment by akimasa** [comment]
I made a build which calibrates drift when first time reading controller.
I tested with Wii + Built-in GC Port and Wii + WUP-028.
There are small drift but much better than before.
![img_2999](https://user-images.githubusercontent.com/4647736/53090862-f4f89400-3553-11e9-9252-617426e4af8a.JPG)

https://github.com/akimasa/Nintendont/blob/SSBGC-drift/loader/loader.dol

**Comment by MarkTheFreak** [comment]
The same thing happens to me with Chibi-Robo (so annoying because every step you take decreases your watts).

**Comment by MarkTheFreak** [comment]
I'll try updating to the latest version to see if that fixes it

**Comment by MarkTheFreak** [comment]
(oops, forgot to comment earlier) Tested Animal Crossing, Super Mario Sunshine and Luigi's Mansion, no drift.
Chibi-Robo: Drift.
;-;

**Comment by MarkTheFreak** [comment]
Using Native Control seems to fix the issue.

**Comment by Kurosakix** [comment]
> I made a build which calibrates drift.
> I tested with Wii + Built-in GC Port and Wii + WUP-028.
> There are small drift but much better than before.
> ![img_2999](https://user-images.githubusercontent.com/4647736/53090862-f4f89400-3553-11e9-9252-617426e4af8a.JPG)
> 
> https://github.com/akimasa/Nintendont/blob/SSBGC-drift/loader/loader.dol

I had the same issue with the left stick and this solved the problem. However, i have noticed that the c-stick also suffers from drift in games where you move the camera, like in Mario Sunshine or Luigi's Mansion. 

Is it just a problem of mine? or it is general too?

P.S.: I can't enable "Native Control" because i'm using nintendont with vWii on Wii U

**Comment by booki89** [comment]
Using the ultimate gc control on my WiiU in vWii and get the drift - anybody have a fix for it?

**Comment by TweakMinded** [comment]
> 
> 
> I made a build which calibrates drift.
> I tested with Wii + Built-in GC Port and Wii + WUP-028.
> There are small drift but much better than before.
> ![img_2999](https://user-images.githubusercontent.com/4647736/53090862-f4f89400-3553-11e9-9252-617426e4af8a.JPG)
> 
> https://github.com/akimasa/Nintendont/blob/SSBGC-drift/loader/loader.dol

That build fixed the left stick but not the right. Any chance of adding whatever change you made on the C-Stick as well? Thanks!

**Comment by booki89** [comment]
@TweakMinded - Check out the other build here, it fixed the C stick drift for me!

https://github.com/akimasa/Nintendont/issues/2

**Comment by iGom** [comment]
Same issue with gc controller on Wii U with adapter

**Comment by yoshifan** [comment]
The Native Control setting doesn't fix the stick drift for F-Zero AX (Triforce arcade game), but thankfully akimasa's fork does fix it.

**Comment by samudex** [comment]
The camera on the pause screen in SSBM kept moving upward, and I was close to giving up on this original GameCube controller. I initially thought the stickbox was broken, but after enabling the Native Control setting, the drift issue disappeared completely.
