### ISSUE TITLE
Triforce games don't save RAM

### ISSUE THREAD

**Issue by RingoStarr39** [FIX94/Nintendont#626]
It seems that Triforce games aren't capable of saving any settings or high scores to RAM.
For example, changes made in the test menu aren't saved after exiting the menu.
Are there any plans to implement this?
Also, when credit mode is turned on after entering and exiting the test menu it's no longer possible to insert credits for some reason.

**Comment by RingoStarr39** [comment]
Anyone?

**Comment by carnage702** [comment]
obviously only like 3 triforce games save progresses and theres is no file implementation to save any ram change at all.
