### ISSUE TITLE
The Sims 2: Pets running to fast

### ISSUE THREAD

**Issue by dennisj007** [FIX94/Nintendont#628]
The Sims 2: Pets running a little bit to fast, the Sounds and Music have normal speed.
I have a PAL Wii with original GameCube Controller and original Memory Card and the last Nintendont Version.
I have tested it with an downloaded PAL ISO and the original Disc.
I not use 60HZ or 480p Hack, Video is set to Auto.

All other The Sims GameCube Games works great.

**Comment by FIX94** [comment]
what exactly is supposed to run too fast? just checked the game and it seems to run exactly as it should for me, running the PAL version of the game, seems to always run in 50hz and does so just fine here...

**Comment by dennisj007** [comment]
The Sims and the Pets move a little to fast.
The Video with the EA Logo on the beginnig are a little to fast too.
Under the Original Wii Disc Channel runs the game fine.

**Comment by carnage702** [comment]
maybe you are using an outdated nintendont version, what version are you using see actual number on top left of nintendont menu.

**Comment by dennisj007** [comment]
I use Nintendont v5.485
