### ISSUE TITLE
Star Fox Adventures - missing voice dialog (streaming audio) during cut scene

### ISSUE THREAD

**Issue by gng2hk** [FIX94/Nintendont#629]
a bit strange that all voice / dialogs (streaming audio) working well UNTIL...
(cutscene) when Fox first time entering Krazoa Palace (collected Krazoa spirit : test of combat), there are series of voice / dialog which became mute...
from subtitles "So, this is Krazoa Palace ... Tricky! ... I can still hear you, Fox" only background weather sound effect...  
after then streaming audio back to normal when Fox first met Krystal, till now I have not finished the game to check other cutscenes yet...
tried defrag / 1:1 the iso, also different region - US, JAP, same result...
wonder this bug can be fixed, as other games may suffer the same issue if the bug exists...
thank you.

**Comment by RenaKunisaki** [comment]
I think this is actually a bug in the game. I've seen it with a real disc on real GameCube.

**Comment by ccfman2004** [comment]
I never had an issue with audio in this game and that cutscene played fine the last time I played using Nintendont.
