### ISSUE TITLE
Nintendont crashes in game when played on HDD

### ISSUE THREAD

**Issue by marioluigi751** [FIX94/Nintendont#630]
Hi, I am using Nintendont on a Wii with GameCube ports, while using my Fat32 External USB HDD which is a Seagate External Backup 1 TB, the game then crashes in game with the last 2 seconds of music looping, then the following message appears"An error has occurred. Turn the Power Off and check the Nintendo GameCube Instruction Booklet for further instructions." Please help, I've searched all over the internet and posted on gbatemp.net and yet still have not gotten an answer. Plus, I saw a thread on here that was closed, but without a proper answer to my problem!

**Comment by carnage702** [comment]
nintendont version number.

**Comment by marioluigi751** [comment]
The loader says v5.485

**Comment by carnage702** [comment]
take a picture of your nintendont settings if you can.

**Comment by marioluigi751** [comment]
I 've tried turning force widescreen and Force Progressive off, but it doesn't make a difference.
![20181130_174200](https://user-images.githubusercontent.com/45473717/49318822-09367300-f4c8-11e8-9bdd-6195371833d7.jpg)

**Comment by carnage702** [comment]
maybe you have a bad iso, do all games crash or just one?

**Comment by marioluigi751** [comment]
Every game does this.

**Comment by carnage702** [comment]
well then its a problem with your hdd, when an error has ocurred happens means the game doesnt get the data fast enough so maybe your hdd is very fragmented or something you can try using another usb/sd and maybe reformat your entire drive  fully into fat32 and try putting the games again inside.
