### ISSUE TITLE
any easy way to use nnt on wiiu with real widescreen

### ISSUE THREAD

**Issue by nictse2013** [FIX94/Nintendont#631]
i tried several games, sms,metroid prime 2 support widescreen on nintendont.
but 007 Russia love,mgs twin snake don't support.
any easy way to fix the game with code or patch to real widescreens ?

**Comment by carnage702** [comment]
easy? hell no.

you need to get the game running on wii or gc then start seeing teh code with a hacking device and finding functions to patch, so no its not easy or else all games would have widescreen.
