### ISSUE TITLE
Add support for the new Hori Battle Pad for Nintendo Switch

### ISSUE THREAD

**Issue by NitroTheRetroGamer** [FIX94/Nintendont#632]
The new Hori Battle Pad for Nintendo Switch is a wired Nintendo Switch Pro Controller with the button layout of a Gamecube controller. Since it's basically just a pro controller, it might not be worth the effort, but I would really like to use it on Nintendont as it is the only "gamecube" controller that I own.
![hori 0](https://user-images.githubusercontent.com/45855264/49953234-f0818080-fefd-11e8-8150-05d6c7b2706d.png)

**Comment by PCjabber** [comment]
Related to #618, #480 and #593.

**Comment by Missingphy** [comment]
does it work with hidtest.

**Comment by marco7229** [comment]
@NitroTheRetroGamer  Was this issue solved? I cant used my Hori controller with Nintendont.

Can u help me please?

MF
