### ISSUE TITLE
Blurry/Grainy Picture on Nintendont

### ISSUE THREAD

**Issue by MinimumVelocity** [FIX94/Nintendont#634]
Hey,
I just installed Nintendont on my Wii u. Went to play Legend of Zelda game runs awesome
But the characters look very Grainy/Fuzzy? I have it set to force widescreen and force progressive scan.
I have it on my 55" tv, could this be normal? or am i missing a option?

**Comment by carnage702** [comment]
gc games are not hd and the bigger the tv the more you notice it, but try another game if it looks the same then your expecting too much from a 480p game lol also windwaker has native preogressive(usa version) so you dont need to force it.

**Comment by GB-CG** [comment]
I recommend the OSSC for playing standard definition games on a large screen, it'll correctly line-double the image. For more information: https://videogameperfection.com/products/open-source-scan-converter/
