### ISSUE TITLE
Greenscreen then crash after launch

### ISSUE THREAD

**Issue by Sneakykng** [FIX94/Nintendont#636]
Console: OG Wii Version 4.3U
Game: couldn't even get there yet
device: USB formatted to FAT32
IOS58
Latest version in the description as of 12/23/2018
So nintendont has always worked for me but all of a sudden it started giving a black screen after searching for devices. So I updated my version with the latest one now when I launch it gives me a green screen and kicks me back to the homebrew channel

video: https://www.youtube.com/watch?v=sRZEWXU5UVs

**Comment by Sneakykng** [comment]
UPDATE: does it without usb also

**Comment by carnage702** [comment]
Delete any ninconfig on Your sd and USB, probably got corrupted

**Comment by Sneakykng** [comment]
controller doesn't work anymore its a og gamecube controller btw

**Comment by carnage702** [comment]
Controles.ini and ninconfig can become corrupted delete them

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Sneakykng** [comment]
where do I find controls.ini?

**Comment by Sneakykng** [comment]
I dont have that file

**Comment by Sneakykng** [comment]
and btw I mean when I select usb it pretty much freezes

**Comment by carnage702** [comment]
Both ninconfig and controller inis are in the root of usb and sd if they exist

**Comment by Sneakykng** [comment]
still freeze after selecting usb

**Comment by carnage702** [comment]
You need a fresh instal delete everything nintendont related on sd and USB except game isos and raw files and redownload everything

**Comment by Sneakykng** [comment]
what would be all the files?

**Comment by carnage702** [comment]
Also try unpluyging Your wiiu GC adapter and startup nintendont without it

**Comment by Sneakykng** [comment]
its wii not wii u

**Comment by carnage702** [comment]
Got anything on USB Doors besides USB?

**Comment by Sneakykng** [comment]
nope

**Comment by carnage702** [comment]
Well then you got corrupted files, Open Your sd and delete nintendont folder from apps, then ninconfig and ini from root if Theresa, on USB do the same and go to saves and if any 0kb filtros Theresa do the same

**Comment by Sneakykng** [comment]
got it
