### ISSUE TITLE
[request] Home button return

### ISSUE THREAD

**Issue by gitfamhub** [FIX94/Nintendont#638]
I like to use the Wii U Pro Controller but it's not supported on the Homebrew Channel. It'd be sweet if I could remap the home button to just take me straight back to Nintendont.

**Comment by carnage702** [comment]
the way nintendont works it can never return to itself, once a game launches nintendont menu cant be returned to, only can return to something like homebrew channel or usbloadergx, if im not mistaken there is a modded homebrew channel that had wiiupro support you probably need to find that.
