### ISSUE TITLE
Issues with external HDD

### ISSUE THREAD

**Issue by dhamiltonc** [FIX94/Nintendont#639]
I'm not entirely sure if this is an issue related more to the homebrew channel or nintendont, but, even after formatting my external HDD to Fat32 with 32kb clusters and connecting it to the wii with/without a y cable, the nintendont app doesn't appear when the homebrew channel is loaded. Instead, I'm left with just an empty blue homebrew main menu.

The file-system of the drive is setup just like any other thumbdrive I've used with nintendont before (apps/games/saves folders, etc).

Please correct me if I've done anything wrong, ask any questions, or offer any help if possible. I've been troubleshooting this issue for days now, and I'm almost to the point of giving up.

**Comment by carnage702** [comment]
if you have the sd card inserted just extract it, sd takes priority over usb so homebrew channels first reads sd and then usb.

not that it matters since you can put nintendont on the sd card and when loading nintendont just pick usb option.

**Comment by dhamiltonc** [comment]
I'd thought about trying that. Regardless, everything should be working with the configuration as it is now, right?

**Comment by carnage702** [comment]
remenber nintendont loader.dol must be renamed to boot.dol for homebrew channel to see it too.
