### ISSUE TITLE
Doesn't detect folder on SD

### ISSUE THREAD

**Issue by Baconz2** [FIX94/Nintendont#640]
I recently got a Gamecube GBA link cable to play Animal Crossing. But when I tried to run it, it wouldn't run. Gave me a CheckForMultigameAndRegion error. I updated Nintendont, but now it doesn't detect the folder. And yes, the folder and the games are there and named it correctly. What do I do?

**Comment by carnage702** [comment]
take a picture of your sd/usb root and then take a picture of the inside of games folder and then inside animal crossing folder.

**Comment by Baconz2** [comment]
![root](https://user-images.githubusercontent.com/46719718/51286892-dbd75300-19a9-11e9-821f-6c25edddefa0.PNG)
![games folder](https://user-images.githubusercontent.com/46719718/51286897-e265ca80-19a9-11e9-97b3-325752682b3f.PNG)
![game](https://user-images.githubusercontent.com/46719718/51286904-e560bb00-19a9-11e9-9d9b-bd7971efde76.PNG)

**Comment by carnage702** [comment]
so the game.iso inside the animal crossing folder is not named game.iso.iso? becuase sometimes people have hidden extensions and get game.iso.iso

also game game iso: i supose you mean animal crossing folder?

if everyting is good try this delete any ninconfig.bin and controller.ini if they exist on the root of your sd card, delete nintendont boot.dol inside apps folder, manualy redownload the loader.dol here and rename it to boot.dol

**Comment by Baconz2** [comment]
I have hidden file extensions off.
Tried deleting boot.dol and redownloading it. Tried deleting nincfg.bin and controller.ini. It didn't work

**Comment by carnage702** [comment]
so does nintendont see the games? on the menu? its just selecting animal crossing that gives the error.

**Comment by Baconz2** [comment]
No, it gives an sd:/games not found error.

**Comment by carnage702** [comment]
well all i can say is your sd card is not compatible, is your sd card fat32 formated? try getting another sd card or usb.

**Comment by Baconz2** [comment]
It did work before. I'll try to get a different sd and see if it's the card, which I doubt it is. To be honest none of the homebrew I have on the sd card is working anymore, so it could be corrupted.

**Comment by carnage702** [comment]
then that should have been a red flag to begin with, try formatting it first , a slow format instead of a quick one.

**Comment by DarkLink1996** [comment]
I've been having the same problem. It worked fine on my older version, but the newest one won't read it. Everything else can but Nintendont. I'll reformat the SD card and see if it works, but it's definitely odd that we're having the same issue. Maybe one of the updates affected compatibility with certain cards?

**Comment by carnage702** [comment]
no update has messed with usb/sd for years.

**Comment by DarkLink1996** [comment]
That is odd. I tried with a known good card and it still failed, so I officially have no idea what's going on

**Comment by carnage702** [comment]
you might have a corrupted nintendont file, delete everything in nintendont apps folder, ninconfig.bin/controller.ini on the root of the sd and check your save folder, to see if the save folder has any 0kb raw files that might be corrupted.

**Comment by DarkLink1996** [comment]
I got it working out of nowhere, I think card reader might have been dirty, but I have no clue. I have a new issue where it's reading the memory card, but not writing to it, but it belongs in a different issue thread

**Comment by carnage702** [comment]
if its not saving ti could be locked or something, or it might be your wii card reader that is dying or something.

**Comment by itdurra** [comment]
Unreal... turning my Wii over fixed my problem. I'm going to blame it on old hardware :/

**Comment by ryokovv006** [comment]
I have the same problem. I have an old build of Nintendont, 4.444 and that version can see all my games in sd:/games but the current version, 5.4 cannot. I have simply swapped the boot.dol back to get it to see the games, so I think there must have been a change at some point to how this works.  
I have a 32gb micro sd card formatted to fat32 (32 cluster size), games are stored in their own folders as game.iso

**Comment by carnage702** [comment]
you probably need to delete your ninconfig.bin since it might not be compatible beween such versions.

**Comment by ryokovv006** [comment]
I tried that. I also tried a fresh install on a newly formatted drive. Not working. But 4.444 does.

**Comment by carnage702** [comment]
got some issue with your sd card, those sd adapters are crappy and fail all the time they get burn easy and maybe 444 is less demanding when asking for stuff than the new one is, but any sd card correctly formated to fat 32 and with deleted ninconfig and games path being

sd:games/anyname/game.iso

 should work unless the sd card is too slow and doesnt respond in time.
also make sure your not naming the games game.iso.iso where you have hidden extensions on your pc,

**Comment by Baconz2** [comment]
yeah it was my SD card adapter, my bad.
