### ISSUE TITLE
Issues with multiple controllers on same adapter when MultiIn=2

### ISSUE THREAD

**Issue by MickMad** [FIX94/Nintendont#643]
Hello there,

first of all, thanks for the wonderful job you guys made.

I am on Wii U, and Ihave a Multi GCN to Wii U/Switch adapter (Amazon says it's from Keten, but the package actually says DOBE), it has a switch to work with the PC or with the Wii U/Switch; when in Wii U mode the adapter straight does not work. I've only managed to get its VID and PID through tdd.exe (a USB Descriptor dumper, very useful) and it shows VID 057E and PID 0337, so it SHOULD emulate an official adapter, but I guess it has been poorly programmed so whatever.

I've written a configuration file for both Nintendont and HID-to-VPAD for the PC mode of this adapter (VID 0079 and PID 1846) and while I've been successful at getting all 4 ports to work correctly with HID-to-VPAD, I am having some troubles with Nintendont.

My adapter is the kind that uses one message for all controllers and flicks the first byte with the ID of the controller (1 to 4 in this case); I've searched in the code and I've found the switch/case that decides what type of controller to use in [kernel/HID.c](https://github.com/FIX94/Nintendont/blob/767f6d4170751319a4ff307e761ce2cf34340ece/kernel/HID.c#L409), my case is this one:

`case 2: // multiple controllers fron a single adapter`
`  if ((Packet[0] < HID_CTRL->MultiInValue) || (Packet[0] > NIN_CFG_MAXPAD))`
`  goto retry;`
`break;`

So I put MultiIn=2, MultiInValue=00 (first byte must be bigger than MultiInValue otherwise the kernel retries to read data) and the controller gets recognized, but it looks like it is getting disconnected every second (I am testing with only one controller at the moment, I have no multiplayer games just yet), it seems like the same behavior as described in [issue 213](https://github.com/FIX94/Nintendont/issues/213) which was closed without explanation. To describe further, 

I also tried setting the MaxPad config in Nintendont to 4 (it was 0 before), but that does not change anything.

At the moment I am stuck with MultiIn=1 and MultiInValue=01 so to filter data for Controller 1 only, which works perfectly for single player, but I would like to be able to use more than 1 controller with Nintendont (as of now, there's not one CFG file in the Nintendont release that has MultiIn set to 2).

Thanks in advance,

Mick

**Comment by carnage702** [comment]
multiin set to one means there is more than one port, if you never tried a multiplayer game yet on nintendont how do you know it doesnt work? remenber most gc games do not allow you to control them with ports 2-4 unless its in multiplayer mode.

**Comment by MickMad** [comment]
As stated at lines 409-417of kernel/HID.c:
`	switch( HID_CTRL->MultiIn )`
`	{`
`[...]`
`		case 1:	// match single controller`
`			if (Packet[0] != HID_CTRL->MultiInValue)`
`				goto retry;`
`			break;`
which means that in case MultiIn=1, Nintendont knows that there are multiple controllers on the same adapter but it filters for the one specified in the MultiInValue, that is for the one where the MultiInValue matches the value in the first byte of the HID packet; so MultiIn=1 and MultiInValue=01 (as specified in my controller cfg file) means that Nintendont only reads data from controller port n.1 (or from the controller whose ID in the HID packet is 1).

I just tried this with, indeed, a 2 players game (namely Soul Calibur II) and the VS mode is not even enabled because the game thinks there's only one controller even if I have 2 plugged in.

**Comment by MickMad** [comment]
Hey there,

nothing yet on this matter?

**Comment by carnage702** [comment]
and probably wont be anything , this is an issue that needs to be solved by you dont think anyone is still active to solve anything, btw i never got to ask but are your controllers offical gc controllers? i have some 3rd party gc controllers that dont work on the adapter in nintendont while offical ones do.

**Comment by MickMad** [comment]
It's alright, I was just checking if anyone had an idea on how to solve this, I don't expect people to just fix stuff. And yes, my controllers are official ones, they're the ones I got back in 2003 I think, when I got a GCN.

**Comment by carnage702** [comment]
well buy an official one even the switch one and it will work.

**Comment by ycdi81** [comment]
Hi MickMad, I have the same problem, and I don't know if you solved this.
My values are:

VID=0079
PID=1846
Polltype=1
MultiIn=2 // for a adapter with various controllers
MultiInValue=01 // this is because the range of controllers is from 01 to 04
...

With this values I can read all the four controllers, but Nintendont assumes that all the four controller are connected, no matter if only have 1 or 2 real controllers.

My problem now is the C stick, this are inverted in both axes, and the R button some times isn't detected correctly.

**Comment by ferolim** [comment]
Hi, @MickMad!

Could you share your controller.ini that works with one controller? I can't configure mine to work even with one controller.

Thanks!

**Comment by cyberrep** [comment]
> 
> 
> Hi MickMad, I have the same problem, and I don't know if you solved this.
> My values are:
> 
> VID=0079
> PID=1846
> Polltype=1
> MultiIn=2 // for a adapter with various controllers
> MultiInValue=01 // this is because the range of controllers is from 01 to 04
> ...
> 
> With this values I can read all the four controllers, but Nintendont assumes that all the four controller are connected, no matter if only have 1 or 2 real controllers.
> 
> My problem now is the C stick, this are inverted in both axes, and the R button some times isn't detected correctly.

Hey buddy, can you send the controller.ini for
VID=0079
PID=1846

**Comment by MickMad** [comment]
I don't have the files on my PC anymore, and I don't have the Wii U with me either. When I get it back I'll post what I had, in the meantime you should try with setting MultiIn=1 and MultiInValue=01 to get a single controller working.

**Comment by MickMad** [comment]
Hi all @cyberrep @ferolim . sorry for the LONG wait :)
I recently set up my Wii U again and I found the time to go back and check the files, as well as getting the config I made 2 years ago.

This is the 0079_1846.ini for nintendont
`[Keten Wii U GameCube Controller Adapter]
VID=0079
PID=1846
Polltype=1
DPAD=1
MultiIn=1
MultiInValue=01
DigitalLR=0
A=1,02
B=1,04
X=1,01
Y=1,08
Z=1,80
L=1,10
R=1,20
Power=1,40
S=2,02
Up=2,10
Down=2,40
Right=2,20
Left=2,80
RightUp=2,30
DownRight=2,60
DownLeft=2,C0
UpLeft=2,90
StickX=3,15,100
StickY=4,15,100
CStickX=6,15,100
CStickY=5,15,100
LAnalog=7
RAnalog=8`

While this is the .ini for HID to VPAD:

`[vid=0x0079,pid=0x1846]
[IgnoreDefault] //Ignoring the built in default values
VPAD_BUTTON_A               = 0x01,0x02
VPAD_BUTTON_B               = 0x01,0x04
VPAD_BUTTON_X               = 0x01,0x01
VPAD_BUTTON_Y               = 0x01,0x08

VPAD_BUTTON_PLUS            = 0x02,0x02

VPAD_BUTTON_L               = 0x01,0x10
VPAD_BUTTON_R               = 0x01,0x20

VPAD_BUTTON_ZL              = 0x01,0x80

DPAD_MODE                   = DPAD_NORMAL
VPAD_BUTTON_UP          	= 0x02,0x10
VPAD_BUTTON_RIGHT          	= 0x02,0x20
VPAD_BUTTON_DOWN          	= 0x02,0x40
VPAD_BUTTON_LEFT	        = 0x02,0x80

VPAD_L_STICK_X              = 0x03,0x80
VPad_L_Stick_X_Deadzone 	= 0x15
VPAD_L_STICK_X_MINMAX 		= 0x1F,0xE3

VPAD_L_STICK_Y              = 0x04,0x80
VPad_L_Stick_Y_Deadzone 	= 0x15
VPAD_L_STICK_Y_MINMAX 		= 0x1F,0xE3

VPAD_R_STICK_X              = 0x06,0x80
VPad_R_Stick_X_Deadzone 	= 0x15
VPAD_R_STICK_X_MINMAX 		= 0x30,0xE3

VPAD_R_STICK_Y              = 0x05,0x80
VPad_R_Stick_Y_Deadzone 	= 0x15
VPAD_R_STICK_Y_MINMAX 		= 0x30,0xE3

VPad_L_Stick_Y_Invert       =   True
VPad_R_Stick_X_Invert       =   True

PAD_COUNT=4
PAD1_FILTER=0x00,0x01
PAD2_FILTER=0x00,0x02
PAD3_FILTER=0x00,0x03
PAD4_FILTER=0x00,0x04`

I hope this info will be useful to someone out there :)

**Comment by carnage702** [comment]
> 
> 
> Hi all @cyberrep @ferolim . sorry for the LONG wait :)
> I recently set up my Wii U again and I found the time to go back and check the files, as well as getting the config I made 2 years ago.
> 
> This is the 0079_1846.ini for nintendont
> 
> ```
> [Keten Wii U GameCube Controller Adapter]
> VID=0079
> PID=1846
> Polltype=1
> DPAD=1
> MultiIn=1
> MultiInValue=01
> DigitalLR=0
> A=1,02
> B=1,04
> X=1,01
> Y=1,08
> Z=1,80
> L=1,10
> R=1,20
> Power=1,40
> S=2,02
> Up=2,10
> Down=2,40
> Right=2,20
> Left=2,8
> RightUp=2,30
> DownRight=2,60
> DownLeft=2,C0
> UpLeft=2,90
> StickX=3,15,100
> StickY=4,15,100
> CStickX=6,15,100
> CStickY=5,15,100
> LAnalog=7
> RAnalog=8
> ```
> 
> While this is the .ini for HID to VPAD:
> 
> ```
> [vid=0x0079,pid=0x1846]
> [IgnoreDefault] //Ignoring the built in default values
> VPAD_BUTTON_A               = 0x01,0x02
> VPAD_BUTTON_B               = 0x01,0x04
> VPAD_BUTTON_X               = 0x01,0x01
> VPAD_BUTTON_Y               = 0x01,0x08
> 
> VPAD_BUTTON_PLUS            = 0x02,0x02
> 
> VPAD_BUTTON_L               = 0x01,0x10
> VPAD_BUTTON_R               = 0x01,0x20
> 
> VPAD_BUTTON_ZL              = 0x01,0x80
> 
> DPAD_MODE                   = DPAD_NORMAL
> VPAD_BUTTON_UP          	= 0x02,0x10
> VPAD_BUTTON_RIGHT          	= 0x02,0x20
> VPAD_BUTTON_DOWN          	= 0x02,0x40
> VPAD_BUTTON_LEFT	        = 0x02,0x80
> 
> VPAD_L_STICK_X              = 0x03,0x80
> VPad_L_Stick_X_Deadzone 	= 0x15
> VPAD_L_STICK_X_MINMAX 		= 0x1F,0xE3
> 
> VPAD_L_STICK_Y              = 0x04,0x80
> VPad_L_Stick_Y_Deadzone 	= 0x15
> VPAD_L_STICK_Y_MINMAX 		= 0x1F,0xE3
> 
> VPAD_R_STICK_X              = 0x06,0x80
> VPad_R_Stick_X_Deadzone 	= 0x15
> VPAD_R_STICK_X_MINMAX 		= 0x30,0xE3
> 
> VPAD_R_STICK_Y              = 0x05,0x80
> VPad_R_Stick_Y_Deadzone 	= 0x15
> VPAD_R_STICK_Y_MINMAX 		= 0x30,0xE3
> 
> VPad_L_Stick_Y_Invert       =   True
> VPad_R_Stick_X_Invert       =   True
> 
> PAD_COUNT=4
> PAD1_FILTER=0x00,0x01
> PAD2_FILTER=0x00,0x02
> PAD3_FILTER=0x00,0x03
> PAD4_FILTER=0x00,0x04
> ```
> 
> I hope this info will be useful to someone out there :)

any chance you know how to get the rumble values to add rumble to controller.inis? i searched the web and it seems only fix94himself and some other guy made inis with rumble values on them, but no explanation on how to get them.

**Comment by MickMad** [comment]
Hi all, hi @carnage702 
Nope, in the sense that I haven't tried it yet. I'll update here if I get the chance to.

**Comment by Larkas** [comment]
Hey, @MickMad , just to let you know, I'm in the same boat you were all back when. It seems that, while Nintendont should be filtering the input by referencing to the first input value when in MultiIn = 2, like HIDtoVPAD does, it's NOT doing that, that is, every tick, it reads the other ports values (neutral, if no controllers are connected) and reports it to EVERY controller.

I'm no programmer, though, so that's as far as I got until I hit that ignorance wall =/ If I manage to fix this, I'll post here (or fork the project, idk).

**Comment by gilesep** [comment]
Hi @MickMad, thanks for raising this issue. I have made a local fix for it on my machine which works fine for me. If you want to try it out too, the modified nintendont boot.dol file and notes on how to make a VID#_PID#.ini file to work with your own splitter controller can be found here: https://github.com/gilesep/Nintendont-gi/releases/tag/v1.0.0. Best wishes. :)

**Comment by MickMad** [comment]
Amazing, thank you very much @gilesep  :)

**Comment by gilesep** [comment]
Thank you very much @MickMad, your reply made my day.  :)  @carnage702 has also merged the fix to the Nintendont master branch now, which I am grateful for: https://github.com/FIX94/Nintendont/pull/1088. Best wishes to you both, Gi :)

**Comment by stanwebber** [comment]
in case anyone runs across this from a google search like i did...
i can confirm gilesep's fix works on 0810:0001 & 0e8f:3013 adapters (with working rumble). the distributed 0810_0001.ini should be updated to multiin=4, multiinvalue=2. there is no controller.ini for 0e8f:3013, but it works with 0810_0001.ini after updating the vid:pid. great work!
