### ISSUE TITLE
Japanese Game Freezes Randomly In Game

### ISSUE THREAD

**Issue by tomossx** [FIX94/Nintendont#644]
nintendont has always worked except now. i got a copy of ssx 3 japanese version. when i play and im in a random race the game freezes then sends me to the home screen? is there any fix to this? i have tried region switcher but that has not worked either.

**Comment by carnage702** [comment]
your probably hitting the reset combo, if i recall a trick in this game hits the same buttons as nintendont reset combo on the gc controller, if you are using a wii you can disable the reset combo by choosing to play native controllers to on

**Comment by tomossx** [comment]
how would i disable that? and whats a native controller?

**Comment by carnage702** [comment]
in nintendont options there is an option called native control just turn that on, you wont be able to exit any game with a combo tough so you will need to just shutdown your console to exit.

**Comment by tomossx** [comment]
thank you for the help it worked. one quick question tho. is there a way to import saves to nintendont?

**Comment by carnage702** [comment]
nintendont saves are raw files so just download dolphin (gc/wii) emulator for pc and use its memory card management option to open nintendont raw files and put or delete anything really.


if you have single save files you will see a raw file (memory card) for each game, if you have a multicard set to on, you will see only one raw file.

**Comment by tomossx** [comment]
i dont have a memory card though. is there a way i can but a save in a folder of my sd card? and so what would i have to name that folder?

**Comment by carnage702** [comment]
nintendont makes its own memory cards and save files on sd or usb(its where the iso is stored)

just turn mc emulation to on in nintendont settings.

**Comment by tomossx** [comment]
i understand. i have a 100% save file on my pc. what would i have to name the folder on my sd card to put the save in. then would i have to make that save a gci or raw

**Comment by carnage702** [comment]
let nintendont make a save file first, then  go to your sd card root in saves see the raw file open it on dolphin and then you can import and export gcis to that file, save and replace the raw file back in nintendont saves folder on the sd card without changing the name of it.

**Comment by tomossx** [comment]
does the save have to be a .raw or .gci and do i just make a folder of the root of my sd called saves

**Comment by tomossx** [comment]
every thing works good now thanks! im guessing the save does not work is bc its a usa save not a jap save

**Comment by carnage702** [comment]
yes saves are region locked
