### ISSUE TITLE
Classic Controller's ABYX buttons are swapped after playing for a while

### ISSUE THREAD

**Issue by icup321** [FIX94/Nintendont#645]
Okay, so I've had this weird issue where the ABYX buttons on my Classic Controller are swapped around after playing for about an hour or two and it seems to happen very often to me. The buttons are automatically swapped from A->B, B->Y, Y->X, X->A (basically an Xbox 360 button layout). This happens in the newest build and it happens on every game.

**Comment by carnage702** [comment]
this is not a bug its a feature... everytime you press the minus button the abxy rotate.
stop pressing it lol.
