### ISSUE TITLE
SW - Rogue Leader

### ISSUE THREAD

**Issue by superdoughboy4** [FIX94/Nintendont#647]
Hanging at certain intervals of levels, same issues I've been having on the latest Dolphin emu.
Figured out the copy I had was compressed, and CleanRipped a legitimate copy to no avail.
Running the game using the disc through original compatible means works perfectly, but running the disc through Nintendont causes the same issues.
Levels I've experienced crashing:
Level 6 - Vengeance on Kothlis: Hangs during AT-AT portion.
Level 7- Imperial Academy Heist: Hangs after finishing mission, preventing completion.
Level 8 - Raid on Bespin: Hangs after reaching Bespin and flying around some.
Level 9 - Strike at the Core: Hangs once you reach the tunnel portion of the level.
Hangs happen with and without cheats. Really strange that it's happening because Rebel Strike runs perectly, and runs perfectly by just running it off of the disc w/o Nintendont.
It's like the game doesn't want to be emulated lol.
Using Nintendont Loader v5.486
Firmware: 58.24.32
Running ISOs off of my Sandisk Ultra 32GB FAT32 SD card.

**Comment by carnage702** [comment]
seems to be an issue with your iso really.

check your iso md5 and take a picture of all your nintendont settings.

**Comment by superdoughboy4** [comment]
ISO's MD5 checks out. Tried it in Dolphin and used the certutil in CMD to make sure.
Also ran the MD5 verifier on the Wii. 1:1.
Settings for the game are all default except for memory card emulation.

**Comment by carnage702** [comment]
lots of people say they are default when they arent a picture would be better.

i played all star wars games on nintendont with no issues whatsoever except a tiny gfx bug on the shiled metter on rogue squadron 3

**Comment by superdoughboy4** [comment]
![20190203_130536](https://user-images.githubusercontent.com/47282653/52180476-9a6de280-27b4-11e9-8400-ab712b496a8e.jpg)

**Comment by superdoughboy4** [comment]
![20190203_131334](https://user-images.githubusercontent.com/47282653/52180571-13216e80-27b6-11e9-9d86-2d504b936333.jpg)

**Comment by carnage702** [comment]
the only thing i see is drive acess led is set to on, turn that off, if it doesnt work ,you are on a wii with gc ports right? it can read gc discs since you said playing normal it works, nintendont can play the disc also just put the disc in and launch it from within nintendont there, maybe your sd card is to blame for something

**Comment by superdoughboy4** [comment]
Ya it's an original GCN compatible Wii.
What I have also noticed is that even when I run the disc through Nintendont, it still crashes at the same intervals. But running it through the normal Wii menu, it's flawless.
I'll check the access LED too. This is really strange...

**Comment by carnage702** [comment]
try turning that off and try again, very wierd, i havent played rogue squadron 2 in awhile but i played it fully on nintendont without any issues like a year or so ago.
