### ISSUE TITLE
Original GC controller on Wii stops working at random intervals

### ISSUE THREAD

**Issue by brotherthirteen** [FIX94/Nintendont#649]
Hi guys,
first of all, thank you for all the work you have put into Nintendont ;)

So I have an original Wii with the latest Nintendont. I have an original GC controller plugged into Port1, recognized without problems in the settings menu. Set Native Control to on (see settings menu screenshot).
It actually works in the game as well... until it doesn't. At seemingly random points (usually after pressing the A button), the controller just stops working.
If I disconnect the controller and reconnect, it usually restarts working again.

I have used this controller both on the original GC and on the Wii in other programs so I don't think it's the controller. Tried on Super Mario Sunshine & Luigi's Mansion, same problem.

Any ideas?

Keep up the good work, cheers :)

![settings](https://user-images.githubusercontent.com/47537145/52585826-24155400-2e36-11e9-9d52-d147af83a22b.jpg)
![controller](https://user-images.githubusercontent.com/47537145/52585828-24155400-2e36-11e9-960b-9d451a4ef4fd.jpg)

**Comment by carnage702** [comment]
you got manny bad settings turned on

debugger turn it off
maxpads set to 4
patch pal50 set to off too(this is only needed when forcing pal games to other videomodes if they fail).
native can be off too, you dont need native to actually use a gc controller.

**Comment by brotherthirteen** [comment]
Hi @carnage702 , thanks for the tips.
Tried all the settings you indicated but was still not working... 

But then I noticed the Wii remote was turning on during GC bootup. Forced it off and now it works like a charm :)

Thank you!

**Comment by brotherthirteen** [comment]
Hi guys,
sorry to have to re-open this issues but it gets really weird.
No problems with Super Mario Sunshine: have played for a couple of days without hitches.
Have tried Luigi's Mansion, Paper Mario and Viewtiful Joe and the controller stops working completely in certain points (usually when pressing wither A or R).
Unplugging the controller from the port fixes it... until you press the button (again either A or R usually) and it stops working.

Any ideas?

**Comment by brotherthirteen** [comment]
Here are the settings (I've tried both with and without Native Control)
![2019-02-16-12 50 - copy](https://user-images.githubusercontent.com/47537145/52899402-eb84ca00-31e9-11e9-89d6-ea19e3f9039d.jpg)

**Comment by carnage702** [comment]
Seems to be anexo issue with Your controller ir controller porta imo

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by brotherthirteen** [comment]
So probably nothing to do except change controller, right?

**Comment by carnage702** [comment]
Yeah  buy an official One, specialy the wiiu smash ones, they are better than the switch ones

**Comment by OutsiderRain** [comment]
Hi im having the exact same problem right now, what can i do? The controller works well in any other thing, but with nintendont just doesnt....
