### ISSUE TITLE
The Urbz: Sims in the City

### ISSUE THREAD

**Issue by zachawii** [FIX94/Nintendont#650]
The game "The Urbz: Sims in the City" has some sort of corruption when playing on Nintendont. The UI renders fine, but the rest of the game is heavily distorted (see attached photo). Both the USA and EUR versions of the game have been tried with the same results. There is a [video ](https://www.youtube.com/watch?v=epUXSHiew18)on YouTube showing the game running in Nintendont without the issue. 

![image](https://user-images.githubusercontent.com/11206045/52611694-8f155980-2e3b-11e9-9b6a-efa8e7e0eaaa.png)

**Comment by carnage702** [comment]
this seems to be an issue on your end, maybe your wii  is damaged or something. but take a picture of your nintendont settings, but this looks like a gpu error on your wii.

**Comment by zachawii** [comment]
The issue was able to be replicated on both a Wii U and an original Wii using the settings below.

![nintendontsettiungs](https://user-images.githubusercontent.com/11206045/52664936-2243a300-2ebf-11e9-9bc4-96b903c6d1c3.PNG)

**Comment by carnage702** [comment]
Turn width to auto instead if 690

**Comment by iJeanG18** [comment]
Hi, I have the same problem, I have the Pal version for what I don´t understand very well the english , this game is in Spanish, the cutscenes is very nice, but the rest game is corrupted or distorcioned, how fix this?

**Comment by carnage702** [comment]
do you have video width  too? just put it at zero or auto or what the default value is.

**Comment by iJeanG18** [comment]
This fix it?

**Comment by iJeanG18** [comment]
Every games Pal found excellent on my wii ntsc, except this.

**Comment by carnage702** [comment]
some games are more picky, other crash for anything, i have no idea which settings you have on, also no idea if it fixed it for him but since he never replied anymore i guess maybe.

**Comment by iJeanG18** [comment]
Bro thanks, I fix the problem, you can close this issue,💪🏻💪🏻💪🏻

**Comment by Johnnyztar3000** [comment]
Muchas gracias en efecto al poner en auto de video with se soluciono también
