### ISSUE TITLE
007: Nightfire PAL version freezes when forcing NTSC

### ISSUE THREAD

**Issue by DongVGH** [FIX94/Nintendont#651]
I'm trying to run the PAL version of Nightfire but unfortunately setting the video mode to anything other than PAL50 makes the game crash at the first mission's loading screen, but the first mission is completely unplayable with the flickering from the PAL50 video mode.

What workarounds are there?

**Comment by carnage702** [comment]
video on auto should play just fine, if your tv cant play 50 hz that is another story, some games cant be forced to other videomodes.

**Comment by DongVGH** [comment]
Well, that sucks. I will have to track down a NTSC iso even though most of them are unlabeled so that will take a while.

Thanks for the answer.
