### ISSUE TITLE
Baten Kaitos - Eternal Wings and the Lost Ocean: turns of Wii on game start

### ISSUE THREAD

**Issue by eku** [FIX94/Nintendont#655]
I've got the ISO from Archive.org (https://archive.org/download/EuropeanGamecubeCollectionByGhostware) . When starting the game the Wii immediately turns off. Loader is USBLGX.

**Comment by carnage702** [comment]
Quem wii shuts down jeans corrupt file check Your saves folder for a 0 kb file

**Comment by eku** [comment]
@carnage702 So what are you telling me?

**Comment by carnage702** [comment]
exactly what i told you... one file was created corrupt or got corrupt in the transfer so you have a corrupt file probably the raw file for the  save of that game, go to the saves folder look for a 0kb file and delete it.

shutting down wii has  the following implications
bad iso(could have become corrupt when passing to sd/usb)
bad save file(upon creation it was created badly so delete and let nintendont try again, this only happens upon creation, once its created it will never go bad)
bad ninconfig.bin (sometimes this file corrupts and needs to be deleted and  recreated by putting your settings on again and start a game)
bad controller.ini(sometimes ini files coorrupt and need a new one too.)
