### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by Cooltshadow99** [FIX94/Nintendont#656]
i have tested it with pikmin 2 and paper mario the thousand year door
pikmin 2 will go to the title screen and let me pick a file but wont go any farther 
paper mario wont even go to the title screen

idk what to do im using vwii on wii u homebrew channel version 1.1.2 ios58 v25.32 
nintendont loader v5.486 (wii u) firmware 58.25.32
please help

**Comment by carnage702** [comment]
take a picture of your nintendont settings.

**Comment by Cooltshadow99** [comment]
![3A664126-58FB-474B-AF8B-CBDCBBD35E1F](https://user-images.githubusercontent.com/34589864/54887159-ac3b4000-4e5d-11e9-888c-07031c4b7b2a.jpeg)

**Comment by carnage702** [comment]
Turn osreport,log and patch pal 50 to off, turn video to auto that should do ir.

**Comment by Cooltshadow99** [comment]
Ok that fixed pikmin 2 but paper Mario still is not working

**Comment by carnage702** [comment]
Make sure you saved the settings by pressing b after changing them and then start any game right after. Does pikmin freeze? Ir blackscreens? Could be a bad uso tough. Those settings start and play any game nos, well except languague that should be auto too.

**Comment by Cooltshadow99** [comment]
I’m ripping a fresh paper Mario iso but pikmin 2 is working now at least it’s letting me play the game

**Comment by carnage702** [comment]
Always confirm the iso MD5 with redump

**Comment by Cooltshadow99** [comment]
Ok I needed a fresh paper Mario iso it works now thank you
