### ISSUE TITLE
nintendont wireless controller problem

### ISSUE THREAD

**Issue by ihd05** [FIX94/Nintendont#657]
VID=2563
PID=0523
controller is not work on my wii. ı did .ini file with HID TEST. the other controllers are perfectly working.can someone help me?

VID=2563
PID=0523
Polltype=1
DPAD=1
DigitalLR=1
A=4,40
B=4,80
X=4,20
Y=4,10
Z=5,08
L=5,02
R=5,01
S=5,20
Power=5,80
Left=4,06
Down=4,04
Right=4,02
Up=4,00
RightUp=4,01
DownRight=4,03
DownLeft=4,05
UpLeft=4,07
StickX=2
StickY=3
CStickX=0
CStickY=1

**Comment by Missingphy** [comment]
what controller is it
