### ISSUE TITLE
video width and screen position not applying to game

### ISSUE THREAD

**Issue by manaboy** [FIX94/Nintendont#658]
Hi, so I saw a setting in nintendont that let's you increase the screen width and position it so the black borders on both left and right disappear. Trouble is, this setting doesn't transfer to the the game when loaded. My Wii (not WiiU) is set to wide-screen and hooked up to my smart TV via component, the game I've tried is Mario sunshine pal, seems to be the same with other GameCube games too.

**Comment by manaboy** [comment]
So basically the games all have black borders on the sides even when force progressive scan and wide-screen is on. The video width and screen position does not transfer into game loaded.

**Comment by carnage702** [comment]
you must change the setting, then press b and start a game right after without ever exiting nintendont so the setting change can be saved, that said those options are hacks and dont work for every game, some games will not be affected, when using width, some will even crash and freeze with width and center position changes.

**Comment by manaboy** [comment]
Thanks, I'll give it a go
