### ISSUE TITLE
Please add sources for HID_Test.dol

### ISSUE THREAD

**Issue by revvv** [FIX94/Nintendont#660]
Could you please publish the sources for controllerconfigs/HID_Test.dol?
I hope I haven't overlooked them.

**Comment by revvv** [comment]
Well, hope you haven't lost the sources. I would love the see them. Maybe I could add USB gamepad support to my project. (So far the theory.) Can I help somehow? Would money help??

**Comment by carnage702** [comment]
hidtest was not made by nintendont team, it was made by Crediar if memory doesnt fail me so you have to ask him if he is still around, while crediar created nintendont he made a proff of concept where it only played wind waker and then he made it opensource where anyone could continue his work thats where fix94 and some others picked it up and made nintendont what it is today, so you have to find crediar somewhere and ask him.

**Comment by revvv** [comment]
Thanks, I'll try that.
