### ISSUE TITLE
Usb controllers dont work in Zelda collectors edition 

### ISSUE THREAD

**Issue by AlexS2412** [FIX94/Nintendont#662]
for some reason they work on the menu but not ingame.

**Comment by carnage702** [comment]
turn native control to off in the settings.

**Comment by AlexS2412** [comment]
now it doesnt work at all.

**Comment by carnage702** [comment]
i need to see your nintendont  settings, take a picture of them and post it here.


also more info wii or wiiu?
if wiiu wiivc inject or vwii?
anything connected to the usbports besides the usb controller?
