### ISSUE TITLE
Nintendont freezes when saving and cutscenes appearing by using cheat codes

### ISSUE THREAD

**Issue by Epsiloniar** [FIX94/Nintendont#663]
Currently on the way by using cheat codes while playing megaman x command mission, if i go to any savepoint to save the game then i saved the game and before it was a success the game just freezes even after any text scenes, for example after a text scene right before the cutscene starts where i have to fight the first boss it also freezes the game, need help i can't continue like this :(

**Comment by carnage702** [comment]
probably the cheat codes has issues with nintendont, nintendont has very diferent setup from gc games and some cheat codes might work some might not.

**Comment by Epsiloniar** [comment]
all the cheat codes i have currently active are working fine

**Comment by carnage702** [comment]
if you turn cheat codes to off and the games doesnt freeze, it means thay are interfering with nintendont code even if they are working still.

**Comment by Epsiloniar** [comment]
alright i somehow managed to save the game without freeze while the cheats are on, i saved quickly as possible and turned cheats instantly off and staff are still there like all sub weapons and so on, not for an infinite amount but i don't care about it, i'm happy with that
