### ISSUE TITLE
GC adapter support 

### ISSUE THREAD

**Issue by weatmod** [FIX94/Nintendont#666]
which   GC adapter are supported and work with  wii u nintendon't?
  have tried 2 already  , they both work fine with  super smash wii u  but do not work at all with nintendon't using forwarders/injects , i start the games(autoboot) with wii mote and select do not use gamepad   but when the games load  no controller is detected

**Comment by carnage702** [comment]
most do work but official one is guaranteed, also  make sure you got native turn off, there is no guarantee for 3rd party  gc adapters tough.

**Comment by carnage702** [comment]
also you have anything connected to the usb ports besides wiiu gc adapter?

**Comment by weatmod** [comment]
> also you have anything connected to the usb ports besides wiiu gc adapter? is your gc controller connected in port 1 of the adapter?and take a picture of your nintendont settings.

yes i have  my external wii u formatted HDD in the bottom  rear USB port
i tried the adapters in the rear port and in the front ports  without success
i tried with native control on and off , most of my games are autoboot but i tried using a  nintendon't forwarder  and  and ISO on my SD card   same result ,i manually set the native control to off ,still not working 
ami not supposed to be able to use a HDD at the same time?

**Comment by weatmod** [comment]
both adapter work fine with smash wiiu    with the HDD connected   smash booting from the external HDD
 with non coldboot haxchi

**Comment by carnage702** [comment]
adapters always work fine on smash nintendont is not smash, it could be you are using an old version of the inject? older inject didnt support usb controllers at first, but its more likely the issue of them being thrid party and nintendont cant deal with them.

the only way would be to use vwii, run nintendont there if the adapter doesnt work on nintendont menu even on vwii its the adapter fault, or it might needs its own ini file which isnt the same as official gc adapter.

**Comment by weatmod** [comment]
> adapters always work fine on smash nintendont is not smash, it could be you are using an old version of the inject? older inject didnt support usb controllers at first, but its more likely the issue of them being thrid party and nintendont cant deal with them.
> 
> the only way would be to use vwii, run nintendont there if the adapter doesnt work on nintendont menu even on vwii its the adapter fault, or it might needs its own ini file which isnt the same as official gc adapter.

it is version v5.486

my vwii is not modded so i canlt test it by running from there
guess i will have to buy the mayflash 4 port adapter and try that one then
that one should work right
also i noticed that a lot of these GC adapters now all say "updated version"
 they have a switch  that says PC /WII U switch
so maybe since they updated these things to work with sitch it has  broken  compatibility  for nintendon't ?
 i am afraid if i buy a mayflash it will be  "updatrd version" too and not work

**Comment by carnage702** [comment]
well original ones were 20$ when they were in stores maybe you can find an original used somewhere for cheap, or even a store that has them in stock  since smash switch didnt came out that long ago.

i cant promise you that 3rd partys will work.i only own 2 original ones, one wiiu and one switch and they both work perfectly.

**Comment by weatmod** [comment]
> well original ones were 20$ when they were in stores maybe you can find an original used somewhere for cheap, or even a store that has them in stock since smash switch didnt came out that long ago.
> 
> i cant promise you that 3rd partys will work.i only own 2 original ones, one wiiu and one switch and they both work perfectly.

what do you man switch? there is an original GC adapter for switch and it works on nintendon't wii u?
i though there was only the wii u one
 
also what about these .ini files, i don't think i have one should i?
 i mean ami supposed to  download the ,ini file for the GC adapter and put it  someplace on my wii u Sd card? because in only have the boot.dol ,  meta.xml , and  image,png files in the nintendon't folder am i supposed to have the GC adapter .ini files in there?
what are those .ini files for and where do they go? or are they built into the boot.dol ?

i tried gamestop but they only sell the orginal adapter and a nyko one and i have to drive out of state to get the  original one

**Comment by carnage702** [comment]
there was the adpater that came with smash bros wiiu and the some that came with smash bros ultimate, its the same adapter but one has a wiiu logo and the other  has a nintendo logo, they are 100% the same nintendo just changed the logo to nintendo becuase saying wiiu and coming in the switch bundle would be weird lol.

**Comment by carnage702** [comment]
you dont need ini files if your controller is already coded in, smash adapter is coded in, but third partys might have a diferent codding start up and nintendont cant use them, i think mayflash smash adapter was coded in but im not sure if newer versions changed the codding or not.

**Comment by emuDrache** [comment]
i use these  
https://www.amazon.de/Gamecube-Controller-Adapter-für-Nintendo/dp/B00YH3NWTW
and they work fine for the most part. just kinda freak out the wiimotes on occasion. but easily fixable.  kid plays smash bros / mario kart with them.

**Comment by weatmod** [comment]
i just found this  thread on GBA temp from  couple months back
https://gbatemp.net/threads/nintendont-and-third-party-gc-adapter.530901/

seems like he had similar issue and the 4 port mayflash adapter solved it 
i am going to try ordering the 4 port mayflash  one from Amazon and returning the other 3rd party one i  ordered  on there
this is the  one i got that  doesn't seem to work so steer clear of it
https://www.amazon.com/GameCube-Adapter-Controller-Buttons-Nintendo/dp/B07MXCX6G8/ref=sr_1_11?keywords=gc+adapter&qid=1555618227&s=electronics&sr=1-11

my  friend let me borrow his and it's different  and he got it from Amazon recently too but i can't seem to  find it on there it has  different name than the ones i see

would be nice if  we could get a compatibility list of  known working and non working adapters
the guy that made the thread on that ISO site said he had luck with  another offbrand one he got from ebay, i guess he just got really lucky


the one my friend lent me looks like this one but it has  name on it i forget the name but it begins with a K i think and when i searched that name on amazon where he got it it didn't return any results 


https://www.amazon.com/Upgraded%E3%80%91-Gamecube-Controller-Lxuemlu-Nintendo/dp/B07MCBST5V/ref=sr_1_18?keywords=gc+adapter&qid=1555618418&s=electronics&sr=1-18

**Comment by weatmod** [comment]
> you dont need ini files if your controller is already coded in, smash adapter is coded in, but third partys might have a diferent codding start up and nintendont cant use them, i think mayflash smash adapter was coded in but im not sure if newer versions changed the codding or not.

yup it was the adapter the mayflash one worked
but i wonder how long it will last i read that it is not a good quality and i had trouble with it at 1st
i tried simpsons road rage with the other 2 adapters it always said no controller found with the mayflash it didn't give that message but the controllers were not working i had to unplug them and plug them in again i tried every port twice and it wasn't working then it finally worked , seems like the ports are not good quality on the mayflash the chinese ones had better quality port connectors i think
i see lots of reviews on Amazon where they report that their mayflash worked good a t 1st but then stopped working shortly after they got it
Edit / Delete Edit Post    Quick reply to this message Reply    Reply With Quote Reply With Quote    Multi-Quote This Message
