### ISSUE TITLE
Taxi 3 (Le Jeu) (France) : Left Deadzone issue (GC Controller)

### ISSUE THREAD

**Issue by Catarax** [FIX94/Nintendont#668]
**Taxi 3 (Le Jeu) (France)
Nintendont v5.486
Wii U
No particular hacks**

When you play the game, the car always go to the left a bit making the game very difficult, i have no issues like that on all Gamecube games I have and tried with 4 different official gamecube controllers.

**Comment by carnage702** [comment]
if you are using the new gc controllers the ones that came with smash bros ultimate that happens on every game, nintendo made them diferent from original gc controllers and wiiu smash controllers so they drift on everygame, but some games only take measurements from one value up others take them very tightly.

**Comment by Catarax** [comment]
Thanks for the information, well i'm using an original purple gamecube controller, I notified the same thing with Smashing Drive, i think some driving games are really sensitive to that.

**Comment by carnage702** [comment]
if your using a wii you can enable native control to get perfect controls, now if your sticks are worned out and dont center correctly then its another story.

**Comment by Catarax** [comment]
There was still the deadzone issue on a Wii U Pro Controller, it's not about my gamecube controllers only.
