### ISSUE TITLE
Capcom vs. SNK 2 EO resists custom video widths.

### ISSUE THREAD

**Issue by vaguerant** [FIX94/Nintendont#670]
It looks like this game is simply ignoring the video width values set in Nintendont. The game doesn't seem to display any wider no matter how they are set.

**Comment by carnage702** [comment]
video width is an hack same as widescreen, it works on some games it doesnt afect some and straight up crashes others, its not 100% compatible and probably never will.

**Comment by vaguerant** [comment]
I figured that was the case, I just thought perhaps there was still work being done on the hack to broaden its compatibility. If not, feel free to close the issue. :)

**Comment by Wolfy76700** [comment]
That being said, there is a 16/9 cheat for Capcom VS SNK 2 EO that makes it widescreen if you do use the NTSC-U version

$16:9 Widescreen (From the Dolphin Wiki)
042B61A8 3FFC71C7
C2094748 00000003
EC011028 C94280E8
FD0A0032 FD004050
60000000 00000000
0403F5CC C0828730
042B65C0 46FFFFFF
042B65C4 46FFFFFF
