### ISSUE TITLE
ps4 dualshock v2 not working

### ISSUE THREAD

**Issue by Missingphy** [FIX94/Nintendont#671]
it simply doesnt work. ive tried more than 10 usb cables and all the usb ports on the wii u and wii but nothing. even a controller.ini doesnt work. what am i doing wrong?
i believe that it should have worked for somebody if a ps4v2.ini exists

this is the .ini file i found online (fix94/nintendont/controllerconfigs)
[DualShock 4v2]
VID=054C
PID=09CC
Polltype=1
DPAD=1
DigitalLR=2
A=5,40
B=5,20
X=5,80
Y=5,10
Z=6,02
L=8,F0
R=9,F0
S=6,20
Left=5,06
Down=5,04
Right=5,02
Up=5,00
RightUp=5,01
DownRight=5,03
DownLeft=5,05
UpLeft=5,07
StickX=1
StickY=2
CStickX=3
CStickY=4
LAnalog=8
RAnalog=9
Power=6,10
found it here: https://github.com/FIX94/Nintendont/blob/master/controllerconfigs/controller_ps4v2.ini

**Comment by carnage702** [comment]
did you put the ini file on the root of the device that has the isos renamed to controller.ini?

**Comment by Missingphy** [comment]
> did you put the ini file on the root of the device that has the isos renamed to controller.ini?

no, let me try that

**Comment by Missingphy** [comment]
> did you put the ini file on the root of the device that has the isos renamed to controller.ini?

nope, still doesnt work

**Comment by carnage702** [comment]
do you have native turned off in the settings? you got anything else connected to the usb ports/ gc ports/ wiiugamepad?

**Comment by Missingphy** [comment]
i am using a wii u so native is off. can the wii u gamepad connect with usb?

**Comment by carnage702** [comment]
if you are using a wii inject with a  wiiu gamepad , the gamepad will take player one, and no you cant use wiiu gamepad by usb it works normaly wirelessly lol if you use a wii inject version of nintendont.

tbh i only have the first version of the ps4 controller so i have no idea if the newer ones work or not never used them, on nintendont menu if you press like the ps button of the ps4 controller and try to use the dpad to move up and down on the gamelist does it do anything?

**Comment by Missingphy** [comment]
no, im using nintendont from the hbc. when i press ps button, flashes white and then turns off. already tried connecting controller before launching nintendont, when inside the nintendont menu, and when a game has fully loaded

**Comment by carnage702** [comment]
then whoever made that ini made it badly or there is more than one new version of them with new pid/vid, like i said i dont own the new version of those so i cant do anything, but yeah if you want find an inject wii channel of nintendont and you can use wiiu gamepad wich screen and everything for nintendont from wiiu menu directly(no rumble tough because wii injects makes gamepad act like CC wich doesnt rumble).

**Comment by carnage702** [comment]
also is nintendont app on sd card or usb? if its on sd  try to put the new ini renamed to Controller.ini on the SD root aswhell.

**Comment by Missingphy** [comment]
app is on sd

**Comment by Missingphy** [comment]
already tried that as well

**Comment by carnage702** [comment]
well cant help you more, got only a launch version of ps4 controller, 2 ps3 controllers, wiiu gc adapter with gc controllers as my hid devices they all work.

**Comment by Missingphy** [comment]
np. i will try with the magic ns dongle then. if it works, ill be closing the issue and requesting an add for the magic ns .ini on the repo.
