### ISSUE TITLE
Animal Crossing not working when using imported RAW save file

### ISSUE THREAD

**Issue by 03bgood** [FIX94/Nintendont#674]
The game just shuts off my Wii U, after the Wii Mode screen shows up.

I'm using the game that is installed via Wii U on my USB and not the Nintedont app. It isn't an ISO file, its a custom inject VC GCN game that also uses the Wii U GamePad.

I can confirmed that my old save file still works; however, the new imported one just shuts off my Wii U.

**Comment by carnage702** [comment]
when wii shuts down means a file is corrupt, so your raw file is corrupt, or ninconfig.bin or even the iso itself.
