### ISSUE TITLE
Crash on "Checking for storage devices" when starting up

### ISSUE THREAD

**Issue by libjet** [FIX94/Nintendont#675]
On my Wii when I run Nintendont from the hbc it works once, and then almost never again. It seems I have to delete and copy over the app everytime I want to run it, and I have no peripherals attached apart from the SD card and a GC controller. Sometimes I also get a green screen but most of the time it just returns back to the loader.

**Comment by carnage702** [comment]
make sure your sd or usb dont know what you are suing are decent enough and if its an SD card if its not locked, seems nintendont cant read write most of the time, due to slow usb device or sd card, its specialy bad if your using a flashdrive.
