### ISSUE TITLE
THPS3 US Version Will never Crash

### ISSUE THREAD

**Issue by james1222312334** [FIX94/Nintendont#676]
Can you make an update that prevents THPS3 From Crashing on the Skater Select Screen?

**Comment by carnage702** [comment]
if its crashing is becuase you have imcompatible settings turned on take a picture of your nintendont settings.

**Comment by james1222312334** [comment]
![2019-05-29-140349](https://user-images.githubusercontent.com/43114648/58580463-2780ef80-821b-11e9-89e5-d4aad8e06857.jpg)

**Comment by carnage702** [comment]
so many hard settings lol, lots of them can make any game crash.


turn off force widescreen and force progressive
turn video width to zero or auto whatever value its defualt.

then it should works its one of this or even more than one that is making it crash, if it works just run then on one by one to see which is imcompatible with this game.

**Comment by james1222312334** [comment]
I can make one Specific Inject from TeconMoon's logic...

**Comment by carnage702** [comment]
some games are imcompatible with certain settings, it doesnt matter if injected or not lol, if your foce the same settings on the inject you get the same result.
