### ISSUE TITLE
Colors :  1:1 Shrunk FST CISO Multi

### ISSUE THREAD

**Issue by DanielBr0wn** [FIX94/Nintendont#681]
Hi, I'm having a problem with starting up games (this is my first time using Nintendont) 
Every time I open up the files in my sd card it says Colors :  1:1 Shrunk FST CISO Multi.
I don't know if this is an easy fix or if this is something else 
My version number is v5.486
![IMG_20190625_082942](https://user-images.githubusercontent.com/52206540/60102494-6ffcd180-9723-11e9-9144-e6e8f3a36bff.jpg)
![IMG_20190625_083053](https://user-images.githubusercontent.com/52206540/60102594-9c185280-9723-11e9-81fb-c84f62957094.jpg)

**Comment by GerbilSoft** [comment]
That's a color code to indicate which format each disc image is in.

The *actual* problem is it isn't detecting the disc images on your SD card.

**Comment by DanielBr0wn** [comment]
Ok, thanks. I was never going to figure this out on my own

**Comment by carnage702** [comment]
probably have the wrong path it should be 

SD:games/anyname/game.iso
