### ISSUE TITLE
Triforce: Virtua Striker 4 Controller Calibration issues on GamePad on NINTENDONT FORWARDER

### ISSUE THREAD

**Issue by olo85** [FIX94/Nintendont#682]
Request is for the following two Triforce games on NINTENDONT:
Virtua Striker 4
Virtua Striker 4 ver.2006

I've been testing Triforce games using the Nintendont forwarder.
Both games boot fine, however the  Wii U GamePad controller is all screwed up, it seems the controller is stuck in the up position.

At the CALIBRATION boot screen I tried to move UP/DOWN/LEFT/RIGHT and I could see the numbers scroll through. On the other hand, my DS4 HID usb connected pad reacts perfectly to the calibration.
So basically player 1 is forced to use a Wii U GamePad that does not calibrate correctly, while player 2 goes alright with whatever joystick one may use (usb, bt, GC adapter...).
Maybe one can use two Wii U Pro controllers instead, bypassing the Gamepad? Perhaps it's problem with the only "forwarder version" of NINTENDONT, and it's better to pass through vWii and HB to solve the problem?

Any chance to go through the issue, Wii U is the best console at the moment to run almost natively Triforce games, it's a pity since this GamePad issue does not allow to appreciate VS4 in full multiplay.
Wanna also thank you in advance for your amazing job that uplifts the hb scene to new levels!

**Comment by carnage702** [comment]
just dont use the gamepad? lol you can star vwii injects saying you dont want to use a the gamepad and use a wiimote to start it, or you can just take the wiiu gamepad out of range from wiiu and not turn it back again.

**Comment by olo85** [comment]
@carnage702 
Thanks for your reply.
You did mention vWii specifically, but the title of the requests says clearly that I am using a forwarder. So If I get this straight, better to access NINTENDONT through vWii the classic way where I can bypass the gamepad?
On the forwarder, at the gamepad compatibility game screen i can not tap the "no button" since at the next screen the gamepad nor the Wii Remote work to proceed any further, hence I am stuck to the very only choice of the "yes use the gamepad".
Any clue why this happens? May it be a forwarder related bug?

**Comment by carnage702** [comment]
maybe your fowarder is broken for me it says this title supports the gamepad do you want to use it i choose no and then for the next click you need the wiimote to start the fowarder, i can do this on my fowarder so no idea on yours.

**Comment by olo85** [comment]
@carnage702 
Alright then.
I'm gonna try a different forwarder.
Or, I will switch to vWii.
Question is, once inside a correctly working NINTENDONT, how do I perform a multiplay, specially on TRIFORCE VS4 ver.2006?
A part from this gamepad calibration issue, I am currently able to connect one and only one DS4 USB controller via HIDtoVPAD, no matter what I do, once in game the second one is not recognized altough HIDtoVPAD allowed me so before.
Maybe I can purchase a Wii U Pro controller and use it as a second controller alongside the DS4 HIDtoVPAD?
Thank you for your clarity anyways.

**Comment by carnage702** [comment]
nintendont only supports one usb controller at a time so no you will never be able to do 2 ps3/ps4 controllers.

Also i dont recall triforce games having multiplayer support, maybe im wrong but that was never coded imo.

you can do multiplay on normal gc games with diferent controllers like 
player one ds4, player 2  wiiu pro, player 3 wiimote+classic controller and so on, but only one hid controller at a time.

**Comment by olo85** [comment]
Well, I actually did succeed in performing a 2 player match in Virtua Striker 4 ver.2006 (TRIFORCE of course) but, as I stated before, the calibration of the GamePad was a failure and the left stick would stuck in down position in my case, with the player 2 controlled by a DS4 perfectly calibrated and working instead. So I guess I need in any case a Wii U Pro Controller for the second player once I will be able to move over the issue of the forwarder.  Now I have clearer ideas anyways. Thank you sir.

**Comment by carnage702** [comment]
you can get wiiu pro controller(official) fake ones usualy dont work wiimotes,wiiupros or even classic controllers.

so wiiu pro,wiimote+Classic controller,wiimote+classic controller pro

**Comment by NG363** [comment]
https://gbatemp.net/threads/nintendont.349258/page-1196


> Request is for the following two Triforce games on NINTENDONT:
> Virtua Striker 4
> Virtua Striker 4 ver.2006
> 
> I've been testing Triforce games using the Nintendont forwarder.
> Both games boot fine, however the Wii U GamePad controller is all screwed up, it seems the controller is stuck in the up position.
> 
> At the CALIBRATION boot screen I tried to move UP/DOWN/LEFT/RIGHT and I could see the numbers scroll through. On the other hand, my DS4 HID usb connected pad reacts perfectly to the calibration.
> So basically player 1 is forced to use a Wii U GamePad that does not calibrate correctly, while player 2 goes alright with whatever joystick one may use (usb, bt, GC adapter...).
> Maybe one can use two Wii U Pro controllers instead, bypassing the Gamepad? Perhaps it's problem with the only "forwarder version" of NINTENDONT, and it's better to pass through vWii and HB to solve the problem?
> 
> Any chance to go through the issue, Wii U is the best console at the moment to run almost natively Triforce games, it's a pity since this GamePad issue does not allow to appreciate VS4 in full multiplay.
> Wanna also thank you in advance for your amazing job that uplifts the hb scene to new levels!

Time set 5 minutes
004768E0 0000000A
004768E1 0000000A

Game difficulty very easy
004768DC 00000000

Virtual time real
004768DD 00000002

Event mode on
004768DE 00000001

Advertise sound on
004768DF 00000001

Golden Goal time 3 minutes
004768E2 00000007
004768E3 00000007

Penalty knockout system real pk - Only comes into effect during quarter / semi final stages.
004768E4 00000004
004768E5 00000004
