### ISSUE TITLE
Compiling Nintendont problem

### ISSUE THREAD

**Issue by 64801965** [FIX94/Nintendont#683]
Building Nintendont loader

/opt/devkitpro/msys2/usr/bin/make -C loader
make[1]: Entering directory '/home/Terny/Downloads/nintendont/loader'
main.c
C:/Users/Terny/Downloads/nintendont/loader/source/main.c:40:10: fatal error: kernel_zip.h: No such file or directory
#include "kernel_zip.h"
^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/opt/devkitpro/devkitPPC/base_rules:18: main.o] Error 1
make[1]: *** [Makefile:108: build] Error 2
make[1]: Leaving directory '/home/Terny/Downloads/nintendont/loader'
make: *** [Makefile:81: loader] Error 2

**Comment by krystal-starfox11111** [comment]
I also have that exact same issue. I don't if it really is just that file missing or if it might be that the latest version of Devkitpcc is incompatible. And unfortunately they took down all their old versions, so I can't even test if that really is the issue.
