### ISSUE TITLE
megaman x collection dont work with component TV

### ISSUE THREAD

**Issue by Dan92xD** [FIX94/Nintendont#684]
can you do a code or patch to cna play megaman x collection on gamecube using component  tv ?? the game just work with rgb red white and yellow

**Comment by TwilightSlick** [comment]
Mega Man X Collection is one of the few GameCube games to run in 240p resolution, which many newer TV's and monitors don't tend to support over component video connections.

Try turning "Force Progressive" on to force the game to run in 480p. That should solve your problem.

**Comment by GB-CG** [comment]
Mine works by using a upscaler like the Framemeister, but a cheaper option like the OSSC will work with it too, if not better. Granted that you don't use composite/S-Video for gaming, that is.
