### ISSUE TITLE
Game ID for need for speed most wanted gc Germany 

### ISSUE THREAD

**Issue by Toolazytochoose** [FIX94/Nintendont#685]
I try to convert ar codes to ocarina and need the game id

**Comment by carnage702** [comment]
you use internet browser to run cfw which is needed for all homebrew on wiiu to work.

if you got haxchi(needs a legit ds vc title purchase) you can improve it to  be cbhc and then you get cfw on boot with the console so no more need for internet you start the wiiu and can run any fowarder from nintendot to installed games and dlc and such.

**Comment by Toolazytochoose** [comment]
Pls help

**Comment by carnage702** [comment]
what exactly do you want?

**Comment by Toolazytochoose** [comment]
GOWE69 is the American id, and i need the id fir the German version

**Comment by carnage702** [comment]
dont know what the 69 is for but the german version just replace the E with a d

GOWD

**Comment by Toolazytochoose** [comment]
Thx, idk too but this is the id

**Comment by GB-CG** [comment]
It is [GNDD69](https://www.gametdb.com/Wii/GNDD69).
