### ISSUE TITLE
[Request] virtual memory card selection/switching 

### ISSUE THREAD

**Issue by Gameplayer9198** [FIX94/Nintendont#687]
Some games only allow one save slot per card. So I am requesting a selection/switching screen or something to choose a card before boot or during gameplay.

**Comment by carnage702** [comment]
you kinda already do that nintendont has both multi and individual memory card options, multi creates a single raw file nimem.raw or whatever its called and every game saves there when multi is set to on, while if multi is set to off it creates individual mc files gameid.raw so by playing the game with multi set to on you will load and save multi card save and with multi set to off you will load and save on the individual mcemu.

**Comment by krystal-starfox11111** [comment]
I also agree that this should be a feature. Yes, there is a feature that already allows using individual memory card files per game, but that essentially limits it to only 2 slots, and also doesn't allow multiple games on that other card. So this feature would make it much more convenient than having to use a separate file manager every time to rename a memory card every time you switch.

I'd also like a feature that allows using memory cards in a custom directory and file name.

**Comment by carnage702** [comment]
there is already a request to add multiple memory cards per game.
