### ISSUE TITLE
Stuck at "loading IOS58 kernel"

### ISSUE THREAD

**Issue by pakodx** [FIX94/Nintendont#688]
Tried to play smash melee and it froze while trying to boot the game ( I think in the part that says loading HDD)
I restarted my Wii, and now I can't use nintendont anymore at all

My Wii is on 4.2U
The melee was US version 1.02
I compressed it using DMToolbox
I literally just finished setting nintendont for the first time tonight, it was like the 3rd game I tried
I'm on the latest nintendont

**Comment by carnage702** [comment]
probably got a corrupt file on usb or SD , delete ninconfig.bin, make sure you dont have any 0kb raw files on the save folder.Make sure osreport and log are set to off in the settings.

**Comment by pakodx** [comment]
There was a 0kb nincfg file at the root of my SD card (even though nintendont was in a USB drive ), I deleted it and made a fresh nintendont install on my SD card but it's still happening
I couldn't find any save folder, and I don't know how to change those settings

**Comment by carnage702** [comment]
where do you have your games? sd or usb? if so go to both devices looking for saves folders.

**Comment by pakodx** [comment]
I have the games on usb, I checked the games folder but I didn't find any saves folder in there

**Comment by carnage702** [comment]
The saves folder are on the root of USB or sd, they aren't inside the games folder, unless you never actually turned memory card emulation to on

**Comment by pakodx** [comment]
I was using real memory cards, so I never turned it on ( didn't know it was an option tbh )

**Comment by carnage702** [comment]
oh ok, so all i can think off is bad sd card or locked sd card, got anything connected to memory cards slots like microphone gc? or usb ports?

**Comment by pakodx** [comment]
I have connected to my Wii:
-sd card (2gb, class 2 )
-pen drive (16gb Kingston taurus )
-128 mb gc memory card
-64 mb gc memory card

At first I was using it from my pen drive, then that error happened
I tried removing the SD card and booting it from USB and it didn't work
I tried booting from the SD card without the USB connected and it didn't work either

For the sake of this reply, just now I tried removing the memory cards and nintendont worked
I plugged them back and checked on the Wii system if there was a corrupt save or something and they were both ok
So I tried nintendont once again and now it works
So I tried booting smash Bros again since it's what started this and it worked this time

Thanks for your help, I think my issue is solved

**Comment by carnage702** [comment]
nintendont sometimse has issues with slot b memory cards so that can be the issue.

**Comment by bluefunoodle311** [comment]
> nintendont sometimse has issues with slot b memory cards so that can be the issue.

Thanks so much for this. Went back to play my softmodded Wii after a good while of it sitting stagnant and ran into problems launching games. Scoured the web and troubleshoot a bunch of unnecessary things. Stumbled across this post and realized, "you know what?!" I had plugged a GC microphone into memory card slot B after finding one at Goodwill. Unplugged it and PRESTO, games are launching just fine now.
