### ISSUE TITLE
Nintendont is stuck on "checking storage devices"

### ISSUE THREAD

**Issue by Nebzilla** [FIX94/Nintendont#689]
Everytime I try to use Nintendont with my flash drive plugged in it freezes on "checking storage devices". Nintendont works fine without the flash drive plugged in though. I have IOS58 and my flash drive works fine with USBLoaderGX. What could be the problem?

**Comment by carnage702** [comment]
nintendont is much more picky with usb stuff so you have your isos on sd? or you have them on another flashdrive?
