### ISSUE TITLE
Virtual memcard doesn't work in certain games

### ISSUE THREAD

**Issue by bruhmoment69420** [FIX94/Nintendont#690]
Certain games like the original Super Monkey Ball don't work with a virtual memory card. It just shuts off my Wii when I try to load it with one. Please fix this

**Comment by carnage702** [comment]
you probably have a corrupt raw file on your SD or usb, go to the saves folder see any 0kb file and delete it.

**Comment by aviwad** [comment]
@bruhmoment69420 I love your username <3

**Comment by bruhmoment69420** [comment]
thx

**Comment by carnage702** [comment]
so did you see the corrupt file?

**Comment by bruhmoment69420** [comment]
i managed to fix it a few months ago

**Comment by bruhmoment69420** [comment]
ok boomer
