### ISSUE TITLE
Emulated Memory Issue Zelda Collector's Edition

### ISSUE THREAD

**Issue by ThomasCapella** [FIX94/Nintendont#696]
My brother has a save file on Ocarina of Time that he's been playing for a few days and now it's saying "The memory card in Slot A is damaged and cannot be used." I tried loading up Wind Waker just to see if it did it on any other games and it worked fine but whenever you try to load something on Collector's Edition it just doesn't work. I've tried deleting the emulated memory file and even changing the folder to not be Read Only. I have no idea what else to do.

**Comment by carnage702** [comment]
If memory card multi is set to off Nintendont makes one per game, probably the card that the collection uses got corrupted, take a picture of your Nintendont settings and post them here.
