### ISSUE TITLE
PAL Luigi's Mansion partially broken on Wii VC by "Start in PAL60 mode" patch

### ISSUE THREAD

**Issue by AuroraWright** [FIX94/Nintendont#697]
The "Start in PAL60 mode" patch in https://github.com/FIX94/Nintendont/blob/master/kernel/Patch.c#L3659-L3667 partially breaks the game if coupled with the "force progressive" setting (which it's meant to be used with anyway) when the game is injected into a Wii VC ISO on Wii U. The game properly displays on the gamepad but fails to output on TV. Recompiling the loader without the above patch and using the game's built-in 50/60 Hz selector with this cheat (the v2): https://www.gc-forever.com/forums/viewtopic.php?f=38&t=2161&p=24418 to run the game in PAL60 works properly with the "force progressive" patch instead.

**Comment by Catarax** [comment]
Have the same crash

**Comment by Catarax** [comment]
Disabling Progressive and PAL50 options fixe the game.

**Comment by AuroraWright** [comment]
The patch should be either removed or fixed imo as it makes it impossible to run the game in 480p without a custom build of the loader.
