### ISSUE TITLE
Play Virtua Striker 2002 with DPad

### ISSUE THREAD

**Issue by grego-maradona** [FIX94/Nintendont#698]
Hello,
I may be missing something, is there a way to play the triforce version of the game with the dpad. the gamecube version allows to play with the analog joystick and the dpad.
Thanks.

**Comment by carnage702** [comment]
crediar did the codding for triforce games, so you would need to change that, possible ? yes, will anyone do it? probably not, becuase its complex code and people who do that have almost disapeared.
