### ISSUE TITLE
Long loading times for listing games on usb

### ISSUE THREAD

**Issue by animekai** [FIX94/Nintendont#701]
I have this problem, I had all gamecube isos, and I said all fullrom set of gamecube games, 670gb of games on a Hdd USB.
The problem comes when listing the games takes as long as 2 minutes for display all games, loading games then is not a problem, but changing games each time takes 2 or more minutes, maybe is because the speed of the hard drive through the USB, but I think the problem is the many games trying to get on list. 
There is any way to just make 1 time scan list, and then just load the list faster? Like loading a listing file with the list of games for faster listing?
I hope I had explain it correctly.

Edit 1: By the way, there are 666 game isos, it took 2 minutes 50 Seconds, to list all the games, almost 200 games per minute xD, there are no more games to add, plz fix the loading listing plz

**Comment by animekai** [comment]
By the way, there are 666 game isos, it took 2 minutes 50 Seconds, to list all the games, almost 200 games per minute xD, there are no more games to add, plz fix the loading listing plz

**Comment by GerbilSoft** [comment]
Nintendont currently reads each disc image to get the game ID from the header. This probably isn't ideal, but it's the only way to definitely identify each game.

Perhaps we could implement some sort of cache file based on file modification times.

**Comment by animekai** [comment]
Yeah, a cache file sounds great, and a manual option to scan the list, or an auto detect when changes are made like when adding new isos, or modifying the iso name etc, or just the cache file sounds good.

**Comment by SieKensou** [comment]
I asked for this long ago: https://github.com/FIX94/Nintendont/issues/500
I hope it can be implemented as it would save much time when you have a lot of games.
