### ISSUE TITLE
Nintendo GameCube Game Boy Advance Cable not Working on Nintendont?

### ISSUE THREAD

**Issue by aroundanera** [FIX94/Nintendont#704]
Pokémon Box: Ruby & Sapphire is the particular game I'm using on Nintendont, and the Nintendo GameCube Game Boy Advance Cable is not doing anything. The Game Boy Advance Pokémon game I'm using is Pokémon Sapphire Version, in which I obtained the Hoenn Pokédex and saved at a Pokémon Center. Despite Pokémon Box: Ruby & Sapphire being the only game I have on Nintendont, it works on compatible Nintendo GameCube game discs. The system I am using is Wii.

**Comment by carnage702** [comment]
you need a wii with gc ports, turn on Native to on nintendont settings, this is the only way for the cable to work, also the cable better be official most 3rd party ones dont work.
