### ISSUE TITLE
Rumble not working on WiiU Gamepad

### ISSUE THREAD

**Issue by nintendonut** [FIX94/Nintendont#706]
Rumble doesn't seem to be working on the WiiU Gamepad. I am using WiiVC injection with the Nintendont Forwarder. Rumble works fine in this setup on WiiU Classic Controllers. Should rumble be supported in this setup, and if not, can it possibly be fixed by setting up a controller.ini?

**Comment by FIX94** [comment]
rumble is not supported by the gamepads firmware in wii vc mode, you would have to design your own custom gamepad firmware and flash it or something which is most certainly not going to happen.

**Comment by boreals-back-again** [comment]
@FIX94 
> rumble is not supported by the gamepads firmware in wii vc mode, you would have to design your own custom gamepad firmware and flash it or something which is most certainly not going to happen.

I'm on [Vanilla](https://github.com/vanilla-wiiu/vanilla) which is basically that.
