### ISSUE TITLE
Wrong sav. File?

### ISSUE THREAD

**Issue by aroundanera** [FIX94/Nintendont#710]
![39456535-F834-47AC-8EDC-46504B4B1EFC](https://user-images.githubusercontent.com/56208968/66620593-ad884c00-eba6-11e9-8b1b-32b52d6d5e51.jpeg)
I wanted to transfer a special Celebi on my Pokémon Emerald Version rom that I play on my Game Boy Advance Super SD Flash Cart, can someone explain why that I can’t seem to save the Pokémon in one of my boxes in the rom’s save file?

**Comment by carnage702** [comment]
That is something you must check online, this has nothing to do with Nintendont
