### ISSUE TITLE
Freeze when using GCN controller adapter with WiiU injects

### ISSUE THREAD

**Issue by missionfloyd** [FIX94/Nintendont#712]
Using Nintendont 6.489 and Nintendont autoboot forwarder 1.2

Starting injected games with the official GCN controller adapter (WUP-028) connected causes the WiiU to freeze on a black screen. I enabled Log and OSReport, but no file is created when this happens.

Doing the same without it connected works normally, as does launching Nintendont from HBC with games on SD card, with or without the adapter connected.

**Comment by carnage702** [comment]
delete any controller.ini that you have on the root of your sd/usb and maybe delete your ninconfig.bin one of these files is corrupted.

**Comment by missionfloyd** [comment]
I deleted the controllers folder, controllers.zip, and nincfg.ini, it still freezes. I also tried deleting the memcard file, then it freezes on 'Initializing virtual 251-block memory card... 2048 of 2048 KiB written'

I've tried moving games to NAND to rule out the hard drive, and tried different SD cards. Still freezes only if the adapter is connected when it starts.

**Comment by carnage702** [comment]
So is the adapter official? Or 3rd party? You got anything else connected to USB ports? Also controller.ini is in the root if there is one. Maybe your Nintendont boot.dol itself is corrupted try deleting and redownload.

**Comment by missionfloyd** [comment]
It's an official Nintendo adapter. I have a WiiU-formatted HDD on the rear USB ports. No controller.ini anywhere, and I have tried redownloading boot.dol

**Comment by carnage702** [comment]
did you tryed unplugging the wiiu formated hdd too?

**Comment by missionfloyd** [comment]
Yes, I tried copying a game to NAND and running it with the hard drive unplugged. Same result.

**Comment by carnage702** [comment]
Tryed starting a game with it unplugged and then plug it mid game?

**Comment by missionfloyd** [comment]
That works.

It'd be nice if I could leave it plugged it in, but okay.

**Comment by Lolithetrolli** [comment]
I have a somewhat related issue that I'd like to share. I have a Nyko Wii U Charge Link cable connected to my Wii U to keep my controller charged at all times. Well, every GameCube injection that I installed would crash like 10 seconds into the game, and I couldn't figure out why for a few days. I later ran the injections with the cable disconnected, and magically the games ran perfectly. Every time I connect the charge cable mid game the Wii U will crash. So I think that the issue has to do with certain peripherals using too much power.

**Comment by missionfloyd** [comment]
I tried some old builds; the issue seems to start with 274699000ccf0b6b8e5fbb8a5cbb50a8272334f4

**Comment by bck427** [comment]
> I tried some old builds; the issue seems to start with commit [2746990](https://github.com/FIX94/Nintendont/commit/274699000ccf0b6b8e5fbb8a5cbb50a8272334f4)


Hey floyd, I've had the same problem. Did you get any old builds to work? I've tried everything and this is such an annoying problem.

**Comment by missionfloyd** [comment]
Yeah, builds prior to that one don't seem to have this problem.

**Comment by bck427** [comment]
That's very weird. I might be a total noob, but is there somewhere I can download those earlier builds? I've looked everywhere and can't find them.

**Comment by guoliang** [comment]
> 
> 
> That's very weird. I might be a total noob, but is there somewhere I can download those earlier builds? I've looked everywhere and can't find them.

Usually you could if they had put releases in the release page
https://github.com/FIX94/Nintendont/releases

But it is empty. So either you need to build it from source, or find somewhere else to download older builds.

**Comment by GB-CG** [comment]
@bck427 @guoliang  Look here: https://github.com/FIX94/Nintendont/commits/master/loader/loader.dol
then browse a repository by clicking on the '<>' button then look at Nintendont/loader/loader.dol

**Comment by bck427** [comment]
Thank you so much! I'll try to see if this solves the problem later today.

**Comment by missionfloyd** [comment]
Here's the one I've been using, It's version 5.486
https://github.com/FIX94/Nintendont/blob/7be1b6df41f07f39fd8e67dfd8be7b0b68209fc7/loader/loader.dol

**Comment by Masana1** [comment]
Hello, I just found this discussion, it's been a day that I seek a solution to this problem.
do you think there will ever be a fix?

**Comment by bck427** [comment]
I haven't found a fix with newer versions, but if you look back at the prior builds and use one of those instead it fixes the problem.

**Comment by Masana1** [comment]
thank you for your response, in fact I currently use the network mode of pso so jles old version does not interest me. I will wait for a new version, maybe the bug will be fixed

**Comment by Bartvz** [comment]
To other people running into this problem: plug the GCN controller adapter into one of the back USB ports, download this file: https://github.com/FIX94/Nintendont/blob/f0694cd68c126ada84fda81307639b3d4e3f72e4/loader/loader.dol, and use it to replace the nintendont boot.dol (simply rename it boot.dol). 
Then the GCN adapter works 😄

**Comment by megamachopop** [comment]
> To other people running into this problem: plug the GCN controller adapter into one of the back USB ports, download this file: https://github.com/FIX94/Nintendont/blob/f0694cd68c126ada84fda81307639b3d4e3f72e4/loader/loader.dol, and use it to replace the nintendont boot.dol (simply rename it boot.dol).
> Then the GCN adapter works 😄

That just looks like an old loader.dol file which has already been said is the solution. Plugging your adapter into the back has nothing to do with it.

**Comment by NOFUNEVER** [comment]
Same problem, old build (sep 30) gets around the problem partially but if I use a usb hub it freezes again. I can leave the hub plugged in and even other peripherals connected to the hub and insert the gc controllers directly to the wiiu it works. If I plug the gc adapter into the hub after the game starts it works, i can't seem to leave the controllers plugged in while starting a game unless I do use the september build and go in directly or wait till after game starts to plug adapter into hub.

**Comment by carnage702** [comment]
> 
> 
> Same problem, old build (sep 30) gets around the problem partially but if I use a usb hub it freezes again. I can leave the hub plugged in and even other peripherals connected to the hub and insert the gc controllers directly to the wiiu it works. If I plug the gc adapter into the hub after the game starts it works, i can't seem to leave the controllers plugged in while starting a game unless I do use the september build and go in directly or wait till after game starts to plug adapter into hub.

nintendont doesnt openly support usbhubs so they will always have issues, to get usb controllers on wiiu injects you need to use version 486 since 489 is broken.

**Comment by TheBoxMan156** [comment]
Okay guys so I made an account just so I can reply to this thread. If the Wii U freezes when you load up a gamecube game using Nintendont, go into the vwii, load Nintendont and turn off memory card simulation. Don't worry, this will not actually turn it off. Load the gamecube game again and it should load now.

**Comment by geogolem** [comment]
im having this issue too. i didnt try "TheBoxMan156" solution yet though...

**Comment by carnage702** [comment]
> 
> 
> im having this issue too. i didnt try "TheBoxMan156" solution yet though...
> 
> EDIT: I ended up trying "TheBoxMan156"'s solution - but it actually did disable the memory card and the game said there is no memory cart - and it told me I wouldnt be able to save..
> 
> reading the description of the option in nintendont - this makes sense. Unfortunately disabling the option, actually disabled the option contrary to TheBoxMan156's experience. I did not test enough to see if having the GC adapter plugged in with this option prevented the black screen freeze since I need the memory card emulation...
> 
> I think this is a similar issue or same issue as: #737
> 
> I'm going to try and go back to the older version since I am not using BBA.
> I tried the September build and I have the exact same issue as "NOFUNEVER" regarding the hub. The old build works properly if I plug directly into wii U.. which is easy enough for me.. Hopefully the newer version eventually gets fixed.. but who knows..

the latest nintendont is bugged with wiiu injects and usb controllers
try this mod and it should work again https://gbatemp.net/attachments/nintendont_fix-zip.214029/

**Comment by bigchieff93** [comment]
> the latest nintendont is bugged with wiiu injects and usb controllers
> try this mod and it should work again https://gbatemp.net/attachments/nintendont_fix-zip.214029/

I used carnage702's boot file and fixed the issue of the system freezing on a black screen when starting a gamecube inject title with the gamecube controller hub plugged in - but I still could not get the gamecube controllers to work at all. My 3rd party pro controllers are trying to work but almost everytime they are scrolling rapidly but before I used your file, any input from them and the system would restart so I feel like that's a start lol. I just recently purchased a set of 4 everretro controllers and a everretro hub from amazon, it works on Smash Bros. for Wii U but cannot get them to do anything on my GC VC Injects. Any help would be much appreciated! Thank you!

**Comment by carnage702** [comment]
> 
> 
> > the latest nintendont is bugged with wiiu injects and usb controllers
> > try this mod and it should work again https://gbatemp.net/attachments/nintendont_fix-zip.214029/
> 
> I used carnage702's boot file and fixed the issue of the system freezing on a black screen when starting a gamecube inject title with the gamecube controller hub plugged in - but I still could not get the gamecube controllers to work at all. My 3rd party pro controllers are trying to work but almost everytime they are scrolling rapidly but before I used your file, any input from them and the system would restart so I feel like that's a start lol. I just recently purchased a set of 4 everretro controllers and a everretro hub from amazon, it works on Smash Bros. for Wii U but cannot get them to do anything on my GC VC Injects. Any help would be much appreciated! Thank you!

nintendont is not compatible with usb hubs, you must plug the usbs directly on wiiu, it has 4 usb ports it should be more than enough for you.

**Comment by bigchieff93** [comment]
Okay I must have missed that part about not working with the USB hubs, but I do thank you very much for your help, I will get some GC to USB cables and should be good to go! (I tested my retrolink GC controller for PC on the USB port on the Wii U on an Inject of Luigi's Mansion and it worked no problem, but I wanted my USB hub that I bought to work, but it works with Smash Bros for Wii U and will work for Switch and also has PC Mode so all in all I'm just glad I found this post instead of pulling my hair out trying to figure it out!!! Thanks again!

**Comment by geogolem** [comment]
I found this thread: https://gbatemp.net/threads/nintendont-freezing-when-loading-game.555909/#post-9180428
and started working from that info.

I believe this is that situation:

this commit works: https://github.com/FIX94/Nintendont/commit/f0694cd68c126ada84fda81307639b3d4e3f72e4
but the next commit has the freeze issue: https://github.com/FIX94/Nintendont/commit/274699000ccf0b6b8e5fbb8a5cbb50a8272334f4

so something in https://github.com/FIX94/Nintendont/commit/274699000ccf0b6b8e5fbb8a5cbb50a8272334f4 is related... i think..

**Comment by SubSystemD** [comment]
This issue is still unresolved. It's really becoming a problem in the community with new people diving into GC injects while there's no clear info on what build of Nintendont to use to circumvent that issue. That plus no update since BBA support. I know you can plug the adapter after booting into Nintendont but that's really not convenient.

**Comment by geogolem** [comment]
> This issue is still unresolved. It's really becoming a problem in the community with new people diving into GC injects while there's no clear info on what build of Nintendont to use to circumvent the problem. That plus not being able to update since BBA support (2018). I know you can plug the adapter after booting into Nintendont but that's really not convenient.

You are right - the main issue is really that there is no official updates/fixes to Nintendont and the last *official* build is broken.

I backed out all the changes until I found a build that works --> then someone said they already did that. Since nothing is being fixed in the official build it is hard to know what build to use and who has done what.

**Comment by SubSystemD** [comment]
I haven't. I'm fine with an older version for now.
It'd be best if FIX94 would add this PR to master (and maybe deal with subsequent issues that removing that lines implies).
Perhaps we could try and get a hold of him over at GBATemp.

Nintendont is one of the best piece of software the scene has ever seen. It'd be shame to see it end that way.

**Comment by geogolem** [comment]
> I haven't. I'm fine with an older version for now.
> It'd be best if FIX94 would add this PR to master (and maybe deal with subsequent issues that removing that line implies).
> Perhaps we could try and get a hold of him over at GBATemp.
> 
> Nintendont is one of the best piece of software the scene has ever seen. It'd be shame to see it end that way.

I emailed him a couple months ago, just to inquire about whether he plans to ever look at PR's etc. I never got a reply.. He contributed alot to the community but who knows if/when he will ever merge PR's for Nintendont..

**Comment by SubSystemD** [comment]
I'm emailing him right now too.
I'm going to try and get in touch with him at GBAtemp.
He still does commit to over repos, so it's not like he's inactive (or thank god even worse than that).

**Comment by carnage702** [comment]
i think i do have permissions to do allow a pull request but im not a codder and im dont know if i would screw something over by just allowing it tbh.

**Comment by SubSystemD** [comment]
I think it will be wiser to wait for a response. I have reached at some people over at GBATemp boards.
I mean it's not like this issue is over 1 year old at this point x)

**Comment by geogolem** [comment]
@carnage702  --> maybe create a new branch and start merging stuff in there.. maybe a branch named *develop* or something..

**Comment by carnage702** [comment]
> 
> 
> @carnage702 --> maybe create a new branch and start merging stuff in there.. maybe a branch named _develop_ or something..
> 
> We don't have to actually close the PR's as they should eventually be merged into master.. but maybe having a develop branch where we can merge stuff and cut releases from would be a good idea.. and if people find issues, they can open issues and we can further debug/fix.. I mean in theory, if we kept develop relatively clean, we could close the PR's and then someday, maybe FIX94 could merge develop into master... as long as each unit is separated into logical commits, things should be easy to rollback etc.

you already got branchs with this issue fixed like grayoldernichs and such so that would be pointless to do, if its not for masters then anyone can just do there own branch and they already did.

**Comment by SubSystemD** [comment]
Sure, though wasn't it a fork rather than a branch? Meaning that people who don't know about his GitHub won't know about it.
I think having a dev branch could actually be a good idea.
That way it stays on this repo and it's easier to tell people to switch on dev branch rather than redirect them to a forked repo.
Also GarryOderNights is quite active on the GBATemp boards so maybe he could implement other fixes.

**Comment by carnage702** [comment]
version 490 , try it.
