### ISSUE TITLE
Melee crashes only in Widescreen

### ISSUE THREAD

**Issue by ghost** [FIX94/Nintendont#713]
So, I play Melee a lot and if I stay at the character select screen for like 2 minutes it beeps SUPER loud and I have to force turn it off, it only happens in widescreen but I really don't wanna play without it so I have to rush myself in through the character select screen but sometimes it happens super fast like right after the match is done. Can Nintendont do something about this? They're still fixing bugs right. Also, I've tried a few Nintendont settings like Ultra Read Speed, Patch PAL50 they don't help. But in non-widescreen it never ever crashes

**Comment by carnage702** [comment]
widescreens are hacks so they dont work correctly on  every game, you would need a custom widesccreen hack made for that game.

**Comment by JustKeepWalking99** [comment]
Well, I can’t use a regular dolphin like one. I tried that for Mario Party 5 and the code can glitch out if I don’t have one JUST for Nintendont. Are you positive it’s not just a little glitch in Nintendonts coding that can be fixed.
