### ISSUE TITLE
Capcom vs. SNK 2 EO crashing.

### ISSUE THREAD

**Issue by ScarredSteel** [FIX94/Nintendont#714]
When using USB Loader on the vWii, each time I make it about halfway through a match in Capcom vs. SNK 2 for GCN, the game freezes up and I'm sent to the vWii home screen. There seems to be no stage, character, or event that triggers it.
This does not occur when I play 3 other GCN titles. Specifically, RoadKill, Def Jam: Vendetta, and Bloody Roar: Primal Fury. (all NTSC versions)

I have checksummed the iso and it is not corrupt.

**Comment by carnage702** [comment]
take a picture of your nintendont settings and post them here.
