### ISSUE TITLE
Wii freezes on game load

### ISSUE THREAD

**Issue by 8bit-coder** [FIX94/Nintendont#717]
I've fully softmodded my wii, and all wii games loaded from my usb drive in USB Loader GX work great but nintendont starts, and then the wii freezes at a black screen, after nintendont shows that it loaded the game. Is there any way to fix this?

**Comment by BitPatty** [comment]
Connecting the Wii to the internet before launching Nintendont usually helps in this scenario, if that's an option for you.

**Comment by 8bit-coder** [comment]
Oh you're right! My wii wasn't connected to the internet while I launched it! Thank you!

**Comment by 8bit-coder** [comment]
I'll test it out again when I get home, If it works, I'll mark this as solved

**Comment by carnage702** [comment]
shoudnt solve anything...

when the wii shuts off it means two things, first iso of the game is corrupted or imcompatible or you have a corrupt raw(save file) on your sd card/hdd, look in the saves folder and delete any 0kb file.

**Comment by BitPatty** [comment]
We've encountered this issue multiple times in the Sunshine speedrunning community and for some reason this workaround appears to fix it for most people.

> when the wii shuts off

In this case the Wii doesn't shut down, it just shows a black screen

**Comment by BitPatty** [comment]
When I get the chance, I am also gonna check whether there is a 0kb save file just in case.

**Comment by 8bit-coder** [comment]
Ok, connecting to the internet had no effect, but after trying to launch the games through USB Loader GX instead of directly from nintendont now works, kinda. Super Smash Bros Meelee launches and works fine, but Wind Waker now goes to the nintendo logo, the dolby logo, and then the wii freezes

**Comment by carnage702** [comment]
take a picture of your nintendont settings

**Comment by BitPatty** [comment]
Update from my end. There's no 0kb file and loading codes still only works consistently while the wii is connected to the internet.

Idk what black magic causes this but at least it works.

Anyway, not the same issue since mine is a frozen blackscreen right when launching the game.
