### ISSUE TITLE
Wii freezes when launching games from USB Loader GX

### ISSUE THREAD

**Issue by ZachZProductions** [FIX94/Nintendont#718]
Hello,

When trying to launch gamecube games with Nintendont thru USB Loader GX the Wii will freeze and the AV signal will disconnect after Nintendont configures the virtual memory.
I have the correct paths set and GameCube settings are set to Nintendont.

Games are launching fine directly from the Nintendont loader itself just failing thru USB GX and I prefer it as the UI is much more user friendly than the native Nintendont UI.

Hopefully someone in this forum has an answer otherwise I guess il forget using USB GX for GC games.

**Comment by zodiac1414** [comment]
this dont help you, but maybe you can help me. my games dont even show in nintendont or anything. i have the iso files in my USB but
