### ISSUE TITLE
[Request] Show game banner like swiss does

### ISSUE THREAD

**Issue by animekai** [FIX94/Nintendont#719]
Can i request a feature, to show the game banner as swiss does it plz?

It willl be great and pleasant to watch the game banner, as the game iso contains the banner itself, it musnt be soo difficult to implement i think?

My regards.

**Comment by CommandBlock6417** [comment]
The GBAtemp thread for Nintendont states that the UI will not be changed, as it's not meant as a frontend, only a menu. Wii USB Loader GX can display the game banners.

**Comment by animekai** [comment]
There is a lot of space in that white menu, a little game banner doesn't hurt anybody xD, it can be put it in any corner and don't affect the ui menu

**Comment by Peredonov** [comment]
You can use the BIOS, where you can see both the game banner as well as the game description on the game start screen, just like you would when loading a real disc on real a Gamecube. Just add a bios to the SD or HDD root folder and hold A when the GC logo appears.
