### ISSUE TITLE
Nintendont - Local multiplayer with ps4 controllers?

### ISSUE THREAD

**Issue by willeaxel01** [FIX94/Nintendont#720]
Hello!
I’m a big fan of nintendont and played alot of games from it. I used one ps4 controller and it works really good in any game.. Then I tried to play James Bond nightfire local multiplayer with two ps4 controllers but that did not Work. I tired all USB inputs with ps4 controllers in any combination but did not Work.. Is it something I need to download or did I do something wrong?

**Comment by carnage702** [comment]
only one hid device works at a time on nintendont, this isnt a bug but the way usb controllers work, you can have one player use one wireless controller like wiiu pro controller, wiimote+cc and another use ps4 controller, only usb devices with multiple ports allow the use of multiple usb controllers like wiiu gc adapter you can use 4 gc controllers and so one.

the way its coded you can never use more than one usb controller at a time.
