### ISSUE TITLE
Wii U Third-party usb ethernet & bba emulation

### ISSUE THREAD

**Issue by jlongenecker** [FIX94/Nintendont#721]
I am using the October 8 build and attempting to use a third party usb ethernet adapter hde for bba emulation. I am running into regular disconnections between my gamecube and the Wii U when using the USB ethernet adapter but not when using wifi for the Wii U and ethernet for the cube (I am testing this using MKDD). The Wii U usb ethernet adapter are plugged into the same switch that has internet access and I have regular disconnects, desyncs or the gamecube and the Wii U do not see one another when attempting to connect. I have not had any successful races with the third party adapter and the gamecube plugged into the same switch. Conversely I have no issues with the Wii U on wifi and the cube on the same network. 

As a side note, I noticed that if I put nintendont into BBA emulation mode and use a USB adapter into a switch without internet Nintendont crashes. I am assuming the Wii U needs internet in order for that third-party adapter to work (even with the issues stated above). 

The reason I want to be able to put the Wii U into a switch is I am using Xlink kai on a raspberry pi to tunnel mkdd. My setup current setup is as follows: Gamecube to switch, switch to raspberry pi running Xlink, raspberry pi uses wifi to get on the network (this setup works without issue). My hope was to be able to use a similar or same setup for the Wii U. 

Appreciate all of your hard work. Happy to send you any data or a video of the issues if helpful.

**Comment by eku** [comment]
@jlongenecker could you provide a network sniffer log, i.e. wireshark?
