### ISSUE TITLE
Nintendont crashes only when trying to use a USB controller

### ISSUE THREAD

**Issue by Nickdabeast010** [FIX94/Nintendont#723]
I really like GameCube games and I bought a USB GameCube controller instead of a real one, but I've heard that you can use a USB controller on Nintendont. I've managed to go through the lengthy process of making sure it's compatible, and making the code for it. I was messing with the coding of the control scheme because I wanted to map digital triggers to analog. It was working fine until one time, it just crashed whenever I tried to boot up a game with that controller. It works fine with wiimote + nunchuck but for some reason, it just doesn't load the game and just crashes back to the Homebrew screen. Can anyone help me?

**Comment by carnage702** [comment]
probably corrupted the controller.ini or ninconfig.bin on your sd card/usb, delete and retry.

**Comment by Nickdabeast010** [comment]
That doesn't seem to work. I copied the code from my other controller.ini file into a new one that I made with notepad++. I also deleted the ninconfig.bin but that still didn't work.

**Comment by Nickdabeast010** [comment]
I also figured out that it only crashes when the controller is plugged in if that helps. It crashes even if a use a wiimote if it is plugged in.

**Comment by carnage702** [comment]
this is a known bug every release after 486 crashes on wiiu inject if a usb controller is plugged,  going back to 486 solves this issue, you only loose the BBA that was added after.

**Comment by carnage702** [comment]
try 490

**Comment by CDM15y** [comment]
I also tried using my PS3 controller, but it crashed. My PS2 controller worked fine.
