### ISSUE TITLE
Melee glitching

### ISSUE THREAD

**Issue by JustKeepWalking99** [FIX94/Nintendont#726]
Hi, I’ve been using Nintendont on my Wii U for about 1 year. Melee only works in standard definition, or stretched Widescreen without progressive scan which really sucks. Progressive makes it look so much better but in progressive mode after selecting a character and a CPU for a match I can literally walk away from my TVfor about 5 minutes and when I come back it’s just buzzing, stops working and I have to unplug the back of the console. (Note: I actually can’t play Melee because I have to use Force Progressive for a few games and its a huge hassle to switch out CFG files so I just don’t play it). I have probably tested it around 50 times by just leaving it on the character select screen and it just crashes, I don’t touch any options all I do is select a character, I wait and then my Wii U buzzes like crazy and it’s REALLY loud. I’ve tried tons of different copies of Meler uncompressed, compressed, previous versions, fresh installs, different title ids, different updates, they all crash. And if I try to start each match one after another I can play about 4 matches before my Wii U randomly buzzes. If the Nintendont creator is reading this is there anything you can do to stop the game from crashing for people who want to use progressive scan over the Widescreen Patch or can you slightly recode the widescreen patch to stop the buzzing. If you can’t it’s cool I totally get it, just voicing out what I’ve noticed.

**Comment by carnage702** [comment]
ssbm ntsc(usa release) has progressive officialy added , so you dont need to force it at all, use the usa version and dont force something nintendo already coded themselves...

**Comment by JustKeepWalking99** [comment]
I don't force progressive, I do it the normal way. I was talking about how I had to force progressive for other games that don't do it naturally. but even when I use force progressive, don't force progressive and just select it off the menu. Same issue. I think the widescreen patch nintendont has is incompatible with the progressive scan or it's just a nintendont glitch in the emulator they use.

**Comment by carnage702** [comment]
> 
> 
> I don't force progressive, I do it the normal way. I was talking about how I had to force progressive for other games that don't do it naturally. but even when I use force progressive, don't force progressive and just select it off the menu. Same issue. I think the widescreen patch nintendont has is incompatible with the progressive scan or it's just a nintendont glitch in the emulator they use.

nintendont is not an emulator and yes widescreen patch probably is too blame becuase its an hack, if you turn it off it should work fine then.

**Comment by JustKeepWalking99** [comment]
The thing is I have to have it permanently set to force progressive, I already explained that I have multiple games that I need to force progressive otherwise they don't work so I can't cherry pick when to have force progressive and when to turn it off. I know it works fine with a stretched widescreen (it looks ugly but it doesn't crash), I've tested it out and it doesn't crash at the character select like the widescreen + progressive setup does. That's why I was hoping the Nintendont maker sees this and fixes the code so it's more compatible.

**Comment by eleriaqueen** [comment]
If I remember correctly you push Y when in Nintendon't, go the through the options (there aren't many) and deactivate the problematic one ! Waiting for Nintendon't to enumerate and mount storage devices takes a while but this is done in a matter of seconds...
