### ISSUE TITLE
Add a DPad only feature

### ISSUE THREAD

**Issue by grego-maradona** [FIX94/Nintendont#727]
Hello,
Is it possible to add a new feature to play only with the DPad ? When this setting is on, it simulate the 4 directions of the analog stick (max course). This will be wonderfull to play all game with an arcade stick...

Thanks a lot.

**Comment by GB-CG** [comment]
Most people would use the SNES-to-GC adapter from Raphnet: https://www.raphnet-tech.com/products/snes_to_wii/index.php

**Comment by grego-maradona** [comment]
Does it work for games that use only the analog stick (ex: virtua striker 4) ??

**Comment by GB-CG** [comment]
On seconds thoughts, the adapter only maps the GC D-pad so that's not doable as of yet.

**Comment by asheenlevrai** [comment]
damn gb-cg... you gave me hope for a minute ;)
