### ISSUE TITLE
games not showing

### ISSUE THREAD

**Issue by zodiac1414** [FIX94/Nintendont#728]
im doing everything im suppose too but still nothing. getting the iso files into the games folder but nothing

**Comment by carnage702** [comment]
need the correct path...

SD or usb: on root creat a folder  named
games
inside the games folder creat another folder you can name it everything like metroid prime
inside metroid prime you put your game  iso renamed to game.iso(make sure you got extensions to show up on your pc so you dont rename it game.iso.iso

so the path is
sd:games/anyname/game.iso or
usb:games/anyname/game.iso

**Comment by zodiac1414** [comment]
Alrighty sir, thank you so much  it helped!
