### ISSUE TITLE
FPS display?

### ISSUE THREAD

**Issue by 60fpshacksrock** [FIX94/Nintendont#729]
Would you mind adding a feature and an option to display the frames per second on the upper left side of the screen?

**Comment by carnage702** [comment]
nintendont is not an emulator so it doesnt emulate the cpu or gpu therefore it doesnt have any graphical way to display anything while running games, so one would need to make one which could probably affect the fps anyway.

**Comment by 60fpshacksrock** [comment]
I know it's not an emulator, more like virtualization.

**Comment by carnage702** [comment]
then you should know nintendont doesnt draw anything or show anything that isnt coded by the games iso to acess the gpu so its not like adding a simple line of codding for fps to be visivle on top corner, emulators have everything coded for gpu nintendont just sends calls there and doesnt do anything more so yeah.
