### ISSUE TITLE
NO STRING on Fairly OddParents Shadow Showdown

### ISSUE THREAD

**Issue by theOptimistic** [FIX94/Nintendont#730]
The game starts, the logos appear and then, suddenly, a "NO STRING" message appears and it doesn't work. This is the only game which I've had a problem with so far.

**Comment by carnage702** [comment]
take a  picture of your nintendont settings, also check your iso md5.

**Comment by theOptimistic** [comment]
Don't have a cellphone right now to take  pic, but it's everything default (so, "no") with Wii U Video mode and 512 memory size.

**Comment by carnage702** [comment]
sometimes people think they have default settings when they dont so if you cant take a picture write them all down, also what is your nintendont version number? and did you check your iso md5? to see if its a good iso?

**Comment by theOptimistic** [comment]
MD5: 949e22308c8d269245f1fc66076fbeea
Nintendont 6.489
Config: https://imgur.com/a/Y7DNkaQ (checked with NinCFGEditor)
Thank you.

**Comment by carnage702** [comment]
the only thing i see that could affect anything is videomode which it says 1280(no idea what that option  is) the default is auto too. also  check your sd card just incase and see if you got a 0kb save file in the saves folder and if so delete it.
