### ISSUE TITLE
Pac-Man World 2 Crashes when in Forced Widescreen.

### ISSUE THREAD

**Issue by Jerdo32** [FIX94/Nintendont#731]
Just as the title implies, when the Force Widescreen option is active, the game mau crash. Also, I wonder, are there still new versions of the emulator being released?

**Comment by carnage702** [comment]
force widescreen is a general hack, its not compatible with every game, also nintendont is not an emulator... 
there is a code made for this game try to use it not sure if it will work on nintendont tough
16:9 Widescreen
C21A773C 00000006
C0030000 3DC03F40
91C20004 C2220004
EC110032 D0030000
C003000C EC110032
D003000C C0030000
60000000 00000000
