### ISSUE TITLE
Pokemon Box: Ruby Sapphire Black Screen

### ISSUE THREAD

**Issue by MagSynchro** [FIX94/Nintendont#732]
Upon trying to exit the Box function of the game by accessing the return to list option the game goes to a black screen with a horrible buzzing noise.

Wii with GC ports here works correctly with Pokemon Box to load the game.
Latest version of Nintendont
Wii version 4.3U
I have Native on in nintendont settings.
I have tested with Pokemon Ruby and Sapphire
I have tested with 2 licensed Nintendo cables.

Error reported as early as version 3.334 (For JP version) / 3.387 (For US Version) though appears to be still occurring when trying to go back to List mode to close out the process.

Reportedly working in v3.364 per GBATemp

Side Note: Per description as the console/game seems to softlock upon this process it appears as though it may be related to the 32k streaming issue reported on the GBATemp wiki.

```My Console shuts down when running a game
Your game most likely uses Audio streaming feature and the stream isn't aligned to 32k which happens when getting bad dumps or compressing with programs that don't care about alignment (ex. GCISOTool).
It's recommended to use a Full Clean 1:1 ISO. Make sure its md5 matches the redump.org checksum.
If you really need to compress the ISO because of space issue, compress it with DMToolbox and enable the 32k alignment option.

I shall be attempting to test with a new ISO from a safe source before attempting to regress install to v3.364 or earlier.

**Comment by GB-CG** [comment]
Why didn't you comment this at #221? Please don't open duplicate issues.
