### ISSUE TITLE
Melee crashes in Progressive Mode - Nintendont bug (pls update it)

### ISSUE THREAD

**Issue by JustKeepWalking99** [FIX94/Nintendont#733]
Hi, I've been using Nintendont for about 6 months, I've had this problem the whole time. I'm on a Wii U and my settings are force progressive, force widescreen, and wii u widescreen (as well as memory card on). After lingering on the character select screen for about 3 minutes it crashes, sometimes the time varies staying on the character select for 30 seconds crashes it and makes a LOUD beep and I have to force shut my Wii U off (it happens in 1-P modes too). I can accomodate this by not using progressive (in non widescreen and non progressive it works FLAWLESSLY no glitches ever) but the characters look FAT and BLOBBY. I've used tons of different isos even tried Melee v01 and v00, I've even messed around with the settings constantly and then I saw this issue on another website and it seems exactly like mine, it seems to be an issue that was fixed in a patch but got broken again. https://smashboards.com/threads/melee-nintendont-keeps-crashing.438274/
I think it's Nintendont's code being bugged, I can't really get advice for it, so I wrote this post hoping Nintendont sees it and sends out an update soon. Bye, have a nice day :)

**Comment by carnage702** [comment]
well ssbm ntsu has native forced progressive option so you dont need to force it, like always forced widescreen and progressive are hacks that dont work on every game, you would need a custom widescreen patch and then use ntscu iso for native 480p.
