### ISSUE TITLE
Latest Nintendont version BREAKS TeconMoon injects

### ISSUE THREAD

**Issue by davisrayler** [FIX94/Nintendont#737]
Hello, it seems that the latest Nintendont version breaks the GameCube injects, the ones you can play with the GAMEPAD on your Wii U. I dont remember what is the previous version that still works with said injects, can someone give me a version list? So i can check when is that happened.

**Comment by davisrayler** [comment]
The one im using right now is version 5.486 and that works fine with the injections.

**Comment by carnage702** [comment]
the recent nintendont mod brooke inhjects if you have any usb controller connected to the usb doors so try unplugging anything on usb doors except the bare essential and try again.

**Comment by davisrayler** [comment]
> the recent nintendont mod brooke inhjects if you have any usb controller connected to the usb doors so try unplugging anything on usb doors except the bare essential and try again.

The only thing i have plugged is the WII U USB GameCube Adapter, that i NEED to play xD unless i of course play with the GamePad... but i cant load the injects cause it doesnt boot the games.

You are telling me to just unplug the Adapter if i want to use the gamepad?

**Comment by carnage702** [comment]
> > the recent nintendont mod brooke inhjects if you have any usb controller connected to the usb doors so try unplugging anything on usb doors except the bare essential and try again.
> 
> The only thing i have plugged is the WII U USB GameCube Adapter, that i NEED to play xD unless i of course play with the GamePad... but i cant load the injects cause it doesnt boot the games.
> 
> You are telling me to just unplug the Adapter if i want to use the gamepad?
> 
> EDIT: I imagine this has something to do with the BBA support.

Yes unplug the adapter and it will run again,   this is a bug after bba was added, not sure when fix94 will fix USB controllers on wiiu injects, but latest versions only have bba so if you don't plan on using it go back to older one. Bluetooth and gamepad still work fine though just USB controllers got broken on injects.

**Comment by davisrayler** [comment]
Thanks for the help. I will stick to 5.486 for now until it gets fixed! Thanks

**Comment by CosmicScale** [comment]
Can anybody point me to a version of Nintendont that doesn't have the USB controller issue? I've tried a few but haven't had much luck.

Latest build works fine but I'm worried I'm gonna wear out my USB port with all this unplugging and re-plugging lol

**Comment by hurda** [comment]
5.486, as mentioned just one posting above yours: https://github.com/FIX94/Nintendont/blob/7be1b6df41f07f39fd8e67dfd8be7b0b68209fc7/loader/loader.dol

**Comment by CosmicScale** [comment]
I tried that version and all I get is a black screen with USB controller plugged in or not. Replaced the boot.dol with the latest version again and it boots but only without a USB controller plugged in.

**Comment by carnage702** [comment]
> 
> 
> I tried that version and all I get is a black screen with USB controller plugged in or not. Replaced the boot.dol with the latest version again and it boots but only without a USB controller plugged in.

did you deleted the ninconfig.bin ? becuase you need to make it do a new config.

**Comment by CosmicScale** [comment]
> I tried that version and all I get is a black screen with USB controller plugged in or not. Replaced the boot.dol with the latest version again and it boots but only without a USB controller plugged in.
> 
> did you deleted the ninconfig.bin ? becuase you need to make it do a new config.

Tried that but it still didn't work. I did get it working tho! Deleted all the controller ini files. It seems you don't need them to use a GameCube controller adapter on this older version. Pretty sure its needed on the latest version.

**Comment by carnage702** [comment]
nope controller.ini files arent needed for a long time , atleast famous ones like wiiugc adapter ps3,ps4 and so on, because they are built into nintendo since like 300s version, the inis are only needed for controllers who dont have one already, you probably had a corrupt controller.ini files then, and nintendont tryed to read that when you inserted a usb controller.
