### ISSUE TITLE
Problems with BBA Emulation using Wii + Gamecube Combination

### ISSUE THREAD

**Issue by Mr-Erreip** [FIX94/Nintendont#738]
Hello there,
I am regularly hosting Mario Kart events among friends using two Gamecubes with genuine BBAs. When I heard that Nintendon't was able to emulate BBA now, I wanted to give it try and substitute one of the Gamecubes for the Wii I modded like 8 years ago?
I used Modmii to update all instances of modding.

I currently have the follwing setup:

1. Wii 4.2E/ HBC 1.1.2/ Nintendon't current release
2. Third-Party USB-Lan Adapter (Wii)
3. Crossovercable
4. Genuine BBA (GC)
5. Original unmoddified Gamecube

I tried running original Disc (Wii) + original Disc (GC) aswell as Iso from SD (Wii) + original Disc (GC), but the consoles keep telling me the connection fails while searching ( sometimes showing the "blue information screen", sometimes the "red error screen").

I checked the cable using both Gamecubes with BBAs and it works without any problems.

Someone able to help? Would be appreciated, thanks in advance :)

**Comment by hurda** [comment]
You followed the game-specific instructions from the [BBA_Readme](https://github.com/FIX94/Nintendont/blob/master/BBA_Readme.md)?

**Comment by Mr-Erreip** [comment]
The 50Hz/60Hz setting already applies when using two GCs, so I am aware of that.

"For Mario Kart, Kirby Air Ride and 1080 Avalance, when you want to connect to a real GameCube or Dolphin, first go into the LAN Mode on them.
After THEY start looking for other consoles, only THEN connect the other nintendont instances."

As for this part I tried the following two things:
1. Entering the LAN mode on GC before entering the LAN mode on the Wii. 
_Result:_ Described errors above
2. Entering the LAN mode on GC before connecting the Wii and then entering the LAN mode on Wii.
_Result:_ The countdown on the GC starts and expires, nothing happens on the Wii

**Comment by hurda** [comment]
And outside of Nintendont, the networking-stuff is working on the Wii and it's properly set up in the Network Profile etc.?
Connecting a Wii to a Gamecube ought to work, coming straight from FIX94: https://www.youtube.com/watch?v=6BaIHMwVo2E&lc=UgyYXb6VvkU0gv4OKRR4AaABAg.90FBr_e2jZQ90FM5EeWfXC (Youtube-comment), but I don't know if the connection via crossover-cable is supported or if the Wii needs a "normal" LAN-network inbetween.

**Comment by carnage702** [comment]
preety sure the wii needs to be connected to a network not to a gc only, since the entire wii firmware can only connect to networks so you probably need to connect gc to a router and the wii to the same one and then try again, direct cable wont work.

**Comment by Mr-Erreip** [comment]
Hello,
@hurda and @carnage702 thats a good point I hadn't thought about yet but will try out this weekend with a router in between (and yes the Wii works in the network)

**Comment by Mr-Erreip** [comment]
So I tried out putting the router in between, it does not work either.

1. Enter the LAN mode on GC, "Looking for GC systems" screen appears, countdown starts, enter the LAN mode on Wii (already connected to router): 
_Result_: The "Looking for GC systems" screen on the Wii apears aswell, Countdown starts and both Countdowns expire
2. Enter the LAN mode on GC, "Looking for GC systems" screen appears, countdown starts, connect the Wii to the router, enter the LAN mode on Wii: 
_Result_: The "Looking for GC systems" screen on the Wii apears aswell, Countdown starts and both Countdowns expire
3. Connect BOTH Gamecube to the router instead of a Wii + GC:
_Result_: Works as intended

Unfortunately I don't have a second Wii to check if using Wifi only might be the solution.

**Comment by hurda** [comment]
And GC connected to router by cable and Wii by WiFi doesn't work?
Does that network-setup of yours have internet-connectivity? In the original BBA-issue-thread it's mentioned that the Wii needs to be "online" to get network-connectivity.
Tried to set the Network Profile from within Nintendont? https://github.com/FIX94/Nintendont/issues/144#issuecomment-531357317

Maybe it doesn't matter, but is there a special reason your Wii is on 4.2E? Maybe Nintendont needs 4.3/IOS58 for BBA-emulation?

Another thing to try to see if it can work at all may be to test Devolution, just to see if BBA-emulation and Wii-GC-Play can work in your setup at all.
