### ISSUE TITLE
Nintendont not reading games on Wii U's external HDD (But works on regular Wii)

### ISSUE THREAD

**Issue by FlameKat53** [FIX94/Nintendont#739]
I tried several ways:
1.) Nintendont from vWii Homebrew channel
2.) Nintendont from .wad Forwarder
3.) Nintendont from Wii U mode Forwarder
4.) Looking for GC dumps via USBLoader GX

None of these show my dumps, though on my wii with the exact same drive it shows up, I did make sure the drive has enough power, too

**Comment by carnage702** [comment]
wiiu is much more picky with usb stuff so your hdd is y cable? or has its own power source?

nintendont version number you are using?

**Comment by FlameKat53** [comment]
So, I got Nintendont from HBC and .wad forwarder working with my HDD. It is a Y cable indeed.

So now just the Wii U Mode one isn’t working
