### ISSUE TITLE
CheckForGamesAndRegions () failed 1

### ISSUE THREAD

**Issue by edgaras1002** [FIX94/Nintendont#740]
How do i fix this errror when i try to play a gc games.

**Comment by carnage702** [comment]
im guessing two things
nintendont is not being able to acess sd card or hdd
or bad isos.

**Comment by edgaras1002** [comment]
But the iso works on dolphin. And the sd card works for wii flow so whats wrong?

**Comment by carnage702** [comment]
just becuase it works on dolphin doesnt mean it will work on nintendont and the sd card might be too slow maybe and needing a format.

what class is your sd card?
fat32 formated?
nintendont version number your using?

take pictures of your sd card root
inside the games folder and inside the individual game folder.

**Comment by edgaras1002** [comment]
My wii is pal and the games might be NTSC-U

**Comment by edgaras1002** [comment]
![IMG_20200215_101914](https://user-images.githubusercontent.com/53020392/74584589-cb464180-4fdc-11ea-9804-833d78eecb66.jpg)

**Comment by carnage702** [comment]
nintendont is region free so the region of the games or wii has nothing to do with anything, but what class is your sd card since your isos are on sd card right?

**Comment by edgaras1002** [comment]
Fat32

**Comment by carnage702** [comment]
> 
> 
> Fat32

fat32 is not a class lol class is speed like class 4,10 uhs  and such.

**Comment by edgaras1002** [comment]
![15817552103792644117414881545161](https://user-images.githubusercontent.com/53020392/74584689-c9c94900-4fdd-11ea-9f02-483fe4b51a19.jpg)
idk what speed is it.

**Comment by carnage702** [comment]
considering that it is a micro sd card the adpter for it might be abit wonky but try this take out everything you need to take out from sd card, to your pc then do a proper format on your sd card and redownload intendont files and put the isos there again, sometimes cards/usb devices are too fragmented and if nintendont cant read the files fast enought it fails.

**Comment by edgaras1002** [comment]
:/ i did that 3 times already. Its gonna take a while.

**Comment by carnage702** [comment]
> 
> 
> :/ i did that 3 times already. Its gonna take a while.

do you have another sd card then? maybe try another one in a diferent micro sd card adapter.

**Comment by edgaras1002** [comment]
I have unbranded one and a Adata branded one.

**Comment by carnage702** [comment]
> 
> 
> I have unbranded one and a Adata branded one.

try the other one with just one game and nintendont inside it if it works its an issue in your sd card reading. you could also try usb device.

**Comment by edgaras1002** [comment]
I tryed it and but same error.

**Comment by edgaras1002** [comment]
ok ill try with a usb drive but adata 16 gb are good?

**Comment by carnage702** [comment]
> 
> 
> ok ill try with a usb drive but adata 16 gb are good?

dont know i use scandisk and kingston, but the sd adapters keep getting bad  so i have like 20, some my pc cant even read after awhile.


also make sure you grab some fresh nintendont files since you may get a corrupt dol or ninconfig that might be messing up stuff.

**Comment by edgaras1002** [comment]
Yes i use kingston but its already full so i cant use that.

**Comment by carnage702** [comment]
well just to make sure try my files here delete all your nintendont files and use mine 
http://www.mediafire.com/file/xhuxb4e9auhxb4x/1-Nintendont_files_to_put_on_the__root_of_the_SD.rar/file

**Comment by edgaras1002** [comment]
![sketch-1581756582146](https://user-images.githubusercontent.com/53020392/74585019-182c1700-4fe1-11ea-8ace-4e2492f11429.png)

**Comment by carnage702** [comment]
so your using sd adapter for your sd car? hmm that might be why it doesnt work, i tough you had those sd adapters to put micro sd cards 

![318079_3_sandisk-32gb-extreme-pro-micro-sdhc-sd-adapter-sdsqxcg-032g-gn6ma](https://user-images.githubusercontent.com/12446178/74585052-b4015700-4fd0-11ea-9dd5-c96536de5310.jpg)

**Comment by edgaras1002** [comment]
No, i have that but i use usbs too.

**Comment by edgaras1002** [comment]
plus i use that micro sd card adapter not usb, sd card ones

**Comment by carnage702** [comment]
> 
> 
> No, i have that but i use usbs too.

well try my files abode and try a fresh install, but just so you know usb flashdrives rarely work on nintendont due to its usb code being diferent, an usb hdd is the safest bet, but all sd cards should work, never had an sd card that failled.

also make sure you delete your nintendont created saves folder maybe a bad file is there.

**Comment by edgaras1002** [comment]
![1581757142078162181104356465686](https://user-images.githubusercontent.com/53020392/74585135-31819300-4fe2-11ea-9ccc-62ebd863baca.jpg)

**Comment by carnage702** [comment]
well i see its locked? shouldnt the pin be up so its unlocked?

**Comment by edgaras1002** [comment]
It Fixed it thanks i thought its unlocked.

**Comment by edgaras1002** [comment]
Well time to close it

**Comment by carnage702** [comment]
yeah nintendont needs sdcard acess to save settings and memory files locked would never work, glad it fixed it for you have fun, dont forget to enable memory card emulation on nintendont settings before starting games.

**Comment by edgaras1002** [comment]
I did it.
