### ISSUE TITLE
HID Controllers Not Working Period

### ISSUE THREAD

**Issue by NoMoreStars** [FIX94/Nintendont#741]
I installed Nintendont and attempted to ty the HID Controller functionality starting with creating a controller.ini for my preferred controller at the moment, the PowerA Wired Controller Plus for the Nintendo Switch. I tested the controller with HIDTest and it registered the button presses, meaning it would be compatible. However after completing the controller.ini HIDTest gives me the following error:

ControlMessage():-7004 failed

Obviously this means I have no control over Nintendont either but something interesting happens instead. Whenever I have the controller plugged in and I launch Nintendont, there seems to be an input stuck inputting up at the initial selection screen between sd card and usb. Whenever I select usb, where my games are, the system freezes completely on the next selection screen where the cursor is stuck on Boot GC Disk in Drive.

I triple checked that the controller.ini is correct, only opting out of including the variables Polltype, DPAD, DigitalLR and MultiIn as I could find absolutely no documentation of their usage or how to determine the needed variables for each. The controller and cable still work perfectly on both the Nintendo Switch and PC. The Wii USB ports seem to be working fine as HIDTest detects controller input, but only when there is no ControlMessage error, which only appears when a controller.ini file is installed. The Wii being used is on version 4.3 which supposedly added the HID support. I'm using the most recent version of Nintendont, 6.489, which I even reinstalled a couple of times. I couldn't find any older versions of Nintendont anywhere and I am completely stumped.

**Comment by carnage702** [comment]
try an older nintendont version https://github.com/FIX94/Nintendont/raw/7be1b6df41f07f39fd8e67dfd8be7b0b68209fc7/loader/loader.dol rename it to boot.dol

**Comment by NoMoreStars** [comment]
No dice, same result freezing on the game selection screen.

**Comment by carnage702** [comment]
so if you pull usb controller out will the game start and run?

**Comment by NoMoreStars** [comment]
Yep, If the controller is not connected then I am able to load games just fine. Of course, I have no control over the game and reinserting controller while the game is running does nothing.

**Comment by carnage702** [comment]
well delete your controller.ini and ninconfig.bin and try it again.
one thing is the controller might not be supported by nintendont since someu usb devices require an activation bit that needs to be hardcoded on nintendont dol like wiiu gc adapter, or your ini is badly made.

**Comment by NoMoreStars** [comment]
Nope, deleting both controller.ini and nincfg.bin creates the same state as my previous comment while deleting only nincfg.bin and keeping controller.ini causes the same initial problems. If my ini is badly made then it is the fault of the developers for not keeping proper documentation of use. After all, it's just a simple string of variables and addresses corresponding to button presses, all easily accessible via HIDTest. I even fiddled around with the controller.ini again, changing Polltype to 1 and DPAD to 0 as suggested by documentation on the HIDTest app. I got partial functionality on the controller, having to work around Nintendont constantly reading a down input which can be circumnavigated by constantly holding right on the DPAD of all things and using the left stick for menu selection. However, same problem as initial, Nintendont freezes on the game selection screen.

**Comment by carnage702** [comment]
like i said some hid controllers arent compatible becuase they need extra stuff maybe that is one of those.
