### ISSUE TITLE
Music playback/looping issue with Kururin Squash

### ISSUE THREAD

**Issue by gingerbeardman** [FIX94/Nintendont#742]
I'm using CISO of Kururin Squash. 
With Nintendont 6.489 (Oct 8 2019)

I have the original disc in storage so can test if required. 

The first time the game loads if you let it sit on the menu screen it will play an intro with music and voices. Then it returns to the menu screen. These two things repeat. 

The music starts with an ascending flute kind of sound, then good into a synth/string/bass tune. 

Each time through the intro, the music either plays fine or plays the first few seconds of ascending flute over and over. 

There's no reproducible pattern. 

Let me know if there's anything else I need to provide.

**Comment by gingerbeardman** [comment]
Interesting...

If I launched Kururin Squash using WiiFlow Lite then the issue isn’t there. That method seems to be ignoring certain config aspects, for example, my custom screen width was not respected. 

If I run Nintendont and launch Kururin Squash from there the issue was present. 

The issue seemed to be “unlock read speed” which I’ve now turned off.

**Comment by carnage702** [comment]
every setting besides mcemu can break games, they are all hacks and dont work well for all the games so always try disabling noone essential settings first.
