### ISSUE TITLE
Gamecube Controller Works in Menu, not in Games

### ISSUE THREAD

**Issue by weelambaiden** [FIX94/Nintendont#743]
I am using the official Nintendo Gamecube controller adapter on my Wii U.  It is plugged into the front USB slots.  I am running Nintendont and my games off a SD card.  I can use the Gamecube controller in the Nintendont menu just fine.  When I launch a game, it does not respond, only the Wii Mote works.

I am running the latest version of Nintendont in vWii.  I have gone to downloads and loaded the latest versions of all the options.

Please let me know if you need any additional information.

Thank you!
Aiden

**Comment by carnage702** [comment]
First make sure native controllers is turned off, second make sure your controller is connected in port 1 of the adapter and not port 2,3,4. third dont activate any BT controller like wiimote+nunchuck wiiupro or wiimote+CC becuase they have priority over hid controllers.

**Comment by weelambaiden** [comment]
Apparently it was plugged into port 4 instead of 1.  I feel so stupid.

Thank you for your prompt response and patience.
