### ISSUE TITLE
[Request] Add GameCube Microphone Emulation for Wii U

### ISSUE THREAD

**Issue by TideGear** [FIX94/Nintendont#744]
Please add GameCube microphone emulation for Wii U. Since Dolphin supports it, perhaps it's well documented now?

**Comment by TideGear** [comment]
It'd be cool to be able to play Odama on the Wii U!

**Comment by ccfman2004** [comment]
Doesn't the Gamecube Mic use the Gamecube memory card slot?

**Comment by TideGear** [comment]
> Doesn't the Gamecube Mic use the Gamecube memory card slot?

Yes, so it would need to be emulated and/or use some kind of adapter.

**Comment by geogolem** [comment]
man it would be nice if this worked...

**Comment by eku** [comment]
Duplikat of #550. Please do not open new issue for already open ones.
