### ISSUE TITLE
Nintendont black screen, audio still plays. Help!

### ISSUE THREAD

**Issue by jeezus2424** [FIX94/Nintendont#746]
I am new to this type of community, but I needed help with a problem I am having with nintendont on my wii. I have it downloaded on the home brew channel, and currently have a 8gb usb drive formatted correctly, and plugged into the correct usb slot on my wii. 

The problem is that when I click on the game title to load it up, it loads through nintendont, then transitions to a blank screen, still playing audio and reading my inputs from my wired gc controller. I have done some research regarding this problem, but I couldn’t find any solutions. 

When it comes to settings, I have tried turning on “forced progressive”, “native control”, etc, but I got no good results. 

As for the format of the usb drive, it is currently on FAT32, with 4096 bytes of allocated units. The only games I have downloaded on the usb drive are “pac-man world 2” and “super mario sunshine” (with the folders being [games—>PAC-man world 2/super Mario sunshine—-> game isos].

If anyone can find a solution to my problem, then it would be greatly appreciated. Thank you in advance.

**Comment by carnage702** [comment]
im guessing your tv is imcompatible with the video signals the games are sending? where are you from pal region or usa? what region are the isos from? take a picture of your settings if you can.

**Comment by AmberV25** [comment]
> I am new to this type of community, but I needed help with a problem I am having with nintendont on my wii. I have it downloaded on the home brew channel, and currently have a 8gb usb drive formatted correctly, and plugged into the correct usb slot on my wii.
> 
> The problem is that when I click on the game title to load it up, it loads through nintendont, then transitions to a blank screen, still playing audio and reading my inputs from my wired gc controller. I have done some research regarding this problem, but I couldn’t find any solutions.
> 
> When it comes to settings, I have tried turning on “forced progressive”, “native control”, etc, but I got no good results.
> 
> As for the format of the usb drive, it is currently on FAT32, with 4096 bytes of allocated units. The only games I have downloaded on the usb drive are “pac-man world 2” and “super mario sunshine” (with the folders being [games—>PAC-man world 2/super Mario sunshine—-> game isos].
> 
> If anyone can find a solution to my problem, then it would be greatly appreciated. Thank you in advance.

So did youfix the issue? Having the same problem here
