### ISSUE TITLE
HDD spin down issue

### ISSUE THREAD

**Issue by Shifty1313** [FIX94/Nintendont#748]
So, I have WII U, hdd docking station ORICO 6518US3, and hitachi ultrastar 750gb, latest nintendont version. Booting games through VC injects.
The problem is that my HDD spins down after exactly 5 minutes of inactivity in any gamecube game (I was literally watching R/W LED with a timer in my hand). So, for some reason nintendont's anti-sleep function doesn't work for me, 1.5 mins passing but R\W LED is not blinking and after 5 mins my HDD is sleeping and games are crashing.

**Comment by carnage702** [comment]
well that is a problem with your hdd, it probably has some hidden functions to go to sleep, your better off researching on how to disable the sleep altogether on your hdd model.

**Comment by Shifty1313** [comment]
Ok, thx, I will try another hdd.
But I am still curious as why can't Nintendont keep my HDD awake? Isn't it supposed to?

**Comment by carnage702** [comment]
> Ok, thx, I will try another hdd.
> But I am still curious as why can't Nintendont keep my HDD awake? Isn't it supposed to?

If you have the latest version then yeah, take a picture of your nintendont settings

**Comment by Shifty1313** [comment]
![P00314-115012-2](https://user-images.githubusercontent.com/31634407/76677729-46564400-65eb-11ea-9fb4-e87f329feb3c.jpg)

**Comment by carnage702** [comment]
well im guessing your hdd just ignores nintendont pokes to make it not sleep, so maybe search the web  on how to disable that on your particular hdd.
