### ISSUE TITLE
BBA Emulation Wired Connection Not Establishing?

### ISSUE THREAD

**Issue by lucarioknight56** [FIX94/Nintendont#749]
I'm trying to use the BBA emulator on two Wiis with USB-to-Ethernet adapters. It works fine wirelessly, but there is a lot of slowdown. When I do the wired, however, it doesn't move past 'Establishing LAN Connection'. I am trying it with Mario Kart, with one Wii using a disc, and another with a copy on a 3.0 flash drive. I've set the network profile to the wired connection, even if it has never been connected to the internet. Is there something I'm doing wrong?

**Comment by carnage702** [comment]
is the router they are connecting to connected to the internet too?

**Comment by lucarioknight56** [comment]
No, it's a standalone switch; there's no internet passing through it.

**Comment by carnage702** [comment]
that is the problem, the wii only considers itself connected if the router has internet acess passing through it.

**Comment by lucarioknight56** [comment]
So I need to have a router connected to the internet, then connect the Wiis to the router with the cables so a LAN connection can happen?

**Comment by carnage702** [comment]
> 
> 
> So I need to have a router connected to the internet, then connect the Wiis to the router with the cables so a LAN connection can happen?

in theory yes, it should work, becuase the wii will say connection established when it sees internet acess even if they dont use the internet for nintendont.

**Comment by lucarioknight56** [comment]
Alright...what if this was done in area without easy access to the router connected to the internet? Or for that matter, what if there was no internet to begin with, or if I were to use a crossover cable? Would it just not work?

**Comment by carnage702** [comment]
probably doesnt work at all, the wii is coded to only establish connection when the router has internet acess, if it doesnt then it will just say connection fail.

if you have a big cable you an connect that router to your main house router  or have to deal with wifi wich sucks, if you have no internet then you can play 4 people atleast on the same console.

**Comment by lucarioknight56** [comment]
Hm, alright. I'll look into getting another router connected to the internet.
