### ISSUE TITLE
controller.ini picked up by HID-test but not by nintendont

### ISSUE THREAD

**Issue by langest** [FIX94/Nintendont#750]
I have created a controller.ini that I have placed in the root of my sd card. I have also tried root of my usb storage as well as the different namings parsed in this file: https://github.com/FIX94/Nintendont/blob/10f52316a67d955e2c9608ae6cefc277ccfb8abe/loader/source/HID.c#L24

For some reason, when I call it sd:/controller.ini it is picked up by HID-test and all my configuration is loaded correctly. Labels for all buttons are available and when I press corresponding buttons their values change on screen.
But nintendont fail to pick up the controller.ini in all of the different setups I have tried.

I also tried an older nintendont version as suggested here: https://github.com/FIX94/Nintendont/issues/741#issuecomment-588066458

**Comment by gmichaud** [comment]
Following this - I have spent almost 10 hours on the problem so far without any solution. Initially it looks my issue was a SD card compatibility problem since HIDTest was not picking up the file but now it works in HIDTest but not in Nintendont 🙁

**Comment by carnage702** [comment]
are your gc isos on sd card?

**Comment by gmichaud** [comment]
@carnage702 yes, on the same SD card.

**Comment by PyJay** [comment]
I am having the same issue which is I have a controller.ini at the root of my SD card. It works with HIDtest but not in Nintendont. For now I've put everything on the SD card (including ROM). I double checked that Native Controls if off. Let me know if you need more info

**Comment by Devnol** [comment]
I have created the ini profile for my Switch Pro Horipad and it does get picked up by HIDTest only if I put it in the root of the SD (if I put it on the root of my hard drive and launch hidtest from my hard drive it doesn't work either). If I start Nintendont it doesn't work but it also blocks me from controlling the menu with my wiiremote. If I unplug the controller the menu works. If I go into a game the controller doesn't work either.

**Comment by Dawnmetty** [comment]
Came here to say the exact same problem. I am using a DS4 controller and i just used a controller.ini config that i got on the controllerconfigs page here on github and just to be safe, i'm using the controller_ps4v2.ini. Checked everything and popped into root of SD (SD is also where Nintendont and games are) and HIDTest picked it up aswell, but when i booted into a game, controller does not work at all. Native Controls are off and ports are set to 4. Will be waiting eagerly for some type of fix , thanks guys

**Comment by carnage702** [comment]
> Came here to talk about the exact same problem. I am using a DS4 controller and i just used a controller.ini config that i got on the controllerconfigs page here on github and just to be safe, i'm using the controller_ps4v2.ini. Checked everything and popped into root of SD (SD is also where Nintendont and games are) and HIDTest picked it up aswell, but when i booted into a game, controller does not work at all. Native Controls are off and ports are set to 4. Will be waiting eagerly for some type of fix , thanks guys

My ds4 works just fine, but I think I got a V1 ds4, also you are on Wii or wiiu?

**Comment by Dawnmetty** [comment]
I'm using a Wii, booting Nintendont through Homebrew Channel

**Comment by carnage702** [comment]
> 
> 
> I'm using a Wii, booting Nintendont through Homebrew Channel

and your pid/vid match the v2 ini? also nothing connected to the wii gc ports or anything to usb ports besides the controller?

**Comment by Dawnmetty** [comment]
Sorry for the delay, yes, pid/vid is a match on the v2.ini. Nothing connected to GC ports and on the USB there is my external drive with the Wii stuff like, games, Wiiflow, etc. Should i remove the USB and try again?

**Comment by carnage702** [comment]
> 
> 
> Sorry for the delay, yes, pid/vid is a match on the v2.ini. Nothing connected to GC ports and on the USB there is my external drive with the Wii stuff like, games, Wiiflow, etc. Should i remove the USB and try again?

well no idea i dont have a v2 ds4 so i cant check it myself, and someone made that ini and it worked for them i guess, unless there is yet another ds4 revision that doesnt 100% match all the v2 ini in there.

**Comment by Dawnmetty** [comment]
I saw some people saying you have to press the PS button twice or something like that, i tried that too but it didn't work but i could be doing it wrong. I'll keep trying stuff until i get it working, i'll probably fail though, because  most likely i won't be knowing what i'm doing
