### ISSUE TITLE
Issues with Nintendont (general questions)

### ISSUE THREAD

**Issue by G3K20** [FIX94/Nintendont#751]
Hello everybody,
i am new here and new in the business of wii u hacking so i have a lot (& maybe some noob) questions. I hope it is okay. 
I use the CBHX and Tecamoon-Injector for Gamecube Games (EU) on Wii U. 

1. Problem: When i start some games like Nintendont shows up with „initialzing“ and then freezes. 
2. Problem: Some Games go through the initialzing, but then the wii u turns offs. Someone answered that there is a bad file or bad iso and something with md55 (???), but what does that all means? 
3. Problem: Some games that always works fine dont start, when i have a usb-controller 
pluged-in. It is normal? 
4. Problem: A way to disable the Gamepad as player 1? 
5. Problem: The working games just works, when i first boot the vwii and then return to the wii u menü. Is it normal? 
6. Problem: Can i open the „tradionall“ nintendont menü somewhere when i use tecamonn injections? 

The Games that works are just Mario Striker, Mario Sunshine, Melee, Mario Party 4 and Pokemon DX. 

I hope it is not too much and okay in this way, but i thaught
It would be better then spamming with questions. 

Thank you for all the coming answers!

**Comment by G3K20** [comment]
Edit: I tryed starting all of my dont working games & i must say that Problem 2) happens by all of them

**Comment by carnage702** [comment]
latest nintendont is bugged with usb controllers and wiiu injects download this version here before bba was added  https://github.com/FIX94/Nintendont/blob/7be1b6df41f07f39fd8e67dfd8be7b0b68209fc7/loader/loader.dol?raw=true  rename it to boot.dol and replace it.

**Comment by G3K20** [comment]
@carnage702 hmm i downloaded it, but now the working games dont working too. Its not even booting into „initalzing“ from Nintendont, just black screen and i cant not turn the wii u off.

**Comment by carnage702** [comment]
if your gc controller is the ones from new smash ultimate they have deadzones issues on nintendont only official gc original ones or smash wiiu ones work fine, maybe some 3rd partys, but smash ultimate ones have deadzones issues on nintendont.

**Comment by G3K20** [comment]
@carnage702 yeah it is ! Good to know thank you :D a last question if it is okay: Does is matter from which region the wii or gamecube roms is? Because finding some wii eu roms is difficult.

**Comment by GB-CG** [comment]
Nintendont does not play Wii iso's, just Gamecube ones. US (NTSC) Gamecube games have better Progressive Scan (480p) support but has less languages then Gamecube's PAL games.

It only matters if you want to play randomizers like Wind Waker or Metroid Prime because they only support the US version of those games.

**Comment by G3K20** [comment]
@GB-CG thank you for the answer ! But what is progressive scan (480p)?

**Comment by GB-CG** [comment]
Normally if you have the component cables (RVL-011) you can set the Wii from 480i to 480p for a clearer image quality. But since you have a Wii U, HDMI supports 480p, upscaled 720p and 1080p.

**Comment by carnage702** [comment]
like he said nintendont is region free, as long as your tv accepts ntsc signal and pal signal anything will play.

**Comment by G3K20** [comment]
You guys are awesome! Thank you a lot! I have few new questions, should i open a new thread or can i ask here ?

**Comment by GB-CG** [comment]
I think it's better to ask questions at the official support thread: https://gbatemp.net/threads/nintendont.349258/
as this is more of a bug tracker really.
