### ISSUE TITLE
Failed To Load IOS 58 From Nand

### ISSUE THREAD

**Issue by Sunshine998** [FIX94/Nintendont#752]
LoadKernel () Error 5 occurred, returning -1. Please help im not sure how to fix this issue with Nintendont. My Wii games on usbloadergx work perfectly.

**Comment by carnage702** [comment]
nintendont needs ios58 being official ios58 from nitendo and a homebrew channel that is ios58 based, older people that hacked their wiis long ago had diferent ios58 and homebrew channels, go to your homebrew channel and either press minus or + or some button on your wiimote and on the top left or right it will say what version of homebrew channel you have.

**Comment by Sunshine998** [comment]
Thank you so much for your reply. My homebrew channel is 1.1.2 IOS61
v22.30. I installed it through the internet connection method without sd
card and without internet channel

**Comment by carnage702** [comment]
Well that's your problem, nintendont needs iOS 58 Homebrew channel, make sure your Wii is in 4.3 fw and install a newer Homebrew channel

**Comment by Sunshine998** [comment]
My wii is version 4.3U but everytime I download homebrew it gives me
version 1.1.2 IOS61. Is there a way to get version 1.0.8?

**Comment by Sunshine998** [comment]
Fixed it! Thank you so very much😊
