### ISSUE TITLE
Issue with MayFlash adapter and gamecube controller

### ISSUE THREAD

**Issue by medic27** [FIX94/Nintendont#754]
Hi, feel like i've tried everything. I'm using this adapter: https://www.amazon.com/Mayflash-GameCube-Controller-Adapter-Switch/dp/B00RSXRLUE/ref=sr_1_1?keywords=mayflash+controller&qid=1584773670&sr=8-1

and using and oem gamecube controller. I've played around with different controller.ini, I've downloaded the controller.zip from nintendont. I've deleted both controller.ini and the other file that could get corrupted. I've tried old versions of Nintendont before it supposedly broke usb when injecting (i'm realizing i never did an injection because I'm on a mac and the injector is for windows). Also i used hackmii to get the loader onto vWii.

Does this adapter simply not work with Nintendont or something?

**Comment by carnage702** [comment]
isnt that the adapters that have wiiu switch mode and a pc mode? is it set to wiiu? is your gc controller on port 1 of the adapter?do you have native controllers set to off on nintendont settings?

**Comment by medic27** [comment]
Yes to all

**Comment by carnage702** [comment]
well does your controller work on nintendont menu? up and down? are both cables connected?, try deleting your controller.ini you have and let nintendont try to use the stock one it has on memory for the mayflash adapter, and you tryed the adapter and controller on smash game first to make sure they worked?

**Comment by medic27** [comment]
All cables connected, it doesnt work in the nintendont menu. It works on my mac for Dolphin. Ive tried deleting controller.ini a couple times already.

**Comment by carnage702** [comment]
is your gamecube controller official? or some fake /3rd party one?
because some fake ones dont work on the adapters with wiiu/wii and nintendont.
i got  a gameware gc controller that doesnt regist any imput on wiiu using the official gc adapter and it worked on original wii, remenber that mayflash has a pc mode which might let it work but on wiiu mode unless you have smash you cant test it to see if it works? did you ever tryed on smash wiiu?

**Comment by medic27** [comment]
Its an official controller. I just tested it on wii U smash (smash4) and it works!

**Comment by carnage702** [comment]
take a picture of your nintendont settings if you can, also how are you launching  nintendont?

**Comment by medic27** [comment]
I got nintendont installed using a miihack instead of like smashstack. I click on wii menu, then the Homebrew channel, then nintendont version 5.486. 
![MVIMG_20200321_130226](https://user-images.githubusercontent.com/6894926/77235576-45398f80-6b74-11ea-8258-dc5dadcbf628.jpg)

**Comment by medic27** [comment]
I don't know if it matters, but i have a bunch of files on my sd card from doing the wii u hack and wii hacks so its not the cleanest sd card in terms of minimum files involved.

**Comment by carnage702** [comment]
well you should turn memory card emulation to on or else you wont be able to save.

well even on nintendont menu moving your controller does nothing? tryed using all 4 diferent ports on nintendont menu?and clicking the dpad up and down to see if it registers anything?

**Comment by medic27** [comment]
Yep just tried all of that. Would it make sense to the HID test app? Not quite sure where to put it though.

**Comment by carnage702** [comment]
> Yep just tried all of that. Would it make sense to the HID test app? Not quite sure where to put it though.
> 
> Also does it matter that im using a 32gb sd card?

Nope,well if you have hidtest just make a folder inside the regular apps folder name. It anything like his teste and inside put the dol file renamed to be called boot.dol

**Comment by medic27** [comment]
Does the HID Test app work if you're in vWii? Does it matter if you run it in vWii or Wii U?

**Comment by carnage702** [comment]
well if its a fake mayflash adapter it probably needs its own ini file made for it.
