### ISSUE TITLE
Intermittent black screen crash before getting to menu

### ISSUE THREAD

**Issue by pa-august** [FIX94/Nintendont#755]
About 1/4th or 1/5th of the time I attempt to launch Nintendont, I get back screen crash and have to yank the power cable to reboot. This especially happens when I boot up the system for the first time in several hours. This happens before I get to the Nintendont main menu and before I can attempt to launch any games. After yanking the power cable Nintondont tends to run successfully on next attempt.

I'm using:

Wii U
CooldBoot Haxchi
Wii U Nintendont forwarder downloaded from USB Helper
Games are stored on SD card

**Comment by carnage702** [comment]
try to take everything from your sd card and then do a slow format and put everything back in, memory might be fragmentated too much.

**Comment by pa-august** [comment]
Tried that, behavior remains unchanged.

**Comment by carnage702** [comment]
no idea then.

**Comment by pa-august** [comment]
Looking more closely at Nintendo's SD card recommendations the problem may be due to my card being 1) 64 gigs and 2) SDXC. Can you recommend a reliable card?

**Comment by carnage702** [comment]
I use a SanDisk class 10 32gb sd card

**Comment by pa-august** [comment]
Ok. On Wii U all isos have to be on the SD card, correct?

**Comment by carnage702** [comment]
not really there is 3 diferent ways to store  nintendont gc isos on wiiu

1- hack vwii and use nintendont  on vwii mode
this gives you sd acess and fat32 hdd acess for isos, you looose acess to wiiu gamepad
****
2-nintendont vwii fowarder plus wiiu fowarder
basicaly a quick shortcut on wiiu  menu that boots nintendont fowarder on vwii mode and uses vwii like abode you can use everything but loose gamepad use

3-vwii inject on wiiu mode
in this mode you are locked out of FAT32 USB storage BUT
there is 2 ways to store isos on this mode
use an inject of nintendont that boots any iso on sd card(the one you have probably)
Make a game specific inject where you store the game iso either on wiiu nand or wiiu formated hdd, you get a channel for that game alone and cant choose which one to boot, which basicly a single game instal using nintendont app on sd card and saves there too but the iso is on wiiu nand or wiiu formated hdd and has its individual channel on wiiu mode menu.

**Comment by pa-august** [comment]
I got a 32 gig SDHD card, but the problem still persist. I formatted it FAT32 to 64k with Windows' built in tool, then tried the official SD Card tool Nintendo links to on their official site, which apparently formats to 32k. No dice either way.

**Comment by carnage702** [comment]
no idea then sorry.

**Comment by carnage702** [comment]
maybe your wii needs sometime to boot up maybe open something or wait like 30 seconds after boot to launch nintendont.

**Comment by GB-CG** [comment]
Try deleting the Homebrew cache (1 Block) save under the Data Management setting?

**Comment by pa-august** [comment]
> Try deleting the Homebrew cache (1 Block) save under the Data Management setting?

I booted into the vWii, deleted the save and launched Nintendont without issue. Rebooted and ran the Wii U menu Nintendont launcher and got the black screen crash per usual.

**Comment by carnage702** [comment]
seems to me your wiiu takes time to boot everything, if you turn on wiiu, go to wiiu homebrew channel, exit and then start nintendont fowarder, to make sure wiiu is fully started every required  function in there or something.

**Comment by pa-august** [comment]
I tried loading and exiting the wiiu homebrew channel and waiting several minutes after booting, neither helps.

Because I was able to go into Wii mode and launch Nintendont without issue, I wonder if it has something to do with the forwader.

**Comment by pa-august** [comment]
I made a VC inject of Metroid Prime to see if it sidesteps this issue and it does not.

**Comment by carnage702** [comment]
> I made a VC inject of Metroid Prime to see if it sidesteps this issue and it does not.

Obviously it wouldn't, because all injects go to the sd card to read nintendont boot.dol so it's the same thing, maybe try older nintendont like 486

**Comment by pa-august** [comment]
> > I made a VC inject of Metroid Prime to see if it sidesteps this issue and it does not.
> 
> Obviously it wouldn't, because all injects go to the sd card to read nintendont boot.dol so it's the same thing, maybe try older nintendont like 486

How do I get old versions of Nintendont?

**Comment by carnage702** [comment]
https://github.com/FIX94/Nintendont...dfd8be7b0b68209fc7/loader/loader.dol?raw=true
Please rename it to boot.dol and replace it.

**Comment by pa-august** [comment]
> https://github.com/FIX94/Nintendont...dfd8be7b0b68209fc7/loader/loader.dol?raw=true
> Please rename it to boot.dol and replace it.
> 
> Not sure if it will change anything for you though.

That's giving a "not found" error.

**Comment by carnage702** [comment]
do you have hidden extensions on your pc? maybe you renamed it to boot.dol.dol? 

if its on nintendont folder replacing the other boot.dol there, it shouldnt be not found unless the name is difrerent.

**Comment by pa-august** [comment]
> do you have hidden extensions on your pc? maybe you renamed it to boot.dol.dol? 
> 
> 
> 
> if its on nintendont folder replacing the other boot.dol there, it shouldnt be not found unless the name is difrerent.

Sorry I mean your link to the old boot.dol seems to be broken.

**Comment by carnage702** [comment]
oh https://github.com/FIX94/Nintendont/blob/7be1b6df41f07f39fd8e67dfd8be7b0b68209fc7/loader/loader.dol?raw=true
this one should work rename to boot.dol and replace.

**Comment by pa-august** [comment]
> oh https://github.com/FIX94/Nintendont/blob/7be1b6df41f07f39fd8e67dfd8be7b0b68209fc7/loader/loader.dol?raw=true
> this one should work rename to boot.dol and replace.

No change, unfortunately.

**Comment by carnage702** [comment]
Out of ideas, I recommend you use nintendont on vwii then.

Enviado do Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by carnage702** [comment]
im gonna give you a workaround but you must do an extra step and instal 2 channels one on wiiu mode and one on vwii

first use wup installer on wiiu and install this
https://drive.google.com/file/d/0BzEB8f_rxW-oOTBXcDdNRl90YlU/view

then go to vwii and use a wad manager and instal this
https://github.com/FIX94/hbc/releases/download/1.1.4-1/Homebrew.Channel.-.OHBC.wad

this are 2 special hbc that you can use the wiiugamepad and boot from wiiu side.After installing both go to wiiu menu, start the new homebrew channel on wiiu menu wich will boot into vwii hbc with gamepad support that you can use nintendont on.

**Comment by pa-august** [comment]
> im gonna give you a workaround but you must do an extra step and instal 2 channels one on wiiu mode and one on vwii
> 
> first use wup installer on wiiu and install this
> https://drive.google.com/file/d/0BzEB8f_rxW-oOTBXcDdNRl90YlU/view
> 
> then go to vwii and use a wad manager and instal this
> https://github.com/FIX94/hbc/releases/download/1.1.4-1/Homebrew.Channel.-.OHBC.wad
> 
> this are 2 special hbc that you can use the wiiugamepad and boot from wiiu side.After installing both go to wiiu menu, start the new homebrew channel on wiiu menu wich will boot into vwii hbc with gamepad support that you can use nintendont on.

This allowed me to sidestep the issue, thanks!

**Comment by pa-august** [comment]
After some testing I'm still getting this issue occasionally with the above method, but significantly less often. I wonder if it's a problem with my Wii U having trouble entering Wii mode reliably.

**Comment by carnage702** [comment]
seems like its an issue with your wiiu becuase nintendont is not even involved on this method, you are just booting the homebrew channel from wiiu mode so if it happens even here, this proves nintendont has nothing to be blamed for.

**Comment by carnage702** [comment]
try 490 maybe it helps.
