### ISSUE TITLE
Nintendont doesn't let me change my buttons layout on wiimote+nunchuk

### ISSUE THREAD

**Issue by CatherineS94** [FIX94/Nintendont#758]
Hi everybody,

Just dowloaded and installed nintendont on my wii usbloader gx and the game load but i can't change the button layout for my controller. I've tried the Button_2 but when i press it nothing happens. I tried updating all that was available. I restarted the wii multiple times too. Can you help me please? Thank you

**Comment by jedthe3rd** [comment]
If you press 2 the the combination for the particular button layout you want described here: https://gbatemp.net/threads/nintendont-wiimote-nunchuck-support-discussions.371356/ 
It should switch to the new layout. There is no visual prompt of it occurring. Just you just have to see if the button mappings changed.
