### ISSUE TITLE
cant get past mission 2 in "James Bond 007 Everything or Nothing" PAL EUR

### ISSUE THREAD

**Issue by Ghozt-S** [FIX94/Nintendont#760]
just a "tiny" issue with a specific game, cant get past mission 2 "Train Chase", it just doesnt load the next mission, black screen, cant even quit nintendont or wiiflow (by the way i use nintendont as a "plugin" in wiiflow lite), all i have left to do is turn off the wii and turn it back on
kinda odd, since in the Nintendont compatibility list is listed that the EUR version of the game runs with no problems (the EUR vercion is listed as "James Bond 007: Todo o Nada"), if anyone knows what nintendont version (or configuration) runs the game properlly, plase share it with me

this is the same rom that im using:
http://www.mediafire.com/file/gopoldfjnpeoo3k/%25234_%255BEsp_-_PAl_-_Espa%25C3%25B1a%255D.rar/file

this are my settings:
https://imgur.com/a/fgljkal

**Comment by carnage702** [comment]
you probably have forced imcompatible sttings, make sure to turn everything off  or auto except mcemu, not sure what settings you have enabbled, needed to see your settings.

stuff like forced widescreen,progressive,videomodes, video width cant break games along with even more settings.

**Comment by Ghozt-S** [comment]
> you probably have forced imcompatible settings, make sure to turn everything off or auto except mcemu, not sure what settings you have enabbled, needed to see your settings.
> 
> stuff like forced widescreen,progressive,videomodes, video width can break games along with even more settings.

this are my settings
https://imgur.com/a/fgljkal

**Comment by carnage702** [comment]
are you renaming your iso directly to game.iso and placing it on sd card/usb or using some program to pass it first?

**Comment by carnage702** [comment]
Also you said you used nintendont through wiiflow, have you tryed using nintendont directly from homebrew channel? just in case wiiflow is doing some forced stuff on its own.

**Comment by Ghozt-S** [comment]
@carnage702 yeah, i did, same problem, ill try again anyway, or just use an emulator to play that mission and import the save to nintendont to play the others

**Comment by carnage702** [comment]
Also you didn't answer my first question? Do you rename the iso or pass it through a program to get it into the sd/USB?

**Comment by Ghozt-S** [comment]
@carnage702 oh right, i did, i rename it as game.iso and placed it in my external hard drive, no programs involved, just copy paste

**Comment by carnage702** [comment]
maybe try a trick it either a crash or can cork, turn on osreport and if still doesnt work, turn on osreport+log on nintendont settings, if it works then turn themb back off becuase those can make many games crash not even sure if the game will work with those 2 set to on, try first solo os report and then osreport+log.

**Comment by Ghozt-S** [comment]
@carnage702 ok thanks, ill give it a try

**Comment by carnage702** [comment]
tbh i dont know if anyone ever tested the snpasi iso for more than the first level so it might be a compatibility issue, maybe try some other version like english eur and english usa.

**Comment by Ghozt-S** [comment]
@carnage702 yeah maybe is a compatibility issue, tried the osreport and osreport+log thing, but i didnt work out, so i played the level on dolphin and imported the save to nintendont and its working now, the next level actually load, but in the transition between level is when crashes, but anyway thanks for the help, i play the spanish ver mostly because thats my primary language and i can focus more in enjoy the game if is in spanish for me, but i hav no prob trying the english ver if i find more problems with this ver

**Comment by carnage702** [comment]
hi there could you go back to your previous save file and try this dol file to see if the mission loads now?
http://www.mediafire.com/file/oe6ru01vi2vy3cp/007ton.7z/file

**Comment by ccfman2004** [comment]
Please remove the media fire link for the iso as its considered piracy.
