### ISSUE TITLE
[request] GameCube arcade stick support

### ISSUE THREAD

**Issue by filevans** [FIX94/Nintendont#765]
Hello,
I've got the Competition Pro Arcade Fighting Stick for the GameCube and it says it works on the Wii in GameCube mode, but it doesn't work through Nintendont, is there any way I can get it working? It works perfectly OK on the PC through the USB GameCube 4 port hub but it's just totally dead on the Wii 
Thanks for your help

**Comment by AnthonyRyuki** [comment]
You should enable the Native Control mode through the Nintendont options.
