### ISSUE TITLE
Analog stick not working under certain conditions

### ISSUE THREAD

**Issue by ThielHater** [FIX94/Nintendont#766]
Hi there, I have one of these third party controllers (https://www.amazon.com/github/dp/B07KYVH3NJ) which has the form of a Gamecube controller but is plugged into the Wii remote. If I play Gamecube games using Nintendont directly, the left analog stick works like a charm but does not when launching the game over USBLoaderGX. This certainly is not a Nintendont problem but I guess you know best, what could cause this behaviour.

**Comment by carnage702** [comment]
well maybe usbloader is forcing settings that nintendont app  isnt like native control set to on? or something? also you are lucky your 3rd party controller works at all, since most  third party wiimotes/cc/ccpro rarely work on nintendont at all.

**Comment by ThielHater** [comment]
USB HID was on and Native control was off. This controller is a Nintendo licensed product, so maybe that does a little in terms of compatibility? However, I did some more tries and apparently the analog stick works most of the time. Then I synced the Wii mote and since then it always worked. Thanks.
