### ISSUE TITLE
Game stops working out of nowhere

### ISSUE THREAD

**Issue by mag-nolia** [FIX94/Nintendont#770]
Pretty self explanatory. Games just crash and go to a black screen that reads the standard gamecube error message.

This has happened on both Mario Sunshine and MGS Twin Snakes, both times during a cutscene.

I'm running it on a 100GB fat32 partition of a hard drive, and it's not the drive powering off, you can still feel it working while it crashes. I haven't changed any settings other than native control, because if it's not on my sticks drift.

**Comment by carnage702** [comment]
if the message is an error has ocurred it means the drive went to sleep or is working on some kind of suspended mode where it takes too long to wake up send nintendont the files it asked for in time.

but just incase take a picture of your nintendont settings.
