### ISSUE TITLE
Increase 480p compatibility, compared to Swiss

### ISSUE THREAD

**Issue by gingerbeardman** [FIX94/Nintendont#771]
I noticed that some games support 480p through Swiss but not Nintendont. I assume there's a reason for this, but I thought I'd open an issue to track this.

https://www.gc-forever.com/wiki/index.php?title=Swiss/Forced_Progressive_Compatibility_List

https://wiki.gbatemp.net/wiki/Nintendont_Compatibility_List

Example
- The Italian Job

Thanks

**Comment by carnage702** [comment]
swiss is a loader on a gamecube... 
nintendont is a bridge of sorts coded on wiimode(not gc mode like dios mios) to translate gc calls into wiimode, obviously they work very diferently.

**Comment by gingerbeardman** [comment]
Does that mean that it's impossible for Nintendont to implement the same 480p compatibility as Swiss?

**Comment by carnage702** [comment]
not impossible but 480p is an hack that applies to certain functions so games that dont use those functions need custom patches and so on, its not something you can just had a simple fix.

**Comment by gingerbeardman** [comment]
I ended up playing this problematic 480p game through Dolphin instead.
