### ISSUE TITLE
Problems playing a game without a GC controller. 

### ISSUE THREAD

**Issue by mrdolphin31** [FIX94/Nintendont#774]
Hello fix94:
I was just wondering that since I installed Nintendont and placed Metroid prime on my actual Wii u, I don't have the money to make a GameCube controller. All my GC controllers are at home n I'm in the nursing home recuperating from a tragic accident. I was on the kicking end however. So if you can point to me some actual Nintendont helper files for the Wii u menu, that'd be more appreciated.

Thanks.
Mrdolphin31

**Comment by carnage702** [comment]
so what exactly do you want? if you are on wiiu you can play the game with wiiu pro controller, wiimote+CC, wiimote+ccpro, hid controllers like ps3 and so on, and if you install the nintendont vwii inject  you can even play using the wiiu gamepad.

what helpers files you want, you didnt said what exactly you need.

**Comment by mrdolphin31** [comment]
I was wanting to play Metroid prime using the gamepad but I'm getting an error every time I press a button, "Wii software cannot be played on the Wii u gamepad. Please check the software and try again". Or something like that. I don't know what I'm going to do. I keep stumbling across the same pitiful old boot. Loader. Dol And I'm not getting anywhere.

So if there's any solutions. Any, I will post a video link to this site linking to my YouTube. Hopefully y'all will get the picture.

Mrdolphin31

**Comment by carnage702** [comment]
unfortunely we cant provide wiiu instalable files on githgub you have to make your own using the wii injector.

https://gbatemp.net/threads/release-wiivc-injector-script-gc-wii-homebrew-support.483577/

**Comment by mrdolphin31** [comment]
I don't have a PC yet. Still in the market for One.
