### ISSUE TITLE
Nintendont crashes when changing Mem settings

### ISSUE THREAD

**Issue by ErisuKuraku** [FIX94/Nintendont#779]
I Installed Nintendont on my Wii and when i try to enable memory card emulation it crashes the Wii and we have to reboot, I can go back into nintendont but the memcard setting isnt saved. Games run ok otherwise (with memcard emulation off).

**Comment by carnage702** [comment]
There is 3 possible issues.
1 your ad card is locked.
2 your sdcard or USB are full
3 issue happened and corrupted memory card files were created, to solve this go to your saves folder on USB or sd and delete any 0kb file you see there

**Comment by ErisuKuraku** [comment]
Thanks very much @carnage702 , I discovered that because the sd card didnt have a saves folder on the root, that resulted in the crash. The Guide we followed didnt mention creating a saves folder. All games work perfectly now.
