### ISSUE TITLE
Crackling noises on some games

### ISSUE THREAD

**Issue by segacdboy15** [FIX94/Nintendont#781]
Games like namco museum 50th anniversary Rayman 3 wario World and a few others have some occasional crackling noises but Namco 50th anniversary in the menu where you pick the games sometimes the music feels like if you were playing a scratched disc

**Comment by carnage702** [comment]
crackling happens when your device isnt fast enough, what do you sue to load isos sd?/flashdrive/hdd?

**Comment by segacdboy15** [comment]
> crackling happens when your device isnt fast enough, what do you sue to load isos sd?/flashdrive/hdd?

I use a my passport 2tb hard drive

**Comment by carnage702** [comment]
Can you take a picture of your nintendont settings?

**Comment by segacdboy15** [comment]
> Can you take a picture of your nintendont settings?

Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?

**Comment by carnage702** [comment]
> 
> 
> > Can you take a picture of your nintendont settings?
> 
> Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?

depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.

**Comment by segacdboy15** [comment]
> > > Can you take a picture of your nintendont settings?
> > 
> > 
> > Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> 
> depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.

So are you saying that if I change the cluster size that can help?

**Comment by carnage702** [comment]
> 
> 
> > > > Can you take a picture of your nintendont settings?
> > > 
> > > 
> > > Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> > 
> > 
> > depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.
> 
> So are you saying that if I change the cluster size that can help?

yes, see what you have first tough.

**Comment by segacdboy15** [comment]
> > > > > Can you take a picture of your nintendont settings?
> > > > 
> > > > 
> > > > Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> > > 
> > > 
> > > depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.
> > 
> > 
> > So are you saying that if I change the cluster size that can help?
> 
> yes, see what you have first tough.

![IMG_20200613_162315](https://user-images.githubusercontent.com/65944863/84578364-751eba80-ad92-11ea-99f8-c2450d1582a1.jpg)
![Uploading IMG_20200613_162315.jpg…]()
So I'm using Linux can I use this program to do that?

**Comment by carnage702** [comment]
> Can you take a picture of your nintendont settings?
> 
>                 Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> 
>             depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.
> 
>         So are you saying that if I change the cluster size that can help?
> 
>     yes, see what you have first tough.
> 
> IMG_20200613_162315
> Uploading IMG_20200613_162315.jpg…
> So I'm using Linux can I use this program to do that?

i dont see the clustersize there so i have no idea.

**Comment by segacdboy15** [comment]
> > Can you take a picture of your nintendont settings?
> > ```
> >             Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> > 
> >         depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.
> > 
> >     So are you saying that if I change the cluster size that can help?
> > 
> > yes, see what you have first tough.
> > ```
> > 
> > 
> > IMG_20200613_162315
> > Uploading IMG_20200613_162315.jpg…
> > So I'm using Linux can I use this program to do that?
> 
> i dont see the clustersize there so i have no idea.

![IMG_20200613_163046](https://user-images.githubusercontent.com/65944863/84578487-cb402d80-ad93-11ea-8793-c4c89b05a02c.jpg)
Is this it?

**Comment by carnage702** [comment]
> 
> 
> > > Can you take a picture of your nintendont settings?
> > > ```
> > >             Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> > > 
> > >         depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.
> > > 
> > >     So are you saying that if I change the cluster size that can help?
> > > 
> > > yes, see what you have first tough.
> > > ```
> > > 
> > > 
> > > IMG_20200613_162315
> > > Uploading IMG_20200613_162315.jpg…
> > > So I'm using Linux can I use this program to do that?
> > 
> > 
> > i dont see the clustersize there so i have no idea.
> 
> ![IMG_20200613_163046](https://user-images.githubusercontent.com/65944863/84578487-cb402d80-ad93-11ea-8793-c4c89b05a02c.jpg)
> Is this it?

no that is just the space it has lol 2000 gb is 2tb.

**Comment by segacdboy15** [comment]
> > > > Can you take a picture of your nintendont settings?
> > > > ```
> > > >             Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> > > > 
> > > >         depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.
> > > > 
> > > >     So are you saying that if I change the cluster size that can help?
> > > > 
> > > > yes, see what you have first tough.
> > > > ```
> > > > 
> > > > 
> > > > IMG_20200613_162315
> > > > Uploading IMG_20200613_162315.jpg…
> > > > So I'm using Linux can I use this program to do that?
> > > 
> > > 
> > > i dont see the clustersize there so i have no idea.
> > 
> > 
> > ![IMG_20200613_163046](https://user-images.githubusercontent.com/65944863/84578487-cb402d80-ad93-11ea-8793-c4c89b05a02c.jpg)
> > Is this it?
> 
> no that is just the space it has lol 2000 gb is 2tb.

Oh okay it's because I kind of heard that allocation is partition although I'm not really sure I guess I'll just have to borrow a Windows computer in order to set the allocation size unless you know of a good Linux program that lets me do that

**Comment by segacdboy15** [comment]
> > > > Can you take a picture of your nintendont settings?
> > > > ```
> > > >             Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> > > > 
> > > >         depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.
> > > > 
> > > >     So are you saying that if I change the cluster size that can help?
> > > > 
> > > > yes, see what you have first tough.
> > > > ```
> > > > 
> > > > 
> > > > IMG_20200613_162315
> > > > Uploading IMG_20200613_162315.jpg…
> > > > So I'm using Linux can I use this program to do that?
> > > 
> > > 
> > > i dont see the clustersize there so i have no idea.
> > 
> > 
> > ![IMG_20200613_163046](https://user-images.githubusercontent.com/65944863/84578487-cb402d80-ad93-11ea-8793-c4c89b05a02c.jpg)
> > Is this it?
> 
> no that is just the space it has lol 2000 gb is 2tb.

Also this program doesn't let me set the allocation size for whatever reason and I thought that the whole resize thing was it but thanks for telling me otherwise

**Comment by carnage702** [comment]
> 
> 
> > > > > Can you take a picture of your nintendont settings?
> > > > > ```
> > > > >             Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> > > > > 
> > > > >         depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.
> > > > > 
> > > > >     So are you saying that if I change the cluster size that can help?
> > > > > 
> > > > > yes, see what you have first tough.
> > > > > ```
> > > > > 
> > > > > 
> > > > > IMG_20200613_162315
> > > > > Uploading IMG_20200613_162315.jpg…
> > > > > So I'm using Linux can I use this program to do that?
> > > > 
> > > > 
> > > > i dont see the clustersize there so i have no idea.
> > > 
> > > 
> > > ![IMG_20200613_163046](https://user-images.githubusercontent.com/65944863/84578487-cb402d80-ad93-11ea-8793-c4c89b05a02c.jpg)
> > > Is this it?
> > 
> > 
> > no that is just the space it has lol 2000 gb is 2tb.
> 
> Also this program doesn't let me set the allocation size for whatever reason and I thought that the whole resize thing was it but thanks for telling me otherwise

on windows if you right click on the drive and select format you see the options size(total size),filesystem(fat32/ntsc/etc)   and then unit allocation size(this is the cluster size) not sure how it is on linux. what appears if you click format on the options to choose from?

**Comment by segacdboy15** [comment]
> > > > > > Can you take a picture of your nintendont settings?
> > > > > > ```
> > > > > >             Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> > > > > > 
> > > > > >         depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.
> > > > > > 
> > > > > >     So are you saying that if I change the cluster size that can help?
> > > > > > 
> > > > > > yes, see what you have first tough.
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > IMG_20200613_162315
> > > > > > Uploading IMG_20200613_162315.jpg…
> > > > > > So I'm using Linux can I use this program to do that?
> > > > > 
> > > > > 
> > > > > i dont see the clustersize there so i have no idea.
> > > > 
> > > > 
> > > > ![IMG_20200613_163046](https://user-images.githubusercontent.com/65944863/84578487-cb402d80-ad93-11ea-8793-c4c89b05a02c.jpg)
> > > > Is this it?
> > > 
> > > 
> > > no that is just the space it has lol 2000 gb is 2tb.
> > 
> > 
> > Also this program doesn't let me set the allocation size for whatever reason and I thought that the whole resize thing was it but thanks for telling me otherwise
> 
> on windows if you right click on the drive and select format you see the options size(total size),filesystem(fat32/ntsc/etc) and then unit allocation size(this is the cluster size) not sure how it is on linux. what appears if you click format on the options to choose from?

![IMG_20200613_165313](https://user-images.githubusercontent.com/65944863/84578844-d21c6f80-ad96-11ea-8b63-aee5e58aa19a.jpg)

**Comment by carnage702** [comment]
> 
> 
> > > > > > > Can you take a picture of your nintendont settings?
> > > > > > > ```
> > > > > > >             Sure but first I need to ask if I buy a Y cable for my hard drive so I can power it up to a wall adapter as well will that increase the speed?
> > > > > > > 
> > > > > > >         depends on the harddrive i guess, but btw check your clustersize, i bet you have a huge cluster size since its a 2tb one, nintendont prefers smaller clustersizes so it can read smaller chuncks quicker due to wii/wiiu speed.32k max of 64k clustersizes are the best, 32k is the best one.
> > > > > > > 
> > > > > > >     So are you saying that if I change the cluster size that can help?
> > > > > > > 
> > > > > > > yes, see what you have first tough.
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > IMG_20200613_162315
> > > > > > > Uploading IMG_20200613_162315.jpg…
> > > > > > > So I'm using Linux can I use this program to do that?
> > > > > > 
> > > > > > 
> > > > > > i dont see the clustersize there so i have no idea.
> > > > > 
> > > > > 
> > > > > ![IMG_20200613_163046](https://user-images.githubusercontent.com/65944863/84578487-cb402d80-ad93-11ea-8793-c4c89b05a02c.jpg)
> > > > > Is this it?
> > > > 
> > > > 
> > > > no that is just the space it has lol 2000 gb is 2tb.
> > > 
> > > 
> > > Also this program doesn't let me set the allocation size for whatever reason and I thought that the whole resize thing was it but thanks for telling me otherwise
> > 
> > 
> > on windows if you right click on the drive and select format you see the options size(total size),filesystem(fat32/ntsc/etc) and then unit allocation size(this is the cluster size) not sure how it is on linux. what appears if you click format on the options to choose from?
> 
> ![IMG_20200613_165313](https://user-images.githubusercontent.com/65944863/84578844-d21c6f80-ad96-11ea-8b63-aee5e58aa19a.jpg)

guess not, maybe try to google how to change allocation size/clustersize on linux, i dont use linux so no idea for me.
