### ISSUE TITLE
[Request] texture dumping and loading

### ISSUE THREAD

**Issue by christopher842** [FIX94/Nintendont#782]
Would it be possible to add a feature that makes it possible to load custom textures and dump textures like how it is for dolphin so that games can be played on an actual Wii/GameCube with better textures etc?

**Comment by carnage702** [comment]
nintendont is not an emulator like dolphin is, if you have textures and such you can just mod the iso itself and then load the moded iso on nintendont.

**Comment by christopher842** [comment]
What's the best iso editing tool out there?
And how do you open up the .bin files that contain the textures?

**Comment by carnage702** [comment]
> 
> 
> What's the best iso editing tool out there?
> And how do you open up the .bin files that contain the textures?

that depends from game to game... each game has each own encoding method that needs to be cracked, if someone made textures for a agme im guessing that game is already cracked and tools exist for that game, google is your friend.
