### ISSUE TITLE
Nintendo GameCube clone adapter doesn't work well

### ISSUE THREAD

**Issue by cartoon20** [FIX94/Nintendont#784]
I bought a GC adapter for my Wii Family Edition, and I tried to make a ".ini" file for the adapter, but when I try it on the Wii, the control goes crazy and Nintendont crashes when I move the stick. 
Can someone help me to make it work?

**Comment by carnage702** [comment]
well if you bough a clone/ fake wiiu gc adapter you get what you pay for, nintendont doesnt need ini devices for official one or mayflash one, didi you tryed without making the ini? to see if nintendont recognized the aadapter?

**Comment by cartoon20** [comment]
Well, the adapter is from other brand (not official, not mayflash), the first thing that I tried was connect the adapter without the ".ini" file and Nintendont didn't recognize it, so I decided to download a PC program to create a ".ini" file for the adapter. 
I tried to guide myself with a ".ini" file of the official adapter that I found, and when I try it on my Wii, Nintendont recognized the adapter, but when I started a GC game, the adapter gone crazy and when I moved the stick, Nintendont crashed and took me back to USB Loader.

**Comment by gingerbeardman** [comment]
Does your adapter have a physical switch to change WiiU/PC modes?

**Comment by Okdak-Sempai** [comment]
Mine have the physical switch to change wiiu/switch to pc mode does this mean it's normal if it dosn't work ? because i even pluged an official gamecube controller and tried all the port

**Comment by gingerbeardman** [comment]
Mine has the same switch, but only works on one side. Try both options of the switch, all ports each time.

**Comment by Okdak-Sempai** [comment]
Do you have to reset nintendront to make it detect changes (like switch changes or plug) or it's automatic ?

**Comment by gingerbeardman** [comment]
You need the matching .ini file to go with your adapter

**Comment by Okdak-Sempai** [comment]
But how i'm suposed to get that,on nintendront i had done "downlad controler.zip" thing and now i have a lot of .ini files but from what i saw the .ini have to be on the controllers folder witch is already the case

**Comment by Okdak-Sempai** [comment]
Or have i have to make my own .ini from that controller with a software or something myself ?

**Comment by carnage702** [comment]
> 
> 
> Or have i have to make my own .ini from that controller with a software or something myself ?

you have to make your own ini with some software and place it on the root of usb/sd and name it controller.ini, the inis are there but if they dont match your adapter they dont do anything lol.

**Comment by gingerbeardman** [comment]
see this https://www.reddit.com/r/WiiHacks/comments/3inq1b/where_can_i_find_a_tutorial_to_making_a_custom/

**Comment by geogolem** [comment]
Just in case, you were having difficulty - I discovered yesterday that you need to launch Super Smash Bros. prior to running HID Test on a WIIU in order to make HID TEST detect the gamecube adapter. This is because Smash Bros. initializes the GC adapter. I have an official adapter - so I dont know about off brand ones - but it took me a while to figure out I needed to use Smash to initialize the adapter when trying to use HID test... so I thought I would share that here.

**Comment by gingerbeardman** [comment]
Love this! Thanks @geogolem

**Comment by Abro61209** [comment]
My mayflash GC adapter works just fine with nintendont. I wouldn't bother buying a GC adapter that isn't mayflash or the official nintendo one.
