### ISSUE TITLE
[Request] Add SNES classic edition controller mode

### ISSUE THREAD

**Issue by sergioad** [FIX94/Nintendont#785]
Hello friend, could you please add a feature on the wii classic controller in which by holding for a while both - & + you switch the ZL and ZR inputs with the L and R inputs while also mirroring the GameCube Z to ZL and -? I own a SNES classic edition controller and with this mode I could play Dpad heavy games like Capcom Vs. SNK 2 EO and Megaman network transmission without loosing any input whatsoever

**Comment by sergioad** [comment]
BTW while I could certainly buy an aftermarket classic controller I do not like the fact that I could end with a low quality product which could break easily, I prefer the feeling of OEM parts and thus I am stuck with my SNES controller, you could also use the home button in both wiimote and classic controller as a digital mode also, by enabling this by holding the home button your D pad is switched to be detected also as the analogue stick

**Comment by sergioad** [comment]
Inputs aside I ask to you for that update, also, I noticed that the wiimote alone nor with a classic controller exit the game pressing the wiimote's home button

**Comment by asheenlevrai** [comment]
(follow this thread)

**Comment by sergioad** [comment]
Yes, long time without a response
