### ISSUE TITLE
Black screen when loading Metroid Prime 1 & 2 (GCN)

### ISSUE THREAD

**Issue by Snowfckingwhite** [FIX94/Nintendont#786]
I have about 20 GameCube games on my SD and USB drive and I didn't ever had any issues playing them. For some reason though Metroid Prime and Metroid Prime 2 suddenly don't work anymore. I have no idea what could cause this I just think it's weird because I used to play them all the time using USBLGX and never had any issues with it and I didn't change anything on my setup since then. The settings are all the same, same TV, same USB drive, same SD card, everything is the same. I just had to remove the games once to make space for something different and later I moved them back on my USB drive but all I get now is a black screen for both games. I am really confused with this because when I tried the isos with Dolphin on my computer everything was fine so I think it can't be the isos. Is there anything I can do?

**Comment by carnage702** [comment]
Take a picture of all your nintendont settings

**Comment by Snowfckingwhite** [comment]
![20200627_051230](https://user-images.githubusercontent.com/65474043/85913414-dafc4f00-b834-11ea-8e86-4bd21c6cb119.jpg)
As I said I can't remember ever changing anything so if there's something wrong with the settings it's truly a miracle how it worked the first time and how all of the other games work perfectly most of the time

**Comment by Snowfckingwhite** [comment]
Alright, I took another look into it and turns out that for some reason the progressive patch setting was turned on in USBLGX even though it was turned off in Nintendont and this prevented the game from starting because if I remember right the engine used by Prime and Prime 2 does not support 480p or something like that

**Comment by carnage702** [comment]
> Alright, I took another look into it and turns out that for some reason the progressive patch setting was turned on in USBLGX even though it was turned off in Nintendont and this prevented the game from starting because if I remember right the engine used by Prime and Prime 2 does not support 480p or something like that

Both Metroid prime games USA version have native 480p so no need to force them.

**Comment by Snowfckingwhite** [comment]
Yeah but I use the PAL version

**Comment by carnage702** [comment]
> 
> 
> Yeah but I use the PAL version

well if you force videomode to ntsc and force progressive, it might work i think?
if not nintendont is region free so you can always play the usa version :P

**Comment by Snowfckingwhite** [comment]
I already figured out that I had to turn off progressive patch in order for it to work and it did so there's no need for me to change the region but thanks anyway for trying to help :)

**Comment by GB-CG** [comment]
The PAL versions of Metroid Prime 1 & 2 are one of the very few games that cannot be forced in 480p on Nintendont as of yet. The only way to play 480p on a PAL ISO of the Prime games is through Swiss. It used to not work before but now it does.

**Comment by Snowfckingwhite** [comment]
It's okay I don't really give a f about screen resolutions as long as I can see the game and especially the Prime games even today look just gorgeous in my opinion so I don't really need that but thanks
