### ISSUE TITLE
Crash on update settings with virtual memory card

### ISSUE THREAD

**Issue by joshop** [FIX94/Nintendont#787]
I enter the settings, turn on memory card emulation (I've tried 251 and 123 blocks, both fail) and whenever I press update after editing that setting (and then press update again on the next screen) it gives me a core dump and reboots. I'm using a **USB** drive to store the games, not an SD card.

**Comment by carnage702** [comment]
there is no update option on nintendont afaik.

to save settings you need to start a game withoput exiting nintendont so:
1-start nintendont
2- choose sd/usb
3-press b/1/whatever key to go to the settings
4- change the settings you want
5-press the b or whatever you pressed to enter the settings
6-choose a game from the list and start it,
 it will save the settings before starting the game.
