### ISSUE TITLE
Button Functions rotate CounterClockwise after games are inactive/paused for an extended period of time

### ISSUE THREAD

**Issue by armoar334** [FIX94/Nintendont#788]
installed using this guide: https://www.youtube.com/watch?v=olY92rSdU1c
Wii u FW: 5.5.4
After an extended period of inactivity, ABXY keys will rotate counterclockwise by one button, e.g X functions as Y, A functions as B.
this is really weird and i cant find any examples of this happening anywhere else.

**Comment by carnage702** [comment]
you pressed the minus button, this is a feature, if you press the minus buttons, buttons will rotate and if you press it again they return to normal...
