### ISSUE TITLE
Pac-Man World 3 crashes on loading screen

### ISSUE THREAD

**Issue by Jerdo32** [FIX94/Nintendont#789]
Right after it says option setting are loaded (or no setting options were found) it says "Loading..." but it stays frozen and the game crashes, needing to turn off my Wii. I've tried multiple attemps to see if they work, with real memory card, no memory card, and Virtual mem card, and it still crashes on same screen. I noticed this happened ever since I added the bios for nintendon't.

**Comment by carnage702** [comment]
Take a picture of your nintendont settings.

**Comment by Jerdo32** [comment]
![20200709_224109](https://user-images.githubusercontent.com/53071715/87110603-69110600-c235-11ea-86f4-6f31879ec1d3.jpg)

This are the settings

**Comment by Jerdo32** [comment]
![20200709_224324](https://user-images.githubusercontent.com/53071715/87110799-e0df3080-c235-11ea-84ff-06805fca752e.jpg)

![20200709_224313](https://user-images.githubusercontent.com/53071715/87110826-efc5e300-c235-11ea-9b33-9c7c9646bf75.jpg)

This us when skip IPL is on, though the game does boot, it crashes in the same place as when IPL is off.

**Comment by Jerdo32** [comment]
> Take a picture of your nintendont settings.

![20200709_224419](https://user-images.githubusercontent.com/53071715/87110948-3b788c80-c236-11ea-92e5-e5db629ee3f8.jpg)

Also here is the place where it crashes.

**Comment by carnage702** [comment]
if the ipl is being skipped you shoudlnt have acess to the bios ... its very very wierd lol

so how is your iso md5? maybe you have a bad dump, try checking your iso Md5 with a known good iso on redump.

**Comment by Jerdo32** [comment]
I had a bad dump, got a new one and it actually works. Still wonder how the game worked when it didn't have the bios, considering that skip ipl didn't work afterwards.

**Comment by carnage702** [comment]
Bios are optional, they aren't required to run any games.
