### ISSUE TITLE
[Solved. I think.] Black screen on game load, worked previously.

### ISSUE THREAD

**Issue by AveyCole** [FIX94/Nintendont#790]
I turned on my Wii and attempting to load any gamecube game via Nintendont now gives me a black screen. Doesn't matter if I use USB Loader GX or Nintendont directly. Interestingly, it doesn't seem to happen when I use my Wii2HDMI adapter. Only on my CRT which worked perfectly the last time I played Gamecube games on it. Even then it only seems to work via USB Loader GX. I don't think I changed any settings unless I accidentally pressed something on the controller while my tv was off and my wii was on. help :(

**Comment by AveyCole** [comment]
I think it was the debugger and debugger wait setting. Turned them off and it works fine now.

**Comment by carnage702** [comment]
obviously you have settings turned on that werent before.
