### ISSUE TITLE
PS3 controller clone drifting

### ISSUE THREAD

**Issue by Midou36O** [FIX94/Nintendont#791]
It seems like my clone ps3 controller keeps drifting and doesn't respond to any of the buttons i press upon plugging it on the usb port, HID-test detects and records every button correctly, but on nintendont and in games it refuses to respond and keeps moving the left joystick up left, moving the joystick doesn't change anything.

**Comment by muchbass** [comment]
I have the same issue as I reported in #722 last year. Until somebody adds support for PS3 controller clones like Gasia and Shanwan in the source code, there's nothing we can do at this moment.

**Comment by Midou36O** [comment]
Any reason for closing this issue?
