### ISSUE TITLE
Fail to start gamecube games

### ISSUE THREAD

**Issue by PinoLaLoggatrice** [FIX94/Nintendont#792]
As soon I launch a game, it just freeze itself on loading, showing only the mark of touch screen not working, I gotta everytime delete the file boot.dol in Nintendont folder and re-place it with the same file I just did copy from a friend's SD Card

**Comment by carnage702** [comment]
what nintendont settings you have on? take a picture of them.

**Comment by PinoLaLoggatrice** [comment]
where do I see them?

**Comment by carnage702** [comment]
When seeing the game list press 1 or b to see them

**Comment by PinoLaLoggatrice** [comment]
I forgot to mention I got my games with HBL on WiiU

**Comment by carnage702** [comment]
> 
> 
> I forgot to mention I got my games with HBL on WiiU

well you still need to have settings you just cant see them, i have no idea what you hardcoded to be on, maybe the instal was bad or something maybe go to the game on memory management and delete it and isntall again, also you need more than the nintendont foilder you need to have an nincfg.bin on the root of the sd card .

**Comment by PinoLaLoggatrice** [comment]
I checked today da SD card
and I have the nincfg.bin file, but what am I supposed to do with it?

**Comment by carnage702** [comment]
your not suposed to do anything with it, that file has the settings, you probably picked the settings or someone gave you one with settings  they had enabled.

like i said either you have a bad install or bad settings. 

just extract this diretely to the route of your sd card
http://www.mediafire.com/file/xhuxb4e9auhxb4x/1-Nintendont_files_to_put_on_the__root_of_the_SD.rar/file

if it aks to replace say yes. also you downloaded the vc injects with a game included like individual game install? or one that acesses nintendont and then you pick the game from sd card?

**Comment by PinoLaLoggatrice** [comment]
did that like an individual installation, btw once I got those files on the root of the SD card What should I do? Can I try launch my game?

**Comment by carnage702** [comment]
> did that like an individual installation, btw once I got those files on the root of the SD card What should I do? Can I try launch my game?

Yes try to launch your game, make sure your ad card is unlocked and maybe check if you have a saves folder on the root of your ad card, if you don't just make one

**Comment by PinoLaLoggatrice** [comment]
Once again, when I did launch the game it just freeze on loading with a black screen

**Comment by carnage702** [comment]
> Once again, when I did launch the game it just freeze on loading with a black screen

You probably have a bad install then , go to wiiu settings and delete your game, and redownload and reinstall, also what game is it?

**Comment by PinoLaLoggatrice** [comment]
Super Mario Sunshine for Gamecube.. I hadn't found many downloads of it, just this one worked, I don't know from where get good games' roms

**Comment by PinoLaLoggatrice** [comment]
can I take my actual saves files, save them on my pc then uninstall and re-install the game, THEN copy those save files into the new save files of the same game?

**Comment by carnage702** [comment]
> can I take my actual saves files, save them on my pc then uninstall and re-install the game, THEN copy those save files into the new save files of the same game?

Yes you can use dolphin and inject the save file in nintendont raw file

**Comment by PinoLaLoggatrice** [comment]
Okidoki, I'm sure we can close this post, one last thing, can u help me to get a good rom for the installation?

**Comment by carnage702** [comment]
> Okidoki, I'm sure we can close this post, one last thing, can u help me to get a good rom for the installation?

I can't give you rom sites since it's illegal, also unless you make your own injections, a good rom alone doesn't help you, since you still need to make a wiiu inject

**Comment by PinoLaLoggatrice** [comment]
Oh got it, well thx anyway for everything, so basically, a little recap,
I extracted that mediafire download if normally gamecube games wouldn't work properly, once I replaced all those files in the root of the SD card it should work everything fine, if it doesn't work too it can be the installation, and u gotta re-do it, dleeting and re-installing the game from the wiiu settings
