### ISSUE TITLE
Mario Kart Sound issue multiplayer second player

### ISSUE THREAD

**Issue by Loganicx** [FIX94/Nintendont#794]
When playing Mario Kart: Double Dash!! there's no sound from the second player, but from 1st and 3rd player works. Anyone else experienced this problem? I've tried with the latest version and one from 2018 and two different Wii's, one RVL-001 and one RVL-101. 

Thanks in advance for any suggestions.

**Comment by carnage702** [comment]
maybe you have sound to stereo on wii settings and only have  like left side sound column or something. maybe check your tv settings aswell, no idea tbh. maybe try setting the wii to mono and see if it solves anything.

**Comment by Loganicx** [comment]
Failure of component cables, will do a more thorough investigation before posting the next time. My apologies.
