### ISSUE TITLE
[issue] generic wiimote crash

### ISSUE THREAD

**Issue by lamatex1yoghurt** [FIX94/Nintendont#796]
Only can play with an original wiimote. If use a generic one, the 4 leds still on and cant play. Some brands of generics can be used only as second gamepad, never as first one.
Tested on 3 Wii consoles and 6 different wiimote generic brands.

**Comment by carnage702** [comment]
fake/3rd party wiimotes arent officialy supported, nintendont is coded very diferently from regular homebrew so the bt code for controllers is much smaller and tighter to fiit into nintendont memory so if a controller does something the original doesnt its very hard for nintendont to acept it without problems, my best sugestion is dont use 3rd party/fake controllers, you can use already a full assortment of controller options from gc controllers to wiiupro to wiiu gamepad to usb controllers like ps3/ps4 etc, you can do multiplayer with 4 diferent controllers if you want.
