### ISSUE TITLE
Issue with Reset/Power off via button combo

### ISSUE THREAD

**Issue by Reignendt** [FIX94/Nintendont#797]
When playing SSX 3 players sometimes need to use the very same button combo as the one you have made to shut off games.
Could you add an option to disable the Reset/Power off button combos, so that we can do all tricks in SSX 3 without accidentally shutting off the game?

Much appreciated!

**Comment by geogolem** [comment]
i dont know about implementing an option, but i do have an idea where in the code this is implemented --> I might take a look at next week - but no promises..

**Comment by NintendoManiac64** [comment]
I do not know how feasible it would be to implement this idea, but perhaps one solution would be to simply require the user to hold down the according button or button combination for 2 or 3 seconds?

I came up with the idea from the fact that I've had some issues with non-savvy players accidentally pressing the home button on a classic controller and resetting the console; similarly the recent fork that adds support for wired Xbox 360 controllers similarly uses the "Xbox Guide" button in the same way to reset the console, but the Xbox 360 "Guide" button is much easier to accidentally press.

Nintendont fork in question:
https://github.com/revvv/Nintendont-XBOX360
