### ISSUE TITLE
Bad Cutscene Stuttering when playing from USB or SD, Discs work fine

### ISSUE THREAD

**Issue by MostMoistMike** [FIX94/Nintendont#798]
I'm having an issue. When I try to load backups from USB 2.0 or an SD card, I get really bad stuttering in cutscenes, every time. 

I've tried multiple devices (one USB external hard drive, two different flash drives, a Class 10 SD card) and the issue persists no matter what. I've also tried reformatting the devices ensuring they're Fat32 with 32 KB clusters, and they are. I've also tried both USB ports.

But still, each time I boot up Mario Sunshine, the opening cutscene has hitches. When I pop in a burned DVD-R of the exact same ISO, it works fine.

Wii System Menu 4.3u

**Comment by carnage702** [comment]
take a paicture of your nintendont settings.

**Comment by MostMoistMike** [comment]
[**Image of Nintendont Settings**](https://i.imgur.com/u3VoR1O.jpg)

**Comment by carnage702** [comment]
set log to off and everything will be fine, why are you making a log while playing? obviously reading and writing at the same time is more than usb or sd card an handle from the poor wii...

**Comment by MostMoistMike** [comment]
Thank you for the suggestion. But the issue was present before I enabled the log. I enabled the log to see if I could track down any information in why it was stuttering in the first place.

**Comment by carnage702** [comment]
> 
> 
> Thank you for the suggestion. But the issue was present before I enabled the log. I enabled the log to see if I could track down any information in why it was stuttering in the first place.

if with log off still does that  then your sd card/usb are just too slow or too fragmented to be readed quickly by nintendont while your disc drive reads ok.

so i sugest do this turn log off first , then get your class 10 sd card on your pc, take everything out and then do a correct slow format on sd or usb whatever you want to use i guess, then put everything back in and try.

becuase it just seems your console is unable to read usb or sd fast enough and the disc drive is fine.

**Comment by carnage702** [comment]
you can also try to unlock read speed, it might mess afew audio syncs in some games like sonic collections or ssbm background music but in general it works almost perfect in many games.

**Comment by MostMoistMike** [comment]
Brand new drive came in from Amazon today. Formatted it to FAT32 with 32KB allocation-size, did a full-format which took about a half hour, loaded the ISOs up (the same ones that work fine when burned to discs) and it still stutters.

**Comment by MostMoistMike** [comment]
Followed the guide at https://gbatemp.net/threads/guide-to-safely-update-your-softmod-fixes-most-compatibility-issues.394397/ to update everything (IOSs, cIOSs, etc) - no luck, still stuttering.

**Comment by carnage702** [comment]
Did you tryed with the unlocked read speed set to on?

**Comment by MostMoistMike** [comment]
Holy Heck I think I figured it out.

Fingers-crossed, but I think (hope) the problem was: The Wii's WiFi adapter.

I happened upon an old thread where someone was having problems with Wii Backups with a different program, and mentioned disabling the WiFi helped. So I decided to give it a shot, and sure enough, the issues I was having seem to be gone.

Not sure why the issue seems to be so uncommon, or what the technical reason behind WiFi interfering with USB and SD loading could be. But I'll do more testing and confirm, then close.

**Comment by carnage702** [comment]
> 
> 
> Holy Heck I think I figured it out.
> 
> Fingers-crossed, but I think (hope) the problem was: The Wii's WiFi adapter.
> 
> I happened upon an old thread where someone was having problems with Wii Backups with a different program, and mentioned disabling the WiFi helped. So I decided to give it a shot, and sure enough, the issues I was having seem to be gone.
> 
> Not sure why the issue seems to be so uncommon, or what the technical reason behind WiFi interfering with USB and SD loading could be. But I'll do more testing and confirm, then close.

im guessing your wii is constantly acessing your wifi, adapter noone stop wich takes away processing power to read/write from usb, while disc drive is independant.
