### ISSUE TITLE
[BUG] BBA adapter emulation severe LAG on Mario Kart Double Dash

### ISSUE THREAD

**Issue by mariano-london** [FIX94/Nintendont#799]
I love what you guys did with BBA emulation, I was an easier way to put my cubes on the side and save some space, but too bad that at the moment you connect a 3erd wii the game became unplayable.

when I tried to connect 6 wii even the menu selector became really laggy (all the wiis were connected using lan adapters no wifi stuff)

**Comment by kingjinxy** [comment]
From what I have read here and on GBATemp, this is simply a limitation of Nintendont's BBA emulation. I have experienced brief hitches even with 2 Wiis connected via a switch, but they were very minor (<3 times for 90 minutes). I have heard that pairing fewer Wiis with more GameCubes or Dolphin instances can help to reduce lag.

**Comment by retroroom** [comment]
I can get about 4 connected with almost no lag (wired) but yeah, 5 for me becomes unplayable. Wish I knew more about coding, I'd love to get this fixed somehow.

**Comment by mariano-london** [comment]
I love what they did because with 2 wiis you can get 8p connected and is a great experience without breaking the bank unfortunately they can't replace a dolphin / GC set so I trust my olds GC when I have people around
