### ISSUE TITLE
home button freezes nintendont during game

### ISSUE THREAD

**Issue by DJa24** [FIX94/Nintendont#800]
just looking for a solution been tryin this issue let me know if anyone else had this problem

**Comment by carnage702** [comment]
home button exits nintendont to return to where it came from, how are you using nintendont?

wii through homebrew channel?
wii through a loader like usbloader gx/etc
wiiu through vwii homebrew channel
wiiu through vwii usb loader
wiiu through wii vc inject?

**Comment by DJa24** [comment]
it should be through homebrew and if not its default

**Comment by DJa24** [comment]
wii specifically

**Comment by DJa24** [comment]
it does it even if i access nintendont and try to return with the  home button

**Comment by carnage702** [comment]
> 
> 
> it does it even if i access nintendont and try to return with the home button

seems to be a problem with your homebrew channel since nintendont if started from homebrew channel and press home returns to homebrew channel so im guessing something is off with your homebrew channel that nintendont cant find a return to it, also you are using the latest version correct?

**Comment by DJa24** [comment]
I went to download the latest recently through the sites
would homebrew need to be updated

**Comment by carnage702** [comment]
> I went to download the latest recently through the sites
> would homebrew need to be updated

Maybe you have an old channel or used some mid to change something like Homebrew theme or something, well hour issue is easy to prevent tough, just don't press home I guess.

**Comment by DJa24** [comment]
so ig the only way to go back is turning it off

**Comment by DJa24** [comment]
> > I went to download the latest recently through the sites
> > would homebrew need to be updated
> 
> Maybe you have an old channel or used some mid to change something like Homebrew theme or something, well hour issue is easy to prevent tough, just don't press home I guess.

what is a mid and how do I see what ver. of homebrew I have

**Comment by carnage702** [comment]
> > > I went to download the latest recently through the sites
> > > would homebrew need to be updated
> > 
> > 
> > Maybe you have an old channel or used some mid to change something like Homebrew theme or something, well hour issue is easy to prevent tough, just don't press home I guess.
> 
> what is a mid and how do I see what ver. of homebrew I have

I meant mod not mid,. I would suggest maybe  do a fresh install first, delete nintendont config files on the root and dol and redownload, and try again. If that doesn't work download a new Homebrew channel and install it with a wad manager

**Comment by DJa24** [comment]
I

> > > > I went to download the latest recently through the sites
> > > > would homebrew need to be updated
> > > 
> > > 
> > > Maybe you have an old channel or used some mid to change something like Homebrew theme or something, well hour issue is easy to prevent tough, just don't press home I guess.
> > 
> > 
> > what is a mid and how do I see what ver. of homebrew I have
> 
> I meant mod not mid,. I would suggest maybe do a fresh install first, delete nintendont config files on the root and dol and redownload, and try again. If that doesn't work download a new Homebrew channel and install it with a wad manager

I'm thinking its the homebrew channnel because I updated both usb loader gx and nintendont but no homebrew

**Comment by DJa24** [comment]
Would the WAD manager version matter

**Comment by carnage702** [comment]
> Would the WAD manager version matter

It shouldn't matter as long as it installs wads

**Comment by DJa24** [comment]
> > Would the WAD manager version matter
> 
> It shouldn't matter as long as it installs wads

Ok ill give an update once i run this trouble shoot

**Comment by DJa24** [comment]
> > > Would the WAD manager version matter
> > 
> > 
> > It shouldn't matter as long as it installs wads
> 
> Ok ill give an update once i run this trouble shoot

I did the update and didnt get any results

**Comment by ccfman2004** [comment]
Out of curiosity what IOS is you Homebrew Channel using?  Open Homebrew Channel and press the Home button: 
![Launchbootmii](https://user-images.githubusercontent.com/79392/91245628-ee844300-e71b-11ea-9c44-64d19afb93b4.JPG)
IOS version used is in the upper right corner along with the Homebrew Channel version.  It should say IOS58 with Channel version 1.1.2.

**Comment by DJa24** [comment]
> Out of curiosity what IOS is you Homebrew Channel using? Open Homebrew Channel and press the Home button:
> ![Launchbootmii](https://user-images.githubusercontent.com/79392/91245628-ee844300-e71b-11ea-9c44-64d19afb93b4.JPG)
> IOS version used is in the upper right corner along with the Homebrew Channel version. It should say IOS58 with Channel version above the IOS version saying 1.1.2.
Im using IOS58
![15984096514034975725846436443690](https://user-images.githubusercontent.com/69767995/91249128-40c96200-e724-11ea-9b8e-13b038e6440a.jpg)

**Comment by ccfman2004** [comment]
So it's not that.  Just wanted to be sure.

**Comment by DJa24** [comment]
> So it's not that. Just wanted to be sure.

Theres actually something else wrong that I'm trying to fix now idk what the problem is but now my wii games aren't start up. If my HDD was going through the wiitdb and processing stuff and the computer had an auto matic restart for an update would that mess with the file type and partition

**Comment by ccfman2004** [comment]
It's possible but usually the OS tries to shut processes down first before fully attempting a restart.  If the app was directly modifying the partition data right when the OS decided to shut it down I can see how might cause data loss or corruption if something crucial was being written to at that moment.  This is the main reason I hate Windows. On the 3DS there have been a few cases where a homebrew app hosed the partition data on the SD card forcing a complete reformat.  What is the filesystem being used to store the games: fat32, NTFS, WFBS, etc?

**Comment by DJa24** [comment]
> It's possible but usually the OS tries to shut processes down first before fully attempting a restart. If the app was directly modifying the partition data right when the OS decided to shut it down I can see how might cause data loss or corruption if something crucial was being written to at that moment. This is the main reason I hate Windows. On the 3DS there have been a few cases where a homebrew app hosed the partition data on the SD card forcing a complete reformat. What is the filesystem being used to store the games: fat32, NTFS, WFBS, etc?

so ill have to format it for the backscreen error to stop happening
