### ISSUE TITLE
Nintendont Wii U gamepad support giving error

### ISSUE THREAD

**Issue by KamiSquadX** [FIX94/Nintendont#802]
I used to get Nintendont to load up all the time on Wii U with gamepad working. Now when i try to load up Nintendont in the year 20XX, i get an error saying "failed to load kernal from NAND" and it just restarts the whole Wii U to where i have to relaunch mecha cfw... Why isn't nintendont loading up again? 

All the files should be in the SD Card...
I tried loading the nintendont channel with and with out mocha cfw...
Tried loading via usb and via system menu...

What could be wrong?

**Comment by carnage702** [comment]
maybe you got some corrupt files on your sd card, try deleting your nintendont boot.dol and meta.xml and redownload new ones.

**Comment by KamiSquadX** [comment]
thank you for the swift reply. v3.334 i had. Built: May 12 2015.
looks like i needed a new nintendont update. 
So now the new download i have is v6.489 Built: Oct 8 2019

Seems like i loads up just fine. Now if i can just get my gcn game to load up...
