### ISSUE TITLE
Now that Snes9x GX and the like supports wired Xbox 360 controllers, surely it'd be realistic for Nintendont to support them as well?

### ISSUE THREAD

**Issue by NintendoManiac64** [FIX94/Nintendont#804]
If you look at the changelog for Snes9x GX, you can see that wired Xbox 360 controller support was added to Snes9x GX in v4.4.5 on 2020-02-01:

https://wiibrew.org/wiki/Snes9x_GX#History

Would this not mean that it's now realistic that Nintendont could similarly implement support wired Xbox 360 controllers?

It's been my impression that supporting wired Xbox 360 controllers in Wii homebrew has historically much much more difficult than supporting something like Nintendo's official 1st party GameCube USB adapter (which Nintendont supports yet Snes9x GX does not, and sadly the Snes9x GX github does not accept requests, meaning one would have to do the wacky thing of running the GameCube version of Snes9x GX inside of Nintendont in order to use the 1st party GameCube USB adapter).

**Comment by revvv** [comment]
I forked Nintendont to support my XBOX 360 controller...
https://github.com/revvv/Nintendont-XBOX360

**Comment by NintendoManiac64** [comment]
> 
> 
> I forked Nintendont to support my XBOX 360 controller...
> https://github.com/revvv/Nintendont-XBOX360

Thanks, I tried it and it generally works great!

Since it's treated as a HID USB device, it's great that I can configure the guide button to not be a console reset button as that button is much easier to accidentally press than the Wii classic controller's "home" button (though even then I'd still prefer the classic controller's "home" button to not reset the console, better yet if only the wii remote's "home" button could be set to reset the console and not the classic controller's "home" button, but I do not know how feasible that is).

My only other concern is that, unlike Snes9x, the Xbox 360's guide button keep flashing continuously even when the controller is functioning which is kind of annoying and visually distracting.  Snes9x by comparison has it light up what player number the controller is (much like how it works on a real Xbox 360).

**Comment by revvv** [comment]
> the Xbox 360's guide button keep flashing continuously

Check out the controller ini file:
```
# EndpointOut is 1 or 2 depending on your hardware, 0 = disable LED and rumble
EndpointOut=1
```

I was not able to adapt the code to detect the endpoint_out, so you probably need to change your endpoint to 2.
BTW: "disable LED" means "flashing" ;-)

**Comment by NintendoManiac64** [comment]
> 
> 
> I forked Nintendont to support my XBOX 360 controller...
> https://github.com/revvv/Nintendont-XBOX360

@Special-Niewbie wants to clarify if this your fork 360 controller support in addition to existing USB controllers, or if its USB controller support is limited to ONLY 360 controllers.

Relevant issue: https://github.com/Special-Niewbie/Nintendont-CrisMMMod/issues/8#

**Comment by carnage702** [comment]
> 
> 
> > I forked Nintendont to support my XBOX 360 controller...
> > https://github.com/revvv/Nintendont-XBOX360
> 
> @Special-Niewbie wants to know if this your fork 360 controller support in addition to existing USB controllers, or if its USB controller support is limited to ONLY 360 controllers:
> 
> [Special-Niewbie/Nintendont-CrisMMMod#8 (comment)](https://github.com/Special-Niewbie/Nintendont-CrisMMMod/issues/8#issuecomment-786576761)

considering his latest commit has an option to choose between hid or ven(xbox360) its preety clear its one or the other, you can use both at the same time https://github.com/revvv/Nintendont-XBOX360/commit/a9164a86ff47291bd7555334e47840d00ed6bfb3

**Comment by revvv** [comment]
> considering his latest commit has an option to choose between hid or ven(xbox360) its preety clear its one or the other, you cant use both at the same time

That's correct. To support both you need to rework the code.
