### ISSUE TITLE
rebind wii u gamepad controls?

### ISSUE THREAD

**Issue by ViolentCrumble** [FIX94/Nintendont#807]
I have noticed there is a way to remap buttons, however there is no example config file for wii u gamepad. Is there a way to remap the buttons for the wii u gamepad?

**Comment by carnage702** [comment]
bt controllers and wiiu gamepad are hardcoded on nintendont itself to remap them you have to rebuild nintendont yourself, unfortunely only hid(usb) controller can be remaped easily, you can press the minus button on gamepad/wiiupro/CC/ccpro to rotate the face buttons once but that is about it without rebuilding.
