### ISSUE TITLE
Black screen after trying to load gamecube bios

### ISSUE THREAD

**Issue by rawpie2** [FIX94/Nintendont#809]
Hello, when trying to load the gamecube bios from my iplusa.bin it does all the checks and everything and then proceeds to hang on a black screen, when I turn the ipl skip on the game works, but the whole point is that I want the bios to work, can anyone help me? I'm using a real wii not a vwii btw.

**Comment by carnage702** [comment]
take a picture of your nintendont settings, also what is the  ipl you got? maybe a bad file?
