### ISSUE TITLE
Video Width (not affecting certain games like SSBM Pal)

### ISSUE THREAD

**Issue by SirPrimalform** [FIX94/Nintendont#811]
___Update:___ 
The original comment here misdiagnosed the problem. It turns out the problem I was running into was that SSBM (PAL) doesn't work with the width parameter at all. The various NTSC versions have patches built into Nintendont but for some reason the PAL version was passed over. If anyone is capable of finding an equivalent patch for the PAL version I'd be really grateful. I'd even be willing to put a small bounty if anyone shows interest, is that considered bad etiquette?

_______________Original comment, please disregard:_______________
Is the video width parameter's upper limit of 720 a hardware limit, or just something that seemed like it would be plenty? I ask because even with the width set to 720, games like Smash Bros. Melee are still too narrow (circular objects are tall ovals and so on).
If it is possible to increase the upper limit I'm sure I'd be able to find a number that would be correct for any setup.
I don't want to seem ungrateful, thank you for making any of this possible in the first place!

EDIT: Additional info that might help.
I'm using a Wii U and starting Nintendont through a VC inject to get gamepad support. However, I used to use Nintendont by booting into the vWii and starting it with the Homebrew Channel and it was the same then. The aspect ratio displays incorrectly on the gamepad as well so it's not an issue with my TV. Lastly, I've tried my Wii U in 1080p mode, 720p mode and 480p mode and the behaviour was identical.

**Comment by carnage702** [comment]
things are oval because you are just stretching 4:3 to  you need to set wiiu force widescreen to on and forced widescreen to on to get true widescreen aspect ratio on wiiu you need both settings.

do remember that force widescreen is a general hack so you might get bugs or crashes on specific games.

**Comment by SirPrimalform** [comment]
Thanks for the reply, but you seem to have misunderstood. I probably didn't explain very well.

I'm not trying to play in widescreen at all, just normal 4:3. However, the image is **narrower** than 4:3, this is the reason the circles are **tall** ovals, not the wide ovals you'd get if you were stretching a 4:3 image to wide screen. Please re-read my first post with that in mind. I do know what I'm talking about when it comes to aspect ratio as I've always been sensitive to it (I'm the guy who cringes when someone's stretching a 4:3 game to fill their big wide screen TV).

My actual question is again, is the maximum video width of 720 a hard limit caused by the scaling hardware in the Wii U or is it an arbitrary limit chosen because it's assumed to be enough? If that limit could be lifted it would solve my problem.

**Comment by carnage702** [comment]
you would have to ask fix94 that, unfortunely he is gone and there is no one left to fix nintendont issues, but width is already unstable and crashes many games so i dont know if it could be augmented, also does it look wrong on wiiu gamepad also?

**Comment by SirPrimalform** [comment]
> you would have to ask fix94 that, unfortunely he is gone and there is no one left to fix nintendont issues, but width is already unstable and crashes many games so i dont know if it could be augmented, also does it look wrong on wiiu gamepad also?

Ah, I didn't realise the project was dead. I though perhaps you'd taken over or were maintaining a fork or something. Yeah, as I mentioned in the first post it's exactly the same on the gamepad. In fact just as you asked that I was taking a picture.
![DSC_1345](https://user-images.githubusercontent.com/19208921/92646208-faf0ca00-f2dd-11ea-84a4-a268da3e4a29.JPG)
![DSC_1347](https://user-images.githubusercontent.com/19208921/92646217-ff1ce780-f2dd-11ea-86c7-2acc5c30738d.JPG)

**Comment by carnage702** [comment]
you shoudl have log set to off btw, that can crash some games and its constantly writing to the sd card which can corrupt stuff.

im not a programmer so no idea, i always use wiiu widescreen and force widescreen whenever possible so i dont really use 4:3 tbh.

**Comment by SirPrimalform** [comment]
> you shoudl have log set to off btw, that can crash some games and its constantly writing to the sd card which can corrupt stuff.
> 
> im not a programmer so no idea, i always use wiiu widescreen and force widescreen whenever possible so i dont really use 4:3 tbh.

Thanks for the tip, I'll turn it off unless I need it.

Even if I turn wide screen on and patch it, it's still too narrow! Normally you'd expect the picture would reach the edges of the screen, in widescreen but not here.

**Comment by carnage702** [comment]
> 
> 
> > you shoudl have log set to off btw, that can crash some games and its constantly writing to the sd card which can corrupt stuff.
> > im not a programmer so no idea, i always use wiiu widescreen and force widescreen whenever possible so i dont really use 4:3 tbh.
> 
> Thanks for the tip, I'll turn it off unless I need it.
> 
> Even if I turn wide screen on and patch it, it's still too narrow! Normally you'd expect the picture would reach the edges of the screen, in widescreen but not here.

i guess its your tv then i get full picture on mine, my tv has alot of modes like full,native, zooms, native and so on, but full always fills the screen with the video signal even using my n64 even.

**Comment by SirPrimalform** [comment]
> > > you shoudl have log set to off btw, that can crash some games and its constantly writing to the sd card which can corrupt stuff.
> > > im not a programmer so no idea, i always use wiiu widescreen and force widescreen whenever possible so i dont really use 4:3 tbh.
> > 
> > 
> > Thanks for the tip, I'll turn it off unless I need it.
> > Even if I turn wide screen on and patch it, it's still too narrow! Normally you'd expect the picture would reach the edges of the screen, in widescreen but not here.
> 
> i guess its your tv then i get full picture on mine, my tv has alot of modes like full,native, zooms, native and so on, but full always fills the screen with the video signal even using my n64 even.

Nope. As I've said a few times, it's like this on the gamepad. It is definitely not my TV.

**Comment by carnage702** [comment]
> 
> 
> > > > you shoudl have log set to off btw, that can crash some games and its constantly writing to the sd card which can corrupt stuff.
> > > > im not a programmer so no idea, i always use wiiu widescreen and force widescreen whenever possible so i dont really use 4:3 tbh.
> > > 
> > > 
> > > Thanks for the tip, I'll turn it off unless I need it.
> > > Even if I turn wide screen on and patch it, it's still too narrow! Normally you'd expect the picture would reach the edges of the screen, in widescreen but not here.
> > 
> > 
> > i guess its your tv then i get full picture on mine, my tv has alot of modes like full,native, zooms, native and so on, but full always fills the screen with the video signal even using my n64 even.
> 
> Nope. As I've said a few times now, it's like this on the gamepad. It is definitely not my TV.
> My TV has all of those modes, but on some GC games the signal has pillarboxing even on wide screen, on both the gamepad and the TV. The pillarboxing is in the signal, so as far as my TV is concerned it IS filling the screen. This is why I'm asking about the video width setting.
> 
> EDIT: This is with the widescreen patch applied and Wii U widescreen on:
> ![DSC_1352](https://user-images.githubusercontent.com/19208921/92741684-c54bef80-f376-11ea-887a-5d3ffd4c4bc4.JPG)
> I'm not denying the possibility of user error but it definitely has nothing to do with my TV. I don't even particularly want to play in widescreen, this is just a good way to demonstrate that the video width parameter isn't going high enough.

its morethan high enough for me lol i just tested 686 fills my wiiu gamepad  altogether  anymore and i just get cutted picture

stretched 4:3 with only wiiu widescreen and 686
![IMG_20200910_172756](https://user-images.githubusercontent.com/12446178/92764376-49f53880-f38c-11ea-9e99-1c1ed0f2f534.jpg)

force wiiu widescreen and widescreen patch
![IMG_20200910_173316](https://user-images.githubusercontent.com/12446178/92764456-5b3e4500-f38c-11ea-97b3-31cb00983752.jpg)

**Comment by carnage702** [comment]
> 
> 
> I wasn't disputing that it was enough for you, just saying that it doesn't go high enough for my setup and that it's definitely not my TV. I'm using the PAL iso, but I'm running it at PAL60 which has the same resolution as NTSC (50Hz PAL has more lines, but 60Hz PAL has the same as NTSC).

that is why i took a picture of the wiiu gamepad, all wiiu gamepads are the same so if it fills my wiiu gamepad screen with 686 width being force widescreen or just stretch 4:3 it should do the same for you becuause there is no setup diference on wiiu gamepad.

i use the ntsc iso due to having native 480p, from the pictures you posted the width its just not affecting the iso at all, either broken or none functional, some games are imune to the width hack and some even crash so any chance you could try the ssbm ntsc iso to see if with 686 you would get full screen like me? it could be the pal iso that is imune to the width hack imo.

**Comment by SirPrimalform** [comment]
> > I wasn't disputing that it was enough for you, just saying that it doesn't go high enough for my setup and that it's definitely not my TV. I'm using the PAL iso, but I'm running it at PAL60 which has the same resolution as NTSC (50Hz PAL has more lines, but 60Hz PAL has the same as NTSC).
> 
> that is why i took a picture of the wiiu gamepad, all wiiu gamepads are the same so if it fills my wiiu gamepad screen with 686 width being force widescreen or just stretch 4:3 it should do the same for you becuause there is no setup diference on wiiu gamepad.
> 
> i use the ntsc iso due to having native 480p, from the pictures you posted the width its just not affecting the iso at all, either broken or none functional, some games are imune to the width hack and some even crash so any chance you could try the ssbm ntsc iso to see if with 686 you would get full screen like me? it could be the pal iso that is imune to the width hack imo.

I did already say, this is nothing to do with the width hack. I don't even want to play in widescreen. I just used that to better demonstrate the problem, because you can clearly see it not reaching the edges. The problem is the same in 4:3, it's just not as obvious because you expect black bars in 4:3, but the problem is that the black bars are bigger than they should be and the screen is narrower than it should be. So this problem has nothing to do with the width hack, it was just a convenient way to show the issue.
I'll try and find an NTSC iso, but if that fixes the problem then all we'd really know is that Nintendont has a bug running PAL60 games, which is a pity because for some games the PAL version is superior (e.g. Luigi's Mansion).

**Comment by carnage702** [comment]
> 
> 
> > > I wasn't disputing that it was enough for you, just saying that it doesn't go high enough for my setup and that it's definitely not my TV. I'm using the PAL iso, but I'm running it at PAL60 which has the same resolution as NTSC (50Hz PAL has more lines, but 60Hz PAL has the same as NTSC).
> > 
> > 
> > that is why i took a picture of the wiiu gamepad, all wiiu gamepads are the same so if it fills my wiiu gamepad screen with 686 width being force widescreen or just stretch 4:3 it should do the same for you becuause there is no setup diference on wiiu gamepad.
> > i use the ntsc iso due to having native 480p, from the pictures you posted the width its just not affecting the iso at all, either broken or none functional, some games are imune to the width hack and some even crash so any chance you could try the ssbm ntsc iso to see if with 686 you would get full screen like me? it could be the pal iso that is imune to the width hack imo.
> 
> I did already say, this is nothing to do with the width hack. I don't even want to play in widescreen. I just used that to better demonstrate the problem, because you can clearly see it not reaching the edges. The problem is the same in 4:3, it's just not as obvious because you expect black bars in 4:3, but the problem is that the black bars are bigger than they should be and the image is narrower than it should be. So this problem has nothing to do with the width hack, it was just a convenient way to show the issue.
> 
> I'll try and find an NTSC iso, but if that fixes the problem then all we'd really know is that Nintendont has a bug running PAL60 games, which is a pity because for some games the PAL version is superior (e.g. Luigi's Mansion).

my entire experimentation problem is too see if you can fill the gamepad screen the correct 4:3 comes latter, if you can like i can on wiiu gamepad with 686 with ntsc iso then it shows that is a pal issue atleast. and you can maybe fix the pal issue by forcing another videomode maybe but first need to confirm its the actual pal version issue, because if with ntsc iso you still cant fill the screen of the wiiu gamepad  with 686 something would be off on your end.

**Comment by SirPrimalform** [comment]
> > > > I wasn't disputing that it was enough for you, just saying that it doesn't go high enough for my setup and that it's definitely not my TV. I'm using the PAL iso, but I'm running it at PAL60 which has the same resolution as NTSC (50Hz PAL has more lines, but 60Hz PAL has the same as NTSC).
> > > 
> > > 
> > > that is why i took a picture of the wiiu gamepad, all wiiu gamepads are the same so if it fills my wiiu gamepad screen with 686 width being force widescreen or just stretch 4:3 it should do the same for you becuause there is no setup diference on wiiu gamepad.
> > > i use the ntsc iso due to having native 480p, from the pictures you posted the width its just not affecting the iso at all, either broken or none functional, some games are imune to the width hack and some even crash so any chance you could try the ssbm ntsc iso to see if with 686 you would get full screen like me? it could be the pal iso that is imune to the width hack imo.
> > 
> > 
> > I did already say, this is nothing to do with the width hack. I don't even want to play in widescreen. I just used that to better demonstrate the problem, because you can clearly see it not reaching the edges. The problem is the same in 4:3, it's just not as obvious because you expect black bars in 4:3, but the problem is that the black bars are bigger than they should be and the image is narrower than it should be. So this problem has nothing to do with the width hack, it was just a convenient way to show the issue.
> > I'll try and find an NTSC iso, but if that fixes the problem then all we'd really know is that Nintendont has a bug running PAL60 games, which is a pity because for some games the PAL version is superior (e.g. Luigi's Mansion).
> 
> my entire experimentation problem is too see if you can fill the gamepad screen, the correct 4:3 comes latter, if you can like i can on the wiiu gamepad with 686 width with ntsc iso then it shows that is a pal issue atleast. and you can maybe fix the pal issue by forcing another videomode maybe but first need to confirm its the actual pal version issue, because if with ntsc iso you still cant fill the screen of the wiiu gamepad with 686 something would be off on your end.

Good plan. I did try forcing other video modes with the PAL version (force NTSC, force PAL60 and I also tried both with "patch PAL50" on), but it's possible that's not enough. I'll find an NTSC ISO and try it out. 

Even if it would be nice to know what the problem is I don't suppose there's any hope of a solution if FIX94 has washed his hands of the project. I don't mind the NTSC version of Melee (I don't think it's missing anything vs the PAL release), but it'll be a shame for other games. I wonder if any of these forks are active: https://github.com/FIX94/Nintendont/network/members

**Comment by carnage702** [comment]
> 
> 
> > > > > I wasn't disputing that it was enough for you, just saying that it doesn't go high enough for my setup and that it's definitely not my TV. I'm using the PAL iso, but I'm running it at PAL60 which has the same resolution as NTSC (50Hz PAL has more lines, but 60Hz PAL has the same as NTSC).
> > > > 
> > > > 
> > > > that is why i took a picture of the wiiu gamepad, all wiiu gamepads are the same so if it fills my wiiu gamepad screen with 686 width being force widescreen or just stretch 4:3 it should do the same for you becuause there is no setup diference on wiiu gamepad.
> > > > i use the ntsc iso due to having native 480p, from the pictures you posted the width its just not affecting the iso at all, either broken or none functional, some games are imune to the width hack and some even crash so any chance you could try the ssbm ntsc iso to see if with 686 you would get full screen like me? it could be the pal iso that is imune to the width hack imo.
> > > 
> > > 
> > > I did already say, this is nothing to do with the width hack. I don't even want to play in widescreen. I just used that to better demonstrate the problem, because you can clearly see it not reaching the edges. The problem is the same in 4:3, it's just not as obvious because you expect black bars in 4:3, but the problem is that the black bars are bigger than they should be and the image is narrower than it should be. So this problem has nothing to do with the width hack, it was just a convenient way to show the issue.
> > > I'll try and find an NTSC iso, but if that fixes the problem then all we'd really know is that Nintendont has a bug running PAL60 games, which is a pity because for some games the PAL version is superior (e.g. Luigi's Mansion).
> > 
> > 
> > my entire experimentation problem is too see if you can fill the gamepad screen, the correct 4:3 comes latter, if you can like i can on the wiiu gamepad with 686 width with ntsc iso then it shows that is a pal issue atleast. and you can maybe fix the pal issue by forcing another videomode maybe but first need to confirm its the actual pal version issue, because if with ntsc iso you still cant fill the screen of the wiiu gamepad with 686 something would be off on your end.
> 
> Good plan. I did try forcing other video modes with the PAL version (force NTSC, force PAL60 and I also tried both with "patch PAL50" on), but it's possible that's not enough. I'll find an NTSC ISO and try it out.
> 
> Even if it would be nice to know what the problem is I don't suppose there's any hope of a solution if FIX94 has washed his hands of the project. I don't mind the NTSC version of Melee (I don't think it's missing anything vs the PAL release), but it'll be a shame for other games. I wonder if any of these forks are active: https://github.com/FIX94/Nintendont/network/members

yeah chance of fixing is slim, and while those forks might be active, one thing is changing afew codes around another is actually know your stuff to do actual nintendont changes without breaking videomodes and resolutions left and right.

afaik only luigi mansion pal version has any actual ntsc diferences the rest are all the same, i use ntsc for the native 480p every chance i get even tough im on pal region 480p better than no change pal 50 or even 60 imo.

**Comment by SirPrimalform** [comment]
> yeah chance of fixing is slim, and while those forks might be active, one thing is changing afew codes around another is actually know your stuff to do actual nintendont changes without breaking videomodes and resolutions left and right.
> 
> afaik only luigi mansion pal version has any actual ntsc diferences the rest are all the same, i use ntsc for the native 480p every chance i get even tough im on pal region 480p better than no change pal 50 or even 60 imo.

I would think expanding the range only has the danger of breaking things if you actually use it. Let's say someone increases the maximum to 900, using 720 or less should still give the same result as always, one can always put a disclaimer about using numbers above 720, Still, I don't even know if this is possible since 720 could be a limit in the hardware or at least in software outside of Nintendont's control. I'm only proposing to try it and see if it's possible. Obviously if it did break video modes we'd know it's a waste of time. 

That's quite a sweeping statement to say that Luigi's Mansion is the only game with any differences... 
To be honest, on the Wii U I haven't noticed any difference between GC at 480i and 480p. I guess I'm more sensitive to aspect ratio than anything else!

**Comment by carnage702** [comment]
> 
> 
> > yeah chance of fixing is slim, and while those forks might be active, one thing is changing afew codes around another is actually know your stuff to do actual nintendont changes without breaking videomodes and resolutions left and right.
> > afaik only luigi mansion pal version has any actual ntsc diferences the rest are all the same, i use ntsc for the native 480p every chance i get even tough im on pal region 480p better than no change pal 50 or even 60 imo.
> 
> I would think expanding the range only has the danger of breaking things if you actually use it. Let's say someone increases the maximum to 900, using 720 or less should still give the same result as always, one can always put a disclaimer about using numbers above 720, Still, I don't even know if this is possible since 720 could be a limit in the hardware or at least in software outside of Nintendont's control. I'm only proposing to try it and see if it's possible. Obviously if it did break video modes we'd know it's a waste of time.
> 
> That's quite a sweeping statement to say that Luigi's Mansion is the only game with any differences...
> To be honest, on the Wii U I haven't noticed any difference between GC at 480i and 480p. I guess I'm more sensitive to aspect ratio than anything else!

never heard anyone saying any other game has actual different content between pal and ntsc release of the same game lol  you can prove me wrong tough. also like i said if the game is being immune to width value changing to 900 wouldn't change a thing, since those bars look like the exact same as if you putted width on auto.

**Comment by SirPrimalform** [comment]
Ok, I've been delving through the issue tracker to see if anyone else reported this (I did look before posting this, but I was misdiagnosing the problem at that point). 

Anyway, I found this: https://github.com/FIX94/Nintendont/issues/147
This seems to be relevant to the problem I'm having, although FIX94 says that the problem is limited to the menus and works in the fights (that isn't the case for me as you can see by the screenshots). Still, it seems like the problem is related.

**Comment by carnage702** [comment]
> 
> 
> > never heard anyone saying any other game has actual different content between pal and ntsc release of the same game lol you can prove me wrong tough.
> 
> Well mostly it's that PAL versions would have bugfixes and things that the earlier NTSC release didn't have. It's not really the point though, we shouldn't need to justify why someone might want to play PAL games in order to fix it. Surely if Nintendont has a bug then it's desirable to fix it.
> 
> > also like i said if the game is being immune to width value changing to 900 wouldn't change a thing, since those bars look like the exact same as if you putted width on auto.
> 
> I didn't say the game was immune to the width value, I said 720 wasn't high enough. There's a big difference.
> If I set it to 720 it's too narrow, if I set it to anything less (or auto) then it's even narrower. The setting works, it just doesn't go far enough.
> 
> EDIT: I take it back. It does seem like it's the same amount too narrow regardless of the settings. As you say, increasing it wouldn't help because it seems it's ignoring the setting.
> It's interesting that you assumed I meant that... did you already know about this bug?

its normal that some games are immune to width settings since its a hack and depending how each game plays with the code it works or doesnt and some it even crashes it, so yeah ssbm is immune to the width setting that is what i expected since your bars looked default value to me.

So basically to fi this you would need to revamp the entire width code altogether since its not a specific game bug, it affects alot fo games, unless anyone knows how to do that besides fix94 dont expect it to be fixed, in the meantime i suggest using the ntsc iso since everything works on it.

**Comment by SirPrimalform** [comment]
> 
> its normal that some games are immune to width settings since its a hack and depending how each game plays with the code it works or doesnt and some it even crashes it, so yeah ssbm is immune to the width setting that is what i expected since your bars looked default value to me.
> 
> So basically to fi this you would need to revamp the entire width code altogether since its not a specific game bug, it affects alot fo games, unless anyone knows how to do that besides fix94 dont expect it to be fixed, in the meantime i suggest using the ntsc iso since everything works on it.

But the weird thing is that in the comments FIX94 says he fixed it...
I don't mind using the NTSC version for SSBM, I just can't work out why it's doing this if it was supposedly patched 5 years ago. Is there something that could be causing Nintendont to not recognise what my game is and not patch correctly?

**Comment by carnage702** [comment]
> 
> 
> > its normal that some games are immune to width settings since its a hack and depending how each game plays with the code it works or doesnt and some it even crashes it, so yeah ssbm is immune to the width setting that is what i expected since your bars looked default value to me.
> > So basically to fi this you would need to revamp the entire width code altogether since its not a specific game bug, it affects alot fo games, unless anyone knows how to do that besides fix94 dont expect it to be fixed, in the meantime i suggest using the ntsc iso since everything works on it.
> 
> But the weird thing is that in the comments FIX94 says he fixed it...
> I don't mind using the NTSC version for SSBM, I just can't work out why it's doing this if it was supposedly patched 5 years ago. Is there something that could be causing Nintendont to not recognise what my game is and not patch correctly?
> EDIT:
> Actually I do mind a bit: https://tcrf.net/Super_Smash_Bros._Melee/Version_Differences#European_Differences
> But it doesn't look like it's going to happen so...

afaik he said he fixed the ntsc versions since there are like 2 or 3 isos.

**Comment by SirPrimalform** [comment]
> afaik he said he fixed the ntsc versions since there are like 2 or 3 isos.

Well he doesn't specify. 

> I already found a fix for the 1.0 ntsc and jap versions, it'll take me a while to check the rest.

I take "the rest" to be all the other versions, PAL being one of them. 
That's followed by:
> there we go, check out 357, melee should be fine now with all the existing versions. if you find any other game with those weird issues let me know.

Again, PAL is one of "all the existing versions". What makes you think he didn't bother with the PAL version (other than that it's not working right now).

**Comment by carnage702** [comment]
> 
> 
> > afaik he said he fixed the ntsc versions since there are like 2 or 3 isos.
> 
> Well he doesn't specify.
> 
> > I already found a fix for the 1.0 ntsc and jap versions, it'll take me a while to check the rest.
> 
> I take "the rest" to be all the other versions, PAL being one of them.
> That's followed by:
> 
> > there we go, check out 357, melee should be fine now with all the existing versions. if you find any other game with those weird issues let me know.
> 
> Again, PAL is one of "all the existing versions". What makes you think he didn't bother with the PAL version (other than that it's not working right now).
> 
> Ah, I just found the actual commit and he didn't include the PAL version. :(
> [1b49785](https://github.com/FIX94/Nintendont/commit/1b4978566eafc32732ed3ae83d7d8b03557ceb9c)

see you always doubt my word for whatever reason like im trying to fool you lol first with width immunity now with the rest of the isos and so on, im not trying to trick you into anything  you just doubt my word on every turn lol.

**Comment by SirPrimalform** [comment]
It's just there have been a few times now where I've had to point out again something that I'd already said or you made incorrect assumptions about what I'm doing. It's not that I think you're trying to trick me or anything, it's just there have already been enough misunderstandings and assumptions that the idea of another one isn't surprising. Don't get me wrong, I appreciate you taking the time to reply.

**Comment by SirPrimalform** [comment]
@carnage702 
I guess this is it then? I hope you didn't take offense to my last comment, it wasn't meant as a slight. It's just a fact that there were miscommunications, when I "doubted your word" it was only because it seemed like more miscommunications.

Now we have correctly diagnosed the problem you have no interest in it because you don't see any justification for playing a PAL game? I would hope that the (maybe impossible) goal would be full compatibility and the merits between the different versions of Melee are subjective. PAL Melee has the balancing I am familiar with.

I realise you don't owe me anything, but making the claim that the PAL version is objectively worse is not a good reason for excluding it because it's not worse - just different.

**Comment by carnage702** [comment]
> 
> 
> @carnage702
> I guess this is it then? I hope you didn't take offense to my last comment, it wasn't meant as a slight. It's just a fact that there were miscommunications, when I "doubted your word" it was only because it seemed like more miscommunications.
> 
> Now we have correctly diagnosed the problem you have no interest in it because you don't see any justification for playing a PAL game? I would hope that the (maybe impossible) goal would be full compatibility and the merits between the different versions of Melee are subjective. PAL Melee has the balancing I am familiar with.
> 
> I realise you don't owe me anything, but making the claim that the PAL version is objectively worse is not a good reason for excluding it because it's not worse - just different.

like i said im not a codder so i cant do anything for you, same for pretty much everyone since this is an advanced program, i dont see fix94 returning any time so nintendont was left as it is right now. 

ssbm does have full compatibility, just because some hacks like width dont work on some versions it doesnt mean its not a compatible game, many games  have no compatibility with hacks like widescreens,width height, forced video-modes and such it was basically an extra if it worked, fix94 never payed much attention to get width working on all games or forced widescreen working in every game, they are hacks so they work on some games and dont work on others.

fix94 main point was getting all games running without crashing  and i think he achieved that so i guess he felt that was enough, so i dont see him returning to fix width on pal version of ssbm.

So the way i see it you have 2 options
1- play ssbm pal the way it is and hope for someday fix94 to return or find a coder that wants to study nintendont and fix it for you.
2-change to ssbm ntsc and play it with all the width you want.

**Comment by SirPrimalform** [comment]
Well it doesn't display properly without the patch so I don't know about calling it fully compatible... 

I'm sorry, I didn't realise you weren't a coder at all. Why are you responding to issues on the tracker if you can't fix them? I still appreciate the reply.
I thought from the way you were arguing against PAL versions that you were able to make a fix and just didn't want to because you didn't like PAL. :P

You're right, those are indeed my only two options. If it's ok, I'll leave this open on the offchance @FIX94 comes back or some other coder sees it.

**Comment by carnage702** [comment]
> 
> 
> Well it doesn't display properly without the patch so I don't know about calling it fully compatible...
> 
> I'm sorry, I didn't realise you weren't a coder at all. Why are you responding to issues on the tracker if you can't fix them? I still appreciate the reply.
> I thought from the way you were arguing against PAL versions that you were able to make a fix and just didn't want to because you didn't like PAL. :P
> 
> You're right, those are indeed my only two options. If it's ok, I'll leave this open on the offchance @FIX94 comes back or some other coder sees it.

i was the main tester of nintendont so i know about allmost all of its quirks and 99% of the issues is people with bad isos, bad forced settings, bad setup and so on, not everything needs to be coded to be solved, heck most things are all user error or some imcompatible setup they have.

**Comment by SirPrimalform** [comment]
Ah, that makes sense. Thanks for your time anyway!

**Comment by SuperrSonic** [comment]
@SirPrimalform If you just want to stretch the screen, you could try this code:

Melee PAL VIW to 704
284b2e0e 00000280
024b2e0a 00000008
024b2e0e 000002c0
e0000000 80008000

It's working on Dolphin, the game reports it correctly but I can't guarantee if it'll work here.
The second line is the position, the third is the width. You can do up to 720, as shown by the likes of Not64 it's possible to go up to 1440, but it requires more than just changing this value and it's not compatible with a lot of TVs, probably not even the Wii U gamepad. I tested it on two HDTVs, one EDTV and one CRT and it only worked on the CRT.

**Comment by SirPrimalform** [comment]
@SuperrSonic 
Thank you! I'll give it a go.
