### ISSUE TITLE
Game crashes a minute of being launched

### ISSUE THREAD

**Issue by santi134565** [FIX94/Nintendont#813]
Hello.
im having this problem, i try to play mario sunshine but after a minute of being launched the game crashes with the an error has ocurred screen, i made the Nintendont log the game and got this

Patch:[__OSInitAudioSystem] not found
Patch:[__DSPHandler] not found
Patch:[PADControlAllMotors] not found
Patch:[PADIsBarrel] not found
Patch:[__PADSetSamplingRate] not found
Patch:Using a EXI Timing of 1900
Jumping to 0x8000522C

**Comment by carnage702** [comment]
Take a picture of your nintendont settings
