### ISSUE TITLE
Games Crash when MCEMU turned on for SD Card

### ISSUE THREAD

**Issue by Eltusto** [FIX94/Nintendont#814]
Is there a way to get MCEMU saves to go to a FAT32 USB stick or USB drive even if the games are on the SD card or a Wii U formatted harddrive?

**Comment by carnage702** [comment]
> 
> 
> Is there a way to get MCEMU saves to go to a FAT32 USB stick or USB drive even if the games are on the SD card or a Wii U formatted harddrive?

the only way on wiiu to make saves be on the usb is if you use vwii itself and not injects, if you use nintendont through vwii you can put isos and everything on sd card and using vwii homebrew channel inside vwii itself will allow nintendont to read the iso from the flashdrive and save on it.

if you use inject method you loose usb fat32 acess and nintendont cant save on wiiu becuase its not a wiiu app therefore has no acess to wiiu memorys to save and vwii inject disables acess to fat32 usb only sd works when using injects, nintendont cant read wiiu formated hdd inject but cant write to it becuase no acess is given.

**Comment by Eltusto** [comment]
Thank you so much for your response, unless I can sort out my SD card issue I guess i'm sticking with vWii not injects
