### ISSUE TITLE
[Request] Wireless Connection With GBArunner2

### ISSUE THREAD

**Issue by DraconicNEO** [FIX94/Nintendont#815]
Very Important, Read this First: This has nothing to Do with the Gameboy Player, This is for Games that use link cable support i.e. The Legend of Zelda: Four Swords Adventures, Animal Crossing, etc.

I think it would be a good idea to add wireless link functionality in order to play games that require a link cable using GBArunner2. This would be helpful for many users who don't have a GBA and/or link Cable (or are using the Wii U) but do have a DS/DSi/3DS.

There was a post related to this on the GBArunner2 github a while back, you can see that [here](https://github.com/Gericom/GBARunner2/issues/147)

**Comment by Arlisbloxer05** [comment]
As much as I'd love to be behind on this, i don't think it'd be possible. GBARunner2 would need to be rewritten heavily and Nintendont's kernal is already fragile enough with the BBA emulation. Maybe if someone found a way to somehow optimize the hell out of it even further (maybe even to the point where we could even do netplay on consoles) there might be enough of a chance for it to happen. Unfortunately though unless someone here wants to pick up where Fix left off and do both of these i doubt we'd see this come to fruition.

**Comment by Farhan1379** [comment]
Is there other Multiplayer Wireless Connection Without Wifi Link?

**Comment by DraconicNEO** [comment]
> Is there other Multiplayer Wireless Connection Without Wifi Link?

There's already BBA emulation, which lets you play GameCube games online. The GBA link would be more for connecting GBA games running on GBArunner2 to gamecube games running on Nintendont to unlock features in either game, that's how GC2GBA link worked.
