### ISSUE TITLE
PS3 Controller wont work on nintendont

### ISSUE THREAD

**Issue by imnotanog** [FIX94/Nintendont#816]
Hello, so I just followed a YT video instructing how to connect a ps3 controller to a Wii. I followed every step but on the last one where you plug in the controller and turn it on, for me it just flashes and won't connect showing the one red light. pls help. The link to the video is https://www.youtube.com/watch?v=EDXS32SvdEM&t=86s.

**Comment by carnage702** [comment]
first off is your ps3 controller an official controller?
take a picture of your nintendont settings.
do you have anything connected to the usb ports of the console besides the ps3 controller? also is your ps3 controller cable a data cable? some usb charging cables are only for charging and do not transfer data.
