### ISSUE TITLE
Possible graphics issue with Eternal Darkness

### ISSUE THREAD

**Issue by ViiMaster** [FIX94/Nintendont#817]
Hello! First, a big thanks to all the Nintendont developers for your great work! 

Now, I have a PAL Wii U with the the latest firmware running the latest, at the time of writing, version of Nintendont.

Whilst playing Eternal Darkness (USA Version), I've noticed a strange visual issue that sometimes occurs on the TV but not at the tablet. Please check the uploaded photos.

- These lines appear only when the camera moves from left to right and from right to left fast.
- When the screen is in one place, the image is fine... No lines/distortion.
- If the issue occurs, it happens for the whole time the game is active. If I turn off the Wii U, turn it ON and boot the game again, the lines might gone and the game will run normal.
- The issue from the game session that appears in the photo, is taking place at the top part of the TV and goes all the way, from left to right. But when it happened before it was placed a bit lower, towards the center of the TV.

This issue appears only with Nintendont (and Eternal Darkness so far... I haven't noticed it in other GameCube games but further testing needs to be done). It never happened with a Wii game or a Wii U game.

![IMG_20200430_183113](https://user-images.githubusercontent.com/23120955/93987356-1f45af80-fd90-11ea-92ff-52ab348050f9.jpg)
![IMG_20200430_183016](https://user-images.githubusercontent.com/23120955/93987502-4f8d4e00-fd90-11ea-89f0-d180d8774fce.jpg)

**Comment by carnage702** [comment]
this is screen tear its not a bug lol many games have this issues even on today standards, specialy xbox one games, you dont notice it on the gamepad becuase the screen is much smaller so the game bugs get hidden much better so you cant notice it since nintendont displays the exact same picture on both screens.

**Comment by ViiMaster** [comment]
Hello,
thank you for clearing that one up. However I'd like to mention that I've never encountered this bug in my life before on any console (XBOX 360, PS3, Wii U, Xbox ONE, PS4) or in any of the non-hdmi ones... Anyway, if you say its a standard bug, I trust you...

**Comment by ViiMaster** [comment]
I have found something extremely similar here:
https://www.reddit.com/r/Gamecube/comments/c4lf44/help_gc_hdmi_screen_tearing/

Of course the more I see it now, i realize that it is not a Nintendont bug lol

**Comment by carnage702** [comment]
this is an issue that happens in alot of games when a wierd refresh framerate combo happen like this  see the shift to the side of the fences

https://i.redd.it/2ysne1jflyg21.jpg

**Comment by ViiMaster** [comment]
Oh I see,,, Very interesting. It amazes me that in 2020 where the HDMI protocol is digital and way more advanced, we get to deal with issues like these! Thank you for the explanation and for baring with me! :)
