### ISSUE TITLE
Enhancement Request - option to read and save to SD gecko

### ISSUE THREAD

**Issue by DraconicNEO** [FIX94/Nintendont#818]
I'm surprised that this isn't already a feature but I think it would be a good idea to be able to have Nintendont access SD gecko to load games and create virtual memory cards on them. Please Note this is not a thread about SD gecko emulation or homebrew patching [like this one](https://github.com/FIX94/Nintendont/issues/407), this is about using an SD gecko as a Source for loading Games (and also saving memory card images) just like how SD cards and USB drives are used. I hope this is considered, being able to use SD gecko in place of an SD card or usb can be very useful.

**Comment by GB-CG** [comment]
The best bet is to create a fork of this repository and try to come up of a code that can do that. Pull requests are not even being merged at the moment.

**Comment by DraconicNEO** [comment]
That's too bad since there are a lot of things that need updating in Nintendont

**Comment by DraconicNEO** [comment]
I don't see what is trevor403's problem I'm just saying that there's room for improvement.

**Comment by DraconicNEO** [comment]
That's too bad since there are a lot of things that need updating in Nintendont

**Comment by eku** [comment]
AFAIK SDgecko behaves like an real Memory Card and Nintendont supports real Memory Cards. So what's your the point?

**Comment by DraconicNEO** [comment]
> 
> 
> AFAIK SDgecko behaves like a real Memory Card and Nintendont supports real Memory Cards. So what's your point?

I don't think you understand what an SD gecko actually does. FYI it doesn't work like a Memory Card, it is an SD card adapter that connects to the memory card slot the key difference is that the SD gecko does not (and will probably never) support saving on it like a memory card. Its primary purpose is loading and Saving files on an SD card. The main idea of this was to allow Nintendont to load games from an SD gecko as one of the sources.
