### ISSUE TITLE
Issue with reading SD card on Wii U

### ISSUE THREAD

**Issue by RainbowAsteroids** [FIX94/Nintendont#821]
I've been trying to play a gamecube game through Nintendont and VC injects, however, whenever I boot up a GC game, I get this error stating that Nintendont failed to create a memory card file. I threw the iso onto my sd card, following and double checking the `sd:/games/[GAME NAME]/game.iso` format, Nintendont failed to find my iso.

When I run the VC inj on a prior version, 5.486, build date Dec 18, 2018, Nintendont tries to create a memory card file and once it's done with that process, my Wii U just shuts off.

My SD card is formated with 32K size clusters, my SD card is not locked, and I have tried with two SD cards, so I do not believe the issue is related to any single SD card. It is also worth noting that Nintendont will work if I have generated a config with memory card virtualization turned off.

[Tree of my SD card if anyone is curious](https://pastebin.com/TnxuUXxP)

**Comment by carnage702** [comment]
Just means your sd card is too slow or fragmented and can't create save file on time, my recommendation is to do a slow format on the sd card
