### ISSUE TITLE
CONFIRMED: BBA emulation does NOT work with 2 LAN adapters via crossover cable between 2 Wii consoles.

### ISSUE THREAD

**Issue by Abro61209** [FIX94/Nintendont#823]
I have 2 homebrewed wiis (obviously). One is 4.1U and one is 4.3U. Don't know if that matters, highly doubt it does. Upon testing via wifi double dash and kirby air ride both work flawlessly except I absolutely hate wifi and would much prefer a wired connection. 

I tried 2 LAN adapters that are both compatible with the wii (I tested them) and plugged in a crossover cable I made at school (I am an IT undergrad student) I know for a fact the crossover cable still works because I am able to LAN play just fine on my PS2s, and was able to configure an old gateway router/switch I had through this same crossover cable.

What's weird is the yellow and green lights go on on both LAN adapters when booting up the games even with all network profiles erased on my wii. I did notice the yellow lights were pretty solid and rarely blinked which usually means there is no data activity. I also even tried making a wired profile and my wii and selecting that in nintendont's BBA emulation section to no avail. I even tried a regular old Ethernet Switch I had lying around and that still didn't work. The Ethernet Switch and the crossover cable between 2 adapters either freeze the games when I hit LAN mode, or just sit at "Establishing LAN link,,," and then failing everytime.

EDIT: I wonder, would I need to assign a static IP and DNS to both wiis in order for a direct connection to work? I know it works that way on PS2 even with a direct connection via crossover but you couldn't assign static IPs and DNS on the gamecube so I have a feeling that wouldn't matter.

EDIT 2: Yeah Static IPs and manual DNS didn't work with the crossover. You do in fact need a router and plug both Wiis into it to get a wired connection. I will now close the issue.

**Comment by carnage702** [comment]
wiis need to have a network to connect, maybe try putting a router between them even if said router is not connected to the internet.

**Comment by Abro61209** [comment]
@carnage702 Hmm I have another ethernet switch that's connected to my router. Let me see if that would work.

**Comment by Abro61209** [comment]
@carnage702 Ok that seemed like it worked. I understand now. The BBA emulator piggybacks off of the Wii's internet profiles created on the system. I was under the assumption it was just simulating an actual BBA adapter hence why the gamecube works with 2 adapters and one crossover cable. I understand now that the Wii actually needs a device with DHCP to actually automatically distribute IPs to those devices in order for this BBA emulator to communicate. I will use my old gateway/router I changed to act as a switch and program it back to act as a router since theoretically that should work. 

Theoretically, assigning static IPs and DNS to the Wiis and then connecting them via crossover should work as well but it didn't seem to work for me. Maybe I missed something, idk. Thanks anyway!
