### ISSUE TITLE
Dragon Ball Z Budokai 2 (PAL) Screen flickering 

### ISSUE THREAD

**Issue by ShadowsuperZ** [FIX94/Nintendont#824]
Alright very new and nooby here. Tried finding the same problem but couldn't find it anywhere. I'm using component cables "the 5 cables with green and 2 reds and white and blue" and connecting them through an adapter that uses HDMI since my tv doesn't have any component slots. The issue is, this is the only game that does this. I tried another Wii PAL game but that didn't show any issues. I tried forcing pal60 and pal50 patch and still flickers. Forcing NTSC just shows a black screen. Using an NTSC Wii and hoping to get any support. Thanks in advance.

**Comment by carnage702** [comment]
did you tryed using the ntsc version of the game? i mean why not?

also take a picture of your nintendont settings.

**Comment by ShadowsuperZ** [comment]
alright lemme take a picture. also i don't want to use the ntsc ver because it doesn't have the opening with lyrics unlike the pal one :)

**Comment by ShadowsuperZ** [comment]
![20201028_140012](https://user-images.githubusercontent.com/73606883/97477464-0c417480-1926-11eb-8914-141eebd72dd8.jpg)

**Comment by carnage702** [comment]
well you have a bunch of stuff that might be messing with it so turn everything to off or auto that isnt necessary,

debugger off
unlock read speed off
osreport off
log off

Video auto(unless your tv doesnt support pal signals) where you simply choose force ntsc)
video width auto
patch pal 50 off

try again with verything off, also try the ntsc version just too see if it does the same incase this doesnt help you.

**Comment by ShadowsuperZ** [comment]
ok i tried with turning all the things u said off and it still flickers. as for the cable thing. i just played other games and they worked smoothly so im very sure it's not that and i unplugged and plugged again and same issue anyways. lemme try with the ntsc version rq

**Comment by ShadowsuperZ** [comment]
well the ntsc ver works fine but i still don't understand what's the issue here

**Comment by hurda** [comment]
Does it work with the ordinary composite-cable (yellow/white/red) straight into the tv?

**Comment by ShadowsuperZ** [comment]
sadly my tv doesn't have any ports for em i use an adapter that converts component to hdmi

**Comment by carnage702** [comment]
> Does it work with the ordinary composite-cable (yellow/white/red) straight into the tv?

Obviously yes, nintendont works the same way the Wii does, but it might be your tv incompatibility with the pal resolution of the game, some games have wierd internal resolutions on pal and ntsc tvs might not like them

**Comment by ShadowsuperZ** [comment]
the game runs at 480i from what ive seen and ive tried other pal games and didn't have any issues so it's still weird

**Comment by carnage702** [comment]
> the game runs at 480i from what ive seen and ive tried other pal games and didn't have any issues so it's still weird

I highly doubt it's 480i that is ntsc games standard resolution, pal games. With 50 hz run at 576i, also the game might be hardcoded for 50hz and your ntsc tv might not like 50hz not all games run at standard resolution tough.

**Comment by ShadowsuperZ** [comment]
ok i just tried using force pal 50 on soul calibur 2 ntsc and it seems you are very much correct as the same problem occured.

**Comment by ShadowsuperZ** [comment]
but is there no way to patch a pal60 or force ntsc on the game or anything? that'd be very helpful

**Comment by carnage702** [comment]
> 
> 
> but is there no way to patch a pal60 or force ntsc on the game or anything? that'd be very helpful

there is that is why there is the force video mode options, but those are hacks that is why they dont work on every game, and like you said force ntsc did blackscreen and force pal60 did nothing so yeah the game is not affected by nintendont forced video mode hacks.

so yeah sadly you either get a tv that supports 50hz or use the ntsc version, so i think this is solved since its the tv that is imcompatible with 50 hz mode.


you can try force videomode to ntsc but not all pal games can be forced, if they are hardcoded ro 50hz is very hard to force them into 60hz unless you made a specific hack code for that game alone.
