### ISSUE TITLE
Savegamemanager

### ISSUE THREAD

**Issue by Senseless-Creature** [FIX94/Nintendont#825]
Hey is there an option to copy Savegames from a Virtual-Memorycard (SD) to a real GC-Memorycard or SD-Gekko and back? This would be really cool :)

**Comment by carnage702** [comment]
> 
> 
> Hey is there an option to copy Savegames from a Virtual-Memorycard (SD) to a real GC-Memorycard or SD-Gekko and back? This would be really cool :)

there is but that isnt done by nintendont but by other homebrew apps on the wii like gcmm
