### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by asheenlevrai** [FIX94/Nintendont#829]
Hi :)

Is it at all **possible** to play GC games on Nintendont using a **SNES controller**?

I have a SNES controller that connects through USB (iBuffalo classic USB gamepad). I DLed "HIDtest" and launched it from the HBC. When it asks to press buttons and check if the series of displayed numbers are changing, they do. Every button on the gamepad induces a change in one of the displayed numbers. (However, the only way for me to exit HIDtest is to power down the Wii. Don't know if this is normal).

Now when I launch a GC game (tried Metroid prime and Zelda) my gamepad doesn't work at all.
The Wiimote doesn't work either but it works once the nunchuck is connected to it (as described in some tutorial I read).

I'd love to be able to play with a SNES gamepad rather than a GC gamepad if this is possible.
Please let me know.
Best,
-a-

**Comment by carnage702** [comment]
im guessing the dpad is mapped to the gc dpad which makes 99% of the games unplayable since most games dont use the gc controller dpad not even to manover in the menus let alone gameplay.

**Comment by asheenlevrai** [comment]
Thanks 👍 

I guess I will have to google every single word you just used and educate myself before I can make sense of what you just said ;-)

Does this mean that my controller is incompatible (and maybe "SNES-like" USB controller would work)? Or does it mean that there is no way to use such controllers in nintendont?

Also, what about the SNES "classic" controllers? those that ship with the SNES classic or mini or whatever it is called and that can actually plug into the Wiimote? Would these work in nintendont?

Thanks
-a-

**Comment by carnage702** [comment]
What I mean is snes dpad is mapped to gc controller dpad almost for sure, and most games don't use the gc dpad for moving in game or even on the menus, most games are just coded that way, so you don't have the analog stick to work most games on a snes controller.

**Comment by asheenlevrai** [comment]
OK, thanks a lot for the explanation.
IIUC this means a(ny) controller with an analog stick is required.

**Comment by carnage702** [comment]
> 
> 
> OK, thanks a lot for the explanation.
> IIUC this means a(ny) controller with an analog stick is required.

pretty much since 99% of gc games use the analog stick as the main way to controll the menus/gameplay and dpad is relegated to minor stuff, that is why its so tiny on the gc controller.

**Comment by asheenlevrai** [comment]
I understand...
And I guess there is no way to use the dpad instead of the analog stick by remapping or anything.
I hate analog sticks ;)

**Comment by asheenlevrai** [comment]
Just another 2 cents:
I connected a SNES classic controller to the wiimote and it "works" in nintendont.
It works in the menus and in game. Now, obviously games are not playable since there are not enough buttons on the SNES gamepad I guess. Especially the lack of analog stick is problematic.

Maybe I should consider something like the 8Bitdo SN30 Pro or the TechKen SNES Classic Pro Controller

**Comment by GB-CG** [comment]
[How about this?](https://www.raphnet-tech.com/products/snes_to_wii/index.php) I've finally got one recently for Gameboy interface but works for Nintendont too, depending what you want to play.

**Comment by asheenlevrai** [comment]
Well I already have those SNES classic gamepads that can plug into the Wiimote.
AFAIU I cannot play GC games with these since they lack an analog stick and the analog stick cannot be remapped to the dpad of the SNES gamepad.
IIUC the Raphnet adapter you mentioned would allow me to connect an SNES controller (with a "regular" SNES connector) to the GC connector on the side of the Wii. I would ths suffer the same limitations as with my current setup, right? I couldn't play GC games due to the lack of analog stick.
Let me know if I'm wrong please :)
Thank you very much for your input.
Best,
-a-

**Comment by carnage702** [comment]
> 
> 
> Well I already have those SNES classic gamepads that can plug into the Wiimote.
> AFAIU I cannot play GC games with these since they lack an analog stick and the analog stick cannot be remapped to the dpad of the SNES gamepad.
> IIUC the Raphnet adapter you mentioned would allow me to connect an SNES controller (with a "regular" SNES connector) to the GC connector on the side of the Wii. I would ths suffer the same limitations as with my current setup, right? I couldn't play GC games due to the lack of analog stick.
> Let me know if I'm wrong please :)
> Thank you very much for your input.
> Best,
> -a-

obviosuly yes, that adapter was made to play simpler games like wiivc titles from nes,snes,genesis and whatnot that dont require too many buttons and have dpad mapped.

i dont get why you would ever want to play a gc game with a snes controller even if you found a way to map the dpad to analog stick you still couldnt play most games since you lacku buttons.

no c stick means lots of games function become unplayable  and you would loose the dpad which is used to do alot of things like switch powers/weapons, and so on on many games same for missing the Z button which is used in almost every gc game.

its never ever good to play a game with a controller with tons of buttons missing.

**Comment by asheenlevrai** [comment]
> > Well I already have those SNES classic gamepads that can plug into the Wiimote.
> > AFAIU I cannot play GC games with these since they lack an analog stick and the analog stick cannot be remapped to the dpad of the SNES gamepad.
> > IIUC the Raphnet adapter you mentioned would allow me to connect an SNES controller (with a "regular" SNES connector) to the GC connector on the side of the Wii. I would ths suffer the same limitations as with my current setup, right? I couldn't play GC games due to the lack of analog stick.
> > Let me know if I'm wrong please :)
> > Thank you very much for your input.
> > Best,
> > -a-
> 
> obviosuly yes, that adapter was made to play simpler games like wiivc titles from nes,snes,genesis and whatnot that dont require too many buttons and have dpad mapped.
> 
> i dont get why you would ever want to play a gc game with a snes controller even if you found a way to map the dpad to analog stick you still couldnt play most games since you lacku buttons.
> 
> no c stick means lots of games function become unplayable and you would loose the dpad which is used to do alot of things like switch powers/weapons, and so on on many games same for missing the Z button which is used in almost every gc game.
> 
> its never ever good to play a game with a controller with tons of buttons missing.

Of course, missing buttons is a no-go.
I wonder if it would be possible to use both buttons from the wiimote and the controller that would be connected to it.
in the case of an SNES classic controller, this would make 6 (wiimote*) + 8 (snes) buttons as well as 2 dpads, one of which could replace the analog stick.
I understand that playing with 2 controllers would not necessarily be convenient but may for games where buttons are used for "secondary" actions (display a map or equipment, camera movement, ...) while 6 to 8 buttons would be enough for main actions in the game (shoot, jump, move, pause, ...).
IDK... This would also require the ability to map buttons on a per-game basis...

*the home button would be reserved to exit the game/app

**Comment by carnage702** [comment]
> 
> 
> > > Well I already have those SNES classic gamepads that can plug into the Wiimote.
> > > AFAIU I cannot play GC games with these since they lack an analog stick and the analog stick cannot be remapped to the dpad of the SNES gamepad.
> > > IIUC the Raphnet adapter you mentioned would allow me to connect an SNES controller (with a "regular" SNES connector) to the GC connector on the side of the Wii. I would ths suffer the same limitations as with my current setup, right? I couldn't play GC games due to the lack of analog stick.
> > > Let me know if I'm wrong please :)
> > > Thank you very much for your input.
> > > Best,
> > > -a-
> > 
> > 
> > obviosuly yes, that adapter was made to play simpler games like wiivc titles from nes,snes,genesis and whatnot that dont require too many buttons and have dpad mapped.
> > i dont get why you would ever want to play a gc game with a snes controller even if you found a way to map the dpad to analog stick you still couldnt play most games since you lacku buttons.
> > no c stick means lots of games function become unplayable and you would loose the dpad which is used to do alot of things like switch powers/weapons, and so on on many games same for missing the Z button which is used in almost every gc game.
> > its never ever good to play a game with a controller with tons of buttons missing.
> 
> Of course, missing buttons is a no-go.
> I wonder if it would be possible to use both buttons from the wiimote and the controller that would be connected to it.
> in the case of an SNES classic controller, this would make 6 (wiimote*) + 8 (snes) buttons as well as 2 dpads, one of which could replace the analog stick.
> I understand that playing with 2 controllers would not necessarily be convenient but may for games where buttons are used for "secondary" actions (display a map or equipment, camera movement, ...) while 6 to 8 buttons would be enough for main actions in the game (shoot, jump, move, pause, ...).
> IDK... This would also require the ability to map buttons on a per-game basis...
> 
> *the home button would be reserved to exit the game/app

why would anyone go through this, it would just make everything god awful to control, serious no one would ever use that let alone loose time working on it.  

seriously if you want to play games only use the snes controller than you should leavue gc games alone since they were made to play with analog stick and alot more buttons, if you cant use any controller besides the snes one just dont play gc games its way simpler for you, they arent the games you would like to play or could with a snes controller.

**Comment by asheenlevrai** [comment]
Yeah... That makes sense.

**Comment by sergioad** [comment]
I wish and I would love if someone could add a feature on the wii classic controller in which by holding for a while a certain button combo you switch the ZL and ZR inputs with the L and R inputs while also mirroring the GameCube Z to ZL and -, I own a SNES classic edition controller and with this mode I could play Dpad heavy games like Capcom Vs. SNK 2 EO and Megaman network transmission without loosing any input whatsoever; BTW while I could certainly buy an aftermarket classic controller I do not like the fact that I could end with a low quality product which could break easily, I prefer the feeling of OEM parts and thus I am stuck with my SNES controller

**Comment by carnage702** [comment]
> 
> 
> I wish and I would love if someone could add a feature on the wii classic controller in which by holding for a while a certain button combo you switch the ZL and ZR inputs with the L and R inputs while also mirroring the GameCube Z to ZL and -, I own a SNES classic edition controller and with this mode I could play Dpad heavy games like Capcom Vs. SNK 2 EO and Megaman network transmission without loosing any input whatsoever; BTW while I could certainly buy an aftermarket classic controller I do not like the fact that I could end with a low quality product which could break easily, I prefer the feeling of OEM parts and thus I am stuck with my SNES controller

![wii-classic-controller-20061118030321009](https://user-images.githubusercontent.com/12446178/101131979-1843e480-35fe-11eb-88f1-6c93aa6660f8.jpg)

you do know that CC  ZL and ZR are tiny buttons that are hard to reach right? so no one would use this feature because it would no make sense to use on a real classic controller, also nintendont is not compatible with most 3rd party/fake controllers, so if you buy a classic controller buy an used original one, they arent that expensive at all.People ask for features that are so specific that only a handful of people would ever use them at all.

**Comment by sergioad** [comment]
> > I wish and I would love if someone could add a feature on the wii classic controller in which by holding for a while a certain button combo you switch the ZL and ZR inputs with the L and R inputs while also mirroring the GameCube Z to ZL and -, I own a SNES classic edition controller and with this mode I could play Dpad heavy games like Capcom Vs. SNK 2 EO and Megaman network transmission without loosing any input whatsoever; BTW while I could certainly buy an aftermarket classic controller I do not like the fact that I could end with a low quality product which could break easily, I prefer the feeling of OEM parts and thus I am stuck with my SNES controller
> 
> ![wii-classic-controller-20061118030321009](https://user-images.githubusercontent.com/12446178/101131979-1843e480-35fe-11eb-88f1-6c93aa6660f8.jpg)
> 
> you do know that CC ZL and ZR are tiny buttons that are hard to reach right? so no one would use this feature because it would no make sense to use on a real classic controller, also nintendont is not compatible with most 3rd party/fake controllers, so if you buy a classic controller buy an used original one, they arent that expensive at all.People ask for features that are so specific that only a handful of people would ever use them at all.

How awful you did not tot the idea, I have a Nintendo Officially made, controller but for the SNES classic edition, it is NOT a cheap knocki off

**Comment by carnage702** [comment]
> > > I wish and I would love if someone could add a feature on the wii classic controller in which by holding for a while a certain button combo you switch the ZL and ZR inputs with the L and R inputs while also mirroring the GameCube Z to ZL and -, I own a SNES classic edition controller and with this mode I could play Dpad heavy games like Capcom Vs. SNK 2 EO and Megaman network transmission without loosing any input whatsoever; BTW while I could certainly buy an aftermarket classic controller I do not like the fact that I could end with a low quality product which could break easily, I prefer the feeling of OEM parts and thus I am stuck with my SNES controller
> > 
> > 
> > ![wii-classic-controller-20061118030321009](https://user-images.githubusercontent.com/12446178/101131979-1843e480-35fe-11eb-88f1-6c93aa6660f8.jpg)
> > you do know that CC ZL and ZR are tiny buttons that are hard to reach right? so no one would use this feature because it would no make sense to use on a real classic controller, also nintendont is not compatible with most 3rd party/fake controllers, so if you buy a classic controller buy an used original one, they arent that expensive at all.People ask for features that are so specific that only a handful of people would ever use them at all.
> 
> How sad you did not tot the idea and either way you got aggressive with me, , I have a Nintendo Officially made, controller but for the SNES classic edition, it is NOT a cheap knockoff

Just buy a real classic controller, doesn't matter if it's best or snes, they don't have enough buttons to play most GC games, seriously adding a code to mainline nintendont just so you could play 2or 3 GC games with a snes controller is ridiculous.

**Comment by sergioad** [comment]
The problem (and I reiterate) is that precisely I do not want to buy a knockoff wii classic controller, in where I live finding a genuine, reasonably priced and in good shape classic controller is a true odisey

**Comment by carnage702** [comment]
> The problem (and I reiterate) is that precisely I do not want to buy a knockoff wii classic controller, in where I live finding a genuine, reasonably priced and in good shape classic controller is a true odisey

So your gonna resignet yourself to play only 1% of a the gc library since you don't have enough buttons because you are afraid of not finding an original controller? Lol 
That isn't even a problem, nintendont is compatible with tons of controllers
Wiiu pro
Ps3
Ps4
Wiiu gc adapter + gc controller
Lots of simple hid controllers
You can buy any controller that says official or genuine on ebay, if it's fake you can just open a dispute and get your money back very easily.

**Comment by sergioad** [comment]
> > The problem (and I reiterate) is that precisely I do not want to buy a knockoff wii classic controller, in where I live finding a genuine, reasonably priced and in good shape classic controller is a true odisey
> 
> So your gonna resignet yourself to play only 1% of a the gc library since you don't have enough buttons because you are afraid of not finding an original controller? Lol
> That isn't even a problem, nintendont is compatible with tons of controllers
> Wiiu pro
> Ps3
> Ps4
> Wiiu gc adapter + gc controller
> Lots of simple hid controllers
> You can buy any controller that says official or genuine on ebay, if it's fake you can just open a dispute and get your money back very easily.

Ok... I will not try to argue with you any further... Apparently I can not state my position that well... Only keep in mind that in the country I live ebay is super insecure, any used original classic controller is priced around $60 being the price of an original modern first party gamepad, $60 in my country is too much (a week and a half of food for a family of four), even if I got a cheap and descent offer in eBay it's shipping cost is excessive and the only plausible way to get a classic controller is an aftermarket one, it is absolutely not feasible.

There are people like me who would be super benefitted from that feature
