### ISSUE TITLE
Wii Remote never turns off if Classic Controller is connected

### ISSUE THREAD

**Issue by Mimimax** [FIX94/Nintendont#830]
If the Classic controller is connected and the wiimote is on prior to booting a game, the wiimote never turns off until turning the console off or the batteries are out/over. It stays on with the 4 lights on simultaneously. It can be a bother as the batteries will keep getting drained as long as the console is on and the batteries are working.

**Comment by asheenlevrai** [comment]
I don't experience the same thing...
Or at least I didn't realize the wiimote would stay ON (the blue LEDs are OFF in my case)

How is this related to nintendont?
Best,
-a-

**Comment by Mimimax** [comment]
Well, it never happens to me with any of Wii's own software (even though Nintendont runs in wii mode), only (and always) on Nintendont while a game is running in it. Also I do play on a real Wii, not Wii U's vWii, if it makes a difference. And disconnecting the CC from the Wiimote after the effect has happened won't undo it until the console or batteries are off. I use default controller configs even.

**Comment by carnage702** [comment]
> 
> 
> Well, it never happens to me with any of Wii's own software (even though Nintendont runs in wii mode), only (and always) on Nintendont while a game is running in it. Also I do play on a real Wii, not Wii U's vWii, if it makes a difference. And disconnecting the CC from the Wiimote after the effect has happened won't undo it until the console or batteries are off. I use default controller configs even.

why do you even have a cc connected at all times if you dont use it on nintendont?
if the wiimote has nothing attached to it nintendont shuts it off when a game is started, obviously if it has a CC attached it consideres it a valid controller and doesnt turn it off. preety sure on homebrew that is how it works.

**Comment by Mimimax** [comment]
I don't like to bother having to keep connecting and disconnecting it, but if that is a general homebrew functionality and can't be changed for Nintendont itself then it's ok.

**Comment by carnage702** [comment]
> 
> 
> I don't like to bother having to keep connecting and disconnecting it, but if that is a general homebrew functionality and can't be changed for Nintendont itself then it's ok.

of course it is, if nintendont sees a valid controller for multiplayer why would we turn it off for no reason? this is how its coded.
