### ISSUE TITLE
Unable to build with latest version of devkitPro

### ISSUE THREAD

**Issue by AnthonyRyuki** [FIX94/Nintendont#832]
Here's what I get whenever I try to build:

Building Multi-DOL loader

make -C multidol
make[1]: Entering directory '/home/f_zer/Documents/Nintendont/multidol'
 ASSEMBLE    crt0.S
 COMPILE     cache.c
 COMPILE     main.c
 COMPILE     global.c
 COMPILE     apploader.c
 COMPILE     dip.c
 COMPILE     utils.c
 LINK        multidol_ldr.elf
collect2.exe: error: ld returned 53 exit status
make[1]: *** [Makefile:44: multidol_ldr.elf] Error 1
make[1]: Leaving directory '/home/f_zer/Documents/Nintendont/multidol'
make: *** [Makefile:27: multidol] Error 2

**Comment by lucarioknight56** [comment]
I'm getting a similar problem. I wanted to compile so I could customize the control inputs to work better with Mario Kart. Any ideas on what the problem is?

**Comment by Special-Niewbie** [comment]
Hi, if can be usefully for you, to solve all these problems on Windows I placed the folder into C:\Users\"Your Account" and open the Mingw64 in Administrator Mode . If not open it in Administrator Mode, this package it seems that cannot be access and makes the compiling issuses errors.

**Comment by AnthonyRyuki** [comment]
Sadly, that didn't work for me.

**Comment by Special-Niewbie** [comment]
If you have all the libs installed and environment ok. The unique thing that I noticed it's, that the build its so much sensitive if there are so many folder under folder and than the Nintendont folder to build it. So the .exe (if not blocking by the Antivirus) it gives, the problems when are not placed into your User account name in free have means mixed with others system folder; so and not under another folder. It will be temporary a mess because you will have your system folder + the Nintendont folder, try like that and launch the Command shell under administrator . If not let's found out the problems to share more specific movement that you make 😉 and Merry Christmas.

**Comment by AnthonyRyuki** [comment]
Merry Christmas to you! First I tried placing the Nintendont folder on the root of my C drive, then I followed your suggestion. Same result. Enabling or disabling administrator rights had no effect, either. When was the last time you updated devkitPro? Are you sure you have the latest version?

**Comment by Special-Niewbie** [comment]
My it's the latest 3.0.3 and modified the pacman repository download file because the devkitproit has a "lack", it doesn't download the repository for Mingnw64 and 32 but only the MSys2 that it cross the two Shell (but the libs are not the same). If you are interested, visit here my simple guide that I made for others under one SM64 port for Wii U: https://gbatemp.net/threads/super-mario-64-port-wii-u.571682/page-15

Let me know

**Comment by AnthonyRyuki** [comment]
It worked! Thanks a million.

**Comment by Special-Niewbie** [comment]
Happy to hear that 😉.

Please AnthonyRyuki, I don't know if you can help me about, but have you any idea ho can I solve one problem with one game triforce Virtua Striker 4 and Wii U PAD controller ; it's about the Y Axis UP little problem. I have opened a topic on the top of Issues section. Can you help me on that 🙏

**Comment by AnthonyRyuki** [comment]
I'm sorry but I don't own a Wii U.

**Comment by AnthonyRyuki** [comment]
I probably have a clue on how to fix that, though. The controls for the arcade games are coded in the kernel\JVSIO.c file, and the analog controls for VS4 start on line 397. For some reason, the offset for the Y axis is set to 7F, while the offset for the X axis is 80. You probably should set both offsets to 80.

**Comment by Special-Niewbie** [comment]
> I probably have a clue on how to fix that, though. The controls for the arcade games are coded in the kernel\JVSIO.c file, and the analog controls for VS4 start on line 397. For some reason, the offset for the Y axis is set to 7F, while the offset for the X axis is 80. You probably should set both offsets to 80.

It's ok, I just need to know which file to play with.....later I will try to thank you anyway

**Comment by AnthonyRyuki** [comment]
Welcome. Speaking of VS4, you may be interested in this pull request I made: https://github.com/FIX94/Nintendont/pull/767
Especially if you're Italian like me.

**Comment by Special-Niewbie** [comment]
> Welcome. Speaking of VS4, you may be interested in this pull request I made: #767
> Especially if you're Italian like me.

😅 Ops.....Grazie 1000 , non mi aspettavo un compaesano dall' altra parte 👌. Dopo ci provo, ti ringrazio veramente tanto e se ho bisogno di un consiglio a tal proposito, potrei ricontattarti? Buon natale di nuovo😉

**Comment by AnthonyRyuki** [comment]
Certo, ricontattami pure. Puoi farlo anche su Facebook se vuoi, ti passo il mio profilo: https://www.facebook.com/antonio.pompo/

**Comment by Special-Niewbie** [comment]
> Certo, ricontattami pure. Puoi farlo anche su Facebook se vuoi, ti passo il mio profilo: https://www.facebook.com/antonio.pompo/

Penso di essere uno dei pochi che non ha Facebook, per mia propria scelta Antonio, o ti ricontatto qui oppure tramite l'account di mio fratello che lui ne ha uno vecchio. Comunque piacere Cristian

**Comment by AnthonyRyuki** [comment]
Va bene, piacere mio

**Comment by Special-Niewbie** [comment]
Ciao Antonio, sei un grande il tuo consiglio era proprio quello che mi serviva, il problema sta nella riga 397 e bisogna cambiare il paramentro da 0x7F ad 0x80, non so' perche' c'e' questo piccolo bug, ma influenza il funzionamento del PAD della WiiU. In piu', ho anche aggiustato i pulsanti inerenti hai comandi. Che dire, mi hai fatto veramente un bel regalo di natale indirettamente; grazie ancora! Ho anche cambiato le righe che abilitano l' Italiano, seguendo il tuo utilissimo post. Sono veramente contento, non puoi immaginare. Se ti servira' qualcosa o scambiare qualche idea mandami pure l' email a questo indirizzo **special-niewbie@techie.com**  . Poi , ho notato che la cronaca Italiana funziona solo nella versione VS4 2004 e non nella ver. 2006; evidentemente nell' ultima versione 2006 e' stata tolta. Ora, vado a scrivere anche nella mia sezione, in modo di chiudere il ticket.

**Comment by AnthonyRyuki** [comment]
Bene, sono molto lieto di averti aiutato. Se guardi i miei altri pull request puoi notare altri miglioramenti che ho apportato ai giochi Triforce.

**Comment by Special-Niewbie** [comment]
Ora provo a stolkerarti un po' :). Sai cosa manca ancora? Il come aggiungere la memoria per VS4, hai qualche idea di come si possa creare?

**Comment by AnthonyRyuki** [comment]
Se intendi per salvare le impostazioni della modalità Test devi attivare la Memcard Emulation nelle opzioni di Nintendont.

**Comment by Special-Niewbie** [comment]
Sì quella è già attivata e non ha effetto sulla memorizzazione dei ranked, intendo la scheda interna al gioco, che dovrebbe servire per tenere in memoria I ranked , sembra che questa funzione non c'è.

**Comment by AnthonyRyuki** [comment]
Purtroppo non so come risolvere questo problema. Anche in F-Zero AX c'è una memoria che non viene salvata, ovvero quella dei fantasmi e dei record del Time Attack. Qui bisogna capire quale area della memoria contiene questi dati per poterla salvare, ma purtroppo temo che occorrano strumenti di debug che io non ho.

**Comment by Special-Niewbie** [comment]
Esatto, dovrebbe essere una cosa simile, spero che FIX94 riesca o qualcuno qui perché è un peccato non averla.

**Comment by AnthonyRyuki** [comment]
Già...

**Comment by Special-Niewbie** [comment]
Ciao Antonio, non sapevo come contattarti (anche se mi hai dato il tuo FB, ma ho un rifiuto nell' usarlo che non hai idea ;) ) Comunque questi giorni sono stato sempre a studiare sulla mod del Nintendont e sono riuscito ad apportare tutte le modifiche ed aggiornarlo. Ho aperto una sezione apposita nel sito di GBATemp, sentiti libero di modificarlo e se hai qualche miglioria da applicare ben venga. Questo è il link: https://gbatemp.net/threads/nintendont-crismmmod.580664/

**Comment by AnthonyRyuki** [comment]
Bene, ottimo! Metterò tutte le pull request che ho messo qui...

**Comment by hurda** [comment]
???
