### ISSUE TITLE
[Request] Per-Game Settings

### ISSUE THREAD

**Issue by GeigerCounter** [FIX94/Nintendont#834]
Simple request: Ability to create game-specific configuration from within Nintendont. For example, to use individual memory card mode for Animal Crossing while using shared memory card mode for games by default. As another example, using Native Control for Final Fantasy: Crystal Chronicles to be able to use the GBA Link system for multiplayer while other games use the regular controls.

**Comment by carnage702** [comment]
you can do per game settings using loaders like usbloader gx and such, nintendont will never support per game settings on its own that is why it was made to be incorporated on loaders.

**Comment by diegorocha2007** [comment]
Hey @carnage702, this request is still valid for WiiU when using injects. Per game settings would prevent conflicts with widescreen patched ISOs and/or widescreen cheat codes and the built-in "Force Widecreen" option.

In fact, I an having a hard time circumventing this limitation, as I want to use a patch for Wario World that works/looks better than nintendont's widescreen option, but one doesn't overwrite the other, and the result is a squished image, like a 21:9 compressed in a 16:9 frame.
And if I disable "force Widescreen", I fix this issue, but I lose widescreen for all the other games.

So a simple per-game setting would fix this issue, for WiiU that is
