### ISSUE TITLE
Crashes on game launch (freezes if vMemCard is OFF)

### ISSUE THREAD

**Issue by asheenlevrai** [FIX94/Nintendont#837]
Hi :)

I had nintendont running smoothly for a little while (I only recently modded my Wii).
Then I moved everything from my SD card to an external USB drive (MBR, FAT32) and also setup USB Loader GX. I have no SD card in the Wii right now.

However, nintendont stopped working since yesterday. Now, when I launch a game, right after "init Card" is displayed it crashes and the Wii turns OFF.

Google led me [here](https://www.reddit.com/r/WiiHacks/comments/2qm49x/nintendont_crashing_at_init_card_when_using/)... So I tried turning OFF memory card emulation. In this case, when I launch a game in nintendont, right after "init Card" is displayed it freezes (black screen) and the Wii stays ON (green LED).
The end result is similar, though.

I tried putting back my SD card, uninstalling and reinstalling nintendont via the HBB (Open Shop), update nintendont and everything else just in case, but now I don't know how to troubleshoot this any further...

Any suggestion is most welcome :)

Best,
-a-

**Comment by carnage702** [comment]
first you might have a corrupt ninconfig.bin on sd card, just delte it and then redo your settings before launching a  game, secodn you might have a corrupt save file, go to the saves folder and delete any 0kb file that is there, third might be your isos that got corrupted passing through or something, maybe you need a full sd specific format(not windows one) and then put everything back in. also make sure the sd card is unlocked too.

**Comment by asheenlevrai** [comment]
Thanks a lot :)
I'll check all that and report here ASAP.
I'll do all you said on the USB drive since I don't use an SD card anymore.
Best,
-a-

PS: I didn't have a save folder actually, but I created one manually for USB Loader GX in order to specify its path in the "custom paths" section of ULGX. This save folder should still be empty, I guess. Maybe that's a hint...

**Comment by asheenlevrai** [comment]
deleting nincfg.bin and re-configuring nintendont didn't solve the problem.
There were no 0KB files in the save folder. deleting all save files didn't solve the problem either.
Recopying my ISO files from a reliable source didn't solve the problem.
I guess my USB drive is OK since I have no other problems than trying to play GC games from nintendont. (ULGX works fine, SNES emulator works fine, ...)

**Comment by asheenlevrai** [comment]
If I use nintendont from my SD it works...
From my USB drive it doesn't...

**Comment by carnage702** [comment]
> 
> 
> If I use nintendont from my SD it works...
> From my USB drive it doesn't...

just shows your usb is incompatible with nintendont, do you have partitions? nintendont is not very friendly with partitions even hidden partitions made by the makers of said device.

Also it might just work to take everything out of your usb device, do a slow format and passing stuff back in again, if the usb is too fragmented, nintendont has very rough time reading it due to the custom usb code it uses so it fits into memory of nintendont.

**Comment by asheenlevrai** [comment]
It looks indeed that my disk is the culprit.
If I load roms from a different USB disk it works...
However, it used to work with that disk too.
And everything not related to nintendont works fine...
I tried to format and move everything back to the disk but I did a quick format and the problem remains...

I'll try a slow format I guess...

**Comment by carnage702** [comment]
> 
> 
> It looks indeed that my disk is the culprit.
> If I load roms from a different USB disk it works...
> However, it used to work with that disk too.
> And everything not related to nintendont works fine...
> I tried to format and move everything back to the disk but I did a quick format and the problem remains...
> 
> I'll try a slow format I guess...

slow formats are better, if it still doesnt work, then no idea, maybe some hidden partition or something is in there.

**Comment by asheenlevrai** [comment]
There are no hidden partitions according to Disk Utility (macOS) and Disk Management (Win10).
I'll try the slow format and report here. 
Thanks

**Comment by asheenlevrai** [comment]
It looks indeed that my disk is the culprit.
If I load roms from a different USB disk it works...
However, it used to work with that disk too.
And everything not related to nintendont works fine...
I tried to format and move everything back to the disk but I did a quick format and the problem remains...

I'll try a slow format I guess...

**Comment by asheenlevrai** [comment]
I formatted the drive in FAT32, 32KB clusters and still the smae issue with GC games in nintendont...
No problem with other drives.
No other problems with this specific drives (Wii games, Homebrew apps, ...)
I guess I'm just unlucky and I will thus use a different drive.
Thanks
-a-
