### ISSUE TITLE
Black Screen on launch 

### ISSUE THREAD

**Issue by yergerb** [FIX94/Nintendont#839]
I get a black screen if i launch a vc inject or nintendont forwarder. However if I launch the vwii first and launch the nintendont from the homebrew back out and then try the vc inject it works just fine. 

wii u
cbhc

**Comment by carnage702** [comment]
What version number you have of nintendont, take a picture of your nintendont settings

**Comment by yergerb** [comment]
![20201206_122516.jpg](https://user-images.githubusercontent.com/74698687/101287549-dca44880-37be-11eb-86f0-288d6cea889e.jpg)

The settings also seen to reset themselves with every launch. This is how they are displayed within the vwii.

**Comment by yergerb** [comment]
I did try to downgrade to another version in which I was able to boot into nintendont from the forwarder but it broke the actual forwarding.

**Comment by carnage702** [comment]
For some people the vwiivc injects don't work for some odd reason, a hey sometimes Boot other times don't, did you made the nintendont inject yourself or got it from somewhere else?  What speed is your sd card?

**Comment by yergerb** [comment]
I made it myself using multiple sources uwuvci, usb helper, 2 different 2 different iso sources for 1 game, 3 games total. all are hit or miss. i tried garys fork fixes, this one, older versions.

**Comment by carnage702** [comment]
> I made it myself using multiple sources uwuvci, usb helper, 2 different 2 different iso sources for 1 game, 3 games total. all are hit or miss. i tried garys fork fixes, this one, older versions.

Some wiius don't like Wiivc I never got some odd reason, I advise on trying to use fix94 open Homebrew channel, install it on vwii, then do a forwarder to the open Homebrew channel and start nintendont from there, maybe it works for you
