### ISSUE TITLE
Randomly shows GameCube Error Message

### ISSUE THREAD

**Issue by MarsBars06** [FIX94/Nintendont#842]
Hi,
My game keeps randomly pulling up the GameCube error message.
I have a 320GB external harddisk formatted to FAT32 with 32 KB clusters.
Can anybody please help?
Thanks

**Comment by MarsBars06** [comment]
Hi,
One more thing:  How fast is the USB harddisk supposed to be without any errors?
Thanks

**Comment by carnage702** [comment]
the error has occurred message can happen when the hdd or nintendont cant awnser fast enough

1 you have alot of settings turned on that can slow down nintendont8ke a picture of your nintendont settings)
2- your hdd is too fragmentated, nintendont doesnt like fragmentation, so do a slow format then copy everything back in.
3- not sure if you are on wiiu or wii but wiiu has crap eletric power through usb doors so you might need a y cable if your hdd doesnt have its own power supply
4-hdd has a sleep setting and goes to sleep and then when awakening up isnt fast enough to respond.

**Comment by MarsBars06** [comment]
Hi @carnage702
I'll try the slow format; the cIOS I have installed prevents the hdd from sleeping and I have a wii, not wiiu.
I'll try and send a picture of my nintendont settings.
Thanks

**Comment by carnage702** [comment]
> 
> 
> Hi @carnage702
> I'll try the slow format; the cIOS I have installed prevents the hdd from sleeping and I have a wii, not wiiu.
> I'll try and send a picture of my nintendont settings.
> Thanks

nintendont does not use any cios so if you think a cios affects nintendont it wont matter, since nintendont only uses wii official ios58 to run, heck the cios itself might even mess with nintendont while trying to acess the hdd if they are poking it since they are probably designed with wii games in mind.

**Comment by MarsBars06** [comment]
Hi @carnage702
I slow formatted the hdd to fat32 with 32k clusters, still freezing
There are no fragments on the disk (according to windows anyway)
I don't know if my hdd is sleeping however, but it works ok when playing wii games through wiiflow
Any other possible solutions?
Thanks for the help btw

**Comment by carnage702** [comment]
> Hi @carnage702
> I slow formatted the hdd to fat32 with 32k clusters, still freezing
> There are no fragments on the disk (according to windows anyway)
> I don't know if my hdd is sleeping however, but it works ok when playing wii games through wiiflow
> Any other possible solutions?
> Thanks for the help btw

Wii games and nintendont is very different, so my only suggestion is try another hdd or sd card

**Comment by MarsBars06** [comment]
using sd card in sd card slot - it works pretty fast now
thanks for helping
