### ISSUE TITLE
Wii Games Crash when loaded from Usb

### ISSUE THREAD

**Issue by OneManArmy600** [FIX94/Nintendont#843]
Whenever I try to load a Wii game. it displays this error message. It worked fine before with most games. Except now I can't get a single game to load. I do not know what is going on and would like some advice.
![20201213_165533](https://user-images.githubusercontent.com/75957804/102029696-3c24ca00-3d64-11eb-8b63-7c189f2bfe0d.jpg)

**Comment by carnage702** [comment]
Nintendont only plays gamecube games... It will never run Wii games.
