### ISSUE TITLE
Mario Kart Arcade GP 2 not working (black screen)

### ISSUE THREAD

**Issue by GaussTek** [FIX94/Nintendont#844]
MKAGP2 worked fine in earlier builds. Now, after the initial verification it just shows a black screen. Tried an old Nintendont build I had as a backup and works fine there, but not on the latest one.

MKAGP1 works just fine, it's just 2 that doesn't work. Any idea what could be the issue? Thanks a bunch!!

(Using a SD and Homebrew Channel on vWii uf that helps).

**Comment by carnage702** [comment]
works fine for me on 491, take a picture of your nintendont settings, it takes some seconds to start but it runs just fine.

**Comment by GaussTek** [comment]
Thanks! Just tried a new SD card formatted to 32kb cluster and it now works fine with latest version. Dunno why the other one didn't work just for this game lol
