### ISSUE TITLE
Wii classic controller pro and the wiimote aren`t working after I launch a game

### ISSUE THREAD

**Issue by Astarka06** [FIX94/Nintendont#845]
If I use an USB controller it works just fine, but the thing is I think the Wii classic controller pro is more accurate if I compare it to my fake ps2 usb controller. My wiimote + classic controller pro will work till i get to the menu, I can mess with the settings all of that but it stops working after I launch any game. Sometimes the wiimote says it's connected properly and sometimes it doesn't. I tried messing with the setting and nothing really changed. Am I missing something?

**Comment by Astarka06** [comment]
nintendont version: 4.431

**Comment by carnage702** [comment]
your nintendont is very outdated latest is 491.

Also if your Classic controller pro or wiimote are fake/3rd party they will most likely never work inside nintendont when a game is running, also if you have your usb controller connected it takes priority over bluetooth controllers.

gc controller through gc ports>usb controller>bluetooth controller.

**Comment by Astarka06** [comment]
> your nintendont is very outdated latest is 491.
> 
> Also if your Classic controller pro or wiimote are fake/3rd party they will most likely never work inside nintendont when a game is running, also if you have your usb controller connected it takes priority over bluetooth controllers.
> 
> gc controller through gc ports>usb controller>bluetooth controller.

My wiimote is original but my classic controller pro is probably fake  (i got it today and they said it`s original but i haven`t checked bc i wanted to get this working). It`s working right now, I was trying to fix this other problem and I moved the boot.dol to the root of my SD card and the classic controller pro started working lol
