### ISSUE TITLE
Solved! Virtua Striker 4 (2004-2006 version) and Wii U PAD as Controller - problem. Please help me

### ISSUE THREAD

**Issue by Special-Niewbie** [FIX94/Nintendont#846]
Hi, If you play with this game by the Wii U PAD, there is a problem with left stick all the way UP (the "Y" axis UP). The left axis UP, when you slide to all the way UP (last 2/3 mm) before touching the Wii U shell, the game read that the Y axis Up goes all the way to the Y axis Down. This happen only when you use the Wii U Pad as controller. Even if you calibrate the Axis by the Game calibration, it will do the same. Please can someone help me to fix it, even if it's necessary to do a Custom Nintendont boot.dol to play with this game only, just to fix this annoyng issue with the Y axis. 

PS: And to be sure that it's not the Wii U PAD problem, I already tested it with 3 different Wii U PAD and all of them has the same issue.

**Comment by Special-Niewbie** [comment]
Solved!!!!! And thanks to @AnthonyRyuki for his precious advice.
The problem it's in Nintendont configuration kernel, the specific Triforce file it's JVSIO.c that for some reason the stickY it's settled to 0x7F instead of 0x80 as the stickX. So, the configuration **0x7F** + **0x80** it's works with everything but except the WiiU Pad and the new configuration **0x80** + **0x80** it's works with everything and even with the WiiU Pad.

Merry Christmas

**Comment by Special-Niewbie** [comment]
I keep in this section, just to be more in highlight and in case others has the same problem....

**Comment by AnthonyRyuki** [comment]
Forse la cosa migliore da fare sarebbe aprire una pull request a riguardo.

**Comment by Special-Niewbie** [comment]
Hai ragione, ma è la prima volta che lo faccio qui su GitHub , come devo fare per caricarlo, Antonio? Perdonami

**Comment by AnthonyRyuki** [comment]
Tranquillo, ci penso io

**Comment by Special-Niewbie** [comment]
👌
