### ISSUE TITLE
WiiU...cannot update Nintendont online

### ISSUE THREAD

**Issue by eewokee** [FIX94/Nintendont#848]
Hi,

when I try to update Nintendont via de WiiU and broadband adapter I get:

Updating Nintendont
network Initialized
Checking latest version

then...my WiiU is stuck and I have to remove the power and restart.

**Comment by carnage702** [comment]
updater is broken for awhile, i mean i think it works but you need to wait like 10 minutes or something along those lines, you can update nintendont by hand to 491 by just clicking here

https://github.com/FIX94/Nintendont/blob/master/loader/loader.dol?raw=true  

 rename it to boot.dol and replace it on your apps folder under nintendont.

**Comment by eewokee** [comment]
Thanks! Ok. No problem.

**Comment by gingerbeardman** [comment]
Thanks. Thought there was something wrong with my setup.
