### ISSUE TITLE
Wind Waker L/R doesn't work with Classic Controller

### ISSUE THREAD

**Issue by 12buntu** [FIX94/Nintendont#850]
I'm playing TLOZ: Wind Waker on an original Wii using a classic controller plugged into the Wiimote. Unfortunately, I'm unable to use L/R buttons at all. Weirdly, when unplugging the classic controller from the Wiimote it seems to send a single R signal. I think it's an issue with this specific game from what I've read on old GBAtemp threads, although I have yet to test it with other games. The L/R buttons do seem to work on the homebrew channel menu, and on the Wii VC, so it's not a physical problem.

**Comment by carnage702** [comment]
is the classic controller also official? or a knockoff/3rd party?

**Comment by 12buntu** [comment]
> is the classic controller also official? or a knockoff/3rd party?

3rd party... is that a problem?

**Comment by carnage702** [comment]
> 
> 
> > is the classic controller also official? or a knockoff/3rd party?
> 
> 3rd party... is that a problem?

yup that is your issue, thrid party controllers have issues in homebrew in general, specialy in nintendont either buy official or dont for homebrew in general.

also if your classic controller reports something wierd it might even report inclorrectly as a classic controller pro which would make zr and zl be L and R instead.

3rd party and knockoffs have loads of issues in homebrew projects they arent recomended at all.

**Comment by carnage702** [comment]
what hid controller?

**Comment by 12buntu** [comment]
> what hid controller?

Logitech F310

**Comment by carnage702** [comment]
> 
> 
> > what hid controller?
> 
> Logitech F310

that one probably has a bad hid file im guessing since some hid controller need to specify if land r are digital or analog and valued acordinglly, i sugest on two things

1-not sure if you are on wii or wiiu but gc controllers are the best for gc games, the wiiu gc adapter works on wiis and wiiu even if your wii has no gc ports and an official wiiu smash controller or original gc controller is the best imo.

2- buy an official classic controller

3-use ps3 controller

4-wiiu pro controller works on nintendont on wii or wiiu even if it doesnt work on wii games per say.

6- original controller for all suggestions, they are abit pricey but they are better quality, last much more time and work perfectly on all homebrews.

**Comment by 12buntu** [comment]
> > > what hid controller?
> > 
> > 
> > Logitech F310
> 
> that one probably has a bad hid file im guessing since some hid controller need to specify if land r are digital or analog and valued acordinglly, i sugest on a couple of things
> 
> 1-not sure if you are on wii or wiiu but gc controllers are the best for gc games, the wiiu gc adapter works on wiis and wiiu even if your wii has no gc ports and an official wiiu smash controller or original gc controller is the best imo.
> 
> 2- buy an official classic controller(they arent the best since the analog stick ranges are crap compared to the gc ones)
> 
> 3-use ps3 controller
> 
> 4-wiiu pro controller works on nintendont on wii or wiiu even if it doesnt work on wii games per say.
> 
> 6- original controller for all suggestions, they are abit pricier but they are better quality, last much more time and work perfectly on all homebrews.

Will a 3rd party gamecube controller work?

**Comment by carnage702** [comment]
> 
> 
> > > > what hid controller?
> > > 
> > > 
> > > Logitech F310
> > 
> > 
> > that one probably has a bad hid file im guessing since some hid controller need to specify if land r are digital or analog and valued acordinglly, i sugest on a couple of things
> > 1-not sure if you are on wii or wiiu but gc controllers are the best for gc games, the wiiu gc adapter works on wiis and wiiu even if your wii has no gc ports and an official wiiu smash controller or original gc controller is the best imo.
> > 2- buy an official classic controller(they arent the best since the analog stick ranges are crap compared to the gc ones)
> > 3-use ps3 controller
> > 4-wiiu pro controller works on nintendont on wii or wiiu even if it doesnt work on wii games per say.
> > 6- original controller for all suggestions, they are abit pricier but they are better quality, last much more time and work perfectly on all homebrews.
> 
> Will a 3rd party gamecube controller work?

its like playing a lottery, some work, some dont, some drift and so on, again i dont recomend any 3rd party stuff, heck an original gc controller  used on the internet should be a more secure thing.
