### ISSUE TITLE
Virtual Memory Card on slot B don't work.

### ISSUE THREAD

**Issue by Vinnievovi** [FIX94/Nintendont#854]
I made a copy of ninmem.raw and renamed it to ninmemb.raw but slot B is still not recognized. Both are located inside the saves folder. I have enabled Memcard multi but it still does not work. The games are started via SD, where there are also the saves.

**Comment by carnage702** [comment]
Sloth must be  a 59 blocks memory card I'm guessing your isn't, nintendont needs the ram space so you must make the slot be be the slowest size

**Comment by Vinnievovi** [comment]
Actually, I had made a copy of a 251 blocks virtual memory card. Now, I tried to use a 251 blocks virtual Memory Card as slot A, and a 59 blocks virtual memory card as slot B, and it still didn't work. So I tried to create 2 virtual memory cards from 59 blocks and worked. Thanks for the support.

**Comment by Vinnievovi** [comment]
I'm writing this additional comment to help someone who needs to use slot B with only virtual memory cards. To use also slot B, with Memcard multi, both virtual Memory Cards must have 59 blocks, otherwise slot B will not be recognized. The virtual Memory Cards must be named in ninmem.raw and ninmemb.raw, and must  be placed in the saves folder.

**Comment by carnage702** [comment]
well its called nimemraw if its a multi memory card, you can also have individual slob be cards where the main one would be lik GC098.raw and the slot b would be gc098b.raw, slot b works for individual and multi, and like i said nintendont needs the ram free to actually work and cant just have 2 loaded memory cards that would eat it up and crash the games running and so on.
