### ISSUE TITLE
Rumble not working for WiiU Gamepad

### ISSUE THREAD

**Issue by GeigerCounter** [FIX94/Nintendont#855]
Rumble emulation not working for the WiiU Gamepad

**Comment by carnage702** [comment]
that is not a bug its something that cant be done, wiiugamepad only works in vwii injection which means nintendo coded it to be a wii classic controller, and wii classic controllers dont rumble, therefore nintendo did not enable rumble code on the vwii injection codding for wiiu gamepad, so unless someone deconstructs the wii injection codding by nintendo and enables some way to acess wiiu gamepad rumble it wont ever work.
