### ISSUE TITLE
Problem with progressive scan support - black borders on the sides

### ISSUE THREAD

**Issue by FaunoLabirintite** [FIX94/Nintendont#857]
When I play GameCube games on my OG Wii, 480i, the aspect ratio is correct.

However, when I play 480p games (native or forced), I get black borders, making the games "taller and thinner" than they should.

I can solve the problem by forcing a video scaling value (684 in my case), but that only works with forced 480p. Games with native 480p support, like Star Fox Adventures and Star Wars Rogue Squadron 2 change back and forth between correct and incorrect ratios.

I wonder if adding a setting to force the game to use Nintendont's own 480p implementation and ignore the game's would solve this issue.

**Comment by vaguerant** [comment]
Is it possible this is something your TV is doing? i.e. When receiving a 480i signal, it stretches the picture (hiding the black bars), but when receiving a 480p signal, it shows the picture unchanged (revealing the black bars). 480i vs. 480p should not change how wide the games are displayed by the console.

**Comment by FaunoLabirintite** [comment]
> Is it possible this is something your TV is doing? i.e. When receiving a 480i signal, it stretches the picture (hiding the black bars), but when receiving a 480p signal, it shows the picture unchanged (revealing the black bars). 480i vs. 480p should not change how wide the games are displayed by the console.

I suppose it is possible. I'll check if Wii 480p games do that as well. However, I think I would have noticed it.

**Comment by FaunoLabirintite** [comment]
Ok, so I've tested using Zelda Wind Waker via disc channel (I have an original copy) and it scales the same way. So, it must be the way my TV handles 480p specifically for GameCube games, since it doesn't happen in Wii games. I'll try forcing 480p via Nintendont to see what happens.

**Comment by carnage702** [comment]
like you said it also happens on regular gc disc channel so its an issue with your tv and not with nintendont so im closing this.
