### ISSUE TITLE
External USB drive slow startup after sleep - Unable to open the disc image file

### ISSUE THREAD

**Issue by Kwakers01** [FIX94/Nintendont#859]
So I have two Wii's both with different USB drives.  I am using USB LoaderGX and running GC's from USB LoaderGX.  The one hard drive works fine and will bring up GC games no problem what so ever.  The other drive brings up the "CheckForMultiGameAndRegion() failed: 1" and "Unable to open the disc image file".  I have moved the drive from the one Wii to the other so have come to the point where it is definitely due to the USB drive.  The drive is a Seagate External USB Drive, Model Number: ST310005EXD101-RK,Family: DESKTOP EXT DRIVE 0.1 FAMILY, Part Number: 9SE2D4-571.

Now the one thing I have noticed is that if I connect it to my Windows 10 PC and leave it a while, it goes into sleep mode.  If, when it has gone to sleep, I click on a folder icon, it can take up to 10-12 secs before the folder opens.

So I suspect that the issue people are having with External USB drives may be that the nintendont software may need to wait a while longer before throwing up the error message.

Is this a possibility?

If it is, would it be possible to get nintendont to count down when it is looking for the USB drive like USB LoaderGX does when you start it?

Thanks

**Comment by MarsBars06** [comment]
hi @Kwakers01 
[https://code.google.com/archive/p/d2x-cios/downloads](url)
this link will take you to the d2x cios download page.
install the latest alt version one for vwii or wii (whichever you have obv.)
use d2x cios installer to install the cios:
base 56 in slot 249
base 57 in slot 250
[https://sites.google.com/site/completesg/backup-launchers/installation](url)
here is a guide to install the cios just in case
hope this helps

**Comment by BillDStrong** [comment]
There is a Seagate utility that allows you to set the drive to stop sleeping. This is a common issue with them.

**Comment by Kwakers01** [comment]
If you need to check quickly you can use windows "Computer Management" (run as administrator) and click on Disk Management.  To change things you many need to use the MiniTool Partition Wizard Free or other progem for disk partitioning.
