### ISSUE TITLE
(help) Nintendont cant recognize ANY usb controller

### ISSUE THREAD

**Issue by Siriustic** [FIX94/Nintendont#862]
Hello everyone!
 I have a problem that have been killing myself for days, and I can't solve it at all.
  I have a Nintendo Wii U with Haxchi, which works perfectly with any game.  The problem is that I'm not able to recognize ANY controller in the App “Hid to vpad”.  Consequently, I am unable to use my gamecube controller for games of any platform.  I also can't use any controller on the Nintendont App via vWii.  When using the Nintendont / USBloader Gx, the game screen opens normally, but does not recognize the USB controls, so I’m unable to play gamecube games.
  So far, the only thing I've been able to use is the gamecube controller in Super Smash Bros U, because according to the company, the SSBU is allowed to recognize the gamecube controller. This is possible using a Gamecube controller adapter for Wii U.
  I have the most updated versions of Hid for Vpad and nintendont, and I am also sure that the USB ports are working, because I’ve been using them on SSBU.
  Any necessary information, ask me.
  Please help me ... I'm going crazy.

**Comment by carnage702** [comment]
what usb controller do you have? you forgot to say the most important bit lol
