### ISSUE TITLE
Automation to assist in Updates

### ISSUE THREAD

**Issue by Dr-Crow** [FIX94/Nintendont#870]
Currently the process for issuing a new release is very manual. After code is published, someone needs to compile the `loader.dol` and then replace the currently `loader.dol`. Additionally, we should also be updating the `controllers.zip` each time there is an update to the controllers ini files. Currently, the `controllers.zip` file has not been updated in 4 years. But controller support has been growing. 

Both these files need to be compile/made and then upload any time we want to produce a release. 

My proposal is to move away from manually update the files and move to a more automated process.

We can use tools like Travis CI or Github actions to do the builds of the `loader.dol` and the processing of the `controllers.zip`. Having a more automated approach to releases could allow for a faster response to bugs.

@carnage702 I am happy with coming up with a PR if you are interested in adding this to the repo.

**Comment by guitaristtom** [comment]
It has always confused me about why "Releases" has never been used, but instead having the `loader.dol` in the `loader` folder getting updated...

It's a tad bit annoying for when you have the repo watched through Github here. Either everything gives a notification or just releases...

**Comment by guitaristtom** [comment]
Why was this closed? 

There was no response given from the devs at all.
