### ISSUE TITLE
Third party Wii U Pro Controller crashes Nintendon't

### ISSUE THREAD

**Issue by GeertBoer** [FIX94/Nintendont#872]
Big issue since new first party Nintendo Wii U Pro Controllers aren't available for purchase anymore

**Comment by carnage702** [comment]
well my fake one actually works, sometimes controllers do all sort of signals and third party/fake ones arent recomended with any homebrew in general and not just nintendont, my fake wiimote even crashes homebrew channel itself so yeah.
