### ISSUE TITLE
Nintendont stucks at Loading IOS58 Kernel

### ISSUE THREAD

**Issue by ghost** [FIX94/Nintendont#874]
Hello everyone so I installed Nintendont on my Wii in Feb and I got the Message after the start so I waited a Month and tried it again and still it stucked at Loading IOS58 Kernel I have an Transcend 4gb SDHC Card and a SanDisk USB 3.0 USB Drive both are formatted in FAT32 standard size there is no GameCube Memory Card or GameCube Controller inside I installed IOS 58 also the old Version of IOS58 but still I have no clue what to do I hope that there is a Solution soon as possible and also there is no ninconfig.bin and there is no save  :/

**Comment by carnage702** [comment]
nintendont to wprok just uses the official ios58 by nintendo so if you have an old ios58 or a cios in place of it it wont work.

Also need an homebrew channel that is ios58 base, some old homebrew channels are not based on ios 58 you can check the top corner of homebrew channel by pressing + or 1 or something and it will say what version your homebrew channel is.

**Comment by NeunMuenze92001** [comment]
my Homebrew Version is 24.12 and I installed the newest IOS58

**Comment by NeunMuenze92001** [comment]
can I get a IOS58? is it a Problem with the SD Card? https://www.amazon.de/Transcend-Class-Speed-Memory-TS4GSDHC4/dp/B003QJV2IG?th=1

**Comment by Special-Niewbie** [comment]
@NeunMuenze92001  Hi friend, are you placed the meta.xml into the Nintendont folder? Or just the boot.dol....

**Comment by NeunMuenze92001** [comment]
replacing what? I got Nintendont from https://wiidatabase.de my Discord is !NeunMuenze92001!#5165

**Comment by Special-Niewbie** [comment]
The unique time that you could have this problem related to IOS58, it's:

1) If you don't place the meta.xml file into the folder. 

2) As @carnage702 said you have wrong IOS version (that you can simply check it, if you press the Home button when you are on the Homebrew Menu Channel)

Try to download all the Nintendont files from here, instead of external sites.......

**Comment by NeunMuenze92001** [comment]
still it stucks at the same Message can I get a Guide to uninstall my IOS 58?

**Comment by NeunMuenze92001** [comment]
Here is my Syscheck https://pastebin.com/rY7bASbc

**Comment by NeunMuenze92001** [comment]
Here is my Syscheck https://pastebin.com/fEtBaXwA

**Comment by carnage702** [comment]
take a picture of where nintendont is getting stuck if you can.

**Comment by NeunMuenze92001** [comment]
https://i.redd.it/ymgqlp5zbs811.jpg

**Comment by carnage702** [comment]
> 
> 
> https://i.redd.it/ymgqlp5zbs811.jpg

your nintendont is very outdated, first update to 492 and second take a picture oif your nintendont folder inside the apps folder, just want to see what is there.

**Comment by NeunMuenze92001** [comment]
actually I took that from Google I have the newest version and there is meta.xml boot.dol and icon.png that's all

**Comment by carnage702** [comment]
> 
> 
> actually I took that from Google I have the newest version and there is meta.xml boot.dol and icon.png that's all

try taking a picture of yours then it doesnt hurt ...

**Comment by EvtL44** [comment]
> nintendont to wprok just uses the official ios58 by nintendo so if you have an old ios58 or a cios in place of it it wont work.
> 
> Also need an homebrew channel that is ios58 base, some old homebrew channels are not based on ios 58 you can check the top corner of homebrew channel by pressing + or 1 or something and it will say what version your homebrew channel is.

![20220114_173008](https://user-images.githubusercontent.com/97769316/149601325-ec18afc7-46f5-44f9-b95c-53ad1f74985f.jpg)

I've had a very similar issue, it started when I updated Nintendont, so it has to be that something is outdated like you say. But how would I go about finding a fix? I've researched and experimented for hours to fix it and even went back to a different version of Nintendont but that made it to where it only loaded the background image.

**Comment by carnage702** [comment]
> 

Try deleting your ninconfig.bin  and try again, ninconfig is on the root of your SD or usb

**Comment by EvtL44** [comment]
No, luck same screen...
i tried an older version but that had a different problem because Nintedont would boot up with only the background.

**Comment by carnage702** [comment]
> No luck, same screen... i tried an older version but that had a different problem because Nintedont would boot up with only the background.

And you have the meta.xml in the apps folder alongside the boot.dol?

And your homebrew channel is ios58 based?

Do you use SD or usb, might be your device getting too fragmented so maybe try another one.or reformat the one you have.

**Comment by EvtL44** [comment]
SD card (FAT32), Homebrew on IOS58 v24.32, I'll try putting only Apps/Nintendont on a USB that's newly formatted to FAT32

![20220114_211513](https://user-images.githubusercontent.com/97769316/149608477-338828d1-7980-4f4d-974d-fa2429ca9043.jpg)

**Comment by EvtL44** [comment]
Same problem on fresh USB

**Comment by carnage702** [comment]
> Same problem on fresh USB
> 
> I reformated my SD card and copied the exact files back. It came up with the same screen again. Blank background happens with older versions too, if done again.

no idea maybe your ios58 is damaged or something, or your wii is dying and its s to fail. do you have any themes installed? did you tryed starting games with memory card emulation turned off? does your wii have gc ports?

**Comment by EvtL44** [comment]
I don't have any themes, and i tried lunching nintendont through USB loader GX and switching the memory card emulation and both had the same results. Yes my wii does have Game Cube Ports. I did go through the GC memory manager and I didn't know what I was doing backing up and restoring files till I got to the one I wanted but that shouldn't mess with IOS58. Is this something I could go to Wii mod lite and install a new IOS58?

**Comment by carnage702** [comment]
> I don't have any themes, and i tried lunching nintendont through USB loader GX and switching the memory card emulation and both had the same results. Yes my wii does have Game Cube Ports. I did go through the GC memory manager and I didn't know what I was doing backing up and restoring files till I got to the one I wanted but that shouldn't mess with IOS58. Is this something I could go to Wii mod lite and install a new IOS58?

gc memory manager only messes with gc memory card slots and not with any ios, maybe try taking everything from memory card slots and everything from the gc ports and even usb ports and then try nintendont.

if that doesnt work i cant help you since if nintendont cant retrieve the ios58 from your console something is off for sure, you might need to open a thread on gbatemp and ask how to restore or reinstall a legit ios58 on top of yours.

**Comment by EvtL44** [comment]
I took out 2 memory cards, the only gc controller plugged in and the USB ports are empty, something different happed... It said "checking storage devices for about 10 seconds then loaded into the proper SD or USB selection, it can even load the only game put on their too. So it was the GC memory cards?

**Comment by EvtL44** [comment]
So if I load nintendont, it says "loading IOS58 Kernel" then I take out my slot for memory card B, then it will go through to the SD card then put the memory card back, it will load the save files for the games later.... that's.. very strange but at least it's progress, thank you so much

**Comment by carnage702** [comment]
> 

yeah you cant have a slot b inserted when starting nintendont because that was what fix94 used for debugging nintendont so it checks for debugging software on slot b, slob can only be used after a game has started.
