### ISSUE TITLE
GC save games gone (after changing video settings?)

### ISSUE THREAD

**Issue by Gul3** [FIX94/Nintendont#875]
So two days in a row now my GC save games via Memory Card Emulation have corrupted/vanished - and a bit sad, 40h+ on PSO, which I restared yesterday and played 10h+ straight to recreate the char, only to be corrupted/gone when I boot up again today.

So I try explain the order of things, so maybe some experts can figure something out of it. 

1. I play on PAL Wii. Until yesterday I used composite video on my Bang & Olufsen CRT. Everything have been working stable for long, until i swapped this cable.
2. Yesterday I got my PAL RGB Scart from retrogamingcables.co.uk (they have different ones for NTSC and PAL for some technichal reason).
3. Initially after swapping the cable, it resultetd in a wrong image, all red and black. 
4. I changed the Video Settings a couple of times in Nintendont, where I got the normal with Force (Deflicker) Video Mode, and PAL60 (I'm running NTSC games, but with forced PAL60. I suspect this might confuse the "Gamecube")
5. Loading games back up - and get message that savegame is corrupted in PSO. In other games they are just gone. 
6. I notice the video settings is not saved, so after a reboot I have to manually set them again. So when I did that today, the same story: GC save games corrupted/gone

So, I have a hunch that its about NTSC game with forced (deflicker option) PAL60. However Im not sure because I also find it strange Nintendont dont save the new settings, like before. Or anyone else have some pointers for me? I was super happy to be able to play PSO again (thanks to BBA Emulation), but now I'm too scared to start up again. Is this due to the new cable and video settings, or some other bug? 

I use version 6.490 (Wii)

**Comment by carnage702** [comment]
sometimes depending on several issues the ninconfig.bin can become corrupt and then affect other stuff so i would advise
 first update to 492
second delete your ninconfig.bin or any controller.ini on the root of your devices(might become corrupt too)
third go to your save folder and any 0kb file just delete it.
4 start nintendont, press b or 1 to go to settings, choose your settings, then press b again and start a game, if you dont start a game before exiting nintendont your settings wont be saved.

**Comment by Gul3** [comment]
Thank you for the feedback. I will try this. However, it gets me a bit uneasy on the stability. I tried to update through Nintendont itself, but after maybe 10 mins, it still said same version. Allmost like theres some read-only thingy going on, but I ensured the SD card is in the correct position (cant start games when its the wrong position apparently). 

PSO is a game people put hundreds of hours into. Would it be safer to use original Memory cards? Corrupted data is nail in the coffin for those type of games

**Comment by carnage702** [comment]
> 
> 
> Thank you for the feedback. I will try this. However, it gets me a bit uneasy on the stability. I tried to update through Nintendont itself, but after maybe 10 mins, it still said same version. Allmost like theres some read-only thingy going on, but I ensured the SD card is in the correct position (cant start games when its the wrong position apparently).
> 
> PSO is a game people put hundreds of hours into. Would it be safer to use original Memory cards? Corrupted data is nail in the coffin for those type of games

well i never corrupted a save at all and maybe you can save your save file by getting the raw file(if you havent formated it yet that is) and using dolphin on pc using the gc memory card manager they have.

well using original memroy card would be better for sure but like i said i did hundreds of hours and hundreds of games on nintendont and never lost a save so maybe it was your sd card/usb that was slow or some really low low % chance of many events that culminated on that who knows, also nintendont updater is broken for a long time update by hand its the way.
