### ISSUE TITLE
initializing virtual 251-block memory card

### ISSUE THREAD

**Issue by ImMock** [FIX94/Nintendont#876]
Im new in all of this and im getting this error, im using Nintendont on Wii SD and storing the games on the USB and trying to play them with USB Loader GX but it never passes from "initializing virtual 251-block memory card" and the options online to change the blocks are not working currently for me, any suggestions or any more information i can give?

**Comment by carnage702** [comment]
is your sd card unlocked? there is the side flip to unlock/lock  
if your isos are on sd card maybe its too slow or its too full or too fragmented.

what speed and class is your sd card? and its full?

also go to your saves folder and delete any 0kb file in there since they are corrupt files.
