### ISSUE TITLE
[Request] add  LAN support for F-Zero AX

### ISSUE THREAD

**Issue by megashockneo** [FIX94/Nintendont#877]
hi i was wondering if it's possible to have f-zero ax take advantage of the BBA feature and link up other systems for multiplayer like on the original triforce hardware.

**Comment by carnage702** [comment]
triforce systems didnt use any of the bba codding, they had a totally different codding altogether and wires, also triforce was done by crediar who bought an arcade machine to decode so no one ever decoded the multiplayer functions so there is nothing to add, unless someone buys 2 arcade machines and documents its entire code while connected there isnt a way to do that.

**Comment by NewGBAXL** [comment]
I'm assuming the reversing was done with the DVD "Media Board" hardware commands, as opposed to the Triforce SDK. When the Triforce SDK is properly reversed the network commands could be more straightforwardly integrated with the existing network code.
This would also allow for proper support for the "namcam" as well.
No Triforce games have been decompiled yet or ship with debugging symbols, so the actual API is still largely untapped.
