### ISSUE TITLE
'Patch Pal50' setting doesn't work with Metroid Prime 2

### ISSUE THREAD

**Issue by Schweini07** [FIX94/Nintendont#882]
Hello everyone!

I recently bought myself the PAL version of Metroid Prime 2, just to find out that it only supports 60hz monitors and tvs. Sadly my two monitors both don't support 60hz, so I had the hope that the 'Patch Pal50' setting would help. It didn't.

I hope this can be looked into, I was really looking forward to playing this game.

If any additional data, like debug logs or system info is needed, please tell me.

**Comment by carnage702** [comment]
did you try to force videomode to pal 50? the patch pal50 option is just to force 50hz into 60hz and not the other way around most of the time.

try force videomode to pal50 and patch pal 50 off and then try force videomode to pal50 and path pal 50 on.

Its very hard to downforce  a patch, if the game was never meant to run at 50hz  it could maybe not work at all if downforced but try what i said abode.

**Comment by Schweini07** [comment]
That didn't work, but I think there is another reason why not.

I use 2 adapters to get the picture and sound to a VGA input:

https://www.amazon.de/gp/product/B01GFMW91E/ref=ppx_yo_dt_b_search_asin_image?ie=UTF8&psc=1
https://www.amazon.de/gp/product/B07SS9RKX1/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

Could it be that one of the adapters - probably the AV one - just doesn't support PAL60?

**Comment by Schweini07** [comment]
```
xrandr
Screen 0: minimum 8 x 8, current 3600 x 1080, maximum 32767 x 32767
DP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 510mm x 290mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1400x1050     59.98  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      59.89  
   1280x800      59.81  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.03    60.00  
   832x624       74.55  
   800x600       75.00    60.32    56.25  
   640x480       75.00    59.94  
   720x400       70.08  
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 connected 1680x1050+1920+0 (normal left inverted right x axis y axis) 470mm x 300mm
   1680x1050     59.97*+
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

My monitors also seem to support 60hz, so it must be about the adapters(?)!

**Comment by carnage702** [comment]
> 
> 
> ```
> xrandr
> Screen 0: minimum 8 x 8, current 3600 x 1080, maximum 32767 x 32767
> DP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 510mm x 290mm
>    1920x1080     60.00*+
>    1680x1050     59.95  
>    1400x1050     59.98  
>    1600x900      60.00  
>    1280x1024     75.02    60.02  
>    1440x900      59.89  
>    1280x800      59.81  
>    1152x864      75.00  
>    1280x720      60.00  
>    1024x768      75.03    60.00  
>    832x624       74.55  
>    800x600       75.00    60.32    56.25  
>    640x480       75.00    59.94  
>    720x400       70.08  
> DP2 disconnected (normal left inverted right x axis y axis)
> HDMI1 connected 1680x1050+1920+0 (normal left inverted right x axis y axis) 470mm x 300mm
>    1680x1050     59.97*+
>    1280x1024     75.02    60.02  
>    1440x900      59.90  
>    1280x960      60.00  
>    1280x800      59.91  
>    1152x864      75.00  
>    1280x720      60.00  
>    1024x768      75.03    70.07    60.00  
>    832x624       74.55  
>    800x600       72.19    75.00    60.32    56.25  
>    640x480       75.00    72.81    66.67    59.94  
>    720x400       70.08  
> HDMI2 disconnected (normal left inverted right x axis y axis)
> VIRTUAL1 disconnected (normal left inverted right x axis y axis)
> ```
> 
> My monitors also seem to support 60hz, so it must be about the adapters(?)!

probably since unless you have a tv from 30 years ago it should support pal60, preety much every monitor always supported 60hz since pcs werent pal they were kst pc and monitors.

also your monitors support up until 1024 so for sure they support pal60...

**Comment by carnage702** [comment]
also are you sure the game is running? and not just a bad iso or bad forced settings and you are just getting black screen and think its the unsuported image? take a picture of your nintendont settings if you can.

**Comment by Schweini07** [comment]
The game is definitely running. Just very distorted. My Adapter also seems to use NTSC443 as a video mode during the game. Normally it's PAL tough. 

![IMG_20210329_183641.jpg](https://user-images.githubusercontent.com/47503977/112870055-170f5980-90be-11eb-96db-ba3b224f610d.jpg)
![IMG_20210329_183553.jpg](https://user-images.githubusercontent.com/47503977/112869849-e3ccca80-90bd-11eb-8c9e-0fdceaa963b1.jpg)
![IMG_20210329_183442.jpg](https://user-images.githubusercontent.com/47503977/112869869-e92a1500-90bd-11eb-9d36-146192565f02.jpg)

**Comment by carnage702** [comment]
that is the distortions of turning pal signal running on ntsc only tv/monitor, so something is mixing up your adapter like he thinks the game is ntsc did you just tryed to force ntsc videomode on the pal game, might just work lol.

**Comment by Schweini07** [comment]
Forcing NTSC results in a black screen and I have to do a hard reset on my Wii.

**Comment by Schweini07** [comment]
But my Adapter tells me during the boot of the game:
```
AV
NTSC
```

So it's detecting NTSC

**Comment by carnage702** [comment]
> 
> 
> But my Adapter tells me during the boot of the game:
> 
> ```
> AV
> NTSC
> ```
> 
> So it's detecting NTSC

no idea  for some reason your adaptors are confusing your monitors, tryed forcing pal 60? mpal?

**Comment by Schweini07** [comment]
Pal60 just results in the distorted picture. And M-PAL gives first a black screen and then no signal.

> no idea for some reason your adaptors are confusing your monitors, tryed forcing pal 60? mpal?

What do youe mean with that? Isn't it good that it used NTSC when I forced it?

**Comment by Schweini07** [comment]
I think I'll buy myself a new adapter, as I am pretty sure that this is not the fault of Nintendon't.
I'll update in a few days if the new one worked.
