### ISSUE TITLE
Melee freezes when ever I pass the trophies n the main menu and 20XX the Wii u gamepad (I use a forward to use the gamepad it may be that but it only does this with 20XX) a few buttons are not mapped correctly (it freezes on that to sometimes.)

### ISSUE THREAD

**Issue by Zacky371** [FIX94/Nintendont#885]

**Comment by Zacky371** [comment]
I may use a vary old vertion of nintendont but idk im grounded right now so may take a bit to figer out

**Comment by carnage702** [comment]
hacks and nintendont dont go very hell since nintendont has some hardcoded stuff that hacks might not respect, there is no guarantee of any hack working its a gamble, regular ssbm works then its the hack issue, also latest nintendont is 499.
