### ISSUE TITLE
"ds4pair_wii" compatability?

### ISSUE THREAD

**Issue by su6ur6an** [FIX94/Nintendont#886]
ds4 bluetooth compatability to nintendont via xerpi lib?

https://github.com/xerpi/ds4pair_wii
https://github.com/xerpi/libds4wiibt
https://github.com/xerpi/ds4wiibt-test
https://github.com/xerpi/ds4wii_gyro_test

**Comment by xtal44** [comment]
In the past (around 2018) I was able to use the official Sony DS4 USB adapter for PC with Nintendont. Doesn't work with Dualsense (and I don't have my PS4 any longer), so I can't check whether the new versions support it.
