### ISSUE TITLE
Can someone please help me work a third party GC adapter with nintendont

### ISSUE THREAD

**Issue by Estus23** [FIX94/Nintendont#889]
I bought a third party GameCube controller adapter from Amazon and can't figure out how to make it work with nintendont.

I'd appreciate it if anyone can help me out.

NINTENDONT Version 6.489
USB Loader GX Version 3.0 r1271

GC Adapter: CLOUDREAM
Model #: HS-WU025
Switch for PC and Switch/Wii U: YES
Data plugged into back bottom slot (1?), rumble plugged into separate powered USB hub plugged into wall outlet.

I have official oem Wavebirds and wired GC controllers plugged into the GC adapter.

HDD: Seagate OneTouch 2TB
P/N: 3BDAPD-500
S/N: NABL9RAC
Main plugged into back top slot (0?), extra power (Y-cable) plugged into same seperate USB hub GC adapter rumble is plugged into.

Added the controller folder filled with .ini files (from online, not from NINTENDONT directly) into the root of my HDD, GX, and NINTENDONT folder in a desperate attempt at making things work.

![IMG_20210423_091151](https://user-images.githubusercontent.com/83097330/115934479-15d41100-a45f-11eb-800d-06761c22bf4a.jpg)

**Comment by cesarmades** [comment]
If your controller doesn't work with the default set of .ini files included you'll have to create your own.

**Comment by MrCapone** [comment]
@Estus23 what vid/pid of your controller when in Wii U/NS mode? If 057e/0337 then its maybe same as mine and #900 here.
