### ISSUE TITLE
Crashing on Custom Robo

### ISSUE THREAD

**Issue by Decolico** [FIX94/Nintendont#896]
Just hacked my wii last night. Haven't had a problem with any other game. Launched Custom Robo, shows me the company logos at the beginning, shows that it created a save file on emulated memory card, then nothing appears afterwards. Thought it might be a bad iso, so downloaded another one, same thing. I am running it off an SD card so that MIGHT be the issue, just wanted to get more information.

**Comment by carnage702** [comment]
take a picture of your nintendont settings

**Comment by Decolico** [comment]
![IMG_20210526_070308544](https://user-images.githubusercontent.com/21351515/119649286-7654c600-bdf0-11eb-9521-7d6ff32b545f.jpg)
Only thing i changed was Memcard, haven't touched anything else.

**Comment by carnage702** [comment]
> 
> 
> ![IMG_20210526_070308544](https://user-images.githubusercontent.com/21351515/119649286-7654c600-bdf0-11eb-9521-7d6ff32b545f.jpg)
> Only thing i changed was Memcard, haven't touched anything else.

just check your iso md5 
https://www.mediafire.com/file/5y3tfpoil433rij/MD5_SHA-1_Utility.exe/file

open your iso on this tool from your sd or usb whatever you use and post the md5 here.

**Comment by Decolico** [comment]
MD5: 0F58271AEDC7FF1AC66688AD02921424
unfortunately, don't know many sites that legitimately work, if this is a bad Iso

**Comment by carnage702** [comment]
> 
> 
> MD5: 0F58271AEDC7FF1AC66688AD02921424
> unfortunately, don't know many sites that legitimately work, if this is a bad Iso

that is not a good iso a
 good ntsc usa md5 is 
546e5108173bceb4d5c8ca27b3fcfc96
jap
6c74f607554a4d991e0a783b14d8b232

but just make sure you dont have any 0kb files in your saves folder anyway

**Comment by Decolico** [comment]
So essentially look for a new ISO? Darn, ok. Thanks!
