### ISSUE TITLE
Support Wii remote by itself as a controller?

### ISSUE THREAD

**Issue by NintendoManiac64** [FIX94/Nintendont#899]
I know that years ago (something like 4 years ago?) it was stated that a Wii remote by itself would never be supported, but this was also back when it was stated that things like the wired Xbox 360 would never be supported which clearly isn't true anymore (see: https://github.com/FIX94/Nintendont/issues/804).

Nevertheless, we all know that the dpad on the OEM GameCube controller is... not great, and USB HID controllers like the dualshock 4 are only supported for 1 player.

Now normally the ideal solution would be to use a classic controller, but availability of those is lacking nowadays, especially if you're trying to set up a multiplayer gaming session (immense demand for the Super NES classic probably didn't help), and the few games that are d-pad heavy such as Nintendo Puzzle Collection (which itself is also a Japan-only game, so it's all the more likely to be ran via something like Nintendont - especially when using an fan-made English translation) could easily work with nothing more than a sideways Wii remote.

Also for reference, Puyo Pop Fever as well as Bust-A-Move 3000 (the PAL version was called "Super Bust-A-Move All-Stars") are two other games in addition to Nintendo Puzzle Collection that are very dpad-heavy yet have minimal button requirements quanity-wise, making them additional good examples of where using only a sideways Wii remote makes sense.

My personal ideal button configuration would be the following (Wii on left, GC on right):
A = R
B = L
1 = B
2 = A
plus = Start
minus = Y
Dpad with remote held sideways = Dpad with controller held normally

**Comment by carnage702** [comment]
Lots of people start nintendont with a wiimote and if the wiimote has no extension attached he will turn off, if this was added everyone would just get wiimote stuck as a player slot and it would not shut off automatically, and like you said for like 2 games why added this ? seems like a waste of everything, nintendont is compatible will all hid controllers which you can get and have great dpads, also is compatible with wiiu pro controller even on regular wii and wiiurpo has a great dpad and its not that hard to find used official classic controllers anyway.

So in the end this would be a nuisance to 99% of the people playing 99% of the games becuase wiimote would not turn off and take a controller slot automaticaly every time someone started nintendont with the wiimote.

**Comment by NintendoManiac64** [comment]
> Lots of people start nintendont with a wiimote and if the wiimote has no extension attached he will turn off, if this was added everyone would just get wiimote stuck as a player slot and it would not shut off automatically.

I'm confused - how is this any different from how wii remotes behave in a commercial Wii game that supports multiple control configurations, like Mario Kart Wii?

**Comment by carnage702** [comment]
> 
> 
> > Lots of people start nintendont with a wiimote and if the wiimote has no extension attached he will turn off, if this was added everyone would just get wiimote stuck as a player slot and it would not shut off automatically.
> 
> I'm confused - how is this any different from how Wii remotes behave in commercial Wii games that supports multiple control configurations, like Mario Kart Wii?
> 
> (forgive my ignorance here, but 99% of the time I've historically used Devolution due to its ability to use a wired Xbox 360 controller and a USB hard drive at the same time, so I'm not super-savvy on how Nintendont behaves)

the diference is wiigames that have solo wiimote support are coded for it and the controlls are good and set, if a game does not support solo wiimote, wiimote error appears saying you will need a classic controller or nunchuk.

no gc game was made to be supported with half of the buttons like wiigames have and nintendont automaticaly shut off if no CC/nunchuck is inserted.so people dont waste battery without needing too.

**Comment by NintendoManiac64** [comment]
>  no gc game was made to be supported with half of the buttons like wiigames have

...I'm probably being _super_ pedantic here considering it's one game, but Nintendo Puzzle Collection actually supports the use of the Game Boy Advance as a controller with no functionality lost compared to GameCube controllers, and the GBA has exactly the same amount of buttons as the Wii remote if you don't count the power and home buttons.

Nevertheless, I understand your point but I couldn't help but point out that it's _technically_ not all...

(it's a bit unfortunate that Nintendo Puzzle Collection is literally the only game with local 4-player Panel de Pon/Tetris Attack/Puzzle League)

**Comment by carnage702** [comment]
> 
> 
> > no gc game was made to be supported with half of the buttons like wiigames have
> 
> ...I'm probably being _super_ pedantic here considering it's one game, but Nintendo Puzzle Collection actually supports the use of the Game Boy Advance as a controller with no functionality lost compared to GameCube controllers, and the GBA has exactly the same amount of buttons as the Wii remote if you don't count the power and home buttons.
> 
> Nevertheless, I understand your point and will not press the issue farther - this comment was purely because couldn't help notice that it's _technically_ not completely "no games"...
> 
> (it's a bit unfortunate that Nintendo Puzzle Collection is literally the only game ever made across any console with local 4-way multiplayer for Panel de Pon/Tetris Attack/Puzzle League, and I think the same may be true for Yoshi's Cookie as well)

if that works you can do it it is supported if you have a wii with gc ports just use your gba and gba link cable and turn native on and play it.

i never said no games work with few controls, i said **99% of them**, there are more games that could work mostly games from midway arcade classics and such but its such a tiny pool that its ridiculous to make a feature that would affect everyone and the wiimote wouldnt turn off by itself so that 2 or 3 people could play 4 or 5 games with solo wiimote...

nintendont is open source so you can code it for yourself or find someone  to do it for you and make a fork, same way why xbox360 controller isnt on the main fork since it takes over hid even on that guys fork i wouldnt trade hid over xinputt anyday on main fork.

Also wiimote dpad sucks big time, if you love dpads that much yopu cant say wiimote is ever decent... seriously classic controller has a dpad 10 times better same for wiiupro controller. no self respecting person would ever say if they had a choice to play a game with a dpad they would choose solo wiimote dpad over CC imo.

**Comment by NintendoManiac64** [comment]
> same way why xbox360 controller isnt on the main fork since it takes over hid even on that guys fork

This really makes me wonder then what sort of voodoo tueidj did to get Devolution to support both hid _and_ xinput USB controllers... But alas, its copyright protection makes it impossible to use a fan-made English translation for Nintendo Puzzle Collection.

**Comment by ildar** [comment]
> Lots of people start nintendont with a wiimote and if the wiimote has no extension attached he will turn off, if this was added everyone would just get wiimote stuck as a player slot and it would not shut off automatically.

It would be very nice to have this big warning in the README: You NEED CC/nunchuck for nintendont to work.
Otherwise it's very hard to guess for a newcomer.
