### ISSUE TITLE
057e 0337 controller adapter unrecognized

### ISSUE THREAD

**Issue by Redbyte1** [FIX94/Nintendont#900]
The ClouDream Adapter (likely just clone of official?) doesn't do anything even with HID_Test. How is it that it can work fine on PC, Switch, and SSBWU but fails to work with Nintendont. Doesn't help that the Wii U version's updating abilities crash so you cannot use Nintendont to download controller.zip. I've tried every combination of controller.ini and SD:/controllers/ with no luck. Tried turning off gamepad, formatting vWii and starting over, launching SSBWU into Nintendont (pull comment said only launching a game that supported it then launching Nintendont worked), tried a Wii Ware game that supports GC in the same fashion, front and back USBs, loading from USB and SD. Any idea how to fix? This is one of the most popular adapters available.

**Comment by carnage702** [comment]
first off no wii or wiiware or wiivc games or wii homebrew apps wil recognize any gc controller connected through any usb adapter(even original one) to be read as a gc controller, that is just an hid device usb controller and noone of the apps or games has any support for it only smash wiiu officially so dont expect to work on anything other than smash4 itself.

your adapter is not the official or any of the other ones in the database which means it has its own vid/(pid and its own bits to be coded in, you would have to do the controller.ini from scratch for your adapter,  i dont know how to make controller.inis so no idea, you need to go and find how to do it yourself, nintendont only supports devices whose people aready made files for them and no one made for that brand/model so no wonder it doesnt work.

even the original gc adapter only works on nintendont and ssb4 and it will not work on anything else, nintendo doesnt accept the wii games to see wiiugc adapter as a gc controller in wii mode at all so no compat, it only works on nintendont becuase nintendont supports hid devices  and tis an hid device.

**Comment by MrCapone** [comment]
@carnage702 vid/pid is the same as official WUP-082. But it refuse to work. Maybe if i can debug nintendont somehow i will found what wrong. But i only have Wii U and afaik there is no debugger for vWii.
