### ISSUE TITLE
Nintendont Greenscreening 

### ISSUE THREAD

**Issue by spectrum9625** [FIX94/Nintendont#901]
Every time I attempt to load into Nintendont, it would say "Returning to Loader" and put me back into the homebrew channel. I then tried updating Nintendont to the latest version however, my gamecube controller did not work and every time I attempted to use the Dpad to select a game, it put me into settings, with no other buttons (minus the Dpad) working. 
After a while, Nintendont is now greenscreening. Whenever I attempt to play gamecube games on USB Loader GX, it brings me to the Wii menu.
I never had this problem for the 5 years that I modded my Wii and am unsure of what to do. Any help will be appreciated, thank you.

**Comment by carnage702** [comment]
probably corrupted files.

1- delete your boot.dol
2-delete your ninconfig.bin and controller.ini on the root of the sd card
3-redownload the dol again and try it.
