### ISSUE TITLE
Super Monkey Ball 2 (NTSC) - loading game saves on PAL console crashes the system when forced to PAL60 or 50

### ISSUE THREAD

**Issue by Daddu3** [FIX94/Nintendont#904]
Noticed this for some while now but NTSC-versions of SMB2 can't load game saves when forced to PAL-video modes - the saves load fine under NTSC-video, though I can't use that due having red tint all over it when plugged with RGB SCART.

Wonder if there's anyway to make a fix for this?

**Comment by carnage702** [comment]
> 
> 
> Noticed this for some while now but NTSC-versions of SMB2 can't load game saves when forced to PAL-video modes - the saves load fine under NTSC-video, though I can't use that due having red tint all over it when plugged with RGB SCART.
> 
> Wonder if there's anyway to make a fix for this?

forced videomodes are an hack they dont work for every game.

why dont you play the pal version of super monkey ball 2? it does exist no need to force pal videomodes on ntsc version...
