### ISSUE TITLE
[Question] How do I exit Nintendont?

### ISSUE THREAD

**Issue by Eddie-Hartman** [FIX94/Nintendont#905]
I'd like to exit nintendont to switch games while using a gamecube controller.
Original wii with Native Control on. I'm seeing some mixed information on if this is possible or not on the web.

I have native control on which I believe is mandatory on the original wii in order to play gamecube games with the gamecube controller. Using the button combo (R + Z + B + D-Pad down) does not exit for me. Pressing home on the wii remote does not exit. Power button on wii remote does nothing.
I've seen that this may be due to having native control turned on, but if I turn it off I can't play games with the gamecube controller (the controller doesn't actually do anything in game).
Is there anything that I can do about this?

**Comment by carnage702** [comment]
having native turn on disables all exit combos due to nintendont not emulation controllers and just letting the wii native code control them.

if your controller does not work without native turned on im guessing its a fake/3rd party/refurbished gc controller? if so its normal it wont work unless you have native on, if it was an official controller it would work without native and you would get the exit combo working.

**Comment by Eddie-Hartman** [comment]
I was trying with the official smash controller for the switch that nintendo sold.
This one: https://www.amazon.com/gp/product/B07DJX3Y47/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
I will try again with my original gamecube controller that came with my console.

**Comment by carnage702** [comment]
> 
> 
> I was trying with the official smash controller for the switch that nintendo sold.
> This one: https://www.amazon.com/gp/product/B07DJX3Y47/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
> I will try again with my original gamecube controller that came with my console.
> 
> EDIT: I tried with my original gamecube controller and it did the same thing. When I turn native off, no button inputs are registered. Are there any other settings that I should be changing?

take a picture of your nintendont settings just making sure what you have.

**Comment by Eddie-Hartman** [comment]
@carnage702 Sure! Thanks for your patience working with me on this. Here are my settings. If there are any dumb ones that I should change let me know. I did look at the summaries for each of them, but didn't see anything in particular that stood out to me. I initally set this up a couple years ago to play 20xx and have recently expanded to playing other games. The particular problem is playing games like Ocarina of Time where I want to explore some bugs and things that require frequent resets, but don't want to go across the room. Or simply for switching games or turning the wii off.
Note: This is with native control off because I was trying with the original gamecube controller, but again this doesn't work.
![image](https://user-images.githubusercontent.com/14089997/122692020-c01ea980-d200-11eb-881e-a615a7552596.png)

**Comment by carnage702** [comment]
You got maxipads set to zero that's why it won't work... Just put it at 4.
Unlock read speed being on can cause issues in certain games too just saying if you ever see issues turn it off

**Comment by Eddie-Hartman** [comment]
@carnage702 Worked perfectly. Thank you!
