### ISSUE TITLE
Something Nintendont needs

### ISSUE THREAD

**Issue by RazorVermillion** [FIX94/Nintendont#910]
I really enjoy this emulator and it's one of my favorites of all time but there's only one feature it needs.

A very useful feature is to have a second memory card emulation.

Memory Card A folder should be like called "memory1" for the first slot.

Memory Card B folder should be like called "memory2" for the second folder.

The reason this would be useful because there are some games that require to only use a one whole memory card such as the sims 2 per game mode that can only be stored onto one memory card slot and can't change game modes even after selection without risking to delete a save file to change game modes.

**Comment by GerbilSoft** [comment]
There *is* support for two memory cards, but it isn't well documented.

You need to have a pre-made memory card image for slot B. Both slot A and B must not be larger than 16 MB total. (I'd recommend 2 MB [251 blocks] or smaller for both.)

If using "multi" (multiple games per card):
* Slot A: ninmem.raw / ninmemj.raw
* Slot B: ninmemb.raw / ninmemjb.raw

If not using "multi" (one game per card):
* Slot A: GAFE01.raw
* Slot B: GAFE01B.raw

where "GAFE01" is the ID6.

**Comment by RazorVermillion** [comment]
I don't got multi enable and i have tried the trick with the sims 2 with the G4ZEB.Raw on the sims 2 and still doesn't work.

**Comment by carnage702** [comment]
> 
> 
> I don't got multi enable and i have tried the trick with the sims 2 with the G4ZEB.Raw on the sims 2 and still doesn't work and not detecting the card at all.

what nintendont version are you running? also maybe your memory cards are too big and nintendont doesnt recognize the second one since there is no memory left, take a picture of your nintendont settings.

Also nintendont is not an emulator, its like a bridge between gc calls and wii cpu/gpu so no its not an emulator.

**Comment by RazorVermillion** [comment]
I'm using 251 size memory card for B and it's not being recognized

**Comment by RazorVermillion** [comment]
I found out the problem now.

Slot B needs to be 128 size to be recognized. 

Slot A can be 251 from testing.

Thank you for the heads up!

**Comment by RazorVermillion** [comment]
Hopefully this could maybe be fixed or added in the future?

**Comment by carnage702** [comment]
i mean nintendont has the option of creating a single memory card per game so on your first post why do you need 2 memory cards? you can simply turn multi to off and let nintendont have a single memory card per game and never run out of space does sims 2 unlçock anything if you have 2 memory cards?

**Comment by RazorVermillion** [comment]
> i mean nintendont has the option of creating a single memory card per game so on your first post why do you need 2 memory cards? you can simply turn multi to off and let nintendont have a single memory card per game and never run out of space does sims 2 unlçock anything if you have 2 memory cards?

The reason why 2 memory cards support would be useful is it saves time and i don't have to keep ejecting my sd card each time i want to play a different game mode on the sims and what if i want to invite my friend over to play some phantasy star online 1 and 2 plus gamecube co-op and create a emulated memory card for him as Slot B?

I have a full set of characters of Slot A on that game.

**Comment by carnage702** [comment]
> 
> 
> > i mean nintendont has the option of creating a single memory card per game so on your first post why do you need 2 memory cards? you can simply turn multi to off and let nintendont have a single memory card per game and never run out of space does sims 2 unlçock anything if you have 2 memory cards?
> 
> The reason why 2 memory cards support would be useful is it saves time and i don't have to keep ejecting my sd card each time i want to play a different game mode on the sims 2 and what if i want to invite my friend over to play some phantasy star online 1 and 2 plus gamecube co-op and create a emulated memory card for him as Slot B?
> 
> I have a full set of characters of Slot A on that game.

why do you need to mess with the save file for sims2? cant you just creat a bigger memory card for that game? doesnt seem like slot 2 would help much in that case, like stated abode slotb does work just make sure your renaming the cards correctly and that they are legit raw files created by nintendont and renamed latter afaik 59 blocks works everytime for slotb) bigger than that might not work, there is not that much free ram available to play around with emulated memory cards.

**Comment by RazorVermillion** [comment]
> > > i mean nintendont has the option of creating a single memory card per game so on your first post why do you need 2 memory cards? you can simply turn multi to off and let nintendont have a single memory card per game and never run out of space does sims 2 unlçock anything if you have 2 memory cards?
> > 
> > 
> > The reason why 2 memory cards support would be useful is it saves time and i don't have to keep ejecting my sd card each time i want to play a different game mode on the sims 2 and what if i want to invite my friend over to play some phantasy star online 1 and 2 plus gamecube co-op and create a emulated memory card for him as Slot B?
> > I have a full set of characters of Slot A on that game.
> 
> why do you need to mess with the save file for sims2? cant you just creat a bigger memory card for that game? doesnt seem like slot 2 would help much in that case, like stated abode slotb does work just make sure your renaming the cards correctly and that they are legit raw files created by nintendont and renamed latter afaik 59 blocks works everytime for slotb) bigger than that might not work, there is not that much free ram available to play around with emulated memory cards.

Well i would do that but EA made it to where you can only use 1 memory card per game mode no matter how big the memory card is. (Which is a dumb move on their part for forcing it on one memory card slot).

There are only 2 game modes
1. Freeplay which has all my create stats family characters.
2. Story mode.

**Comment by GerbilSoft** [comment]
I'll need to test the per-game dual slot support. Will look at it (hopefully) sometime this weekend.

**Comment by carnage702** [comment]
> 
> 
> > > > i mean nintendont has the option of creating a single memory card per game so on your first post why do you need 2 memory cards? you can simply turn multi to off and let nintendont have a single memory card per game and never run out of space does sims 2 unlçock anything if you have 2 memory cards?
> > > 
> > > 
> > > The reason why 2 memory cards support would be useful is it saves time and i don't have to keep ejecting my sd card each time i want to play a different game mode on the sims 2 and what if i want to invite my friend over to play some phantasy star online 1 and 2 plus gamecube co-op and create a emulated memory card for him as Slot B?
> > > I have a full set of characters of Slot A on that game.
> > 
> > 
> > why do you need to mess with the save file for sims2? cant you just creat a bigger memory card for that game? doesnt seem like slot 2 would help much in that case, like stated abode slotb does work just make sure your renaming the cards correctly and that they are legit raw files created by nintendont and renamed latter afaik 59 blocks works everytime for slotb) bigger than that might not work, there is not that much free ram available to play around with emulated memory cards.
> 
> Well i would do that but EA made it to where you can only use 1 memory card per game mode no matter how big the memory card is. (Which is a dumb move on their part for forcing it on one memory card slot for per game mode).
> 
> There are only 2 game modes you can only have 1 game mode per game cube memory slot.
> 
>     1. Freeplay which has all my create stats family characters.
> 
>     2. Story mode.
> 
> 
> ![Untitled](https://user-images.githubusercontent.com/79543686/124034914-d2030800-d9c9-11eb-8859-e84b431805f2.png)
> 
> Wait size of the memory card for slot a and b should be 59 blocks? I'm gonna test that out.
> 
> Alright i've just tested 59 blocks on both cards and still not working for slot b.

they dont need to be same size, you can have 251 slot 1 and 59 blocks slotb atleast i remenber that worked, not sure if it was just for multi or not.

**Comment by RazorVermillion** [comment]
I'm playing this on a original wii though SD Card and the ISO is trimmed to save space on my sd card.

**Comment by DraconicNEO** [comment]
> 
> 
> There _is_ support for two memory cards, but it isn't well documented.
> 
> You need to have a pre-made memory card image for slot B. Both slot A and B must not be larger than 16 MB total. (I'd recommend 2 MB [251 blocks] or smaller for both.)
> 
> If using "multi" (multiple games per card):
> 
>     * Slot A: ninmem.raw / ninmemj.raw
> 
>     * Slot B: ninmemb.raw / ninmemjb.raw
> 
> 
> If not using "multi" (one game per card):
> 
>     * Slot A: GAFE.raw
> 
>     * Slot B: GAFEB.raw
> 
> 
> where "GAFE" is the ID4.
> 
> EDIT: It's the ID4, not ID6.

I tried doing the one where you rename it to have "B" on the end but it still doesn't show up in slot B, I am on the latest version of Nintendont so I don't know what's causing it.

**Comment by RazorVermillion** [comment]
I wonder if anyone else is having this issue with sims 2

**Comment by DraconicNEO** [comment]
> 
> 
> I wonder if anyone else is having this issue with sims 2

Well I'm not Playing Sims 2 but I want to use this Feature in PSO since Slot B allows saving extra data. I'm not able to get it working using One game per memory card (and yes I'm using 251 memory cards).

**Comment by RazorVermillion** [comment]
It would be very useful for PSO and plus my friends can use their own saves within files without having to keep pulling out my SD card every time and switching between file to file.

**Comment by carnage702** [comment]
so from what i saw in the code the slob b is not gameidb but gameid_b?

have you guys tried the gameid _b?

**Comment by RazorVermillion** [comment]
> so from what i saw in the code the slob b is not gameidb but gameid_b?
> 
> have you guys tried the gameid _b?


From my testing, it actually works.
all you had to do was add _B after the gameid

Exactly like this

GAFE_B.raw

Hopefully this gets known and shown for everyone who wants to have a secondary memory card if they choose and want to.

But thank you for the looking in the code carnage702

**Comment by DraconicNEO** [comment]
> so from what i saw in the code the slob b is not gameidb but gameid_b?
> 
> have you guys tried the gameid _b? 

I feel like this information should be added to the Readme file and official documentation.
