### ISSUE TITLE
Wii U crashes when MEMCard Emulation is activated on SD Card

### ISSUE THREAD

**Issue by Fingii** [FIX94/Nintendont#912]
Hey there,
I´ve been having problem with Nintendont for some weeks now and i would hope you guys could help me.  I already made a thread on GBA Temp but sadly no one could help me out. I basically want to play Gamecube Games on my Wii U Gamepad, since i dont have a GC Controller or an adapter. So let me try to summarize everything. 

Here are some methods I tried:

I tried the GC Injects from TeconMoons and Wii U USB Helper. Both result in a black screen.
Then i tried a Nintendont Forwader which was located on my Wii U Menu. Also a black screen.
Then i tried Method 3 from this thread: https://gbatemp.net/threads/tutorial-how-to-play-gamecube-ps1-n64-games-from-the-wiiu-gamepad.489122/  (You have Gamepad support for the vWii homebrew channel and you can control the hombrew channel with your Gamepad, go to Nintendont and use the Wii U Gamepad as your controller, basically just a homebrew channel forwader with Gamepad Support) 
This works just fine and i can control everything with my Gamepad and can play GC with my Gamepad.
But here is the problem. If I use this method Nintendont doesnt recognize my USB Stick and it just says "No FAT Device found". My SD Card works, but the same problem occurs, that when i turn on MemCard Emulation, the Wii U crashes. So this method is pretty much useless for me since only my USB Stick works with MemCard Emulation but it doesnt get recognized using the homebrew channel forwader.

Here are some infos that might be useful:

Nintendont works fine if I go normally to Nintendont via vWii.
I have a USB Stick and a SD Card, both formatted to Fat 32 ( And a HDD for my Wii U Games but i think thats irrelevant since my HDD uses a different format)
For my USB Stick it doesnt matter if I have Memcard Emulation on or off, both work just fine.
For my SD Card it does matter . If its off, it works fine but if its on, Nintendont loads up to 9 Kernels and then the Wii U completely shuts down. I tried 3 different SD Cards so i dont think the SD Card is the problem. I also tried using a SD Card reader so it gets recognized as USB to see if my SD Card Slot from my Wii U may be faulty. Nintendont works fine and recognizes my SD Card reader as a USB but the same problem occurs when i turn on MemCard Emulation.
The physical lock on my SD Card is not "activated". On Windows it says that my SD Card is on Read Only mode, but i cant change that somehow. But it says the same for my USB Stick and my USB Stick works fine. 
I also never had any problem with my SD Card ever, only when using Nintendont, when MemCard Emulation is on.
I also tried a lot of different Nintendont versions, same problem.
I also tried disconnecting every USB Device on my Wii U, so that only my SD Card is in there. Same problem.

So without MemCard i cant save my games, or is there another way with MemCard Emulation turned off to save my game saves?

I apologize if this is a bit long but i tried to answer any questions that might could come up. If there are any things I forgot to mention, please let me know and I will try to answer any questions.
Thanks is advance.

**Comment by carnage702** [comment]
check your sd card saves folder and check for 0kb files and delete any of them

**Comment by Fingii** [comment]
There was a 0kb file in my save folder. Deleted that and now it works! Dont know why i havent tried that. Thank you so much dude, you are a life saver!

**Comment by carnage702** [comment]
> There was a 0kb file in my save folder. Deleted that and now it works! Dont know why i havent tried that. Thank you so much dude, you are a life saver!

A 0kb file is a corrupt file sometimes mcemu files get corrupt on creation for unknown reasons
