### ISSUE TITLE
Gamecube Games not loading in vWii Nintendont

### ISSUE THREAD

**Issue by Octoham** [FIX94/Nintendont#913]
i can navigate the menus just fine but when i try to start a game, it initializes all the kernels up until when the display is drawn. the drawn display only shows a black screen and nothing else.

**Comment by carnage702** [comment]
> 
> 
> i can navigate the menus just fine but when i try to start a game, it initializes all the kernels up until when the display is drawn. the drawn display only shows a black screen and nothing else.

take a picture of your nintendont settings.

also sd or usb? is sd card locked?/usb full?

**Comment by Octoham** [comment]
sd card and unlocked (trust me i checked that at least 4 times) and the settings are here:
![WIN_20210714_09_36_43_Pro](https://user-images.githubusercontent.com/46746534/125631563-ba1e45ee-06d7-416a-89db-6c117f914c22.jpg)

**Comment by Octoham** [comment]
and the card has 700MB left

**Comment by carnage702** [comment]
> 
> 
> and the card has 700MB left

what class is the sd card? maybe its too slow?

**Comment by Octoham** [comment]
its a regular sd card that came with my Wii (i had a wii before i had a Wii U)

**Comment by carnage702** [comment]
> 
> 
> its a regular sd card that came with my Wii (i had a wii before i had a Wii U)

sd cards say on the front the class and im guessing that is a slow as hell sd card might b too slow to load the files and read for nintendont.

you can try 2 things one turn mcemu to off and try to start the games without memory card emulation.

if they run then you have a bad save file go to the saves folder and check for any 0kb files and delete them.

if they dont run you either have bad isos or the sd card is way too slow. you should always use full 1.35gb iso files with md5 check matching redump for best compatibility.

**Comment by Octoham** [comment]
i checked the MD5 (its super smash bros melee v1.02 USA) i had the same issue with mcemu off (i tried before) but i guess i could use my usb to load the game

**Comment by Octoham** [comment]
![image](https://user-images.githubusercontent.com/46746534/125633683-2bfedfb0-92b8-4c5e-8f25-10a41594e840.png)
thats the sd card

**Comment by carnage702** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/46746534/125633683-2bfedfb0-92b8-4c5e-8f25-10a41594e840.png)
> thats the sd card

that is first generation sd card, dont think that has any speed to run any game try using a usb device altough one that isnt a flash drive since flash drives are very poor for homebrew in general and more so in nintendont.

either buy an up to date sd card or an hdd with y cable or its own power supply.

heck i bought a 32gb micro sd card with an adapter for like 8 euros by kingstone like 2 years ago , they are extremely cheap nowadays.

**Comment by Octoham** [comment]
the usb drive goes at 5MB/s i hope thats enough

**Comment by Octoham** [comment]
compared to the 200KB/s that the sd was running at

**Comment by carnage702** [comment]
> 
> 
> the usb drive goes at 5MB/s i hope thats enough

that isnt the issue wiiu has has handicapped usb power supply, that is why you need y cables for hdd and such so the drive might not work 100% due to the power it is getting isnt what the manufacturer design it  for, so it might now work well with nintendont fast request to read/write.

**Comment by Octoham** [comment]
i have an other question, how the heck do people play 8GB wii games using USB Loader when the file system (FAT32) limits a file at 4GB

**Comment by carnage702** [comment]
> 
> 
> i have an other question, how the heck do people play 8GB wii games using USB Loader when the file system (FAT32) limits a file at 4GB

this is not a nintendont question but i can awnser it usbloader can play splitted isos, there is a tool which i forgot the name that splits the iso into 2 parts and usbloader plys the game just fine taking pieces from which part its asked and you get 2 4gb files like xenoblade.0 and xenoblade.1 or something along those lines.

**Comment by Octoham** [comment]
ah ok

**Comment by Octoham** [comment]
and my gamecube controllers don,t seem to work
I have an adapter wich works on my nintendo switch and on my pc

**Comment by carnage702** [comment]
> 
> 
> and my gamecube controllers don,t seem to work
> I have an adapter wich works on my nintendo switch and on my pc

is it a mayflash one or original one? or a random Chinese knockoff? because if its the knockoff you might need to make your own controller ini for it since the vaklues will not be hardcoded in nintendont, most have a wiiu switch you can toogle and even then might not work.

**Comment by Octoham** [comment]
i think random japaneese knockoff that works very well and i always use it in wiiu mode

**Comment by carnage702** [comment]
> 
> 
> i think random japaneese knockoff that works very well and i always use it in wiiu mode

that doesnt matter if it works well or not, since not one made a controller.ini for it it wont work at all, i dont know how to make controller inis so i cant help you, nintendont uses controller by the way of ini files, if its a fake knockoff adapter its values wont match the real ones so they can be readed by nintendont at all.

**Comment by Octoham** [comment]
welp i guess i could use the wii u gamepad but i'd need the wiiu nintendont forwarder

**Comment by carnage702** [comment]
> 
> 
> welp i guess i could use the wii u gamepad but i'd need the wiiu nintendont forwarder

dont you have a wiiu pro controller? wiimote+classic controller?

**Comment by Octoham** [comment]
i only have wii remotes ,nunchucks and gamecube controllers

**Comment by Octoham** [comment]
i should close the issue
