### ISSUE TITLE
General problem with getting my .ISO file to appear on the Nintendont game list

### ISSUE THREAD

**Issue by Latiascringesatyou** [FIX94/Nintendont#914]
Kind of mid question here, but when I try to open my ISO on Nintendont, it always says "Boot GC Disc in Drive [DISC01]" and not the name of the game, and like any person new to Nintendont, I casually select the Boot GC Disc in Drive thing. Then, the same exact message pops up: "The Disc Drive Could Not Be Initialized!" and takes me back to the Wii Homebrew screen. I put the exact files for for Nintendont in the right place, the ISO where it needs to be, and the same message still appears. The file type of the ISO I'm using is ISO itself (Disc Image File file type), and this leads me to a confusion circle. Does anybody know how to solve this? Is it the ISO's, SD Card's, or Wii's fault? Could it be my fault? Somebody please answer me soon, this is the only alternative I have to playing mario kart double dash on my Family Edition Wii, since my Wii can't read my MKDD Disc. (If this issue breaks the GitHub Community Guidelines, please tell me and I will delete this.)

**Comment by carnage702** [comment]
your not putting the iso in the correct place not sure if you use sd or usb but the path is

sd:games/anyname/game.iso

the iso itself needs to be renamed to game.iso and make sure your not running hidden extyour iso is actualy named game.iso.iso you need a folder called games on the root of sd or usb too.

so for your case you could put the iso like this
sd:games/Mario Kart DD/game.iso
or
usb:games/mario Kart DD/game.iso

**Comment by Latiascringesatyou** [comment]
I did as so, and the problem no longer appear but now this pops up: ![image](https://user-images.githubusercontent.com/87508408/126012088-dcbd4cac-b5b5-4ff2-b0ce-ea2fc1104e48.jpeg) (it says the disc is not a GCN disc if you can't see the image) I can assume it's the ISO's problem now. The game file is an disc image file,so if it's the ISO's problem, I will find a new file for it, if anything else happens I will tell you

**Comment by carnage702** [comment]
you dont get it if nintendont is seeing the iso there will be listed at the menu and not the boot disc option...

take a picture of your sd/usb root, then a picture inside the games folder and then a picture inside the mario kart dd folder

you will never choose that option to boot any iso that is only for booting real discs in the drive on original wiis with gc ports nothing else, all isos appear named right below that if nintendont sees them.

**Comment by Latiascringesatyou** [comment]
These are all the images in the order you specified the picture's subject in:(root) ![image](https://user-images.githubusercontent.com/87508408/126015880-ef1ca483-2c6b-4f5f-a47e-d54bda8dfe32.jpeg)(inside games file)![image](https://user-images.githubusercontent.com/87508408/126015981-e2b0b11d-0808-4ed5-883e-756f40bf28ff.jpeg)(inside MKDD file) ![image](https://user-images.githubusercontent.com/87508408/126016066-26e746fd-5f9a-4ec7-a942-a80cc2a28444.jpeg) where is the part where I messed up?

**Comment by carnage702** [comment]
im guessing you have hidden extensions on your pc and your iso is actually called game.iso.iso so try to just rename your iso to game instead of game.iso

**Comment by Latiascringesatyou** [comment]
thanks, the iso now works, but I possess yet another problem, the wii classic controller doesn't work. I saw somebody's issue saying the wii controller doesn't work if it's a third party model and I believe my classic controller is third party. It has plus symbol-like screws, and I'm pretty sure that's an indication of an third party device. If this is what is causing the problem, is there a file (or setting I can enable on nintendont) I can add to make the wii classic controller work properly? or, is it just the wiimote's connection to the sensor bar?

**Comment by carnage702** [comment]
Nope nothing can be done, if it's third party or fake and doesn't work then there is no setting to be toogled or changed, you can either buy official stuff or use some hid USB controllers like PS3  or PS4 controller if you have any.

**Comment by Latiascringesatyou** [comment]
I do have one official wiimote, do I just need to connect a nunchuck in and it will work?

**Comment by carnage702** [comment]
> 
> 
> I do have one official wiimote, do I just need to connect a nunchuck in and it will work?

it will somewhat work since wiimote+nunchuck doesn't have enough buttons to emulate the gc controller there is alot of wierd moves and combos and such, its not recommended at all just buy an official classic controller or classic controller pro , there are plenty out there used to sale.

or if you have some other console with usb controllers like ps3, ps4 or some adapters like wiiu gc adapter and a gc controller or switch such, or even if you have an wiiu pro controller if official you can sync it to wii menu on wii and it wont work on anything on wii but it will on nintendont even on wii.

so the issue is solved so now you have other issues which we cant do much about.

**Comment by BREAKINGKINGS1** [comment]
Can someone please help so I have nintendont i done everything correct downloaded rom from vimms lair made a games folder on root sd card extracted into games folder but when I extract it has .nkit not .iso

**Comment by carnage702** [comment]
> Can someone please help so I have nintendont i done everything correct downloaded rom from vimms lair made a games folder on root sd card extracted into games folder but when I extract it has .nkit not .iso

nkit iso are not recommended  for nintendont nor they are officially supported just find a regular iso.

**Comment by GB-CG** [comment]
@BREAKINGKINGS1 FYI, Nkit ISO's can be decompressed back to the regular iso in the nKit settings.
