### ISSUE TITLE
Mario kart arcade gp 2 randomly crashes

### ISSUE THREAD

**Issue by littlelum** [FIX94/Nintendont#918]
When playing MKAGP2 sometimes the game crashes when loading a level or transitioning between menus. Some examples are loading a race, selecting continue after finishing a race, and selecting a character or car. Triforce arcade mode setting doesn't help. I'm using a condensed ISO if that's important. Also loading off of an SD card. Thanks.

**Comment by carnage702** [comment]
never had the game crash on me at all, maybe you are forcing settings on the game that shouldnt be forced? also triforce games require alot of speed so maybe your sd card is not fast enough?

**Comment by littlelum** [comment]
I'm not forcing anything other than arcade mode and emulated memory card, everything else is off. I tried using a usb hard drive but it could be read due to bring in FAT format. (I can't reformat it because it's shared by multiple people) I don't have any other usb hard drive. Would enabling high read speed help?

**Comment by carnage702** [comment]
> 
> 
> I'm not forcing anything other than arcade mode and emulated memory card, everything else is off. I tried using a usb hard drive but it could be read due to bring in FAT format. (I can't reformat it because it's shared by multiple people) I don't have any other usb hard drive. Would enabling high read speed help?

doesnt hurt to try but like i said hundreds of people tried this game and i cant recall an issue like yours, it just seems the game cant read fast enough and crashes, if unlock read speed doesnt work you need to get a new more recent sd card since im guessing you have a very slow one.

**Comment by littlelum** [comment]
I tried enabling faster load speed, and it hasn't crashed yet, so that's good. Anyways, regardless whether or not that fixed it, thanks for helping me out. I tend to get strange issues that people normally don't get, and I appreciate being given a straight answer for once. Thanks again, and have a nice day!
