### ISSUE TITLE
Metal Gear Solid - The Twin Snakes OST mod

### ISSUE THREAD

**Issue by ViewtifulM** [FIX94/Nintendont#919]
Hi!

I'm trying to play a [Metal Gear Solid - The Twin Snakes OST mod](https://youtu.be/W5DZPLZx6s4) via Nintendont on my Wii U. The game loads fine but after the Konami logo I get the following error (see attached image):

"ERROR: module 'shared/mgso__pal.rel' is too big

limit is 4874240
size is 1452174120
over by 1447299880"

I have checked the MD5 and it seems OK. Original ISO plays fine.

Any clue?

Thanks!

![IMG_20210731_163952](https://user-images.githubusercontent.com/66161515/127753104-7f5dc9ab-24f2-4729-bf5d-ee880519bdd7.jpg)

**Comment by carnage702** [comment]
take a picture of your nintendont settings.

**Comment by ViewtifulM** [comment]
![IMG_20210801_093807](https://user-images.githubusercontent.com/66161515/127763269-93923649-d052-49c9-a05c-82f536ddfde4.jpg)

**Comment by carnage702** [comment]
did you actually tried your iso on dolphin to make sure its correctly patched? the warning error is a game error not a nintendont one, once a game starts nintendont doesnt have any graphic interface to write anything on the screen, which means that is a error sent by the game itself.

**Comment by ViewtifulM** [comment]
I have repatched the game just in case. It is working on Dolphin, but shows the same error (with different numbers) on Nintendont.
![IMG_20210801_102005](https://user-images.githubusercontent.com/66161515/127764920-de497e55-0cac-4aca-8e0a-b9c98889801f.jpg)

**Comment by carnage702** [comment]
> 
> 
> I have repatched the game just in case. It is working on Dolphin, but shows the same error (with different numbers) on Nintendont.
> ![IMG_20210801_102005](https://user-images.githubusercontent.com/66161515/127764920-de497e55-0cac-4aca-8e0a-b9c98889801f.jpg)

well nintendont cant write to the screen so that is a game error, nintendont is not an emulator, is more of a bridge turning gc code into wii code, and doesnt have any gfx to write anything to the screen besides the menu itself i saw that you are using patch pal50 to on did you tryed turning that off?

 maybe dolphin removes limits or something no idea also patching a game should always yeld the same effect, not sure how repatching a game gives you different rel sizes if its the same patch.

**Comment by ViewtifulM** [comment]
I have tried vanilla settings and it is not working.

**Comment by carnage702** [comment]
so i finally tried this and it works pretty well so you are doing it wrong for sure.

i have all my nintendont settings set to off or auto except mcemu which is on
used the link  you posted and used the youtube google drive link option
downloaded the patch option  pal pal 001 to 004
used 7z to extrac into single files
got an md5 pal iso matching redump
downloaded xdealtaui utility from first google results
used xdeltaui chooing the patch and the iso and the new iso named game.iso
putted iso on sd card and it works on wiivc just fine.

and it works... so im not sure

**Comment by ViewtifulM** [comment]
Hmmm... I don't know what I can be doing wrong. I mean... I've followed the very same steps you did... And it works on Dolphin! This is driving me crazy!

**Comment by carnage702** [comment]
> 
> 
> Hmmm... I don't know what I can be doing wrong. I mean... I've followed the very same steps you did... And it works on Dolphin! This is driving me crazy!

do you have a previous save file? maybe an older save file is not compatible with the patched version?

**Comment by ViewtifulM** [comment]
I'm going to start all over again from the very begining.

**Comment by GB-CG** [comment]
@ViewtifulM The mod got updated to 1.3 this year and should resolve most issues on hardware now. No issues for me so far.

**Comment by Invincible-Atlas** [comment]
I have been having a similar issue, except it says that module 'shared/mgso.rel' is too big, and that the size is -1537292761, and it is over by -1542160857. also, I am using an unmodded version of the rom.
