### ISSUE TITLE
Is There a Way to Put Nintendont into Gamecube Mode?

### ISSUE THREAD

**Issue by ReclaimerShawn** [FIX94/Nintendont#921]
I'd like to put Nintendont into Gamecube Mode in order to be able to get proper addresses whenever I use my USB Gecko, as I wanted to make cheats for the Gamecube. I know there is an option to use Nintendont with Native Control, but Nintendont is still in Wii Mode while this occurs. Is there a way to either get Nintendont to work in Gamecube Mode or to get some other program to load Gecko Codes/Debugger while in Gamecube Mode? Thanks for reading.

**Comment by carnage702** [comment]
No... Nintendont runs in Wii mode that is the point of nintendont to run in GC mode you use dios mios
