### ISSUE TITLE
Savefile present on a real memory card is not read correctly

### ISSUE THREAD

**Issue by ctwurp** [FIX94/Nintendont#926]
When playing the PAL version of Zelda: Twilight Princess with the save stored on a real memory card present in Slot A some data (from what I've seen only the playtime and the date of the save) is read incorrectly. This issue is not present when using same memory card with the same savefile on it playing in the consoles native GameCube mode or on a real GameCube. I have not tested if this also happens with the emulated memory card feature but I can do that if you need me to. I'm playing on a white RVL-001 console with the RVL-CPU-01 motherboard revision if that is something you need to know. I've attached some pictures that shows the difference. If you need a copy of the save or the whole memory card please let me know, I'd
 be happy to provide them to you.

![nintendont](https://user-images.githubusercontent.com/89127138/129859133-7dcbf4a3-1075-4465-9198-44767ca6efda.jpg)
(Nintendont)
![gcmode](https://user-images.githubusercontent.com/89127138/129859447-f513469b-38c3-4b68-b440-13835ce8039c.jpg)
(GameCube mode)
![gcmode using swiss](https://user-images.githubusercontent.com/89127138/129860079-114ad018-f82a-413f-b819-ecc5e853a82e.jpg)
(GC Mode using swiss for 480p patches)

**Comment by carnage702** [comment]
probably has to do on how the game counts time, they probably counted time and compare to gc cpu to show the playtime, while nintendont runs on wii cpu therefore the game calculations faisl to count time becuase its using the wii cpu value instead of the gc cpu value, and they dont match, so its not reading it wrong, its reading it completely right, the ticks just dont match up so the game doesnt calculate the time liek ti should be calculated, minor issue that doesnt affect anything imo.

**Comment by binturongx10** [comment]
This also happens with Wind Waker.

GC Mode
![20210915_075904](https://user-images.githubusercontent.com/44976517/133429631-dfdd055d-b0dc-4287-9201-74e0702159e1.jpg)

Nintendont
![20210915_075803](https://user-images.githubusercontent.com/44976517/133429739-795c593c-f26f-4269-b94f-f851ed30dea3.jpg)
Does not seem to cause any real issues tho.

**Comment by binturongx10** [comment]
It was funny when dolphin thought my twilight princess save was from 2032 tho.

**Comment by carnage702** [comment]
like said abode some games count time by using ticks so when they compare those tiks the times will be changed if you start and finish a game on nintendont the time will be correct, if you bounce around between nintendont and gc and dolphin the time will be all over the place, the only way to do this is patching every game that counts time  this way and make a custom patch for each one which isnt ideal and not really something that someone would invest time for a cosmetic change.
