### ISSUE TITLE
Sonic Riders (PAL) freeze on loading screen

### ISSUE THREAD

**Issue by Vendicatorealato** [FIX94/Nintendont#927]
Sonic Riders (PAL) freeze on loading screen when Tag Mode is selected. I am on a first model of Wii, I tried an untrimmed .iso ROM on SD Card and USB HDD (FAT32 with 32KB of unit cluster size), italian language, with various Nintendont settings... but the result is always the same.

**Comment by carnage702** [comment]
https://www.mediafire.com/file/hilym1huus7w2q1/boot.dol/file

can you try this file? and see if it works now?

**Comment by Vendicatorealato** [comment]
For now I could try only a trimmed .iso on SD Card, it has the same problem.

**Comment by carnage702** [comment]
just make sure you have an iso with the md5 matching redump and everything off or auto except mcemu if needed i will try this myself when i have the time tough.

**Comment by Vendicatorealato** [comment]
Maybe is better if you can try yourself when you have time, now I tried the 1:1 ROM (always on SD Card FAT32 with 32KB cluster size) with all Nintendont settings set to Auto or Off (the only exception is Native Control, that was On), and the result is always the same. I think that the ROM is ok because it works without problems on Dolphin.

**Comment by carnage702** [comment]
So i tryed this and both pal and usa version have this issue, i guess no one cared to try tag mode all this time and without fix94 here i dont know if there is anyone still caring to try and track down this issue  i took a debug log and it seems its an invalid adress type of crash

https://pastebin.com/unjQHGGi

if anyone can and wants to put a pull request to fix this i will merge it tough.

**Comment by hurda** [comment]
>  i guess no one cared to try tag mode all this time

Not quite:
https://gbatemp.net/threads/nintendont.349258/page-1267#post-5372471
March 2015

**Comment by carnage702** [comment]
> 
> 
> > i guess no one cared to try tag mode all this time
> 
> Not quite:
> https://gbatemp.net/threads/nintendont.349258/page-1267#post-5372471
> March 2015

guess fix94 just didnt care much to fix that then lol i stand corrected.

**Comment by Vendicatorealato** [comment]
I read all the discussion, on Nintendont r313 Tag Mode worked for FIX94 and pedro702 but not for memoryman3... and him wasn't able to fix it. The problem seems to be releated to the SD card, that or is too slow (but in my case I have a SanDisk Ultra with 80 MB/s of speed reading, then I don't think that the problem in this) or too fragmented. I'll try to re-format the SD, I'll let you know.
The thing that seems strange to me it's that you -pedro702- have tried personally now and confirmed that actually the game freeze, then... perhaps in a later version than the r313 Nintendont got a regression? I don't know if it's possibile, I'm only thinking about different possibilities.

**Comment by carnage702** [comment]
> 
> 
> I read all the discussion, on Nintendont r313 Tag Mode worked for FIX94 and pedro702 but not for memoryman3... and him wasn't able to fix it. The problem seems to be releated to the SD card, that or is too slow (but in my case I have a SanDisk Ultra with 80 MB/s of speed reading, then I don't think that the problem in this) or too fragmented. I'll try to re-format the SD, I'll let you know.
> The thing that seems strange to me it's that you -pedro702- have tried personally now and confirmed that actually the game freeze, then... perhaps in a later version than the r313 Nintendont got a regression? I don't know if it's possibile, I'm only thinking about different possibilities.

lots of things changed it might be a matter of fitting it on an existing exception list or something im trying 313 where its suposed to work and ntsc works fine on tag mode on 313 and pal still doesnt, im wondering if its a bad iso i got even tough it matched redump now hmm

**Comment by Vendicatorealato** [comment]
> > 
> 
> > 
> 
> > I read all the discussion, on Nintendont r313 Tag Mode worked for FIX94 and pedro702 but not for memoryman3... and him wasn't able to fix it. The problem seems to be releated to the SD card, that or is too slow (but in my case I have a SanDisk Ultra with 80 MB/s of speed reading, then I don't think that the problem in this) or too fragmented. I'll try to re-format the SD, I'll let you know.
> 
> > The thing that seems strange to me it's that you -pedro702- have tried personally now and confirmed that actually the game freeze, then... perhaps in a later version than the r313 Nintendont got a regression? I don't know if it's possibile, I'm only thinking about different possibilities.
> 
> 
> 
> lots of things changed it might be a matter of fitting it on an existing exception list or something im trying 313 where its suposed to work and ntsc works fine on tag mode on 313 and pal still doesnt, im wondering if its a bad iso i got even tough it matched redump now hmm

At the time on GBATemp you tried also PAL version and you said that it works well... wow, this is a very curious issue.
I don't know nothing about coding, but maybe can be an idea to implement the changes that you made above on latest version in r313?
Anyway, I don't know if it can be useful but I tried it with an Official GameCube Controller (Smash U Edition) and with an official 1019 Memory Card. Try the game with Native Control Off and Unlock Read Speed On can be an idea?
Sorry if I am only writing and not testing, it's because I don't have the Wii now and then I can't try nothing, but I'm interested to help to solve this issue!

**Comment by carnage702** [comment]
So i fixed sonic riders usa freeze on tag on the newly released 497, and found out for some reason the patch fix94 made for sonic riders pal does not apply to the game and even if you force it the game will still crash so i think he made a mistake on some numbers on the patchs somewhere, maybe back then when i tryed the pal version i clicked on the ntsc instead of pal to test, becuase even on 313 tag mode does not work on pal version so the patch never worked im guessing.

Making patches is too much advanced for me so you need to find a damn good codder to take a good look at this, also the ntsc version has the same languages as pal version and runs with 60hz and has native progressive report so if you guys really want to play tag mode that much you can do so on the ntsc version now on 497.

**Comment by Vendicatorealato** [comment]
I tried now the PAL version with r497, the Tag Mode works!!! SD card configured as I said before, and in Nintendont settings Native Control, Force progressive and Force widescreen are On.

**Comment by carnage702** [comment]
> 
> 
> I tried now the PAL version with r497, the Tag Mode works!!! SD card configured as I said before, and in Nintendont settings Native Control, Force progressive and Force widescreen are On.

you are right lol i just tested it and yes if you force progressive and widescreen the tag mode does indeed work.

Seriously this game codding is awful, basically he doesnt like more cpu power or tramples over itself while loading, so the more settings you force nintendont to apply less cpu power goes to the game therefore tag mode works because nintendont is allocating some cpu power to force widescreen and force progressive lol.

well that is one way to play this game pal release i guess, damn sonic team making such a buggy mess...
