### ISSUE TITLE
Pikmin 1 (PAL) DOES NOT LOAD.

### ISSUE THREAD

**Issue by RAAVENNGAMER** [FIX94/Nintendont#928]
Hello developer (carnage702) or developers. I have a WII that I bought a few days ago and it is the first time that I have one, I touch one, I play with one, etc.

The truth is that I learn something quickly if things are explained to me well and in detail. For example, if they tell me about something, they have to explain to me what it is, how it works, how it is installed, where I can get it, how to delete it, where to install it, how to install it, etc, that is, all the details. I mention the above to clarify that I understand quickly if things are explained to me well because the truth is I know about these games, I like to play them, etc.

Returning to my explanation, I said that I bought a wii a few days ago, and I did a hack following these steps of a tutorial, although it is in Spanish which is my native language, but I think the important thing is to see the steps and I put it here to Let them know how I did it and maybe that is the problem or I don't know. I want to be fully understood so that I can solve my problem because I have been looking for a long time:

- https://www.youtube.com/watch?v=6fSrb0PVrSc&list=PLMk1B3p-qHkCDrJmVbiVkqX7PlxVG2wsS&index=2&ab_channel=TutioCriss
- https://www.youtube.com/watch?v=3PKSD45Bzes&list=PLMk1B3p-qHkCDrJmVbiVkqX7PlxVG2wsS&index=3&ab_channel=TutioCriss
- https://www.youtube.com/watch?v=2Nwk6_-Ddt4&list=PLMk1B3p-qHkCDrJmVbiVkqX7PlxVG2wsS&index=4&ab_channel=TutioCriss
- https://www.youtube.com/watch?v=vnpmZvV_myI&list=PLMk1B3p-qHkCDrJmVbiVkqX7PlxVG2wsS&index=5&ab_channel=TutioCriss
- https://www.youtube.com/watch?v=hVeD_jKg4Is&list=PLMk1B3p-qHkCDrJmVbiVkqX7PlxVG2wsS&index=6&ab_channel=TutioCriss
- https://www.youtube.com/watch?v=KLHRRVCoH4A&list=PLMk1B3p-qHkCDrJmVbiVkqX7PlxVG2wsS&index=7&ab_channel=TutioCriss

And that's it.

Now I will talk about the specifications of my wii.
My wii is American:
- Ver. 4.3U
- Screen: 480p, 16: 9 (I use the “Component” cables, those with 5 inputs: 3 video and 2 audio)

![image](https://user-images.githubusercontent.com/70992213/130911608-ee4a6b19-ef0d-4cff-aef5-9c3134a051ce.png)

My Homebrew Channel says:
- 1.1.2
- IOS58 v24.32

My Nintendont:
- v6.489
- Firmware: 58.24.32

I continue. On my wii, I use a sd memory for apps, settings and so on. For games I use a USB. On my USB I have both wii and gc (GameCube) games. They all really run me well, but I've been having problems with only 2 games: “luigi's mansion” and “pikmin”. These games have only given me problems when trying to play them in Spanish, European version (pal), but the English version (ntsc) does not give me problems. The fact is that as I mentioned before, my native language is Spanish, and it is true that I defend myself a little in English because I am learning it, but it is not the same to enjoy a game in your own language than to try to understand everything in another language. . I have to say that I have been able to play “luigi's mansion”. I tried different settings until I found the right one. For those who are interested, I have 2 cases:

In one of the blogs at https://wii.scenebeta.com specifically in this link ( https://wii.scenebeta.com/node/63105 ) (in Spanish too), someone mentioned that the configuration for luigi's mansion that worked on Nintendot it was:

- Video: Force (Deflicker)
- VideoMode: NTSC
- Patch Pal50: On

However, this setting did not work for me. In my case the one that worked was:
- Memcard Emulation: On
- Force Widescreen: On
- Video: Force
- Videomode: NTSC
- Memcard Blocks: 251
- Video Width: Auto
- Path PAL50: On (Here I have to mention that when I deactivate it, the game appears in a different color, for example, the color of the Nintendo logo when the game starts is blue. Path PAL50 must be activated in my case to make the game look good)
![image](https://user-images.githubusercontent.com/70992213/130911644-0250f1c5-0874-4cd4-b92c-74e07524d2dc.png)

For those who are interested, here is the information of the game:
- YouTube video from which you download the game (in Spanish): https://www.youtube.com/watch?v=b2FD5PryVPg&t=56s&ab_channel=masterpegaso1
- Mediafire link presented in the previous video: http://www.mediafire.com/file/328qb8sjylnxcr1/Lu1g15_m4ns10n.7z/file

Continuing with my explanation, the problem I have now is with the Pikmin game.
- page where you download the game: https://romsnintendoenespanol.com.ve/ngc/pikmin-ngc/
- link 1 of mediafire obtained from the previous page: http://www.mediafire.com/file/m078yja0kfl1575/Pikmin_%255BNGC%255D_%255BRoms_Nintendo_en_Espa%25C3%25B1ol%255D.part1.rar/file
- link 2 of mediafire obtained from the previous page: http://www.mediafire.com/file/adb0xpt1rei89y5/Pikmin_%255BNGC%255D_%255BRoms_Nintendo_en_Espa%25C3%25B1ol%255D.part2.rar/file

In total the game weighs approximately 1.35 GB.
 
The thing is, I have tried a lot of settings for this game, but it doesn't load it for me. When I use the same settings that I used for luigi's mansion listed above, the game only loads the Nintendo logo at the beginning, and the game's voice saying “pikmin” also plays when the game starts and the logo is displayed. But then the logo disappears and remains on a black screen. As I said before, I have tried all the video mode options: force ntsc, pal50, (pal60 in usb loader), and nothing. I also tried to change the resolution of the wii, lower the quality to 480i and nothing, also change the screen in the wii settings from 16: 9 to 4: 3 and neither. Also disable Path PAL50 and nothing. And I already ran out of ideas. But the next day I try again, and I've been like that for several days, but I'm tired of it xD.

I came across this YouTube video: https://www.youtube.com/watch?v=ajCwoFfIHuM&ab_channel=FearStigma

This video provides the mega link to download both Pikmin 1 and Pikmin 2 for gc (GameCube).

Link of the games from the previous video: https://mega.nz/folder/0SwE2CDA#apRl3uKHRnb4rg7AFIP6ig

In one of the comments on this video, the user: "Rodrigo ramirez" whose profile picture is an image of Mario's "green mushroom"
![image](https://user-images.githubusercontent.com/70992213/130911691-de8871ee-5df8-433c-a28b-ce1a9c8a6240.png)

He claimed that the pikmin game, or rather, both of them worked perfectly for him on his wii. That comment is from 2 years ago, and he himself specified in response to a comment he received from someone ("Oscar Eduardo Jimenez Cunjama" who at that time had the same problem that I have) that the version of nintendont that he had and in which the game worked for was the "v5.483".

I suppose that the current version of nintendont that is v.6489 should be better than the one Rodrigo ramirez mentioned he had. And you can't really judge the version just by a game that doesn't work, which in my case is pikmin. It may work for someone else. Anyway, this is my problem and I would very much like you to help me solve it.

Things to keep in mind:
- Everything I have explained I have written in Spanish and translated into English. So sorry if something is not perfectly understood, it may be a translation error. But I tried to be clear.
- Thank you very much for developing nintendont and giving support. I know very well that nintendont is not different from everything in life, that it is not perfect and can give failures.
- I wait for an answer as soon as possible, because I want to play this game with great eagerness. And I hope I can help those who have wanted to play luigi's mansion like me in 2021.

**Comment by Maesejesus** [comment]
RAAVENGAMER, the reason you can't play Pikmin 1 PAL is precisely because it's a 50Hz only game. 

You can try this patch I made long ago, to turn the PAL release into a 60Hz 480i, and then you can also force Progressive, then you can play it at 480p normally. 

http://www.romhacking.net/hacks/3001/

Good luck.

**Comment by RAAVENNGAMER** [comment]
> RAAVENGAMER, the reason you can't play Pikmin 1 PAL is precisely because it's a 50Hz only game.
> 
> You can try this patch I made long ago, to turn the PAL release into a 60Hz 480i, and then you can also force Progressive, then you can play it at 480p normally.
> 
> http://www.romhacking.net/hacks/3001/
> 
> Good luck.

Hello Maesejesus. Thank you very much for the tip. However, I don't know how to make or apply that patch to the game. Could you explain the steps to follow in detail in a comment? Ago emphasis on this part, please explain me as someone who has never patched a game and does not know anything about this in order to understand and do this well. What should I open, what should I press, when should I enter it into memory, etc. The post you sent me downloads a file with a .ips and an .xdelta patch, as well as some instructions, but I don't understand them. So if you could do me that favor.

1- As I told you, I have already downloaded the file of the post you sent me.
2- I already have the LunarIps program.

**Comment by Maesejesus** [comment]
Sorry for not answering earlier, I had some busy days. 

Patching with IPS is very simple:

Open Lunar IPS. 
Choose Apply IPS Patch.
A window will open, go to the folder where you have the file "Pikmin 1 PAL 60Hz Mode Patch.ips", double click it. 
Another window will open, this time looking for your Pikmin ISO. Double click it too. It has to be a clean image. 
Once you select it, the program will apply the changes, and that's all you need to do.

After that, you only have do the usual thing and put the game on the correct folder on whatever device you use to load games, SD, USB or whatever it is. You can shrink the image too if you want, it'll work too. 

Good luck with it!
