### ISSUE TITLE
Compile fails with devkitppc r39-2 (GCC 11) and libogc 2.3.1-1

### ISSUE THREAD

**Issue by Ntemis** [FIX94/Nintendont#931]
Building FatFS library for ARM
 
make -C fatfs -f Makefile.arm
make[1]: Entering directory '/home/demetris/Desktop/Nintendont/fatfs'
CC	ff-arm.o
make[1]: /opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc: Command not found
make[1]: *** [Makefile.arm:42: ff-arm.o] Error 127
make[1]: Leaving directory '/home/demetris/Desktop/Nintendont/fatfs'
make: *** [Makefile:45: fatfs/libfat-arm.a] Error 2

**Comment by Jonaykon** [comment]
did you figure out the problem? im having the same issue

**Comment by saulfabregwiivc** [comment]
read this: https://github.com/FIX94/Nintendont?tab=readme-ov-file#compiling
