### ISSUE TITLE
2nd controller keeps defaulting to the 4th controller port

### ISSUE THREAD

**Issue by AJgibhub** [FIX94/Nintendont#932]
So, i have 2 classic controller pros, one of them works on my normal wiimote just fine, but the other cc on my other wiimote keeps defaulting to the 4th controller port, even if i boot that controller first, also, both of them work on my wii completely ok and set themselves in the right order outside of nintendont, is there any way of changing the controller number order in here or is it something in my end?

**Comment by carnage702** [comment]
by 4 controller you mean all 4 lights get turned on? or just the 4 light alone? if all 4 lights are on means nintendont cant read it, its probably fake/3rd party wiimote or classic controller, they dont work well in homebrew.

**Comment by AJgibhub** [comment]
only the 4th light gets turned on yes, also my other wiimote is a fake/third party one, the other one who worked is an official

**Comment by carnage702** [comment]
if its defaulting to 4 means you have stuff connected to the wii or usb that have the other slots, and you are telling me if you go to a game like ssbm the  CC will be 4 player? you are sure it works? 
Also what do you have connected on your wii? both wii gc ports, wii usb and wii bt?

**Comment by AJgibhub** [comment]
i didnt yet check if the controller only works in the 4th controller port, also the only things that are on  my wii now are my usb that i keep my wii games on and the other that i have my homebrew and gc games on

**Comment by AJgibhub** [comment]
i've tested it now with rayman arena and melee, the the controller dosent work at all

**Comment by carnage702** [comment]
> 
> 
> i've tested it now with rayman arena and melee, the the controller dosent work at all

yup like i said its all lights on which means its either a fake wiimote or fake CC pro, fake/3rd partys usualy dont work on homebrew in general.
