### ISSUE TITLE
Can't tell what version of Nintendont I'm on

### ISSUE THREAD

**Issue by pa-august** [FIX94/Nintendont#934]
I'm on Wii U.

I've downloaded the latest loader.dol and renamed it boot.dol, and overwrote it the old one on my SD card, along with meta.xml and icon.png. However, Nintendont still claims it's version 6.489 from Oct 2019. 

Using the updater from the menu doesn't seem to do anything. Trying any of the other update options from the Nintendont menu causes a hard crash and I have to unplug the system.

**Comment by carnage702** [comment]
If the version didn't update then you didn't replaced the right file or downloaded the latest one   remember nintendont is a Wii app so nintendont boot.dol  goes into SD:apps/nintendont not SD:wiiu/apps/ nintendont

**Comment by pa-august** [comment]
I tried using a different Wii U forwarder than the one I had been using previously, and apparently that was the issue. Either it has an old version of Nintendont bult into it or is pointing to the wrong thing, which I didn't even know was a possibility.
