### ISSUE TITLE
6.498 crashes/shuts down when loading F-Zero GX (NTSC-U) if memory card emulation is enabled

### ISSUE THREAD

**Issue by lemmingfactory** [FIX94/Nintendont#936]
Version 6.498 shuts off console when attempting to load the game if memory card emulation is enabled.  This error occurs when using the Nintendont loader through the homebrew channel or via Wiiflow Lite.  Disabling memory card emulation allows game to run normally.  This occurs even with no other options enabled.  Tested with two Wiis and one Wii U, with exact same result (immediate shutdown).  F-Zero GX (NTSC-U) ISO ripped from original disc and verified with Redump.

**Comment by carnage702** [comment]
you probably have a corrupt save file on your sd card go to you sd card and check the saves folder and delete any 0kb files that might be in there.

**Comment by lemmingfactory** [comment]
Deleting the game's 32kB save file fixed the issue.  Thank you!
