### ISSUE TITLE
Error loading save for Star Wars Rogue Squadron III - Rebel Strike from physical memory card

### ISSUE THREAD

**Issue by Arrghus8** [FIX94/Nintendont#946]
I'm having trouble getting Nintendont to load a save file for Star Wars Rogue Squadron III - Rebel Strike from a physical 251 memory card.
When starting up the game, I get an error message:
"Memory Card Slot A:
This Memory Card 
is damaged and cannot
be used with this game."

I can load the save file if I use Devolution or launch by disc.
I can also load saves for other games using Nintendont without any issues.

If I run the game through Devolution/disc and update the save file, then Nintendont is able to load the save on the following boot.
After the save file is updated from within Nintendont, future boots give the above error message.
I have tried formatting the memory card using GCMM and restoring the save file, but it does not fix the problem.

Any help or suggestions are greatly appreciated.

Thanks!

**Comment by carnage702** [comment]
what is the size of your real memory card? 8mb? 16mb?

**Comment by Arrghus8** [comment]
I have the same behavior with a Nintendo black 251 block memory card and a white 1019 block memory card.
I don't have a 59 block card to test, but I imagine there would be no change.

**Comment by carnage702** [comment]
if you put the save file on an emulated memory card the save works fine?

**Comment by carnage702** [comment]
also take a picture of your nintendont settings btw.

**Comment by Arrghus8** [comment]
The save file works if I use an emulated memory card.

I'm using USB Loader GX to launch Nintendont, so the settings are handled through there.
As near as I can tell, the only changes I've made are to set
Auto Boot: On
Unlock Read Speed: On
Skip IPL: Yes

After playing around with the settings, it seems like everything works as it should if I set "Skip IPL" to no, which is a workaround I'm happy to use.

I've done some further testing with "Skip IPL" set to yes.
If I use GCMM to _dump_ the save file, then Nintendont will successfully load the save on the next boot.
I'm not sure how or why GCMM would be changing the save file on the memory card when dumping it, but something must be happening.
Subsequent boots through Nintendont (with "Skip IPL" on) will give the corrupted save message until I again use GCMM to redump the save file (or launch the game by disc/Devolution/Nintendont with "Skip IPL" off).

**Comment by carnage702** [comment]
probably some bits or whatever that are set and that this spcifiq games checks on the save file or whatever im guessing. glad you found a workaround.
skip ipl doesnt load the bios which im guessing this game uses to check for some legit codding on boot or whatever, some games had wierd save protection stuff, im guessing this game has some wierd stuff.
