### ISSUE TITLE
Resident Evil 4 black screen after skipping cutscene 

### ISSUE THREAD

**Issue by jksherk** [FIX94/Nintendont#948]
Setting: defaults setting, only turned on wiiu windscreen and memory card emulation

iso: redump

Device: tried Sd card and Sd card reader plug in USB port 

Problem: in stage 1-2, the first time meet village head and fight saw man, I died a lot. When I choose continue, there is a phone call cutsence(I didn’t save in kitchen), I skip that cutscenes, but i randomly get a blackscreen, tried 30 times get 4, need to force shutdown wiiu, any ideas?

**Comment by carnage702** [comment]
when you say default setting there might not be default at all, lots of people think they have default settings when they dont, take a picture of your nintendont settings.

**Comment by jksherk** [comment]
![Uploading 19BABCE7-E7EA-497F-B61B-685649D959CC.jpeg…]()

**Comment by jksherk** [comment]
![63304D80-7ECD-41B2-989E-C9DA0B7B9995](https://user-images.githubusercontent.com/71897861/142040866-e6d50e8d-1933-44ad-a282-94e86de7c5e9.jpeg)

**Comment by jksherk** [comment]
anyway this is the save file if you want to test,https://drive.google.com/file/d/1PINsd2Bc1PG6yISz9YM94UzP7CfcMkzM/view?usp=sharing  RE4 USA version

**Comment by carnage702** [comment]
maybe there is a problem of speed somewhere, try turning unlock read speed to on to see if it bypasses that, maybe its too much data to quickly being asked since you are skipping stuff.

**Comment by jksherk** [comment]
OK, thank you! Will try tomorrow

**Comment by jksherk** [comment]
unlock read speed fix the problem, thanks again!

**Comment by carnage702** [comment]
do recall the sd card slot on wiiu is not well very fast, and if the game asks for too much and your sd card is slow there is chance of crashing, but if you dont skip stuff and have a fast enough sd card  it should be fine, glad it worked, do remember unlocking read speed can have issues on some games where music/audio can get de-synced on some particular games but most re fine with it.
