### ISSUE TITLE
Possible link cable over Wi-Fi connection between 3DS and WiiU

### ISSUE THREAD

**Issue by Lord-Jabu-Jabu** [FIX94/Nintendont#950]
I have no idea if this is possible but the idea would be using the 3DS as a GBA and connecting cover Wi-Fi to the WiiU to have it act like they are connected over a link cable. This would be amazing for a game like four swords adventures! I’ve done a lot of searching and I’m definitely not the first person to think of this but it haven’t seen anyone say why this wouldn’t be possible other then an issue with latency. I’m sure this would be a big project and I don’t expect it to be done but maybe it’s worth asking.

**Comment by carnage702** [comment]
You would need to emulate the  cable protocols and then make an emulator for the 3ds side to meet the requirements and so on, nintendont is open source so if you can or find someone willing to do this codding go on ahead and submit a pull request when done, but i doubt someone would be willing to do it.
