### ISSUE TITLE
Failed to load IOS58 From NAND

### ISSUE THREAD

**Issue by morkmordare** [FIX94/Nintendont#952]
So this is the error I get when installing Nintendont

this is my syscheck everything should be up to date
SysCheck HDE v2.4.0 HacksDen Edition by JoostinOnline, Double_A, R2-D2199, and Nano
...runs on IOS58 (rev 6176).

Region: NTSC-U (original region: JAP)
System Menu 4.3U (v513)
Priiloader installed
Drive date: 12.18.2008
Homebrew Channel 1.1.2 running on IOS58

Hollywood v0x21
Console ID: 90218192
Console Type: Wii
Shop Channel Country: United States (49)
Boot2 v4
Found 68 titles.
Found 47 IOS on this console. 15 of them are stubs.

IOS3 (rev 65280): Stub
IOS4 (rev 65280): Stub
IOS9 (rev 1034): No Patches
IOS10 (rev 768): Stub
IOS11 (rev 256): Stub
IOS12 (rev 526): No Patches
IOS13 (rev 1032): No Patches
IOS14 (rev 1032): No Patches
IOS15 (rev 1032): No Patches
IOS16 (rev 512): Stub
IOS17 (rev 1032): No Patches
IOS20 (rev 256): Stub
IOS21 (rev 1039): No Patches
IOS22 (rev 1294): No Patches
IOS28 (rev 1807): No Patches
IOS30 (rev 2816): Stub
IOS31 (rev 3608): No Patches
IOS33 (rev 3608): No Patches
IOS34 (rev 3608): No Patches
IOS35 (rev 3608): No Patches
IOS36 (rev 3608): No Patches
IOS37 (rev 5663): No Patches
IOS38 (rev 4124): No Patches
IOS40 (rev 3072): Stub
IOS41 (rev 3607): No Patches
IOS43 (rev 3607): No Patches
IOS45 (rev 3607): No Patches
IOS46 (rev 3607): No Patches
IOS48 (rev 4124): No Patches
IOS50 (rev 5120): Stub
IOS51 (rev 4864): Stub
IOS52 (rev 5888): Stub
IOS53 (rev 5663): No Patches
IOS55 (rev 5663): No Patches
IOS56 (rev 5662): No Patches
IOS57 (rev 5919): No Patches
IOS58 (rev 6176): USB 2.0
IOS60 (rev 6400): Stub
IOS61 (rev 5662): No Patches
IOS70 (rev 6912): Stub
IOS80 (rev 6944): No Patches
IOS222 (rev 65280): Stub
IOS223 (rev 65280): Stub
IOS249[57] (rev 65535, Info: d2x-v10beta52): Trucha Bug, NAND Access, USB 2.0
IOS250[56] (rev 65535, Info: d2x-v10beta52): Trucha Bug, NAND Access, USB 2.0
IOS251[38] (rev 65535, Info: d2x-v10beta52): Trucha Bug, ES Identify, NAND Access
IOS254 (rev 65281): BootMii
BC v6
MIOS v10
Report generated on 12/06/2021.
 any ideas

**Comment by carnage702** [comment]
is your homebrew channel ios58 based? on the homebrew channel press  either home or + or 1 and on the top right or left corner will say your homebrew version.

also you got the xml file alongside the boot.dol in the nintendont folder?

**Comment by morkmordare** [comment]
Yeah just installed everything today. Followed the instructions on
wiiguide. And the folder has both the boot.dol and the .xml file I even
tried the xml text from different sources with no change

**Comment by carnage702** [comment]
what about homebrew channel version any picture?

**Comment by carnage702** [comment]
so you have nintendont on sd or usb? maybe try swithing it to another device?

so you got o the homebrew channel and start nintendont what happen does the sd/usb menu pop up? or crashes before that?

**Comment by carnage702** [comment]
make sure your device of nintendont is fat32 formated, when saving the meta.xml you choose save link as so it stays as a xml file and not a txt file, then check your homebrew channel, it should csay what base is running it could be the old ones running on another base.

**Comment by morkmordare** [comment]
Homebrew is version 1.1.2 and the nintendont is on the sd card which was prepared on the Wii on bootmii I believe or whichever portion allowed it to be prepaaired.

**Comment by carnage702** [comment]
> Homebrew is version 1.1.2 and the nintendont is on the sd card which was prepared on the Wii on bootmii I believe or whichever portion allowed it to be prepaaired.

again no picture is hard to accept what it shows...

also i seems you used alot of programs to perpare stuff im guessing there is alot of errors from outdated stuff being prepared...

you should go to your pc and format your sd card to fat32 to make sure then manualy put the apps folder and nintendont folders in there, im guessing some program is not doing things like they did a manual setup is always preffered.

some people got this error due to sd card being badly formated to fat32, their homebrew channel using ios6x instead of 58, having a fake ios58(cios) instead of the original one by nintendo itself, lacking the correct meta.xml filetype and so on.

**Comment by morkmordare** [comment]
I don't understand what you mean by used alot of programs to prepare stuff I simply followed the instructions everything seems to be up to date and everything else works fine. The xml file was saved in the correct format. The ad card was formated by the Wii when I was installing the homebrew channel. I suppose I can run everything again but these are the directions I followed. https://wii.guide/str2hax

**Comment by carnage702** [comment]
> 

im not gonna read an entire hacking setup or guess if its updated or not or if some step is not right.

if nintendont is failling to even reach ios58 on your console then something is wrong with your steps.

if you already have homebrew channel all nintendont needs to run is official iso58 on your wii no cios version of it.

the homebrew channel must be ios58 based, again you dont take a picture of it on your wii so no idea if you messed up when choosing something step.

A fat32 sd/usb with the correct nintendont files.

i cant help you anymore if everything you say is  i used this guide... that doesnt help at all to find the issue, you could have made a mistake following any guide so i have no guarantees you got everything correct in there even.

**Comment by morkmordare** [comment]
I can updating ios58 alone. But my syscheck shows homebrew is running on ios58 version 1.1.2

**Comment by morkmordare** [comment]
![IMG_20211207_190413](https://user-images.githubusercontent.com/95676140/145141418-58be3de8-4fa0-48ae-b356-387c9599281a.jpg)
![IMG_20211207_190518](https://user-images.githubusercontent.com/95676140/145141422-806bfb06-0184-4ccd-840e-35ec9b768c80.jpg)
 This is what's running also tried to load from the USB drive same error

**Comment by morkmordare** [comment]
Got it working

**Comment by carnage702** [comment]
you should post on how you fixed it in-case more people have the same issue.

**Comment by morkmordare** [comment]
No problem. Basically I was following the instructions a bit too literal and the files ended up as meta.xml.xml and boot.dol.dol. same with the game cube games not showing cause I had them as game.iso.iso. so don't put .??? Behind the file name and it will work fine

**Comment by carnage702** [comment]
> No problem. Basically I was following the instructions a bit too literal and the files ended up as meta.xml.xml and boot.dol.dol. same with the game cube games not showing cause I had them as game.iso.iso. so don't put .??? Behind the file name and it will work fine

that is because you have hidden extensions on your pc which hides the extensions, if you change that in the settings you can see and rename extensions on the fly on rename.
