### ISSUE TITLE
Problem With USB drive and Nintendont

### ISSUE THREAD

**Issue by TheEliteSlothie** [FIX94/Nintendont#953]
Basically I'm trying to use Nintendont to play my GameCube Games but I keep getting the error "USB FAT drive can't be opened". If someone can please help with this that would be great!

**Comment by carnage702** [comment]
wii or wiiu?
is your usb device fat32 formated?

**Comment by TheEliteSlothie** [comment]
It's on my Wii and I did try a diffrent drive but that kept corrupting but the one that gave me that error was formatted to FAT32. I may need to reformat it and try it again.

**Comment by carnage702** [comment]
seems to me your using flashdrives, they arent recomended for any homebrew especially nintendont, they fail alot, get too fragmented and then get reading fails, nintendont needs constante data retrieval and fast so flashdrives are very unstable, you should use an hdd or an sd card and forget about using flashdrive for everything homebrew in general.
