### ISSUE TITLE
Triforce issues (Virtua Striker 4 v2006)

### ISSUE THREAD

**Issue by dallenc** [FIX94/Nintendont#954]
Hi,

Am currently using a Black Wii NTSC Console with the system firmware updated to 4.3U, connected to a USB 3.0 WD My Elements 320GB External Hard Disk Drive (no seperate power cable, usb powered) & running the latest version of Nintendont as downloaded here on github. The hdd has been confirmed to work as per the GBATemp compatibility list & formatted to FAT32 using the the latest version of Wii Backup Manager.

Have been trying both the European and Japanese versions of Virtua Striker 4 v2006 - GVS46J & GVS46E and they load with no issues whatsoever.

The problem i do encounter is terrible in-game lag during incidents like a foul, an offside or after a game ends. We're talking 8-10 seconds each time those things happen.

Have tried a mix of loading the games from within USB Loader GX and/or Nintendont direct but it makes no difference. 

I may also like to add that I have no SD card inserted, everything is loaded off the USB powered hdd if that matters.

Am curious if it is an issue with my hdd or others are facing the same? Should I be loading Triforce and/or GameCube via the SD card instead? Wii games seem to work fine without lags.

Thanks.

**Comment by carnage702** [comment]
yes triforce works best from SD slot, triforce was loaded like a cartridge and wii and gc games were loaded like discs so they are built around disk read speeds while triforce was made with cartridge speeds in mind(which means very quick requests and delivery of data on all the data reads, so yeah using an sd card and unlock read speed to yes  on nintendont settings should give you a much better consistency on triforce stuff.

**Comment by dallenc** [comment]
Many thanks!
