### ISSUE TITLE
Mario superstar baseball and Pikmin not working

### ISSUE THREAD

**Issue by TheEliteSlothie** [FIX94/Nintendont#957]
I am having a problem with nintendont. When I run Pikmin the game gets to the Nintendo logo then it says pikmin then the game freezes right when it ends saying pikmin. Then with Mario Baseball I run the game and I press start it loads my save then it shows a black screen. Idk if it's the iso or nintendont but if someone can help me with this that would be great!

**Comment by carnage702** [comment]
take a picture of your nintendont settings, then check your isos md5.

**Comment by TheEliteSlothie** [comment]
![16407878976786184958061439987125](https://user-images.githubusercontent.com/73500181/147672825-4e973925-29ef-4b1a-b8ba-690a3ec8d880.jpg)

**Comment by carnage702** [comment]
> ![16407878976786184958061439987125](https://user-images.githubusercontent.com/73500181/147672825-4e973925-29ef-4b1a-b8ba-690a3ec8d880.jpg)

so you dont even use memory card emulation? if so then your issue for sure are the isos

check your isos md5 you can check it with this program
https://www.mediafire.com/file/5y3tfpoil433rij/MD5_SHA-1_Utility.exe/file

for best compatibility your isos must be full 1.35gb isos and matching redump md5 so check your isos md5 and post them here.
