### ISSUE TITLE
Remove Alpha Dithering?

### ISSUE THREAD

**Issue by kevingliebe** [FIX94/Nintendont#962]
Is there any way to remove Alpha Dithering in nintendont as there is in Swiss?

It really looks awful at times in games like Windwaker.

**Comment by carnage702** [comment]
> Is there any way to remove Alpha Dithering in nintendont as there is in Swiss?
> 
> It really looks awful at times in games like Windwaker.

in nintendont itself no, you can remove deflicker by forcing options but  nothing else, if you want to do anything more than that you either patch your games with gecko codes  or just use swiss on the wii, never saw anyone saying WW looked awful lol.
