### ISSUE TITLE
EUR/PAL games won't read GC Boot iplpal.bin

### ISSUE THREAD

**Issue by danylopez123** [FIX94/Nintendont#963]
I've recently saw how to enable the Gamecube BIOS for the games.
For the USA and JAP games worked fine on reading iplusa.bin and ipljap.bin and have the Gamecube BIOS working with them.
Even for the Triforce games with the segaboot.bin worked as a charm.
But for the PAL games to read them with iplpal.bin? It won't load the Gamecube BIOS at all and i tried this with some PAL games and happens the same thing.
Is there something im missing?

**Comment by carnage702** [comment]
PAL bios does not work on wiiu, due to a missing resolution/hz combination it uses, if you are on wii you can see and use pal bios, on wiiu its disabled due to incompatibility with the system.

**Comment by danylopez123** [comment]
Well.. dam.
Seems that i have no choice with that since a few days ago i got a new Capture Card but only acepts HDMI so i have my Wii U for that.
Oh well, that's alright.
