### ISSUE TITLE
Spongebob Squarepants BFBB emulated memcard does not work

### ISSUE THREAD

**Issue by AJgibhub** [FIX94/Nintendont#964]
ive been trying to play bfbb for a while, but the emulated memcard dosen't seem to work, it worked some time ago, but now it dosen't, everytime i boot the game up it just shows the no memory card inserted sceen, i tried playing it in an another usb stick i had and it showed the same problem, any ideas?

**Comment by carnage702** [comment]
Take a picture of your nintendont settings

**Comment by AJgibhub** [comment]
![i](https://user-images.githubusercontent.com/90291713/150400464-c3efcd27-b108-4434-80a9-fe68efacd3e8.png)

**Comment by carnage702** [comment]
do you start the game directly from nintendont itself or use a loader/forwarder? like usbloadergx/wiiflow/etc?

take a picture of your saves folder btw just want to see what is inside.

**Comment by AJgibhub** [comment]
straight from nintendont
![image](https://user-images.githubusercontent.com/90291713/150422742-7d908832-c078-4e84-a889-8d6d8bbd1df7.png)

**Comment by carnage702** [comment]
well the save file for spongebob is right there GQPE.raw maybe its bad?/corrupt? did you had any saving done? maybe try to delete it and let nintendont creat a new one.

**Comment by AJgibhub** [comment]
i tried what you said with another usb stick and,
it worked! many thanks.
