### ISSUE TITLE
Star Wars Rogue Squadron III graphics corrupted 

### ISSUE THREAD

**Issue by kscorpionx** [FIX94/Nintendont#967]
In the first mission "Revenge of the empire", when starting to play with the x-wing, the graphics under the A button icon show many rainbow lines, instead of the power meter, after the first cutscene it goes back to normal , but then In the second scene, the graphics displayed are corrupted.

**Comment by carnage702** [comment]
this is a known issue the life/shield meter randomly gets corrupted and randomly fixes itself, no one found out why tough, so the chances of being fixed are close to zero.

**Comment by GB-CG** [comment]
Duplicate of https://github.com/FIX94/Nintendont/issues/352

**Comment by carnage702** [comment]
like it said abode its a duplicate issue.
