### ISSUE TITLE
Super Smash Bros. Melee ntsc (v1.02) crash issues

### ISSUE THREAD

**Issue by brandbox23** [FIX94/Nintendont#968]
I have the latest version of nintendont on both wii and wii u, I saw on the compatibility list that the game has an issue when saving in-game on the character select screen causes the freezing of the game, ergo the famous *beeeeep sound and forcing to shutdown the console, I would like to know if this issue is able to be solved on future releases of the emulator, as I've seen that other regions like pal and japan of the game don't have these problems.

**Comment by carnage702** [comment]
> I have the latest version of nintendont on both wii and wii u, I saw on the compatibility list that the game has an issue when saving in-game on the character select screen causes the freezing of the game, ergo the famous *beeeeep sound and forcing to shutdown the console, I would like to know if this issue is able to be solved on future releases of the emulator, as I've seen that other regions like pal and japan of the game don't have these problems.

first off nintendont is not an emulator

second the beep noise is not a crash but a beep when ssbm menu when you pick characters on the css since the game does alot of fast checks and nintendont can beep when doing this same for tales of games, but this does not freeze is a simple beep.

third if you are having actual freezes then you have forced settings that are incompatible with your game or a bad iso, or bad sd/usb, post your nintendont settings with a picture.

**Comment by brandbox23** [comment]
@carnage702 ok well sorry for the wrong term then, the thing is that on the launcher I have all the settings as default, except for cheats for widescreen and to use the c-stick on 1 player, even so, before using cheats I had this issue nonetheless, this doesn't regard a small beep noise every certain amount of time, but once it happens itblast forever and I have to force the shutdown

**Comment by carnage702** [comment]
> @carnage702 ok well sorry for the wrong term then, the thing is that on the launcher I have all the settings as default, except for cheats for widescreen and to use the c-stick on 1 player, even so, before using cheats I had this issue nonetheless, this doesn't regard a small beep noise every certain amount of time, but once it happens itblast forever and I have to force the shutdown. Also the thing is that when I use the 20XX edition, the game doesn't freeze anymore, this is why I don't get it, they are the same version, but one is the official release and the other has an extra mod and it does not present these issues...

take a picture of your nintendont settings, then check your iso md5 the beeps ssbm does are tiny beeps  which dont freeze at all when choosing characters too fast, that is why the game is green, if the game just hard-locked for everyone randomly it wouldn't be green.

**Comment by brandbox23** [comment]
@carnage702 
![20220201_222804](https://user-images.githubusercontent.com/82955607/152054487-150e9072-223e-42a6-9f29-9548cdbbcd32.jpg)
Hi, sorry for responding 4 days later... anyway these are my settings for both wii and wii u on nintendont

**Comment by carnage702** [comment]
turn off cheats and put width to auto, width is also a hack that can crash games, might as well turn off arcade mode and wiimote rumble too.

if the game still crashes then check your iso md5 compare it to redump
use this https://www.mediafire.com/file/5y3tfpoil433rij/MD5_SHA-1_Utility.exe/file

ssb, usa md5 must match one of this
3a62f8d10fd210d4928ad37e3816e33c
0e63d4223b01d9aba596259dc155a174

**Comment by brandbox23** [comment]
Ok I checked it and is correct it has this 0e63d4223b01d9aba596259dc155a174
I'll try turning off those features you've mentioned
