### ISSUE TITLE
Animal Crossing Pal NTSC Patch

### ISSUE THREAD

**Issue by POK3DEXTEUR** [FIX94/Nintendont#969]
Hi, I try to play at Animal Crossing at Gamecube Pal on my Wii with the Ntsc Video Patch but I have a black screen with the sound... A Solution ?

**Comment by carnage702** [comment]
not all games support being forced to other video settings besides their default ones, if your getting black screen then your tv does not support the videomode, animal crossing came out on every region so get one version that works on your tv.

**Comment by POK3DEXTEUR** [comment]
I want play to this version for the French translation :(
