### ISSUE TITLE
Feature request: Bypass "Checking storage devices" at every launch of Nintendont

### ISSUE THREAD

**Issue by shar33f** [FIX94/Nintendont#971]
Hi guys, I am running Nintendont on my Wii and absolutely loving it! I was just wondering if there is a way to bypass the "Checking storage devices" message and have Nintendont default to my SD card since everything is always stored on my SD card. This would save a few seconds during startup. I've searched and could not find a way to do this. I'm hoping there's a config file or some way to set a flag so it knows always use the same device (SD card) rather than scanning all ports and giving the option to choose a one. TIA!

**Comment by carnage702** [comment]
that already exists its called using a loader. if you use usbloadergx or wiiflow you can pick a game and it will start, nintendont used directly wont ever have any setting to remove the checking.

**Comment by shar33f** [comment]
> that already exists its called using a loader. if you use usbloadergx or wiiflow you can pick a game and it will start, nintendont used directly wont ever have any setting to remove the checking.

Yes, I'm well aware I can use Nintendont that way, but I don't use a loader. I much prefer the simple UI of Nintendont over the loaders :). I'm using Priiloader at startup to start the Homebrew Channel and then loading Nintendont from there, so I was hoping to shave a few seconds waiting at every launch but no big deal.
