### ISSUE TITLE
Resident Evil 4 is crashing or freezing at any given point when a transition happens.

### ISSUE THREAD

**Issue by BENEMERITO** [FIX94/Nintendont#972]
Just like that, really, and it's been a problem forever that has affected every version of the game, although the european release is the worst offender. It only happens when the game loads a new level and the trasnmission screen or a cutscene kicks in. I checked the reported issues section and I discovered that there is no mention of this, so I figured.

**Comment by carnage702** [comment]
take a picture of your nintendont settings, i played the entire re4 on nintendont like 4 years ago and never had any crash myself.

**Comment by BENEMERITO** [comment]
![IMG_20220213_002606](https://user-images.githubusercontent.com/26521150/153741839-d41f11b0-789c-41a0-96ca-0e15834e4a24.jpg)

**Comment by carnage702** [comment]
settings seems fine im guessing it could be 2 issues

1- iso is not good,  are you using a full 1.35gb iso with md5 matching redump?
2- your sd/usb that might be slow or just too fragmented you can pass your stuff to your pc format your device and then pass them back or try turning unlock read speed to on to see if it helps you.

**Comment by BENEMERITO** [comment]
i always stick to games in iso format, wich i get from archive.org. re4 is the only game i have ever encuntered a problem with. the issue seems aggavated when using a dualshock 4 (v2) as a controller too.

**Comment by BENEMERITO** [comment]
well, just as a wrap up, i unlocked the reading speed and now the european version is working perfectly fine during the couple hours i played today. i never bothered to tweak the configuration options since i can always play the wii release, though.
