### ISSUE TITLE
pac man world 2 nintendont freeze

### ISSUE THREAD

**Issue by LittleHooligan74** [FIX94/Nintendont#978]
Pacman world 2 on my Wii u freezes 10 minutes later with a loud buzz, so I updated Nintendont to the latest version, and freeze still happens

1. the game was injected from Teconmoon's  WiiVC injector
2. the game is converted to nkit.iso
3. I have Wii u widescreen enabled
4. not sure if other games (like sonic riders and paper Mario, or shadow) will freeze

**Comment by carnage702** [comment]
Each game is singular.

EVERY FORCED SETTING can lead to a crash depending on the game

To get perfect compatibility you should

1- use full 1.35gb isos with md5 matching redump not nkit.iso
2- you should force no settings except memory card emulation, any other setting can freeze depending on the game, so forced widescreen,forced width,forced videomodes,forced progressive and more can cause a game to crash., any setting besides memory crd emulation has the ability to crash games depending on  how they are codded.
