### ISSUE TITLE
Tom and Jerry in war of the wiskers GC don't work

### ISSUE THREAD

**Issue by Harol030** [FIX94/Nintendont#979]
when activating the progressive mode or also emulating a memcard (of any size) the game does not start or cannot be seen it can only be played if the progressive mode and the memcard are deactivated... which is impossible to make it playable since the screen appears small and cannot be played properly...

**Comment by carnage702** [comment]
take a picture of your nintendont settings and then check your iso md5

**Comment by Harol030** [comment]
> tome una foto de la configuración de su nintendont y luego verifique su iso md5
I use the default settings and have only used the progressive and memcard emulation mode options.

**Comment by carnage702** [comment]
> > tome una foto de la configuración de su nintendont y luego verifique su iso md5
> > I use the default settings and have only used the progressive and memcard emulation mode options.
> > And i already verified MD5

that is what people think they use... many times they think they have default and they dont... just take a picture.
