### ISSUE TITLE
DS3 and DS4 button mapping suggestion

### ISSUE THREAD

**Issue by Tw5EjGDE** [FIX94/Nintendont#984]
At the moment the DS3 and DS4 are mapped to the SNES button layout.
I understand that with the Classic Controller you may want the buttons to match the labels, but on the DualShock it doesn't match regardless.
I think it would make more sense to rotate the button mappings 90 degrees to closer match the GameCube layout.
So instead of looking like this:
```

  X
Y   A
  B
```
It would look like this:
```
  Y
B   X
  A
```
This way, instead of jump being on circle for example, it would be on cross.

**Comment by carnage702** [comment]
both ds3 and ds4 are hid controllers which means you can make your own  mapping by editing the controller ini files.

https://github.com/FIX94/Nintendont/tree/master/controllerconfigs

grab your corresponding ini file  open it with notepad change the button you want and save, then rename to "controller.ini" and place it on the root of your usb or sd depending where you have your isos.
