### ISSUE TITLE
Saving data issues on hdd

### ISSUE THREAD

**Issue by brandbox23** [FIX94/Nintendont#985]
Hi, here I am again with a new issue, the other one regarding crashes on ssbm is solved, on wii I switched from a usb stick, to an hdd seagate of 1tb on fat32 using guiformat, but I discovered an issue, idk if this happens because of compatibility with the hdd, but while playing smash bros melee, it seems that because the game constantly saves data on every match ending or change of settings, after a certain amount of time, when a battle ends, it gets stuck on the GAME! Screen, I can listen the winner character music but nothing else, what's interesting though is that the game remains frozen, but it doesn't crash, as I can exit the loader using the combo buttons to return to the hb channel, I would like to know if there's a solution to that

**Comment by brandbox23** [comment]
@carnage702 I began playing it from sd a long time ago before using a usb or hdd and I never had this issue, so it could be about sleep mode.
I'll try checking on my hdd if sleep mode is on, if so, then if I disable it from pc when I plug it again on my wii, the sleep mode will remain as off??

**Comment by carnage702** [comment]
> @carnage702 I began playing it from sd a long time ago before using a usb or hdd and I never had this issue, so it could be about sleep mode. I'll try checking on my hdd if sleep mode is on, if so, then if I disable it from pc when I plug it again on my wii, the sleep mode will remain as off??

yeah  but some manufacturers have it hidden to its tricky to find the sleep mode and even trickier to disable it.

**Comment by brandbox23** [comment]
@carnage702 I've disabled sleep mode of the hdd through my computer, still, when I first booted the launcher, while playing after few minutes the game crashed in game, so I tried a second time, and there were no problems... until again after idk maybe 20 minutes, the game remained again on the GAME! screen

**Comment by carnage702** [comment]
like i said i never saw anyone with this issue, if you have everything and i mean everything off or auto except memory card emulation and are running latest 498 nintendont everything should work fine, i advice on getting the game on the sd card and try it from there, if this doesnt happen from sd card then it might be an issue with your hdd, either some bad compatibility issue with nintendont or soemthing along those lines.

**Comment by weirdal3333** [comment]
Just double checking on this... You formatted it with 64kb allocation unit size, right? the default settings for formatting on windows may make drives slow and unresponsive. a 64kb allocation unit size may fix this issue on drives larger than 128GB
