### ISSUE TITLE
Black screen If connect Dualshock3 with cable before play gamecube vc game (injection method made in Wiiu helper) 

### ISSUE THREAD

**Issue by bbking26** [FIX94/Nintendont#986]
It's will show black screen after  nintendont memory initial 
btw that working fine if connect ds3 controller after game is show up
not sure this from boolpair or something else.
Nintendont version 6.498

**Comment by carnage702** [comment]
i remneber some old injecters have this problem, maybe the one in usbhelper is outdated and you need to make an inject with a more up to date injector.
