### ISSUE TITLE
"Failed to load IOS58 from NAND"

### ISSUE THREAD

**Issue by MrPedson** [FIX94/Nintendont#987]
![20220310_181531](https://user-images.githubusercontent.com/101358865/157734938-f8e5d4cd-e4f3-4300-b865-287480b7ea40.jpg)
I have checked it, it does have that line
(If it helps I'm on the vwii)

**Comment by hurda** [comment]
Been discussed before multiple times: https://github.com/FIX94/Nintendont/search?q=ios58+nand&type=issues
Maybe anything posted in these can help you, especially the stuff about the full filename of meta.xml being different than that.

**Comment by MrPedson** [comment]
Thanks! I found my problem I accidentally turned it into a .txt file instead of .xml lol
