### ISSUE TITLE
Nintendont "failed to load kernel from NAND", when launched with WiiU inject

### ISSUE THREAD

**Issue by fazzefazze** [FIX94/Nintendont#990]
I tried both injecting separate GC games, and injecting Nintendont itself to the WiiU Menu, but it still displays same error message, and goes back to WiiU menu. Despite this, it works from vWii. 
What problem can this be?

**Comment by carnage702** [comment]
where is nintendont stored? usb or sd?

**Comment by fazzefazze** [comment]
> where is nintendont stored? usb or sd?

SD

**Comment by fazzefazze** [comment]
I solved my issue my reformatting SD card, and installing Nintendont with WiiU injector again. Thanks!
