### ISSUE TITLE
Tv says resolution not supported

### ISSUE THREAD

**Issue by Zlundberg12** [FIX94/Nintendont#998]
Tried loading up the sims US version and my TV says resolution not supported. My TV AFAIK does 480i to 1080p and everything in between and haven't had this problem before. I am using the og wii nintendont on vwii on wii u. It displays just fine on the gamepad. I also have nintendont with gamepad support and all of the settings are the same between the 2 but the gamepad supported version displays onto the TV just fine. I just want to get it to work on both versions of nintendont please any help is appreciated

**Comment by carnage702** [comment]
what do you want me to do? nintendont doesnt change the resolution of games only the videomode, for example megaman collection runs at 240p  or something similar, not all games run at 480i/480p.  some games run at wierd resolutions, try the pal version to see if its different if it still says the same you can always just use the gamepad or try another tv in your house.
